import {describe,it,expect,vi} from 'vitest';
import {parseBookingDetail} from '../src/bookingDetail';
import {createRuntimeClient} from '../src/index';
const T='11111111-1111-4111-8111-111111111111',B='22222222-2222-4222-8222-222222222222',S='33333333-3333-4333-8333-333333333333',C='44444444-4444-4444-8444-444444444444',P='55555555-5555-4555-8555-555555555555';
const row=()=>({id:B,tenant_id:T,reference:'LMN-TEST',state:'confirmed',slot_start:'2030-01-01T12:00:00Z',slot_end:'2030-01-01T13:00:00Z',created_at:'2029-01-01T12:00:00Z',selection:{serviceId:S},pricing:{total:{amount:12500,currency:'USD'},deposit:{amount:0,currency:'USD'}},customer_id:C,customer:{id:C,tenant_id:T,name:'Test customer',email:'customer@example.test',phone:null},payment_id:P,payment:{id:P,booking_id:B,tenant_id:T,state:'succeeded',amount:12500,currency:'USD',provider:'mock'},address:null,notes:null,history:[{booking_id:B,from_state:null,to_state:'draft',reason:'created',at:'2029-01-01T12:00:00Z'}]});
describe('connected booking detail boundary',()=>{
 it('returns stored money and customer; empty pricing stays unpriced',()=>{expect(parseBookingDetail([row()],T,B)?.total?.amount).toBe(12500);expect(parseBookingDetail([{...row(),pricing:{}}],T,B)?.total).toBeNull();expect(parseBookingDetail([],T,B)).toBeNull()});
 it.each(['parent','customer','payment','history'])('rejects foreign %s binding',part=>{const r=row();if(part==='parent')r.tenant_id=B;if(part==='customer')r.customer.tenant_id=B;if(part==='payment')r.payment.booking_id=C;if(part==='history')r.history[0]!.booking_id=C;expect(()=>parseBookingDetail([r],T,B)).toThrow('verified')});
 it('rejects unsafe money and mismatched currencies',()=>{for(const amount of [-1,1.5,Number.MAX_SAFE_INTEGER+1]){const r=row();r.pricing.total.amount=amount;expect(()=>parseBookingDetail([r],T,B)).toThrow()}const r=row();r.payment.currency='EUR';expect(()=>parseBookingDetail([r],T,B)).toThrow()});
 it('supports partial refunds without inventing net amounts',()=>{const r=row();r.payment.state='partially_refunded';expect(parseBookingDetail([r],T,B)?.payment?.state).toBe('partially_refunded')});
 it('retains a separate refundable rental deposit larger than the booking charge',()=>{const r=row();r.pricing.deposit.amount=50000;expect(parseBookingDetail([r],T,B)?.deposit?.amount).toBe(50000)});
 it('requires login and sends both tenant and booking filters',async()=>{const responses=[{access_token:'synthetic'}, {id:C}, [row()]];const f=vi.fn<typeof fetch>(async()=>new Response(JSON.stringify(responses.shift()),{status:200}));const c=createRuntimeClient({url:'https://example.supabase.co',publishableKey:'sb_publishable_fixture',tenantId:T},f);await expect(c.bookingDetail(T,B)).rejects.toThrow('sign in');expect(f).not.toHaveBeenCalled();await c.signIn('fixture@example.test','fixture');await c.bookingDetail(T,B);expect(String(f.mock.calls[2]![0])).toContain(`tenant_id=eq.${T}&id=eq.${B}`);expect(f.mock.calls[2]![1]!.headers).toMatchObject({Authorization:'Bearer synthetic'});c.signOut();await expect(c.bookingDetail(T,B)).rejects.toThrow('sign in')});
});
