import {it,expect,vi} from 'vitest';
import {createRuntimeClient} from '../src/index';
const T='11111111-1111-4111-8111-111111111111',B='22222222-2222-4222-8222-222222222222',U='33333333-3333-4333-8333-333333333333',F='44444444-4444-4444-8444-444444444444';
const receipt={schemaVersion:1,tenantId:T,bookingId:B,channels:[{channel:'email',receiptRecorded:true},{channel:'sms',receiptRecorded:false}]};
const json=(value:unknown,status=200)=>new Response(JSON.stringify(value),{status});
function fixture({members=[{tenant_id:T,role:'BUSINESS_OWNER'}],reply=async()=>json({ok:true,data:receipt}),membershipRead}:{members?:unknown;reply?:()=>Promise<Response>;membershipRead?:()=>Promise<Response>}={}){let actor=U;const transport=vi.fn<typeof fetch>(async input=>{const path=String(input);if(path.includes('/token?'))return json({access_token:'synthetic-owner-private-token'});if(path.endsWith('/user'))return json({id:actor});if(path.includes('/tenant_members?'))return membershipRead?membershipRead():json(members);if(path.includes('/api/confirmation-receipts?'))return reply();throw Error('Unexpected transport');});return{transport,client:createRuntimeClient({url:'https://example.supabase.co',publishableKey:'sb_publishable_synthetic_fixture',tenantId:T,allowMembershipDiscovery:true,bookingApiOrigin:'https://api.example.test'},transport),actor:(id:string)=>{actor=id;}};}
const calls=(x:ReturnType<typeof fixture>)=>x.transport.mock.calls.filter(([url])=>String(url).includes('/api/confirmation-receipts?'));
it('uses explicit fresh-owner GET with exact canonical scope and records only ordered existence flags',async()=>{const x=fixture();await x.client.signIn('owner@example.test','synthetic');expect(await x.client.readConfirmationReceiptStatus(T.toUpperCase(),B.toUpperCase())).toEqual(receipt);expect(calls(x)[0]).toEqual(['https://api.example.test/api/confirmation-receipts?tenantId='+T+'&bookingId='+B,expect.objectContaining({method:'GET',credentials:'omit',redirect:'error',cache:'no-store',referrerPolicy:'no-referrer',headers:{Authorization:'Bearer synthetic-owner-private-token'}})]);expect(calls(x)[0]![1]).not.toHaveProperty('body');expect(JSON.stringify(receipt)).not.toMatch(/sent|delivered|provider|timestamp|recipient|synthetic-owner-private-token/i);await x.client.readConfirmationReceiptStatus(T,B);expect(calls(x)).toHaveLength(2);});
it('no automatic receipt request, unsigned request or widened query is possible',async()=>{const x=fixture();expect(x.transport).not.toHaveBeenCalled();await expect(x.client.readConfirmationReceiptStatus(T,B)).rejects.toMatchObject({code:'UNAUTHENTICATED'});await x.client.signIn('owner@example.test','synthetic');for(const [tenant,booking] of [[T+'&role=owner',B],[T,B+'&actor='+U],['forged',B],[T,'forged']])await expect(x.client.readConfirmationReceiptStatus(tenant!,booking!)).rejects.toMatchObject({code:'INVALID_REQUEST'});expect(calls(x)).toHaveLength(0);});
it.each([[],[{tenant_id:T,role:'BUSINESS_STAFF'}],[{tenant_id:F,role:'BUSINESS_OWNER'}],[{tenant_id:T,role:'BUSINESS_OWNER',extra:true}]].map(members=>({members})))('requires fresh exact-owner membership before receipt HTTP',async({members})=>{const x=fixture({members});await x.client.signIn('owner@example.test','synthetic');await expect(x.client.readConfirmationReceiptStatus(T,B)).rejects.toMatchObject({code:'FORBIDDEN'});expect(calls(x)).toHaveLength(0);});
it.each([{...receipt,tenantId:F},{...receipt,bookingId:F},{...receipt,channels:[...receipt.channels].reverse()},{...receipt,channels:[receipt.channels[0]]},{...receipt,channels:[receipt.channels[0],receipt.channels[0]]},{...receipt,channels:[{channel:'email',receiptRecorded:'true'},receipt.channels[1]]},{...receipt,channels:[{...receipt.channels[0],deliveryConfirmed:true},receipt.channels[1]]},{...receipt,provider:'mock'},null])('rejects foreign/malformed/widened snapshots rather than inventing receipt flags',async data=>{const x=fixture({reply:async()=>json({ok:true,data})});await x.client.signIn('owner@example.test','synthetic');await expect(x.client.readConfirmationReceiptStatus(T,B)).rejects.toMatchObject({code:'UNVERIFIED'});expect(calls(x)).toHaveLength(1);});
it.each([[403,'FORBIDDEN'],[404,'NOT_AVAILABLE'],[422,'UNSUPPORTED_CONFIG']] as const)('reports strict error %s without defaults or retry',async(status,code)=>{const x=fixture({reply:async()=>json({ok:false,code},status)});await x.client.signIn('owner@example.test','synthetic');await expect(x.client.readConfirmationReceiptStatus(T,B)).rejects.toMatchObject({code});expect(calls(x)).toHaveLength(1);});
it('network/provider errors remain generic and never send a writer or retry',async()=>{const x=fixture({reply:async()=>{throw Error('PRIVATE_PROVIDER_SECRET');}});await x.client.signIn('owner@example.test','synthetic');await expect(x.client.readConfirmationReceiptStatus(T,B)).rejects.toThrow('Receipt recording status could not be verified.');expect(calls(x)).toHaveLength(1);expect(calls(x)[0]![1]?.method).toBe('GET');});
it.each(['','<html>expired</html>','{malformed'])('invalidates current401 before parsing body %s',async body=>{const x=fixture({reply:async()=>new Response(body,{status:401})});await x.client.signIn('owner@example.test','synthetic');const at=x.client.authContextRevision();await expect(x.client.readConfirmationReceiptStatus(T,B)).rejects.toMatchObject({code:'UNAUTHENTICATED'});expect(x.client.authContextRevision()).toBeGreaterThan(at);await expect(x.client.readConfirmationReceiptStatus(T,B)).rejects.toMatchObject({code:'UNAUTHENTICATED'});expect(calls(x)).toHaveLength(1);});
it.each(['','<html>expired</html>','{malformed'])('late401 body %s never signs out a same-actor replacement session',async body=>{let finish!:(value:Response)=>void;const x=fixture({reply:()=>new Promise(resolve=>finish=resolve)});await x.client.signIn('owner@example.test','synthetic');const pending=x.client.readConfirmationReceiptStatus(T,B);await vi.waitFor(()=>expect(finish).toBeTypeOf('function'));x.client.signOut();await x.client.signIn('owner@example.test','synthetic');const at=x.client.authContextRevision();finish(new Response(body,{status:401}));await expect(pending).rejects.toMatchObject({code:'STALE_CONTEXT'});expect(x.client.authContextRevision()).toBe(at);expect(await x.client.memberships()).toEqual([{tenant_id:T,role:'BUSINESS_OWNER'}]);});
it('denies late foreign-actor success and preserves replacement authentication',async()=>{let finish!:(value:Response)=>void;const x=fixture({reply:()=>new Promise(resolve=>finish=resolve)});await x.client.signIn('owner@example.test','synthetic');const pending=x.client.readConfirmationReceiptStatus(T,B);await vi.waitFor(()=>expect(finish).toBeTypeOf('function'));x.client.signOut();x.actor(F);await x.client.signIn('owner2@example.test','synthetic');const at=x.client.authContextRevision();finish(json({ok:true,data:receipt}));await expect(pending).rejects.toMatchObject({code:'STALE_CONTEXT'});expect(x.client.authContextRevision()).toBe(at);});
it('signout during membership lookup prevents the receipt request',async()=>{let finish!:(value:Response)=>void;const x=fixture({membershipRead:()=>new Promise(resolve=>finish=resolve)});await x.client.signIn('owner@example.test','synthetic');const pending=x.client.readConfirmationReceiptStatus(T,B);x.client.signOut();finish(json([{tenant_id:T,role:'BUSINESS_OWNER'}]));await expect(pending).rejects.toMatchObject({code:'STALE_CONTEXT'});expect(calls(x)).toHaveLength(0);});
it('auth replacement during JSON parsing suppresses the parsed snapshot',async()=>{let finish!:(value:unknown)=>void;const response=json({ok:true,data:receipt});vi.spyOn(response,'json').mockImplementation(()=>new Promise(resolve=>finish=resolve));const x=fixture({reply:async()=>response});await x.client.signIn('owner@example.test','synthetic');const pending=x.client.readConfirmationReceiptStatus(T,B);await vi.waitFor(()=>expect(finish).toBeTypeOf('function'));x.client.signOut();await x.client.signIn('owner@example.test','synthetic');finish({ok:true,data:receipt});await expect(pending).rejects.toMatchObject({code:'STALE_CONTEXT'});});
