import {it,expect,vi} from 'vitest';
import {createDetailingCustomerClient} from '../src/detailing-customer';
import {createFlowHttpServer} from '../../../apps/api/src/http';
import type {DetailingReservationInput} from '@lumin/contracts';
const id='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222',token='t'.repeat(43),expiresAt='2035-01-01T00:00:00Z';
const catalog={name:'Detailing',description:'Published description',currency:'USD',durationMinutes:30,packages:[{id:'basic',label:'Basic',amount:1000}],vehicles:[{id:'car',label:'Car',multiplierBp:10000}],addons:[],locations:[]};
const render={versionId:id,renderSchemaVersion:7,businessType:'AUTO_DETAILING',submissionMode:'detailing_quote',bookingMode:'unavailable',paymentMode:'unavailable',pricingModel:'package_subtotal_vehicle_multiplier',serviceId:id,catalog,publication:{name:'Published detailing',presentation:{accentColor:'#4f46e5',layout:'stacked'},draftRevision:1}};
const selection={packageId:'basic',vehicleId:'car',addonIds:[]};const money=(amount:number)=>({amount,currency:'USD'});
const receipt={schemaVersion:1,versionId:id,installationId:id,serviceId:id,expiresAt,selection,pricingModel:'package_subtotal_vehicle_multiplier',bookingMode:'unavailable',paymentMode:'unavailable',pricing:{lines:[{code:'package',label:'Basic',quantity:1,amount:money(1000)}],subtotal:money(1000),tax:money(0),deposit:money(0),total:money(1000)}};
const json=(data:unknown)=>new Response(JSON.stringify({ok:true,data}));
it('uses private dedicated transport and server receipts with no browser-calculated total',async()=>{const fetcher=vi.fn(async(url:string)=>json(url.includes('/quote')?receipt:{sessionToken:token,expiresAt,render}));const client=createDetailingCustomerClient('https://api.example',false,fetcher as typeof fetch);await client.session(id);expect(await client.quote(selection)).toEqual(receipt);expect(fetcher.mock.calls[1]![0]).toBe('https://api.example/api/detailing-flow-sessions/quote');expect((fetcher.mock.calls as unknown as [string,RequestInit][])[1]![1]).toMatchObject({credentials:'omit',redirect:'error',cache:'no-store',referrerPolicy:'no-referrer',headers:{Authorization:'Bearer '+token},body:JSON.stringify(selection)});});
it.each(['version','installation','service','expiry','selection','currency','extra'] as const)('rejects malformed or foreign %s quote',async field=>{const changed=field==='version'?{...receipt,versionId:other}:field==='installation'?{...receipt,installationId:other}:field==='service'?{...receipt,serviceId:other}:field==='expiry'?{...receipt,expiresAt:'2036-01-01T00:00:00Z'}:field==='selection'?{...receipt,selection:{...selection,packageId:'foreign'}}:field==='currency'?{...receipt,pricing:{...receipt.pricing,total:{amount:1000,currency:'EUR'}}}:{...receipt,secret:'unexpected'};const client=createDetailingCustomerClient('https://api.example',false,vi.fn(async url=>json(String(url).includes('/quote')?changed:{sessionToken:token,expiresAt,render})));await client.session(id);await expect(client.quote(selection)).rejects.toThrow('could not be verified');});
it('rejects unknown catalog choices before transport and drops late responses after invalidation',async()=>{let finish!:(r:Response)=>void;const fetcher=vi.fn(async url=>String(url).includes('/quote')?new Promise<Response>(resolve=>finish=resolve):json({sessionToken:token,expiresAt,render}));const client=createDetailingCustomerClient('https://api.example',false,fetcher);await client.session(id);await expect(client.quote({...selection,addonIds:['unknown']})).rejects.toThrow();expect(fetcher).toHaveBeenCalledTimes(1);const request=client.quote(selection);client.invalidate();finish(json(receipt));await expect(request).rejects.toThrow('expired');});
it.each(['https://user:secret@api.example','https://api.example/path','https://api.example?token=secret','http://api.example','javascript:alert(1)'])('rejects unsafe origin %s before transport',origin=>{expect(()=>createDetailingCustomerClient(origin)).toThrow();});
it('validates availability provenance, duration and bounded slots',async()=>{let value={schemaVersion:1,versionId:id,installationId:id,serviceId:id,expiresAt,durationMinutes:30,timezone:'America/Los_Angeles',slots:[{start:'2030-01-01T10:00:00.000Z',end:'2030-01-01T10:30:00.000Z',remainingCapacity:1}]};const client=createDetailingCustomerClient('https://api.example',false,vi.fn(async url=>json(String(url).includes('/availability')?value:{sessionToken:token,expiresAt,render})));await client.session(id);const q={from:'2030-01-01T00:00:00.000Z',to:'2030-01-02T00:00:00.000Z'};expect(await client.availability(q)).toEqual(value);value={...value,serviceId:other};await expect(client.availability(q)).rejects.toThrow();value={...value,serviceId:id,durationMinutes:45};await expect(client.availability(q)).rejects.toThrow();});
it('crosses the accepted HTTP boundary with exact origin and hashed bearer, while legacy RPC stays untouched',async()=>{
 const origin='https://checkout.example.test',legacy=vi.fn(),session=vi.fn(async()=>({render,expiresAt})),price=vi.fn(async()=>receipt),slots=vi.fn(async()=>({schemaVersion:1 as const,versionId:id,installationId:id,serviceId:id,expiresAt,durationMinutes:30,timezone:'America/Los_Angeles',slots:[]}));
 const server=createFlowHttpServer({repository:{call:legacy},customerOrigins:[origin],ownerOrigins:[],detailingPublication:true,detailingAvailability:slots,detailingPublicationApi:{session,quote:price,save:vi.fn(),read:vi.fn(),publish:vi.fn(),recover:vi.fn()} as never});
 await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));
 try{const address=server.address();if(!address||typeof address==='string')throw Error('Missing loopback address');const base='http://127.0.0.1:'+address.port;
  const transport:typeof fetch=(url,options)=>fetch(url,{...options,headers:{...options?.headers,Origin:origin}});
  const client=createDetailingCustomerClient(base,true,transport);await client.session(id);expect(await client.quote(selection)).toEqual(receipt);await client.availability({from:'2030-01-01T00:00:00.000Z',to:'2030-01-02T00:00:00.000Z'});
  expect(session).toHaveBeenCalledWith(id,expect.stringMatching(/^[0-9a-f]{64}$/),origin);expect(price).toHaveBeenCalledWith(expect.stringMatching(/^[0-9a-f]{64}$/),origin,selection);expect(slots).toHaveBeenCalledWith(expect.stringMatching(/^[0-9a-f]{64}$/),origin,expect.any(Object));expect(legacy).not.toHaveBeenCalled();
  const foreign=createDetailingCustomerClient(base,true,(url,options)=>fetch(url,{...options,headers:{...options?.headers,Origin:'https://foreign.example'}}));await expect(foreign.session(id)).rejects.toThrow();expect(session).toHaveBeenCalledTimes(1);
 }finally{server.closeAllConnections();await new Promise<void>(resolve=>server.close(()=>resolve()));}
});
let reservationNumber=100;
async function reservationFixture(action?:(path:string,body:unknown)=>Promise<Response>){
 const installation='99000000-0000-4000-8000-'+String(++reservationNumber).padStart(12,'0'),booking='99000000-0000-4000-8000-'+String(++reservationNumber).padStart(12,'0');
 const from='2030-01-01T00:00:00.000Z',to='2030-01-02T00:00:00.000Z',slot={start:'2030-01-01T10:00:00.000Z',end:'2030-01-01T10:30:00.000Z',remainingCapacity:1};
 const requested={schemaVersion:1,versionId:id,installationId:installation,serviceId:id,bookingId:booking,reference:'LMN-ABC123',selection,pricing:receipt.pricing,slot:{start:slot.start,end:slot.end},state:'draft',confirmed:false,paymentMode:'unavailable'};
 const reserved={schemaVersion:1,versionId:id,installationId:installation,serviceId:id,bookingId:booking,holdId:other,status:'active',expiresAt:'2030-01-01T09:59:00.000Z'};
 const fetcher=vi.fn(async(url:string,options?:RequestInit)=>{if(url.includes('/request')||url.includes('/hold'))return action?action(url,JSON.parse(String(options?.body))):json(url.includes('/request')?requested:reserved);if(url.includes('/quote'))return json({...receipt,installationId:installation});if(url.includes('/availability'))return json({schemaVersion:1,versionId:id,installationId:installation,serviceId:id,expiresAt,durationMinutes:30,timezone:'America/Los_Angeles',slots:[slot]});return json({sessionToken:token,expiresAt,render});});
 const client=createDetailingCustomerClient('https://api.example',false,fetcher as typeof fetch);await client.session(installation);await client.quote(selection);await client.availability({from,to});
 const body:DetailingReservationInput={schemaVersion:1,idempotencyKey:'frozen-request-operation-0001',selection,customer:{name:'Fictional customer',email:'fictional@example.test'},requestedStart:slot.start};return{client,fetcher,body,requested,reserved,installation};
}
it('submits only the frozen selection/customer/time and reserves only persisted exact request, with same active hold replay',async()=>{const x=await reservationFixture();expect(await x.client.request(x.body)).toEqual(x.requested);expect(x.client.operation().phase).toBe('saved');expect(await x.client.hold()).toEqual(x.reserved);expect(await x.client.hold()).toEqual(x.reserved);const writes=x.fetcher.mock.calls.filter(([url])=>url.includes('/request')||url.includes('/hold'));expect(writes.map(([u])=>u.split('/').at(-1))).toEqual(['request','hold','hold']);expect(JSON.parse(String(writes[0]![1]?.body))).toEqual(x.body);expect(writes[0]![1]).toMatchObject({headers:{Authorization:'Bearer '+token},credentials:'omit',redirect:'error'});expect(writes[1]![1]?.body).toBe('{}');expect(x.client.operation().phase).toBe('held');});
it('a lost request receipt freezes body/key, forbids sibling edits and new issuer, and permits only explicit identical replay',async()=>{let calls=0;const x=await reservationFixture(async()=>{if(++calls===1)throw Error('private lost response');return json(x.requested);});await expect(x.client.request(x.body)).rejects.toThrow();expect(x.client.operation().phase).toBe('request_unknown');const before=x.fetcher.mock.calls.length;await expect(x.client.request({...x.body,idempotencyKey:'different-request-key-0001'})).rejects.toThrow();await expect(x.client.quote(selection)).rejects.toThrow();expect(()=>x.client.clearSelection()).toThrow();expect(x.fetcher).toHaveBeenCalledTimes(before);x.client.invalidate();const second=createDetailingCustomerClient('https://api.example',false,x.fetcher as typeof fetch);await second.session(x.installation);expect(x.fetcher).toHaveBeenCalledTimes(before);expect(await second.request(x.body)).toEqual(x.requested);const writes=x.fetcher.mock.calls.filter(([u])=>u.includes('/request'));expect(writes[0]![1]?.body).toBe(writes[1]![1]?.body);});
it('rejects an ambiguous request with substituted but internally valid server pricing and keeps the write locked',async()=>{const x=await reservationFixture(async()=>json({...x.requested,pricing:{...x.requested.pricing,lines:[{code:'package',label:'Basic',quantity:1,amount:money(999)}],subtotal:money(999),total:money(999)}}));await expect(x.client.request(x.body)).rejects.toThrow();expect(x.client.operation().phase).toBe('request_unknown');await expect(x.client.hold()).rejects.toThrow();});
it('a lost hold result stays unverified until explicit same-request replay and never creates a payment',async()=>{let holds=0;const x=await reservationFixture(async path=>{if(path.includes('/request'))return json(x.requested);if(++holds===1)throw Error('lost private hold');return json(x.reserved);});await x.client.request(x.body);await expect(x.client.hold()).rejects.toThrow();expect(x.client.operation().phase).toBe('hold_unknown');expect(await x.client.hold()).toEqual(x.reserved);expect(x.client.operation().phase).toBe('held');expect(x.fetcher.mock.calls.every(([u])=>!u.includes('/payment')&&!u.includes('/confirm'))).toBe(true);});
it('blocks repeated clicks and late request results after invalidation, then restores only original same-origin frozen operation',async()=>{let finish!:(r:Response)=>void;const x=await reservationFixture(()=>new Promise<Response>(resolve=>finish=resolve));const pending=x.client.request(x.body);await expect(x.client.request(x.body)).rejects.toThrow();x.client.invalidate();finish(json(x.requested));await expect(pending).rejects.toThrow();expect(x.client.operation().phase).toBe('request_unknown');const foreign=createDetailingCustomerClient('https://other.example',false,x.fetcher as typeof fetch);await expect(foreign.session(x.installation)).rejects.toThrow();});
it('a definite first request denial releases only its own attempt; denial after unknown does not unlock it',async()=>{const deny=()=>new Response(JSON.stringify({ok:false,code:'FORBIDDEN'}),{status:403});const x=await reservationFixture(async()=>deny());await expect(x.client.request(x.body)).rejects.toThrow();expect(x.client.operation().phase).toBe('ready');let attempts=0;const y=await reservationFixture(async()=>{if(++attempts===1)throw Error('lost');return deny();});await expect(y.client.request(y.body)).rejects.toThrow();await expect(y.client.request(y.body)).rejects.toThrow();expect(y.client.operation().phase).toBe('request_unknown');});
it('never renews an expired cached hold and rejects changed live hold tuples',async()=>{let change=false;const x=await reservationFixture(async path=>json(path.includes('/request')?x.requested:change?{...x.reserved,holdId:id}:x.reserved));await x.client.request(x.body);await x.client.hold();change=true;await expect(x.client.hold()).rejects.toThrow();expect(x.client.operation().phase).toBe('hold_unknown');const before=x.fetcher.mock.calls.length;const date=vi.spyOn(Date,'now').mockReturnValue(Date.parse(x.reserved.expiresAt));try{await expect(x.client.hold()).rejects.toThrow();expect(x.fetcher).toHaveBeenCalledTimes(before);}finally{date.mockRestore();}});
it('rejects stale session, quote, and slot state before request transport',async()=>{const x=await reservationFixture();x.client.clearAvailability();const count=x.fetcher.mock.calls.length;await expect(x.client.request(x.body)).rejects.toThrow();expect(x.fetcher).toHaveBeenCalledTimes(count);const y=await reservationFixture();const now=vi.spyOn(Date,'now').mockReturnValue(Date.parse(expiresAt));try{await expect(y.client.request(y.body)).rejects.toThrow();}finally{now.mockRestore();}expect(y.client.operation().phase).toBe('ready');});
it('restores a saved tuple after remount as unverified until explicit same-hold verification',async()=>{const x=await reservationFixture();await x.client.request(x.body);await x.client.hold();x.client.invalidate();const next=createDetailingCustomerClient('https://api.example',false,x.fetcher as typeof fetch);const before=x.fetcher.mock.calls.length;await next.session(x.installation);expect(next.operation().phase).toBe('hold_unknown');expect(x.fetcher).toHaveBeenCalledTimes(before);expect(await next.hold()).toEqual(x.reserved);expect(next.operation().phase).toBe('held');});

async function financialFixture(){
 vi.resetModules();const {createDetailingCustomerClient:factory}=await import('../src/detailing-customer');
 const installation='98000000-0000-4000-8000-'+String(++reservationNumber).padStart(12,'0'),booking='98000000-0000-4000-8000-'+String(++reservationNumber).padStart(12,'0');
 const slot={start:'2030-01-01T10:00:00.000Z',end:'2030-01-01T10:30:00.000Z',remainingCapacity:1};
 const request={schemaVersion:1,versionId:id,installationId:installation,serviceId:id,bookingId:booking,reference:'LMN-ABC123',selection,pricing:receipt.pricing,slot:{start:slot.start,end:slot.end},state:'draft',confirmed:false,paymentMode:'unavailable'};
 const hold={schemaVersion:1,versionId:id,installationId:installation,serviceId:id,bookingId:booking,holdId:other,status:'active',expiresAt:'2030-01-01T09:59:00.000Z'};
 const identity={schemaVersion:1,versionId:id,installationId:installation,serviceId:id,bookingId:booking,provider:'staging_mock',simulated:true};
 const payment={...identity,paymentId:other,state:'confirmed',replayed:false};
 const control:{paid:boolean;action?: (path:string,options?:RequestInit)=>Promise<Response|undefined>}={paid:false};
 const fetcher=vi.fn(async(url:string,options?:RequestInit)=>{const intercepted=await control.action?.(url,options);if(intercepted)return intercepted;
  if(url.endsWith('/payment-readiness'))return json({...identity,...(control.paid?{state:'confirmed',canPay:false,canConfirm:true}:{state:'draft',canPay:true,canConfirm:false})});
  if(url.endsWith('/mock-payment')){const replayed=control.paid;control.paid=true;return json({...payment,replayed});}
  if(url.endsWith('/confirm'))return json({...payment,replayed:true});
  if(url.endsWith('/request'))return json(request);if(url.endsWith('/hold'))return json(hold);
  if(url.endsWith('/quote'))return json({...receipt,installationId:installation});if(url.includes('/availability'))return json({schemaVersion:1,versionId:id,installationId:installation,serviceId:id,expiresAt,durationMinutes:30,timezone:'America/Los_Angeles',slots:[slot]});return json({sessionToken:token,expiresAt,render});
 });
 const client=factory('https://api.example',false,fetcher as typeof fetch),body:DetailingReservationInput={schemaVersion:1,idempotencyKey:'financial-original-request-0001',selection,customer:{name:'Fictional customer',email:'fictional@example.test'},requestedStart:slot.start};
 await client.session(installation);await client.quote(selection);await client.availability({from:'2030-01-01T00:00:00.000Z',to:'2030-01-02T00:00:00.000Z'});await client.request(body);await client.hold();return{factory,client,fetcher,control,identity,payment,hold,body,installation};
}
it('requires explicit private server readiness despite unavailable render, consumes proof, and confirms exact payment replay',async()=>{
 const x=await financialFixture();await expect(x.client.mockPayment()).rejects.toThrow();await expect(x.client.confirm()).rejects.toThrow();expect(x.fetcher).toHaveBeenCalledTimes(5);
 const ready=await x.client.paymentReadiness();expect(ready).toMatchObject({state:'draft',canPay:true});expect(x.client.operation().phase).toBe('payment_ready');ready.bookingId=other;
 expect(await x.client.mockPayment()).toEqual(x.payment);expect(x.client.operation().phase).toBe('confirmed');await expect(x.client.confirm()).rejects.toThrow();await x.client.paymentReadiness();expect(await x.client.confirm()).toEqual({...x.payment,replayed:true});
 const calls=x.fetcher.mock.calls.filter(([u])=>u.includes('/payment')||u.endsWith('/mock-payment')||u.endsWith('/confirm'));expect(calls.map(([u])=>u.split('/').at(-1))).toEqual(['payment-readiness','mock-payment','payment-readiness','confirm']);
 for(const [url,options] of calls){expect(url).not.toContain(token);expect(options).toMatchObject({credentials:'omit',cache:'no-store',redirect:'error',headers:{Authorization:'Bearer '+token}});expect(options?.body).toBe(url.endsWith('/payment-readiness')?undefined:'{}');}
});
it.each(['versionId','installationId','serviceId','bookingId','provider','simulated','flags','extra'])('rejects malformed/foreign readiness %s without enabling a writer',async field=>{
 const x=await financialFixture(),valid={...x.identity,state:'draft',canPay:true,canConfirm:false},bad=field==='flags'?{...valid,canConfirm:true}:field==='extra'?{...valid,total:1000}:field==='provider'?{...valid,provider:'live'}:field==='simulated'?{...valid,simulated:false}:{...valid,[field]:other};x.control.action=async path=>path.endsWith('/payment-readiness')?json(bad):undefined;
 await expect(x.client.paymentReadiness()).rejects.toThrow();await expect(x.client.mockPayment()).rejects.toThrow();expect(x.client.operation().phase).toBe('held');expect(x.fetcher.mock.calls.filter(([u])=>u.endsWith('/mock-payment'))).toHaveLength(0);
});
it('lost committed payment locks all editing and issuers, then explicit read and confirmation recover without another payment',async()=>{
 const x=await financialFixture();await x.client.paymentReadiness();x.control.action=async path=>{if(path.endsWith('/mock-payment')){x.control.paid=true;throw Error('lost committed receipt');}return undefined;};await expect(x.client.mockPayment()).rejects.toThrow();expect(x.client.operation().phase).toBe('payment_unknown');const before=x.fetcher.mock.calls.length;
 await expect(x.client.mockPayment()).rejects.toThrow();await expect(x.client.request(x.body)).rejects.toThrow();await expect(x.client.hold()).rejects.toThrow();expect(()=>x.client.clearSelection()).toThrow();expect(()=>x.client.clearAvailability()).toThrow();await expect(x.factory('https://api.example',false,x.fetcher as typeof fetch).session(other)).rejects.toThrow();await expect(x.factory('https://foreign.example',false,x.fetcher as typeof fetch).session(x.installation)).rejects.toThrow();expect(x.fetcher).toHaveBeenCalledTimes(before);
 x.control.action=undefined;await x.client.paymentReadiness();expect(x.client.operation().phase).toBe('payment_unknown');await x.client.confirm();expect(x.client.operation().phase).toBe('confirmed');expect(x.fetcher.mock.calls.filter(([u])=>u.endsWith('/mock-payment'))).toHaveLength(1);
});
it('uncommitted ambiguity remains locked after draft readiness and permits only explicit same-attempt payment',async()=>{
 const x=await financialFixture();await x.client.paymentReadiness();x.control.action=async path=>{if(path.endsWith('/mock-payment'))throw Error('lost before commit');return undefined;};await expect(x.client.mockPayment()).rejects.toThrow();x.control.action=undefined;await x.client.paymentReadiness();expect(x.client.operation().phase).toBe('payment_unknown');await expect(x.client.request({...x.body,idempotencyKey:'new-request-operation-0001'})).rejects.toThrow();expect(await x.client.mockPayment()).toEqual(x.payment);expect(x.client.operation().phase).toBe('confirmed');
});
it('remount recovers committed confirmation after cached hold expires, without acquiring another session or renewing hold',async()=>{
 const x=await financialFixture();await x.client.paymentReadiness();x.control.action=async path=>{if(path.endsWith('/mock-payment')){x.control.paid=true;throw Error('lost');}return undefined;};await expect(x.client.mockPayment()).rejects.toThrow();x.client.invalidate();x.control.action=undefined;const next=x.factory('https://api.example',false,x.fetcher as typeof fetch),before=x.fetcher.mock.calls.length;await next.session(x.installation);expect(x.fetcher).toHaveBeenCalledTimes(before);
 const clock=vi.spyOn(Date,'now').mockReturnValue(Date.parse(x.hold.expiresAt)+1);try{await next.paymentReadiness();await next.confirm();expect(next.operation().phase).toBe('confirmed');await expect(next.hold()).rejects.toThrow();}finally{clock.mockRestore();}expect(x.fetcher.mock.calls.filter(([u])=>u.endsWith('/sessions')||u.endsWith('/hold'))).toHaveLength(2);
});
it('blocks duplicate pending financial calls and rejects late results after remount ownership changes',async()=>{
 const x=await financialFixture();await x.client.paymentReadiness();let finish!:(r:Response)=>void;x.control.action=async path=>path.endsWith('/mock-payment')?new Promise<Response>(resolve=>finish=resolve):undefined;const pending=x.client.mockPayment();await Promise.resolve();await expect(x.client.mockPayment()).rejects.toThrow();await expect(x.client.paymentReadiness()).rejects.toThrow();await expect(x.client.confirm()).rejects.toThrow();const next=x.factory('https://api.example',false,x.fetcher as typeof fetch);await next.session(x.installation);finish(json(x.payment));await expect(pending).rejects.toThrow();expect(next.operation().phase).toBe('payment_unknown');x.control.action=undefined;x.control.paid=true;await next.paymentReadiness();await next.confirm();expect(next.operation().phase).toBe('confirmed');
});
it('expired hold prevents initial money transport and expired session prevents readiness or late activation',async()=>{
 const x=await financialFixture();await x.client.paymentReadiness();const count=x.fetcher.mock.calls.length,clock=vi.spyOn(Date,'now').mockReturnValue(Date.parse(x.hold.expiresAt));try{await expect(x.client.mockPayment()).rejects.toThrow();expect(x.fetcher).toHaveBeenCalledTimes(count);clock.mockReturnValue(Date.parse(expiresAt));await expect(x.client.paymentReadiness()).rejects.toThrow();expect(x.fetcher).toHaveBeenCalledTimes(count);}finally{clock.mockRestore();}
 let finish!:(r:Response)=>void;x.control.action=async path=>path.endsWith('/payment-readiness')?new Promise<Response>(resolve=>finish=resolve):undefined;const pending=x.client.paymentReadiness();await Promise.resolve();const late=vi.spyOn(Date,'now').mockReturnValue(Date.parse(expiresAt));try{finish(json({...x.identity,state:'draft',canPay:true,canConfirm:false}));await expect(pending).rejects.toThrow();expect(x.client.operation().readiness).toBeUndefined();}finally{late.mockRestore();}
});
it.each(['identity','provider','extra','paymentId','replayed'])('keeps financial outcome unknown on invalid %s payment receipt',async field=>{
 const x=await financialFixture();await x.client.paymentReadiness();if(field==='paymentId'||field==='replayed'){await x.client.mockPayment();await x.client.paymentReadiness();x.control.action=async path=>path.endsWith('/confirm')?json({...x.payment,replayed:field==='replayed'?false:true,paymentId:field==='paymentId'?id:other}):undefined;await expect(x.client.confirm()).rejects.toThrow();expect(x.client.operation().payment?.paymentId).toBe(other);}else{x.control.action=async path=>path.endsWith('/mock-payment')?json(field==='identity'?{...x.payment,bookingId:other}:field==='provider'?{...x.payment,provider:'live'}:{...x.payment,total:1000}):undefined;await expect(x.client.mockPayment()).rejects.toThrow();}expect(x.client.operation().phase).toBe('payment_unknown');await expect(x.client.request(x.body)).rejects.toThrow();
});
it('initial remount needs explicit same hold verification and invalidated readiness cannot activate payment',async()=>{
 const x=await financialFixture(),next=x.factory('https://api.example',false,x.fetcher as typeof fetch);await next.session(x.installation);await expect(next.paymentReadiness()).rejects.toThrow();await next.hold();await next.paymentReadiness();next.invalidate();await expect(next.mockPayment()).rejects.toThrow();expect(x.fetcher.mock.calls.filter(([u])=>u.endsWith('/mock-payment'))).toHaveLength(0);
});
it('crosses real private HTTP handlers: lost committed payment is reconciled read-only then explicit confirmation, never legacy money',async()=>{
 const x=await financialFixture();vi.resetModules();const {createDetailingCustomerClient:factory}=await import('../src/detailing-customer');const origin='https://checkout.example.test',legacy=vi.fn(),mockPayment=vi.fn(async()=>{x.control.paid=true;return x.payment;}),confirm=vi.fn(async()=>({...x.payment,replayed:true})),readiness=vi.fn(async()=>({...x.identity,...(x.control.paid?{state:'confirmed',canPay:false,canConfirm:true}:{state:'draft',canPay:true,canConfirm:false})}));
 const slot={start:x.body.requestedStart,end:'2030-01-01T10:30:00.000Z',remainingCapacity:1},requested={...x.identity,reference:'LMN-ABC123',selection,pricing:receipt.pricing,slot:{start:slot.start,end:slot.end},state:'draft',confirmed:false,paymentMode:'unavailable'};delete (requested as Partial<typeof requested>).provider;delete (requested as Partial<typeof requested>).simulated;
 const server=createFlowHttpServer({repository:{call:legacy},customerOrigins:[origin],ownerOrigins:[],detailingPublication:true,detailingPaymentApi:{readiness,mockPayment,confirm} as never,detailingReservationApi:{request:vi.fn(async()=>requested),hold:vi.fn(async()=>x.hold)} as never,detailingAvailability:vi.fn(async()=>({schemaVersion:1,versionId:id,installationId:x.installation,serviceId:id,expiresAt,durationMinutes:30,timezone:'UTC',slots:[slot]})) as never,detailingPublicationApi:{session:vi.fn(async()=>({render,expiresAt})),quote:vi.fn(async()=>({...receipt,installationId:x.installation})),save:vi.fn(),read:vi.fn(),publish:vi.fn(),recover:vi.fn()} as never});
 await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));try{const address=server.address();if(!address||typeof address==='string')throw Error('No address');const base='http://127.0.0.1:'+address.port;let drop=true;const transport=vi.fn(async(url:string,options?:RequestInit)=>{const response=await fetch(url,{...options,headers:{...options?.headers,Origin:origin}});if(url.endsWith('/mock-payment')&&drop){drop=false;await response.text();throw Error('committed response dropped');}return response;});const client=factory(base,true,transport as typeof fetch);
 const loaded=await client.session(x.installation);expect(loaded.render.paymentMode).toBe('unavailable');await client.quote(selection);await client.availability({from:'2030-01-01T00:00:00.000Z',to:'2030-01-02T00:00:00.000Z'});await client.request(x.body);await client.hold();await client.paymentReadiness();expect(mockPayment).not.toHaveBeenCalled();expect(confirm).not.toHaveBeenCalled();await expect(client.mockPayment()).rejects.toThrow();expect(client.operation().phase).toBe('payment_unknown');await client.paymentReadiness();expect(mockPayment).toHaveBeenCalledTimes(1);expect(confirm).not.toHaveBeenCalled();await client.confirm();expect(client.operation().phase).toBe('confirmed');expect(confirm).toHaveBeenCalledTimes(1);expect(legacy).not.toHaveBeenCalled();
 const hash=mockPayment.mock.calls[0] as unknown as [string,string];expect(hash).toEqual([expect.stringMatching(/^[0-9a-f]{64}$/),origin]);expect(confirm.mock.calls[0]).toEqual(hash);expect(readiness.mock.calls).toEqual([hash,hash]);for(const [url,options] of transport.mock.calls.filter(([u])=>u.endsWith('/mock-payment')||u.endsWith('/confirm'))){expect(url).not.toContain(loaded.sessionToken);expect(options?.body).toBe('{}');expect(options?.headers).toMatchObject({Authorization:'Bearer '+loaded.sessionToken});}
 }finally{server.closeAllConnections();await new Promise<void>(resolve=>server.close(()=>resolve()));}
});
it('readiness transport failure never releases a financial unknown lock or automatically retries money',async()=>{
 const x=await financialFixture();await x.client.paymentReadiness();x.control.action=async path=>{if(path.endsWith('/mock-payment'))throw Error('lost');return undefined;};await expect(x.client.mockPayment()).rejects.toThrow();x.control.action=async path=>path.endsWith('/payment-readiness')?new Response(JSON.stringify({ok:false,code:'CONFLICT'}),{status:409}):undefined;await expect(x.client.paymentReadiness()).rejects.toThrow();expect(x.client.operation().phase).toBe('payment_unknown');await expect(x.client.mockPayment()).rejects.toThrow();await expect(x.client.request(x.body)).rejects.toThrow();expect(x.fetcher.mock.calls.filter(([u])=>u.endsWith('/mock-payment'))).toHaveLength(1);
});
it('late readonly proof cannot survive remount and late successful money cannot survive session expiry',async()=>{
 const x=await financialFixture();let finish!:(r:Response)=>void;x.control.action=async path=>path.endsWith('/payment-readiness')?new Promise<Response>(resolve=>finish=resolve):undefined;const read=x.client.paymentReadiness();await Promise.resolve();const next=x.factory('https://api.example',false,x.fetcher as typeof fetch);await next.session(x.installation);finish(json({...x.identity,state:'draft',canPay:true,canConfirm:false}));await expect(read).rejects.toThrow();expect(next.operation().readiness).toBeUndefined();await expect(next.mockPayment()).rejects.toThrow();x.control.action=undefined;await next.hold();await next.paymentReadiness();x.control.action=async path=>path.endsWith('/mock-payment')?new Promise<Response>(resolve=>finish=resolve):undefined;const write=next.mockPayment();await Promise.resolve();const clock=vi.spyOn(Date,'now').mockReturnValue(Date.parse(expiresAt));try{finish(json(x.payment));await expect(write).rejects.toThrow();expect(next.operation().phase).toBe('payment_unknown');expect(next.operation().payment).toBeUndefined();}finally{clock.mockRestore();}
});
