import {useEffect,useMemo,useRef,useState} from 'react';
import {createRosterClient,RosterError,type RosterSnapshot} from '@lumin/flow-ui';
export function formatRosterTime(instant:string,zone:string){
 const options:Intl.DateTimeFormatOptions={year:'numeric',month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZone:zone};
 try{return {text:new Intl.DateTimeFormat(undefined,options).format(new Date(instant)),zone,fallback:false};}
 catch{return {text:new Intl.DateTimeFormat(undefined,{...options,timeZone:'UTC'}).format(new Date(instant)),zone:'UTC',fallback:true};}
}
const validName=(s:string)=>Array.from(s).length<=160&&s.replace(/^ +| +$/g,'').length>0;
export function RosterPanel({apiUrl,token,tenant}:{apiUrl:string;token:string;tenant:string}){
 const client=useMemo(()=>{try{if(!['localhost','127.0.0.1'].includes(location.hostname)||!['localhost','127.0.0.1'].includes(new URL(apiUrl).hostname))return null;return createRosterClient(apiUrl,true);}catch{return null;}},[apiUrl]);
 const [snapshot,setSnapshot]=useState<RosterSnapshot>(),[phase,setPhase]=useState<'loading'|'ready'|'uninitialized'|'blocked'|'denied'|'unavailable'>('loading'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [workerId,setWorkerId]=useState(''),[workerName,setWorkerName]=useState(''),[workerActive,setWorkerActive]=useState(true),[crewId,setCrewId]=useState(''),[crewName,setCrewName]=useState(''),[crewActive,setCrewActive]=useState(true);
 const generation=useRef(0),inFlight=useRef(false),minimumVersion=useRef(0);
 function resetForms(){setWorkerId('');setWorkerName('');setWorkerActive(true);setCrewId('');setCrewName('');setCrewActive(true);}
 function fail(e:unknown,uncertain=false){const code=e instanceof RosterError?e.code:'INTERNAL_ERROR';if(code==='FORBIDDEN'||code==='UNAUTHENTICATED'){setSnapshot(undefined);resetForms();setPhase('denied');}else if(code==='ROSTER_NOT_INITIALIZED'){setSnapshot(undefined);setPhase('uninitialized');}else setPhase('blocked');setError(e instanceof RosterError?e.message:'The roster could not be loaded.');if(uncertain&&code==='INTERNAL_ERROR')setMessage('The save outcome is unknown. Refresh and review the roster before making another change.');}
 async function refresh(){if(!client||inFlight.current)return;const at=++generation.current;client.invalidate();inFlight.current=true;setBusy(true);setError('');setMessage('');try{const next=await client.snapshot(token,tenant);if(at!==generation.current)return;if(next.rosterVersion<minimumVersion.current)throw new RosterError('INTERNAL_ERROR');minimumVersion.current=next.rosterVersion;setSnapshot(next);setPhase('ready');resetForms();}catch(e){if(at===generation.current)fail(e);}finally{if(at===generation.current){inFlight.current=false;setBusy(false);}}}
 useEffect(()=>{generation.current++;client?.invalidate();inFlight.current=false;minimumVersion.current=0;setSnapshot(undefined);resetForms();setError('');setMessage('');setPhase(client?'loading':'unavailable');if(client)void refresh();return()=>{generation.current++;client?.invalidate();inFlight.current=false;};},[client,token,tenant]);
 async function mutate(work:()=>Promise<{rosterVersion:number}>,reset:'worker'|'crew'|'all'|'none'='none'){if(!client||inFlight.current||(phase!=='ready'&&phase!=='uninitialized'))return;const at=++generation.current;inFlight.current=true;setBusy(true);setError('');setMessage('');let saved=false;try{const receipt=await work();if(at!==generation.current)return;minimumVersion.current=Math.max(minimumVersion.current,receipt.rosterVersion);saved=true;setMessage('Change saved. Refreshing the roster…');const next=await client.snapshot(token,tenant);if(at!==generation.current)return;if(next.rosterVersion<minimumVersion.current)throw new RosterError('INTERNAL_ERROR');minimumVersion.current=next.rosterVersion;setSnapshot(next);setPhase('ready');if(reset==='all')resetForms();else if(reset==='worker'){setWorkerId('');setWorkerName('');setWorkerActive(true);}else if(reset==='crew'){setCrewId('');setCrewName('');setCrewActive(true);}setMessage('Change saved and roster refreshed.');}catch(e){if(at!==generation.current)return;if(saved){setPhase('blocked');setError('The change was saved, but the roster could not refresh. Refresh before making another change.');if(e instanceof RosterError&&(e.code==='FORBIDDEN'||e.code==='UNAUTHENTICATED')){setSnapshot(undefined);resetForms();setPhase('denied');}}else fail(e,true);}finally{if(at===generation.current){inFlight.current=false;setBusy(false);}}}
 function selectWorker(id:string){if(busy)return;generation.current++;const w=snapshot?.workers.find(w=>w.id===id);setWorkerId(id);setWorkerName(w?.displayName??'');setWorkerActive(w?.active??true);setMessage('');setError('');}
 function selectCrew(id:string){if(busy)return;generation.current++;const c=snapshot?.crews.find(c=>c.id===id);setCrewId(id);setCrewName(c?.name??'');setCrewActive(c?.active??true);setMessage('');setError('');}
 const editable=phase==='ready'&&!busy&&!!snapshot,worker=snapshot?.workers.find(w=>w.id===workerId),crew=snapshot?.crews.find(c=>c.id===crewId);
 return <section><h1>Workers</h1><p>Manage your operational team and service eligibility. Login access, job assignments and booking availability are not managed here.</p>{!client?<p role="alert">Roster management is unavailable. Use the configured local test workspace.</p>:<><button disabled={busy} onClick={()=>void refresh()}>Refresh roster (discard edits)</button>{busy&&<p role="status">Loading or saving roster…</p>}{phase==='uninitialized'&&<section><h2>Set up your roster</h2><p>No roster has been created for this business.</p><button disabled={busy} onClick={()=>void mutate(()=>client.provision(token,tenant),'all')}>Set up roster</button></section>}{phase==='denied'&&<p role="alert">An active business owner account is required to manage this roster.</p>}{snapshot&&<><p>{snapshot.workers.length===0?'No workers have been added.':'Current roster, including retired workers.'}</p><section><h2>Worker details</h2><fieldset disabled={!editable}><label>Choose worker<select value={workerId} onChange={e=>selectWorker(e.target.value)}><option value="">New worker</option>{snapshot.workers.map(w=><option key={w.id} value={w.id}>{w.displayName}{w.active?'':' · Retired'}</option>)}</select></label><label>Worker name<input value={workerName} onChange={e=>{setWorkerName(e.target.value);setMessage('');}}/></label><label><input type="checkbox" checked={workerActive} onChange={e=>{setWorkerActive(e.target.checked);setMessage('');}}/>Worker active</label><button disabled={!validName(workerName)} onClick={()=>void mutate(()=>client.worker(token,tenant,workerId||null,{expectedRosterVersion:snapshot.rosterVersion,displayName:workerName,active:workerActive}),'worker')}>{workerId?'Save worker':'Add worker'}</button></fieldset>
 {worker&&<><h3>Service eligibility for {worker.displayName}</h3><p>Eligibility is a team setting, not a promise of availability.</p>{snapshot.services.length===0?<p>No services are available.</p>:<fieldset disabled={!editable}>{snapshot.services.map(service=>{const existing=snapshot.eligibility.find(e=>e.workerId===worker.id&&e.serviceId===service.id);return <label key={service.id} style={{display:'block'}}><input type="checkbox" checked={existing?.active??false} disabled={!service.active&&!existing} onChange={e=>void mutate(()=>client.eligibility(token,tenant,{expectedRosterVersion:snapshot.rosterVersion,serviceId:service.id,workerId:worker.id,active:e.target.checked,create:!existing}))}/>{service.name||'Unnamed service'}{service.active?'':' · Inactive service'}</label>;})}</fieldset>}<h3>Dated shifts for {worker.displayName}</h3><p>Read-only shifts. Shift editing is not available here.</p>{snapshot.shifts.filter(s=>s.workerId===worker.id).length===0?<p>No dated shifts recorded.</p>:<ul>{snapshot.shifts.filter(s=>s.workerId===worker.id).map(s=>{const start=formatRosterTime(s.startsAt,s.sourceTimeZone),end=formatRosterTime(s.endsAt,s.sourceTimeZone);return <li key={s.id}>{s.kind==='blocked'?'Blocked':'Available'}{s.active?'':' · Retired'}: {start.text} – {end.text} · {start.zone}{start.fallback&&<> (UTC display fallback; recorded zone: {s.sourceTimeZone})</>}</li>;})}</ul>}</>}
 </section><section><h2>Crews</h2>{snapshot.crews.length===0&&<p>No crews have been added.</p>}<fieldset disabled={!editable}><label>Choose crew<select value={crewId} onChange={e=>selectCrew(e.target.value)}><option value="">New crew</option>{snapshot.crews.map(c=><option key={c.id} value={c.id}>{c.name}{c.active?'':' · Retired'}</option>)}</select></label><label>Crew name<input value={crewName} onChange={e=>{setCrewName(e.target.value);setMessage('');}}/></label><label><input type="checkbox" checked={crewActive} onChange={e=>{setCrewActive(e.target.checked);setMessage('');}}/>Crew active</label><button disabled={!validName(crewName)} onClick={()=>void mutate(()=>client.crew(token,tenant,crewId||null,{expectedRosterVersion:snapshot.rosterVersion,name:crewName,active:crewActive}),'crew')}>{crewId?'Save crew':'Add crew'}</button></fieldset>{crew&&<><h3>Members of {crew.name}</h3>{snapshot.workers.length===0?<p>Add a worker before choosing members.</p>:<fieldset disabled={!editable}>{snapshot.workers.map(w=><label key={w.id} style={{display:'block'}}><input type="checkbox" checked={crew.workerIds.includes(w.id)} onChange={e=>void mutate(()=>client.member(token,tenant,crew.id,{expectedRosterVersion:snapshot.rosterVersion,workerId:w.id,present:e.target.checked}))}/>{w.displayName}{w.active?'':' · Retired'}</label>)}</fieldset>}</>}</section></>}{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}</>}</section>;
}
