import {describe,expect,it} from 'vitest';
import {PaidOptionRender,PaidOptionService,validatePaidOptionAnswers,isPaidOptionRender} from './paidOptionPublication';
import {isPaidSimpleRender} from './paidPublication';
const service={id:'42000000-0000-4000-8000-000000000003',name:'Housekeeping',durationMinutes:60,price:{amount:12500,currency:'USD'},questions:[{id:'access',prompt:'Will someone be present?',kind:'single_choice',required:true,choices:[{id:'present',label:'Someone present'},{id:'key',label:'Key provided'}]}]};
const render={versionId:'42000000-0000-4000-8000-000000000004',renderSchemaVersion:4,submissionMode:'paid_option_request',paymentMode:'staging_mock',simulated:true,service};
describe('explicit paid V4 price-neutral option',()=>{
 it('pins one bounded question independently of V3',()=>{expect(PaidOptionRender.parse(render)).toEqual(render);expect(isPaidOptionRender(render)).toBe(true);expect(isPaidSimpleRender(render)).toBe(false);expect(isPaidOptionRender({...render,renderSchemaVersion:3})).toBe(false);});
 it.each([{}, {access:{choiceIds:[]}}, {access:{choiceIds:['present','key']}}, {access:{choiceIds:['unknown']}}, {foreign:{choiceIds:['present']}}, {access:{choiceIds:['present'],price:1}}, {access:{choiceIds:['present']},other:{choiceIds:['key']}}, {access:{quantity:1}}, {access:{choiceIds:['present'],quantity:1}}])('rejects missing/widened/foreign answers %j',answers=>{expect(()=>validatePaidOptionAnswers(service,answers)).toThrow();});
 it('returns exact catalog-bound selection for each supported choice',()=>{for(const id of ['present','key'])expect(validatePaidOptionAnswers(service,{access:{choiceIds:[id]}})).toEqual({serviceId:service.id,answers:{access:{choiceIds:[id]}}});});
 it.each([{...service,questions:[]},{...service,questions:[...service.questions,...service.questions]},{...service,price:{amount:0,currency:'USD'}},{...service,questions:[{...service.questions[0],required:false}]},{...service,questions:[{...service.questions[0],kind:'quantity'}]},{...service,questions:[{...service.questions[0],choices:[{id:'present',label:'A'},{id:'present',label:'B'}]}]},{...service,questions:[{...service.questions[0],choices:[{id:'present',label:'A',priceDelta:1},{id:'key',label:'B'}]}]},{...service,questions:[{...service.questions[0],id:'__proto__'}]}])('rejects unsupported service shape %j',value=>{expect(PaidOptionService.safeParse(value).success).toBe(false);});
});
