import {useMemo,useRef,useState,type FormEvent} from 'react';
import {createRuntimeClient,type RuntimeConfig} from '@lumin/runtime-client';
type Tables=Awaited<ReturnType<ReturnType<typeof createRuntimeClient>['aggregates']>>;
const columns={platform_business_stats:['month','status','tenants_created','tenants_total_to_date'],platform_booking_stats:['month','state','booking_count'],platform_economics:['month','currency','merchant_gmv','refunded_amount','subscription_revenue','transaction_revenue'],platform_integration_health:['kind','provider','status','connection_count']} as const;
const titles={platform_business_stats:'Business growth',platform_booking_stats:'Requests by state',platform_economics:'Economics by currency',platform_integration_health:'Connection records'};
export function ConnectedCommandCenter({config}:{config:RuntimeConfig}){
 const client=useMemo(()=>{try{return createRuntimeClient(config)}catch{return null}},[config.url,config.publishableKey,config.tenantId]);
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[signedIn,setSignedIn]=useState(false),[tables,setTables]=useState<Tables|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const generation=useRef(0);
 async function load(){if(!client)return;const current=++generation.current;setBusy(true);setError('');setTables(null);try{const result=await client.aggregates();if(current===generation.current)setTables(result)}catch(e){if(current===generation.current)setError(e instanceof Error?e.message:'Unable to load aggregates.')}finally{if(current===generation.current)setBusy(false)}}
 async function login(e:FormEvent){e.preventDefault();if(!client||busy)return;setBusy(true);setError('');try{await client.signIn(email,password);if(!await client.isPlatformAdmin()){client.signOut();throw Error('Platform administrator access is required.')}setSignedIn(true);await load()}catch(e){client.signOut();setSignedIn(false);setError(e instanceof Error?e.message:'Unable to sign in.')}finally{setPassword('');setBusy(false)}}
 function logout(){generation.current++;client?.signOut();setSignedIn(false);setTables(null);setEmail('');setPassword('');setBusy(false);setError('')}
 return <main style={{maxWidth:1100,margin:'40px auto',padding:24}}><p>Lumin Command Center · Connected preview</p><h1>Platform overview</h1><p>Business activity and connection summaries. Customer details stay private.</p>{!client?<p role="alert">Connected mode configuration is missing or invalid.</p>:!signedIn?<form onSubmit={login}><fieldset disabled={busy} style={{display:'grid',gap:16,border:0}}><label>Email<input type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button>{busy?'Signing in…':'Sign in'}</button></fieldset><p>Use an existing platform administrator account. Sessions stay in memory.</p></form>:<><button onClick={logout}>Sign out</button><button disabled={busy} onClick={()=>void load()}>Refresh</button>{busy&&<p role="status">Loading aggregates…</p>}{tables&&(Object.keys(columns) as (keyof Tables)[]).map(key=><section key={key} style={{overflowX:'auto'}}><h2>{titles[key]}</h2>{tables[key].length===0?<p>No recorded data.</p>:<table><thead><tr>{columns[key].map(c=><th key={c}>{c.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{tables[key].map((row,i)=><tr key={i}>{columns[key].map(c=><td key={c}>{typeof row[c]==='string'||typeof row[c]==='number'?String(row[c]):'—'}</td>)}</tr>)}</tbody></table>}</section>)}<p>Amounts are minor units, grouped by currency. Platform billing is not connected. Recorded connection statuses do not confirm provider availability. Each view is limited to 1,000 rows.</p></>}{error&&<p role="alert">{error}</p>}</main>
}

