import {z} from 'zod';
import {CurrencyCode} from './money';
function text(value:string):boolean{if(/[\u0000-\u001f\u007f-\u009f]/.test(value))return false;for(let i=0;i<value.length;i++){const u=value.charCodeAt(i);if(u>=0xd800&&u<=0xdbff){const n=value.charCodeAt(++i);if(!(n>=0xdc00&&n<=0xdfff))return false;}else if(u>=0xdc00&&u<=0xdfff)return false;}return value===value.trim();}
const Name=z.string().min(1).max(200).refine(text),Label=z.string().min(1).max(100).refine(text),Description=z.string().max(2000).refine(text);
const Key=z.string().regex(/^[a-z][a-z0-9_-]{0,39}$/).refine(v=>!['constructor','prototype','tenant','role','provider','total','price','amount'].includes(v));
const Amount=z.number().int().safe().min(0),Multiplier=z.number().int().safe().min(0);
const Package=z.object({id:Key,label:Label,amount:Amount}).strict(),Vehicle=z.object({id:Key,label:Label,multiplierBp:Multiplier}).strict(),Addon=z.object({id:Key,name:Label,amount:Amount}).strict();
const Catalog=z.object({name:Name,description:Description,currency:CurrencyCode,durationMinutes:z.number().int().min(5).max(1440),packages:z.array(Package).min(1).max(5),vehicles:z.array(Vehicle).min(1).max(5),addons:z.array(Addon).max(5),locations:z.array(Package).max(3)}).strict();
function safe(c:z.infer<typeof Catalog>):boolean{if(!c.packages.length||!c.vehicles.length||[...c.packages.map(p=>p.amount),...c.vehicles.map(v=>v.multiplierBp),...c.addons.map(a=>a.amount),...c.locations.map(l=>l.amount)].every(v=>Number.isSafeInteger(v)&&v>=0)===false)return false;if([c.packages,c.vehicles,c.addons,c.locations].some(a=>new Set(a.map(x=>x.id)).size!==a.length))return false;const subtotal=BigInt(Math.max(...c.packages.map(p=>p.amount)))+c.addons.reduce((s,a)=>s+BigInt(a.amount),0n)+BigInt(Math.max(0,...c.locations.map(l=>l.amount)));const multiplier=BigInt(Math.max(...c.vehicles.map(v=>v.multiplierBp)));return subtotal<=BigInt(Number.MAX_SAFE_INTEGER)&&subtotal*multiplier<=BigInt(Number.MAX_SAFE_INTEGER);}
/** Existing core model: all additive lines (including addons/location) precede vehicle multiplier. */
export const CreateDetailingOffer=Catalog.extend({idempotencyKey:z.string().min(16).max(128).regex(/^[A-Za-z0-9_-]+$/)}).strict().refine(safe,'Pricing intermediate exceeds exact integer range');
export type CreateDetailingOffer=z.infer<typeof CreateDetailingOffer>;
const Choice=z.object({id:Key,label:Label,priceDelta:Amount,priceMultiplierBp:Multiplier}).strict();
const Question=z.object({id:z.enum(['package','vehicle','location']),prompt:Label,kind:z.literal('single_choice'),required:z.literal(true),choices:z.array(Choice).min(1).max(5)}).strict();
const Service=z.object({id:z.string().uuid(),tenantId:z.string().uuid(),archetype:z.literal('configurable'),name:Name,description:Description,currency:CurrencyCode,basePrice:z.literal(0),durationMinutes:z.number().int().min(5).max(1440),taxRateBp:z.literal(0),active:z.literal(true),items:z.array(z.never()).max(0),addons:z.array(z.object({id:Key,name:Label,price:Amount}).strict()).max(5),questions:z.array(Question).min(2).max(3)}).strict().superRefine((s,ctx)=>{try{const c={name:s.name,description:s.description,currency:s.currency,durationMinutes:s.durationMinutes,packages:s.questions[0]!.choices.map(x=>({id:x.id,label:x.label,amount:x.priceDelta})),vehicles:s.questions[1]!.choices.map(x=>({id:x.id,label:x.label,multiplierBp:x.priceMultiplierBp})),addons:s.addons.map(x=>({id:x.id,name:x.name,amount:x.price})),locations:s.questions[2]?.choices.map(x=>({id:x.id,label:x.label,amount:x.priceDelta}))??[]};if(!safe(c)||s.questions.some((q,i)=>q.id!==['package','vehicle','location'][i]||q.prompt!==['Detail package','Vehicle type','Service location'][i]||q.choices.some(x=>i===1?x.priceDelta!==0:x.priceMultiplierBp!==10000))||c.locations.length>3)ctx.addIssue({code:'custom',message:'Unsupported detailing model'});}catch{ctx.addIssue({code:'custom',message:'Invalid detailing model'});}});
export const DetailingOfferReceipt=z.object({schemaVersion:z.literal(1),tenantId:z.string().uuid(),businessType:z.literal('AUTO_DETAILING'),pricingModel:z.literal('package_subtotal_vehicle_multiplier'),service:Service}).strict().refine(r=>r.tenantId===r.service.tenantId);
export type DetailingOfferReceipt=z.infer<typeof DetailingOfferReceipt>;
export function buildDetailingService(serviceId:string,tenantId:string,input:CreateDetailingOffer):DetailingOfferReceipt['service']{const b=CreateDetailingOffer.parse(input);return Service.parse({id:serviceId,tenantId,archetype:'configurable',name:b.name,description:b.description,currency:b.currency,basePrice:0,durationMinutes:b.durationMinutes,taxRateBp:0,active:true,items:[],addons:b.addons.map(a=>({id:a.id,name:a.name,price:a.amount})),questions:[{id:'package',prompt:'Detail package',kind:'single_choice',required:true,choices:b.packages.map(p=>({id:p.id,label:p.label,priceDelta:p.amount,priceMultiplierBp:10000}))},{id:'vehicle',prompt:'Vehicle type',kind:'single_choice',required:true,choices:b.vehicles.map(v=>({id:v.id,label:v.label,priceDelta:0,priceMultiplierBp:v.multiplierBp}))},...(b.locations.length?[{id:'location',prompt:'Service location',kind:'single_choice',required:true,choices:b.locations.map(l=>({id:l.id,label:l.label,priceDelta:l.amount,priceMultiplierBp:10000}))}]:[])]});}
