import {describe,it,expect} from 'vitest';
import {CreateDetailingOffer,DetailingOfferReceipt,buildDetailingService} from './detailing-catalog';
const body={name:'Detail package menu',description:'Owner authored detailing',currency:'USD',durationMinutes:120,packages:[{id:'basic',label:'Basic',amount:8000},{id:'deluxe',label:'Deluxe',amount:15000}],vehicles:[{id:'sedan',label:'Sedan',multiplierBp:10000},{id:'suv',label:'SUV',multiplierBp:12500}],addons:[{id:'pet-hair',name:'Pet hair',amount:3000}],locations:[{id:'studio',label:'Studio',amount:0},{id:'mobile',label:'Mobile visit',amount:2000}],idempotencyKey:'detailing-create-fixture-001'};
const tenant='62000000-0000-4000-8000-000000000002',service='62000000-0000-4000-8000-000000000003';
describe('owner detailing catalog exact model',()=>{
 it('retains ordered package/vehicle/addon/location rates in the standard configurable model',()=>{const s=buildDetailingService(service,tenant,body);expect(s.archetype).toBe('configurable');expect(s.questions.map(q=>q.id)).toEqual(['package','vehicle','location']);expect(s.questions[0]!.choices[1]).toEqual({id:'deluxe',label:'Deluxe',priceDelta:15000,priceMultiplierBp:10000});expect(s.questions[1]!.choices[1]).toEqual({id:'suv',label:'SUV',priceDelta:0,priceMultiplierBp:12500});expect(s.addons[0]).toEqual({id:'pet-hair',name:'Pet hair',price:3000});expect(s.taxRateBp).toBe(0);});
 it('supports omitted location selection only when owner supplies an explicit empty array',()=>{expect(buildDetailingService(service,tenant,{...body,locations:[]}).questions.map(q=>q.id)).toEqual(['package','vehicle']);});
 it.each(['tenantId','actor','total','taxRateBp','basePrice','provider','role','resources','serviceId'])('rejects injected authority %s',key=>{expect(CreateDetailingOffer.safeParse({...body,[key]:1}).success).toBe(false);});
 it.each([-1,1.5,NaN,Infinity,Number.MAX_SAFE_INTEGER+1])('rejects invalid owner monetary value %s',amount=>{expect(CreateDetailingOffer.safeParse({...body,packages:[{...body.packages[0]!,amount}]}).success).toBe(false);});
 it.each(['__proto__','constructor','prototype','price','total','tenant','a.b','x;delete','UPPER'])('rejects injection/reserved catalog ID %s',id=>{expect(CreateDetailingOffer.safeParse({...body,packages:[{...body.packages[0]!,id}]}).success).toBe(false);});
 it.each([' bad','bad ','bad\nlabel','bad\u0085label','\ud800'])('rejects malformed catalog label',label=>{expect(CreateDetailingOffer.safeParse({...body,packages:[{...body.packages[0]!,label}]}).success).toBe(false);});
 it('accepts paired UTF16 and rejects duplicates/unknown choice properties and bounded overflow',()=>{expect(CreateDetailingOffer.safeParse({...body,name:'Detail 🚗'}).success).toBe(true);expect(CreateDetailingOffer.safeParse({...body,packages:[body.packages[0],body.packages[0]]}).success).toBe(false);expect(CreateDetailingOffer.safeParse({...body,vehicles:[{...body.vehicles[0]!,priceDelta:1}]}).success).toBe(false);expect(CreateDetailingOffer.safeParse({...body,packages:Array.from({length:6},(_,i)=>({...body.packages[0]!,id:'p'+i}))}).success).toBe(false);});
 it('bounds the actual multiplication intermediate, retaining exact maximum-safe price support',()=>{const max=Math.floor(Number.MAX_SAFE_INTEGER/10000);const safe={...body,packages:[{id:'basic',label:'Basic',amount:max}],vehicles:[{id:'sedan',label:'Sedan',multiplierBp:10000}],addons:[],locations:[]};expect(CreateDetailingOffer.safeParse(safe).success).toBe(true);expect(CreateDetailingOffer.safeParse({...safe,packages:[{...safe.packages[0]!,amount:max+1}]}).success).toBe(false);expect(CreateDetailingOffer.safeParse({...safe,vehicles:[{id:'free',label:'Free',multiplierBp:0}],packages:[{id:'basic',label:'Basic',amount:Number.MAX_SAFE_INTEGER}]}).success).toBe(true);});
 it('rejects receipt widening, model drift, foreign identity and housekeeping flattening',()=>{const receipt={schemaVersion:1,tenantId:tenant,businessType:'AUTO_DETAILING',pricingModel:'package_subtotal_vehicle_multiplier',service:buildDetailingService(service,tenant,body)};expect(DetailingOfferReceipt.safeParse(receipt).success).toBe(true);for(const bad of [{...receipt,total:1},{...receipt,businessType:'HOUSEKEEPING'},{...receipt,tenantId:service},{...receipt,service:{...receipt.service,basePrice:15000}},{...receipt,service:{...receipt.service,questions:[...receipt.service.questions].reverse()}}])expect(DetailingOfferReceipt.safeParse(bad).success).toBe(false);});
});
