import { describe,it,expect,vi,afterEach } from 'vitest';
import { EventEmitter } from 'node:events';
import { createRequire } from 'node:module';
import { Pool } from 'pg';
import { __createModeInstallationRepositoryForTests as create,createLocalModeInstallationRepository,type ModeClock,type ModeMethod } from '../server/mode-installation-repository';
import { createModeContracts } from '../server/mode-installation-contracts';
vi.mock('pg',()=>({Pool:vi.fn()}));
const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const actor={mode:'local_synthetic',userId:id(1)};
const profile={profileVersion:'local-test',rendererOrigin:'https://renderer.example.test',apiOrigin:'https://api.example.test',portalOrigin:'https://portal.example.test',loaderUrl:`https://renderer.example.test/assets/booking-lumin-loader.${'a'.repeat(64)}.js`};
const parents=['https://merchant.example.test'];
const scope={tenantId:id(2),flowId:id(3)},key='operation_key_0001';
const requests:Record<ModeMethod,any>={publish:{...scope,expectedDraftRevision:1,idempotencyKey:key},install:{...scope,versionId:id(4),expectedPublishedVersionId:id(4),mode:'iframe',deploymentProfileVersion:profile.profileVersion,allowedParentOrigins:parents,idempotencyKey:key},applyVersion:{...scope,installationId:id(5),expectedTargetRevision:1,expectedCurrentVersionId:id(4),newVersionId:id(6),idempotencyKey:key},updatePolicy:{...scope,installationId:id(5),expectedPolicyRevision:1,enabled:false,allowedParentOrigins:parents,idempotencyKey:key},publicPolicy:{installationId:id(5)},ownerInstallations:{...scope,afterId:null,limit:10},ownerHistory:{...scope,installationId:id(5),beforeSequence:null,limit:10},ownerOperation:{...scope,operation:'apply',idempotencyKey:key}};
const common={schemaVersion:1,actorId:actor.userId,flowId:scope.flowId};
const row={installationId:id(5),flowId:scope.flowId,mode:'iframe',deploymentProfileVersion:profile.profileVersion,currentVersionId:id(4),targetRevision:1,policyRevision:1,enabled:true,allowedParentOrigins:parents};
const history={sequence:1,operation:'install',currentVersionId:id(4),targetRevision:1,policyRevision:1,enabled:true,allowedParentOrigins:parents};
const responses:Record<ModeMethod,any>={publish:{...common,operation:'publish',versionId:id(4),sourceRevision:1,renderSchemaVersion:1},install:{...common,operation:'install',...row,changed:true},applyVersion:{...common,operation:'apply',installationId:id(5),previousVersionId:id(4),currentVersionId:id(6),targetRevision:2,policyRevision:1,changed:true},updatePolicy:{...common,operation:'policy',installationId:id(5),currentVersionId:id(4),targetRevision:1,policyRevision:2,enabled:false,allowedParentOrigins:parents,changed:true},publicPolicy:{schemaVersion:1,...row,rendererOrigin:profile.rendererOrigin,apiOrigin:profile.apiOrigin,loaderUrl:profile.loaderUrl},ownerInstallations:{installations:[row],nextCursor:null},ownerHistory:{history:[history],nextCursor:null},ownerOperation:{...common,operation:'apply',installationId:id(5),previousVersionId:id(4),currentVersionId:id(6),targetRevision:2,policyRevision:1,changed:true}};
delete responses.publicPolicy.flowId;
const clone=<T>(x:T):T=>JSON.parse(JSON.stringify(x));
const select=(data:any)=>({command:'SELECT',rowCount:1,rows:[{result:data}]});
const deferred=<T>()=>{let resolve!:(x:T)=>void,reject!:(x:unknown)=>void;const promise=new Promise<T>((a,b)=>{resolve=a;reject=b;});return{promise,resolve,reject};};
const flush=async()=>{for(let i=0;i<45;i++)await Promise.resolve();};
class Clock implements ModeClock{mono=0;reads=0;onRead?:()=>void;next=0;timers=new Map<number,{at:number;fn:()=>void}>();monotonic(){this.reads++;this.onRead?.();return this.mono;}setTimer(fn:()=>void,ms:number){const id=++this.next;this.timers.set(id,{at:this.mono+ms,fn});return id;}clearTimer(id:unknown){this.timers.delete(id as number);}advance(ms:number,fire=true){this.mono+=ms;if(fire)for(const [id,t]of [...this.timers])if(t.at<=this.mono){this.timers.delete(id);t.fn();}}}
class Client extends EventEmitter{commands:{sql:string;values?:unknown[]}[]=[];releases:(Error|undefined)[]=[];data:any=responses.publish;hook?:(sql:string,values?:unknown[])=>any;async query(sql:string,values?:unknown[]){this.commands.push({sql,values});const special=this.hook?.(sql,values);if(special!==undefined)return special;return sql.startsWith('SELECT')?select(clone(this.data)):{command:sql.startsWith('BEGIN')?'BEGIN':sql.startsWith('SET')?'SET':'COMMIT'};}release(error?:Error){this.releases.push(error);if(error)this.emit('end');}}
class FakePool extends EventEmitter{client=new Client();connects=0;ends=0;pending?:Promise<Client>;ending?:Promise<void>;connect(){this.connects++;return this.pending??Promise.resolve(this.client);}end(){this.ends++;return this.ending??Promise.resolve();}}
function setup(method:ModeMethod='publish'){const pool=new FakePool(),clock=new Clock();pool.client.data=clone(responses[method]);const repo=create({pool,clock,profiles:[profile]});return{pool,clock,repo};}
function call(repo:ReturnType<typeof create>,method:ModeMethod,request:unknown=requests[method],a:unknown=actor,options?:any):Promise<any>{return method==='publicPolicy'?repo.publicPolicy(request,options):(repo[method] as any)(a,request,options);}
const methods=Object.keys(requests) as ModeMethod[];
afterEach(()=>vi.unstubAllEnvs());

describe('fixed method transaction controls',()=>{
 it.each(methods)('%s validates and completes with immutable data',async method=>{const {repo,pool}=setup(method);const result=await call(repo,method);expect(result.kind).toBe(['publish','install','applyVersion','updatePolicy'].includes(method)?'committed':'completed');expect(result.receipt??result.data).toEqual(responses[method]);expect(Object.isFrozen(result)).toBe(true);expect(Object.isFrozen(result.receipt??result.data)).toBe(true);expect(pool.client.commands.map(x=>x.sql).slice(0,5)).toEqual(['BEGIN ISOLATION LEVEL READ COMMITTED',"SET LOCAL statement_timeout='5s'","SET LOCAL lock_timeout='5s'","SET LOCAL idle_in_transaction_session_timeout='1s'","SET LOCAL ROLE service_role"]);expect(pool.client.commands.at(-2)?.sql).toBe('SET CONSTRAINTS ALL IMMEDIATE');expect(pool.client.commands.at(-1)?.sql).toBe('COMMIT');expect(pool.client.releases).toEqual([undefined]);expect(pool.client.commands.filter(x=>x.sql.startsWith('SELECT'))).toHaveLength(1);});
 it('fixed install casts and actor binding preserve parameter order',async()=>{const {repo,pool}=setup('install');await call(repo,'install');expect(pool.client.commands[5]).toEqual({sql:'SELECT public.mode_install_flow($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::uuid,$6::text,$7::text,$8::jsonb,$9::text) AS result',values:[actor.userId,scope.tenantId,scope.flowId,id(4),id(4),'iframe','local-test',JSON.stringify(parents),key]});});
 it.each(methods)('%s rejects request authority fields before checkout',async method=>{const {repo,pool}=setup(method);expect(await call(repo,method,{...requests[method],actorId:id(9)})).toMatchObject({code:'INVALID_REQUEST',transaction:'not_started'});expect(pool.connects).toBe(0);});
 it.each(['uppercase','newline','short'])('rejects malformed UUID %s before SQL',async kind=>{const {repo,pool}=setup();const flowId=kind==='uppercase'?'AAAAAAAA-AAAA-4AAA-8AAA-AAAAAAAAAAAA':kind==='newline'?scope.flowId+'\n':scope.flowId.slice(1);expect(await repo.publish(actor,{...requests.publish,flowId})).toMatchObject({code:'INVALID_REQUEST'});expect(pool.connects).toBe(0);});
 it.each(['\n','\r','\r\n','\u2028','\u2029'])('key suffix %j rejected',async suffix=>{const {repo}=setup();expect(await repo.publish(actor,{...requests.publish,idempotencyKey:key+suffix})).toMatchObject({code:'INVALID_REQUEST'});});
});

describe('descriptor-safe copied inputs and registry',()=>{
 it.each(['getter','proxy','revoked','symbol','cycle','array'])('rejects %s without supplied code execution',async kind=>{let hits=0;let r:any={...requests.publish};if(kind==='getter')Object.defineProperty(r,'flowId',{enumerable:true,get(){hits++;return scope.flowId;}});if(kind==='proxy')r=new Proxy(r,{ownKeys(){hits++;throw Error();}});if(kind==='revoked'){const p=Proxy.revocable(r,{});p.revoke();r=p.proxy;}if(kind==='symbol')r[Symbol('x')]=1;if(kind==='cycle')r.extra=r;if(kind==='array')r=[];const{repo,pool}=setup();expect(await repo.publish(actor,r)).toMatchObject({code:'INVALID_REQUEST'});expect(pool.connects).toBe(0);expect(hits).toBe(0);});
 it('copier rejects actor depth and oversized origin array before descendant reflection',async()=>{
  vi.resetModules();const original=Object.getOwnPropertyDescriptor;const touched:object[]=[];const spy=vi.spyOn(Object,'getOwnPropertyDescriptor').mockImplementation((obj,key)=>{touched.push(obj);return original(obj,key);});
  try{const {createModeContracts:isolated}=await import('../server/mode-installation-contracts');const contracts=isolated([profile]);const nested={child:{value:'x'}};expect(()=>contracts.copyInput('publish',{mode:'local_synthetic',userId:nested},requests.publish)).toThrow();expect(touched.includes(nested)).toBe(false);const list=Array.from({length:21},()=>({value:'x'}));const page={installations:[{...row,allowedParentOrigins:list}],nextCursor:null};const input=contracts.copyInput('ownerInstallations',actor,requests.ownerInstallations);touched.length=0;expect(()=>contracts.parseResult('ownerInstallations',select(page),input)).toThrow();expect(list.some(item=>touched.includes(item))).toBe(false);const copied=contracts.copyInput('publish',actor,requests.publish);expect(Object.isFrozen(copied)).toBe(true);}finally{spy.mockRestore();vi.resetModules();}
 });
 it('nested parent getter is not invoked and sparse/extra/oversize arrays reject',async()=>{for(const kind of ['getter','sparse','extra','large']){let hits=0;const list:any=[...parents];if(kind==='getter')Object.defineProperty(list,'0',{enumerable:true,get(){hits++;return parents[0];}});if(kind==='sparse')delete list[0];if(kind==='extra')list.foo='bar';if(kind==='large')list.length=21;const{repo}=setup('install');expect(await repo.install(actor,{...requests.install,allowedParentOrigins:list})).toMatchObject({code:'INVALID_REQUEST'});expect(hits).toBe(0);}});
 it('copies nested input and registry before delayed checkout',async()=>{const pool=new FakePool(),clock=new Clock(),profiles=[clone(profile)],r=clone(requests.install),a={...actor},gate=deferred<Client>();pool.pending=gate.promise;pool.client.data=clone(responses.install);const repo=create({pool,clock,profiles});const pending=repo.install(a,r);a.userId=id(9);r.allowedParentOrigins[0]='https://attacker.example';profiles[0]!.apiOrigin='https://attacker.example';gate.resolve(pool.client);const result=await pending;expect(result).toMatchObject({kind:'committed',receipt:{actorId:actor.userId,allowedParentOrigins:parents}});expect(pool.client.commands[5]?.values?.[0]).toBe(actor.userId);});
 it.each(['install','updatePolicy'] as const)('%s uses captured serializer after delayed acquisition',async method=>{const{repo,pool}=setup(method);const gate=deferred<Client>();pool.pending=gate.promise;const data=clone(responses[method]);pool.client.hook=sql=>sql.startsWith('SELECT')?select(data):undefined;const pending=call(repo,method);const original=JSON.stringify;const spy=vi.spyOn(JSON,'stringify').mockImplementation(((value:any,...rest:any[])=>Array.isArray(value)?'"tampered"':(original as any)(value,...rest)) as any);let result:any;try{gate.resolve(pool.client);result=await pending;}finally{spy.mockRestore();}expect(result.kind).toBe('committed');expect(pool.client.commands[5]?.values?.[method==='install'?7:6]).toBe(original(parents));});
 it('canonicalizes unsorted unique input but rejects duplicate parents',async()=>{const {repo,pool}=setup('install');const list=['https://z.example','https://a.example'];pool.client.data={...responses.install,allowedParentOrigins:[...list].sort()};expect(await repo.install(actor,{...requests.install,allowedParentOrigins:list})).toMatchObject({kind:'committed'});expect(pool.client.commands[5]?.values?.[7]).toBe(JSON.stringify([...list].sort()));expect(await repo.install(actor,{...requests.install,allowedParentOrigins:[parents[0],parents[0]]})).toMatchObject({code:'INVALID_REQUEST'});});
 it.each(['https://127.0.0.1','https://[::1]','https://xn--bcher-kva.example','https://0x','https://*.example','https://a;.example'])('S1 excludes %s',async origin=>{const {repo,pool}=setup('install');expect(await repo.install(actor,{...requests.install,allowedParentOrigins:[origin]})).toMatchObject({code:'INVALID_REQUEST'});expect(pool.connects).toBe(0);});
 it.each([profile.rendererOrigin,profile.apiOrigin,profile.portalOrigin])('excludes profile origin %s',async origin=>{const{repo}=setup('install');expect(await repo.install(actor,{...requests.install,allowedParentOrigins:[origin]})).toMatchObject({code:'INVALID_REQUEST'});});
 it('unknown/duplicate/malformed registry entries fail closed',()=>{expect(()=>createModeContracts([profile,profile])).toThrow();expect(()=>createModeContracts([{...profile,apiOrigin:profile.rendererOrigin}])).toThrow();expect(()=>createModeContracts(Array(65).fill(profile))).toThrow();const {repo,pool}=setup('install');return repo.install(actor,{...requests.install,deploymentProfileVersion:'unregistered'}).then(r=>{expect(r).toMatchObject({code:'INVALID_REQUEST'});expect(pool.connects).toBe(0);});});
 it('hostile options wrapper is rejected but trusted native signal uses captured methods',async()=>{let hits=0;const{repo}=setup();const options={get signal(){hits++;return new AbortController().signal;}};expect(await repo.publish(actor,requests.publish,options)).toMatchObject({code:'INVALID_REQUEST'});expect(hits).toBe(0);const signal=new AbortController().signal;Object.defineProperty(signal,'addEventListener',{value:()=>{throw Error('not intrinsic');}});expect(await repo.publish(actor,requests.publish,{signal})).toMatchObject({kind:'committed'});});
});

describe('strict output and historical semantics',()=>{
 it.each(methods)('%s rejects extra result keys with no commit',async method=>{const{repo,pool}=setup(method);pool.client.data.extra='sensitive';expect(await call(repo,method)).toMatchObject({kind:'failed',code:'INTERNAL_ERROR'});expect(pool.client.commands.some(x=>x.sql==='COMMIT')).toBe(false);});
 it.each(['command','rowCount','rows','payload'])('metadata/payload getter %s never executes',async field=>{let hits=0;const{repo,pool}=setup();const result:any=select(clone(responses.publish));if(field==='payload')Object.defineProperty(result.rows[0].result,'versionId',{enumerable:true,get(){hits++;return id(4);}});else Object.defineProperty(result,field,{enumerable:true,get(){hits++;return field==='command'?'SELECT':1;}});pool.client.hook=sql=>sql.startsWith('SELECT')?result:undefined;expect(await call(repo,'publish')).toMatchObject({code:'INTERNAL_ERROR'});expect(hits).toBe(0);});
 it('legitimate class metadata and unrelated metadata getters are ignored',async()=>{const{repo,pool}=setup();class Result{command='SELECT';rowCount=1;rows=[{result:clone(responses.publish)}];get fields(){throw Error('must not read');}}pool.client.hook=sql=>sql.startsWith('SELECT')?new Result():undefined;expect(await call(repo,'publish')).toMatchObject({kind:'committed'});});
 it.each(['actorId','flowId','sourceRevision'])('publish binding %s rejects',async field=>{const{repo,pool}=setup();pool.client.data[field]=field==='sourceRevision'?2:id(9);expect(await call(repo,'publish')).toMatchObject({code:'INTERNAL_ERROR'});});
 it.each(['install','publicPolicy','ownerInstallations','ownerOperation'] as const)('unregistered profile output %s rejects',async method=>{const{repo,pool}=setup(method);if(method==='ownerInstallations')pool.client.data.installations[0].deploymentProfileVersion='unregistered';else if(method==='ownerOperation'){pool.client.data={...responses.install,deploymentProfileVersion:'unregistered'};}else pool.client.data.deploymentProfileVersion='unregistered';const request=method==='ownerOperation'?{...requests.ownerOperation,operation:'install'}:requests[method];expect(await call(repo,method,request)).toMatchObject({code:'INTERNAL_ERROR'});});
 it.each(['rendererOrigin','apiOrigin','loaderUrl'])('public profile mismatch %s rejects',async field=>{const{repo,pool}=setup('publicPolicy');pool.client.data[field]='https://wrong.example';expect(await call(repo,'publicPolicy')).toMatchObject({code:'INTERNAL_ERROR'});});
 it('max-safe apply no-op valid; changed overflow rejected before acquisition',async()=>{const{repo,pool}=setup('applyVersion');pool.client.data={...responses.applyVersion,previousVersionId:id(6),changed:false,targetRevision:Number.MAX_SAFE_INTEGER};const r={...requests.applyVersion,expectedCurrentVersionId:id(6),expectedTargetRevision:Number.MAX_SAFE_INTEGER};expect(await call(repo,'applyVersion',r)).toMatchObject({kind:'committed'});const before=pool.connects;expect(await call(repo,'applyVersion',{...r,newVersionId:id(7)})).toMatchObject({code:'LIMIT_EXCEEDED',transaction:'not_started'});expect(pool.connects).toBe(before);});
 it('recovered no-op can retain revision2, and original request fields are not invented',async()=>{const{repo,pool}=setup('ownerOperation');pool.client.data={...responses.ownerOperation,previousVersionId:id(6),changed:false,targetRevision:2};expect(await call(repo,'ownerOperation')).toMatchObject({kind:'completed',data:{targetRevision:2,changed:false}});});
 it.each([{sequence:1,operation:'apply'},{sequence:2,operation:'install'},{sequence:1,enabled:false},{sequence:3,operation:'policy',policyRevision:2},{sequence:2,operation:'apply',targetRevision:1}])('rejects impossible history %j',async delta=>{const{repo,pool}=setup('ownerHistory');pool.client.data.history[0]={...history,...delta};expect(await call(repo,'ownerHistory')).toMatchObject({code:'INTERNAL_ERROR'});});
 it.each(['ownerInstallations','ownerHistory'] as const)('%s exact cursor and order rules',async method=>{for(const variant of ['empty','short','wrong','duplicate']){const{repo,pool}=setup(method);const field=method==='ownerInstallations'?'installations':'history';const cursor=method==='ownerInstallations'?id(5):1;pool.client.data.nextCursor=cursor;if(variant==='empty')pool.client.data[field]=[];if(variant==='wrong')pool.client.data.nextCursor=method==='ownerInstallations'?id(9):9;if(variant==='duplicate')pool.client.data[field]=[pool.client.data[field][0],clone(pool.client.data[field][0])];expect(await call(repo,method)).toMatchObject({code:'INTERNAL_ERROR'});}const {repo,pool}=setup(method);pool.client.data.nextCursor=method==='ownerInstallations'?id(5):1;expect(await call(repo,method,{...requests[method],limit:1})).toMatchObject({kind:'completed'});});
 it('valid sparse history page follows intrinsic equations without adjacency requirement',async()=>{const{repo,pool}=setup('ownerHistory');pool.client.data.history=[{...history,sequence:4,operation:'policy',policyRevision:4},{...history,sequence:2,operation:'policy',policyRevision:2}];expect(await call(repo,'ownerHistory')).toMatchObject({kind:'completed'});});
});

describe('bounded lifecycle and honest transaction certainty',()=>{
 it('deadline on final BEGIN guard is not_started with no query submitted',async()=>{const{repo,pool,clock}=setup();clock.onRead=()=>{if(clock.reads===5)clock.mono=10000;};expect(await call(repo,'publish')).toMatchObject({code:'DEADLINE',transaction:'not_started',backendMayStillRun:false});expect(pool.client.commands).toEqual([]);expect(pool.client.releases).toHaveLength(1);});
 it.each([4000,10000])('rejected checkout at %s resamples original budget',async elapsed=>{const{repo,pool,clock}=setup();const d=deferred<Client>();pool.pending=d.promise;const pending=call(repo,'publish');clock.advance(elapsed,false);d.reject(Error('private'));expect(await pending).toMatchObject({code:elapsed===4000?'ACQUISITION_TIMEOUT':'DEADLINE',transaction:'not_started'});});
 it('rejected SQL continuation resamples deadline rather than reporting stale domain error',async()=>{const{repo,pool,clock}=setup();pool.client.hook=sql=>{if(sql.startsWith('SELECT')){clock.advance(10000,false);throw Object.assign(Error('FORBIDDEN'),{code:'42501'});}};expect(await call(repo,'publish')).toMatchObject({code:'DEADLINE',transaction:'no_commit_submitted'});expect(pool.client.commands.at(-1)?.sql.startsWith('SELECT')).toBe(true);});
 it('entry-relative acquisition timeout discards delivered late client, no SQL',async()=>{const{repo,pool,clock}=setup();const d=deferred<Client>();pool.pending=d.promise;clock.onRead=()=>{if(clock.reads===3)clock.mono=1000;};const pending=call(repo,'publish');clock.advance(2000);expect(await pending).toMatchObject({code:'ACQUISITION_TIMEOUT',transaction:'not_started'});d.resolve(pool.client);await flush();expect(pool.client.releases).toHaveLength(1);expect(pool.client.releases[0]).toBeInstanceOf(Error);expect(pool.client.commands).toHaveLength(0);});
 it('validation exhaustion does not even call connect',async()=>{const{repo,pool,clock}=setup();clock.onRead=()=>{if(clock.reads===3)clock.mono=3000;};expect(await call(repo,'publish')).toMatchObject({code:'ACQUISITION_TIMEOUT'});expect(pool.connects).toBe(0);});
 it('inflight query deadline consumes late rejection and sends no rollback or commit',async()=>{const{repo,pool,clock}=setup();const d=deferred<unknown>();pool.client.hook=sql=>sql.startsWith('SELECT')?d.promise:undefined;const pending=call(repo,'publish');await flush();clock.advance(10000);expect(await pending).toMatchObject({code:'DEADLINE',transaction:'no_commit_submitted',backendMayStillRun:true});d.reject(Error('late sensitive detail'));await flush();expect(pool.client.commands.at(-1)?.sql.startsWith('SELECT')).toBe(true);expect(pool.client.releases).toHaveLength(1);});
 it.each(['publish','ownerHistory'] as const)('%s COMMIT loss is correctly categorized',async method=>{const{repo,pool}=setup(method);pool.client.hook=sql=>{if(sql==='COMMIT')throw Error('sensitive transport error');};const result=await call(repo,method);expect(result.kind).toBe(method==='publish'?'unknown_commit':'completion_uncertain');expect(method==='publish'?result.receipt:result.data).toBeNull();expect(JSON.stringify(result)).not.toContain('sensitive');expect(pool.connects).toBe(1);});
 it.each(['publish','ownerHistory'] as const)('%s ROLLBACK tag is known rollback',async method=>{const{repo,pool}=setup(method);pool.client.hook=sql=>sql==='COMMIT'?{command:'ROLLBACK'}:undefined;expect(await call(repo,method)).toEqual({kind:'failed',code:'INTERNAL_ERROR',transaction:'rolled_back',backendMayStillRun:false});});
 it.each(['SELECT','missing','getter'])('invalid COMMIT acknowledgement %s never success',async kind=>{let hits=0;const{repo,pool}=setup();pool.client.hook=sql=>{if(sql==='COMMIT'){if(kind==='missing')return{};if(kind==='getter')return{get command(){hits++;return'COMMIT';}};return{command:'SELECT'};}};expect(await call(repo,'publish')).toMatchObject({kind:'unknown_commit'});expect(hits).toBe(0);});
 it.each(['publish','ownerHistory'] as const)('%s known completion after budget withholds data',async method=>{const{repo,pool,clock}=setup(method);pool.client.hook=sql=>{if(sql==='COMMIT'){clock.advance(10000,false);return{command:'COMMIT'};}};expect(await call(repo,method)).toMatchObject({kind:method==='publish'?'committed':'completed',delivery:'withheld',reason:'DEADLINE'});});
 it('late COMMIT acknowledgement never overwrites uncertainty',async()=>{const{repo,pool,clock}=setup();const d=deferred<any>();pool.client.hook=sql=>sql==='COMMIT'?d.promise:undefined;const pending=call(repo,'publish');await flush();clock.advance(10000);const result=await pending;expect(result.kind).toBe('unknown_commit');d.resolve({command:'COMMIT'});await flush();expect(result.kind).toBe('unknown_commit');expect(pool.client.releases).toHaveLength(1);});
 it('trusted signal abort before BEGIN does not acquire; after submit is uncertain',async()=>{for(const afterCommit of [false,true]){const{repo,pool}=setup();const controller=new AbortController();const d=deferred<any>();if(afterCommit)pool.client.hook=sql=>sql==='COMMIT'?d.promise:undefined;else controller.abort();const pending=call(repo,'publish',requests.publish,actor,{signal:controller.signal});await flush();if(afterCommit)controller.abort();expect(await pending).toMatchObject(afterCommit?{kind:'unknown_commit'}:{code:'ABORTED',transaction:'not_started'});if(!afterCommit)expect(pool.connects).toBe(0);else{d.resolve({command:'COMMIT'});await flush();}}});
 it('bad and regressing clocks fail or withhold according to known commit latch',async()=>{for(const stage of ['entry','before','after']){const{repo,pool,clock}=setup();if(stage==='entry')clock.mono=NaN;else pool.client.hook=sql=>{if(sql===(stage==='before'?'SET CONSTRAINTS ALL IMMEDIATE':'COMMIT')){clock.mono=-1;return{command:stage==='before'?'SET':'COMMIT'};}};expect(await call(repo,'publish')).toMatchObject(stage==='after'?{kind:'committed',delivery:'withheld',reason:'CLOCK_UNAVAILABLE'}:{kind:'failed',code:'CLOCK_UNAVAILABLE'});}});
 it('close is bounded/idempotent, consumes late acquisition and rejects new calls',async()=>{const{repo,pool,clock}=setup();const d=deferred<Client>();pool.pending=d.promise;pool.ending=new Promise(()=>{});const pending=call(repo,'publish'),closing=repo.close();expect(repo.close()).toBe(closing);expect(await pending).toMatchObject({code:'CLOSED'});clock.advance(10000);await closing;expect(pool.ends).toBe(1);expect(await call(repo,'publish')).toMatchObject({code:'CLOSED'});d.resolve(pool.client);await flush();expect(pool.client.releases).toHaveLength(1);expect(pool.client.commands).toHaveLength(0);});
 it('active client errors retain listener until end and idle errors are consumed',async()=>{const{repo,pool}=setup();const d=deferred<any>();pool.client.hook=()=>d.promise;pool.client.release=function(e){this.releases.push(e);};const pending=call(repo,'publish');await flush();pool.client.emit('error',Error('private'));pool.client.emit('error',Error('late'));expect(await pending).toMatchObject({code:'CONNECTION_FAILED'});pool.client.emit('end');expect(pool.client.listenerCount('error')).toBe(0);d.reject(Error('late query'));await flush();pool.emit('error',Error('private idle'));});
});

describe('safe errors and local factory',()=>{
 it.each([['42501','FORBIDDEN','FORBIDDEN'],['40001','MODE_CONFLICT','CONFLICT'],['22023','INVALID_OVERRIDE','INVALID_REQUEST'],['0A000','UNSUPPORTED_CONFIG','UNSUPPORTED'],['P0002','SERVICE_UNAVAILABLE','UNAVAILABLE'],['23514','MODE_RECEIPT_BINDING','INTERNAL_ERROR'],['42501','private unknown','INTERNAL_ERROR'],['40P01','private deadlock','DEADLOCK'],['55P03','private lock','LOCK_TIMEOUT'],['57014','private timeout','SERVER_TIMEOUT']])('maps exact %s/%s',async(code,message,expected)=>{const{repo,pool}=setup();pool.client.hook=sql=>{if(sql.startsWith('SELECT'))throw Object.assign(Error(message),{code,detail:'private'});};const result=await call(repo,'publish');expect(result).toMatchObject({code:expected});expect(JSON.stringify(result)).not.toContain('private');});
 it('error accessor is not invoked',async()=>{let hits=0;const{repo,pool}=setup();pool.client.hook=()=>{throw{get code(){hits++;return'42501';},message:'FORBIDDEN'};};expect(await call(repo,'publish')).toMatchObject({code:'INTERNAL_ERROR'});expect(hits).toBe(0);});
 function env(){for(const [k,v]of Object.entries({LOCAL_HARNESS:'1',FLOW_TEST_DISPOSABLE:'1',MODE_INSTALLATIONS_TEST_DISPOSABLE:'1',PGHOST:'127.0.0.1',PGPORT:'55439',PGUSER:'postgres',PGDATABASE:'lumin_installation_s1_transport_unit',PGPASSWORD:'',DATABASE_URL:'',PGHOSTADDR:'',PGSERVICE:'',PGSERVICEFILE:'',PGPASSFILE:'',PGOPTIONS:''}))vi.stubEnv(k,v);}
 it.each(['','postgres'])('factory fixed password callback snapshots synthetic value %j',async password=>{env();vi.stubEnv('PGPASSWORD',password);const pool=new FakePool();vi.mocked(Pool).mockImplementation(function(){return pool as any;});const repo=createLocalModeInstallationRepository();const config=vi.mocked(Pool).mock.calls.at(-1)![0] as any;expect(typeof config.password).toBe('function');vi.stubEnv('PGPASSWORD','later arbitrary');expect(config.password()).toBe(password);expect(config.pipeline).toBe(false);expect(config.ssl).toBe(false);expect(config.query_timeout).toBe(0);await repo.close();});
 it('actual installed pg uses fixed callbacks without configured/default pgpass access',async()=>{
  env();const real=await vi.importActual<typeof import('pg')>('pg');const require=createRequire(import.meta.url);const path=require.resolve('pgpass');const old=require.cache[path];let reads=0;
  require.cache[path]={id:path,filename:path,loaded:true,exports:(_config:unknown,cb:(value:string)=>void)=>{reads++;cb('synthetic-probe-only');}} as any;
  const getPassword=async(client:any)=>{await new Promise<void>((resolve,reject)=>{client.once('error',reject);client._getPassword(resolve);});};
  try{
   for(const configured of [false,true]){vi.stubEnv('PGPASSFILE',configured?'synthetic-unused-path':'');const control=new real.Client({host:'127.0.0.1',user:'postgres',database:'lumin_installation_s1_transport_unit',password:''});const before=reads;await getPassword(control);expect(reads).toBe(before+1);
    for(const password of ['','postgres']){vi.stubEnv('PGPASSFILE','');vi.stubEnv('PGPASSWORD',password);const pool=new FakePool();vi.mocked(Pool).mockImplementation(function(){return pool as any;});const repo=createLocalModeInstallationRepository();const config=vi.mocked(Pool).mock.calls.at(-1)![0] as any;vi.stubEnv('PGPASSFILE',configured?'synthetic-unused-path':'');vi.stubEnv('PGPASSWORD','later-ignored');const client=new real.Client(config);const previous=reads;await getPassword(client);await getPassword(client);expect(reads).toBe(previous);expect((client as any).password).toBe(password);await repo.close();}
    vi.stubEnv('PGPASSWORD','');
   }
  }finally{if(old)require.cache[path]=old;else delete require.cache[path];}
 });
 it.each([['PGPASSWORD','real-secret'],['PGPASSFILE','file'],['PGHOST','example.com'],['PGPORT','05432'],['PGDATABASE','production'],['PGUSER','other'],['LOCAL_HARNESS','0'],['DATABASE_URL','postgres://example']])('factory rejects %s override',async(name,value)=>{env();vi.stubEnv(name,value);const count=vi.mocked(Pool).mock.calls.length;expect(()=>createLocalModeInstallationRepository()).toThrow();expect(vi.mocked(Pool).mock.calls.length).toBe(count);});
});


// Valid frozen schemas cannot reach their byte ceilings: parents<=20*300 ASCII,
// a receipt/input stays<8192 bytes,100 rows<750000,64 profiles<100000.
// Controlled malformed DTOs below deliberately reach copier ceilings while keeping
// depth/nodes/individual strings within their caps. Post-copy schema reflection
// distinguishes a byte-limit rejection from an unrelated schema rejection.
function byteFixture(kind:'single'|'input'|'page'|'registry',target:number){
 const marker='budget-é😀\n"\\';const slots:{object:any;key:string|number}[]=[];
 const list=()=>Array.from({length:20},()=> '');
 let raw:any;
 if(kind==='registry'){raw=Array.from({length:64},()=>{const r:any={_probe:marker};for(let i=0;i<7;i++){r['p'+i]='';slots.push({object:r,key:'p'+i});}return r;});}
 else if(kind==='page'){raw={_probe:marker,bulk:Array.from({length:100},()=>({a:list(),b:list()}))};for(const row of raw.bulk)for(const array of [row.a,row.b])array.forEach((_:unknown,i:number)=>slots.push({object:array,key:i}));}
 else{raw={_probe:marker,a:list(),b:list()};for(const array of [raw.a,raw.b])array.forEach((_:unknown,i:number)=>slots.push({object:array,key:i}));}
 const measured=()=>kind==='registry'?{profiles:raw}:kind==='input'?{actor,request:raw}:raw;
 let remaining=target-Buffer.byteLength(JSON.stringify(measured()),'utf8');expect(remaining).toBeGreaterThanOrEqual(0);
 for(const slot of slots){const n=Math.min(512,remaining);slot.object[slot.key]='x'.repeat(n);remaining-=n;}expect(remaining).toBe(0);expect(Buffer.byteLength(JSON.stringify(measured()),'utf8')).toBe(target);
 return{raw,marker};
}
async function boundaryProbe(kind:'single'|'input'|'page'|'registry',raw:any,marker:string){
 vi.resetModules();const originalKeys=Reflect.ownKeys,originalDescriptor=Object.getOwnPropertyDescriptor,originalBytes=Buffer.byteLength;const originals=new WeakSet<object>();
 const remember=(x:any)=>{if(x&&typeof x==='object'){originals.add(x);for(const k of originalKeys(x))if(k!=='length')remember(originalDescriptor(x,k)?.value);}};remember(raw);
 let schemaVisits=0;const lengths:number[]=[];
 const keys=vi.spyOn(Reflect,'ownKeys').mockImplementation(x=>{if(!originals.has(x)&&originalDescriptor(x,'_probe')?.value===marker)schemaVisits++;return originalKeys(x);});
 const bytes=vi.spyOn(Buffer,'byteLength').mockImplementation(((value:any,encoding:any)=>{const n=originalBytes(value,encoding);lengths.push(n);return n;}) as any);
 try{const{createModeContracts:isolated}=await import('../server/mode-installation-contracts');if(kind==='registry')expect(()=>isolated(raw)).toThrow();else{const contracts=isolated([profile]);if(kind==='input')expect(()=>contracts.copyInput('publish',actor,raw)).toThrow();else{const method=kind==='page'?'ownerHistory':'publish';const input=contracts.copyInput(method,actor,requests[method]);expect(()=>contracts.parseResult(method,select(raw),input)).toThrow();}}return{schemaVisits,lengths};}
 finally{keys.mockRestore();bytes.mockRestore();vi.resetModules();}
}
describe('exact bounded copier evidence',()=>{
 it.each([['single',16384],['input',16384],['page',1048576],['registry',131072]] as const)('%s complete UTF8 boundary is checked before schema',async(kind,cap)=>{for(const delta of [-1,0,1]){const {raw,marker}=byteFixture(kind,cap+delta);const observed=await boundaryProbe(kind,raw,marker);expect(observed.lengths).toContain(cap+delta);expect(observed.schemaVisits>0).toBe(delta<=0);}});
 it('single-result depth4 accepted by copier, depth5 stops before schema',async()=>{for(const over of [false,true]){const marker='depth-boundary';const raw={_probe:marker,nest:{a:{b:{c:over?{d:0}:0}}}};const observed=await boundaryProbe('single',raw,marker);expect(observed.schemaVisits>0).toBe(!over);}});
 it('single-result node256 accepted by copier, node257 stops before serialization/schema',async()=>{for(const over of [false,true]){const marker='node-boundary';const groups=Array.from({length:13},(_,i)=>Array(i<12?20:over?1:0).fill(0));const raw={_probe:marker,groups};const observed=await boundaryProbe('single',raw,marker);expect(observed.schemaVisits>0).toBe(!over);const bytes=Buffer.byteLength(JSON.stringify(raw),'utf8');expect(observed.lengths.includes(bytes)).toBe(!over);}});
 it('supports64 genuine immutable profiles and100 origin-rich installation rows',()=>{const profiles=Array.from({length:64},(_,i)=>({...profile,profileVersion:'profile-'+i}));const contracts=createModeContracts(profiles);const origins=Array.from({length:20},(_,i)=>`https://${String(i).padStart(2,'0')}${'a'.repeat(61)}.${'b'.repeat(63)}.${'c'.repeat(63)}.${'d'.repeat(56)}.test`).sort();const data={installations:Array.from({length:100},(_,i)=>({...row,installationId:id(100+i),deploymentProfileVersion:'profile-'+(i%64),allowedParentOrigins:[...origins]})),nextCursor:id(199)};const input=contracts.copyInput('ownerInstallations',actor,{...requests.ownerInstallations,limit:100});const output=contracts.parseResult('ownerInstallations',select(data),input);expect(output.installations).toHaveLength(100);expect(output.nextCursor).toBe(id(199));expect(Object.isFrozen(output.installations[0]!.allowedParentOrigins)).toBe(true);});
});
