import { describe, it, expect, vi } from 'vitest';
import { EventEmitter } from 'node:events';
import { __createModeOwnerCompositionForTests } from '../server/mode-owner-composition';
const id = (n: number) => `00000000-0000-0000-0000-${String(n).padStart(12, '0')}`;
const profile = { profileVersion: 'local-v1', rendererOrigin: 'https://renderer.mode-owner.test', apiOrigin: 'https://api.mode-owner.test', portalOrigin: 'https://portal.mode-owner.test', loaderUrl: 'https://renderer.mode-owner.test/assets/booking-lumin-loader.' + 'a'.repeat(64) + '.js' };
const config = () => ({ profiles: [profile], credentials: [{ credential: 'synthetic-owner-token', userId: id(1) }], localPortalOrigin: 'http://127.0.0.1:5174' });
const env = () => ({ LOCAL_HARNESS: '1', FLOW_TEST_DISPOSABLE: '1', MODE_INSTALLATIONS_TEST_DISPOSABLE: '1', MODE_SESSIONS_TEST_DISPOSABLE: '1', MODE_OWNER_TEST_DISPOSABLE: '1', PGHOST: '127.0.0.1', PGPORT: '55439', PGUSER: 'postgres', PGDATABASE: 'lumin_mode_owner_journey_unit', PGPASSWORD: '', MODE_OWNER_API_PORT: '8788', MODE_OWNER_DRAFT_PORT: '8789' });
class Pool extends EventEmitter {
    queries: string[] = [];
    end = vi.fn(async () => { });
    async connect() { return { query: async (t: string) => { this.queries.push(t); return { rows: [{ result: { services: [] } }] }; }, release() { }, on() { }, removeListener() { } }; }
}
function setup(c: unknown = config(), e: NodeJS.ProcessEnv = env()) { const pools: Pool[] = [], configs: any[] = []; const result = __createModeOwnerCompositionForTests(c, { environment: e, poolFactory: pc => { configs.push(pc); const p = new Pool(); pools.push(p); return p; } }); return { result, pools, configs }; }
describe('guarded same-database owner composition', () => {
    it('creates exactly three independent bounded pools with identical database identity', async () => { const s = setup(); expect(s.pools).toHaveLength(3); expect(new Set(s.pools).size).toBe(3); for (const c of s.configs)
        expect(c).toMatchObject({ host: '127.0.0.1', port: 55439, user: 'postgres', database: 'lumin_mode_owner_journey_unit', ssl: false, pipeline: false, max: 2, statement_timeout: 5000, lock_timeout: 5000, idle_in_transaction_session_timeout: 1000, query_timeout: 0 }); expect(new Set(s.configs.map(c => c.application_name)).size).toBe(3); expect(s.result.localOwnerApi).toBe('http://127.0.0.1:8788'); expect(s.result.localDraftApi).toBe('http://127.0.0.1:8789'); await s.result.close(); });
    it.each(['', 'postgres'])('fixed password callback captures synthetic %s', async (password) => { const e = env(); e.PGPASSWORD = password; const s = setup(config(), e); e.PGPASSWORD = 'later-not-used'; for (const c of s.configs) {
        expect(typeof c.password).toBe('function');
        expect(c.password()).toBe(password);
    } await s.result.close(); });
    it.each([['LOCAL_HARNESS', '0'], ['FLOW_TEST_DISPOSABLE', '0'], ['MODE_INSTALLATIONS_TEST_DISPOSABLE', '0'], ['MODE_SESSIONS_TEST_DISPOSABLE', '0'], ['MODE_OWNER_TEST_DISPOSABLE', '0'], ['PGHOST', 'database.example'], ['PGUSER', 'other'], ['PGPORT', '05432'], ['PGDATABASE', 'lumin_mode_session_transport_old'], ['PGDATABASE', 'production'], ['PGPASSWORD', 'real'], ['DATABASE_URL', 'postgres://remote'], ['PGPASSFILE', 'file'], ['PGOPTIONS', 'x'], ['PGSERVICE', 'x'], ['PGSERVICEFILE', 'x'], ['PGHOSTADDR', '127.0.0.1'], ['MODE_OWNER_API_PORT', '80'], ['MODE_OWNER_DRAFT_PORT', '8788']])('rejects%s=%s before pool creation', (key, value) => { const e = { ...env(), [key]: value }, factory = vi.fn(); expect(() => __createModeOwnerCompositionForTests(config(), { environment: e, poolFactory: factory })).toThrow('EXPLICIT_LOCAL_MODE_OWNER_REQUIRED'); expect(factory).not.toHaveBeenCalled(); });
    it.each(['http://localhost:5174', 'https://127.0.0.1:5174', 'http://127.0.0.1:8788', 'http://127.0.0.1:5174/', 'https://remote.example:5174'])('rejects physical Portal%s', origin => expect(() => setup({ ...config(), localPortalOrigin: origin })).toThrow());
    it('exposes only seven S1 owner methods and S2 history', async () => { const s = setup(); expect(Object.keys(s.result.owner).sort()).toEqual(['publish', 'install', 'applyVersion', 'updatePolicy', 'ownerInstallations', 'ownerHistory', 'ownerOperation', 'requestHistory'].sort()); expect((s.result as any).pools).toBeUndefined(); expect((s.result.owner as any).publicPolicy).toBeUndefined(); await s.result.close(); });
    it('bounded credential mapping is copied, no fallback or real auth', async () => { const c = config(), s = setup(c); c.credentials[0]!.userId = id(2); expect(await s.result.authenticateOwner('synthetic-owner-token')).toBe(id(1)); expect(await s.result.authenticateOwner('unknown-credential-token')).toBeNull(); await s.result.close(); expect(await s.result.authenticateOwner('synthetic-owner-token')).toBeNull(); });
    it('supports16 identities, rejects17 before descendants', async () => { const c = config(); c.credentials = Array.from({ length: 16 }, (_, i) => ({ credential: 'synthetic-owner-token-' + i, userId: id(i + 1) })); const s = setup(c); expect(await s.result.authenticateOwner('synthetic-owner-token-15')).toBe(id(16)); await s.result.close(); let reads = 0; const bad = Array.from({ length: 17 }, () => ({ get credential() { reads++; return 'x'; } })); expect(() => setup({ ...config(), credentials: bad })).toThrow(); expect(reads).toBe(0); });
    it('empty registry works but physical/profile equality and multiple profiles fail', async () => { const s = setup({ ...config(), profiles: [] }); expect(s.result.profile).toBeNull(); await s.result.close(); expect(() => setup({ ...config(), profiles: [profile, profile] })).toThrow(); expect(() => setup({ ...config(), localPortalOrigin: 'https://localhost:5174', profiles: [{ ...profile, portalOrigin: 'https://localhost:5174' }] })).toThrow(); });
    it('blocks every legacy non-draft RPC before SQL while accepted service read works', async () => { const s = setup(); for (const name of ['publish_bound_flow', 'publish_configurable_flow', 'issue_flow_session', 'submit_flow_request', 'flow_owner_requests', 'owner_roster_snapshot'])
        await expect(s.result.draftRepository.call(name as any, [])).rejects.toMatchObject({ code: 'NOT_AVAILABLE' }); expect(s.pools[2]!.queries).toHaveLength(0); await expect(s.result.draftRepository.call('flow_owner_services', [id(1), id(2)])).resolves.toEqual({ services: [] }); expect(s.pools[2]!.queries.some(t => t.includes('flow_owner_services'))).toBe(true); await s.result.close(); });
    it('closes each pool once and consumes startup pool factory failure', async () => { const s = setup(), a = s.result.close(), b = s.result.close(); expect(a).toBe(b); await a; for (const p of s.pools)
        expect(p.end).toHaveBeenCalledTimes(1); const prior = new Pool(); let n = 0; expect(() => __createModeOwnerCompositionForTests(config(), { environment: env(), poolFactory: () => { if (++n === 2)
            throw Error('private'); return prior; } })).toThrow('MODE_OWNER_STARTUP_FAILED'); await Promise.resolve(); expect(prior.end).toHaveBeenCalledTimes(1); });
});
