import {describe,it,expect} from 'vitest';
import {EventEmitter} from 'node:events';
import {__createPlanningAllocationRepositoryForTests,createLocalPlanningAllocationRepository,type PlanningClock,type PlanningPool,type PlanningClient} from '../server/planning-allocation-repository';
import {planningExpiryMicroseconds,parsePlanningReceipt,type PlanningAllocationOutcome} from '../server/planning-allocation-contracts';
const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const actor={mode:'local_synthetic',userId:id(1)};
const request={tenantId:id(2),bookingId:id(3),crewId:id(4),targetGeneration:1};
const baseReceipt=()=>({schemaVersion:1,groupId:id(5),generation:1,bookingId:id(3),status:'held',usable:true,expiresAt:'2030-01-01T00:00:00.000000Z',bookingState:'draft',confirmed:false});
const row=(receipt:unknown=baseReceipt())=>({command:'SELECT',rowCount:1,rows:[{result:receipt}]});
function deferred<T>(){let resolve!:(v:T)=>void,reject!:(e:unknown)=>void;const promise=new Promise<T>((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};}
async function flush(){for(let i=0;i<40;i++)await Promise.resolve();}
class Clock implements PlanningClock{
 mono=0;now=Date.UTC(2029,0,1);next=0;timers=new Map<number,{at:number;fn:()=>void}>();
 monotonic=()=>this.mono;wall=()=>this.now;
 setTimer=(fn:()=>void,ms:number)=>{const id=++this.next;this.timers.set(id,{at:this.mono+ms,fn});return id;};
 clearTimer=(id:unknown)=>{this.timers.delete(Number(id));};
 advance(ms:number,fire=true){this.mono+=ms;if(fire){for(const [id,t]of [...this.timers])if(t.at<=this.mono){this.timers.delete(id);t.fn();}}}
}
class Client extends EventEmitter implements PlanningClient{
 calls:{sql:string;values?:unknown[]}[]=[];releases:(Error|undefined)[]=[];
 hook?:(text:string,index:number)=>unknown;
 async query(sql:string,values?:unknown[]){this.calls.push({sql,values});const result=this.hook?.(sql,this.calls.length-1);if(result!==undefined)return await result;return sql.startsWith('SELECT')?row():{command:sql.startsWith('BEGIN')?'BEGIN':sql==='COMMIT'?'COMMIT':'SET'};}
 release(error?:Error){this.releases.push(error);if(this.releases.length>1)throw Error('DOUBLE_RELEASE');if(error)this.emit('end');}
}
class Pool extends EventEmitter implements PlanningPool{
 client=new Client();connects=0;endCalls=0;pending?:Promise<PlanningClient>;ending?:Promise<void>;
 async connect(){this.connects++;return this.pending??this.client;}
 async end(){this.endCalls++;await this.ending;}
}
function setup(){const clock=new Clock(),pool=new Pool();return {clock,pool,repo:__createPlanningAllocationRepositoryForTests(pool,clock)};}
const outcome=(v:PlanningAllocationOutcome)=>JSON.stringify(v);
const commands=['BEGIN ISOLATION LEVEL READ COMMITTED',"SET LOCAL statement_timeout='5s'","SET LOCAL lock_timeout='5s'","SET LOCAL idle_in_transaction_session_timeout='1s'",'SET LOCAL ROLE service_role','SELECT public.allocate_planning_group($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::bigint) AS result','SET CONSTRAINTS ALL IMMEDIATE','COMMIT'];
describe('planning allocator immutable contracts',()=>{
 it('uses exact separate commands and committed frozen receipt',async()=>{const {repo,pool}=setup();const result=await repo.allocate(actor,request);expect(pool.client.calls.map(c=>c.sql)).toEqual(commands);expect(pool.client.calls[5]!.values).toEqual([actor.userId,request.tenantId,request.bookingId,request.crewId,1]);expect(result.kind).toBe('committed');expect(Object.isFrozen(result)).toBe(true);if(result.kind==='committed'&&result.receipt)expect(Object.isFrozen(result.receipt)).toBe(true);expect(pool.client.releases).toEqual([undefined]);await repo.close();});
 it.each([null,{}, {...actor,mode:'hosted'}, {...actor,userId:id(1).toUpperCase().replace('0000','ABCD')},{...actor,role:'owner'}])('rejects invalid actor %j',async invalid=>{const {repo,pool}=setup();expect(await repo.allocate(invalid,request)).toMatchObject({kind:'failed',code:'INVALID_REQUEST',transaction:'not_started'});expect(pool.connects).toBe(0);});
 it.each([{...request,targetGeneration:0},{...request,targetGeneration:1.5},{...request,targetGeneration:9007199254740992},{...request,sql:'commit'},{...request,expiresAt:'2030'},{...request,tenantId:'bad'}])('rejects request %j',async invalid=>{const {repo,pool}=setup();expect(await repo.allocate(actor,invalid)).toMatchObject({code:'INVALID_REQUEST'});expect(pool.connects).toBe(0);});
 it('rejects getters without invoking them',async()=>{const {repo,pool}=setup();let read=false;const input={...request};Object.defineProperty(input,'tenantId',{enumerable:true,get(){read=true;return id(2);}});expect(await repo.allocate(actor,input)).toMatchObject({code:'INVALID_REQUEST'});expect(read).toBe(false);expect(pool.connects).toBe(0);});
 it('copies authority and request before every await',async()=>{const {repo,pool}=setup();const wait=deferred<PlanningClient>();pool.pending=wait.promise;const a={...actor},r={...request};const result=repo.allocate(a,r);a.userId=id(99);r.tenantId=id(98);r.targetGeneration=9;wait.resolve(pool.client);await result;expect(pool.client.calls[5]!.values).toEqual([actor.userId,request.tenantId,request.bookingId,request.crewId,1]);});
 it.each(['1900-02-29T00:00:00.000000Z','0000-01-01T00:00:00.000000Z','2028-02-30T00:00:00.000000Z','2028-01-01T24:00:00.000000Z','2028-01-01T00:00:60.000000Z','2028-01-01T00:00:00.000Z','2028-13-01T00:00:00.000000Z'])('rejects invalid date %s',s=>expect(()=>planningExpiryMicroseconds(s)).toThrow());
 it('preserves Gregorian date and exact microseconds',()=>{expect(planningExpiryMicroseconds('1970-01-01T00:00:00.000001Z')).toBe(1n);expect(planningExpiryMicroseconds('1969-12-31T23:59:59.999999Z')).toBe(-1n);expect(planningExpiryMicroseconds('0001-01-01T00:00:00.000000Z')).toBe(-62135596800000000n);expect(planningExpiryMicroseconds('2000-02-29T00:00:00.000000Z')).toBe(BigInt(Date.UTC(2000,1,29))*1000n);expect(planningExpiryMicroseconds('9999-12-31T23:59:59.999999Z')).toBe(253402300799999999n);});
 it.each([{extra:'secret'},{bookingId:id(99)},{generation:2},{status:'released',usable:true},{confirmed:true},{groupId:'bad'},{schemaVersion:2},{expiresAt:'bad'},{bookingState:'confirmed'},{usable:'true'}])('invalid receipt prevents COMMIT %j',async change=>{const {repo,pool}=setup();pool.client.hook=sql=>sql.startsWith('SELECT')?row({...baseReceipt(),...change}):undefined;const result=await repo.allocate(actor,request);expect(result).toMatchObject({kind:'failed',code:'INTERNAL_ERROR',transaction:'no_commit_submitted'});expect(pool.client.calls.some(c=>c.sql==='COMMIT')).toBe(false);expect(pool.client.releases).toHaveLength(1);expect(pool.client.releases[0]).toBeInstanceOf(Error);});
 it('rejects extra row columns, getters and unsupported DTO prototype',()=>{expect(()=>parsePlanningReceipt({...row(),rows:[{result:baseReceipt(),extra:1}]},request)).toThrow();expect(()=>parsePlanningReceipt(row(Object.assign(Object.create({}),baseReceipt())),request)).toThrow();const r=baseReceipt();Object.defineProperty(r,'usable',{get(){throw Error('getter');},enumerable:true});expect(()=>parsePlanningReceipt(row(r),request)).toThrow();});
});
describe('planning allocator lifecycle',()=>{
 it.each(commands.slice(0,-1).map((s,i)=>[i,s]))('failure at stage %s never commits or rolls back',async(index)=>{const {repo,pool}=setup();pool.client.hook=(_s,i)=>{if(i===index)throw Object.assign(Error('ALLOCATION_UNAVAILABLE'),{code:'P0001'});};const result=await repo.allocate(actor,request);expect(result).toMatchObject({kind:'failed',code:'UNAVAILABLE',transaction:'no_commit_submitted',backendMayStillRun:true});expect(pool.client.calls.some(c=>c.sql==='COMMIT'||c.sql==='ROLLBACK')).toBe(false);expect(pool.client.releases).toHaveLength(1);});
 it.each(commands.map((s,i)=>[i,s]))('abort at await %s prevents further SQL',async(index)=>{const {repo,pool}=setup();const d=deferred<unknown>(),abort=new AbortController();pool.client.hook=(_s,i)=>i===index?d.promise:undefined;const pending=repo.allocate(actor,request,{signal:abort.signal});await flush();abort.abort();const result=await pending;expect(result.kind).toBe(index===7?'unknown_commit':'failed');expect(pool.client.calls).toHaveLength(Number(index)+1);d.resolve({command:index===7?'COMMIT':'SET'});await flush();expect(pool.client.calls).toHaveLength(Number(index)+1);expect(pool.client.releases).toHaveLength(1);});
 it('acquisition expires at three seconds and consumes/discards late client',async()=>{const {repo,pool,clock}=setup();const d=deferred<PlanningClient>();pool.pending=d.promise;const pending=repo.allocate(actor,request);clock.advance(2999);await flush();expect(pool.client.releases).toHaveLength(0);clock.advance(1);expect(await pending).toMatchObject({code:'ACQUISITION_TIMEOUT',transaction:'not_started',backendMayStillRun:false});d.resolve(pool.client);await flush();expect(pool.client.calls).toHaveLength(0);expect(pool.client.releases).toHaveLength(1);});
 it('validation exhausting acquisition budget never starts checkout',async()=>{const {repo,pool,clock}=setup();const proxy=new Proxy({...request},{ownKeys(target){clock.advance(1600,false);return Reflect.ownKeys(target);}});expect(await repo.allocate(actor,proxy)).toMatchObject({code:'ACQUISITION_TIMEOUT'});expect(pool.connects).toBe(0);});
 it('original total budget is not reset by acquisition or stages',async()=>{const {repo,pool,clock}=setup();const acquired=deferred<PlanningClient>(),stage=deferred<unknown>();pool.pending=acquired.promise;const result=repo.allocate(actor,request);clock.advance(2000);acquired.resolve(pool.client);pool.client.hook=sql=>sql.startsWith('SELECT')?stage.promise:undefined;await flush();clock.advance(7999);expect(pool.client.releases).toHaveLength(0);clock.advance(1);expect(await result).toMatchObject({code:'DEADLINE',transaction:'no_commit_submitted'});stage.reject(Error('late sensitive error'));await flush();});
 it('input validation time consumes acquisition budget',async()=>{const {repo,pool,clock}=setup();pool.pending=new Promise(()=>{});const proxy=new Proxy({...request},{ownKeys(target){clock.advance(1000,false);return Reflect.ownKeys(target);}});const pending=repo.allocate(actor,proxy);clock.advance(3000-clock.mono);expect(await pending).toMatchObject({code:'ACQUISITION_TIMEOUT'});});
 it('COMMIT failure is uncertain and has no receipt/raw details',async()=>{const {repo,pool}=setup();pool.client.hook=sql=>{if(sql==='COMMIT')throw Object.assign(Error('secret query parameters'),{code:'23514',detail:'secret'});};const result=await repo.allocate(actor,request);expect(result).toEqual({kind:'unknown_commit',code:'COMMIT_UNCERTAIN',receipt:null,reconciliation:'REAUTHORIZE_SAME_TARGET'});expect(outcome(result)).not.toContain('secret');});
 it.each(['ROLLBACK','SELECT'])('COMMIT tag %s is never success',async tag=>{const {repo,pool}=setup();pool.client.hook=sql=>sql==='COMMIT'?{command:tag}:undefined;const result=await repo.allocate(actor,request);expect(result.kind).toBe(tag==='ROLLBACK'?'failed':'unknown_commit');if(tag==='ROLLBACK')expect(result).toMatchObject({transaction:'rolled_back',backendMayStillRun:false});});
 it('late timer delivery after acknowledged COMMIT withholds known committed receipt',async()=>{const {repo,pool,clock}=setup();pool.client.hook=sql=>{if(sql==='COMMIT'){clock.advance(10001,false);return {command:'COMMIT'};}};expect(await repo.allocate(actor,request)).toEqual({kind:'committed',delivery:'withheld',receipt:null,reason:'DEADLINE'});});
 it('late COMMIT acknowledgement cannot replace settled uncertainty',async()=>{const {repo,pool,clock}=setup();const d=deferred<unknown>();pool.client.hook=sql=>sql==='COMMIT'?d.promise:undefined;const pending=repo.allocate(actor,request);await flush();clock.advance(10000);const result=await pending;expect(result.kind).toBe('unknown_commit');d.resolve({command:'COMMIT'});await flush();expect(result.kind).toBe('unknown_commit');expect(pool.client.releases).toHaveLength(1);});
 it('client errors settle once; late error is handled until end',async()=>{const {repo,pool}=setup();const d=deferred<unknown>();pool.client.hook=()=>d.promise;pool.client.release=function(error?:Error){this.releases.push(error);};const pending=repo.allocate(actor,request);await flush();pool.client.emit('error',Error('secret'));pool.client.emit('error',Error('duplicate'));expect(await pending).toMatchObject({code:'CONNECTION_FAILED'});expect(pool.client.releases).toHaveLength(1);pool.client.emit('end');expect(pool.client.listenerCount('error')).toBe(0);d.reject(Error('late'));await flush();pool.emit('error',Error('idle secret'));});
 it('close aborts operations and has bounded idempotent pool shutdown',async()=>{const {repo,pool,clock}=setup();pool.pending=new Promise(()=>{});pool.ending=new Promise(()=>{});const pending=repo.allocate(actor,request);const closing=repo.close();expect(await pending).toMatchObject({code:'ABORTED'});expect(repo.close()).toBe(closing);clock.advance(10000);await closing;expect(pool.endCalls).toBe(1);expect(await repo.allocate(actor,request)).toMatchObject({code:'ABORTED'});expect(pool.connects).toBe(1);});
 it.each([['40001','unrecognized','INTERNAL_ERROR'],['40001','ALLOCATION_EVIDENCE_CHANGED','EVIDENCE_CHANGED'],['40P01','secret','DEADLOCK'],['55P03','secret','LOCK_TIMEOUT'],['57014','secret','SERVER_TIMEOUT']])('sanitizes exact error inventory %s/%s',async(code,message,expected)=>{const {repo,pool}=setup();pool.client.hook=()=>{throw Object.assign(Error(message),{code});};expect(await repo.allocate(actor,request)).toMatchObject({kind:'failed',code:expected});});
});
describe('planning allocator conservative clock',()=>{
 it.each([-1,0,1])('exact expiry comparison at offset %s microseconds',async offset=>{const {repo,pool,clock}=setup();clock.now=0;const expiry=offset<0?'1969-12-31T23:59:59.999999Z':offset===0?'1970-01-01T00:00:00.000000Z':'1970-01-01T00:00:00.000001Z';pool.client.hook=sql=>sql.startsWith('SELECT')?row({...baseReceipt(),expiresAt:expiry}):undefined;const result=await repo.allocate(actor,request);expect(result).toMatchObject({receipt:{usable:offset>0,expiresAt:expiry}});});
 it('backward wall step cannot extend expiry, never upgrades SQL false',async()=>{const {repo,pool,clock}=setup();clock.now=1000;pool.client.hook=sql=>{if(sql.startsWith('SELECT'))return row({...baseReceipt(),expiresAt:'1970-01-01T00:00:01.001000Z'});if(sql==='COMMIT'){clock.now=-100000;clock.advance(2,false);return {command:'COMMIT'};}};expect(await repo.allocate(actor,request)).toMatchObject({receipt:{usable:false}});const other=setup();other.pool.client.hook=sql=>sql.startsWith('SELECT')?row({...baseReceipt(),usable:false}):undefined;expect(await other.repo.allocate(actor,request)).toMatchObject({receipt:{usable:false}});});
 it('forward wall jump downgrades without changing expiry',async()=>{const {repo,pool,clock}=setup();pool.client.hook=sql=>{if(sql==='COMMIT'){clock.now=Date.UTC(2031,0,1);return {command:'COMMIT'};}};expect(await repo.allocate(actor,request)).toMatchObject({receipt:{usable:false,expiresAt:baseReceipt().expiresAt}});});
 it.each([NaN,Infinity,-1])('bad initial monotonic %s prevents acquisition',async n=>{const {repo,pool,clock}=setup();clock.mono=n;expect(await repo.allocate(actor,request)).toMatchObject({kind:'failed',code:'INTERNAL_ERROR'});expect(pool.connects).toBe(0);});
 it('clock regression before COMMIT fails; after acknowledged COMMIT withholds',async()=>{for(const stage of ['SET CONSTRAINTS ALL IMMEDIATE','COMMIT']){const {repo,pool,clock}=setup();pool.client.hook=sql=>{if(sql===stage){clock.mono=-1;return {command:stage==='COMMIT'?'COMMIT':'SET'};}};const result=await repo.allocate(actor,request);expect(result.kind).toBe(stage==='COMMIT'?'committed':'failed');if(stage==='COMMIT')expect(result).toMatchObject({delivery:'withheld',reason:'CLOCK_UNAVAILABLE'});}});
 it('local factory fails closed without explicit disposable activation',()=>{const previous=process.env.LOCAL_HARNESS;delete process.env.LOCAL_HARNESS;try{expect(()=>createLocalPlanningAllocationRepository()).toThrow('EXPLICIT_LOCAL_DISPOSABLE_REQUIRED');}finally{if(previous!==undefined)process.env.LOCAL_HARNESS=previous;}});
});
