import {act,cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {afterEach,expect,it,vi} from 'vitest';
import App from './App';
const id='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222';
function published(name='Published V9 route'){return {versionId:id,renderSchemaVersion:9,submissionMode:'paid_journey_customer_field_request',paymentMode:'staging_mock',simulated:true,service:{id,name:'Housekeeping route service',durationMinutes:60,price:{amount:12500,currency:'USD'}},form:{name,presentation:{accentColor:'#0f766e',layout:'compact'},journey:{schemaVersion:1,stages:['service','options','schedule','information','review_payment','confirmation'].map(kind=>({id:kind,kind,label:kind,enabled:kind!=='options'}))},customerFields:[{id:'custom_gate',kind:'text',label:'Gate information',required:false,maxLength:100}],fieldBindings:[{fieldId:'custom_gate',stageId:'information'}]}};}
const response=(data:unknown)=>new Response(JSON.stringify({ok:true,data}),{status:200});
function setup(pathname:string,env='staging'){vi.stubGlobal('location',{protocol:'https:',origin:'https://checkout.example',pathname});vi.stubEnv('BASE_URL','/checkout/');vi.stubEnv('VITE_RUNTIME_ENV',env);vi.stubEnv('VITE_RUNTIME_MODE','supabase');vi.stubEnv('VITE_SUPABASE_URL','https://child.supabase.co');vi.stubEnv('VITE_SUPABASE_PUBLISHABLE_KEY','sb_publishable_stagingpublic');vi.stubEnv('VITE_TENANT_ID',id);vi.stubEnv('VITE_FLOW_API_URL','https://api.example');}
afterEach(()=>{cleanup();vi.unstubAllGlobals();vi.unstubAllEnvs();vi.restoreAllMocks();});
it.each(['/checkout/journey-fields/flow/'+id,'/journey-fields/flow/'+id,'/checkout/journey-fields/flow/'+id+'/'])('dispatches exact V9 presentation route %s through actual origin-bound SDK only',async path=>{setup(path);const fetcher=vi.fn<typeof fetch>(async()=>response(published()));vi.stubGlobal('fetch',fetcher);render(<App/>);await screen.findByRole('heading',{name:'Published V9 route'});expect(screen.getByText('$125.00')).toBeVisible();expect(fetcher).toHaveBeenCalledTimes(1);expect(fetcher.mock.calls[0]![0]).toBe('https://api.example/api/public/paid-journey-customer-field-installations/'+id+'/render');expect(fetcher.mock.calls[0]![1]?.method).toBe('GET');expect(fetcher.mock.calls[0]![1]?.headers).toEqual({Origin:'https://checkout.example'});expect(screen.getByRole('button',{name:'Booking submission not connected yet'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'Next preview step'}));fireEvent.click(screen.getByRole('button',{name:'Next preview step'}));expect(screen.getByLabelText('Gate information')).toBeVisible();expect(fetcher).toHaveBeenCalledTimes(1);expect(screen.queryByRole('button',{name:'Open booking form'})).toBeNull();});
it.each(['v8','unsupported-mode','denied','network'])('never launches legacy sessions after %s on the V9 route',async kind=>{setup('/checkout/journey-fields/flow/'+id);const fetcher=vi.fn(async()=>{if(kind==='network')throw Error('private diagnostic');if(kind==='denied')return new Response(JSON.stringify({ok:false,code:'NOT_AVAILABLE'}),{status:404});const value:any=published();if(kind==='v8')value.renderSchemaVersion=8;else value.submissionMode='paid_journey_request';return response(value);});vi.stubGlobal('fetch',fetcher);render(<App/>);await screen.findByRole('alert');expect(fetcher).toHaveBeenCalledTimes(1);expect(document.body.textContent).not.toContain('private diagnostic');expect(screen.queryByText('Housekeeping route service')).toBeNull();expect(screen.queryByText('Detailing quote')).toBeNull();});
it.each(['/checkout/journey-fields/flow/not-a-uuid','/checkout/journey-fields/flow/'+id+'/extra','/checkout/journey-fields/unknown'])('invalid V9 path %s fails closed without demo or legacy',async path=>{setup(path);const fetcher=vi.fn();vi.stubGlobal('fetch',fetcher);render(<App/>);await screen.findByRole('alert');expect(fetcher).not.toHaveBeenCalled();expect(screen.queryByRole('navigation',{name:'Checkout progress'})).toBeNull();});
it('changing V9 installation A-B-A ignores old bodies and keeps current presentation only',async()=>{setup('/checkout/journey-fields/flow/'+id);const pending:Array<(r:Response)=>void>=[];const fetcher=vi.fn<typeof fetch>(()=>new Promise(resolve=>pending.push(resolve)));vi.stubGlobal('fetch',fetcher);const view=render(<App/>);await waitFor(()=>expect(pending).toHaveLength(1));setup('/checkout/journey-fields/flow/'+other);view.rerender(<App/>);await waitFor(()=>expect(pending).toHaveLength(2));setup('/checkout/journey-fields/flow/'+id);view.rerender(<App/>);await waitFor(()=>expect(pending).toHaveLength(3));await act(async()=>{pending[0]!(response(published('Old route A')));pending[1]!(response(published('Old route B')));pending[2]!(response(published()));});await screen.findByRole('heading',{name:'Published V9 route'});expect(screen.queryByText('Old route A')).toBeNull();expect(screen.queryByText('Old route B')).toBeNull();expect(fetcher.mock.calls.every(([,request])=>request?.method==='GET')).toBe(true);});
it('staging to production context immediately hides the prior V9 render without fallback',async()=>{setup('/checkout/journey-fields/flow/'+id);const fetcher=vi.fn(async()=>response(published()));vi.stubGlobal('fetch',fetcher);const view=render(<App/>);await screen.findByRole('heading',{name:'Published V9 route'});setup('/checkout/journey-fields/flow/'+id,'production');view.rerender(<App/>);await screen.findByRole('alert');expect(screen.queryByText('Housekeeping route service')).toBeNull();expect(fetcher).toHaveBeenCalledTimes(1);});
it('preserves explicit V8 route and does not probe V9 or issue any automatic session',async()=>{setup('/checkout/journey/flow/'+id);const fetcher=vi.fn();vi.stubGlobal('fetch',fetcher);render(<App/>);await screen.findByRole('button',{name:'Open booking form'});expect(fetcher).not.toHaveBeenCalled();expect(screen.queryByText(/Read-only published preview/)).toBeNull();});
it.each([['/checkout/journey-fields','/'],['/checkout/journey-fields','/checkout/'],['/journey-fields','/'],['/journey-fields','/checkout/']])('bare V9 namespace %s at base %s rejects before any connected or legacy read',async(path,base)=>{setup(path);vi.stubEnv('BASE_URL',base);const fetcher=vi.fn();vi.stubGlobal('fetch',fetcher);render(<App/>);expect(await screen.findByRole('alert')).toHaveTextContent('This staging presentation URL is invalid');await act(async()=>{await new Promise(resolve=>setTimeout(resolve,25));});expect(fetcher).not.toHaveBeenCalled();expect(screen.queryByRole('heading',{name:'Request a service'})).toBeNull();expect(screen.queryByRole('navigation',{name:'Checkout progress'})).toBeNull();});
