/** Independent actual-driver tests; synthetic local identity, never hosted activation. */
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {createRequire} from 'node:module';
import net from 'node:net';
import {Client,Pool,type PoolClient} from 'pg';
import {createLocalModeInstallationRepository,__createModeInstallationRepositoryForTests as create} from './mode-installation-repository';
import {profile,config,pool,observer,seed,actor,scope,publish,recovery,install,state,blocker,blocked,gone,pid,observe,pause,commitFixture,lateFault,lateHistoryFault,type Fixture} from './mode-installation-transport-fixtures';
type Hook=(client:PoolClient,text:string,values:unknown[]|undefined,run:()=>Promise<any>)=>Promise<any>;
type RecordEntry={pid:number,commands:string[],releases:boolean[]};
type Attempt={state:'pending'|'rejected'|'returned';record?:RecordEntry};
type Clock={monotonic():number;setTimer(fn:()=>void,ms:number):unknown;clearTimer(handle:unknown):void};
function tracked(real:Pool,hook?:Hook,afterAcquire?:()=>Promise<void>,profiles:readonly any[]=[profile],clock?:Clock){const records:RecordEntry[]=[];const attempts:Attempt[]=[];const facade={
 async connect(){const attempt:Attempt={state:'pending'};attempts.push(attempt);let client:PoolClient;try{client=await real.connect();}catch(error){attempt.state='rejected';throw error;}const record={pid:pid(client),commands:[] as string[],releases:[] as boolean[]};records.push(record);attempt.record=record;if(afterAcquire)await afterAcquire();attempt.state='returned';return {
 query(text:string,values?:unknown[]){record.commands.push(text);const run=()=>client.query(text,values);return hook?hook(client,text,values,run):run();},release(error?:Error){record.releases.push(Boolean(error));client.release(error);},on(name:string,fn:any){client.on(name as 'error'|'end',fn);return this;},removeListener(name:string,fn:any){client.removeListener(name as 'error'|'end',fn);return this;}};},end:()=>real.end(),on(name:string,fn:any){real.on(name as 'error',fn);return this;},removeListener(name:string,fn:any){real.removeListener(name as 'error',fn);return this;}};
 return {repository:create({pool:facade,profiles,...(clock?{clock}:{})}),records,attempts,real};}
function receipt(out:any){assert.equal(out.kind,'committed');assert.equal(out.delivery,'receipt');assert.ok(out.receipt);assert.ok(Object.isFrozen(out)&&Object.isFrozen(out.receipt));return out.receipt;}
function data(out:any){assert.equal(out.kind,'completed');assert.equal(out.delivery,'data');assert.ok(out.data);assert.ok(Object.isFrozen(out)&&Object.isFrozen(out.data));return out.data;}
function failed(out:any,code?:string){assert.equal(out.kind,'failed');if(code)assert.equal(out.code,code);assert.equal('receipt'in out,false);assert.equal('data'in out,false);}
function deferred(){let resolve!:()=>void;const promise=new Promise<void>(r=>resolve=r);return {promise,resolve};}
async function phase(ready:Promise<void>,outcome:Promise<unknown>,label:string){let timer:ReturnType<typeof setTimeout>|undefined;try{await Promise.race([ready,outcome.then(out=>{throw Error(label+' returned before phase: '+JSON.stringify(out));}),new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(Error(label+' phase deadline')),4000);})]);}finally{if(timer)clearTimeout(timer);}}
const isCommit=(text:string)=>text==='COMMIT';
const c=await observer();const resources:Array<()=>Promise<unknown>>=[];const errors:unknown[]=[];const unhandled=(error:unknown)=>errors.push(error);process.on('unhandledRejection',unhandled);
function make(hook?:Hook,real=pool(),afterAcquire?:()=>Promise<void>,profiles:readonly any[]=[profile],clock?:Clock){const r=tracked(real,hook,afterAcquire,profiles,clock);resources.push(()=>r.repository.close());return r;}
async function acquired(r:ReturnType<typeof make>){await observe(async()=>r.records.length>0,'actual repository checkout');return r.records.at(-1)!.pid;}
async function drain(r:ReturnType<typeof make>){await observe(async()=>r.attempts.length===1&&r.real.waitingCount===0&&(r.attempts[0]!.state==='rejected'||(r.attempts[0]!.state==='returned'&&r.attempts[0]!.record!.releases.length>0)),'driver rejection or delivered-client disposal');const a=r.attempts[0]!;if(a.state==='rejected'){assert.equal(a.record,undefined);assert.deepEqual(r.records,[]);}else{assert.equal(a.state,'returned');assert.equal(r.records.length,1);assert.deepEqual(a.record!.commands,[]);assert.deepEqual(a.record!.releases,[true]);}}
async function prepared(f:Fixture){const r=make();return receipt(await r.repository.publish(actor(f),publish(f)));}
/** Actual PostgreSQL protocol frames, with CommandComplete COMMIT and ReadyForQuery dropped. */
async function lossProxy(){const sockets=new Set<net.Socket>();let sawCommit=false,sawReady=false;const server=net.createServer(front=>{const back=net.connect({host:config().host,port:config().port!});sockets.add(front);sockets.add(back);let pending=Buffer.alloc(0),dropping=false;const close=()=>{front.destroy();back.destroy();};front.on('error',close);back.on('error',close);front.on('close',()=>{sockets.delete(front);back.destroy();});back.on('close',()=>{sockets.delete(back);front.destroy();});front.on('data',b=>back.write(b));back.on('data',b=>{pending=Buffer.concat([pending,b]);while(pending.length>=5){const length=pending.readInt32BE(1);assert.ok(length>=4&&length<=1_048_576);if(pending.length<length+1)return;const frame=pending.subarray(0,length+1);pending=pending.subarray(length+1);if(frame[0]===67&&frame.subarray(5).toString('utf8')==='COMMIT\0'){sawCommit=true;dropping=true;}if(dropping){if(frame[0]===90){sawReady=true;close();}continue;}front.write(frame);}});});await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));return {port:(server.address()as net.AddressInfo).port,get sawCommit(){return sawCommit;},get sawReady(){return sawReady;},async close(){for(const socket of sockets)socket.destroy();await new Promise<void>(resolve=>server.close(()=>resolve()));}};}
/** Exercise installed driver's real password branch without reading any credential file. */
async function passwordProbe(factoryOptions:any){const require=createRequire(import.meta.url);const loader=require('node:module') as {_load:(...args:any[])=>any};const original=loader._load;const saved=process.env.PGPASSWORD;let discoveries=0;const clients:Client[]=[];loader._load=function(name:string,...args:any[]){if(name==='pgpass'){discoveries++;return (_parameters:unknown,done:(value:undefined)=>void)=>done(undefined);}return Reflect.apply(original,this,[name,...args]);};
 const get=async(client:Client)=>{await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>{client.removeListener('error',bad);reject(Error('password probe bounded deadline'));},2000);const bad=(error:Error)=>{clearTimeout(timer);reject(error);};client.once('error',bad);(client as any)._getPassword(()=>{clearTimeout(timer);client.removeListener('error',bad);resolve();});});};
 try{delete process.env.PGPASSWORD;const control=new Client({...config(),password:''});clients.push(control);await get(control);assert.equal(discoveries,1,'positive control must discover pgpass');discoveries=0;assert.equal(typeof factoryOptions.password,'function');const candidate=new Client(factoryOptions);clients.push(candidate);process.env.PGPASSWORD='forbidden_test_value';await get(candidate);assert.equal(discoveries,0,'actual factory callback must bypass pgpass');assert.equal((candidate as any).password,saved??'','callback uses validated immutable snapshot');await get(candidate);assert.equal(discoveries,0,'subsequent password state stays a string, no fallback');}
 finally{loader._load=original;if(saved===undefined)delete process.env.PGPASSWORD;else process.env.PGPASSWORD=saved;for(const client of clients)await client.end();}}
try{
 // Public factory, not just internal seam. Capture its actual Pool options for driver fallback proof.
 const f=await seed(c);let factoryOptions:any;const originalConnect=Pool.prototype.connect;(Pool.prototype as any).connect=function(...args:any[]){factoryOptions=(this as any).options;return Reflect.apply(originalConnect,this,args);};let publicRepo:ReturnType<typeof createLocalModeInstallationRepository>;let pub:any;
 try{publicRepo=createLocalModeInstallationRepository({profiles:[profile]});resources.push(()=>publicRepo.close());pub=receipt(await publicRepo.publish(actor(f),publish(f)));}finally{Pool.prototype.connect=originalConnect;}
 await passwordProbe(factoryOptions);const initial=await state(c,f);await publicRepo!.close();const restarted=createLocalModeInstallationRepository({profiles:[profile]});resources.push(()=>restarted.close());assert.deepEqual(data(await restarted.ownerOperation(actor(f),recovery(f,'publish'))),pub);assert.deepEqual(await state(c,f),initial);
 console.log('PASS actual public factory/restart/recovery and installed-driver password callback bypass with no-file positive control');
 const r=make();const installed=receipt(await r.repository.install(actor(f),install(f,pub.versionId)));const id=installed.installationId;
 const unchanged=receipt(await r.repository.applyVersion(actor(f),{...scope(f),installationId:id,expectedTargetRevision:1,expectedCurrentVersionId:pub.versionId,newVersionId:pub.versionId,idempotencyKey:'transport_apply_noop'}));assert.equal(unchanged.changed,false);
 const changed=receipt(await r.repository.updatePolicy(actor(f),{...scope(f),installationId:id,expectedPolicyRevision:1,enabled:true,allowedParentOrigins:['https://other-merchant.test'],idempotencyKey:'transport_policy_01'}));assert.equal(changed.changed,true);assert.equal(changed.policyRevision,2);
 const listing=data(await r.repository.ownerInstallations(actor(f),{...scope(f),afterId:null,limit:100}));assert.equal(listing.installations.length,1);assert.equal(listing.installations[0].installationId,id);
 const history=data(await r.repository.ownerHistory(actor(f),{...scope(f),installationId:id,beforeSequence:null,limit:100}));assert.equal(history.history.length,2);assert.equal(history.history[0].sequence,2);
 assert.deepEqual(data(await r.repository.ownerOperation(actor(f),recovery(f,'install','transport_install_01'))),installed);
 const policy=data(await r.repository.publicPolicy({installationId:id}));assert.equal(policy.allowedParentOrigins[0],'https://other-merchant.test');assert.equal(policy.rendererOrigin,profile.rendererOrigin);assert.equal('actorId'in policy,false);assert.equal('tenantId'in policy,false);
 assert.equal(new Set(r.records.map(x=>x.pid)).size,1,'healthy sequential calls must reuse clean client');assert.ok(r.records.every(x=>x.releases.length===1&&!x.releases[0]));const healthy=await r.real.connect();try{assert.deepEqual((await healthy.query("select current_user,current_setting('role') role,current_setting('transaction_isolation') isolation")).rows[0],{current_user:'postgres',role:'none',isolation:'read committed'});}finally{healthy.release();}
 const v2=await seed(c,true);assert.equal(receipt(await r.repository.publish(actor(v2),publish(v2))).renderSchemaVersion,2);
 const current=await state(c,f);for(const key of ['legacyInstall','sessions','requests','bookings','payments','holds','outbox'])assert.equal(current[key],0,key);
 console.log('PASS all eight methods, V1/V2 publication, current/history schemas, clean reuse and no booking/payment/session side effects');
 // Registry mismatches are real SQL output, not fabricated return DTOs.
 const badR={...profile,rendererOrigin:'https://wrong-renderer.test',loaderUrl:'https://wrong-renderer.test/assets/booking-lumin-loader.'+'a'.repeat(64)+'.js'};const mismatch=make(undefined,pool(),undefined,[badR]);failed(await mismatch.repository.publicPolicy({installationId:id}),'INTERNAL_ERROR');assert.deepEqual(await state(c,f),current);
 const differentP={...profile,portalOrigin:'https://unreturned-portal.test'};const unseen=make(undefined,pool(),undefined,[differentP]);assert.equal(data(await unseen.repository.publicPolicy({installationId:id})).rendererOrigin,profile.rendererOrigin);
 console.log('PASS actual public-policy registry mismatch rejected; unreturned P mismatch remains explicitly unobservable');
 // Current authority, including recovery, is checked by the real database.
 const foreign=await seed(c);failed(await r.repository.ownerOperation(actor(foreign),recovery(f,'publish')),'FORBIDDEN');failed(await r.repository.ownerOperation({mode:'local_synthetic',userId:f.other},recovery(f,'publish')),'UNAVAILABLE');
 await c.query("update public.tenant_members set role='BUSINESS_STAFF' where tenant_id=$1 and user_id=$2",[f.tenant,f.actor]);failed(await r.repository.ownerOperation(actor(f),recovery(f,'publish')),'FORBIDDEN');await c.query("update public.tenant_members set role='BUSINESS_OWNER' where tenant_id=$1 and user_id=$2",[f.tenant,f.actor]);
 console.log('PASS actual current membership and actor-scoped historical recovery');
 // Real server lock timeout poisons the checked-out client; subsequent operation uses a new backend.
 {const x=await seed(c),before=await state(c,x),hold=await blocker();try{await hold.query('select id from public.flows where id=$1 for update',[x.flow]);const locked=make(),pending=locked.repository.publish(actor(x),publish(x));const target=await acquired(locked);await blocked(c,target,pid(hold));const out=await pending;failed(out);assert.ok(['SERVER_TIMEOUT','LOCK_TIMEOUT'].includes((out as any).code));assert.deepEqual(locked.records[0]!.releases,[true]);await hold.query('rollback');await gone(c,target);assert.deepEqual(await state(c,x),before);receipt(await locked.repository.publish(actor(x),publish(x)));assert.notEqual(locked.records.at(-1)!.pid,target);}finally{await hold.end();}}
 console.log('PASS actual blocked query timeout, full rollback and backend nonreuse');
 // Actual queued driver timeout and deterministic late acquisition disposal are distinct outcomes.
 {const real=new Pool({...config(),connectionTimeoutMillis:1000}),a=await real.connect(),b=await real.connect(),queued=make(undefined,real);try{const out=await queued.repository.publish(actor(f),publish(f));failed(out,'CONNECTION_FAILED');assert.equal((out as any).transaction,'not_started');await drain(queued);}finally{a.release();b.release();}}
 {const real=pool(),a=await real.connect(),b=await real.connect(),gate=deferred(),ready=deferred(),queued=make(undefined,real,async()=>{ready.resolve();await gate.promise;}),abort=new AbortController();let releasedA=false;try{const pending=queued.repository.publish(actor(f),publish(f),{signal:abort.signal});await observe(async()=>real.waitingCount===1,'queued acquisition');abort.abort();failed(await pending,'ABORTED');a.release();releasedA=true;await phase(ready.promise,new Promise(()=>{}),'late dequeue');assert.equal(real.waitingCount,0);assert.deepEqual([...queued.records[0]!.releases],[]);assert.throws(()=>assert.deepEqual([...queued.records[0]!.releases],[true]));let finished=false;const waiting=drain(queued).then(()=>{finished=true;});await new Promise<void>(resolve=>setImmediate(resolve));assert.equal(finished,false);gate.resolve();await waiting;await gone(c,queued.records[0]!.pid);}finally{gate.resolve();if(!releasedA)a.release();b.release();}}
 console.log('PASS real rejected checkout and gated late-disposal observer; queue removal cannot falsely pass');
 // The trigger failure occurs after real SQL mutation work and must roll the entire transaction back.
 {const x=await seed(c),key='transport_late_fault_01',before=await state(c,x),cleanup=await lateFault(c,key);let observed=false;const faulty=make(async(_client,text,_values,run)=>{try{return await run();}catch(error){if(text.startsWith('SELECT')&&(error as any).code==='22023'&&(error as Error).message==='ACTUAL_TRANSPORT_LATE_FAULT')observed=true;throw error;}});try{failed(await faulty.repository.publish(actor(x),publish(x,key)),'INTERNAL_ERROR');assert.equal(observed,true);await gone(c,faulty.records[0]!.pid);assert.deepEqual(await state(c,x),before);}finally{await cleanup();}}
 console.log('PASS actual late SQL fault and full state rollback');
 // Real aborted transaction produces PostgreSQL ROLLBACK, not uncertain commit.
 {const x=await seed(c),before=await state(c,x);let tag='';const aborted=make(async(client,text,_values,run)=>{if(isCommit(text)){await client.query('select 1/0').catch(()=>{});const result=await run();tag=result.command;return result;}return run();});const out=await aborted.repository.publish(actor(x),publish(x));failed(out);assert.equal(tag,'ROLLBACK');assert.equal((out as any).transaction,'rolled_back');assert.equal((out as any).backendMayStillRun,false);await gone(c,aborted.records[0]!.pid);assert.deepEqual(await state(c,x),before);}
 // Dedicated permanent fixture avoids the invalid temporary/permanent FK setup trap.
 {const x=await seed(c),before=await state(c,x),fixture=await commitFixture(c);let submitted=false,sqlstate='';const rejected=make(async(client,text,_values,run)=>{if(isCommit(text)){await client.query('set local role none');await client.query(fixture.defer);await client.query(fixture.insert,[randomUUID()]);submitted=true;try{return await run();}catch(error){sqlstate=(error as any).code;throw error;}}return run();});try{const out=await rejected.repository.publish(actor(x),publish(x));assert.equal(out.kind,'unknown_commit');assert.equal(submitted,true);assert.equal(sqlstate,'23503');await gone(c,rejected.records[0]!.pid);assert.deepEqual(await state(c,x),before);}finally{await fixture.cleanup();}}
 console.log('PASS actual COMMIT ROLLBACK tag and wire-submitted deferred COMMIT rejection remain distinct');
 for(const reading of [false,true]){const x=await seed(c);if(reading)await prepared(x);const before=await state(c,x),proxy=await lossProxy(),lost=make(undefined,new Pool({...config(),port:proxy.port}));try{const out=reading?await lost.repository.ownerOperation(actor(x),recovery(x,'publish')):await lost.repository.publish(actor(x),publish(x));assert.equal(out.kind,reading?'completion_uncertain':'unknown_commit');assert.equal(proxy.sawCommit,true);assert.equal(proxy.sawReady,true);await gone(c,lost.records[0]!.pid);const after=await state(c,x);if(reading)assert.deepEqual(after,before);else{assert.notDeepEqual(after,before);const recovered=data(await r.repository.ownerOperation(actor(x),recovery(x,'publish')));assert.equal(recovered.operation,'publish');assert.deepEqual(await state(c,x),after);failed(await r.repository.ownerOperation({mode:'local_synthetic',userId:x.other},recovery(x,'publish')),'UNAVAILABLE');}}finally{await lost.repository.close();await proxy.close();}}
 console.log('PASS actual protocol COMMIT acknowledgement loss separates read uncertainty from mutation reconciliation');
 for(const reading of [false,true]){const x=await seed(c);if(reading)await prepared(x);let offset=0,tag='';const clock:Clock={monotonic:()=>performance.now()+offset,setTimer:(fn,ms)=>setTimeout(fn,ms),clearTimer:handle=>clearTimeout(handle as ReturnType<typeof setTimeout>)};const withheld=make(async(_client,text,_values,run)=>{const result=await run();if(isCommit(text)){tag=result.command;offset+=10001;}return result;},pool(),undefined,[profile],clock);const out=reading?await withheld.repository.ownerOperation(actor(x),recovery(x,'publish')):await withheld.repository.publish(actor(x),publish(x));assert.equal(tag,'COMMIT');assert.equal(out.kind,reading?'completed':'committed');assert.equal((out as any).delivery,'withheld');assert.equal((out as any).reason,'DEADLINE');assert.equal((out as any)[reading?'data':'receipt'],null);assert.equal(data(await r.repository.ownerOperation(actor(x),recovery(x,'publish'))).operation,'publish');}
 console.log('PASS actual acknowledged COMMIT with explicitly synthetic post-ack clock expiry withholds delivery without inventing uncertainty');
 // Deferred FK causes an observed COMMIT lock wait; abort has no immediate backend-stop guarantee.
 {const x=await seed(c),fixture=await commitFixture(c),ready=deferred(),resume=deferred(),abort=new AbortController();let submitted=false;const waiting=make(async(client,text,_values,run)=>{if(isCommit(text)){await client.query('set local role none');await client.query(fixture.defer);await client.query(fixture.insert,[fixture.parent]);ready.resolve();await resume.promise;submitted=true;}return run();});const hold=await blocker();try{const pending=waiting.repository.publish(actor(x),publish(x),{signal:abort.signal});await phase(ready.promise,pending,'deferred COMMIT prepared');await hold.query(fixture.lock,[fixture.parent]);resume.resolve();const target=await acquired(waiting);await blocked(c,target,pid(hold));assert.equal(submitted,true);assert.equal((await c.query('select query from pg_stat_activity where pid=$1',[target])).rows[0].query,'COMMIT');abort.abort();assert.equal((await pending).kind,'unknown_commit');await hold.query('rollback');await gone(c,target);const beforeRecovery=await state(c,x);const recovered=await r.repository.ownerOperation(actor(x),recovery(x,'publish'));assert.ok(recovered.kind==='completed'||(recovered.kind==='failed'&&recovered.code==='UNAVAILABLE'));assert.deepEqual(await state(c,x),beforeRecovery);}finally{resume.resolve();await hold.end();await fixture.cleanup();}}
 console.log('PASS actual blocked COMMIT abort and explicit read-only reconciliation');
 {const x=await seed(c),before=await state(c,x);let stages=0,commit=false;const slow=make(async(client,text,_values,run)=>{if(text==='SET LOCAL ROLE service_role'||text.startsWith('SELECT')||text==='SET CONSTRAINTS ALL IMMEDIATE'){stages++;await client.query('select pg_sleep(3.6)');}if(isCommit(text))commit=true;return run();});const out=await slow.repository.publish(actor(x),publish(x));failed(out,'DEADLINE');assert.equal(stages,3);assert.equal(commit,false);await gone(c,slow.records[0]!.pid);assert.deepEqual(await state(c,x),before);}
 console.log('PASS three synthetic sub-5s database delays share original 10s deadline, with no COMMIT after abandonment');
 // Historical recovery is denied after archive, even for the original owner/key.
 {const x=await seed(c);await prepared(x);await c.query("update public.flows set status='archived' where id=$1",[x.flow]);const before=await state(c,x);failed(await r.repository.ownerOperation(actor(x),recovery(x,'publish')),'UNAVAILABLE');assert.deepEqual(await state(c,x),before);}
 // A real history trigger failure must roll back installation + history + owner receipt together.
 {const x=await seed(c),published=await prepared(x),before=await state(c,x),cleanup=await lateHistoryFault(c,x.flow);let actual=false;const faulty=make(async(_client,text,_values,run)=>{try{return await run();}catch(error){if(text.startsWith('SELECT')&&(error as any).code==='22023'&&(error as Error).message==='ACTUAL_TRANSPORT_HISTORY_FAULT')actual=true;throw error;}});try{failed(await faulty.repository.install(actor(x),install(x,published.versionId)),'INTERNAL_ERROR');assert.equal(actual,true);await gone(c,faulty.records[0]!.pid);assert.deepEqual(await state(c,x),before);}finally{await cleanup();}receipt(await r.repository.install(actor(x),install(x,published.versionId)));}
 console.log('PASS actual archived recovery denial and late history failure full rollback with successful clean control');
 // Exercise the positive version transition through the adapter, with real publication and history.
 {const x=await seed(c),first=await prepared(x),installed=receipt(await r.repository.install(actor(x),install(x,first.versionId)));await c.query('select public.save_bound_flow_draft($1,$2,$3,$4,1,$5,$6)',[x.actor,x.tenant,x.flow,x.service,'Revised',JSON.stringify({key:'revised',steps:[{key:'count',questionKey:'count',kind:'question',required:true}]})]);const next=receipt(await r.repository.publish(actor(x),{...publish(x,'transport_publish_02'),expectedDraftRevision:2}));const applied=receipt(await r.repository.applyVersion(actor(x),{...scope(x),installationId:installed.installationId,expectedTargetRevision:1,expectedCurrentVersionId:first.versionId,newVersionId:next.versionId,idempotencyKey:'transport_apply_changed'}));assert.equal(applied.changed,true);assert.equal(applied.targetRevision,2);assert.equal(applied.currentVersionId,next.versionId);const h=data(await r.repository.ownerHistory(actor(x),{...scope(x),installationId:installed.installationId,beforeSequence:null,limit:100}));assert.equal(h.history[0].operation,'apply');assert.equal(h.history[0].currentVersionId,next.versionId);}
 console.log('PASS actual changed version application and resulting owner history');
 await pause(30);assert.deepEqual(errors,[]);console.log('PASS MODE INSTALLATION TRANSPORT actual-driver integration');
}finally{for(const close of resources.reverse())await close();await c.end();process.removeListener('unhandledRejection',unhandled);}
