import { describe, it, expect, afterEach } from 'vitest';
import { mkdtemp, writeFile, rm, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { createHash } from 'node:crypto';
import type { IncomingMessage, ServerResponse } from 'node:http';
import { loadModeRuntimeAssets } from './mode-runtime-assets';
const dirs: string[] = [];
afterEach(async()=>{for(const dir of dirs.splice(0)){if(!resolve(dir).startsWith(resolve(tmpdir())+requireSep()))throw Error();await rm(dir,{recursive:true,force:true});}});
function requireSep(){return process.platform==='win32'?'\\':'/';}
async function fixture(){
 const directory=await mkdtemp(join(tmpdir(),'lumin-runtime-test-'));dirs.push(directory);
 const asset=async(name:string)=>{const body=Buffer.from(`(()=>{const ${name}=1;})();`);const sha256=createHash('sha256').update(body).digest('hex');const file=`booking-lumin-${name}.${sha256}.js`;await writeFile(join(directory,file),body);return {file,sha256,bytes:body.length};};
 const loader=await asset('loader'),controller=await asset('controller');
 const profile={profileVersion:'runtime-test-v1',rendererOrigin:'https://renderer.test:4443',apiOrigin:'https://api.test:4444',portalOrigin:'https://portal.test:4445',loaderUrl:'https://renderer.test:4443/assets/'+loader.file};
 const manifest={schemaVersion:1,profile,loader,controller};await writeFile(join(directory,'manifest.json'),JSON.stringify(manifest));return {directory,manifest};
}
function request(handler:Awaited<ReturnType<typeof loadModeRuntimeAssets>>,url:string,method='GET',rawHeaders=['Host','renderer.test:4443'],servername='renderer.test',encrypted=true){
 const headers:Record<string,unknown>={};let body:Buffer|undefined;const res={destroyed:false,writableEnded:false,statusCode:0,setHeader:(k:string,v:unknown)=>{headers[k.toLowerCase()]=v;},end:(v?:Buffer)=>{body=v;}};
 handler.handle({url,method,rawHeaders,socket:{encrypted,servername}} as unknown as IncomingMessage,res as unknown as ServerResponse);return {status:res.statusCode,headers,body};
}
describe('runtime registered immutable assets',()=>{
 it('serves exact bytes and HEAD metadata without exposing registrations',async()=>{const f=await fixture();const h=await loadModeRuntimeAssets(f.directory);const p='/assets/'+f.manifest.loader.file;const get=request(h,p);expect(get.status).toBe(200);expect(get.body).toEqual(await readFile(join(f.directory,f.manifest.loader.file)));expect(get.headers).toEqual({'content-type':'application/javascript;charset=utf-8','content-length':f.manifest.loader.bytes,'cache-control':'public,max-age=31536000,immutable','cdn-cache-control':'public,max-age=31536000,immutable','netlify-cdn-cache-control':'public,max-age=31536000,immutable','x-content-type-options':'nosniff','referrer-policy':'no-referrer','access-control-allow-origin':'*'});const head=request(h,p,'HEAD');expect(head.headers).toEqual(get.headers);expect(head.body).toBeUndefined();expect(Object.isFrozen(h)).toBe(true);});
 it.each(['?x=1','#x','%2e','/../x','\\x'])('rejects malformed raw targets %s',async(suffix)=>{const f=await fixture();const h=await loadModeRuntimeAssets(f.directory);expect(request(h,'/assets/'+f.manifest.loader.file+suffix).status).toBe(400);});
 it.each([['Authorization','x'],['Cookie',''],['Range','bytes=0-1'],['If-Range','x'],['Transfer-Encoding','chunked'],['Content-Length','1'],['Host','renderer.test:4443']])('rejects forbidden or duplicate header %s',async(key,value)=>{const f=await fixture();const h=await loadModeRuntimeAssets(f.directory);const r=request(h,'/assets/'+f.manifest.loader.file,'GET',['Host','renderer.test:4443',key,value]);expect(r.status).toBe(400);expect(r.body?.toString()).toBe('{"error":"ASSET_UNAVAILABLE"}');expect(r.headers['access-control-allow-origin']).toBeUndefined();});
 it('rejects TLS and authority aliases and oversized headers',async()=>{const f=await fixture();const h=await loadModeRuntimeAssets(f.directory);const p='/assets/'+f.manifest.loader.file;expect(request(h,p,'GET',['Host','renderer.test:4443'],'other.test').status).toBe(400);expect(request(h,p,'GET',['Host','renderer.test:4443'],'renderer.test',false).status).toBe(400);expect(request(h,p,'GET',['Host','RENDERER.test:4443']).status).toBe(400);expect(request(h,p,'GET',['Host','renderer.test:4443','X-Padding','x'.repeat(8192)]).status).toBe(400);});
 it('ignores conditional validators, denies unknown assets and methods, preserves HEAD error length',async()=>{const f=await fixture();const h=await loadModeRuntimeAssets(f.directory);const p='/assets/'+f.manifest.loader.file;expect(request(h,p,'GET',['Host','renderer.test:4443','If-None-Match','*']).status).toBe(200);expect(request(h,'/assets/unknown.js').status).toBe(404);const r=request(h,p,'OPTIONS');expect(r.status).toBe(405);expect(r.headers.allow).toBe('GET, HEAD');const head=request(h,'/unknown','HEAD');expect(head.status).toBe(404);expect(head.body).toBeUndefined();expect(head.headers['content-length']).toBe(Buffer.byteLength('{"error":"ASSET_UNAVAILABLE"}'));});
 it.each(['extra','corrupt','length','profile','field'])('rejects invalid registration %s',async(kind)=>{const f=await fixture();if(kind==='extra')await writeFile(join(f.directory,'extra.map'),'x');if(kind==='corrupt')await writeFile(join(f.directory,f.manifest.loader.file),'corrupt');if(kind==='length')f.manifest.controller.bytes++;if(kind==='profile')f.manifest.profile.apiOrigin=f.manifest.profile.rendererOrigin;if(kind==='field')Object.assign(f.manifest,{extra:true});if(['length','profile','field'].includes(kind))await writeFile(join(f.directory,'manifest.json'),JSON.stringify(f.manifest));await expect(loadModeRuntimeAssets(f.directory)).rejects.toThrow();});
 it('closed registration is unavailable and cannot serve retained bytes',async()=>{const f=await fixture();const h=await loadModeRuntimeAssets(f.directory);h.close();h.close();const r=request(h,'/assets/'+f.manifest.loader.file);expect(r.status).toBe(503);expect(r.headers['cache-control']).toBe('no-store,max-age=0');expect(r.headers['access-control-allow-origin']).toBeUndefined();expect(request(h,'/assets/'+f.manifest.loader.file,'HEAD').body).toBeUndefined();});
 it('keeps validated startup bytes stable after a disk change',async()=>{const f=await fixture();const h=await loadModeRuntimeAssets(f.directory);await writeFile(join(f.directory,f.manifest.loader.file),'replaced');const r=request(h,'/assets/'+f.manifest.loader.file);expect(r.status).toBe(200);expect(createHash('sha256').update(r.body!).digest('hex')).toBe(f.manifest.loader.sha256);});
});
