import {act,cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {afterEach,expect,it,vi} from 'vitest';
import type {PublicRuntimeConfig} from '@lumin/runtime-client';
import {HostedJourneyCustomerFieldFlow} from './HostedJourneyCustomerFieldFlow';
const id='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222';
const config:PublicRuntimeConfig={mode:'supabase',environment:'staging',apiOrigin:'https://api.example',flowApiOrigin:'https://api.example',supabaseUrl:'https://child.supabase.co',supabasePublishableKey:'sb_publishable_stagingpublic',tenantId:id};
function snapshot(name='Published cleaning') {return {versionId:id,renderSchemaVersion:9,submissionMode:'paid_journey_customer_field_request',paymentMode:'staging_mock',simulated:true,service:{id,name:'Home cleaning',durationMinutes:60,price:{amount:12500,currency:'USD'}},form:{name,presentation:{accentColor:'#0f766e',layout:'compact'},journey:{schemaVersion:1,stages:[{id:'service',kind:'service',label:'Service',enabled:true},{id:'options',kind:'options',label:'Disabled options',enabled:false},{id:'information',kind:'information',label:'Information',enabled:true},{id:'informational_access',kind:'informational',label:'Access details',enabled:true},{id:'schedule',kind:'schedule',label:'Schedule',enabled:true},{id:'review_payment',kind:'review_payment',label:'Payment',enabled:true},{id:'confirmation',kind:'confirmation',label:'Confirmation',enabled:true}]},customerFields:[{id:'custom_access',kind:'text',label:'Needs access?',required:true,maxLength:20},{id:'custom_note',kind:'text',label:'Access note',required:true,maxLength:40,when:{fieldId:'custom_access',equals:'yes'}}],fieldBindings:[{fieldId:'custom_access',stageId:'information'},{fieldId:'custom_note',stageId:'informational_access'}]}};}
const response=(data:unknown)=>new Response(JSON.stringify({ok:true,data}),{status:200});
function start(fetcher=vi.fn<typeof fetch>(async()=>response(snapshot()))){vi.stubGlobal('location',{protocol:'https:',origin:'https://checkout.example'});vi.stubGlobal('fetch',fetcher);return {view:render(<HostedJourneyCustomerFieldFlow installationId={id} config={config}/>),fetcher};}
async function ready(){await screen.findByRole('heading',{name:'Published cleaning'});}
const next=()=>fireEvent.click(screen.getByRole('button',{name:'Next preview step'}));
afterEach(()=>{cleanup();vi.unstubAllGlobals();vi.useRealTimers();vi.restoreAllMocks();});
it('loads only the exact public V9 origin endpoint, displays pinned price and never writes or stores answers',async()=>{const storage=vi.spyOn(Storage.prototype,'setItem'),{fetcher}=start();await ready();expect(fetcher).toHaveBeenCalledTimes(1);expect(fetcher.mock.calls[0]![0]).toBe('https://api.example/api/public/paid-journey-customer-field-installations/'+id+'/render');expect(fetcher.mock.calls[0]![1]?.headers).toEqual({Origin:'https://checkout.example'});expect(screen.getByText('$125.00')).toBeVisible();expect(screen.getByText(/60 minutes/)).toBeVisible();expect(screen.queryByText('Disabled options')).toBeNull();expect(screen.getByRole('button',{name:'Booking submission not connected yet'})).toBeDisabled();next();fireEvent.change(screen.getByLabelText(/Needs access/),{target:{value:'yes'}});expect(storage).not.toHaveBeenCalled();expect(fetcher).toHaveBeenCalledTimes(1);});
it('honors stage bindings, conditional visibility and forgets hidden answers across navigation',async()=>{start();await ready();next();fireEvent.change(screen.getByLabelText(/Needs access/),{target:{value:'yes'}});expect(screen.queryByLabelText(/Access note/)).toBeNull();next();fireEvent.change(screen.getByLabelText(/Access note/),{target:{value:'Private gate note'}});fireEvent.click(screen.getByRole('button',{name:'Previous preview step'}));fireEvent.change(screen.getByLabelText(/Needs access/),{target:{value:'no'}});next();expect(screen.queryByLabelText(/Access note/)).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Previous preview step'}));fireEvent.change(screen.getByLabelText(/Needs access/),{target:{value:'yes'}});next();expect(screen.getByLabelText(/Access note/)).toHaveValue('');});
it('has associated labels, local-only help, ordered navigation and truthful unavailable stages',async()=>{start();await ready();expect(screen.getByRole('button',{name:'Previous preview step'})).toBeDisabled();next();expect(screen.getByLabelText(/Needs access/)).toHaveAccessibleDescription('Local preview answer only');next();next();expect(screen.getByText(/No availability or reservation is claimed/)).toBeVisible();next();expect(screen.getByText(/No payment has been requested or received/)).toBeVisible();next();expect(screen.getByText(/No booking has been created or confirmed/)).toBeVisible();expect(screen.getByRole('button',{name:'Next preview step'})).toBeDisabled();});
it('moves keyboard focus to each stage heading',async()=>{start();await ready();next();await waitFor(()=>expect(screen.getByRole('heading',{name:'Information'})).toHaveFocus());});
it.each(['v8','money','binding','control'])('rejects malformed %s publication without trusted display or fallback',async kind=>{const value:any=snapshot();if(kind==='v8')value.renderSchemaVersion=8;if(kind==='money')value.service.price.amount=-1;if(kind==='binding')value.form.fieldBindings[0].stageId='schedule';if(kind==='control')value.form.name='Bad\u0000name';const {fetcher}=start(vi.fn(async()=>response(value)));await screen.findByRole('alert');expect(screen.queryByText('Home cleaning')).toBeNull();expect(fetcher).toHaveBeenCalledTimes(1);});
it('aborts unmount and ignores its late read',async()=>{let finish!:(r:Response)=>void;const {view,fetcher}=start(vi.fn(()=>new Promise(resolve=>finish=resolve)));view.unmount();expect(fetcher.mock.calls[0]![1]?.signal?.aborted).toBe(true);await act(async()=>finish(response(snapshot('Late private form'))));expect(screen.queryByText('Late private form')).toBeNull();});
it('suppresses A-B-A stale reads and clears local answers on context replacement',async()=>{const pending:Array<(r:Response)=>void>=[];const {view,fetcher}=start(vi.fn(()=>new Promise(resolve=>pending.push(resolve))));view.rerender(<HostedJourneyCustomerFieldFlow installationId={other} config={config}/>);view.rerender(<HostedJourneyCustomerFieldFlow installationId={id} config={config}/>);await act(async()=>{pending[0]!(response(snapshot('Old A')));pending[1]!(response(snapshot('Old B')));pending[2]!(response(snapshot()));});await ready();expect(screen.queryByText('Old A')).toBeNull();expect(screen.queryByText('Old B')).toBeNull();expect(fetcher.mock.calls[0]![1]?.signal?.aborted).toBe(true);next();fireEvent.change(screen.getByLabelText(/Needs access/),{target:{value:'private'}});view.rerender(<HostedJourneyCustomerFieldFlow installationId={other} config={config}/>);expect(screen.queryByDisplayValue('private')).toBeNull();});
it('bounds stalled reads, reports failure safely and does not auto retry',async()=>{vi.useFakeTimers();const {fetcher}=start(vi.fn(()=>new Promise(()=>{})));await act(async()=>vi.advanceTimersByTimeAsync(30000));expect(screen.getByRole('alert')).toHaveTextContent('No booking or payment was made');expect(fetcher.mock.calls[0]![1]?.signal?.aborted).toBe(true);await act(async()=>vi.advanceTimersByTimeAsync(60000));expect(fetcher).toHaveBeenCalledTimes(1);});
it.each([320,375,390,430,768,1280])('uses wrapping bounded controls at %ipx without fixed viewport dimensions',async width=>{vi.stubGlobal('innerWidth',width);start();await ready();next();const input=screen.getByLabelText(/Needs access/);expect(input).toHaveStyle({width:'100%',minWidth:'0',maxWidth:'100%',boxSizing:'border-box'});expect(screen.getByRole('navigation',{name:'Preview steps'})).toHaveStyle({flexWrap:'wrap'});expect(screen.getByRole('region',{name:'Published booking form preview'})).toHaveStyle({overflowWrap:'anywhere'});});
it('does not fetch outside connected HTTPS staging or for noncanonical installations',async()=>{vi.stubGlobal('location',{protocol:'https:',origin:'https://checkout.example'});const fetcher=vi.fn();vi.stubGlobal('fetch',fetcher);const view=render(<HostedJourneyCustomerFieldFlow installationId={id} config={{...config,environment:'production'}}/>);await screen.findByRole('alert');expect(fetcher).not.toHaveBeenCalled();view.rerender(<HostedJourneyCustomerFieldFlow installationId="not-a-uuid" config={config}/>);await screen.findByRole('alert');expect(fetcher).not.toHaveBeenCalled();});
it('delayed response-body A-B-A cannot revive old form metadata',async()=>{let finish!:(body:unknown)=>void;let count=0;const fetcher=vi.fn<typeof fetch>(async()=>++count===1?{status:200,redirected:false,json:()=>new Promise(resolve=>finish=resolve)} as Response:response(snapshot()));const {view}=start(fetcher);await waitFor(()=>expect(finish).toBeTypeOf('function'));view.rerender(<HostedJourneyCustomerFieldFlow installationId={other} config={config}/>);view.rerender(<HostedJourneyCustomerFieldFlow installationId={id} config={config}/>);await ready();await act(async()=>finish({ok:true,data:snapshot('Stale body A')}));expect(screen.queryByText('Stale body A')).toBeNull();});
it('rejects local control text and preserves Unicode text without transmitting it',async()=>{const {fetcher}=start();await ready();next();const input=screen.getByLabelText(/Needs access/);fireEvent.change(input,{target:{value:'Cafe 🙂'}});expect(input).toHaveValue('Cafe 🙂');fireEvent.change(input,{target:{value:'Bad\u0001'}});expect(input).toHaveValue('Cafe 🙂');expect(fetcher).toHaveBeenCalledTimes(1);});
it('uses currency minor-unit contract for zero-decimal server prices',async()=>{const value=snapshot();value.service.price.currency='JPY';value.service.price.amount=12500;start(vi.fn(async()=>response(value)));await ready();expect(screen.getByText('¥12,500')).toBeVisible();});
it('isolates accessible question identifiers across simultaneous previews',async()=>{start();await ready();render(<HostedJourneyCustomerFieldFlow installationId={id} config={config}/>);await waitFor(()=>expect(screen.getAllByRole('heading',{name:'Published cleaning'})).toHaveLength(2));for(const button of screen.getAllByRole('button',{name:'Next preview step'}))fireEvent.click(button);const inputs=screen.getAllByLabelText(/Needs access/);expect(inputs[0]!.id).not.toBe(inputs[1]!.id);});

const sessionReceipt=(expiresAt=new Date(Date.now()+900000).toISOString())=>({schemaVersion:2,installationId:id,sessionToken:'A'.repeat(43),expiresAt,render:snapshot()});
function schedulingTransport(options:{lostIssue?:boolean;lostRead?:boolean;empty?:boolean;malformed?:boolean;expiresAt?:string}={}){
 let issueCount=0,readCount=0;
 return vi.fn<typeof fetch>(async(url,init)=>{
  if(init?.method==='POST'){issueCount++;if(options.lostIssue)throw Error('private provider');return response(sessionReceipt(options.expiresAt));}
  const target=new URL(String(url));if(target.pathname.endsWith('/availability')){readCount++;if(options.lostRead&&readCount===1)throw Error('private provider');const from=Date.parse(target.searchParams.get('from')!),start=new Date(from+9*3600000).toISOString(),end=new Date(from+10*3600000).toISOString();return response({schemaVersion:2,installationId:id,versionId:options.malformed?other:id,serviceId:id,durationMinutes:60,slots:options.empty?[]:[{start,end,remainingCapacity:1}]});}
  return response(snapshot());
 });
}
async function schedule(){await ready();next();next();next();expect(screen.getByRole('heading',{name:'Schedule'})).toBeVisible();}
it('explicit check uses one session POST then scoped availability GET and local selection without financial writes',async()=>{const storage=vi.spyOn(Storage.prototype,'setItem'),fetcher=schedulingTransport();start(fetcher);await schedule();expect(fetcher).toHaveBeenCalledTimes(1);fireEvent.click(screen.getByRole('button',{name:'Check available times'}));const radio=await screen.findByRole('radio');expect(fetcher).toHaveBeenCalledTimes(3);const issue=fetcher.mock.calls[1]!,read=fetcher.mock.calls[2]!;expect(issue[1]?.method).toBe('POST');expect(issue[1]?.body).toBe('{}');expect(issue[1]?.headers).toEqual({Origin:'https://checkout.example','Content-Type':'application/json'});expect(String(read[0])).toContain('/api/public/paid-journey-customer-field-flow-sessions/availability?from=');expect(read[1]?.headers).toEqual({Origin:'https://checkout.example',Authorization:'Bearer '+'A'.repeat(43)});fireEvent.click(radio);expect(screen.getByText(/Selected locally/)).toBeVisible();expect(fetcher).toHaveBeenCalledTimes(3);expect(storage).not.toHaveBeenCalled();expect(document.body.textContent).not.toContain('A'.repeat(43));expect(screen.getByRole('button',{name:'Booking submission not connected yet'})).toBeDisabled();await waitFor(()=>expect(screen.getByLabelText('Scheduling results')).toHaveFocus());});
it('explicit recheck and date change reuse only GET, clear old selection and preserve local answers',async()=>{const fetcher=schedulingTransport();start(fetcher);await ready();next();fireEvent.change(screen.getByLabelText(/Needs access/),{target:{value:'yes'}});next();fireEvent.change(screen.getByLabelText(/Access note/),{target:{value:'Private local note'}});next();fireEvent.click(screen.getByRole('button',{name:'Check available times'}));fireEvent.click(await screen.findByRole('radio'));const day=new Date(Date.now()+2*86400000).toISOString().slice(0,10);fireEvent.change(screen.getByLabelText('Date to check (UTC)'),{target:{value:day}});expect(screen.queryByRole('radio')).toBeNull();expect(screen.queryByText(/Selected locally/)).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Check available times again'}));await screen.findByRole('radio');expect(fetcher.mock.calls.filter(([,init])=>init?.method==='POST')).toHaveLength(1);fireEvent.click(screen.getByRole('button',{name:'Previous preview step'}));expect(screen.getByLabelText(/Access note/)).toHaveValue('Private local note');});
it('lost issuance is fenced through preview reload and never auto-retried or replaced',async()=>{const fetcher=schedulingTransport({lostIssue:true});start(fetcher);await schedule();fireEvent.click(screen.getByRole('button',{name:'Check available times'}));await screen.findByText(/Session creation could not be verified/);expect(screen.getByRole('button',{name:'Check available times'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'Reload published preview'}));await schedule();expect(screen.getByRole('button',{name:'Check available times'})).toBeDisabled();expect(fetcher.mock.calls.filter(([,init])=>init?.method==='POST')).toHaveLength(1);expect(fetcher).toHaveBeenCalledTimes(3);});
it('availability failure permits only explicit GET retry on the same session',async()=>{const fetcher=schedulingTransport({lostRead:true});start(fetcher);await schedule();fireEvent.click(screen.getByRole('button',{name:'Check available times'}));await screen.findByText(/Available times could not be verified/);expect(fetcher).toHaveBeenCalledTimes(3);fireEvent.click(screen.getByRole('button',{name:'Check available times again'}));await screen.findByRole('radio');expect(fetcher).toHaveBeenCalledTimes(4);expect(fetcher.mock.calls.filter(([,init])=>init?.method==='POST')).toHaveLength(1);});
it.each(['empty','malformed'])('displays truthful %s availability without invented slots',async mode=>{const fetcher=schedulingTransport({empty:mode==='empty',malformed:mode==='malformed'});start(fetcher);await schedule();fireEvent.click(screen.getByRole('button',{name:'Check available times'}));await screen.findByText(mode==='empty'?/No available times were returned/:/Available times could not be verified/);expect(screen.queryByRole('radio')).toBeNull();expect(screen.getByText('$125.00')).toBeVisible();expect(fetcher.mock.calls.filter(([,init])=>init?.method==='POST')).toHaveLength(1);});
it('double click while session body is pending sends once and late A-B-A response cannot revive capability',async()=>{let finish!:(value:unknown)=>void;const ordinary=schedulingTransport(),fetcher=vi.fn<typeof fetch>(async(url,init)=>init?.method==='POST'?{status:200,redirected:false,json:()=>new Promise(resolve=>finish=resolve)} as Response:ordinary(url,init));const {view}=start(fetcher);await schedule();const button=screen.getByRole('button',{name:'Check available times'});fireEvent.click(button);fireEvent.click(button);await waitFor(()=>expect(finish).toBeTypeOf('function'));expect(fetcher.mock.calls.filter(([,init])=>init?.method==='POST')).toHaveLength(1);view.rerender(<HostedJourneyCustomerFieldFlow installationId={other} config={config}/>);view.rerender(<HostedJourneyCustomerFieldFlow installationId={id} config={config}/>);await schedule();await act(async()=>finish({ok:true,data:sessionReceipt()}));expect(screen.queryByRole('radio')).toBeNull();expect(screen.getByRole('button',{name:'Check available times'})).toBeDisabled();expect(fetcher.mock.calls.some(([url])=>String(url).includes('/availability?'))).toBe(false);});
it('aborts stalled issuance at deadline and never issues again after delayed completion',async()=>{let finish!:(value:unknown)=>void;const fetcher=vi.fn<typeof fetch>(async(_url,init)=>init?.method==='POST'?({status:200,redirected:false,json:()=>new Promise(resolve=>finish=resolve)}) as Response:response(snapshot()));start(fetcher);await schedule();vi.useFakeTimers();fireEvent.click(screen.getByRole('button',{name:'Check available times'}));await act(async()=>{await Promise.resolve();await vi.advanceTimersByTimeAsync(30000);});expect(screen.getByText(/Session creation could not be verified/)).toBeVisible();await act(async()=>finish({ok:true,data:sessionReceipt()}));expect(screen.getByRole('button',{name:'Check available times'})).toBeDisabled();expect(fetcher).toHaveBeenCalledTimes(2);});
it('session expiry clears displayed slots and local schedule without renewal or financial calls',async()=>{const expiry=new Date(Date.now()+60000).toISOString(),fetcher=schedulingTransport({expiresAt:expiry});start(fetcher);await schedule();vi.useFakeTimers();await act(async()=>{fireEvent.click(screen.getByRole('button',{name:'Check available times'}));await vi.advanceTimersByTimeAsync(0);});fireEvent.click(screen.getByRole('radio'));await act(async()=>vi.advanceTimersByTimeAsync(60000));expect(screen.queryByRole('radio')).toBeNull();expect(screen.queryByText(/Selected locally/)).toBeNull();expect(screen.getByText(/This scheduling session expired/)).toBeVisible();expect(screen.getByRole('button',{name:'Check available times'})).toBeDisabled();expect(fetcher).toHaveBeenCalledTimes(3);});

it('issued version or price mismatch never reads availability or retries issuance',async()=>{const ordinary=schedulingTransport(),fetcher=vi.fn<typeof fetch>(async(url,init)=>{if(init?.method==='POST'){const r=sessionReceipt();r.render.service.price.amount=1;return response(r);}return ordinary(url,init);});start(fetcher);await schedule();fireEvent.click(screen.getByRole('button',{name:'Check available times'}));await screen.findByText(/Session creation could not be verified/);expect(screen.queryByRole('radio')).toBeNull();expect(screen.getByText('$125.00')).toBeVisible();expect(fetcher).toHaveBeenCalledTimes(2);expect(fetcher.mock.calls.some(([url])=>String(url).includes('/availability?'))).toBe(false);expect(screen.getByRole('button',{name:'Check available times'})).toBeDisabled();});
it('late availability body cannot revive old selection after context A-B-A',async()=>{let finish!:(value:unknown)=>void;const ordinary=schedulingTransport(),fetcher=vi.fn<typeof fetch>(async(url,init)=>String(url).includes('/availability?')?{status:200,redirected:false,json:()=>new Promise(resolve=>finish=resolve)} as Response:ordinary(url,init));const {view}=start(fetcher);await schedule();fireEvent.click(screen.getByRole('button',{name:'Check available times'}));await waitFor(()=>expect(finish).toBeTypeOf('function'));const request=fetcher.mock.calls.find(([url])=>String(url).includes('/availability?'))!,from=Date.parse(new URL(String(request[0])).searchParams.get('from')!);view.rerender(<HostedJourneyCustomerFieldFlow installationId={other} config={config}/>);view.rerender(<HostedJourneyCustomerFieldFlow installationId={id} config={config}/>);await schedule();await act(async()=>finish({ok:true,data:{schemaVersion:2,installationId:id,versionId:id,serviceId:id,durationMinutes:60,slots:[{start:new Date(from+9*3600000).toISOString(),end:new Date(from+10*3600000).toISOString(),remainingCapacity:1}]}}));expect(request[1]?.signal?.aborted).toBe(true);expect(screen.queryByRole('radio')).toBeNull();expect(screen.getByRole('button',{name:'Check available times'})).toBeDisabled();expect(fetcher.mock.calls.filter(([,init])=>init?.method==='POST')).toHaveLength(1);});
