import {useEffect,useMemo,useRef,useState,type FormEvent} from 'react';
import {createFlowClient,FlowError,QuestionForm,ConfigurableQuestionForm,isConfigurable,canonicalConfigurableAnswers,answersValid,type FlowClient,type Answers} from '@lumin/flow-ui';
type Session=Awaited<ReturnType<FlowClient['session']>>;
type RequestBody=Parameters<FlowClient['submit']>[1];
export function HostedFlow({installationId,apiUrl,localHarness=false}:{installationId:string;apiUrl:string;localHarness?:boolean}){
 const client=useMemo(()=>{try{return createFlowClient(apiUrl,localHarness);}catch{return null;}},[apiUrl,localHarness]);
 const [session,setSession]=useState<Session>(),[answers,setAnswers]=useState<Answers>({}),[name,setName]=useState(''),[email,setEmail]=useState(''),[time,setTime]=useState(''),[pending,setPending]=useState<RequestBody>(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[reference,setReference]=useState('');const generation=useRef(0),pendingRef=useRef<RequestBody>(),inFlight=useRef(false);
 const secure=location.protocol==='https:';
 useEffect(()=>{const at=++generation.current;setSession(undefined);setPending(undefined);pendingRef.current=undefined;inFlight.current=false;setReference('');setAnswers({});setName('');setEmail('');setTime('');setError('');if(!client||!secure)return;if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(installationId)){setError('This request form is unavailable.');return;}setBusy(true);void client.session(installationId).then(s=>{if(at===generation.current){if(Date.parse(s.expiresAt)<=Date.now())throw new FlowError('NOT_AVAILABLE');setSession(s);}}).catch(e=>{if(at===generation.current)setError(e instanceof FlowError?e.message:'Unable to open this request form.');}).finally(()=>{if(at===generation.current)setBusy(false);});return()=>{generation.current++;client?.invalidate();};},[client,installationId,secure]);
 async function submit(e:FormEvent){e.preventDefault();if(!client||!session||busy||inFlight.current||reference)return;const at=generation.current;setError('');let body=pendingRef.current;if(!body){const date=new Date(time);let accepted=answers;let valid=false;try{if(isConfigurable(session.render)){accepted=canonicalConfigurableAnswers(session.render,answers);valid=true;}else valid=answersValid(session.render.service,session.render.config,answers);}catch{}if(!valid||!name.trim()||!email.trim()||!Number.isFinite(date.getTime())||date.getTime()<=Date.now()){setError('Complete the required answers and choose a future requested time.');return;}body={idempotencyKey:crypto.randomUUID(),answers:structuredClone(accepted),customer:{name:name.trim(),email:email.trim()},requestedStart:date.toISOString()};pendingRef.current=body;setPending(body);}inFlight.current=true;setBusy(true);try{const result=await client.submit(session.sessionToken,body);if(at===generation.current){setReference(result.reference);setSession(undefined);setAnswers({});setName('');setEmail('');setTime('');setPending(undefined);pendingRef.current=undefined;}}catch(e){if(at===generation.current)setError(e instanceof FlowError?e.message:'Unable to save the request. Retry the same request.');}finally{if(at===generation.current){inFlight.current=false;setBusy(false);}}}
 return <main className="checkout-card"><p>Request form{localHarness?' · Local harness':''}</p>{!secure?<section><h1>Secure customer page required</h1><p>This request form must open on its published HTTPS site. Local HTTP does not demonstrate a customer session.</p></section>:!client?<p role="alert">The request service is not configured.</p>:reference?<section><h1>Request saved</h1><p>Reference: <strong>{reference}</strong></p><p>Your request is unconfirmed. No payment was taken and availability is not guaranteed.</p></section>:session?<form onSubmit={submit}><h1>{session.render.service.name}</h1><p>Answer the questions and request a time. The business must confirm your request.</p>{isConfigurable(session.render)?<ConfigurableQuestionForm render={session.render} answers={answers} onChange={setAnswers} disabled={busy||!!pending}/>:<QuestionForm service={session.render.service} config={session.render.config} answers={answers} onChange={setAnswers} disabled={busy||!!pending}/>}<fieldset disabled={busy||!!pending}><label>Your name<input required maxLength={200} autoComplete="name" value={name} onChange={e=>setName(e.target.value)}/></label><label>Email<input type="email" required maxLength={254} autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Requested date and time<input type="datetime-local" required value={time} onChange={e=>setTime(e.target.value)}/></label><p>Time zone: {Intl.DateTimeFormat().resolvedOptions().timeZone}. This is a preferred time, not a reservation.</p></fieldset><button disabled={busy}>{busy?'Saving…':pending?'Retry the same request':'Send unconfirmed request'}</button>{pending&&!busy&&<p>Your original answers are kept for a safe retry.</p>}</form>:null}{busy&&!session&&<p role="status">Opening request form…</p>}{error&&<p role="alert">{error}</p>}</main>;
}
