import {useEffect,useMemo,useRef,useState,type CSSProperties} from 'react';
import {formatMoney,DetailingReservationInput,type DetailingQuoteReceipt,type DetailingAvailabilityReceipt,type DetailingQuoteInput} from '@lumin/contracts';
import {createDetailingCustomerClient,DetailingCustomerError,type DetailingCustomerSession,type DetailingCustomerOperation} from '@lumin/runtime-client';
import {DetailingTestPaymentPanel,type DetailingTestPaymentState} from './DetailingTestPaymentPanel';

export function HostedDetailingFlow({installationId,apiUrl,localHarness=false}:{installationId:string;apiUrl:string;localHarness?:boolean}){
 const client=useMemo(()=>{try{return createDetailingCustomerClient(apiUrl,localHarness);}catch{return null;}},[apiUrl,localHarness]);
 const [session,setSession]=useState<DetailingCustomerSession>(),[selection,setSelection]=useState<DetailingQuoteInput>({packageId:'',vehicleId:'',addonIds:[]}),[quote,setQuote]=useState<DetailingQuoteReceipt>(),[availability,setAvailability]=useState<DetailingAvailabilityReceipt>(),[date,setDate]=useState(''),[slot,setSlot]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loadingSlots,setLoadingSlots]=useState(false),[expired,setExpired]=useState(false),[retry,setRetry]=useState(0),[name,setName]=useState(''),[email,setEmail]=useState(''),[review,setReview]=useState(false),[operation,setOperation]=useState<DetailingCustomerOperation>({phase:'ready'}),[holdExpired,setHoldExpired]=useState(false),[paymentHoldVerified,setPaymentHoldVerified]=useState(false);
 const lifecycle=useRef(0),quoteGeneration=useRef(0),slotGeneration=useRef(0),writing=useRef(false),secure=location.protocol==='https:';
 const locked=operation.phase!=='ready',unknown=operation.phase==='request_unknown'||operation.phase==='hold_unknown';
 const financialPending=['readiness_pending','payment_pending','confirmation_pending'].includes(operation.phase),financialAttempt=financialPending||operation.phase==='payment_unknown'||!!operation.payment;
 const confirmed=operation.phase==='confirmed'&&!!operation.payment;
 const message=(e:unknown)=>e instanceof DetailingCustomerError?e.message:'The Detailing service could not be verified. Try again.';
 useEffect(()=>{const at=++lifecycle.current;quoteGeneration.current++;slotGeneration.current++;writing.current=false;setSession(undefined);setQuote(undefined);setAvailability(undefined);setSlot('');setDate('');setSelection({packageId:'',vehicleId:'',addonIds:[]});setName('');setEmail('');setReview(false);setOperation({phase:'ready'});setHoldExpired(false);setPaymentHoldVerified(false);setError('');setExpired(false);setBusy(false);setLoadingSlots(false);
  if(!client||!secure)return;setBusy(true);void client.session(installationId).then(value=>{if(at===lifecycle.current){setSession(value);const previous=client.operation();setOperation(previous);if(previous.body){setSelection(previous.body.selection);setName(previous.body.customer.name);setEmail(previous.body.customer.email);setSlot(previous.body.requestedStart);}}}).catch(e=>{if(at===lifecycle.current)setError(message(e));}).finally(()=>{if(at===lifecycle.current)setBusy(false);});
  return()=>{lifecycle.current++;quoteGeneration.current++;slotGeneration.current++;client?.invalidate();};
 },[client,installationId,secure]);
 // A remount can restore an operation owned by an older client instance. Observe
 // only its in-memory completion; never replay transport or accept its late receipt.
 useEffect(()=>{const pending=['request_pending','hold_pending','readiness_pending','payment_pending','confirmation_pending'];if(!client||!session||expired||!pending.includes(operation.phase))return;const at=lifecycle.current;const timer=setInterval(()=>{if(at!==lifecycle.current){clearInterval(timer);return;}const next=client.operation();if(pending.includes(next.phase))return;clearInterval(timer);setOperation(next);setBusy(false);writing.current=false;},100);return()=>clearInterval(timer);},[client,session,operation.phase,expired]);
 useEffect(()=>{if(!session)return;let timer:ReturnType<typeof setTimeout>;const check=()=>{const remaining=Date.parse(session.expiresAt)-Date.now();if(remaining<=0){quoteGeneration.current++;slotGeneration.current++;setExpired(true);setQuote(undefined);setAvailability(undefined);setSlot('');setReview(false);setBusy(false);setLoadingSlots(false);client?.invalidate();}else timer=setTimeout(check,Math.min(remaining,2147483647));};check();return()=>clearTimeout(timer);},[session,client]);
 useEffect(()=>{if(locked||(!quote&&!availability))return;const deadline=Math.min(quote?Date.parse(quote.expiresAt):Infinity,availability?Date.parse(availability.expiresAt):Infinity);const timer=setTimeout(()=>{if(client?.operation().phase!=='ready')return;quoteGeneration.current++;slotGeneration.current++;client?.clearSelection();setQuote(undefined);setAvailability(undefined);setSlot('');setReview(false);setBusy(false);setLoadingSlots(false);setError('This quote or availability expired. Request a fresh quote and choose a date again.');},Math.max(0,Math.min(deadline-Date.now(),2147483647)));return()=>clearTimeout(timer);},[quote,availability,locked,client]);
 useEffect(()=>{if(!operation.hold)return;const remaining=Date.parse(operation.hold.expiresAt)-Date.now();setHoldExpired(remaining<=0);if(remaining<=0)return;const timer=setTimeout(()=>setHoldExpired(true),Math.min(remaining,2147483647));return()=>clearTimeout(timer);},[operation.hold]);
 function change(next:DetailingQuoteInput){if(locked||writing.current)return;client?.clearSelection();quoteGeneration.current++;slotGeneration.current++;setSelection(next);setQuote(undefined);setAvailability(undefined);setSlot('');setDate('');setReview(false);setError('');setBusy(false);setLoadingSlots(false);}
 async function requestQuote(){if(!client||!session||expired||locked||writing.current)return;const at=++quoteGeneration.current;slotGeneration.current++;setReview(false);setQuote(undefined);setAvailability(undefined);setSlot('');setDate('');setLoadingSlots(false);setBusy(true);setError('');try{const value=await client.quote(selection);if(at===quoteGeneration.current)setQuote(value);}catch(e){if(at===quoteGeneration.current)setError(message(e));}finally{if(at===quoteGeneration.current)setBusy(false);}}
 useEffect(()=>{if(locked)return;const at=++slotGeneration.current;setAvailability(undefined);setSlot('');setLoadingSlots(false);if(!date||!quote||!session||!client||expired)return;setError('');
  // UTC query bounds are explicit. Times are shown in the server's business timezone.
  const from=new Date(date+'T00:00:00.000Z');if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isFinite(from.getTime())||from.toISOString().slice(0,10)!==date){setError('Choose a valid date.');return;}const to=new Date(from.getTime()+86400000);setLoadingSlots(true);
  void client.availability({from:from.toISOString(),to:to.toISOString()}).then(value=>{if(at===slotGeneration.current&&Date.parse(quote.expiresAt)>Date.now())setAvailability(value);}).catch(e=>{if(at===slotGeneration.current)setError(message(e));}).finally(()=>{if(at===slotGeneration.current)setLoadingSlots(false);});return()=>{slotGeneration.current++;};
 },[date,quote,session,client,expired,retry,locked]);
 function readyToReview(){if(!quote||!availability||!slot||loadingSlots||Date.parse(quote.expiresAt)<=Date.now()||Date.parse(availability.expiresAt)<=Date.now()||!availability.slots.some(s=>s.start===slot&&Date.parse(s.start)>Date.now()))return false;return DetailingReservationInput.safeParse({schemaVersion:1,idempotencyKey:'review-validation-0001',selection,customer:{name:name.trim(),email:email.trim()},requestedStart:slot}).success;}
 async function sendRequest(){if(!client||!session||expired||writing.current||busy||operation.request)return;let body=operation.body;
  if(!body){if(!review||!readyToReview()){setError('Check your customer details and choose a current available time.');return;}body={schemaVersion:1,idempotencyKey:crypto.randomUUID(),selection:structuredClone(selection),customer:{name:name.trim(),email:email.trim()},requestedStart:slot};}
  const at=lifecycle.current;writing.current=true;setBusy(true);setError('');const pending=client.request(body);setOperation(client.operation());
  try{await pending;}catch(e){if(at===lifecycle.current)setError(message(e));}finally{if(at===lifecycle.current){setOperation(client.operation());setBusy(false);writing.current=false;}}
 }
 async function reserve(){if(!client||!operation.request||expired||holdExpired||writing.current||busy)return;const at=lifecycle.current;writing.current=true;setBusy(true);setError('');const pending=client.hold();setOperation(client.operation());
  try{await pending;if(at===lifecycle.current)setPaymentHoldVerified(true);}catch(e){if(at===lifecycle.current)setError(message(e));}finally{if(at===lifecycle.current){setOperation(client.operation());setBusy(false);writing.current=false;}}
 }
 async function paymentAction(kind:'read'|'pay'|'confirm'){
  if(!client||!operation.request||expired||writing.current||busy)return;const at=lifecycle.current;writing.current=true;setBusy(true);setError('');
  if(kind!=='read')setPaymentHoldVerified(false);
  const pending=kind==='read'?client.paymentReadiness():kind==='pay'?client.mockPayment():client.confirm();setOperation(client.operation());
  try{await pending;}catch(e){if(at===lifecycle.current)setError(message(e));}finally{if(at===lifecycle.current){setOperation(client.operation());setBusy(false);writing.current=false;}}
 }
 const paymentState:DetailingTestPaymentState=operation.phase==='payment_unknown'?{phase:'unverified',recovery:operation.readiness?.state==='confirmed'?'confirm':operation.readiness?.state==='draft'&&!holdExpired&&paymentHoldVerified?'retry-payment':'check'}:
  operation.phase==='payment_pending'||operation.phase==='confirmation_pending'?{phase:'paying'}:operation.phase==='readiness_pending'?{phase:'checking'}:confirmed?{phase:'confirmed'}:
  operation.phase==='payment_ready'&&!holdExpired&&!expired?{phase:'ready'}:{phase:'unavailable',canCheckAvailability:operation.phase==='held'&&!holdExpired&&!expired};
 const cat=session?.render.catalog,complete=!!selection.packageId&&!!selection.vehicleId&&(!cat?.locations.length||!!selection.locationId);
 return <div className="checkout-root"><main className="checkout-card" style={{minWidth:0,overflowWrap:'anywhere',...(session?{'--accent':session.render.publication.presentation.accentColor}:{})} as CSSProperties}>
 {!secure?<><h1>Secure customer page required</h1><p>Open this Detailing form on its published HTTPS site.</p></>:!client?<p role="alert">The Detailing service is not configured.</p>:<><h1>{session?.render.publication.name??'Detailing quote'}</h1>{error&&<p role="alert">{error}</p>}{expired&&<p role="alert">Your session expired. {locked?'Your attempted request, reservation or test payment must be checked with the business.':'Reload to start again.'}</p>}{cat?<><p>{cat.description}</p><p>A saved request remains unconfirmed until its test confirmation is verified. Choosing a time does not reserve it.</p>
 {operation.request?<section aria-label="Saved request">
  <h2>{confirmed?(expired?'Last verified test confirmation':'Booking confirmed (test)'):financialAttempt?'Booking status being verified':'Request saved, unconfirmed'}</h2>
  <p>Reference: <strong>{operation.request.reference}</strong></p><p>Server total: <strong>{formatMoney(operation.request.pricing.total)}</strong></p><p>Requested time: {new Date(operation.request.slot.start).toLocaleString()}.</p>
  {!financialAttempt&&<><p>No payment has been taken.</p>{operation.phase==='hold_unknown'?<p role="status">Reservation status is unverified. Retry only this same reservation, or contact the business.</p>:operation.hold?(holdExpired?<p role="status">The temporary reservation expired. Your request remains saved and unconfirmed.</p>:expired?<p role="status">Current reservation status is unverified because your session expired.</p>:<p role="status">Time temporarily reserved until {new Date(operation.hold.expiresAt).toLocaleString()}. This is an active hold, not a confirmed booking.</p>):<p>No reservation has been verified.</p>}{!expired&&!holdExpired&&<button type="button" disabled={busy||operation.phase==='hold_pending'} onClick={reserve}>{busy||operation.phase==='hold_pending'?'Checking reservation…':operation.phase==='hold_unknown'?'Retry the same reservation':operation.hold?'Verify the same reservation':'Reserve requested time'}</button>}</>}
  {operation.phase==='payment_unknown'&&operation.readiness?.state==='draft'&&!paymentHoldVerified&&!expired&&!holdExpired&&<button type="button" disabled={busy} onClick={reserve}>Verify the same reservation before retry</button>}
  {operation.hold&&<DetailingTestPaymentPanel state={paymentState} formattedTotal={formatMoney(operation.request.pricing.total)} reference={operation.request.reference} busy={busy||expired} onCheckAvailability={()=>void paymentAction('read')} onCheckStatus={()=>void paymentAction('read')} onCompleteTestPayment={()=>void paymentAction('pay')} onReplayConfirmation={()=>void paymentAction('confirm')}/>}
 </section>:
 <><fieldset disabled={expired||locked} style={{minWidth:0}}><legend>Your Detailing choices</legend><label>Detail package<select value={selection.packageId} onChange={e=>change({...selection,packageId:e.target.value})}><option value="">Choose a package</option>{cat.packages.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select></label><label>Vehicle type<select value={selection.vehicleId} onChange={e=>change({...selection,vehicleId:e.target.value})}><option value="">Choose a vehicle</option>{cat.vehicles.map(v=><option key={v.id} value={v.id}>{v.label}</option>)}</select></label>{cat.addons.map(a=><label key={a.id}><input type="checkbox" checked={selection.addonIds.includes(a.id)} onChange={e=>change({...selection,addonIds:e.target.checked?[...selection.addonIds,a.id]:selection.addonIds.filter(id=>id!==a.id)})}/>{a.name}</label>)}{!!cat.locations.length&&<label>Service location<select value={selection.locationId??''} onChange={e=>change({...selection,locationId:e.target.value})}><option value="">Choose a location</option>{cat.locations.map(l=><option key={l.id} value={l.id}>{l.label}</option>)}</select></label>}<button type="button" disabled={!complete||busy} onClick={requestQuote}>{busy&&!locked?'Requesting quote…':'Get server quote'}</button></fieldset>
 {quote&&<section aria-label="Server quote"><h2>Server quote</h2><ul>{quote.pricing.lines.map((line,i)=><li key={i}>{line.label}: {formatMoney(line.amount)} × {line.quantity}</li>)}</ul><p>Total: <strong>{formatMoney(quote.pricing.total)}</strong></p><p>Quote reported valid until {new Date(quote.expiresAt).toLocaleString()}.</p><fieldset disabled={expired||locked}><label>Availability date (UTC)<input type="date" value={date} onChange={e=>{if(writing.current)return;client.clearAvailability();slotGeneration.current++;setSlot('');setAvailability(undefined);setReview(false);setError('');setDate(e.target.value);}}/></label>{loadingSlots&&<p role="status">Checking availability…</p>}{availability&&<><p>Times shown in {availability.timezone}.</p>{availability.slots.some(s=>Date.parse(s.start)>Date.now())?<label>Available time<select value={slot} onChange={e=>{setReview(false);setSlot(e.target.value);}}><option value="">Choose a time</option>{availability.slots.filter(s=>Date.parse(s.start)>Date.now()).map(s=><option key={s.start} value={s.start}>{new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short',timeZone:availability.timezone}).format(new Date(s.start))}</option>)}</select></label>:<p>No available times in this date range.</p>}</>}{date&&!loadingSlots&&!availability&&<button type="button" onClick={()=>setRetry(n=>n+1)}>Retry availability</button>}{slot&&<p role="status">Time selected for review. No booking has been created, no time reserved, and no payment taken.</p>}<label>Your name<input autoComplete="name" maxLength={200} value={name} onChange={e=>{setReview(false);setName(e.target.value);}}/></label><label>Email<input type="email" autoComplete="email" maxLength={254} value={email} onChange={e=>{setReview(false);setEmail(e.target.value);}}/></label><button type="button" disabled={!readyToReview()||busy} onClick={()=>setReview(true)}>Review request</button></fieldset></section>}
 {review&&!locked&&<section aria-label="Review request"><h2>Review your request</h2><p>{name.trim()} · {email.trim()}</p><p>Package: {cat.packages.find(p=>p.id===selection.packageId)?.label}; vehicle: {cat.vehicles.find(v=>v.id===selection.vehicleId)?.label}.</p><p>Addons: {cat.addons.filter(a=>selection.addonIds.includes(a.id)).map(a=>a.name).join(', ')||'None'}.</p>{selection.locationId&&<p>Location: {cat.locations.find(l=>l.id===selection.locationId)?.label}.</p>}<p>Requested time: {new Date(slot).toLocaleString()}.</p>{quote&&<p>Server total: {formatMoney(quote.pricing.total)}</p>}<p>Send this unconfirmed request first. A temporary reservation and a verified test-payment check require separate explicit actions.</p><button type="button" disabled={busy||expired} onClick={sendRequest}>Send unconfirmed request</button></section>}
 {unknown&&!operation.request&&<section><h2>Request status unverified</h2><p>Your exact request is frozen. Do not start another request or reload this page while its status is uncertain. Retry the same request, or contact the business.</p>{operation.body&&<p>Requested time: {new Date(operation.body.requestedStart).toLocaleString()}.</p>}{!expired&&<button type="button" disabled={busy} onClick={sendRequest}>Retry the same request</button>}</section>}
 {operation.phase==='request_pending'&&<p role="status">Sending your exact request…</p>}</>}
 </>:busy?<p role="status">Opening Detailing form…</p>:null}</>}
 </main></div>;
}
