import {render,screen,fireEvent,waitFor,cleanup} from '@testing-library/react';
import {afterEach,it,expect,vi} from 'vitest';
import {HostedFlow} from './HostedFlow';
import {createFlowClient} from '@lumin/flow-ui';
const id='11111111-1111-4111-8111-111111111111',token='t'.repeat(43);
const service={id,name:'Published service',durationMinutes:30,questions:[{id:'q',prompt:'Choose an option',kind:'single_choice',required:true,choices:[{id:'a',label:'Option A'}]}]};
const slotStart=new Date('2030-01-01T10:00').toISOString();
const availabilityResponse=(url:string)=>{const start=new Date(new URL(url).searchParams.get('from')!);start.setHours(10);return new Response(JSON.stringify({ok:true,data:{schemaVersion:1,serviceId:id,durationMinutes:30,slots:[{start:start.toISOString(),end:new Date(start.getTime()+1800000).toISOString(),remainingCapacity:1}]}}));};
const bookingReference='LMN-'+id.replaceAll('-','').toUpperCase();
const config={key:'request',steps:[{key:'q',questionKey:'q',kind:'question',required:true}]};
afterEach(()=>{cleanup();vi.unstubAllGlobals();});
it('uses pinned questions and identical body/key for ambiguous retry, never exposes token or confirmation',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});const bodies:string[]=[];const calls:RequestInit[]=[];
 vi.stubGlobal('fetch',vi.fn(async(url:string,options:RequestInit)=>{calls.push(options);if(url.includes('/availability'))return availabilityResponse(url);if(url.includes('/sessions'))return new Response(JSON.stringify({ok:true,data:{sessionToken:token,expiresAt:'2035-01-01T00:00:00Z',render:{versionId:id,config,service}}}));bodies.push(options.body as string);if(bodies.length===1)throw Error('connection interrupted with private-server-details');return new Response(JSON.stringify({ok:true,data:{reference:bookingReference,state:'draft',confirmed:false}}));}));
 render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await screen.findByText('Published service');fireEvent.change(screen.getByLabelText('Choose an option'),{target:{value:'a'}});fireEvent.change(screen.getByLabelText('Your name'),{target:{value:'Synthetic Person'}});fireEvent.change(screen.getByLabelText('Email'),{target:{value:'synthetic@example.test'}});fireEvent.change(screen.getByLabelText('Requested date'),{target:{value:'2030-01-01'}});await waitFor(()=>expect(screen.getByLabelText('Available time')).toBeEnabled());fireEvent.change(screen.getByLabelText('Available time'),{target:{value:slotStart}});fireEvent.click(screen.getByText('Send unconfirmed request'));await screen.findByText('Retry the same request');expect(screen.getByLabelText('Your name')).toBeDisabled();fireEvent.click(screen.getByText('Retry the same request'));await screen.findByText('Request saved');expect(bodies).toHaveLength(2);expect(JSON.parse(bodies[0]!).requestedStart).toBe(slotStart);expect(bodies[0]).toBe(bodies[1]);expect(JSON.parse(bodies[0]!)).not.toHaveProperty('tenantId');expect(JSON.parse(bodies[0]!)).not.toHaveProperty('serviceId');expect(calls[1]!.headers).toMatchObject({Authorization:'Bearer '+token});expect(document.body.textContent).not.toContain(token);expect(document.body.textContent).not.toContain('private-server-details');expect(screen.getByText(/Your request is unconfirmed/)).toBeTruthy();
});
it('does not create a customer session from an HTTP page',()=>{vi.stubGlobal('location',{protocol:'http:'});const fetcher=vi.fn();vi.stubGlobal('fetch',fetcher);render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);expect(screen.getByText('Secure customer page required')).toBeTruthy();expect(fetcher).not.toHaveBeenCalled();});
it('invalid installation IDs fail visibly without network calls',async()=>{vi.stubGlobal('location',{protocol:'https:'});const fetcher=vi.fn();vi.stubGlobal('fetch',fetcher);render(<HostedFlow installationId="bad?credential=unsafe" apiUrl="https://api.example"/>);await waitFor(()=>expect(screen.getByRole('alert')).toHaveTextContent('unavailable'));expect(fetcher).not.toHaveBeenCalled();});
it('V2 submits canonical pinned answers and omits newly hidden fields on an identical retry',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});const bodies:string[]=[];
 const v2={versionId:id,renderSchemaVersion:2,submissionMode:'unconfirmed_request',service:{...service,questions:[{id:'hasOwnProperty',prompt:'Mode',kind:'single_choice',required:true,choices:[{id:'toString',label:'More'},{id:'no',label:'Less'}]},{id:'quantity',prompt:'Extra amount',kind:'quantity',required:false,choices:[],minQty:0,maxQty:3},{id:'multi',prompt:'Extras',kind:'multi_choice',required:false,choices:[{id:'😀',label:'First'},{id:'é',label:'Second'}]}]},config:{key:'v2',steps:[{key:'mode',questionKey:'hasOwnProperty',kind:'question',required:true},{key:'quantity',questionKey:'quantity',kind:'question',required:true,visibleWhen:{field:'hasOwnProperty',op:'eq',value:'toString'}},{key:'multi',questionKey:'multi',kind:'question',required:false}]}};
 vi.stubGlobal('fetch',vi.fn(async(url:string,options:RequestInit)=>{if(url.includes('/availability'))return availabilityResponse(url);if(url.includes('/sessions'))return new Response(JSON.stringify({ok:true,data:{sessionToken:token,expiresAt:'2035-01-01T00:00:00Z',render:v2}}));bodies.push(options.body as string);if(bodies.length===1)throw Error('interrupted');return new Response(JSON.stringify({ok:true,data:{reference:bookingReference,state:'draft',confirmed:false}}));}));
 render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await screen.findByText('Published service');fireEvent.change(screen.getByLabelText('Mode'),{target:{value:'toString'}});fireEvent.change(screen.getByLabelText('Extra amount'),{target:{value:'2'}});fireEvent.change(screen.getByLabelText('Mode'),{target:{value:'no'}});fireEvent.click(screen.getByLabelText('Second'));fireEvent.click(screen.getByLabelText('First'));fireEvent.change(screen.getByLabelText('Your name'),{target:{value:'Synthetic Person'}});fireEvent.change(screen.getByLabelText('Email'),{target:{value:'synthetic@example.test'}});fireEvent.change(screen.getByLabelText('Requested date'),{target:{value:'2030-01-01'}});await waitFor(()=>expect(screen.getByLabelText('Available time')).toBeEnabled());fireEvent.change(screen.getByLabelText('Available time'),{target:{value:slotStart}});fireEvent.click(screen.getByText('Send unconfirmed request'));await screen.findByText('Retry the same request');fireEvent.click(screen.getByText('Retry the same request'));await screen.findByText('Request saved');expect(bodies[0]).toBe(bodies[1]);const body=JSON.parse(bodies[0]!);expect(body.answers).not.toHaveProperty('quantity');expect(body.answers.multi.choiceIds).toEqual(['😀','é']);expect(body.answers.hasOwnProperty.choiceIds).toEqual(['no']);expect(body).not.toHaveProperty('renderSchemaVersion');
});

it.each(['foreign service','wrong duration','invalid time'])('rejects %s availability without enabling submission',async(kind)=>{
 vi.stubGlobal('location',{protocol:'https:'});const submit=vi.fn();
 vi.stubGlobal('fetch',vi.fn(async(url:string)=>{if(url.includes('/availability'))return new Response(JSON.stringify({ok:true,data:{schemaVersion:1,serviceId:kind==='foreign service'?'22222222-2222-4222-8222-222222222222':id,durationMinutes:kind==='wrong duration'?60:30,slots:[{start:kind==='invalid time'?'invalid':slotStart,end:new Date(Date.parse(slotStart)+(kind==='wrong duration'?3600000:1800000)).toISOString(),remainingCapacity:1}]}}));if(url.includes('/sessions'))return new Response(JSON.stringify({ok:true,data:{sessionToken:token,expiresAt:'2035-01-01T00:00:00Z',render:{versionId:id,config,service}}}));submit();throw Error('unexpected');}));
 render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await screen.findByText('Published service');fireEvent.change(screen.getByLabelText('Requested date'),{target:{value:'2030-01-01'}});await screen.findByText('Retry available times');expect(screen.getByLabelText('Available time')).toBeDisabled();expect(screen.getByText('Send unconfirmed request')).toBeDisabled();expect(submit).not.toHaveBeenCalled();
});
it('clears selected slots immediately and discards responses for an earlier date',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});let resolve!:(response:Response)=>void;
 vi.stubGlobal('fetch',vi.fn(async(url:string)=>{if(url.includes('/availability')){if(new URL(url).searchParams.get('from')===new Date('2030-01-01T00:00').toISOString())return new Promise<Response>(r=>resolve=r);return availabilityResponse(url);}return new Response(JSON.stringify({ok:true,data:{sessionToken:token,expiresAt:'2035-01-01T00:00:00Z',render:{versionId:id,config,service}}}));}));
 render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await screen.findByText('Published service');fireEvent.change(screen.getByLabelText('Requested date'),{target:{value:'2030-01-01'}});await waitFor(()=>expect(resolve).toBeTypeOf('function'));fireEvent.change(screen.getByLabelText('Requested date'),{target:{value:'2030-01-02'}});await waitFor(()=>expect(screen.getByLabelText('Available time')).toBeEnabled());const next=new Date('2030-01-02T10:00').toISOString();fireEvent.change(screen.getByLabelText('Available time'),{target:{value:next}});resolve(availabilityResponse('https://api.example?from='+encodeURIComponent(new Date('2030-01-01T00:00').toISOString())));await waitFor(()=>expect(screen.getByLabelText('Available time')).toHaveValue(next));expect(Array.from((screen.getByLabelText('Available time') as HTMLSelectElement).options).map(option=>option.value)).toEqual(['',next]);
 fireEvent.change(screen.getByLabelText('Requested date'),{target:{value:''}});expect(screen.getByLabelText('Available time')).toHaveValue('');expect(screen.getByText('Send unconfirmed request')).toBeDisabled();
});
it('retries failed availability and shows an honest empty date',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});let attempts=0;
 vi.stubGlobal('fetch',vi.fn(async(url:string)=>{if(url.includes('/availability')){if(++attempts===1)throw Error('secret details');return new Response(JSON.stringify({ok:true,data:{schemaVersion:1,serviceId:id,durationMinutes:30,slots:[]}}));}return new Response(JSON.stringify({ok:true,data:{sessionToken:token,expiresAt:'2035-01-01T00:00:00Z',render:{versionId:id,config,service}}}));}));
 render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await screen.findByText('Published service');fireEvent.change(screen.getByLabelText('Requested date'),{target:{value:'2030-01-01'}});fireEvent.click(await screen.findByText('Retry available times'));await screen.findByText('No available times on this date. Choose another date.');expect(attempts).toBe(2);expect(screen.getByText('Send unconfirmed request')).toBeDisabled();expect(document.body.textContent).not.toContain('secret details');
});
it('blocks submission when a session expires after slots were loaded',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});const now=vi.spyOn(Date,'now').mockReturnValue(Date.parse('2029-12-01T00:00:00Z'));const sent=vi.fn();
 vi.stubGlobal('fetch',vi.fn(async(url:string)=>{if(url.includes('/availability'))return availabilityResponse(url);if(url.includes('/sessions'))return new Response(JSON.stringify({ok:true,data:{sessionToken:token,expiresAt:'2030-01-01T00:00:00Z',render:{versionId:id,config,service}}}));sent();throw Error('unexpected');}));
 try{render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await screen.findByText('Published service');fireEvent.change(screen.getByLabelText('Requested date'),{target:{value:'2030-01-01'}});await waitFor(()=>expect(screen.getByLabelText('Available time')).toBeEnabled());fireEvent.change(screen.getByLabelText('Available time'),{target:{value:slotStart}});now.mockReturnValue(Date.parse('2030-01-01T00:00:00Z'));fireEvent.submit(screen.getByText('Send unconfirmed request').closest('form')!);await screen.findAllByText('Your session expired. Reload this page to start again.');expect(sent).not.toHaveBeenCalled();expect(screen.getByText('Send unconfirmed request')).toBeDisabled();}finally{now.mockRestore();}
});
it('offers a cross-midnight slot from a full-day response while omitting next-day boundary starts',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});const {createAvailabilityEngine}=await import('@lumin/core');let expected:string[]=[];let crossMidnight='';
 vi.stubGlobal('fetch',vi.fn(async(url:string)=>{if(url.includes('/availability')){const query=new URL(url).searchParams,from=query.get('from')!,to=query.get('to')!;const browserZone=Intl.DateTimeFormat().resolvedOptions().timeZone;
 const tenantTimezone=browserZone==='America/Los_Angeles'?'Asia/Kolkata':'America/Los_Angeles';
 const slots=createAvailabilityEngine().getSlots({tenantTimezone,serviceId:id,durationMinutes:30,policy:{leadTimeMinutes:0,horizonDays:60,slotIntervalMinutes:15},rules:Array.from({length:7},(_,weekday)=>({id,tenantId:id,serviceId:id,weekday,startMinute:0,endMinute:1440,capacity:1})),overrides:[],existing:[],now:new Date(Date.parse(from)-86400000).toISOString(),from,to});
 expected=slots.filter(slot=>Date.parse(slot.start)<Date.parse(to)).map(slot=>slot.start);crossMidnight=slots.find(slot=>Date.parse(slot.start)<Date.parse(to)&&Date.parse(slot.end)>Date.parse(to))!.start;expect(slots.some(slot=>Date.parse(slot.start)===Date.parse(to))).toBe(true);
 return new Response(JSON.stringify({ok:true,data:{schemaVersion:1,serviceId:id,durationMinutes:30,slots}}));}return new Response(JSON.stringify({ok:true,data:{sessionToken:token,expiresAt:'2035-01-01T00:00:00Z',render:{versionId:id,config,service}}}));}));
 render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await screen.findByText('Published service');fireEvent.change(screen.getByLabelText('Requested date'),{target:{value:'2030-01-01'}});await waitFor(()=>expect(screen.getByLabelText('Available time')).toBeEnabled());const selector=screen.getByLabelText('Available time') as HTMLSelectElement;expect(Array.from(selector.options).slice(1).map(option=>option.value)).toEqual(expected);fireEvent.change(selector,{target:{value:crossMidnight}});expect(screen.getByText('Send unconfirmed request')).toBeEnabled();
});
async function saveRequest(retryRequest=false){
 await screen.findByText('Published service');fireEvent.change(screen.getByLabelText('Choose an option'),{target:{value:'a'}});fireEvent.change(screen.getByLabelText('Your name'),{target:{value:'Synthetic Person'}});fireEvent.change(screen.getByLabelText('Email'),{target:{value:'synthetic@example.test'}});fireEvent.change(screen.getByLabelText('Requested date'),{target:{value:'2030-01-01'}});await waitFor(()=>expect(screen.getByLabelText('Available time')).toBeEnabled());fireEvent.change(screen.getByLabelText('Available time'),{target:{value:slotStart}});fireEvent.click(screen.getByText('Send unconfirmed request'));if(retryRequest){fireEvent.click(await screen.findByText('Retry the same request'));}await screen.findByText('Request saved');
}
it('keeps a saved request visible during an ambiguous hold retry using the identical session and empty body',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});const holds:RequestInit[]=[];
 vi.stubGlobal('fetch',vi.fn(async(url:string,options:RequestInit)=>{
  if(url.endsWith('/hold')){holds.push(options);if(holds.length===1)throw Error('private failure');return new Response(JSON.stringify({ok:true,data:{schemaVersion:1,bookingId:id,holdId:id,status:'active',expiresAt:'2030-01-01T10:05:00Z'}}));}
  if(url.includes('/availability'))return availabilityResponse(url);if(url.includes('/sessions'))return new Response(JSON.stringify({ok:true,data:{sessionToken:token,expiresAt:'2035-01-01T00:00:00Z',render:{versionId:id,config,service}}}));return new Response(JSON.stringify({ok:true,data:{reference:bookingReference,state:'draft',confirmed:false}}));
 }));
 render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await saveRequest();expect(holds).toHaveLength(0);fireEvent.click(screen.getByText('Reserve selected time'));await screen.findByText('Retry reservation of selected time');expect(screen.getByText('Request saved')).toBeTruthy();expect(screen.getByText(bookingReference)).toBeTruthy();expect(screen.getByText('Reservation status is unverified. Retry safely to check the same reservation.')).toBeTruthy();fireEvent.click(screen.getByText('Retry reservation of selected time'));await screen.findByText(/Selected time temporarily reserved until/);expect(holds).toHaveLength(2);expect(holds[0]!.body).toBe('{}');expect(holds[1]!.body).toBe(holds[0]!.body);expect(holds[0]!.headers).toEqual(holds[1]!.headers);expect(holds[0]!.headers).toMatchObject({Authorization:'Bearer '+token});expect(screen.getByText(/Your request is unconfirmed. No payment was taken/)).toBeTruthy();expect(screen.queryByText('Reserve selected time')).toBeNull();expect(document.body.textContent).not.toContain(token);expect(document.body.textContent).not.toContain('private failure');
});
it('keeps the saved request and refuses a hold after session expiry',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});const now=vi.spyOn(Date,'now').mockReturnValue(Date.parse('2029-12-01T00:00:00Z'));const held=vi.fn();
 vi.stubGlobal('fetch',vi.fn(async(url:string)=>{if(url.endsWith('/hold')){held();throw Error('unexpected');}if(url.includes('/availability'))return availabilityResponse(url);if(url.includes('/sessions'))return new Response(JSON.stringify({ok:true,data:{sessionToken:token,expiresAt:'2030-01-01T00:00:00Z',render:{versionId:id,config,service}}}));return new Response(JSON.stringify({ok:true,data:{reference:bookingReference,state:'draft',confirmed:false}}));}));
 try{render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await saveRequest();now.mockReturnValue(Date.parse('2030-01-01T00:00:00Z'));fireEvent.click(screen.getByText('Reserve selected time'));await screen.findByText('Your session expired. Your request remains saved. Contact the business for help with your saved request.');expect(held).not.toHaveBeenCalled();expect(screen.getByText(bookingReference)).toBeTruthy();expect(screen.queryByRole('button',{name:'Reserve selected time'})).toBeNull();}finally{now.mockRestore();}
});
it('changes active hold wording when the temporary reservation expires',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});let expiresAt='';
 vi.stubGlobal('fetch',vi.fn(async(url:string)=>{if(url.endsWith('/hold')){expiresAt=new Date(Date.now()+150).toISOString();return new Response(JSON.stringify({ok:true,data:{schemaVersion:1,bookingId:id,holdId:id,status:'active',expiresAt}}));}if(url.includes('/availability'))return availabilityResponse(url);if(url.includes('/sessions'))return new Response(JSON.stringify({ok:true,data:{sessionToken:token,expiresAt:'2035-01-01T00:00:00Z',render:{versionId:id,config,service}}}));return new Response(JSON.stringify({ok:true,data:{reference:bookingReference,state:'draft',confirmed:false}}));}));
 render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await saveRequest();fireEvent.click(screen.getByText('Reserve selected time'));await screen.findByText(/Selected time temporarily reserved until/);await screen.findByText("The temporary reservation's reported expiry has passed. Your request remains saved and unconfirmed.");expect(screen.queryByText(/Selected time temporarily reserved until/)).toBeNull();expect(screen.getByText(bookingReference)).toBeTruthy();
});
it('rejects an expired hold receipt without claiming a reservation',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});vi.stubGlobal('fetch',vi.fn(async(url:string)=>{if(url.endsWith('/hold'))return new Response(JSON.stringify({ok:true,data:{schemaVersion:1,bookingId:id,holdId:id,status:'active',expiresAt:'2020-01-01T00:00:00Z'}}));if(url.includes('/availability'))return availabilityResponse(url);if(url.includes('/sessions'))return new Response(JSON.stringify({ok:true,data:{sessionToken:token,expiresAt:'2035-01-01T00:00:00Z',render:{versionId:id,config,service}}}));return new Response(JSON.stringify({ok:true,data:{reference:bookingReference,state:'draft',confirmed:false}}));}));
 render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await saveRequest();fireEvent.click(screen.getByText('Reserve selected time'));await screen.findByText('Retry reservation of selected time');expect(screen.getByText(bookingReference)).toBeTruthy();expect(screen.queryByText(/Selected time temporarily reserved until/)).toBeNull();expect(screen.getByText('Reservation status is unverified. Retry safely to check the same reservation.')).toBeTruthy();
});
it('discards a pending hold when the installation changes',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});let resolve!:(response:Response)=>void;
 vi.stubGlobal('fetch',vi.fn(async(url:string)=>{if(url.endsWith('/hold'))return new Promise<Response>(r=>resolve=r);if(url.includes('/availability'))return availabilityResponse(url);if(url.includes('/sessions'))return new Response(JSON.stringify({ok:true,data:{sessionToken:token,expiresAt:'2035-01-01T00:00:00Z',render:{versionId:id,config,service}}}));return new Response(JSON.stringify({ok:true,data:{reference:bookingReference,state:'draft',confirmed:false}}));}));
 const {rerender}=render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await saveRequest();fireEvent.click(screen.getByText('Reserve selected time'));await waitFor(()=>expect(resolve).toBeTypeOf('function'));rerender(<HostedFlow installationId="22222222-2222-4222-8222-222222222222" apiUrl="https://api.example"/>);await screen.findByText('Published service');resolve(new Response(JSON.stringify({ok:true,data:{schemaVersion:1,bookingId:id,holdId:id,status:'active',expiresAt:'2030-01-01T10:05:00Z'}})));await waitFor(()=>expect(screen.queryByText(/Selected time temporarily reserved until/)).toBeNull());expect(screen.queryByText(bookingReference)).toBeNull();expect(screen.getByText('Send unconfirmed request')).toBeDisabled();
});
it.each(['foreign booking','unverifiable reference'])('rejects a hold receipt with %s without claiming a reservation',async(kind)=>{
 vi.stubGlobal('location',{protocol:'https:'});const reference=kind==='unverifiable reference'?'LMN-GENERIC':bookingReference;
 vi.stubGlobal('fetch',vi.fn(async(url:string)=>{if(url.endsWith('/hold'))return new Response(JSON.stringify({ok:true,data:{schemaVersion:1,bookingId:kind==='foreign booking'?'22222222-2222-4222-8222-222222222222':id,holdId:id,status:'active',expiresAt:'2030-01-01T10:05:00Z'}}));if(url.includes('/availability'))return availabilityResponse(url);if(url.includes('/sessions'))return new Response(JSON.stringify({ok:true,data:{sessionToken:token,expiresAt:'2035-01-01T00:00:00Z',render:{versionId:id,config,service}}}));return new Response(JSON.stringify({ok:true,data:{reference,state:'draft',confirmed:false}}));}));
 render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await saveRequest();fireEvent.click(screen.getByText('Reserve selected time'));await screen.findByText('Retry reservation of selected time');expect(screen.getByText(reference)).toBeTruthy();expect(screen.queryByText(/Selected time temporarily reserved until/)).toBeNull();expect(screen.getByText('Reservation status is unverified. Retry safely to check the same reservation.')).toBeTruthy();expect(screen.queryByText(/No time was reserved/)).toBeNull();
});
const paidRender={versionId:id,renderSchemaVersion:3,submissionMode:'paid_service_request',paymentMode:'staging_mock',simulated:true,service:{id,name:'Paid housekeeping',durationMinutes:30,price:{amount:12500,currency:'USD'}}};
it('renders only the immutable published name and whitelisted presentation while retaining service price',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});
 const publication={name:'<img src=x onerror=alert(1)>',draftRevision:2,presentation:{accentColor:'#0e7490',layout:'compact'}};
 const fetcher=vi.fn(async()=>new Response(JSON.stringify({ok:true,data:{sessionToken:token,expiresAt:'2035-01-01T00:00:00Z',render:{...paidRender,publication}}})));
 vi.stubGlobal('fetch',fetcher);render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);
 const heading=await screen.findByRole('heading',{name:publication.name});
 expect(heading.querySelector('img')).toBeNull();
 expect(screen.getByText('Service: Paid housekeeping')).toBeTruthy();
 expect(screen.getByText('Published service price: $125.00')).toBeTruthy();
 const main=screen.getByRole('main');expect(main).toHaveClass('paid-form-layout-compact');
 expect(main.style.getPropertyValue('--accent')).toBe('#0e7490');
 expect(main.parentElement).toHaveClass('checkout-root');
 expect(screen.getByLabelText('Your name')).toBeEnabled();
 expect(screen.queryByText('Test booking confirmed')).toBeNull();expect(fetcher).toHaveBeenCalledTimes(1);
});
it('rejects a published presentation with an unapproved color instead of applying caller CSS',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});
 vi.stubGlobal('fetch',vi.fn(async()=>new Response(JSON.stringify({ok:true,data:{sessionToken:token,expiresAt:'2035-01-01T00:00:00Z',render:{...paidRender,publication:{name:'Invalid design',draftRevision:1,presentation:{accentColor:'url(https://unapproved.example)',layout:'compact'}}}}}))));
 render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);
 await screen.findByRole('alert');expect(screen.queryByLabelText('Your name')).toBeNull();
 expect(screen.getByRole('main').style.getPropertyValue('--accent')).toBe('');
});
const paymentData={schemaVersion:1,bookingId:id,paymentId:'33333333-3333-4333-8333-333333333333',state:'confirmed',replayed:false,provider:'staging_mock',simulated:true};
async function savePaidRequest(retryRequest=false){
 await screen.findByText('Paid housekeeping');fireEvent.change(screen.getByLabelText('Your name'),{target:{value:'Synthetic Person'}});fireEvent.change(screen.getByLabelText('Email'),{target:{value:'synthetic@example.test'}});fireEvent.change(screen.getByLabelText('Requested date'),{target:{value:'2030-01-01'}});await waitFor(()=>expect(screen.getByLabelText('Available time')).toBeEnabled());fireEvent.change(screen.getByLabelText('Available time'),{target:{value:slotStart}});fireEvent.click(screen.getByText('Send unconfirmed request'));if(retryRequest){fireEvent.click(await screen.findByText('Retry the same request'));}await screen.findByText('Request saved');
}
function paidTransport(payment:(options:RequestInit)=>Promise<Response>,holdExpiry='2030-01-01T10:05:00Z',sessionExpiry='2035-01-01T00:00:00Z'){
 return vi.fn(async(url:string,options:RequestInit)=>{if(url.endsWith('/mock-payment'))return payment(options);if(url.endsWith('/hold'))return new Response(JSON.stringify({ok:true,data:{schemaVersion:1,bookingId:id,holdId:id,status:'active',expiresAt:holdExpiry}}));if(url.includes('/availability'))return availabilityResponse(url);if(url.includes('/sessions'))return new Response(JSON.stringify({ok:true,data:{sessionToken:token,expiresAt:sessionExpiry,render:paidRender}}));return new Response(JSON.stringify({ok:true,data:{reference:bookingReference,state:'draft',confirmed:false}}));});
}
it('uses pinned V3 price and explicit request, hold and staging test payment before authoritative confirmation',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});const payment=vi.fn(async()=>new Response(JSON.stringify({ok:true,data:paymentData})));const transport=paidTransport(payment);vi.stubGlobal('fetch',transport);
 render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await screen.findByText('Paid housekeeping');expect(screen.getByText('Published service price: $125.00')).toBeTruthy();expect(screen.getByText(/Staging test mode/)).toBeTruthy();expect(screen.queryByLabelText('Choose an option')).toBeNull();await savePaidRequest();expect(payment).not.toHaveBeenCalled();expect(screen.queryByText('Make staging test payment')).toBeNull();fireEvent.click(screen.getByText('Reserve selected time'));await screen.findByText('Make staging test payment');expect(payment).not.toHaveBeenCalled();expect(screen.queryByText('Test booking confirmed')).toBeNull();fireEvent.click(screen.getByText('Make staging test payment'));await screen.findByText('Test booking confirmed');expect(payment).toHaveBeenCalledTimes(1);expect(screen.getByText(/The server confirmed this booking with a simulated staging payment/)).toBeTruthy();expect(screen.getByText(bookingReference)).toBeTruthy();expect(document.body.textContent).not.toContain(token);
 const request=transport.mock.calls.find(([url])=>url.endsWith('/request'))!;expect(JSON.parse(request[1].body as string)).toMatchObject({answers:{},requestedStart:slotStart});expect(Object.keys(JSON.parse(request[1].body as string)).sort()).toEqual(['answers','customer','idempotencyKey','requestedStart']);for(const [url,options] of transport.mock.calls.filter(([url])=>url.endsWith('/hold')||url.endsWith('/mock-payment'))){expect(url).not.toMatch(/tenantId|serviceId|bookingId|amount/);expect(options.body).toBe('{}');expect(options.headers).toMatchObject({Authorization:'Bearer '+token});}
});
it('retries the same ambiguous test payment after hold expiry without inventing confirmation',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});const now=vi.spyOn(Date,'now').mockReturnValue(Date.parse('2029-12-01T00:00:00Z'));const bodies:RequestInit[]=[];const transport=paidTransport(async(options)=>{bodies.push(options);if(bodies.length===1)throw Error('private payment details');return new Response(JSON.stringify({ok:true,data:{...paymentData,replayed:true}}));},'2029-12-01T00:05:00Z');vi.stubGlobal('fetch',transport);
 try{render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await savePaidRequest();fireEvent.click(screen.getByText('Reserve selected time'));fireEvent.click(await screen.findByText('Make staging test payment'));await screen.findByText('Retry the same test payment');expect(screen.getByText('Request saved')).toBeTruthy();expect(screen.queryByText('Test booking confirmed')).toBeNull();expect(screen.getByText('Test payment and confirmation status are unverified. Retry safely using the same saved request.')).toBeTruthy();now.mockReturnValue(Date.parse('2029-12-01T00:06:00Z'));fireEvent.click(screen.getByText('Retry the same test payment'));await screen.findByText('Test booking confirmed');expect(bodies).toHaveLength(2);expect(bodies[0]!.body).toBe('{}');expect(bodies[1]!.body).toBe(bodies[0]!.body);expect(bodies[1]!.headers).toEqual(bodies[0]!.headers);expect(transport.mock.calls.filter(([url])=>url.endsWith('/request'))).toHaveLength(1);expect(document.body.textContent).not.toContain('private payment details');}finally{now.mockRestore();}
});
it.each(['foreign booking','real provider','unconfirmed state'])('rejects %s payment receipts without confirmation claims',async(kind)=>{
 vi.stubGlobal('location',{protocol:'https:'});vi.stubGlobal('fetch',paidTransport(async()=>new Response(JSON.stringify({ok:true,data:{...paymentData,...(kind==='foreign booking'?{bookingId:'22222222-2222-4222-8222-222222222222'}:kind==='real provider'?{provider:'stripe'}:{state:'draft'})}}))));render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await savePaidRequest();fireEvent.click(screen.getByText('Reserve selected time'));fireEvent.click(await screen.findByText('Make staging test payment'));await screen.findByText('Retry the same test payment');expect(screen.queryByText('Test booking confirmed')).toBeNull();expect(screen.getByText(bookingReference)).toBeTruthy();expect(screen.getByText(/Test payment status is unverified/)).toBeTruthy();
});
it('blocks first test payment after the accepted hold expiry',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});const now=vi.spyOn(Date,'now').mockReturnValue(Date.parse('2029-12-01T00:00:00Z'));const payment=vi.fn(async()=>new Response(JSON.stringify({ok:true,data:paymentData})));vi.stubGlobal('fetch',paidTransport(payment,'2029-12-01T00:05:00Z','2029-12-01T00:10:00Z'));
 try{render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await savePaidRequest();fireEvent.click(screen.getByText('Reserve selected time'));await screen.findByText('Make staging test payment');now.mockReturnValue(Date.parse('2029-12-01T00:06:00Z'));fireEvent.click(screen.getByText('Make staging test payment'));await waitFor(()=>expect(screen.getByText('Make staging test payment')).toBeDisabled());expect(payment).not.toHaveBeenCalled();}finally{now.mockRestore();}
});
it('discards a late test-payment receipt after switching installation',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});let resolve!:(value:Response)=>void;vi.stubGlobal('fetch',paidTransport(()=>new Promise<Response>(r=>resolve=r)));const {rerender}=render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await savePaidRequest();fireEvent.click(screen.getByText('Reserve selected time'));fireEvent.click(await screen.findByText('Make staging test payment'));await waitFor(()=>expect(resolve).toBeTypeOf('function'));rerender(<HostedFlow installationId="22222222-2222-4222-8222-222222222222" apiUrl="https://api.example"/>);await screen.findByText('Paid housekeeping');resolve(new Response(JSON.stringify({ok:true,data:paymentData})));await waitFor(()=>expect(screen.queryByText('Test booking confirmed')).toBeNull());expect(screen.queryByText(bookingReference)).toBeNull();expect(screen.getByText('Send unconfirmed request')).toBeDisabled();
});
it('blocks test payment after session expiry while retaining the saved request',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});const now=vi.spyOn(Date,'now').mockReturnValue(Date.parse('2029-12-01T00:00:00Z'));const payment=vi.fn(async()=>new Response(JSON.stringify({ok:true,data:paymentData})));vi.stubGlobal('fetch',paidTransport(payment,'2029-12-01T00:15:00Z','2029-12-01T00:10:00Z'));
 try{render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await savePaidRequest();fireEvent.click(screen.getByText('Reserve selected time'));await screen.findByText('Make staging test payment');now.mockReturnValue(Date.parse('2029-12-01T00:11:00Z'));fireEvent.click(screen.getByText('Make staging test payment'));await screen.findByText('Your session expired. Your request remains saved. Contact the business for help with your saved request.');expect(payment).not.toHaveBeenCalled();expect(screen.queryByText('Make staging test payment')).toBeNull();expect(screen.getByText(bookingReference)).toBeTruthy();}finally{now.mockRestore();}
});
it('keeps V3 empty answers and the original request identity on an ambiguous request retry',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});const bodies:string[]=[];const base=paidTransport(async()=>{throw Error('unexpected payment');});vi.stubGlobal('fetch',vi.fn(async(url:string,options:RequestInit)=>{if(url.endsWith('/request')){bodies.push(options.body as string);if(bodies.length===1)throw Error('interrupted');}return base(url,options);}));
 render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await savePaidRequest(true);expect(bodies).toHaveLength(2);expect(bodies[0]).toBe(bodies[1]);expect(JSON.parse(bodies[0]!).answers).toEqual({});expect(screen.queryByText('Make staging test payment')).toBeNull();expect(screen.getByText('Reserve selected time')).toBeTruthy();
});

const paidOptionRender={versionId:id,renderSchemaVersion:4,submissionMode:'paid_option_request',paymentMode:'staging_mock',simulated:true,service:{...paidRender.service,questions:[{id:'visit',prompt:'Choose a visit',kind:'single_choice',required:true,choices:[{id:'first',label:'First visit'},{id:'return',label:'Return visit'}]}]}};
function optionTransport(request:(options:RequestInit)=>Promise<Response>=async()=>new Response(JSON.stringify({ok:true,data:{reference:bookingReference,state:'draft',confirmed:false}})),payment:(options:RequestInit)=>Promise<Response>=async()=>new Response(JSON.stringify({ok:true,data:paymentData})),expiresAt='2035-01-01T00:00:00Z'){
 return vi.fn(async(url:string,options:RequestInit)=>{if(url.endsWith('/request'))return request(options);if(url.endsWith('/mock-payment'))return payment(options);if(url.endsWith('/hold'))return new Response(JSON.stringify({ok:true,data:{schemaVersion:1,bookingId:id,holdId:id,status:'active',expiresAt:'2030-01-01T10:05:00Z'}}));if(url.includes('/availability'))return availabilityResponse(url);if(url.includes('/sessions'))return new Response(JSON.stringify({ok:true,data:{sessionToken:token,expiresAt,render:paidOptionRender}}));throw Error('Unexpected request');});
}
async function fillOptionRequest(choice='return'){
 await screen.findByText('Paid housekeeping');if(choice)fireEvent.change(screen.getByLabelText('Choose a visit'),{target:{value:choice}});fireEvent.change(screen.getByLabelText('Your name'),{target:{value:'Synthetic Person'}});fireEvent.change(screen.getByLabelText('Email'),{target:{value:'synthetic@example.test'}});fireEvent.change(screen.getByLabelText('Requested date'),{target:{value:'2030-01-01'}});await waitFor(()=>expect(screen.getByLabelText('Available time')).toBeEnabled());fireEvent.change(screen.getByLabelText('Available time'),{target:{value:slotStart}});
}
it('V4 requires a pinned accessible option before submission and rejects a caller-injected catalog choice',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});const request=vi.fn(async()=>new Response(JSON.stringify({ok:true,data:{reference:bookingReference,state:'draft',confirmed:false}})));vi.stubGlobal('fetch',optionTransport(request));render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await fillOptionRequest('');const select=screen.getByRole('combobox',{name:'Choose a visit'}) as HTMLSelectElement;expect(select).toBeRequired();expect(Array.from(select.options).map(option=>option.value)).toEqual(['','first','return']);expect(Number.parseFloat(select.style.minWidth)).toBe(0);fireEvent.submit(screen.getByText('Send unconfirmed request').closest('form')!);await screen.findByText('Complete the required answers and choose an available future time.');expect(request).not.toHaveBeenCalled();const foreign=document.createElement('option');foreign.value='foreign';foreign.textContent='Caller choice';select.appendChild(foreign);fireEvent.change(select,{target:{value:'foreign'}});fireEvent.submit(screen.getByText('Send unconfirmed request').closest('form')!);expect(request).not.toHaveBeenCalled();expect(screen.queryByText('Request saved')).toBeNull();expect(screen.getByText('Published service price: $125.00')).toBeTruthy();
});
it('V4 freezes the original option/body/key through ambiguous request retry and shows it in saved and authoritative confirmed views',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});const bodies:string[]=[];const payment=vi.fn(async(_options:RequestInit)=>new Response(JSON.stringify({ok:true,data:paymentData})));const transport=optionTransport(async options=>{bodies.push(options.body as string);if(bodies.length===1)throw Error('PRIVATE-OPTION-ERROR');return new Response(JSON.stringify({ok:true,data:{reference:bookingReference,state:'draft',confirmed:false}}));},payment);vi.stubGlobal('fetch',transport);render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await fillOptionRequest();fireEvent.click(screen.getByText('Send unconfirmed request'));await screen.findByText('Retry the same request');expect(screen.getByLabelText('Choose a visit')).toBeDisabled();fireEvent.change(screen.getByLabelText('Choose a visit'),{target:{value:'first'}});fireEvent.click(screen.getByText('Retry the same request'));await screen.findByText('Request saved');expect(bodies[1]).toBe(bodies[0]);expect(JSON.parse(bodies[0]!)).toEqual({idempotencyKey:expect.any(String),answers:{visit:{choiceIds:['return']}},customer:{name:'Synthetic Person',email:'synthetic@example.test'},requestedStart:slotStart});expect(screen.getByText('Selected option (Choose a visit): Return visit')).toBeTruthy();expect(payment).not.toHaveBeenCalled();expect(screen.queryByText('Test booking confirmed')).toBeNull();fireEvent.click(screen.getByText('Reserve selected time'));fireEvent.click(await screen.findByText('Make staging test payment'));await screen.findByText('Test booking confirmed');expect(screen.getByText('Selected option (Choose a visit): Return visit')).toBeTruthy();expect(screen.getByText('Published service price: $125.00')).toBeTruthy();expect(transport.mock.calls.filter(([url])=>url.endsWith('/hold'))[0]?.[1]?.body).toBe('{}');expect(payment.mock.calls[0]?.[0]?.body).toBe('{}');expect(document.body.textContent).not.toContain(token);expect(document.body.textContent).not.toContain('PRIVATE-OPTION-ERROR');
});
it.each(['unknown version','extra choice price','optional question','duplicate choices'])('rejects %s V4 sessions without rendering option, payment or legacy fallback controls',async(kind)=>{
 vi.stubGlobal('location',{protocol:'https:'});const q=paidOptionRender.service.questions[0]!;const invalidRender=kind==='unknown version'?{...paidOptionRender,renderSchemaVersion:5}:{...paidOptionRender,service:{...paidOptionRender.service,questions:[kind==='extra choice price'?{...q,choices:[{...q.choices[0],price:1},q.choices[1]]}:kind==='optional question'?{...q,required:false}:{...q,choices:[q.choices[0],q.choices[0]]}]}};vi.stubGlobal('fetch',vi.fn(async()=>new Response(JSON.stringify({ok:true,data:{sessionToken:token,expiresAt:'2035-01-01T00:00:00Z',render:invalidRender}}))));render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await screen.findByRole('alert');expect(screen.queryByLabelText('Choose a visit')).toBeNull();expect(screen.queryByText('Send unconfirmed request')).toBeNull();expect(screen.queryByText('Make staging test payment')).toBeNull();expect(screen.queryByText('Published service price: $125.00')).toBeNull();
});
it('discards a late V4 session after installation change and renders the new V3 without old choices',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});let finish!:(response:Response)=>void;const second='22222222-2222-4222-8222-222222222222';vi.stubGlobal('fetch',vi.fn(async(url:string)=>url.includes('/'+id+'/sessions')?new Promise<Response>(r=>finish=r):new Response(JSON.stringify({ok:true,data:{sessionToken:token,expiresAt:'2035-01-01T00:00:00Z',render:paidRender}}))));const {rerender}=render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await waitFor(()=>expect(finish).toBeTypeOf('function'));rerender(<HostedFlow installationId={second} apiUrl="https://api.example"/>);await screen.findByText('Paid housekeeping');finish(new Response(JSON.stringify({ok:true,data:{sessionToken:token,expiresAt:'2035-01-01T00:00:00Z',render:paidOptionRender}})));await waitFor(()=>expect(screen.queryByLabelText('Choose a visit')).toBeNull());expect(screen.queryByText(/Selected option/)).toBeNull();expect(screen.getByText('Send unconfirmed request')).toBeDisabled();
});
it('V4 expiry refuses a selected option request without sending or claiming confirmation',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});const now=vi.spyOn(Date,'now').mockReturnValue(Date.parse('2029-12-01T00:00:00Z'));const request=vi.fn(async()=>{throw Error('Unexpected submit');});vi.stubGlobal('fetch',optionTransport(request,async()=>{throw Error('Unexpected payment');},'2029-12-01T00:10:00Z'));
 try{render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await fillOptionRequest();now.mockReturnValue(Date.parse('2029-12-01T00:10:00Z'));fireEvent.submit(screen.getByText('Send unconfirmed request').closest('form')!);await screen.findAllByText('Your session expired. Reload this page to start again.');expect(request).not.toHaveBeenCalled();expect(screen.queryByText('Request saved')).toBeNull();expect(screen.queryByText('Test booking confirmed')).toBeNull();}finally{now.mockRestore();}
});
it('retains the frozen V4 option through an ambiguous simulated payment and verifies only an authoritative retry receipt',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});let n=0;const calls:RequestInit[]=[];vi.stubGlobal('fetch',optionTransport(undefined,async options=>{calls.push(options);if(++n===1)throw Error('PRIVATE-PAYMENT');return new Response(JSON.stringify({ok:true,data:{...paymentData,replayed:true}}));}));render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await fillOptionRequest('first');fireEvent.click(screen.getByText('Send unconfirmed request'));await screen.findByText('Request saved');fireEvent.click(screen.getByText('Reserve selected time'));fireEvent.click(await screen.findByText('Make staging test payment'));await screen.findByText('Retry the same test payment');expect(screen.getByText('Selected option (Choose a visit): First visit')).toBeTruthy();expect(screen.queryByText('Test booking confirmed')).toBeNull();fireEvent.click(screen.getByText('Retry the same test payment'));await screen.findByText('Test booking confirmed');expect(screen.getByText('Selected option (Choose a visit): First visit')).toBeTruthy();expect(calls).toHaveLength(2);expect(calls[1]!.body).toBe(calls[0]!.body);expect(calls[1]!.headers).toEqual(calls[0]!.headers);expect(document.body.textContent).not.toContain('PRIVATE-PAYMENT');
});

it('drops a late V4 saved request and its frozen option summary after installation change',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});let finish!:(response:Response)=>void;const second='22222222-2222-4222-8222-222222222222';const transport=optionTransport(()=>new Promise<Response>(r=>finish=r));vi.stubGlobal('fetch',transport);const {rerender}=render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await fillOptionRequest();fireEvent.click(screen.getByText('Send unconfirmed request'));await waitFor(()=>expect(finish).toBeTypeOf('function'));rerender(<HostedFlow installationId={second} apiUrl="https://api.example"/>);await screen.findByText('Paid housekeeping');finish(new Response(JSON.stringify({ok:true,data:{reference:bookingReference,state:'draft',confirmed:false}})));await waitFor(()=>expect(screen.queryByText('Request saved')).toBeNull());expect(screen.queryByText(/Selected option/)).toBeNull();expect(screen.queryByText(bookingReference)).toBeNull();expect(screen.getByLabelText('Choose a visit')).toHaveValue('');expect(screen.getByText('Send unconfirmed request')).toBeDisabled();
});

const fieldRender={versionId:id,renderSchemaVersion:5,submissionMode:'paid_customer_field_request',paymentMode:'staging_mock',simulated:true,service:paidRender.service,publication:{name:'Saved customer field form',draftRevision:2,presentation:{accentColor:'#0e7490',layout:'compact'}},customerFields:[{id:'custom_notes',kind:'text',label:'Notes',required:false,maxLength:4},{id:'custom_access',kind:'text',label:'Entry instructions',required:true,maxLength:20}]};
function fieldTransport(request:(options:RequestInit)=>Promise<Response>=async()=>new Response(JSON.stringify({ok:true,data:{reference:bookingReference,state:'draft',confirmed:false}})),payment:(options:RequestInit)=>Promise<Response>=async()=>new Response(JSON.stringify({ok:true,data:paymentData})),expiresAt='2035-01-01T00:00:00Z',renderValue:unknown=fieldRender){
 return vi.fn(async(url:string,options:RequestInit)=>{if(url.endsWith('/request'))return request(options);if(url.endsWith('/mock-payment'))return payment(options);if(url.endsWith('/hold'))return new Response(JSON.stringify({ok:true,data:{schemaVersion:1,bookingId:id,holdId:id,status:'active',expiresAt:'2030-01-01T10:05:00Z'}}));if(url.includes('/availability'))return availabilityResponse(url);if(url.includes('/sessions'))return new Response(JSON.stringify({ok:true,data:{sessionToken:token,expiresAt,render:renderValue}}));throw Error('Unexpected request');});
}
async function fillFieldRequest(access='Gate 12',notes?:string){
 await screen.findByRole('heading',{name:'Saved customer field form'});if(access!==undefined)fireEvent.change(screen.getByLabelText('Entry instructions'),{target:{value:access}});if(notes!==undefined)fireEvent.change(screen.getByLabelText('Notes (optional)'),{target:{value:notes}});
 fireEvent.change(screen.getByLabelText('Your name'),{target:{value:'Synthetic Person'}});fireEvent.change(screen.getByLabelText('Email'),{target:{value:'synthetic@example.test'}});fireEvent.change(screen.getByLabelText('Requested date'),{target:{value:'2030-01-01'}});await waitFor(()=>expect(screen.getByLabelText('Available time')).toBeEnabled());fireEvent.change(screen.getByLabelText('Available time'),{target:{value:slotStart}});
}
it('V5 acquires one explicit session and renders pinned accessible fields in order with native bounds',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});const transport=fieldTransport();vi.stubGlobal('fetch',transport);render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await screen.findByRole('heading',{name:'Saved customer field form'});
 const notes=screen.getByLabelText('Notes (optional)') as HTMLInputElement,access=screen.getByLabelText('Entry instructions') as HTMLInputElement;
 expect(notes).not.toBeRequired();expect(access).toBeRequired();expect(notes.maxLength).toBe(4);expect(access.maxLength).toBe(20);expect(notes.compareDocumentPosition(access)&Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy();expect(screen.getByLabelText('Email').compareDocumentPosition(notes)&Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy();
 expect(notes.type).toBe('text');expect(notes.autocomplete).toBe('off');expect(Number.parseFloat(access.style.minWidth)).toBe(0);expect(access.style.width).toBe('100%');expect(screen.getByRole('main').className).toContain('paid-form-layout-compact');expect(screen.getByRole('main').style.getPropertyValue('--accent')).toBe('#0e7490');expect(screen.getByText('Published service price: $125.00')).toBeTruthy();expect(transport.mock.calls.filter(([url])=>url.includes('/sessions'))).toHaveLength(1);
});
it.each(['', ' \u00a0 ', 'x'.repeat(21),'bad\u0085value','\ud800'])('V5 rejects missing/invalid required information without any request or financial calls %j',async value=>{
 vi.stubGlobal('location',{protocol:'https:'});const request=vi.fn(async()=>{throw Error('Unexpected write');}),transport=fieldTransport(request);vi.stubGlobal('fetch',transport);render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await fillFieldRequest(value);fireEvent.submit(screen.getByText('Send unconfirmed request').closest('form')!);await screen.findByText('Complete the required customer information using the published field limits.');expect(request).not.toHaveBeenCalled();expect(transport.mock.calls.filter(([url])=>url.endsWith('/hold')||url.endsWith('/mock-payment'))).toHaveLength(0);expect(screen.queryByText('Request saved')).toBeNull();
});
it('V5 applies UTF16 limits to optional information and permits valid pairs while preserving exact values',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});const bodies:string[]=[];vi.stubGlobal('fetch',fieldTransport(async options=>{bodies.push(options.body as string);return new Response(JSON.stringify({ok:true,data:{reference:bookingReference,state:'draft',confirmed:false}}));}));render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await fillFieldRequest(' Gate 12 ','😀😀a');fireEvent.submit(screen.getByText('Send unconfirmed request').closest('form')!);await screen.findByText('Complete the required customer information using the published field limits.');expect(bodies).toHaveLength(0);fireEvent.change(screen.getByLabelText('Notes (optional)'),{target:{value:'😀😀'}});fireEvent.click(screen.getByText('Send unconfirmed request'));await screen.findByText('Request saved');expect(JSON.parse(bodies[0]!)).toEqual({schemaVersion:2,idempotencyKey:expect.any(String),answers:{},customerAnswers:{custom_notes:'😀😀',custom_access:' Gate 12 '},customer:{name:'Synthetic Person',email:'synthetic@example.test'},requestedStart:slotStart});expect(Object.keys(JSON.parse(bodies[0]!).customerAnswers)).toEqual(['custom_notes','custom_access']);expect(document.body.textContent).not.toContain(' Gate 12 ');
});
it('V5 freezes private information/body/key through an unknown request and keeps hold/payment authority separate',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});const bodies:string[]=[];let paymentCalls=0;const transport=fieldTransport(async options=>{bodies.push(options.body as string);if(bodies.length===1)throw Error('PRIVATE-FIELD-ERROR');return new Response(JSON.stringify({ok:true,data:{reference:bookingReference,state:'draft',confirmed:false}}));},async()=>{paymentCalls++;return new Response(JSON.stringify({ok:true,data:paymentData}));});vi.stubGlobal('fetch',transport);render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await fillFieldRequest('Private entry');fireEvent.click(screen.getByText('Send unconfirmed request'));await screen.findByText('Retry the same request');expect(screen.getByLabelText('Entry instructions')).toBeDisabled();expect(screen.getByLabelText('Notes (optional)')).toBeDisabled();fireEvent.change(screen.getByLabelText('Entry instructions'),{target:{value:'Changed'}});fireEvent.change(screen.getByLabelText('Notes (optional)'),{target:{value:'New'}});fireEvent.click(screen.getByText('Retry the same request'));await screen.findByText('Request saved');expect(bodies[1]).toBe(bodies[0]);expect(JSON.parse(bodies[0]!).customerAnswers).toEqual({custom_access:'Private entry'});expect(JSON.parse(bodies[0]!).answers).toEqual({});expect(JSON.parse(bodies[0]!)).not.toHaveProperty('price');expect(paymentCalls).toBe(0);expect(screen.queryByText('Test booking confirmed')).toBeNull();expect(document.body.textContent).not.toContain('Private entry');expect(document.body.textContent).not.toContain('PRIVATE-FIELD-ERROR');
 fireEvent.click(screen.getByText('Reserve selected time'));fireEvent.click(await screen.findByText('Make staging test payment'));await screen.findByText('Test booking confirmed');expect(paymentCalls).toBe(1);expect(transport.mock.calls.filter(([url])=>url.includes('/sessions'))).toHaveLength(1);expect(transport.mock.calls.find(([url])=>url.endsWith('/hold'))?.[1].body).toBe('{}');expect(transport.mock.calls.find(([url])=>url.endsWith('/mock-payment'))?.[1].body).toBe('{}');expect(document.body.textContent).not.toContain(token);expect(document.body.textContent).not.toContain('Private entry');
});
it('V5 expires an unknown request without sending another request or granting reservation',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});const now=vi.spyOn(Date,'now').mockReturnValue(Date.parse('2029-12-01T00:00:00Z'));const request=vi.fn(async()=>{throw Error('Ambiguous request');}),transport=fieldTransport(request,undefined,'2029-12-01T00:10:00Z');vi.stubGlobal('fetch',transport);
 try{render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await fillFieldRequest();fireEvent.click(screen.getByText('Send unconfirmed request'));await screen.findByText('Retry the same request');now.mockReturnValue(Date.parse('2029-12-01T00:10:00Z'));fireEvent.submit(screen.getByText('Retry the same request').closest('form')!);await screen.findAllByText('Your session expired. Reload this page to start again.');expect(request).toHaveBeenCalledOnce();expect(screen.queryByText('Reserve selected time')).toBeNull();expect(screen.queryByText('Test booking confirmed')).toBeNull();}finally{now.mockRestore();}
});
it('V5 drops late private request results and fields when installation context changes',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});let finish!:(response:Response)=>void;const second='22222222-2222-4222-8222-222222222222',transport=fieldTransport(()=>new Promise<Response>(r=>finish=r));vi.stubGlobal('fetch',vi.fn(async(url:string,options:RequestInit)=>url.includes('/'+second+'/sessions')?new Response(JSON.stringify({ok:true,data:{sessionToken:token,expiresAt:'2035-01-01T00:00:00Z',render:paidRender}})):transport(url,options)));const {rerender}=render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await fillFieldRequest('Private entry');fireEvent.click(screen.getByText('Send unconfirmed request'));await waitFor(()=>expect(finish).toBeTypeOf('function'));rerender(<HostedFlow installationId={second} apiUrl="https://api.example"/>);await screen.findByText('Paid housekeeping');finish(new Response(JSON.stringify({ok:true,data:{reference:bookingReference,state:'draft',confirmed:false}})));await waitFor(()=>expect(screen.queryByText('Request saved')).toBeNull());expect(screen.queryByLabelText('Entry instructions')).toBeNull();expect(screen.queryByText(bookingReference)).toBeNull();expect(document.body.textContent).not.toContain('Private entry');expect(screen.getByText('Send unconfirmed request')).toBeDisabled();
});
it.each(['unknown version','unsupported kind','extra price','duplicate ID','unsafe label','unapproved design'])('V5 rejects %s without a legacy renderer or a second session acquisition',async kind=>{
 vi.stubGlobal('location',{protocol:'https:'});const f=fieldRender.customerFields[0]!;const invalid=kind==='unknown version'?{...fieldRender,renderSchemaVersion:6}:kind==='unapproved design'?{...fieldRender,publication:{...fieldRender.publication,presentation:{accentColor:'url(evil)',layout:'compact'}}}:{...fieldRender,customerFields:kind==='duplicate ID'?[f,f]:[{...f,...(kind==='unsupported kind'?{kind:'email'}:kind==='extra price'?{price:1}:{label:'bad\nlabel'})}]};const transport=fieldTransport(undefined,undefined,undefined,invalid);vi.stubGlobal('fetch',transport);render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await screen.findByRole('alert');expect(screen.queryByText('Send unconfirmed request')).toBeNull();expect(screen.queryByLabelText('Notes (optional)')).toBeNull();expect(transport).toHaveBeenCalledOnce();
});
it('V5 default client acquisition remains failclosed while Checkout opts in explicitly',async()=>{
 const transport=fieldTransport();const client=createFlowClient('https://api.example',false,transport as unknown as typeof fetch);await expect(client.session(id)).rejects.toMatchObject({code:'INTERNAL_ERROR'});expect(transport).toHaveBeenCalledOnce();
});

it('V5 moves keyboard focus to each verified receipt after explicit request and payment',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});const transport=fieldTransport();vi.stubGlobal('fetch',transport);render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await fillFieldRequest();
 const submit=screen.getByRole('button',{name:'Send unconfirmed request'});submit.focus();fireEvent.click(submit);const saved=await screen.findByRole('heading',{name:'Request saved'});expect(saved).toHaveFocus();expect(saved).toHaveAttribute('tabindex','-1');
 fireEvent.click(screen.getByRole('button',{name:'Reserve selected time'}));const pay=await screen.findByRole('button',{name:'Make staging test payment'});pay.focus();fireEvent.click(pay);const confirmed=await screen.findByRole('heading',{name:'Test booking confirmed'});expect(confirmed).toHaveFocus();expect(transport.mock.calls.filter(([url])=>url.endsWith('/request'))).toHaveLength(1);expect(transport.mock.calls.filter(([url])=>url.endsWith('/mock-payment'))).toHaveLength(1);
});
it('V5 pending or failed writes do not move focus to an unverified receipt',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});let rejectRequest!:(error:Error)=>void;const request=vi.fn(()=>new Promise<Response>((_resolve,reject)=>rejectRequest=reject)),transport=fieldTransport(request);vi.stubGlobal('fetch',transport);render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await fillFieldRequest();
 const heading=screen.getByRole('heading',{name:'Saved customer field form'}),submit=screen.getByRole('button',{name:'Send unconfirmed request'});submit.focus();fireEvent.click(submit);await waitFor(()=>expect(request).toHaveBeenCalledOnce());expect(screen.queryByRole('heading',{name:'Request saved'})).toBeNull();expect(heading).not.toHaveFocus();rejectRequest(Error('Unknown delivery'));await screen.findByRole('button',{name:'Retry the same request'});expect(screen.queryByRole('heading',{name:'Request saved'})).toBeNull();expect(heading).not.toHaveFocus();expect(screen.queryByRole('heading',{name:'Test booking confirmed'})).toBeNull();
});

it('V5 payment loading and failure do not focus or announce a confirmed receipt',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});let rejectPayment!:(error:Error)=>void;const payment=vi.fn(()=>new Promise<Response>((_resolve,reject)=>rejectPayment=reject)),transport=fieldTransport(undefined,payment);vi.stubGlobal('fetch',transport);render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await fillFieldRequest();fireEvent.click(screen.getByRole('button',{name:'Send unconfirmed request'}));const saved=await screen.findByRole('heading',{name:'Request saved'});expect(saved).toHaveFocus();fireEvent.click(screen.getByRole('button',{name:'Reserve selected time'}));const pay=await screen.findByRole('button',{name:'Make staging test payment'});pay.focus();fireEvent.click(pay);await waitFor(()=>expect(payment).toHaveBeenCalledOnce());expect(saved).not.toHaveFocus();expect(screen.queryByRole('heading',{name:'Test booking confirmed'})).toBeNull();rejectPayment(Error('Unknown payment delivery'));await screen.findByRole('button',{name:'Retry the same test payment'});expect(saved).not.toHaveFocus();expect(screen.queryByRole('heading',{name:'Test booking confirmed'})).toBeNull();expect(payment).toHaveBeenCalledOnce();
});
