import {render,screen,fireEvent,waitFor,cleanup} from '@testing-library/react';
import {it,expect,vi,afterEach} from 'vitest';
import {HostedDetailingFlow} from './HostedDetailingFlow';
const id='11111111-1111-4111-8111-111111111111',token='t'.repeat(43),expiresAt='2035-01-01T00:00:00Z';
const catalog={name:'Detailing',description:'Published description',currency:'USD',durationMinutes:30,packages:[{id:'basic',label:'Basic',amount:1000},{id:'deep',label:'Deep',amount:2000}],vehicles:[{id:'car',label:'Car',multiplierBp:10000}],addons:[{id:'wax',name:'Wax',amount:500}],locations:[{id:'shop',label:'Shop',amount:0}]};
const detailingRender={versionId:id,renderSchemaVersion:7,businessType:'AUTO_DETAILING',submissionMode:'detailing_quote',bookingMode:'unavailable',paymentMode:'unavailable',pricingModel:'package_subtotal_vehicle_multiplier',serviceId:id,catalog,publication:{name:'Published detailing',presentation:{accentColor:'#4f46e5',layout:'stacked'},draftRevision:1}};
const money=(amount:number)=>({amount,currency:'USD'});const json=(data:unknown)=>new Response(JSON.stringify({ok:true,data}));
const quote=(selection:unknown)=>({schemaVersion:1,versionId:id,installationId:id,serviceId:id,expiresAt,selection,pricingModel:'package_subtotal_vehicle_multiplier',bookingMode:'unavailable',paymentMode:'unavailable',pricing:{lines:[{code:'server',label:'Server-priced selection',quantity:1,amount:money(7777)}],subtotal:money(7777),tax:money(0),deposit:money(0),total:money(7777)}});
const start='2030-01-01T10:00:00.000Z';const availability={schemaVersion:1,versionId:id,installationId:id,serviceId:id,expiresAt,durationMinutes:30,timezone:'America/Los_Angeles',slots:[{start,end:'2030-01-01T10:30:00.000Z',remainingCapacity:1}]};
afterEach(()=>{cleanup();vi.unstubAllGlobals();vi.restoreAllMocks();vi.useRealTimers();});
async function open(fetcher:ReturnType<typeof vi.fn>){vi.stubGlobal('location',{protocol:'https:'});vi.stubGlobal('fetch',fetcher);render(<HostedDetailingFlow installationId={id} apiUrl="https://api.example"/>);await screen.findByText('Published detailing');fireEvent.change(screen.getByLabelText('Detail package'),{target:{value:'basic'}});fireEvent.change(screen.getByLabelText('Vehicle type'),{target:{value:'car'}});fireEvent.change(screen.getByLabelText('Service location'),{target:{value:'shop'}});fireEvent.click(screen.getByLabelText('Wax'));}
it('connects choices, shows only server financial truth and never claims a booking',async()=>{const fetcher=vi.fn(async(url:string,options:RequestInit)=>url.includes('/quote')?json(quote(JSON.parse(String(options.body)))):url.includes('/availability')?json(availability):json({sessionToken:token,expiresAt,render:detailingRender}));await open(fetcher);fireEvent.click(screen.getByText('Get server quote'));await screen.findByText('$77.77');expect(JSON.parse(String(fetcher.mock.calls[1]![1].body))).toEqual({packageId:'basic',vehicleId:'car',addonIds:['wax'],locationId:'shop'});fireEvent.change(screen.getByLabelText('Availability date (UTC)'),{target:{value:'2030-01-01'}});await screen.findByLabelText('Available time');fireEvent.change(screen.getByLabelText('Available time'),{target:{value:start}});expect(screen.getByText(/No booking has been created/)).toBeTruthy();expect(document.body.textContent).not.toContain(token);expect(fetcher.mock.calls.every(([u])=>!u.includes('/request')&&!u.includes('/hold')&&!u.includes('/payment'))).toBe(true);fireEvent.change(screen.getByLabelText('Detail package'),{target:{value:'deep'}});expect(screen.queryByText('$77.77')).toBeNull();expect(screen.queryByLabelText('Available time')).toBeNull();expect(screen.queryByText(/No booking has been created/)).toBeNull();});
it.each(['success','error'])('ignores late quote %s after a choice changes',async mode=>{let finish!:(r:Response)=>void;const fetcher=vi.fn(async(url:string)=>url.includes('/quote')?new Promise<Response>(resolve=>finish=resolve):json({sessionToken:token,expiresAt,render:detailingRender}));await open(fetcher);fireEvent.click(screen.getByText('Get server quote'));await waitFor(()=>expect(finish).toBeTypeOf('function'));fireEvent.change(screen.getByLabelText('Detail package'),{target:{value:'deep'}});finish(mode==='success'?json(quote({packageId:'basic',vehicleId:'car',addonIds:['wax'],locationId:'shop'})):new Response(JSON.stringify({ok:false,code:'FORBIDDEN'}),{status:403}));await waitFor(()=>expect(screen.getByText('Get server quote')).toBeEnabled());expect(screen.queryByRole('alert')).toBeNull();expect(screen.queryByText('$77.77')).toBeNull();});
it('ignores late availability after date changes and renders empty availability truthfully',async()=>{let finish!:(r:Response)=>void;let reads=0;const fetcher=vi.fn(async(url:string,options:RequestInit)=>url.includes('/quote')?json(quote(JSON.parse(String(options.body)))):url.includes('/availability')?(++reads===1?new Promise<Response>(resolve=>finish=resolve):json({...availability,slots:[]})):json({sessionToken:token,expiresAt,render:detailingRender}));await open(fetcher);fireEvent.click(screen.getByText('Get server quote'));await screen.findByText('$77.77');fireEvent.change(screen.getByLabelText('Availability date (UTC)'),{target:{value:'2030-01-01'}});await waitFor(()=>expect(finish).toBeTypeOf('function'));fireEvent.change(screen.getByLabelText('Availability date (UTC)'),{target:{value:'2030-01-02'}});await screen.findByText('No available times in this date range.');finish(json(availability));await waitFor(()=>expect(screen.queryByLabelText('Available time')).toBeNull());});
it('rejects HTTP customer pages without fetching',()=>{vi.stubGlobal('location',{protocol:'http:'});const fetcher=vi.fn();vi.stubGlobal('fetch',fetcher);render(<HostedDetailingFlow installationId={id} apiUrl="https://api.example"/>);expect(screen.getByText('Secure customer page required')).toBeTruthy();expect(fetcher).not.toHaveBeenCalled();});
it('removes expired financial and availability receipts with a truthful renewal message',async()=>{const fetcher=vi.fn(async(url:string,options:RequestInit)=>url.includes('/quote')?json({...quote(JSON.parse(String(options.body))),expiresAt:new Date(Date.now()+200).toISOString()}):json({sessionToken:token,expiresAt,render:detailingRender}));await open(fetcher);fireEvent.click(screen.getByText('Get server quote'));await screen.findByText('$77.77');await screen.findByText('This quote or availability expired. Request a fresh quote and choose a date again.');expect(screen.queryByText('$77.77')).toBeNull();expect(screen.queryByLabelText('Availability date (UTC)')).toBeNull();});
let requestNumber=100;
async function requestUI(mode:'normal'|'request_unknown'|'hold_unknown'|'price_mismatch'|'forbidden'|'expiry'|'pending'|'hold_pending'|'pay_normal'|'pay_unknown'|'pay_forged'|'readiness_forbidden'|'pay_pending'|'pay_uncommitted'='normal',timezone=availability.timezone){
 const installation='98000000-0000-4000-8000-'+String(++requestNumber).padStart(12,'0'),booking='98000000-0000-4000-8000-'+String(++requestNumber).padStart(12,'0');let reads=0,payments=0,confirms=0,committed=false;let requests=0,holds=0,finish!:(r:Response)=>void;
 const requestReceipt=(body:{selection:unknown})=>({schemaVersion:1,versionId:id,installationId:installation,serviceId:id,bookingId:booking,reference:'LMN-'+booking.replaceAll('-','').toUpperCase(),selection:body.selection,pricing:quote(body.selection).pricing,slot:{start,end:availability.slots[0]!.end},state:'draft',confirmed:false,paymentMode:'unavailable'});
 const holdReceipt=()=>({schemaVersion:1,versionId:id,installationId:installation,serviceId:id,bookingId:booking,holdId:id,status:'active',expiresAt:mode==='expiry'?new Date(Date.now()+200).toISOString():'2030-01-01T09:59:00.000Z'});
 const paymentBase={schemaVersion:1,versionId:id,installationId:installation,serviceId:id,bookingId:booking,provider:'staging_mock',simulated:true};
 const paymentReceipt=()=>({...paymentBase,paymentId:id,state:'confirmed',replayed:false});
 const fetcher=vi.fn(async(url:string,options:RequestInit)=>{if(url.endsWith('/payment-readiness')){reads++;if(mode==='readiness_forbidden')return new Response(JSON.stringify({ok:false,code:'FORBIDDEN'}),{status:403});return json({...paymentBase,state:committed?'confirmed':'draft',canPay:!committed,canConfirm:committed});}if(url.endsWith('/mock-payment')){payments++;if(mode==='pay_uncommitted'&&payments===1)throw Error('private lost before commit');committed=true;if(mode==='pay_unknown')throw Error('private lost payment');if(mode==='pay_pending')return new Promise<Response>(resolve=>finish=resolve);return json(mode==='pay_forged'?{...paymentReceipt(),bookingId:id}:paymentReceipt());}if(url.endsWith('/confirm')){confirms++;return json({...paymentReceipt(),replayed:true});}const body=options.body?JSON.parse(String(options.body)):undefined;if(url.endsWith('/request')){requests++;if(mode==='pending')return new Promise<Response>(resolve=>finish=resolve);if(mode==='request_unknown'&&requests===1)throw Error('private lost request');if(mode==='forbidden')return new Response(JSON.stringify({ok:false,code:'FORBIDDEN'}),{status:403});const data=requestReceipt(body);return json(mode==='price_mismatch'?{...data,pricing:{...data.pricing,lines:[{code:'server',label:'Substituted',quantity:1,amount:money(1000)}],subtotal:money(1000),total:money(1000)}}:data);}if(url.endsWith('/hold')){holds++;if(mode==='hold_pending')return new Promise<Response>(resolve=>finish=resolve);if(mode==='hold_unknown'&&holds===1)throw Error('private lost hold');return json(holdReceipt());}if(url.includes('/quote'))return json({...quote(body),installationId:installation});if(url.includes('/availability'))return json({...availability,installationId:installation,timezone});return json({sessionToken:token,expiresAt,render:detailingRender});});
 vi.stubGlobal('location',{protocol:'https:'});vi.stubGlobal('fetch',fetcher);const view=render(<HostedDetailingFlow installationId={installation} apiUrl="https://api.example"/>);await screen.findByText('Published detailing');fireEvent.change(screen.getByLabelText('Detail package'),{target:{value:'basic'}});fireEvent.change(screen.getByLabelText('Vehicle type'),{target:{value:'car'}});fireEvent.change(screen.getByLabelText('Service location'),{target:{value:'shop'}});fireEvent.click(screen.getByLabelText('Wax'));fireEvent.click(screen.getByText('Get server quote'));await screen.findByText('$77.77');fireEvent.change(screen.getByLabelText('Availability date (UTC)'),{target:{value:'2030-01-01'}});await screen.findByLabelText('Available time');fireEvent.change(screen.getByLabelText('Available time'),{target:{value:start}});fireEvent.change(screen.getByLabelText('Your name'),{target:{value:'Fictional customer'}});fireEvent.change(screen.getByLabelText('Email'),{target:{value:'fictional@example.test'}});fireEvent.click(screen.getByText('Review request'));await screen.findByText('Review your request');return{fetcher,view,installation,requestReceipt,holdReceipt,paymentReceipt,financialCounts:()=>({reads,payments,confirms}),finish:(body:unknown)=>finish(json(body)),counts:()=>({requests,holds})};
}
it('requires explicit review and submission before a separate exact temporary reservation, without automatically starting payment',async()=>{const x=await requestUI();expect(x.counts()).toEqual({requests:0,holds:0});fireEvent.click(screen.getByText('Send unconfirmed request'));await screen.findByText('Request saved, unconfirmed');expect(x.counts()).toEqual({requests:1,holds:0});expect(screen.getByText(/A saved request remains unconfirmed/)).toBeTruthy();fireEvent.click(screen.getByText('Reserve requested time'));await screen.findByText(/Time temporarily reserved until/);expect(x.counts()).toEqual({requests:1,holds:1});fireEvent.click(screen.getByText('Verify the same reservation'));await screen.findByText(/Time temporarily reserved until/);await waitFor(()=>expect(x.counts().holds).toBe(2));const writes=x.fetcher.mock.calls.filter(([u])=>u.endsWith('/request')||u.endsWith('/hold'));expect(JSON.parse(String(writes[0]![1].body))).toMatchObject({schemaVersion:1,customer:{name:'Fictional customer',email:'fictional@example.test'},requestedStart:start,selection:{packageId:'basic',vehicleId:'car',addonIds:['wax'],locationId:'shop'}});expect(JSON.parse(String(writes[0]![1].body))).not.toHaveProperty('pricing');expect(document.body.textContent).not.toContain(token);expect(x.fetcher.mock.calls.every(([u])=>!u.includes('/payment')&&!u.includes('/confirm'))).toBe(true);});
it('freezes an unknown request and retries only the identical body/key on an explicit click',async()=>{const x=await requestUI('request_unknown');fireEvent.click(screen.getByText('Send unconfirmed request'));await screen.findByText('Request status unverified');expect(screen.getByLabelText('Detail package')).toBeDisabled();expect(screen.getByLabelText('Your name')).toBeDisabled();expect(screen.queryByText('Reserve requested time')).toBeNull();expect(x.counts().requests).toBe(1);fireEvent.click(screen.getByText('Retry the same request'));await screen.findByText('Request saved, unconfirmed');const writes=x.fetcher.mock.calls.filter(([u])=>u.endsWith('/request'));expect(writes[0]![1].body).toBe(writes[1]![1].body);});
it('renders unknown hold status truthfully and reconciles only the same persisted reservation',async()=>{const x=await requestUI('hold_unknown');fireEvent.click(screen.getByText('Send unconfirmed request'));await screen.findByText('Request saved, unconfirmed');fireEvent.click(screen.getByText('Reserve requested time'));await screen.findByText(/Reservation status is unverified/);expect(screen.queryByText(/Time temporarily reserved until/)).toBeNull();expect(x.counts()).toEqual({requests:1,holds:1});fireEvent.click(screen.getByText('Retry the same reservation'));await screen.findByText(/Time temporarily reserved until/);expect(x.counts()).toEqual({requests:1,holds:2});});
it('never displays substituted financial truth or enables hold after an unverified request receipt',async()=>{const x=await requestUI('price_mismatch');fireEvent.click(screen.getByText('Send unconfirmed request'));await screen.findByText('Request status unverified');expect(screen.queryByText('Request saved, unconfirmed')).toBeNull();expect(screen.queryByText('$10.00')).toBeNull();expect(x.counts().holds).toBe(0);});
it('a definite forbidden request does not display saved or active status',async()=>{const x=await requestUI('forbidden');fireEvent.click(screen.getByText('Send unconfirmed request'));await screen.findByRole('alert');expect(screen.queryByText('Request saved, unconfirmed')).toBeNull();expect(screen.getByLabelText('Detail package')).toBeEnabled();expect(x.counts()).toEqual({requests:1,holds:0});});
it('expires a hold without silently renewing it or claiming confirmation',async()=>{const x=await requestUI('expiry');fireEvent.click(screen.getByText('Send unconfirmed request'));await screen.findByText('Request saved, unconfirmed');fireEvent.click(screen.getByText('Reserve requested time'));await screen.findByText(/Time temporarily reserved until/);await screen.findByText('The temporary reservation expired. Your request remains saved and unconfirmed.');expect(screen.queryByText('Verify the same reservation')).toBeNull();expect(x.counts().holds).toBe(1);});
it('prevents repeated submit clicks and hides old receipt after an installation changes',async()=>{const x=await requestUI('pending');fireEvent.click(screen.getByText('Send unconfirmed request'));expect(screen.queryByText('Send unconfirmed request')).toBeNull();expect(screen.getByLabelText('Detail package')).toBeDisabled();expect(x.counts().requests).toBe(1);const requestCall=x.fetcher.mock.calls.find(([u])=>u.endsWith('/request'))!;x.view.rerender(<HostedDetailingFlow installationId="97000000-0000-4000-8000-000000000001" apiUrl="https://api.example"/>);await screen.findByText('Published detailing');x.finish(x.requestReceipt(JSON.parse(String(requestCall[1].body))));await waitFor(()=>expect(screen.queryByText('Request saved, unconfirmed')).toBeNull());expect(x.counts().requests).toBe(1);});
it('observes a pending request after remount without sending another write and offers exact replay',async()=>{const x=await requestUI('pending');fireEvent.click(screen.getByText('Send unconfirmed request'));const requestCall=x.fetcher.mock.calls.find(([u])=>u.endsWith('/request'))!;x.view.unmount();render(<HostedDetailingFlow installationId={x.installation} apiUrl="https://api.example"/>);await screen.findByText('Sending your exact request…');x.finish(x.requestReceipt(JSON.parse(String(requestCall[1].body))));await screen.findByText('Retry the same request');expect(screen.getByLabelText('Detail package')).toBeDisabled();expect(screen.queryByText('Request saved, unconfirmed')).toBeNull();expect(x.counts()).toEqual({requests:1,holds:0});});
it('observes a pending hold after remount and exposes only explicit same-hold recovery',async()=>{const x=await requestUI('hold_pending');fireEvent.click(screen.getByText('Send unconfirmed request'));await screen.findByText('Request saved, unconfirmed');fireEvent.click(screen.getByText('Reserve requested time'));expect(x.counts()).toEqual({requests:1,holds:1});x.view.unmount();render(<HostedDetailingFlow installationId={x.installation} apiUrl="https://api.example"/>);await screen.findByText('Checking reservation…');expect(screen.getByText('Checking reservation…')).toBeDisabled();x.finish(x.holdReceipt());await screen.findByText('Retry the same reservation');expect(screen.getByText(/Reservation status is unverified/)).toBeTruthy();expect(screen.queryByText(/Time temporarily reserved until/)).toBeNull();expect(x.counts()).toEqual({requests:1,holds:1});});

async function readyForPayment(mode:Parameters<typeof requestUI>[0]){
 const x=await requestUI(mode);fireEvent.click(screen.getByText('Send unconfirmed request'));await screen.findByText('Request saved, unconfirmed');fireEvent.click(screen.getByText('Reserve requested time'));await screen.findByText(/Time temporarily reserved until/);expect(x.financialCounts()).toEqual({reads:0,payments:0,confirms:0});return x;
}
it('requires explicit readiness and payment clicks and displays only a verified test confirmation',async()=>{
 const x=await readyForPayment('pay_normal');fireEvent.click(screen.getByText('Check test payment availability'));await screen.findByText('Complete test payment');expect(x.financialCounts()).toEqual({reads:1,payments:0,confirms:0});fireEvent.click(screen.getByText('Complete test payment'));await screen.findByText('Booking confirmed (test)');expect(x.financialCounts()).toEqual({reads:1,payments:1,confirms:0});expect(screen.getByText('STAGING TEST — no money charged.')).toBeTruthy();expect(screen.queryByText(/Time temporarily reserved until/)).toBeNull();expect(screen.queryByText('Request saved, unconfirmed')).toBeNull();expect(document.body.textContent).not.toContain(token);const call=x.fetcher.mock.calls.find(([u])=>u.endsWith('/mock-payment'))!;expect(call[1].method).toBe('POST');expect(JSON.parse(String(call[1].body))).toEqual({});
});
it('keeps a lost committed payment unverified until explicit same-booking confirmation recovery',async()=>{
 const x=await readyForPayment('pay_unknown');fireEvent.click(screen.getByText('Check test payment availability'));await screen.findByText('Complete test payment');fireEvent.click(screen.getByText('Complete test payment'));await screen.findByText('Check test payment status');expect(screen.queryByText('Booking confirmed (test)')).toBeNull();expect(screen.queryByText(/Time temporarily reserved until/)).toBeNull();fireEvent.click(screen.getByText('Check test payment status'));await screen.findByText('Verify the same test confirmation');expect(screen.queryByText('Booking confirmed (test)')).toBeNull();expect(x.financialCounts()).toEqual({reads:2,payments:1,confirms:0});fireEvent.click(screen.getByText('Verify the same test confirmation'));await screen.findByText('Booking confirmed (test)');expect(x.financialCounts()).toEqual({reads:2,payments:1,confirms:1});expect(JSON.parse(String(x.fetcher.mock.calls.find(([u])=>u.endsWith('/confirm'))![1].body))).toEqual({});
});
it('does not offer payment after denied readiness',async()=>{
 const x=await readyForPayment('readiness_forbidden');fireEvent.click(screen.getByText('Check test payment availability'));await waitFor(()=>expect(x.financialCounts().reads).toBe(1));await screen.findByRole('alert');expect(screen.queryByText('Complete test payment')).toBeNull();expect(x.financialCounts().payments).toBe(0);expect(screen.queryByText('Booking confirmed (test)')).toBeNull();
});
it('rejects a payment receipt belonging to another booking',async()=>{
 const x=await readyForPayment('pay_forged');fireEvent.click(screen.getByText('Check test payment availability'));await screen.findByText('Complete test payment');fireEvent.click(screen.getByText('Complete test payment'));await screen.findByText('Check test payment status');expect(screen.queryByText('Booking confirmed (test)')).toBeNull();expect(screen.queryByLabelText('Detail package')).toBeNull();expect(x.financialCounts().payments).toBe(1);fireEvent.click(screen.getByText('Check test payment status'));await screen.findByText('Verify the same test confirmation');fireEvent.click(screen.getByText('Verify the same test confirmation'));await screen.findByText('Booking confirmed (test)');
});
it('does not submit twice or accept a late payment after remount',async()=>{
 const x=await readyForPayment('pay_pending');fireEvent.click(screen.getByText('Check test payment availability'));await screen.findByText('Complete test payment');fireEvent.click(screen.getByText('Complete test payment'));expect(screen.getByText('Complete test payment')).toBeDisabled();fireEvent.click(screen.getByText('Complete test payment'));expect(x.financialCounts().payments).toBe(1);x.view.unmount();render(<HostedDetailingFlow installationId={x.installation} apiUrl="https://api.example"/>);await screen.findByText('Completing the staging test payment. Booking confirmation has not yet been verified.');x.finish(x.paymentReceipt());await screen.findByText('Check test payment status');expect(screen.queryByText('Booking confirmed (test)')).toBeNull();expect(x.financialCounts()).toEqual({reads:1,payments:1,confirms:0});fireEvent.click(screen.getByText('Check test payment status'));await screen.findByText('Verify the same test confirmation');fireEvent.click(screen.getByText('Verify the same test confirmation'));await screen.findByText('Booking confirmed (test)');
});

it('recovers a lost-before-commit payment after remount by verifying only the original hold',async()=>{
 const x=await readyForPayment('pay_uncommitted');fireEvent.click(screen.getByText('Check test payment availability'));await screen.findByText('Complete test payment');fireEvent.click(screen.getByText('Complete test payment'));await screen.findByText('Check test payment status');x.view.unmount();render(<HostedDetailingFlow installationId={x.installation} apiUrl="https://api.example"/>);await screen.findByText('Check test payment status');fireEvent.click(screen.getByText('Check test payment status'));await screen.findByText('Verify the same reservation before retry');expect(screen.queryByText('Retry the same test payment')).toBeNull();expect(x.counts()).toEqual({requests:1,holds:1});fireEvent.click(screen.getByText('Verify the same reservation before retry'));await waitFor(()=>expect(x.counts().holds).toBe(2));await waitFor(()=>expect(screen.queryByText('Verify the same reservation before retry')).toBeNull());expect(screen.queryByText('Retry the same test payment')).toBeNull();fireEvent.click(screen.getByText('Check test payment status'));await screen.findByText('Retry the same test payment');expect(x.financialCounts().payments).toBe(1);fireEvent.click(screen.getByText('Retry the same test payment'));await screen.findByText('Booking confirmed (test)');expect(x.counts()).toEqual({requests:1,holds:2});expect(x.financialCounts()).toEqual({reads:3,payments:2,confirms:0});const holds=x.fetcher.mock.calls.filter(([u])=>u.endsWith('/hold'));expect(holds[0]![1].body).toBe(holds[1]![1].body);expect(JSON.parse(String(holds[1]![1].body))).toEqual({});
});

function browserInLosAngeles() {
 const NativeFormatter=Intl.DateTimeFormat;
 vi.spyOn(Intl,'DateTimeFormat').mockImplementation(function(_locales,options){return new NativeFormatter('en-US',{...options,timeZone:options?.timeZone??'America/Los_Angeles'});});
 vi.spyOn(Date.prototype,'toLocaleString').mockImplementation(function(this:Date){return new NativeFormatter('en-US',{dateStyle:'medium',timeStyle:'short',timeZone:'America/Los_Angeles'}).format(this);});
 expect(new Intl.DateTimeFormat().resolvedOptions().timeZone).toBe('America/Los_Angeles');
 expect(new Date(start).toLocaleString()).toBe('Jan 1, 2030, 2:00 AM');
}

it.each([
 ['UTC','Jan 1, 2030, 10:00 AM'],
 ['Asia/Tokyo','Jan 1, 2030, 7:00 PM'],
])('keeps %s slot, reviewed, and saved times consistent when the browser uses Los Angeles',async(timezone,label)=>{
 browserInLosAngeles();
 const x=await requestUI('normal',timezone);
 expect(screen.getByText('Times shown in '+timezone+'.')).toBeVisible();
 expect(screen.getByRole('option',{name:label})).toBeInTheDocument();
 expect(screen.getByText('Requested time: '+label+' ('+timezone+').')).toBeVisible();
 fireEvent.click(screen.getByText('Send unconfirmed request'));
 await screen.findByText('Request saved, unconfirmed');
 expect(screen.getByText('Requested time: '+label+' ('+timezone+').')).toBeVisible();
 const write=x.fetcher.mock.calls.find(([url])=>url.endsWith('/request'))!;
 expect(JSON.parse(String(write[1].body)).requestedStart).toBe(start);
 expect(x.counts()).toEqual({requests:1,holds:0});
});

it('keeps the verified server zone while a request is unknown and uses explicitly labelled UTC after remount',async()=>{
 browserInLosAngeles();
 const x=await requestUI('request_unknown','Asia/Tokyo');
 fireEvent.click(screen.getByText('Send unconfirmed request'));
 await screen.findByText('Request status unverified');
 expect(screen.getByText('Requested time: Jan 1, 2030, 7:00 PM (Asia/Tokyo).')).toBeVisible();
 x.view.unmount();
 render(<HostedDetailingFlow installationId={x.installation} apiUrl="https://api.example"/>);
 await screen.findByText('Request status unverified');
 expect(screen.getByText('Requested time: Jan 1, 2030, 10:00 AM (UTC).')).toBeVisible();
 expect(screen.queryByText(/Times shown in Asia\/Tokyo/)).toBeNull();
 expect(x.counts()).toEqual({requests:1,holds:0});
 fireEvent.click(screen.getByText('Retry the same request'));
 await screen.findByText('Request saved, unconfirmed');
 expect(screen.getByText('Requested time: Jan 1, 2030, 10:00 AM (UTC).')).toBeVisible();
 const writes=x.fetcher.mock.calls.filter(([url])=>url.endsWith('/request'));
 expect(writes[0]![1].body).toBe(writes[1]![1].body);
});

it('labels a restored saved request in UTC when the public operation has no availability context',async()=>{
 browserInLosAngeles();
 const x=await requestUI('normal','Asia/Tokyo');
 fireEvent.click(screen.getByText('Send unconfirmed request'));
 await screen.findByText('Request saved, unconfirmed');
 expect(screen.getByText('Requested time: Jan 1, 2030, 7:00 PM (Asia/Tokyo).')).toBeVisible();
 x.view.unmount();
 render(<HostedDetailingFlow installationId={x.installation} apiUrl="https://api.example"/>);
 await screen.findByText('Request saved, unconfirmed');
 expect(screen.getByText('Requested time: Jan 1, 2030, 10:00 AM (UTC).')).toBeVisible();
 expect(x.counts()).toEqual({requests:1,holds:0});
});
