import {render,screen,fireEvent,waitFor,cleanup} from '@testing-library/react';
import {afterEach,it,expect,vi} from 'vitest';
import {HostedFlow} from './HostedFlow';
const id='11111111-1111-4111-8111-111111111111',token='c'.repeat(43),reference='LMN-'+id.replaceAll('-','').toUpperCase();
const pinned={versionId:id,renderSchemaVersion:6,submissionMode:'paid_conditional_customer_field_request',paymentMode:'staging_mock',simulated:true,service:{id,name:'Cleaning',durationMinutes:30,price:{amount:12500,currency:'USD'}},publication:{name:'Conditional cleaning',draftRevision:3,presentation:{accentColor:'#0e7490',layout:'compact'}},customerFields:[{id:'custom_access',kind:'text',label:'Access method',required:true,maxLength:20},{id:'custom_gate',kind:'text',label:'Gate code',required:true,maxLength:10,when:{fieldId:'custom_access',equals:'gate'}}]};
const slot=new Date('2030-01-01T10:00').toISOString();
const envelope=(data:unknown)=>new Response(JSON.stringify({ok:true,data}));
afterEach(()=>{cleanup();vi.unstubAllGlobals();});
function fixture(lose=false){const requests:string[]=[],writes:string[]=[];const fetcher=vi.fn(async(url:string,options:RequestInit)=>{if(url.includes('/sessions'))return envelope({sessionToken:token,expiresAt:'2035-01-01T00:00:00Z',render:pinned});if(url.includes('/availability'))return envelope({schemaVersion:1,serviceId:id,durationMinutes:30,slots:[{start:slot,end:new Date(Date.parse(slot)+1800000).toISOString(),remainingCapacity:1}]});writes.push(url);if(url.endsWith('/request')){requests.push(String(options.body));if(lose){lose=false;throw Error('Lost response');}return envelope({reference,state:'draft',confirmed:false});}if(url.endsWith('/hold'))return envelope({schemaVersion:1,bookingId:id,holdId:id,status:'active',expiresAt:'2030-01-01T10:05:00Z'});if(url.endsWith('/mock-payment'))return envelope({schemaVersion:1,bookingId:id,paymentId:id,state:'confirmed',replayed:false,provider:'staging_mock',simulated:true});throw Error('Unexpected request');});vi.stubGlobal('location',{protocol:'https:'});vi.stubGlobal('fetch',fetcher);render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);return{requests,writes,fetcher};}
async function fill(){await screen.findByText('Conditional cleaning');fireEvent.change(screen.getByLabelText('Your name'),{target:{value:'Controlled customer'}});fireEvent.change(screen.getByLabelText('Email'),{target:{value:'controlled@example.test'}});fireEvent.change(screen.getByLabelText('Requested date'),{target:{value:'2030-01-01'}});await waitFor(()=>expect(screen.getByLabelText('Available time')).toBeEnabled());fireEvent.change(screen.getByLabelText('Available time'),{target:{value:slot}});}
it('requires newly visible answers, clears hidden values, and completes only explicit request/hold/test payment',async()=>{const {requests,writes}=fixture();await fill();expect(screen.queryByLabelText('Gate code')).toBeNull();fireEvent.change(screen.getByLabelText('Access method'),{target:{value:'gate'}});expect(screen.getByLabelText('Gate code')).toBeRequired();fireEvent.submit(screen.getByText('Send unconfirmed request').closest('form')!);await screen.findByText('Complete the required customer information using the published field limits.');expect(writes).toHaveLength(0);fireEvent.change(screen.getByLabelText('Gate code'),{target:{value:'PRIVATE123'}});fireEvent.change(screen.getByLabelText('Access method'),{target:{value:'key'}});expect(screen.queryByLabelText('Gate code')).toBeNull();fireEvent.click(screen.getByText('Send unconfirmed request'));await screen.findByText('Request saved');expect(JSON.parse(requests[0]!)).toEqual({schemaVersion:3,idempotencyKey:expect.any(String),answers:{},customerAnswers:{custom_access:'key'},customer:{name:'Controlled customer',email:'controlled@example.test'},requestedStart:slot});expect(document.body.textContent).not.toContain('PRIVATE123');expect(writes).toHaveLength(1);fireEvent.click(screen.getByText('Reserve selected time'));await screen.findByText('Make staging test payment');expect(writes).toHaveLength(2);fireEvent.click(screen.getByText('Make staging test payment'));await screen.findByRole('heading',{name:'Test booking confirmed'});expect(writes).toHaveLength(3);expect(screen.getByRole('heading',{name:'Test booking confirmed'})).toHaveFocus();expect(document.body.textContent).not.toContain(token);});
it('freezes conditional answers on ambiguous delivery and retries the identical canonical schema3 body',async()=>{const {requests,writes}=fixture(true);await fill();fireEvent.change(screen.getByLabelText('Access method'),{target:{value:'gate'}});fireEvent.change(screen.getByLabelText('Gate code'),{target:{value:'123'}});fireEvent.click(screen.getByText('Send unconfirmed request'));await screen.findByText('Retry the same request');expect(screen.getByLabelText('Access method')).toBeDisabled();expect(screen.getByLabelText('Gate code')).toBeDisabled();fireEvent.click(screen.getByText('Retry the same request'));await screen.findByText('Request saved');expect(requests).toHaveLength(2);expect(requests[0]).toBe(requests[1]);expect(JSON.parse(requests[0]!).customerAnswers).toEqual({custom_access:'gate',custom_gate:'123'});expect(writes.every(url=>url.endsWith('/request'))).toBe(true);});
