import {act,cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {afterEach,expect,it,vi} from 'vitest';
import {HostedJourneyFlow} from './HostedJourneyFlow';
import type {PublicRuntimeConfig} from '@lumin/runtime-client';
const id='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222';
const config:PublicRuntimeConfig={mode:'supabase',environment:'staging',apiOrigin:'https://api.example',flowApiOrigin:'https://api.example',supabaseUrl:'https://child.supabase.co',supabasePublishableKey:'sb_publishable_stagingpublic',tenantId:id};
const journey=(informationFirst=false)=>({schemaVersion:1,stages:(informationFirst?['service','options','information','schedule','review_payment','confirmation']:['service','options','schedule','information','review_payment','confirmation']).map(kind=>({id:kind,kind,label:kind==='review_payment'?'Review & Payment':kind[0]!.toUpperCase()+kind.slice(1),enabled:kind!=='options'}))});
const session=(name='Published journey',informationFirst=false)=>({schemaVersion:1,sessionToken:'x'.repeat(43),expiresAt:new Date(Date.now()+10*60000).toISOString(),render:{versionId:id,renderSchemaVersion:8,submissionMode:'paid_journey_request',paymentMode:'staging_mock',simulated:true,service:{id,name:'Home cleaning',durationMinutes:30,price:{amount:5000,currency:'USD'}},form:{name,presentation:{accentColor:'#0f766e',layout:'compact'},journey:journey(informationFirst)}}});
const response=(data:unknown)=>new Response(JSON.stringify({ok:true,data}),{status:200});
const tomorrow=()=>new Date(Date.now()+86400000).toISOString().slice(0,10);
function transport(informationFirst=false){return vi.fn<typeof fetch>(async(url)=>{
 if(String(url).endsWith('/sessions'))return response(session('Published journey',informationFirst));
 const from=new URL(String(url)).searchParams.get('from')!;const start=new Date(Date.parse(from)+12*3600000).toISOString();
 return response({schemaVersion:1,serviceId:id,durationMinutes:30,slots:[{start,end:new Date(Date.parse(start)+1800000).toISOString(),remainingCapacity:1}]});
});}
async function open(){fireEvent.click(screen.getByRole('button',{name:'Open booking form'}));await screen.findByRole('heading',{name:'Published journey'});}
async function schedule(){fireEvent.click(screen.getByRole('button',{name:'Continue'}));fireEvent.change(screen.getByLabelText('Date (UTC)'),{target:{value:tomorrow()}});await screen.findByRole('radio');}
afterEach(()=>{cleanup();vi.unstubAllGlobals();vi.useRealTimers();});
it('requires explicit opening, uses only dedicated session/availability endpoints and never stores tokens or calls writers',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});const fetcher=transport();vi.stubGlobal('fetch',fetcher);const storage=vi.spyOn(Storage.prototype,'setItem');
 render(<HostedJourneyFlow installationId={id} config={config}/>);expect(fetcher).not.toHaveBeenCalled();await open();expect(screen.getByText('Home cleaning')).toBeVisible();await schedule();
 expect(fetcher.mock.calls[0]![0]).toBe(`https://api.example/api/paid-journey-installations/${id}/sessions`);
 expect(fetcher.mock.calls[0]![1]).toMatchObject({method:'POST',body:'{}',credentials:'omit',redirect:'error'});
 expect(fetcher.mock.calls.slice(1).every(([url,init])=>String(url).includes('/paid-journey-flow-sessions/availability?')&&init?.method==='GET'&&!init.body&&!('Origin' in (init.headers as Record<string,string>)))).toBe(true);
 fireEvent.click(screen.getByRole('radio'));fireEvent.click(screen.getByRole('button',{name:'Continue'}));
 fireEvent.change(screen.getByLabelText('Your name'),{target:{value:'Staging customer'}});fireEvent.change(screen.getByLabelText('Email'),{target:{value:'customer@example.test'}});fireEvent.click(screen.getByRole('button',{name:'Continue'}));
 expect(screen.getByText(/Booking submission and test payment are currently unavailable/)).toBeVisible();expect(screen.queryByRole('button',{name:/pay|confirm|submit/i})).toBeNull();expect(storage).not.toHaveBeenCalled();expect(document.body.textContent).not.toContain('x'.repeat(43));storage.mockRestore();
 expect(fetcher.mock.calls.filter(([,init])=>init?.method==='POST')).toHaveLength(1);
});
it('renders immutable published order/design and customer information before schedule when published that way',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});vi.stubGlobal('fetch',transport(true));render(<HostedJourneyFlow installationId={id} config={config}/>);await open();
 expect(screen.getByRole('main')).toHaveStyle({'--accent':'#0f766e',padding:'12px',minWidth:'0',boxSizing:'border-box'});
 expect(screen.getByRole('main')).toHaveClass('hosted-flow-card','paid-form-layout-compact');
 expect(screen.getByRole('navigation').textContent).toBe('ServiceInformationScheduleReview & PaymentConfirmation');
 fireEvent.click(screen.getByRole('button',{name:'Continue'}));expect(screen.getByLabelText('Your name')).toBeVisible();expect(screen.queryByLabelText('Date (UTC)')).toBeNull();expect(screen.getByRole('button',{name:'Continue'})).toBeDisabled();
});
it.each(['demo','production','missing-key','missing-tenant','bad-api','http-page'])('fails closed on unavailable public configuration: %s',kind=>{
 vi.stubGlobal('location',{protocol:kind==='http-page'?'http:':'https:'});const fetcher=vi.fn();vi.stubGlobal('fetch',fetcher);
 const value={...config,...(kind==='demo'?{mode:'demo' as const}:kind==='production'?{environment:'production' as const}:kind==='missing-key'?{supabasePublishableKey:''}:kind==='missing-tenant'?{tenantId:''}:kind==='bad-api'?{flowApiOrigin:'http://api.example'}:{})};
 render(<HostedJourneyFlow installationId={id} config={value}/>);expect(screen.getByRole('alert')).toHaveTextContent('configuration could not be verified');expect(fetcher).not.toHaveBeenCalled();
});
it.each(['legacy-version','extra-private','wrong-token'])('rejects malformed session %s without issuing legacy fallback or auto retry',async kind=>{
 vi.stubGlobal('location',{protocol:'https:'});const data=session();const malformed=kind==='legacy-version'?{...data,render:{...data.render,renderSchemaVersion:7}}:kind==='extra-private'?{...data,tenantId:id}:{...data,sessionToken:'short'};
 const fetcher=vi.fn<typeof fetch>(async()=>response(malformed));vi.stubGlobal('fetch',fetcher);render(<HostedJourneyFlow installationId={id} config={config}/>);fireEvent.click(screen.getByRole('button',{name:'Open booking form'}));
 await screen.findByRole('alert');expect(fetcher).toHaveBeenCalledTimes(1);expect(screen.queryByText('Home cleaning')).toBeNull();expect(screen.getByRole('button',{name:'Open a new temporary session'})).toBeEnabled();
});
it('times out a stalled issuance, ignores its late receipt and retries only explicitly',async()=>{
 vi.useFakeTimers();vi.stubGlobal('location',{protocol:'https:'});let finish!:(value:Response)=>void;const fetcher=vi.fn<typeof fetch>(()=>new Promise(resolve=>finish=resolve));vi.stubGlobal('fetch',fetcher);
 render(<HostedJourneyFlow installationId={id} config={config}/>);fireEvent.click(screen.getByRole('button',{name:'Open booking form'}));await act(async()=>{await vi.advanceTimersByTimeAsync(30000);});expect(screen.getByRole('alert')).toHaveTextContent('may have been issued');expect(fetcher.mock.calls[0]![1]!.signal!.aborted).toBe(true);
 await act(async()=>{finish(response(session('Late form')));});expect(screen.queryByText('Late form')).toBeNull();await act(async()=>{await vi.advanceTimersByTimeAsync(60000);});expect(fetcher).toHaveBeenCalledTimes(1);
});
it('aborts pending issuance on installation replacement and unmount, never showing old authority',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});let finish!:(value:Response)=>void;const fetcher=vi.fn<typeof fetch>(()=>new Promise(resolve=>finish=resolve));vi.stubGlobal('fetch',fetcher);
 const view=render(<HostedJourneyFlow installationId={id} config={config}/>);fireEvent.click(screen.getByRole('button',{name:'Open booking form'}));view.rerender(<HostedJourneyFlow installationId={other} config={config}/>);expect(fetcher.mock.calls[0]![1]!.signal!.aborted).toBe(true);
 await act(async()=>finish(response(session('Old form'))));expect(screen.queryByText('Old form')).toBeNull();expect(fetcher).toHaveBeenCalledTimes(1);fireEvent.click(screen.getByRole('button',{name:'Open booking form'}));view.unmount();expect(fetcher.mock.calls[1]![1]!.signal!.aborted).toBe(true);
});
it('clears selected slots on date change and discards out-of-order availability',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});const pending:Array<{url:string;finish:(r:Response)=>void}>=[];const fetcher=vi.fn<typeof fetch>(async url=>String(url).endsWith('/sessions')?response(session()):new Promise(resolve=>pending.push({url:String(url),finish:resolve})));vi.stubGlobal('fetch',fetcher);
 render(<HostedJourneyFlow installationId={id} config={config}/>);await open();fireEvent.click(screen.getByRole('button',{name:'Continue'}));fireEvent.change(screen.getByLabelText('Date (UTC)'),{target:{value:tomorrow()}});await waitFor(()=>expect(pending.length).toBe(2));
 const data=(entry:typeof pending[number])=>{const start=new Date(Date.parse(new URL(entry.url).searchParams.get('from')!)+12*3600000).toISOString();return {schemaVersion:1,serviceId:id,durationMinutes:30,slots:[{start,end:new Date(Date.parse(start)+1800000).toISOString(),remainingCapacity:1}]};};
 await act(async()=>pending[1]!.finish(response(data(pending[1]!))));fireEvent.click(screen.getByRole('radio'));expect(screen.getByRole('button',{name:'Continue'})).toBeEnabled();
 const next=new Date(Date.now()+2*86400000).toISOString().slice(0,10);fireEvent.change(screen.getByLabelText('Date (UTC)'),{target:{value:next}});expect(screen.getByRole('button',{name:'Continue'})).toBeDisabled();expect(screen.queryByRole('radio')).toBeNull();
 await act(async()=>pending[0]!.finish(response(data(pending[0]!))));expect(screen.queryByRole('radio')).toBeNull();
});
it('rejects mismatched availability without creating selectable synthetic slots',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});vi.stubGlobal('fetch',vi.fn<typeof fetch>(async url=>String(url).endsWith('/sessions')?response(session()):response({schemaVersion:1,serviceId:other,durationMinutes:30,slots:[]})));
 render(<HostedJourneyFlow installationId={id} config={config}/>);await open();fireEvent.click(screen.getByRole('button',{name:'Continue'}));await screen.findByRole('alert');expect(screen.queryByRole('radio')).toBeNull();expect(screen.getByRole('button',{name:'Continue'})).toBeDisabled();
});
it('expires the session and clears customer details and availability without automatic reissuance',async()=>{
 vi.useFakeTimers();vi.stubGlobal('location',{protocol:'https:'});const fetcher=transport(true);vi.stubGlobal('fetch',fetcher);render(<HostedJourneyFlow installationId={id} config={config}/>);
 await act(async()=>{fireEvent.click(screen.getByRole('button',{name:'Open booking form'}));});fireEvent.click(screen.getByRole('button',{name:'Continue'}));fireEvent.change(screen.getByLabelText('Your name'),{target:{value:'Private name'}});
 await act(async()=>{await vi.advanceTimersByTimeAsync(10*60000);});expect(screen.getByRole('alert')).toHaveTextContent('session expired');expect(screen.queryByLabelText('Your name')).toBeNull();expect(fetcher.mock.calls.filter(([,init])=>init?.method==='POST')).toHaveLength(1);
});
it('does not issue duplicate sessions on repeated opening clicks',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});const fetcher=vi.fn<typeof fetch>(()=>new Promise(()=>{}));vi.stubGlobal('fetch',fetcher);render(<HostedJourneyFlow installationId={id} config={config}/>);
 const button=screen.getByRole('button',{name:'Open booking form'});fireEvent.click(button);fireEvent.click(button);expect(fetcher).toHaveBeenCalledTimes(1);expect(button).toBeDisabled();
});
it('rejects late receipt after public client configuration changes even when the installation stays the same',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});let finish!:(value:Response)=>void;const fetcher=vi.fn<typeof fetch>(()=>new Promise(resolve=>finish=resolve));vi.stubGlobal('fetch',fetcher);const view=render(<HostedJourneyFlow installationId={id} config={config}/>);fireEvent.click(screen.getByRole('button',{name:'Open booking form'}));
 view.rerender(<HostedJourneyFlow installationId={id} config={{...config,flowApiOrigin:'https://other.example'}}/>);await act(async()=>finish(response(session('Wrong client form'))));expect(screen.queryByText('Wrong client form')).toBeNull();expect(fetcher).toHaveBeenCalledTimes(1);expect(screen.getByRole('button',{name:'Open booking form'})).toBeEnabled();
});
it('replaces stalled availability with truthful failure and aborts it without a new session or synthetic slots',async()=>{
 vi.useFakeTimers();vi.stubGlobal('location',{protocol:'https:'});const fetcher=vi.fn<typeof fetch>(async url=>String(url).endsWith('/sessions')?response(session()):new Promise(()=>{}));vi.stubGlobal('fetch',fetcher);render(<HostedJourneyFlow installationId={id} config={config}/>);
 await act(async()=>fireEvent.click(screen.getByRole('button',{name:'Open booking form'})));fireEvent.click(screen.getByRole('button',{name:'Continue'}));await act(async()=>{await vi.advanceTimersByTimeAsync(30000);});expect(screen.getByRole('alert')).toHaveTextContent('Availability could not be verified');expect(fetcher.mock.calls[1]![1]!.signal!.aborted).toBe(true);expect(screen.queryByRole('radio')).toBeNull();expect(screen.getByRole('button',{name:'Continue'})).toBeDisabled();
 await act(async()=>{await vi.advanceTimersByTimeAsync(30000);});expect(fetcher).toHaveBeenCalledTimes(2);
});

type JourneyFlowComponent=typeof HostedJourneyFlow;
async function freshHoldFlow(){vi.resetModules();return (await import('./HostedJourneyFlow')).HostedJourneyFlow;}
const holdReceipt=(input:{requestedStart:string},replayed=false)=>({schemaVersion:1,versionId:id,installationId:id,serviceId:id,bookingId:other,reference:'LMN-'+other.replaceAll('-','').toUpperCase(),state:'draft',confirmed:false,paymentMode:'unavailable',slot:{start:input.requestedStart,end:new Date(Date.parse(input.requestedStart)+1800000).toISOString()},holdId:'33333333-3333-4333-8333-333333333333',status:'active',expiresAt:new Date(Date.now()+299000).toISOString(),replayed});
function holdTransport(writer:(body:any,init?:RequestInit)=>Promise<Response>=async body=>response(holdReceipt(body)),reader:(init?:RequestInit)=>Promise<Response>=async()=>new Response(JSON.stringify({ok:false,code:'NOT_AVAILABLE'}),{status:404})){const read=transport();return vi.fn<typeof fetch>((url,init)=>String(url).endsWith('/hold')?init?.method==='GET'?reader(init):writer(JSON.parse(String(init?.body)),init):read(url,init));}
async function readyToReserve(Flow:JourneyFlowComponent){const view=render(<Flow installationId={id} config={config}/>);await open();await schedule();fireEvent.click(screen.getByRole('radio'));fireEvent.click(screen.getByRole('button',{name:'Continue'}));fireEvent.change(screen.getByLabelText('Your name'),{target:{value:'Staging customer'}});fireEvent.change(screen.getByLabelText('Email'),{target:{value:'customer@example.test'}});fireEvent.click(screen.getByRole('button',{name:'Continue'}));return view;}
it('reserves the actual selected slot explicitly and displays only verified draft/hold truth, with no payment or confirmation writer',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});const secure=vi.fn((values:Uint8Array)=>values.fill(7));vi.stubGlobal('crypto',{getRandomValues:secure});const f=holdTransport();vi.stubGlobal('fetch',f);const Flow=await freshHoldFlow();await readyToReserve(Flow);expect(f.mock.calls.filter(([url])=>String(url).endsWith('/hold'))).toHaveLength(0);
 fireEvent.click(screen.getByRole('button',{name:'Reserve this time (staging)'}));expect(await screen.findByText(/Temporary hold verified/)).toBeVisible();expect(screen.getByText(/Booking remains DRAFT/)).toBeVisible();expect(screen.getByText(/Hold active until/)).toBeVisible();expect(screen.queryByRole('button',{name:/pay|confirm|open booking|continue|back/i})).toBeNull();
 const [url,init]=f.mock.calls.find(([value])=>String(value).endsWith('/hold'))!;expect(url).toBe('https://api.example/api/paid-journey-flow-sessions/hold');expect(init?.headers).toEqual({'Content-Type':'application/json',Authorization:'Bearer '+'x'.repeat(43)});const body=JSON.parse(String(init?.body));expect(body).toMatchObject({schemaVersion:1,idempotencyKey:'07'.repeat(32),customer:{name:'Staging customer',email:'customer@example.test'},answers:{}});expect(body.requestedStart.slice(0,10)).toBe(tomorrow());expect(secure).toHaveBeenCalledTimes(1);expect(document.body.textContent).not.toMatch(/x{43}|customer@example.test|Staging customer/);expect(f.mock.calls.filter(([,value])=>value?.method==='POST')).toHaveLength(2);
});
it('retains a lost hold response and explicitly retries the same frozen body without a new session or key',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});let count=0;let saved:any;const f=holdTransport(async body=>{saved??=body;if(++count===1)throw Error('private-session-secret');return response(holdReceipt(saved,true));});vi.stubGlobal('fetch',f);const Flow=await freshHoldFlow();await readyToReserve(Flow);fireEvent.click(screen.getByRole('button',{name:'Reserve this time (staging)'}));await screen.findByRole('alert');expect(screen.getByRole('alert')).toHaveTextContent('A draft and hold may exist');expect(document.body.textContent).not.toContain('private-session-secret');expect(screen.queryByLabelText('Your name')).toBeNull();expect(screen.queryByRole('button',{name:/new|back|open|continue/i})).toBeNull();expect(count).toBe(1);
 await act(async()=>fireEvent.click(screen.getByRole('button',{name:'Check existing reservation'})));fireEvent.click(screen.getByRole('button',{name:'Retry same hold request'}));await screen.findByText(/Temporary hold verified/);const calls=f.mock.calls.filter(([url,init])=>String(url).endsWith('/hold')&&init?.method==='POST');expect(calls[0]![1]?.body).toBe(calls[1]![1]?.body);expect(f.mock.calls.filter(([url])=>String(url).endsWith('/sessions'))).toHaveLength(1);
});
it('rate-limited retry after a verified hold preserves its last verified draft reference and blocks replacement attempts',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});let count=0;let accepted:any;const f=holdTransport(async body=>{if(++count===1){accepted=holdReceipt(body);return response(accepted);}return new Response(JSON.stringify({ok:false,code:'RATE_LIMITED'}),{status:429});});vi.stubGlobal('fetch',f);await readyToReserve(await freshHoldFlow());fireEvent.click(screen.getByRole('button',{name:'Reserve this time (staging)'}));await screen.findByText(/Temporary hold verified/);await act(async()=>fireEvent.click(screen.getByRole('button',{name:'Check existing reservation'})));fireEvent.click(screen.getByRole('button',{name:'Retry same hold request'}));await screen.findByRole('alert');expect(screen.getByText(/Last verified draft reference/)).toHaveTextContent(accepted.reference);expect(screen.queryByText(/Hold active until/)).toBeNull();expect(screen.queryByRole('button',{name:/open|new|back|reserve this/i})).toBeNull();expect(count).toBe(2);
});
it('duplicate reserve clicks cannot dispatch overlapping holds and unmount/remount retains an unresolved attempt',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});let finish!:(r:Response)=>void;const f=holdTransport(async()=>new Promise(resolve=>finish=resolve));vi.stubGlobal('fetch',f);const Flow=await freshHoldFlow();const view=await readyToReserve(Flow);const button=screen.getByRole('button',{name:'Reserve this time (staging)'});fireEvent.click(button);fireEvent.click(button);expect(f.mock.calls.filter(([url])=>String(url).endsWith('/hold'))).toHaveLength(1);const request=f.mock.calls.find(([url])=>String(url).endsWith('/hold'))!;view.unmount();expect(request[1]?.signal?.aborted).toBe(true);
 render(<Flow installationId={id} config={config}/>);expect(screen.getByRole('alert')).toHaveTextContent('A draft and hold may exist');expect(screen.queryByRole('button',{name:/open/i})).toBeNull();await act(async()=>finish(response(holdReceipt(JSON.parse(String(request[1]?.body))))));expect(screen.queryByText(/Temporary hold verified/)).toBeNull();f.mockImplementation(holdTransport(async body=>response(holdReceipt(body,true))));await act(async()=>fireEvent.click(screen.getByRole('button',{name:'Check existing reservation'})));fireEvent.click(screen.getByRole('button',{name:'Retry same hold request'}));await screen.findByText(/Temporary hold verified/);expect(f.mock.calls.filter(([url])=>String(url).endsWith('/sessions'))).toHaveLength(1);expect(f.mock.calls.filter(([url,init])=>String(url).endsWith('/hold')&&init?.method==='POST')[1]![1]?.body).toBe(request[1]?.body);
});
it.each(['installation','tenant','api','key'])('withholds previous hold details after %s context changes and prevents new sessions',async kind=>{
 vi.stubGlobal('location',{protocol:'https:'});let finish!:(r:Response)=>void;const f=holdTransport(async()=>new Promise(resolve=>finish=resolve));vi.stubGlobal('fetch',f);const Flow=await freshHoldFlow();const view=await readyToReserve(Flow);fireEvent.click(screen.getByRole('button',{name:'Reserve this time (staging)'}));const request=f.mock.calls.find(([url])=>String(url).endsWith('/hold'))!;
 const nextConfig={...config,...(kind==='tenant'?{tenantId:other}:kind==='api'?{flowApiOrigin:'https://other.example'}:kind==='key'?{supabasePublishableKey:'sb_publishable_other'}:{})};const next=<Flow installationId={kind==='installation'?other:id} config={nextConfig}/>;if(kind==='api'||kind==='key'){view.unmount();render(next);}else view.rerender(next);expect(screen.getByRole('alert')).toHaveTextContent('earlier reservation attempt');expect(screen.queryByRole('button')).toBeNull();await act(async()=>finish(response(holdReceipt(JSON.parse(String(request[1]?.body))))));expect(document.body.textContent).not.toMatch(/LMN|customer@example|Staging customer/);expect(f.mock.calls.filter(([url])=>String(url).endsWith('/sessions'))).toHaveLength(1);
});
it('forged confirmed/payment receipt is uncertain, never a successful booking',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});const f=holdTransport(async body=>response({...holdReceipt(body),confirmed:true,state:'confirmed',paymentMode:'staging_mock'}));vi.stubGlobal('fetch',f);await readyToReserve(await freshHoldFlow());fireEvent.click(screen.getByRole('button',{name:'Reserve this time (staging)'}));await screen.findByRole('alert');expect(screen.queryByText(/Temporary hold verified|Draft reference:/)).toBeNull();expect(screen.getByRole('alert')).toHaveTextContent('Reservation status could not be verified');expect(screen.queryByRole('button',{name:/pay|confirm|new booking/i})).toBeNull();
});
it('known hold expiry removes active/retry claims but preserves its historical draft reference',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});vi.stubGlobal('fetch',holdTransport());await readyToReserve(await freshHoldFlow());vi.useFakeTimers();await act(async()=>fireEvent.click(screen.getByRole('button',{name:'Reserve this time (staging)'})));expect(screen.getByText(/Temporary hold verified/)).toBeVisible();await act(async()=>{await vi.advanceTimersByTimeAsync(300000);});expect(screen.queryByText(/Hold active until|Temporary hold verified/)).toBeNull();expect(screen.getByText(/Last verified draft reference/)).toBeVisible();expect(screen.queryByRole('button')).toBeNull();expect(screen.getByText(/Contact the business/)).toBeVisible();
});
it('expired session during hold body parsing suppresses receipt and disallows replacement or retry',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});let finish!:(v:unknown)=>void;let submitted:any;const f=holdTransport(async body=>{submitted=body;return {status:200,redirected:false,json:()=>new Promise(resolve=>finish=resolve)} as Response;});vi.stubGlobal('fetch',f);await readyToReserve(await freshHoldFlow());const start=Date.now(),clock=vi.spyOn(Date,'now').mockReturnValue(start);try{fireEvent.click(screen.getByRole('button',{name:'Reserve this time (staging)'}));await waitFor(()=>expect(finish).toBeTypeOf('function'));clock.mockReturnValue(start+11*60000);await act(async()=>finish({ok:true,data:holdReceipt(submitted)}));expect(screen.getByRole('alert')).toHaveTextContent('A draft and hold may exist');expect(screen.queryByRole('button')).toBeNull();expect(screen.queryByText(/Temporary hold verified/)).toBeNull();}finally{clock.mockRestore();}
});
it('remounting a verified hold shows its existing draft instead of silently opening a new booking',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});const f=holdTransport();vi.stubGlobal('fetch',f);const Flow=await freshHoldFlow();const view=await readyToReserve(Flow);fireEvent.click(screen.getByRole('button',{name:'Reserve this time (staging)'}));await screen.findByText(/Temporary hold verified/);view.unmount();render(<Flow installationId={id} config={config}/>);expect(screen.getByText(/Temporary hold verified/)).toBeVisible();expect(screen.getByText(/Draft reference:/)).toBeVisible();expect(screen.queryByRole('button',{name:/open|reserve this/i})).toBeNull();expect(f.mock.calls.filter(([,init])=>init?.method==='POST')).toHaveLength(2);
});
it('stalled hold times out honestly and cannot POST retry while its original dispatch remains pending',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});let finish!:(r:Response)=>void;const f=holdTransport(async()=>new Promise(resolve=>finish=resolve));vi.stubGlobal('fetch',f);await readyToReserve(await freshHoldFlow());vi.useFakeTimers();fireEvent.click(screen.getByRole('button',{name:'Reserve this time (staging)'}));const original=f.mock.calls.find(([url])=>String(url).endsWith('/hold'))!;await act(async()=>{await vi.advanceTimersByTimeAsync(30000);});expect(original[1]?.signal?.aborted).toBe(true);await act(async()=>fireEvent.click(screen.getByRole('button',{name:'Check existing reservation'})));expect(screen.queryByRole('button',{name:'Retry same hold request'})).toBeNull();expect(f.mock.calls.filter(([url])=>String(url).endsWith('/hold'))).toHaveLength(1);await act(async()=>finish(response(holdReceipt(JSON.parse(String(original[1]?.body))))));f.mockImplementation(holdTransport(async body=>response(holdReceipt(body,true))));await act(async()=>fireEvent.click(screen.getByRole('button',{name:'Check existing reservation'})));await act(async()=>fireEvent.click(screen.getByRole('button',{name:'Retry same hold request'})));expect(screen.getByText(/Temporary hold verified/)).toBeVisible();expect(f.mock.calls.filter(([url,init])=>String(url).endsWith('/hold')&&init?.method==='POST')[1]![1]?.body).toBe(original[1]?.body);
});it('secure key failure sends no hold and does not create an unresolved reservation',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});vi.stubGlobal('crypto',{getRandomValues:()=>{throw Error('private crypto failure');}});const f=holdTransport();vi.stubGlobal('fetch',f);await readyToReserve(await freshHoldFlow());fireEvent.click(screen.getByRole('button',{name:'Reserve this time (staging)'}));expect(screen.getByRole('alert')).toHaveTextContent('No reservation request was sent');expect(document.body.textContent).not.toContain('private crypto failure');expect(f.mock.calls.filter(([url])=>String(url).endsWith('/hold'))).toHaveLength(0);expect(screen.getByRole('button',{name:'Back'})).toBeEnabled();
});

it('explicitly checks an uncertain original reservation before retry, recovering without any second POST or token storage',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});let saved:any;const f=holdTransport(async body=>{saved=body;throw Error('lost private reply');},async()=>response(holdReceipt(saved,true)));vi.stubGlobal('fetch',f);await readyToReserve(await freshHoldFlow());fireEvent.click(screen.getByRole('button',{name:'Reserve this time (staging)'}));await screen.findByRole('alert');expect(screen.queryByRole('button',{name:'Retry same hold request'})).toBeNull();expect(f.mock.calls.filter(([url,init])=>String(url).endsWith('/hold')&&init?.method==='GET')).toHaveLength(0);
 fireEvent.click(screen.getByRole('button',{name:'Check existing reservation'}));await screen.findByText(/Temporary hold verified/);const read=f.mock.calls.find(([url,init])=>String(url).endsWith('/hold')&&init?.method==='GET')!;expect(read[1]?.body).toBeUndefined();expect(read[1]?.headers).toEqual({Authorization:'Bearer '+'x'.repeat(43)});expect(read[1]).toMatchObject({credentials:'omit',cache:'no-store',redirect:'error'});expect(f.mock.calls.filter(([url,init])=>String(url).endsWith('/hold')&&init?.method==='POST')).toHaveLength(1);expect(screen.queryByRole('button',{name:'Retry same hold request'})).toBeNull();expect(document.body.textContent).not.toMatch(/x{43}|customer@example|Staging customer|lost private/);
});
it.each([404,403,500])('failed recovery %s leaves an honest unresolved attempt and permits only explicit same-body retry after the check',async status=>{
 vi.stubGlobal('location',{protocol:'https:'});let saved:any;const f=holdTransport(async body=>{saved??=body;throw Error('lost');},async()=>new Response(JSON.stringify({ok:false,code:status===404?'NOT_AVAILABLE':status===403?'FORBIDDEN':'INTERNAL_ERROR'}),{status}));vi.stubGlobal('fetch',f);await readyToReserve(await freshHoldFlow());fireEvent.click(screen.getByRole('button',{name:'Reserve this time (staging)'}));await screen.findByRole('alert');fireEvent.click(screen.getByRole('button',{name:'Check existing reservation'}));await screen.findByRole('button',{name:'Retry same hold request'});expect(screen.getByRole('alert')).toHaveTextContent('A draft and hold may exist');expect(screen.queryByRole('button',{name:/open|new|reserve this/i})).toBeNull();expect(f.mock.calls.filter(([url,init])=>String(url).endsWith('/hold')&&init?.method==='POST')).toHaveLength(1);
});
it('duplicate read clicks dispatch one GET, and unmount/remount aborts and rejects its late result without a writer',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});let saved:any,finish!:(r:Response)=>void;const f=holdTransport(async body=>{saved=body;throw Error('lost');},async()=>new Promise(resolve=>finish=resolve));vi.stubGlobal('fetch',f);const Flow=await freshHoldFlow(),view=await readyToReserve(Flow);fireEvent.click(screen.getByRole('button',{name:'Reserve this time (staging)'}));await screen.findByRole('alert');const button=screen.getByRole('button',{name:'Check existing reservation'});fireEvent.click(button);fireEvent.click(button);expect(screen.getByRole('status')).toHaveTextContent('Checking the existing reservation');const gets=f.mock.calls.filter(([url,init])=>String(url).endsWith('/hold')&&init?.method==='GET');expect(gets).toHaveLength(1);view.unmount();expect(gets[0]![1]?.signal?.aborted).toBe(true);render(<Flow installationId={id} config={config}/>);await act(async()=>finish(response(holdReceipt(saved,true))));expect(screen.queryByText(/Temporary hold verified/)).toBeNull();expect(screen.queryByRole('button',{name:'Retry same hold request'})).toBeNull();expect(f.mock.calls.filter(([url,init])=>String(url).endsWith('/hold')&&init?.method==='POST')).toHaveLength(1);
});
it.each(['installation','config'])('late recovery cannot resurrect old evidence after %s context replacement and return',async kind=>{
 vi.stubGlobal('location',{protocol:'https:'});let saved:any,finish!:(r:Response)=>void;const f=holdTransport(async body=>{saved=body;throw Error('lost');},async()=>new Promise(resolve=>finish=resolve));vi.stubGlobal('fetch',f);const Flow=await freshHoldFlow(),view=await readyToReserve(Flow);fireEvent.click(screen.getByRole('button',{name:'Reserve this time (staging)'}));await screen.findByRole('alert');fireEvent.click(screen.getByRole('button',{name:'Check existing reservation'}));view.rerender(<Flow installationId={kind==='installation'?other:id} config={kind==='config'?{...config,tenantId:other}:config}/>);expect(screen.getByRole('alert')).toHaveTextContent('earlier reservation attempt');expect(screen.queryByRole('button')).toBeNull();view.rerender(<Flow installationId={id} config={config}/>);await act(async()=>finish(response(holdReceipt(saved,true))));expect(screen.queryByText(/Temporary hold verified|Draft reference:/)).toBeNull();expect(screen.queryByRole('button',{name:'Retry same hold request'})).toBeNull();expect(f.mock.calls.filter(([url,init])=>String(url).endsWith('/hold')&&init?.method==='POST')).toHaveLength(1);
});
it('expired session while parsing a recovery response keeps unknown status and drops all recovery actions',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});let saved:any,finish!:(value:unknown)=>void;const f=holdTransport(async body=>{saved=body;throw Error('lost');},async()=>({status:200,redirected:false,json:()=>new Promise(resolve=>finish=resolve)} as Response));vi.stubGlobal('fetch',f);await readyToReserve(await freshHoldFlow());fireEvent.click(screen.getByRole('button',{name:'Reserve this time (staging)'}));await screen.findByRole('alert');fireEvent.click(screen.getByRole('button',{name:'Check existing reservation'}));await waitFor(()=>expect(finish).toBeTypeOf('function'));const clock=vi.spyOn(Date,'now').mockReturnValue(Date.now()+11*60000);try{await act(async()=>finish({ok:true,data:holdReceipt(saved,true)}));expect(screen.getByRole('alert')).toHaveTextContent('A draft and hold may exist');expect(screen.queryByRole('button')).toBeNull();expect(screen.queryByText(/Temporary hold verified/)).toBeNull();expect(document.body.textContent).not.toMatch(/x{43}|customer@example/);}finally{clock.mockRestore();}
});

it('stalled read times out without a POST retry and ignores its eventual receipt',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});let saved:any,finish!:(r:Response)=>void;const f=holdTransport(async body=>{saved=body;throw Error('lost');},async()=>new Promise(resolve=>finish=resolve));vi.stubGlobal('fetch',f);await readyToReserve(await freshHoldFlow());fireEvent.click(screen.getByRole('button',{name:'Reserve this time (staging)'}));await screen.findByRole('alert');vi.useFakeTimers();fireEvent.click(screen.getByRole('button',{name:'Check existing reservation'}));const read=f.mock.calls.find(([url,init])=>String(url).endsWith('/hold')&&init?.method==='GET')!;await act(async()=>vi.advanceTimersByTimeAsync(30000));expect(read[1]?.signal?.aborted).toBe(true);expect(screen.getByRole('alert')).toHaveTextContent('A draft and hold may exist');expect(screen.queryByRole('button',{name:'Retry same hold request'})).toBeNull();await act(async()=>finish(response(holdReceipt(saved,true))));expect(screen.queryByText(/Temporary hold verified/)).toBeNull();expect(f.mock.calls.filter(([url,init])=>String(url).endsWith('/hold')&&init?.method==='POST')).toHaveLength(1);
});
it('forged financial success in a read stays unresolved and never displays a confirmed booking',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});let saved:any;const f=holdTransport(async body=>{saved=body;throw Error('lost');},async()=>response({...holdReceipt(saved,true),confirmed:true,state:'confirmed',paymentMode:'live'}));vi.stubGlobal('fetch',f);await readyToReserve(await freshHoldFlow());fireEvent.click(screen.getByRole('button',{name:'Reserve this time (staging)'}));await screen.findByRole('alert');fireEvent.click(screen.getByRole('button',{name:'Check existing reservation'}));await screen.findByRole('button',{name:'Retry same hold request'});expect(screen.queryByText(/Temporary hold verified|Draft reference:/)).toBeNull();expect(screen.getByRole('alert')).toHaveTextContent('No payment or confirmation was authorized');expect(f.mock.calls.filter(([url,init])=>String(url).endsWith('/hold')&&init?.method==='POST')).toHaveLength(1);
});
