import {render,screen,fireEvent,waitFor,cleanup,act} from '@testing-library/react';
import {Suspense,startTransition} from 'react';
import {afterEach,it,expect,vi} from 'vitest';
import {HostedFlow} from './HostedFlow';
const id='11111111-1111-4111-8111-111111111111',token='t'.repeat(43);
const service={id,name:'Published service',durationMinutes:30,questions:[{id:'q',prompt:'Choose an option',kind:'single_choice',required:true,choices:[{id:'a',label:'Option A'}]}]};
const config={key:'request',steps:[{key:'q',questionKey:'q',kind:'question',required:true}]};
const otherId='22222222-2222-4222-8222-222222222222';
const deferred=<T,>()=>{let resolve!:(value:T)=>void;const promise=new Promise<T>(r=>resolve=r);return{promise,resolve};};
const sessionResponse=(label:string,sessionToken=token)=>new Response(JSON.stringify({ok:true,data:{sessionToken,expiresAt:'2035-01-01T00:00:00Z',render:{versionId:id,config,service:{...service,name:label}}}}));
function retainedReactHandler(element:Element,name:'onSubmit'|'onChange'){
 const key=Object.getOwnPropertyNames(element).find(value=>value.startsWith('__reactProps$'));
 if(!key)throw Error('React props unavailable for retained-handler regression');
 const handler=(element as any)[key][name];
 if(typeof handler!=='function')throw Error('Expected retained React handler');
 return handler as (event:any)=>void;
}
afterEach(()=>{cleanup();vi.unstubAllGlobals();});
it('uses pinned questions and identical body/key for ambiguous retry, never exposes token or confirmation',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});const bodies:string[]=[];const calls:RequestInit[]=[];
 vi.stubGlobal('fetch',vi.fn(async(url:string,options:RequestInit)=>{calls.push(options);if(url.includes('/sessions'))return new Response(JSON.stringify({ok:true,data:{sessionToken:token,expiresAt:'2035-01-01T00:00:00Z',render:{versionId:id,config,service}}}));bodies.push(options.body as string);if(bodies.length===1)throw Error('connection interrupted with private-server-details');return new Response(JSON.stringify({ok:true,data:{reference:'LMN-TEST123',state:'draft',confirmed:false}}));}));
 render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await screen.findByText('Published service');fireEvent.change(screen.getByLabelText('Choose an option'),{target:{value:'a'}});fireEvent.change(screen.getByLabelText('Your name'),{target:{value:'Synthetic Person'}});fireEvent.change(screen.getByLabelText('Email'),{target:{value:'synthetic@example.test'}});fireEvent.change(screen.getByLabelText('Requested date and time'),{target:{value:'2030-01-01T10:00'}});fireEvent.click(screen.getByText('Send unconfirmed request'));await screen.findByText('Retry the same request');expect(screen.getByLabelText('Your name')).toBeDisabled();fireEvent.click(screen.getByText('Retry the same request'));await screen.findByText('Request saved');expect(bodies).toHaveLength(2);expect(bodies[0]).toBe(bodies[1]);expect(JSON.parse(bodies[0]!)).not.toHaveProperty('tenantId');expect(JSON.parse(bodies[0]!)).not.toHaveProperty('serviceId');expect(calls[1]!.headers).toMatchObject({Authorization:'Bearer '+token});expect(document.body.textContent).not.toContain(token);expect(document.body.textContent).not.toContain('private-server-details');expect(screen.getByText(/Your request is unconfirmed/)).toBeTruthy();
});
it('does not create a customer session from an HTTP page',()=>{vi.stubGlobal('location',{protocol:'http:'});const fetcher=vi.fn();vi.stubGlobal('fetch',fetcher);render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);expect(screen.getByText('Secure customer page required')).toBeTruthy();expect(fetcher).not.toHaveBeenCalled();});
it('invalid installation IDs fail visibly without network calls',async()=>{vi.stubGlobal('location',{protocol:'https:'});const fetcher=vi.fn();vi.stubGlobal('fetch',fetcher);render(<HostedFlow installationId="bad?credential=unsafe" apiUrl="https://api.example"/>);await waitFor(()=>expect(screen.getByRole('alert')).toHaveTextContent('unavailable'));expect(fetcher).not.toHaveBeenCalled();});
it('V2 submits canonical pinned answers and omits newly hidden fields on an identical retry',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});const bodies:string[]=[];
 const v2={versionId:id,renderSchemaVersion:2,submissionMode:'unconfirmed_request',service:{...service,questions:[{id:'hasOwnProperty',prompt:'Mode',kind:'single_choice',required:true,choices:[{id:'toString',label:'More'},{id:'no',label:'Less'}]},{id:'quantity',prompt:'Extra amount',kind:'quantity',required:false,choices:[],minQty:0,maxQty:3},{id:'multi',prompt:'Extras',kind:'multi_choice',required:false,choices:[{id:'😀',label:'First'},{id:'é',label:'Second'}]}]},config:{key:'v2',steps:[{key:'mode',questionKey:'hasOwnProperty',kind:'question',required:true},{key:'quantity',questionKey:'quantity',kind:'question',required:true,visibleWhen:{field:'hasOwnProperty',op:'eq',value:'toString'}},{key:'multi',questionKey:'multi',kind:'question',required:false}]}};
 vi.stubGlobal('fetch',vi.fn(async(url:string,options:RequestInit)=>{if(url.includes('/sessions'))return new Response(JSON.stringify({ok:true,data:{sessionToken:token,expiresAt:'2035-01-01T00:00:00Z',render:v2}}));bodies.push(options.body as string);if(bodies.length===1)throw Error('interrupted');return new Response(JSON.stringify({ok:true,data:{reference:'LMN-V2',state:'draft',confirmed:false}}));}));
 render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await screen.findByText('Published service');fireEvent.change(screen.getByLabelText('Mode'),{target:{value:'toString'}});fireEvent.change(screen.getByLabelText('Extra amount'),{target:{value:'2'}});fireEvent.change(screen.getByLabelText('Mode'),{target:{value:'no'}});fireEvent.click(screen.getByLabelText('Second'));fireEvent.click(screen.getByLabelText('First'));fireEvent.change(screen.getByLabelText('Your name'),{target:{value:'Synthetic Person'}});fireEvent.change(screen.getByLabelText('Email'),{target:{value:'synthetic@example.test'}});fireEvent.change(screen.getByLabelText('Requested date and time'),{target:{value:'2030-01-01T10:00'}});fireEvent.click(screen.getByText('Send unconfirmed request'));await screen.findByText('Retry the same request');fireEvent.click(screen.getByText('Retry the same request'));await screen.findByText('Request saved');expect(bodies[0]).toBe(bodies[1]);const body=JSON.parse(bodies[0]!);expect(body.answers).not.toHaveProperty('quantity');expect(body.answers.multi.choiceIds).toEqual(['😀','é']);expect(body.answers.hasOwnProperty.choiceIds).toEqual(['no']);expect(body).not.toHaveProperty('renderSchemaVersion');
});
it('clears an old retry body and customer form on installation and API-client changes',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});const next=deferred<Response>(),posts:Array<{url:string;body:any}>=[];
 const fetcher=vi.fn(async(url:string,options:RequestInit)=>{if(url.includes('/sessions'))return url.includes(otherId)?next.promise:sessionResponse('Old service');posts.push({url,body:JSON.parse(options.body as string)});return posts.length===1?Promise.reject(Error('private old save')):new Response(JSON.stringify({ok:true,data:{reference:'LMN-NEW',state:'draft',confirmed:false}}));});vi.stubGlobal('fetch',fetcher);
 const view=render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await screen.findByText('Old service');fireEvent.change(screen.getByLabelText('Choose an option'),{target:{value:'a'}});fireEvent.change(screen.getByLabelText('Your name'),{target:{value:'Old customer'}});fireEvent.change(screen.getByLabelText('Email'),{target:{value:'old@example.test'}});fireEvent.change(screen.getByLabelText('Requested date and time'),{target:{value:'2030-01-01T10:00'}});fireEvent.click(screen.getByText('Send unconfirmed request'));await screen.findByText('Retry the same request');const oldKey=posts[0]!.body.idempotencyKey;
 view.rerender(<HostedFlow installationId={otherId} apiUrl="https://new-api.example"/>);expect(screen.queryByText('Old service')).toBeNull();expect(screen.queryByDisplayValue('Old customer')).toBeNull();expect(screen.queryByText('Retry the same request')).toBeNull();expect(screen.queryByText(/original answers are kept/)).toBeNull();next.resolve(sessionResponse('New service','n'.repeat(43)));await screen.findByText('New service');expect(screen.getByLabelText('Your name')).toHaveValue('');fireEvent.change(screen.getByLabelText('Choose an option'),{target:{value:'a'}});fireEvent.change(screen.getByLabelText('Your name'),{target:{value:'New customer'}});fireEvent.change(screen.getByLabelText('Email'),{target:{value:'new@example.test'}});fireEvent.change(screen.getByLabelText('Requested date and time'),{target:{value:'2030-01-02T10:00'}});fireEvent.click(screen.getByText('Send unconfirmed request'));await screen.findByText('Request saved');expect(posts).toHaveLength(2);expect(posts[1]!.url).toContain('new-api.example');expect(posts[1]!.body.customer.name).toBe('New customer');expect(posts[1]!.body.idempotencyKey).not.toBe(oldKey);expect(posts[1]!.body.requestedStart).not.toBe(posts[0]!.body.requestedStart);
});
it('ignores an old pending submission response after context change',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});const oldSave=deferred<Response>(),fetcher=vi.fn(async(url:string,options:RequestInit)=>url.includes('/sessions')?sessionResponse(url.includes(otherId)?'New service':'Old service',url.includes(otherId)?'n'.repeat(43):token):url.startsWith('https://api.example')?oldSave.promise:new Response(JSON.stringify({ok:true,data:{reference:'LMN-NEW',state:'draft',confirmed:false}})));vi.stubGlobal('fetch',fetcher);
 const view=render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await screen.findByText('Old service');fireEvent.change(screen.getByLabelText('Choose an option'),{target:{value:'a'}});fireEvent.change(screen.getByLabelText('Your name'),{target:{value:'Old customer'}});fireEvent.change(screen.getByLabelText('Email'),{target:{value:'old@example.test'}});fireEvent.change(screen.getByLabelText('Requested date and time'),{target:{value:'2030-01-01T10:00'}});fireEvent.click(screen.getByText('Send unconfirmed request'));await waitFor(()=>expect(fetcher).toHaveBeenCalledTimes(2));view.rerender(<HostedFlow installationId={otherId} apiUrl="https://new-api.example"/>);await screen.findByText('New service');oldSave.resolve(new Response(JSON.stringify({ok:true,data:{reference:'LMN-OLD',state:'draft',confirmed:false}})));await waitFor(()=>expect(screen.getByText('New service')).toBeTruthy());expect(screen.queryByText('Request saved')).toBeNull();expect(screen.queryByText('LMN-OLD')).toBeNull();expect(screen.getByLabelText('Your name')).toHaveValue('');
});
it('hides old customer state on local-harness and secure-page context changes',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});const fetcher=vi.fn(async()=>sessionResponse('Published service'));vi.stubGlobal('fetch',fetcher);const view=render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await screen.findByText('Published service');fireEvent.change(screen.getByLabelText('Your name'),{target:{value:'Private old name'}});view.rerender(<HostedFlow installationId={id} apiUrl="https://api.example" localHarness/>);await screen.findByText('Published service');expect(screen.getByLabelText('Your name')).toHaveValue('');fireEvent.change(screen.getByLabelText('Your name'),{target:{value:'Private harness name'}});vi.stubGlobal('location',{protocol:'http:'});view.rerender(<HostedFlow installationId={id} apiUrl="https://api.example" localHarness/>);expect(screen.getByText('Secure customer page required')).toBeTruthy();expect(screen.queryByDisplayValue('Private harness name')).toBeNull();expect(fetcher).toHaveBeenCalledTimes(2);vi.stubGlobal('location',{protocol:'https:'});view.rerender(<HostedFlow installationId={id} apiUrl="https://api.example" localHarness/>);await screen.findByText('Published service');expect(screen.getByLabelText('Your name')).toHaveValue('');expect(fetcher).toHaveBeenCalledTimes(3);
});
it('never revives retained A handlers or retry data after an A to B to A context cycle',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});const posts:Array<{authorization:unknown;body:any}>=[];
 const fetcher=vi.fn(async(url:string,options:RequestInit)=>{if(url.includes('/sessions'))return sessionResponse(url.includes(otherId)?'Other service':'Original service',url.includes(otherId)?'b'.repeat(43):token);posts.push({authorization:(options.headers as Record<string,string>).Authorization,body:JSON.parse(options.body as string)});return new Response(JSON.stringify({ok:true,data:{reference:'LMN-NEW',state:'draft',confirmed:false}}));});vi.stubGlobal('fetch',fetcher);
 const view=render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await screen.findByText('Original service');const form=document.querySelector('form')!,nameInput=screen.getByLabelText('Your name'),choice=screen.getByLabelText('Choose an option');const staleSubmit=retainedReactHandler(form,'onSubmit'),staleName=retainedReactHandler(nameInput,'onChange'),staleChoice=retainedReactHandler(choice,'onChange');fireEvent.change(nameInput,{target:{value:'OLD_CUSTOMER'}});
 view.rerender(<HostedFlow installationId={otherId} apiUrl="https://api.example"/>);await screen.findByText('Other service');view.rerender(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await screen.findByText('Original service');expect(screen.getByLabelText('Your name')).toHaveValue('');staleName({target:{value:'OLD_CUSTOMER'}});staleChoice({target:{value:'a'}});staleSubmit({preventDefault(){}});expect(screen.getByLabelText('Your name')).toHaveValue('');expect(screen.getByLabelText('Choose an option')).toHaveValue('');expect(posts).toHaveLength(0);
 fireEvent.change(screen.getByLabelText('Choose an option'),{target:{value:'a'}});fireEvent.change(screen.getByLabelText('Your name'),{target:{value:'NEW_CUSTOMER'}});fireEvent.change(screen.getByLabelText('Email'),{target:{value:'new@example.test'}});fireEvent.change(screen.getByLabelText('Requested date and time'),{target:{value:'2030-01-01T10:00'}});fireEvent.click(screen.getByText('Send unconfirmed request'));await screen.findByText('Request saved');expect(posts).toHaveLength(1);expect(posts[0]!.authorization).toBe('Bearer '+token);expect(posts[0]!.body.customer.name).toBe('NEW_CUSTOMER');
});
it('keeps the committed A form usable when a B transition render is abandoned',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});const posts:any[]=[];vi.stubGlobal('fetch',vi.fn(async(url:string,options:RequestInit)=>{if(url.includes('/sessions'))return sessionResponse('Original service');posts.push(JSON.parse(options.body as string));return new Response(JSON.stringify({ok:true,data:{reference:'LMN-A',state:'draft',confirmed:false}}));}));
 const never=new Promise<void>(()=>{});
 function SuspendAfterFlow({target}:{target:string}){if(target===otherId)throw never;return null;}
 function View({target}:{target:string}){return <Suspense fallback={<p>Preparing other context</p>}><HostedFlow installationId={target} apiUrl="https://api.example"/><SuspendAfterFlow target={target}/></Suspense>;}
 const view=render(<View target={id}/>);await screen.findByText('Original service');fireEvent.change(screen.getByLabelText('Choose an option'),{target:{value:'a'}});fireEvent.change(screen.getByLabelText('Your name'),{target:{value:'Committed A'}});fireEvent.change(screen.getByLabelText('Email'),{target:{value:'a@example.test'}});fireEvent.change(screen.getByLabelText('Requested date and time'),{target:{value:'2030-01-01T10:00'}});
 await act(async()=>{startTransition(()=>view.rerender(<View target={otherId}/>));});
 expect(screen.getByText('Original service')).toBeTruthy();expect(screen.getByLabelText('Your name')).toHaveValue('Committed A');fireEvent.click(screen.getByText('Send unconfirmed request'));await screen.findByText('Request saved');expect(posts).toHaveLength(1);expect(posts[0].customer.name).toBe('Committed A');
});
