import {render,screen,fireEvent,waitFor,cleanup} from '@testing-library/react';
import {afterEach,it,expect,vi} from 'vitest';
import {HostedFlow} from './HostedFlow';
const id='11111111-1111-4111-8111-111111111111',token='t'.repeat(43);
const service={id,name:'Published service',durationMinutes:30,questions:[{id:'q',prompt:'Choose an option',kind:'single_choice',required:true,choices:[{id:'a',label:'Option A'}]}]};
const slotStart=new Date('2030-01-01T10:00').toISOString();
const availabilityResponse=(url:string)=>{const start=new Date(new URL(url).searchParams.get('from')!);start.setHours(10);return new Response(JSON.stringify({ok:true,data:{schemaVersion:1,serviceId:id,durationMinutes:30,slots:[{start:start.toISOString(),end:new Date(start.getTime()+1800000).toISOString(),remainingCapacity:1}]}}));};
const config={key:'request',steps:[{key:'q',questionKey:'q',kind:'question',required:true}]};
afterEach(()=>{cleanup();vi.unstubAllGlobals();});
it('uses pinned questions and identical body/key for ambiguous retry, never exposes token or confirmation',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});const bodies:string[]=[];const calls:RequestInit[]=[];
 vi.stubGlobal('fetch',vi.fn(async(url:string,options:RequestInit)=>{calls.push(options);if(url.includes('/availability'))return availabilityResponse(url);if(url.includes('/sessions'))return new Response(JSON.stringify({ok:true,data:{sessionToken:token,expiresAt:'2035-01-01T00:00:00Z',render:{versionId:id,config,service}}}));bodies.push(options.body as string);if(bodies.length===1)throw Error('connection interrupted with private-server-details');return new Response(JSON.stringify({ok:true,data:{reference:'LMN-TEST123',state:'draft',confirmed:false}}));}));
 render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await screen.findByText('Published service');fireEvent.change(screen.getByLabelText('Choose an option'),{target:{value:'a'}});fireEvent.change(screen.getByLabelText('Your name'),{target:{value:'Synthetic Person'}});fireEvent.change(screen.getByLabelText('Email'),{target:{value:'synthetic@example.test'}});fireEvent.change(screen.getByLabelText('Requested date'),{target:{value:'2030-01-01'}});await waitFor(()=>expect(screen.getByLabelText('Available time')).toBeEnabled());fireEvent.change(screen.getByLabelText('Available time'),{target:{value:slotStart}});fireEvent.click(screen.getByText('Send unconfirmed request'));await screen.findByText('Retry the same request');expect(screen.getByLabelText('Your name')).toBeDisabled();fireEvent.click(screen.getByText('Retry the same request'));await screen.findByText('Request saved');expect(bodies).toHaveLength(2);expect(JSON.parse(bodies[0]!).requestedStart).toBe(slotStart);expect(bodies[0]).toBe(bodies[1]);expect(JSON.parse(bodies[0]!)).not.toHaveProperty('tenantId');expect(JSON.parse(bodies[0]!)).not.toHaveProperty('serviceId');expect(calls[1]!.headers).toMatchObject({Authorization:'Bearer '+token});expect(document.body.textContent).not.toContain(token);expect(document.body.textContent).not.toContain('private-server-details');expect(screen.getByText(/Your request is unconfirmed/)).toBeTruthy();
});
it('does not create a customer session from an HTTP page',()=>{vi.stubGlobal('location',{protocol:'http:'});const fetcher=vi.fn();vi.stubGlobal('fetch',fetcher);render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);expect(screen.getByText('Secure customer page required')).toBeTruthy();expect(fetcher).not.toHaveBeenCalled();});
it('invalid installation IDs fail visibly without network calls',async()=>{vi.stubGlobal('location',{protocol:'https:'});const fetcher=vi.fn();vi.stubGlobal('fetch',fetcher);render(<HostedFlow installationId="bad?credential=unsafe" apiUrl="https://api.example"/>);await waitFor(()=>expect(screen.getByRole('alert')).toHaveTextContent('unavailable'));expect(fetcher).not.toHaveBeenCalled();});
it('V2 submits canonical pinned answers and omits newly hidden fields on an identical retry',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});const bodies:string[]=[];
 const v2={versionId:id,renderSchemaVersion:2,submissionMode:'unconfirmed_request',service:{...service,questions:[{id:'hasOwnProperty',prompt:'Mode',kind:'single_choice',required:true,choices:[{id:'toString',label:'More'},{id:'no',label:'Less'}]},{id:'quantity',prompt:'Extra amount',kind:'quantity',required:false,choices:[],minQty:0,maxQty:3},{id:'multi',prompt:'Extras',kind:'multi_choice',required:false,choices:[{id:'😀',label:'First'},{id:'é',label:'Second'}]}]},config:{key:'v2',steps:[{key:'mode',questionKey:'hasOwnProperty',kind:'question',required:true},{key:'quantity',questionKey:'quantity',kind:'question',required:true,visibleWhen:{field:'hasOwnProperty',op:'eq',value:'toString'}},{key:'multi',questionKey:'multi',kind:'question',required:false}]}};
 vi.stubGlobal('fetch',vi.fn(async(url:string,options:RequestInit)=>{if(url.includes('/availability'))return availabilityResponse(url);if(url.includes('/sessions'))return new Response(JSON.stringify({ok:true,data:{sessionToken:token,expiresAt:'2035-01-01T00:00:00Z',render:v2}}));bodies.push(options.body as string);if(bodies.length===1)throw Error('interrupted');return new Response(JSON.stringify({ok:true,data:{reference:'LMN-V2',state:'draft',confirmed:false}}));}));
 render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await screen.findByText('Published service');fireEvent.change(screen.getByLabelText('Mode'),{target:{value:'toString'}});fireEvent.change(screen.getByLabelText('Extra amount'),{target:{value:'2'}});fireEvent.change(screen.getByLabelText('Mode'),{target:{value:'no'}});fireEvent.click(screen.getByLabelText('Second'));fireEvent.click(screen.getByLabelText('First'));fireEvent.change(screen.getByLabelText('Your name'),{target:{value:'Synthetic Person'}});fireEvent.change(screen.getByLabelText('Email'),{target:{value:'synthetic@example.test'}});fireEvent.change(screen.getByLabelText('Requested date'),{target:{value:'2030-01-01'}});await waitFor(()=>expect(screen.getByLabelText('Available time')).toBeEnabled());fireEvent.change(screen.getByLabelText('Available time'),{target:{value:slotStart}});fireEvent.click(screen.getByText('Send unconfirmed request'));await screen.findByText('Retry the same request');fireEvent.click(screen.getByText('Retry the same request'));await screen.findByText('Request saved');expect(bodies[0]).toBe(bodies[1]);const body=JSON.parse(bodies[0]!);expect(body.answers).not.toHaveProperty('quantity');expect(body.answers.multi.choiceIds).toEqual(['😀','é']);expect(body.answers.hasOwnProperty.choiceIds).toEqual(['no']);expect(body).not.toHaveProperty('renderSchemaVersion');
});

it.each(['foreign service','wrong duration','invalid time'])('rejects %s availability without enabling submission',async(kind)=>{
 vi.stubGlobal('location',{protocol:'https:'});const submit=vi.fn();
 vi.stubGlobal('fetch',vi.fn(async(url:string)=>{if(url.includes('/availability'))return new Response(JSON.stringify({ok:true,data:{schemaVersion:1,serviceId:kind==='foreign service'?'22222222-2222-4222-8222-222222222222':id,durationMinutes:kind==='wrong duration'?60:30,slots:[{start:kind==='invalid time'?'invalid':slotStart,end:new Date(Date.parse(slotStart)+(kind==='wrong duration'?3600000:1800000)).toISOString(),remainingCapacity:1}]}}));if(url.includes('/sessions'))return new Response(JSON.stringify({ok:true,data:{sessionToken:token,expiresAt:'2035-01-01T00:00:00Z',render:{versionId:id,config,service}}}));submit();throw Error('unexpected');}));
 render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await screen.findByText('Published service');fireEvent.change(screen.getByLabelText('Requested date'),{target:{value:'2030-01-01'}});await screen.findByText('Retry available times');expect(screen.getByLabelText('Available time')).toBeDisabled();expect(screen.getByText('Send unconfirmed request')).toBeDisabled();expect(submit).not.toHaveBeenCalled();
});
it('clears selected slots immediately and discards responses for an earlier date',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});let resolve!:(response:Response)=>void;
 vi.stubGlobal('fetch',vi.fn(async(url:string)=>{if(url.includes('/availability')){if(new URL(url).searchParams.get('from')===new Date('2030-01-01T00:00').toISOString())return new Promise<Response>(r=>resolve=r);return availabilityResponse(url);}return new Response(JSON.stringify({ok:true,data:{sessionToken:token,expiresAt:'2035-01-01T00:00:00Z',render:{versionId:id,config,service}}}));}));
 render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await screen.findByText('Published service');fireEvent.change(screen.getByLabelText('Requested date'),{target:{value:'2030-01-01'}});await waitFor(()=>expect(resolve).toBeTypeOf('function'));fireEvent.change(screen.getByLabelText('Requested date'),{target:{value:'2030-01-02'}});await waitFor(()=>expect(screen.getByLabelText('Available time')).toBeEnabled());const next=new Date('2030-01-02T10:00').toISOString();fireEvent.change(screen.getByLabelText('Available time'),{target:{value:next}});resolve(availabilityResponse('https://api.example?from='+encodeURIComponent(new Date('2030-01-01T00:00').toISOString())));await waitFor(()=>expect(screen.getByLabelText('Available time')).toHaveValue(next));expect(Array.from((screen.getByLabelText('Available time') as HTMLSelectElement).options).map(option=>option.value)).toEqual(['',next]);
 fireEvent.change(screen.getByLabelText('Requested date'),{target:{value:''}});expect(screen.getByLabelText('Available time')).toHaveValue('');expect(screen.getByText('Send unconfirmed request')).toBeDisabled();
});
it('retries failed availability and shows an honest empty date',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});let attempts=0;
 vi.stubGlobal('fetch',vi.fn(async(url:string)=>{if(url.includes('/availability')){if(++attempts===1)throw Error('secret details');return new Response(JSON.stringify({ok:true,data:{schemaVersion:1,serviceId:id,durationMinutes:30,slots:[]}}));}return new Response(JSON.stringify({ok:true,data:{sessionToken:token,expiresAt:'2035-01-01T00:00:00Z',render:{versionId:id,config,service}}}));}));
 render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await screen.findByText('Published service');fireEvent.change(screen.getByLabelText('Requested date'),{target:{value:'2030-01-01'}});fireEvent.click(await screen.findByText('Retry available times'));await screen.findByText('No available times on this date. Choose another date.');expect(attempts).toBe(2);expect(screen.getByText('Send unconfirmed request')).toBeDisabled();expect(document.body.textContent).not.toContain('secret details');
});
it('blocks submission when a session expires after slots were loaded',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});const now=vi.spyOn(Date,'now').mockReturnValue(Date.parse('2029-12-01T00:00:00Z'));const sent=vi.fn();
 vi.stubGlobal('fetch',vi.fn(async(url:string)=>{if(url.includes('/availability'))return availabilityResponse(url);if(url.includes('/sessions'))return new Response(JSON.stringify({ok:true,data:{sessionToken:token,expiresAt:'2030-01-01T00:00:00Z',render:{versionId:id,config,service}}}));sent();throw Error('unexpected');}));
 try{render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await screen.findByText('Published service');fireEvent.change(screen.getByLabelText('Requested date'),{target:{value:'2030-01-01'}});await waitFor(()=>expect(screen.getByLabelText('Available time')).toBeEnabled());fireEvent.change(screen.getByLabelText('Available time'),{target:{value:slotStart}});now.mockReturnValue(Date.parse('2030-01-01T00:00:00Z'));fireEvent.submit(screen.getByText('Send unconfirmed request').closest('form')!);await screen.findAllByText('Your session expired. Reload this page to start again.');expect(sent).not.toHaveBeenCalled();expect(screen.getByText('Send unconfirmed request')).toBeDisabled();}finally{now.mockRestore();}
});
it('offers a cross-midnight slot from a full-day response while omitting next-day boundary starts',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});const {createAvailabilityEngine}=await import('@lumin/core');let expected:string[]=[];let crossMidnight='';
 vi.stubGlobal('fetch',vi.fn(async(url:string)=>{if(url.includes('/availability')){const query=new URL(url).searchParams,from=query.get('from')!,to=query.get('to')!;const browserZone=Intl.DateTimeFormat().resolvedOptions().timeZone;
 const tenantTimezone=browserZone==='America/Los_Angeles'?'Asia/Kolkata':'America/Los_Angeles';
 const slots=createAvailabilityEngine().getSlots({tenantTimezone,serviceId:id,durationMinutes:30,policy:{leadTimeMinutes:0,horizonDays:60,slotIntervalMinutes:15},rules:Array.from({length:7},(_,weekday)=>({id,tenantId:id,serviceId:id,weekday,startMinute:0,endMinute:1440,capacity:1})),overrides:[],existing:[],now:new Date(Date.parse(from)-86400000).toISOString(),from,to});
 expected=slots.filter(slot=>Date.parse(slot.start)<Date.parse(to)).map(slot=>slot.start);crossMidnight=slots.find(slot=>Date.parse(slot.start)<Date.parse(to)&&Date.parse(slot.end)>Date.parse(to))!.start;expect(slots.some(slot=>Date.parse(slot.start)===Date.parse(to))).toBe(true);
 return new Response(JSON.stringify({ok:true,data:{schemaVersion:1,serviceId:id,durationMinutes:30,slots}}));}return new Response(JSON.stringify({ok:true,data:{sessionToken:token,expiresAt:'2035-01-01T00:00:00Z',render:{versionId:id,config,service}}}));}));
 render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await screen.findByText('Published service');fireEvent.change(screen.getByLabelText('Requested date'),{target:{value:'2030-01-01'}});await waitFor(()=>expect(screen.getByLabelText('Available time')).toBeEnabled());const selector=screen.getByLabelText('Available time') as HTMLSelectElement;expect(Array.from(selector.options).slice(1).map(option=>option.value)).toEqual(expected);fireEvent.change(selector,{target:{value:crossMidnight}});expect(screen.getByText('Send unconfirmed request')).toBeEnabled();
});
async function saveRequest(){
 await screen.findByText('Published service');fireEvent.change(screen.getByLabelText('Choose an option'),{target:{value:'a'}});fireEvent.change(screen.getByLabelText('Your name'),{target:{value:'Synthetic Person'}});fireEvent.change(screen.getByLabelText('Email'),{target:{value:'synthetic@example.test'}});fireEvent.change(screen.getByLabelText('Requested date'),{target:{value:'2030-01-01'}});await waitFor(()=>expect(screen.getByLabelText('Available time')).toBeEnabled());fireEvent.change(screen.getByLabelText('Available time'),{target:{value:slotStart}});fireEvent.click(screen.getByText('Send unconfirmed request'));await screen.findByText('Request saved');
}
it('keeps a saved request visible during an ambiguous hold retry using the identical session and empty body',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});const holds:RequestInit[]=[];
 vi.stubGlobal('fetch',vi.fn(async(url:string,options:RequestInit)=>{
  if(url.endsWith('/hold')){holds.push(options);if(holds.length===1)throw Error('private failure');return new Response(JSON.stringify({ok:true,data:{bookingId:id,holdId:id,status:'active',expiresAt:'2030-01-01T10:05:00Z'}}));}
  if(url.includes('/availability'))return availabilityResponse(url);if(url.includes('/sessions'))return new Response(JSON.stringify({ok:true,data:{sessionToken:token,expiresAt:'2035-01-01T00:00:00Z',render:{versionId:id,config,service}}}));return new Response(JSON.stringify({ok:true,data:{reference:'LMN-HOLD',state:'draft',confirmed:false}}));
 }));
 render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await saveRequest();expect(holds).toHaveLength(0);fireEvent.click(screen.getByText('Reserve selected time'));await screen.findByText('Retry reservation of selected time');expect(screen.getByText('Request saved')).toBeTruthy();expect(screen.getByText('LMN-HOLD')).toBeTruthy();expect(screen.getByText(/No time was reserved/)).toBeTruthy();fireEvent.click(screen.getByText('Retry reservation of selected time'));await screen.findByText(/Selected time temporarily reserved until/);expect(holds).toHaveLength(2);expect(holds[0]!.body).toBe('{}');expect(holds[1]!.body).toBe(holds[0]!.body);expect(holds[0]!.headers).toEqual(holds[1]!.headers);expect(holds[0]!.headers).toMatchObject({Authorization:'Bearer '+token});expect(screen.getByText(/Your request is unconfirmed. No payment was taken/)).toBeTruthy();expect(screen.queryByText('Reserve selected time')).toBeNull();expect(document.body.textContent).not.toContain(token);expect(document.body.textContent).not.toContain('private failure');
});
it('keeps the saved request and refuses a hold after session expiry',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});const now=vi.spyOn(Date,'now').mockReturnValue(Date.parse('2029-12-01T00:00:00Z'));const held=vi.fn();
 vi.stubGlobal('fetch',vi.fn(async(url:string)=>{if(url.endsWith('/hold')){held();throw Error('unexpected');}if(url.includes('/availability'))return availabilityResponse(url);if(url.includes('/sessions'))return new Response(JSON.stringify({ok:true,data:{sessionToken:token,expiresAt:'2030-01-01T00:00:00Z',render:{versionId:id,config,service}}}));return new Response(JSON.stringify({ok:true,data:{reference:'LMN-EXPIRED',state:'draft',confirmed:false}}));}));
 try{render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await saveRequest();now.mockReturnValue(Date.parse('2030-01-01T00:00:00Z'));fireEvent.click(screen.getByText('Reserve selected time'));await screen.findByText('Your session expired. Your request remains saved. Reload this page to start again.');expect(held).not.toHaveBeenCalled();expect(screen.getByText('LMN-EXPIRED')).toBeTruthy();expect(screen.queryByRole('button',{name:'Reserve selected time'})).toBeNull();}finally{now.mockRestore();}
});
it('changes active hold wording when the temporary reservation expires',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});let expiresAt='';
 vi.stubGlobal('fetch',vi.fn(async(url:string)=>{if(url.endsWith('/hold')){expiresAt=new Date(Date.now()+150).toISOString();return new Response(JSON.stringify({ok:true,data:{bookingId:id,holdId:id,status:'active',expiresAt}}));}if(url.includes('/availability'))return availabilityResponse(url);if(url.includes('/sessions'))return new Response(JSON.stringify({ok:true,data:{sessionToken:token,expiresAt:'2035-01-01T00:00:00Z',render:{versionId:id,config,service}}}));return new Response(JSON.stringify({ok:true,data:{reference:'LMN-TEMP',state:'draft',confirmed:false}}));}));
 render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await saveRequest();fireEvent.click(screen.getByText('Reserve selected time'));await screen.findByText(/Selected time temporarily reserved until/);await screen.findByText('The temporary reservation expired. Your request remains saved and unconfirmed.');expect(screen.queryByText(/Selected time temporarily reserved until/)).toBeNull();expect(screen.getByText('LMN-TEMP')).toBeTruthy();
});
it('rejects an expired hold receipt without claiming a reservation',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});vi.stubGlobal('fetch',vi.fn(async(url:string)=>{if(url.endsWith('/hold'))return new Response(JSON.stringify({ok:true,data:{bookingId:id,holdId:id,status:'active',expiresAt:'2020-01-01T00:00:00Z'}}));if(url.includes('/availability'))return availabilityResponse(url);if(url.includes('/sessions'))return new Response(JSON.stringify({ok:true,data:{sessionToken:token,expiresAt:'2035-01-01T00:00:00Z',render:{versionId:id,config,service}}}));return new Response(JSON.stringify({ok:true,data:{reference:'LMN-OLD',state:'draft',confirmed:false}}));}));
 render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await saveRequest();fireEvent.click(screen.getByText('Reserve selected time'));await screen.findByText('Retry reservation of selected time');expect(screen.getByText('LMN-OLD')).toBeTruthy();expect(screen.queryByText(/Selected time temporarily reserved until/)).toBeNull();expect(screen.getByText(/No time was reserved/)).toBeTruthy();
});
it('discards a pending hold when the installation changes',async()=>{
 vi.stubGlobal('location',{protocol:'https:'});let resolve!:(response:Response)=>void;
 vi.stubGlobal('fetch',vi.fn(async(url:string)=>{if(url.endsWith('/hold'))return new Promise<Response>(r=>resolve=r);if(url.includes('/availability'))return availabilityResponse(url);if(url.includes('/sessions'))return new Response(JSON.stringify({ok:true,data:{sessionToken:token,expiresAt:'2035-01-01T00:00:00Z',render:{versionId:id,config,service}}}));return new Response(JSON.stringify({ok:true,data:{reference:'LMN-STALE',state:'draft',confirmed:false}}));}));
 const {rerender}=render(<HostedFlow installationId={id} apiUrl="https://api.example"/>);await saveRequest();fireEvent.click(screen.getByText('Reserve selected time'));await waitFor(()=>expect(resolve).toBeTypeOf('function'));rerender(<HostedFlow installationId="22222222-2222-4222-8222-222222222222" apiUrl="https://api.example"/>);await screen.findByText('Published service');resolve(new Response(JSON.stringify({ok:true,data:{bookingId:id,holdId:id,status:'active',expiresAt:'2030-01-01T10:05:00Z'}})));await waitFor(()=>expect(screen.queryByText(/Selected time temporarily reserved until/)).toBeNull());expect(screen.queryByText('LMN-STALE')).toBeNull();expect(screen.getByText('Send unconfirmed request')).toBeDisabled();
});
