import {useState} from 'react';
import {render,screen,fireEvent,cleanup} from '@testing-library/react';
import {afterEach,expect,it} from 'vitest';
import {type ConfigurableRender,type Answers} from '@lumin/flow-ui';
import {ConfigurablePreview} from './ConfigurablePreview';
const fixture:ConfigurableRender={versionId:'11111111-1111-4111-8111-111111111111',renderSchemaVersion:2,submissionMode:'unconfirmed_request',config:{key:'test',steps:[{key:'mode',questionKey:'mode',kind:'question',required:true},{key:'extras',questionKey:'extras',kind:'question',required:true,visibleWhen:{field:'mode',op:'eq',value:'yes'}},{key:'count',questionKey:'count',kind:'question',required:false}]},service:{id:'22222222-2222-4222-8222-222222222222',name:'Preview fixture',durationMinutes:30,questions:[{id:'mode',prompt:'Mode',kind:'single_choice',required:true,choices:[{id:'yes',label:'Yes'},{id:'no',label:'No'}]},{id:'extras',prompt:'Extras',kind:'multi_choice',required:false,choices:[{id:'one',label:'Extra one'}]},{id:'count',prompt:'Count',kind:'quantity',required:false,choices:[],minQty:1,maxQty:3}]}};
function Harness(){const[answers,setAnswers]=useState<Answers>({});return <ConfigurablePreview render={fixture} answers={answers} onChange={setAnswers}/>;}
const check=()=>fireEvent.click(screen.getByRole('button',{name:'Check these answers'}));
afterEach(cleanup);
it('uses native required validation then canonical validation; optional omission passes',()=>{render(<Harness/>);check();expect(screen.getByRole('alert')).toBeTruthy();expect(screen.getByLabelText('Mode')).toHaveFocus();fireEvent.change(screen.getByLabelText('Mode'),{target:{value:'no'}});check();expect(screen.getByRole('status')).toHaveTextContent('valid for this preview');});
it('conditional required checkbox fails until answered; hiding clears its answer',()=>{render(<Harness/>);fireEvent.change(screen.getByLabelText('Mode'),{target:{value:'yes'}});check();expect(screen.getByRole('alert')).toBeTruthy();fireEvent.click(screen.getByLabelText('Extra one'));check();expect(screen.getByRole('status')).toBeTruthy();fireEvent.change(screen.getByLabelText('Mode'),{target:{value:'no'}});expect(screen.queryByRole('status')).toBeNull();check();expect(screen.getByRole('status')).toBeTruthy();fireEvent.change(screen.getByLabelText('Mode'),{target:{value:'yes'}});expect(screen.getByLabelText('Extra one')).not.toBeChecked();check();expect(screen.getByRole('alert')).toBeTruthy();});
it.each(['0','4','1.5'])('rejects invalid quantity %s',value=>{render(<Harness/>);fireEvent.change(screen.getByLabelText('Mode'),{target:{value:'no'}});fireEvent.change(screen.getByLabelText('Count'),{target:{value}});check();expect(screen.getByRole('alert')).toBeTruthy();expect(screen.queryByRole('status')).toBeNull();});
it('reset clears answers and result',()=>{render(<Harness/>);fireEvent.change(screen.getByLabelText('Mode'),{target:{value:'no'}});check();fireEvent.click(screen.getByRole('button',{name:'Start preview again'}));expect(screen.getByLabelText('Mode')).toHaveValue('');expect(screen.queryByRole('status')).toBeNull();});
it('invalidates results synchronously when render changes and cannot resurrect them',()=>{const answers={mode:{choiceIds:['no']}};const view=render(<ConfigurablePreview render={fixture} answers={answers} onChange={()=>{}}/>);check();expect(screen.getByRole('status')).toBeTruthy();view.rerender(<ConfigurablePreview render={{...fixture,service:{...fixture.service,name:'Changed'}}} answers={answers} onChange={()=>{}}/>);expect(screen.queryByRole('status')).toBeNull();view.rerender(<ConfigurablePreview render={fixture} answers={answers} onChange={()=>{}}/>);expect(screen.queryByRole('status')).toBeNull();});
it('canonical validation rejects an injected unknown answer even when visible inputs are valid',()=>{render(<ConfigurablePreview render={fixture} answers={{mode:{choiceIds:['no']},unexpected:{quantity:1}}} onChange={()=>{}}/>);check();expect(screen.getByRole('alert')).toBeTruthy();expect(screen.queryByRole('status')).toBeNull();});