import {afterEach,expect,it,vi} from 'vitest';
import {act,cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {FieldDraftV2Editor} from './FieldDraftV2Editor';
import type {FieldDraftV2Client} from '../../../../packages/flow-ui/src/fieldDraftV2Client';
const layoutControl=vi.hoisted(()=>({suppress:false}));
vi.mock('react',async importOriginal=>{const actual=await importOriginal<typeof import('react')>();return {...actual,useLayoutEffect:(effect:()=>void|(()=>void),deps?:readonly unknown[])=>actual.useLayoutEffect(()=>layoutControl.suppress?undefined:effect(),deps)};});
afterEach(()=>{layoutControl.suppress=false;cleanup();});
const field={key:'question_a',kind:'text' as const,prompt:'Original',required:false,minLength:0,maxLength:100};
const receipt=()=>({fieldDraftVersion:2 as const,parentAuthoringVersion:2 as const,draftRevision:1,savedParentRevision:1,currentParentRevision:1,runtimePublishable:false as const,stale:false,definition:{schemaVersion:2 as const,fields:[field]}});
function setup(){const client:FieldDraftV2Client={read:vi.fn().mockResolvedValue({status:'present',receipt:receipt()}),save:vi.fn().mockResolvedValue({...receipt(),draftRevision:2}),invalidate:vi.fn()};return {client,props:{client,token:'synthetic',tenant:'tenant',flowId:'flow',parentRevision:1,parentDirty:false,enabled:true,onDirtyChange:vi.fn(),onBusyChange:vi.fn()}};}
async function load(){fireEvent.click(screen.getByText('Load questions'));await screen.findByLabelText('Question label');}
it('writes a mixed V2 definition with exact metadata and both revision tokens',async()=>{const {client,props}=setup();render(<FieldDraftV2Editor {...props}/>);await load();fireEvent.change(screen.getByLabelText('Answer format'),{target:{value:'textarea'}});fireEvent.change(screen.getByLabelText('Question label'),{target:{value:'  <b>Question</b>  '}});fireEvent.click(screen.getByText('Save questions'));await waitFor(()=>expect(client.save).toHaveBeenCalledTimes(1));expect(vi.mocked(client.save).mock.calls[0]?.[3]).toEqual({fieldDraftVersion:2,parentAuthoringVersion:2,expectedRevision:1,expectedFlowRevision:1,definition:{schemaVersion:2,fields:[{...field,kind:'textarea',prompt:'  <b>Question</b>  '}]}});});
it('rejects blank labels and invalid character limits without transport',async()=>{const {client,props}=setup();render(<FieldDraftV2Editor {...props}/>);await load();fireEvent.change(screen.getByLabelText('Question label'),{target:{value:'   '}});expect(screen.getByText('Save questions')).toBeDisabled();fireEvent.change(screen.getByLabelText('Question label'),{target:{value:'Fine'}});fireEvent.change(screen.getByLabelText('Minimum characters'),{target:{value:'200'}});expect(screen.getByText('Save questions')).toBeDisabled();expect(client.save).not.toHaveBeenCalled();});
it('preserves edits after conflict and never retries automatically',async()=>{const {client,props}=setup();vi.mocked(client.save).mockRejectedValue({code:'CONFLICT'});render(<FieldDraftV2Editor {...props}/>);await load();fireEvent.change(screen.getByLabelText('Question label'),{target:{value:'Keep me'}});fireEvent.click(screen.getByText('Save questions'));await screen.findByText(/Questions changed elsewhere/);expect(screen.getByLabelText('Question label')).toHaveValue('Keep me');expect(screen.getByText('Save questions')).toBeDisabled();expect(client.save).toHaveBeenCalledTimes(1);});
it('requires explicit latest read and stale acknowledgement after parent changes',async()=>{const {client,props}=setup();const view=render(<FieldDraftV2Editor {...props}/>);await load();view.rerender(<FieldDraftV2Editor {...props} parentRevision={2}/>);expect(screen.getByText('Save questions')).toBeDisabled();vi.mocked(client.read).mockResolvedValue({status:'present',receipt:{...receipt(),currentParentRevision:2,stale:true}});fireEvent.click(screen.getByText('Check latest version'));const ack=await screen.findByLabelText('I reviewed these questions for the updated booking flow.');expect(screen.getByText('Save questions')).toBeDisabled();fireEvent.click(ack);expect(screen.getByText('Save questions')).not.toBeDisabled();});
it('fences late context reads and immediately hides previous fields',async()=>{const {client,props}=setup();const view=render(<FieldDraftV2Editor {...props}/>);await load();let resolve!:(v:any)=>void;vi.mocked(client.read).mockImplementationOnce(()=>new Promise(r=>resolve=r));fireEvent.click(screen.getByText('Reload questions'));view.rerender(<FieldDraftV2Editor {...props} tenant="other"/>);expect(screen.queryByLabelText('Question label')).toBeNull();await act(async()=>resolve({status:'present',receipt:receipt()}));expect(screen.queryByLabelText('Question label')).toBeNull();expect(client.invalidate).toHaveBeenCalled();});
it('reports dirty and busy immediately to replacement observers',async()=>{const {client,props}=setup();const view=render(<FieldDraftV2Editor {...props}/>);await load();fireEvent.change(screen.getByLabelText('Question label'),{target:{value:'Edited'}});let resolve!:(v:any)=>void;vi.mocked(client.save).mockImplementationOnce(()=>new Promise(r=>resolve=r));fireEvent.click(screen.getByText('Save questions'));const dirty=vi.fn(),busy=vi.fn();view.rerender(<FieldDraftV2Editor {...props} onDirtyChange={dirty} onBusyChange={busy}/>);expect(dirty).toHaveBeenLastCalledWith(true);expect(busy).toHaveBeenLastCalledWith(true);await act(async()=>resolve({...receipt(),draftRevision:2}));});
it('disabled capability and unsaved parent prevent all reads',()=>{const {client,props}=setup();const view=render(<FieldDraftV2Editor {...props} enabled={false}/>);expect(screen.queryByText('Load questions')).toBeNull();view.rerender(<FieldDraftV2Editor {...props} parentDirty/>);expect(screen.getByText('Load questions')).toBeDisabled();expect(client.read).not.toHaveBeenCalled();});

it('new context observers never receive old dirty or busy state',async()=>{const {client,props}=setup();const view=render(<FieldDraftV2Editor {...props}/>);await load();fireEvent.change(screen.getByLabelText('Question label'),{target:{value:'Edited'}});let resolve!:(v:any)=>void;vi.mocked(client.save).mockImplementationOnce(()=>new Promise(r=>resolve=r));fireEvent.click(screen.getByText('Save questions'));const dirty=vi.fn(),busy=vi.fn();view.rerender(<FieldDraftV2Editor {...props} tenant="new" onDirtyChange={dirty} onBusyChange={busy}/>);expect(dirty.mock.calls.every(([v])=>v===false)).toBe(true);expect(busy.mock.calls.every(([v])=>v===false)).toBe(true);expect(screen.queryByLabelText('Question label')).toBeNull();await act(async()=>resolve({...receipt(),draftRevision:2}));expect(screen.queryByLabelText('Question label')).toBeNull();});

it('render itself hides old status and busy before new context layout effects',async()=>{const {client,props}=setup();const view=render(<FieldDraftV2Editor {...props}/>);await load();let resolve!:(v:any)=>void;vi.mocked(client.read).mockImplementationOnce(()=>new Promise(r=>resolve=r));fireEvent.click(screen.getByText('Reload questions'));expect(screen.getByRole('status').textContent).not.toBe('');layoutControl.suppress=true;view.rerender(<FieldDraftV2Editor {...props} tenant="different"/>);expect(screen.getByRole('status').textContent).toBe('');expect(screen.getByText('Load questions')).not.toBeDisabled();expect(screen.queryByLabelText('Question label')).toBeNull();layoutControl.suppress=false;await act(async()=>resolve({status:'present',receipt:receipt()}));});
it('new context reports its own loading and failure status after reset',async()=>{const {client,props}=setup();const view=render(<FieldDraftV2Editor {...props}/>);await load();view.rerender(<FieldDraftV2Editor {...props} tenant="new"/>);let reject!:(e:Error)=>void;vi.mocked(client.read).mockImplementationOnce(()=>new Promise((_,r)=>reject=r));fireEvent.click(screen.getByText('Load questions'));expect(screen.getByRole('status').textContent).not.toBe('');await act(async()=>reject(new Error('private error')));expect(screen.getByRole('status')).toHaveTextContent('Questions could not be loaded. Try again.');expect(screen.queryByText('private error')).toBeNull();});
