import {afterEach,expect,it,vi} from 'vitest';
import {act,cleanup,fireEvent,render,screen,within,waitFor} from '@testing-library/react';
import {FieldDraftV2Editor} from './FieldDraftV2Editor';
import type {FieldDraftV2Client} from '../../../../packages/flow-ui/src/fieldDraftV2Client';
afterEach(cleanup);
const field={key:'question',kind:'textarea' as const,prompt:'Instructions',required:true,minLength:1,maxLength:50};
const receipt={fieldDraftVersion:2 as const,parentAuthoringVersion:2 as const,draftRevision:1,savedParentRevision:1,currentParentRevision:1,runtimePublishable:false as const,stale:false,definition:{schemaVersion:2 as const,fields:[field]}};
function setup(){const client:FieldDraftV2Client={read:vi.fn().mockResolvedValue({status:'present',receipt}),save:vi.fn().mockResolvedValue({...receipt,draftRevision:2}),invalidate:vi.fn()};const props={client,token:'synthetic',tenant:'tenant',flowId:'flow',parentRevision:1,parentDirty:false,enabled:true,onDirtyChange:vi.fn(),onBusyChange:vi.fn()};return {client,props};}
const preview=()=>screen.getByRole('region',{name:'Question preview'});
async function open(){fireEvent.click(screen.getByText('Load questions'));await screen.findByLabelText('Question label');fireEvent.click(screen.getByText('Try questions'));}
it('rehearses long answers without dirty notifications or transport and excludes answers from save',async()=>{const {client,props}=setup();render(<FieldDraftV2Editor {...props}/>);await open();const dirty=props.onDirtyChange.mock.calls.length,busy=props.onBusyChange.mock.calls.length;fireEvent.change(within(preview()).getByLabelText('Instructions'),{target:{value:'First\nSecond'}});fireEvent.click(within(preview()).getByText('Check answers'));expect(within(preview()).getByRole('status')).toHaveTextContent('Nothing was submitted.');expect(props.onDirtyChange).toHaveBeenCalledTimes(dirty);expect(props.onBusyChange).toHaveBeenCalledTimes(busy);expect(client.read).toHaveBeenCalledTimes(1);expect(client.save).not.toHaveBeenCalled();fireEvent.click(screen.getByText('Save questions'));await waitFor(()=>expect(client.save).toHaveBeenCalledTimes(1));expect(vi.mocked(client.save).mock.calls[0]?.[3]).toEqual({fieldDraftVersion:2,parentAuthoringVersion:2,expectedRevision:1,expectedFlowRevision:1,definition:receipt.definition});expect(screen.queryByRole('region',{name:'Question preview'})).toBeNull();});
it('closing and reopening discards rehearsal values',async()=>{const {props}=setup();render(<FieldDraftV2Editor {...props}/>);await open();fireEvent.change(within(preview()).getByLabelText('Instructions'),{target:{value:'Private answer'}});fireEvent.click(screen.getByText('Close preview'));fireEvent.click(screen.getByText('Try questions'));expect(within(preview()).getByLabelText('Instructions')).toHaveValue('');});
it('edit and revert never revive old answers even with equivalent definition',async()=>{const {props}=setup();render(<FieldDraftV2Editor {...props}/>);await open();fireEvent.change(within(preview()).getByLabelText('Instructions'),{target:{value:'Private'}});fireEvent.change(screen.getByLabelText('Question label'),{target:{value:'Changed'}});expect(screen.queryByRole('region',{name:'Question preview'})).toBeNull();fireEvent.change(screen.getByLabelText('Question label'),{target:{value:'Instructions'}});expect(screen.queryByRole('region',{name:'Question preview'})).toBeNull();fireEvent.click(screen.getByText('Try questions'));expect(within(preview()).getByLabelText('Instructions')).toHaveValue('');});
it('parent dirty transition hides preview and does not reopen when eligible again',async()=>{const {props}=setup();const view=render(<FieldDraftV2Editor {...props}/>);await open();view.rerender(<FieldDraftV2Editor {...props} parentDirty/>);expect(screen.queryByRole('region',{name:'Question preview'})).toBeNull();expect(screen.getByText('Try questions')).toBeDisabled();view.rerender(<FieldDraftV2Editor {...props}/>);expect(screen.queryByRole('region',{name:'Question preview'})).toBeNull();expect(screen.getByText('Try questions')).not.toBeDisabled();});
it('failed latest check retires preview until explicitly reopened',async()=>{const {client,props}=setup();render(<FieldDraftV2Editor {...props}/>);await open();let reject!:(e:Error)=>void;vi.mocked(client.read).mockImplementationOnce(()=>new Promise((_,r)=>reject=r));fireEvent.click(screen.getByText('Check latest version'));expect(screen.queryByRole('region',{name:'Question preview'})).toBeNull();expect(screen.getByText('Try questions')).toBeDisabled();await act(async()=>reject(new Error('internal')));expect(screen.queryByRole('region',{name:'Question preview'})).toBeNull();expect(screen.getByText('Try questions')).not.toBeDisabled();});
it('invalid definition and stale unacknowledged parent cannot open preview',async()=>{const {client,props}=setup();vi.mocked(client.read).mockResolvedValue({status:'present',receipt:{...receipt,stale:true,savedParentRevision:1,currentParentRevision:2}});render(<FieldDraftV2Editor {...props} parentRevision={2}/>);fireEvent.click(screen.getByText('Load questions'));await screen.findByLabelText('Question label');expect(screen.getByText('Try questions')).toBeDisabled();fireEvent.click(screen.getByLabelText('I reviewed these questions for the updated booking flow.'));expect(screen.getByText('Try questions')).not.toBeDisabled();fireEvent.change(screen.getByLabelText('Question label'),{target:{value:''}});expect(screen.getByText('Try questions')).toBeDisabled();});
it('parent revision away and back requires a fresh blank preview',async()=>{const {props}=setup();const view=render(<FieldDraftV2Editor {...props}/>);await open();fireEvent.change(within(preview()).getByLabelText('Instructions'),{target:{value:'Private'}});view.rerender(<FieldDraftV2Editor {...props} parentRevision={2}/>);expect(screen.queryByRole('region',{name:'Question preview'})).toBeNull();expect(screen.getByText('Try questions')).toBeDisabled();view.rerender(<FieldDraftV2Editor {...props}/>);expect(screen.queryByRole('region',{name:'Question preview'})).toBeNull();fireEvent.click(screen.getByText('Try questions'));expect(within(preview()).getByLabelText('Instructions')).toHaveValue('');});
