import {afterEach,expect,it,vi} from 'vitest';
import {createRuntimeClient} from './index';
const T='a1111111-1111-4111-8111-111111111111',B='b2222222-2222-4222-8222-222222222222',U='33333333-3333-4333-8333-333333333333',F='44444444-4444-4444-8444-444444444444';
const receipt={schemaVersion:1,tenantId:T,bookingId:B,status:'recorded',provenance:{flowId:U,versionId:F,renderSchemaVersion:6,draftRevision:1},answers:[{fieldId:'custom_access',label:'Pinned entry instructions',value:'<img src=x onerror=alert(1)>'},{fieldId:'custom_note',label:'Pinned notes',value:' Gate 12 '}]};
const json=(value:unknown,status=200)=>new Response(JSON.stringify(value),{status});
function deferred<T>(){let resolve!:(value:T)=>void,reject!:(error:Error)=>void;const promise=new Promise<T>((r,j)=>{resolve=r;reject=j;});return{promise,resolve,reject};}
function fixture({members=[{tenant_id:T,role:'BUSINESS_OWNER'}],reply=async()=>json({ok:true,data:receipt}),membershipRead,apiOrigin='https://api.example.test'}:{members?:unknown;reply?:(options?:RequestInit)=>Promise<Response>;membershipRead?:(options?:RequestInit)=>Promise<Response>;apiOrigin?:string}={}){
 let actor=U;const transport=vi.fn<typeof fetch>(async(input,options)=>{const path=String(input);if(path.includes('/token?'))return json({access_token:'synthetic-owner-private-token'});if(path.endsWith('/user'))return json({id:actor});if(path.includes('/tenant_members?'))return membershipRead?membershipRead(options):json(members);if(path.includes('/api/booking-form-answers?'))return reply(options);throw Error('Unexpected transport');});
 const client=createRuntimeClient({url:'https://example.supabase.co',publishableKey:'sb_publishable_fixture',tenantId:T,allowMembershipDiscovery:true,...(apiOrigin?{bookingApiOrigin:apiOrigin}:{})},transport);return{transport,client,actor:(id:string)=>{actor=id;}};
}
const calls=(x:ReturnType<typeof fixture>)=>x.transport.mock.calls.filter(([url])=>String(url).includes('/api/booking-form-answers?'));
afterEach(()=>{vi.useRealTimers();vi.restoreAllMocks();});
it('uses fresh owner membership and exact authenticated GET, preserves pinned order and freezes output',async()=>{const x=fixture();await x.client.signIn('owner@example.test','synthetic');const result=await x.client.readBookingFormAnswers(T.toUpperCase(),B.toUpperCase());expect(result).toEqual(receipt);expect(calls(x)[0]).toEqual(['https://api.example.test/api/booking-form-answers?tenantId='+T+'&bookingId='+B,expect.objectContaining({method:'GET',credentials:'omit',cache:'no-store',redirect:'error',referrerPolicy:'no-referrer',headers:{Authorization:'Bearer synthetic-owner-private-token'},signal:expect.any(AbortSignal)})]);expect(calls(x)[0]![1]).not.toHaveProperty('body');expect(Object.isFrozen(result)).toBe(true);expect(Object.isFrozen(result.answers)).toBe(true);expect(Object.isFrozen(result.provenance)).toBe(true);expect(result.answers.every(Object.isFrozen)).toBe(true);});
it('never automatically reads or submits a booking and rejects invalid scopes before transport',async()=>{const x=fixture();await expect(x.client.readBookingFormAnswers(T,B)).rejects.toMatchObject({code:'UNAUTHENTICATED'});expect(x.transport).not.toHaveBeenCalled();await x.client.signIn('owner@example.test','synthetic');for(const [t,b] of [[T+'&role=owner',B],[T,B+'&actor='+U],['forged',B],[T,'forged']])await expect(x.client.readBookingFormAnswers(t!,b!)).rejects.toMatchObject({code:'INVALID_REQUEST'});expect(calls(x)).toHaveLength(0);});
it('requires configured API origin',async()=>{const x=fixture({apiOrigin:''});await x.client.signIn('owner@example.test','synthetic');await expect(x.client.readBookingFormAnswers(T,B)).rejects.toMatchObject({code:'UNAUTHENTICATED'});expect(calls(x)).toHaveLength(0);});
it.each([[],[{tenant_id:T,role:'BUSINESS_STAFF'}],[{tenant_id:F,role:'BUSINESS_OWNER'}],[{tenant_id:T,role:'BUSINESS_OWNER',extra:true}]].map(members=>({members})))('blocks nonowner/foreign/malformed fresh membership',async({members})=>{const x=fixture({members});await x.client.signIn('owner@example.test','synthetic');await expect(x.client.readBookingFormAnswers(T,B)).rejects.toMatchObject({code:'FORBIDDEN'});expect(calls(x)).toHaveLength(0);});
it('checks fresh membership on every refresh and stops after revocation',async()=>{let members=[{tenant_id:T,role:'BUSINESS_OWNER'}];const x=fixture({membershipRead:async()=>json(members)});await x.client.signIn('owner@example.test','synthetic');await x.client.readBookingFormAnswers(T,B);members=[];await expect(x.client.readBookingFormAnswers(T,B)).rejects.toMatchObject({code:'FORBIDDEN'});expect(calls(x)).toHaveLength(1);});
it.each(['not_recorded','unsupported'])('preserves explicit %s without inventing an answer',async status=>{const data={schemaVersion:1,tenantId:T,bookingId:B,status,provenance:null,answers:[]};const x=fixture({reply:async()=>json({ok:true,data})});await x.client.signIn('owner@example.test','synthetic');expect(await x.client.readBookingFormAnswers(T,B)).toEqual(data);});
it.each([{...receipt,tenantId:F},{...receipt,bookingId:F},{...receipt,sessionToken:'PRIVATE'},{...receipt,provenance:{...receipt.provenance,requestHash:'PRIVATE'}},{...receipt,answers:[...receipt.answers,receipt.answers[0]]},{...receipt,answers:[{...receipt.answers[0],value:'bad\ntext'}]},{...receipt,answers:[{...receipt.answers[0],value:'x'.repeat(1001)}]},{...receipt,answers:[{...receipt.answers[0],fieldId:'custom_price'}]}])('rejects foreign, malformed and private/widened DTOs',async data=>{const x=fixture({reply:async()=>json({ok:true,data})});await x.client.signIn('owner@example.test','synthetic');await expect(x.client.readBookingFormAnswers(T,B)).rejects.toMatchObject({code:'UNVERIFIED'});expect(calls(x)).toHaveLength(1);});
it.each([[403,'FORBIDDEN'],[404,'NOT_AVAILABLE'],[422,'UNSUPPORTED_CONFIG']] as const)('preserves sanitized API status %s/%s',async(status,code)=>{const x=fixture({reply:async()=>json({ok:false,code},status)});await x.client.signIn('owner@example.test','synthetic');await expect(x.client.readBookingFormAnswers(T,B)).rejects.toMatchObject({code});});
it('clears only the current expired auth on 401',async()=>{const x=fixture({reply:async()=>json({ok:false,code:'UNAUTHENTICATED'},401)});await x.client.signIn('owner@example.test','synthetic');await expect(x.client.readBookingFormAnswers(T,B)).rejects.toMatchObject({code:'UNAUTHENTICATED'});await expect(x.client.readBookingFormAnswers(T,B)).rejects.toMatchObject({code:'UNAUTHENTICATED'});expect(calls(x)).toHaveLength(1);});
it('aborts a never-settling API transport on context change without clearing replacement auth',async()=>{const pendingResponse=deferred<Response>();let signal:AbortSignal|undefined;const x=fixture({reply:options=>{signal=options?.signal??undefined;return pendingResponse.promise;}});await x.client.signIn('owner@example.test','synthetic');const pending=x.client.readBookingFormAnswers(T,B).catch(error=>error);await vi.waitFor(()=>expect(signal).toBeDefined());x.client.signOut();await x.client.signIn('owner@example.test','synthetic');const revision=x.client.authContextRevision();expect(signal!.aborted).toBe(true);expect(await pending).toMatchObject({code:'STALE_CONTEXT'});pendingResponse.resolve(json({ok:false,code:'UNAUTHENTICATED'},401));await Promise.resolve();expect(x.client.authContextRevision()).toBe(revision);expect(calls(x)).toHaveLength(1);});
it.each(['membership','response','body'] as const)('caller cancellation aborts %s and consumes late resolution/rejection',async phase=>{const held=deferred<any>();let signal:AbortSignal|undefined;const response=json({ok:true,data:receipt});if(phase==='body')vi.spyOn(response,'json').mockImplementation(()=>held.promise);const x=fixture({...(phase==='membership'?{membershipRead:(options?:RequestInit)=>{signal=options?.signal??undefined;return held.promise;}}:{reply:async(options?:RequestInit)=>{signal=options?.signal??undefined;return phase==='response'?held.promise:response;}})});await x.client.signIn('owner@example.test','synthetic');const controller=new AbortController(),pending=x.client.readBookingFormAnswers(T,B,controller.signal).catch(error=>error);await vi.waitFor(()=>expect(signal).toBeDefined());if(phase==='body')await vi.waitFor(()=>expect(response.json).toHaveBeenCalled());controller.abort();expect(await pending).toMatchObject({code:'ABORTED'});expect(signal!.aborted).toBe(true);held.reject(Error('PRIVATE_LATE_ERROR'));await Promise.resolve();expect(calls(x)).toHaveLength(phase==='membership'?0:1);});
it('already cancelled caller causes no membership or answer read',async()=>{const x=fixture();await x.client.signIn('owner@example.test','synthetic');const before=x.transport.mock.calls.length,c=new AbortController();c.abort();await expect(x.client.readBookingFormAnswers(T,B,c.signal)).rejects.toMatchObject({code:'ABORTED'});expect(x.transport).toHaveBeenCalledTimes(before);});
it.each(['response','body'] as const)('bounded read deadline aborts nonsettling %s without retry',async phase=>{const held=deferred<any>();let signal:AbortSignal|undefined;const response=json({ok:true,data:receipt});if(phase==='body')vi.spyOn(response,'json').mockImplementation(()=>held.promise);const x=fixture({reply:async options=>{signal=options?.signal??undefined;return phase==='response'?held.promise:response;}});await x.client.signIn('owner@example.test','synthetic');vi.useFakeTimers();const pending=x.client.readBookingFormAnswers(T,B).catch(error=>error);await vi.advanceTimersByTimeAsync(14999);expect(signal!.aborted).toBe(false);await vi.advanceTimersByTimeAsync(1);expect(await pending).toMatchObject({code:'UNVERIFIED'});expect(signal!.aborted).toBe(true);held.resolve(phase==='body'?{ok:true,data:receipt}:response);await vi.advanceTimersByTimeAsync(30000);expect(calls(x)).toHaveLength(1);expect(vi.getTimerCount()).toBe(0);});
it('sanitizes membership/transport/body failures and makes no automatic retries',async()=>{for(const stage of ['membership','transport','body']){const response=json({ok:true,data:receipt});if(stage==='body')vi.spyOn(response,'json').mockRejectedValue(Error('PRIVATE_BODY'));const x=fixture({...(stage==='membership'?{membershipRead:async()=>{throw Error('PRIVATE_MEMBERSHIP');}}:{reply:async()=>{if(stage==='transport')throw Error('PRIVATE_NETWORK');return response;}})});await x.client.signIn('owner@example.test','synthetic');const error=await x.client.readBookingFormAnswers(T,B).catch(value=>value);expect(error.code).toBe('UNVERIFIED');expect(error.message).not.toContain('PRIVATE');expect(calls(x)).toHaveLength(stage==='membership'?0:1);}});
