import {describe,it,expect,vi} from 'vitest';
import {createServer} from 'node:http';
import {createRuntimeClient} from './index';
const T='11111111-1111-4111-8111-111111111111',U='22222222-2222-4222-8222-222222222222',F='33333333-3333-4333-8333-333333333333',A='44444444-4444-4444-8444-444444444444',B='55555555-5555-4555-8555-555555555555',I='66666666-6666-4666-8666-666666666666';
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status});
const journey={schemaVersion:1,stages:['service','options','schedule','information','review_payment','confirmation'].map(kind=>({id:kind,kind,label:kind,enabled:true}))};
const publication={versionId:A,installationId:I,renderSchemaVersion:8,hostedPath:'/checkout/flow/'+I};
const history=()=>({schemaVersion:1,tenantId:T,flowId:F,versions:[{versionId:B,draftRevision:2,name:'Current',journey,presentation:{accentColor:'#4f46e5',layout:'stacked'},current:true,publication:{...publication,versionId:B}},{versionId:A,draftRevision:1,name:'Prior',journey,presentation:{accentColor:'#4f46e5',layout:'compact'},current:false,publication}]});
const input={expectedCurrentVersionId:B,targetVersionId:A};
const receipt=()=>({schemaVersion:1,tenantId:T,flowId:F,draftRevision:1,...publication});
async function fixture(){const f=vi.fn<typeof fetch>().mockResolvedValueOnce(json({access_token:'fixture'})).mockResolvedValueOnce(json({id:U}));const c=createRuntimeClient({url:'https://example.supabase.co',publishableKey:'sb_publishable_synthetic',tenantId:T,bookingApiOrigin:'https://api.example.test'},f);await c.signIn('fixture@example.test','fixture');return {c,f};}
async function ready(){const {c,f}=await fixture();f.mockResolvedValueOnce(json({ok:true,data:history()}));await c.paidJourneyVersionHistory(T,F);return {c,f};}
describe('explicit authenticated V8 history and rollback',()=>{
 it('uses actual fetch for one owner history read and one exact CAS POST',async()=>{const seen:Array<{path:string;method:string;authorization:string|undefined;body:string}>=[];const server=createServer((req,res)=>{let body='';req.on('data',chunk=>body+=chunk);req.on('end',()=>{seen.push({path:req.url!,method:req.method!,authorization:req.headers.authorization,body});res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify({ok:true,data:req.method==='GET'?history():receipt()}));});});await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const address=server.address();if(!address||typeof address==='string')throw Error('Missing isolated listener');const f:typeof fetch=async(url,init)=>String(url).includes('/auth/v1/token')?json({access_token:'fixture'}):String(url).endsWith('/auth/v1/user')?json({id:U}):fetch('http://127.0.0.1:'+address.port+new URL(String(url)).pathname+new URL(String(url)).search,init);try{const c=createRuntimeClient({url:'https://example.supabase.co',publishableKey:'sb_publishable_synthetic',tenantId:T,bookingApiOrigin:'https://api.example.test'},f);await c.signIn('fixture@example.test','fixture');await c.paidJourneyVersionHistory(T,F);await c.rollbackPaidJourney(T,F,input);expect(seen).toEqual([{path:'/api/paid-journey-flows/'+F+'/versions?tenantId='+T,method:'GET',authorization:'Bearer fixture',body:''},{path:'/api/paid-journey-flows/'+F+'/rollback?tenantId='+T,method:'POST',authorization:'Bearer fixture',body:JSON.stringify(input)}]);}finally{server.closeAllConnections();await new Promise<void>(resolve=>server.close(()=>resolve()));}});
 it('reads bounded immutable history with auth transport and sends only explicit CAS identities',async()=>{const {c,f}=await ready();f.mockResolvedValueOnce(json({ok:true,data:receipt()}));const result=await c.rollbackPaidJourney(T,F,input);expect(result).toEqual(receipt());expect(Object.isFrozen(result)).toBe(true);expect(c.paidJourneyRollbackState(T)).toEqual({phase:'verified',receipt:receipt()});expect(f.mock.calls[2]).toEqual(['https://api.example.test/api/paid-journey-flows/'+F+'/versions?tenantId='+T,expect.objectContaining({method:'GET',credentials:'omit',cache:'no-store',redirect:'error',headers:{Authorization:'Bearer fixture'}})]);expect(f.mock.calls[3]?.[1]?.body).toBe(JSON.stringify(input));expect(f.mock.calls[3]?.[1]?.method).toBe('POST');});
 it.each(['tenant','flow','order','duplicate','two-current','no-current','extra','schema','path','foreign-install','journey','too-many'])('rejects malformed %s history without granting rollback',async(kind)=>{const {c,f}=await fixture();const h:any=structuredClone(history());if(kind==='tenant')h.tenantId=U;if(kind==='flow')h.flowId=U;if(kind==='order')h.versions.reverse();if(kind==='duplicate')h.versions[1].versionId=B;if(kind==='two-current')h.versions[1].current=true;if(kind==='no-current')h.versions[0].current=false;if(kind==='extra')h.secret='forbidden';if(kind==='schema')h.versions[1].publication.renderSchemaVersion=6;if(kind==='path')h.versions[1].publication.hostedPath='https://evil.example/';if(kind==='foreign-install')h.versions[1].publication.versionId=B;if(kind==='journey')h.versions[1].journey.stages=[];if(kind==='too-many')h.versions=Array(51).fill(h.versions[0]);f.mockResolvedValueOnce(json({ok:true,data:h}));await expect(c.paidJourneyVersionHistory(T,F)).rejects.toMatchObject({delivery:'not_sent'});await expect(c.rollbackPaidJourney(T,F,input)).rejects.toMatchObject({delivery:'not_sent'});expect(f).toHaveBeenCalledTimes(3);});
 it.each(['tenant','flow','revision','installation','version','path','extra','legacy'])('retains uncertainty for forged %s rollback receipt',async(kind)=>{const {c,f}=await ready();const r:any=receipt();if(kind==='tenant')r.tenantId=U;if(kind==='flow')r.flowId=U;if(kind==='revision')r.draftRevision=2;if(kind==='installation')r.installationId=U;if(kind==='version')r.versionId=B;if(kind==='path')r.hostedPath='/checkout/flow/'+U;if(kind==='extra')r.amount=1;if(kind==='legacy')r.renderSchemaVersion=6;f.mockResolvedValueOnce(json({ok:true,data:r}));await expect(c.rollbackPaidJourney(T,F,input)).rejects.toMatchObject({delivery:'unknown'});expect(c.paidJourneyRollbackState(T).phase).toBe('unknown');await expect(c.rollbackPaidJourney(T,F,input)).rejects.toMatchObject({delivery:'not_sent'});expect(f).toHaveBeenCalledTimes(4);});
 it('requires fresh owner history and never trusts a caller-supplied installation or amount',async()=>{const {c,f}=await fixture();await expect(c.rollbackPaidJourney(T,F,input)).rejects.toMatchObject({delivery:'not_sent'});f.mockResolvedValueOnce(json({ok:true,data:history()}));await c.paidJourneyVersionHistory(T,F);for(const extra of [{...input,amount:1},{...input,installationId:I},{...input,targetVersionId:B},{...input,expectedCurrentVersionId:A}])await expect(c.rollbackPaidJourney(T,F,extra)).rejects.toMatchObject({delivery:'not_sent'});expect(f).toHaveBeenCalledTimes(3);});
 it('blocks double click and other owner writes, and does not change customer payment state',async()=>{const {c,f}=await ready();let finish!:(r:Response)=>void;f.mockImplementationOnce(()=>new Promise(done=>finish=done));const pending=c.rollbackPaidJourney(T,F,input);await expect(c.rollbackPaidJourney(T,F,input)).rejects.toMatchObject({delivery:'not_sent'});await expect(c.loadPaidJourneyDraft(T,F)).rejects.toMatchObject({delivery:'not_sent'});expect(c.paidJourneyPaymentState()).toEqual({phase:'ready'});finish(json({ok:true,data:receipt()}));await pending;expect(f).toHaveBeenCalledTimes(4);});
 it('allows explicit read after transport loss but never clears or attributes uncertain rollback',async()=>{const {c,f}=await ready();f.mockRejectedValueOnce(Error('lost credential must not print'));await expect(c.rollbackPaidJourney(T,F,input)).rejects.toMatchObject({delivery:'unknown'});const restored=history();restored.versions[0]!.current=false;restored.versions[1]!.current=true;f.mockResolvedValueOnce(json({ok:true,data:restored}));expect(await c.paidJourneyVersionHistory(T,F)).toEqual(restored);expect(c.paidJourneyRollbackState(T).phase).toBe('unknown');await expect(c.rollbackPaidJourney(T,F,{expectedCurrentVersionId:A,targetVersionId:B})).rejects.toMatchObject({delivery:'not_sent'});expect(f).toHaveBeenCalledTimes(5);});
 it.each(['abort','auth','redirect'])('late %s rollback success is not accepted and is never retried',async(kind)=>{const {c,f}=await ready();const controller=new AbortController();let finish!:(r:Response)=>void;f.mockImplementationOnce(()=>new Promise(done=>finish=done));const pending=c.rollbackPaidJourney(T,F,input,{signal:controller.signal});if(kind==='abort')controller.abort();if(kind==='auth')c.signOut();const r=json({ok:true,data:receipt()});if(kind==='redirect')Object.defineProperty(r,'redirected',{value:true});finish(r);await expect(pending).rejects.toMatchObject({delivery:'unknown'});expect(c.paidJourneyRollbackState(T).phase).toBe(kind==='auth'?'ready':'unknown');expect(f).toHaveBeenCalledTimes(4);});
 it('A-B-A authentication cannot revive a late rollback or cached history',async()=>{const {c,f}=await ready();let finish!:(r:Response)=>void;f.mockImplementationOnce(()=>new Promise(done=>finish=done));const pending=c.rollbackPaidJourney(T,F,input);for(const actor of [T,U]){c.signOut();expect(c.paidJourneyRollbackState(T)).toEqual({phase:'ready'});f.mockResolvedValueOnce(json({access_token:'new'})).mockResolvedValueOnce(json({id:actor}));await c.signIn('fixture@example.test','fixture');if(actor===T)expect(c.paidJourneyRollbackState(T)).toEqual({phase:'ready'});}finish(json({ok:true,data:receipt()}));await expect(pending).rejects.toMatchObject({delivery:'unknown'});expect(c.paidJourneyRollbackState(T).phase).toBe('unknown');await expect(c.rollbackPaidJourney(T,F,input)).rejects.toMatchObject({delivery:'not_sent'});});
 it('definite CAS conflict releases its own lock but requires a fresh read',async()=>{const {c,f}=await ready();f.mockResolvedValueOnce(json({ok:false,code:'CONFLICT'},409));await expect(c.rollbackPaidJourney(T,F,input)).rejects.toMatchObject({delivery:'rejected'});expect(c.paidJourneyRollbackState(T)).toEqual({phase:'ready'});await expect(c.rollbackPaidJourney(T,F,input)).rejects.toMatchObject({delivery:'not_sent'});f.mockResolvedValueOnce(json({ok:true,data:history()}));await c.paidJourneyVersionHistory(T,F);f.mockResolvedValueOnce(json({ok:true,data:receipt()}));await c.rollbackPaidJourney(T,F,input);expect(f).toHaveBeenCalledTimes(6);});
 it('pre-abort prevents dispatch and a read abort cannot cache authority',async()=>{const {c,f}=await fixture();const pre=new AbortController();pre.abort();await expect(c.paidJourneyVersionHistory(T,F,{signal:pre.signal})).rejects.toMatchObject({delivery:'not_sent'});expect(f).toHaveBeenCalledTimes(2);let finish!:(r:Response)=>void;const late=new AbortController();f.mockImplementationOnce(()=>new Promise(done=>finish=done));const pending=c.paidJourneyVersionHistory(T,F,{signal:late.signal});late.abort();finish(json({ok:true,data:history()}));await expect(pending).rejects.toMatchObject({delivery:'not_sent'});await expect(c.rollbackPaidJourney(T,F,input)).rejects.toMatchObject({delivery:'not_sent'});});
 it('a failed refresh invalidates previously cached rollback selection',async()=>{const {c,f}=await ready();f.mockResolvedValueOnce(json({ok:true,data:{...history(),tenantId:U}}));await expect(c.paidJourneyVersionHistory(T,F)).rejects.toMatchObject({delivery:'not_sent'});await expect(c.rollbackPaidJourney(T,F,input)).rejects.toMatchObject({delivery:'not_sent'});expect(f).toHaveBeenCalledTimes(4);});
 it('owner A-B-A cannot reuse an earlier history as rollback authority',async()=>{const {c,f}=await ready();for(const actor of [T,U]){c.signOut();f.mockResolvedValueOnce(json({access_token:'new'})).mockResolvedValueOnce(json({id:actor}));await c.signIn('fixture@example.test','fixture');}await expect(c.rollbackPaidJourney(T,F,input)).rejects.toMatchObject({delivery:'not_sent'});expect(f).toHaveBeenCalledTimes(7);});
});
