import {describe,it,expect,vi} from 'vitest';
import {createServer} from 'node:http';
import {createRuntimeClient,type PaidJourneyCustomerFieldDraftInput} from './index';
const T='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',F='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',U='cccccccc-cccc-4ccc-8ccc-cccccccccccc',S='dddddddd-dddd-4ddd-8ddd-dddddddddddd';
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status});
const form=()=>({name:'Connected fields',presentation:{accentColor:'#4f46e5' as const,layout:'stacked' as const},journey:{schemaVersion:1 as const,stages:(['service','options','schedule','information','review_payment','confirmation'] as const).map(kind=>({id:kind,kind,label:kind,enabled:true}))},customerFields:[{id:'custom_access',kind:'text' as const,label:'Access',required:false,maxLength:40}],fieldBindings:[{fieldId:'custom_access',stageId:'information'}]});
const input=(revision=0):PaidJourneyCustomerFieldDraftInput=>({schemaVersion:2,serviceId:S,expectedRevision:revision,form:form()});
const receipt=(revision=1)=>({schemaVersion:2,tenantId:T,flowId:F,revision});
const loaded=(revision=1)=>({...receipt(revision),serviceId:S,form:form()});
async function fixture(){const f=vi.fn<typeof fetch>().mockResolvedValueOnce(json({access_token:'fixture'})).mockResolvedValueOnce(json({id:U}));const c=createRuntimeClient({url:'https://example.supabase.co',publishableKey:'sb_publishable_synthetic',tenantId:T,bookingApiOrigin:'https://api.example.test'},f);await c.signIn('fixture@example.test','fixture');return {c,f};}
describe('dedicated conditional journey draft SDK',()=>{
 it('captures exact immutable body before caller mutation and sends only dedicated owner-authoring request',async()=>{const {c,f}=await fixture(),v=input();let finish!:(r:Response)=>void;f.mockImplementationOnce(()=>new Promise(done=>finish=done));const pending=c.savePaidJourneyCustomerFieldDraft(T.toUpperCase(),F.toUpperCase(),v);(v.form as any).customerFields[0].label='Changed';expect(c.paidJourneyCustomerFieldDraftState(T)).toEqual({phase:'saving',flowId:F});const request=f.mock.calls[2]!;expect(request[0]).toBe('https://api.example.test/api/paid-journey-customer-field-flows/'+F+'/draft?tenantId='+T);expect(request[1]).toMatchObject({method:'POST',credentials:'omit',cache:'no-store',redirect:'error',headers:{Authorization:'Bearer fixture','Content-Type':'application/json'}});expect(JSON.parse(request[1]!.body as string).form.customerFields[0].label).toBe('Access');finish(json({ok:true,data:receipt()}));expect(await pending).toEqual(receipt());expect(c.paidJourneyCustomerFieldDraftState(T)).toEqual({phase:'saved',flowId:F,revision:1});});
 it('loads immutable strict form and increments only observed revision',async()=>{const {c,f}=await fixture();f.mockResolvedValueOnce(json({ok:true,data:loaded(4)}));const draft=await c.loadPaidJourneyCustomerFieldDraft(T,F);expect(Object.isFrozen(draft.form.customerFields[0])).toBe(true);f.mockResolvedValueOnce(json({ok:true,data:receipt(5)}));await c.savePaidJourneyCustomerFieldDraft(T,F,input(4));expect(c.paidJourneyCustomerFieldDraftState(T)).toEqual({phase:'saved',flowId:F,revision:5});});
 it.each(['tenant','flow','revision','schema','extra','legacy'])('uncertain %s receipt cannot be repeated or replaced',async(kind)=>{const {c,f}=await fixture(),r:any=receipt();if(kind==='tenant')r.tenantId=U;if(kind==='flow')r.flowId=U;if(kind==='revision')r.revision=2;if(kind==='schema')r.schemaVersion=1;if(kind==='extra')r.secret='must not print';if(kind==='legacy'){delete r.tenantId;delete r.schemaVersion;}f.mockResolvedValueOnce(json({ok:true,data:r}));await expect(c.savePaidJourneyCustomerFieldDraft(T,F,input())).rejects.toMatchObject({delivery:'unknown'});await expect(c.savePaidJourneyCustomerFieldDraft(T,F,input())).rejects.toMatchObject({delivery:'not_sent'});await expect(c.savePaidJourneyDraft(T,F,{schemaVersion:1,expectedRevision:0,serviceId:S,name:'Old',presentation:form().presentation,journey:form().journey})).rejects.toMatchObject({delivery:'not_sent'});expect(c.paidJourneyPaymentState()).toEqual({phase:'ready'});expect(f).toHaveBeenCalledTimes(3);});
 it.each(['foreign','extra','binding','canonical','legacy'])('rejects %s read result without granting save authority',async(kind)=>{const {c,f}=await fixture(),r:any=loaded();if(kind==='foreign')r.tenantId=U;if(kind==='extra')r.private='hidden';if(kind==='binding')r.form.fieldBindings=[];if(kind==='canonical')r.serviceId=S.toUpperCase();if(kind==='legacy')r.schemaVersion=1;f.mockResolvedValueOnce(json({ok:true,data:r}));await expect(c.loadPaidJourneyCustomerFieldDraft(T,F)).rejects.toMatchObject({delivery:'unknown'});await expect(c.savePaidJourneyCustomerFieldDraft(T,F,input(1))).rejects.toMatchObject({delivery:'not_sent'});expect(f).toHaveBeenCalledTimes(3);});
 it.each(['lost','json','redirect'])('retains private uncertainty after %s transport outcome and explicit read never clears it',async(kind)=>{const {c,f}=await fixture();if(kind==='lost')f.mockRejectedValueOnce(Error('private bearer must not print'));else {const r=json({ok:true,data:receipt()});if(kind==='json')vi.spyOn(r,'json').mockRejectedValue(Error('private'));else Object.defineProperty(r,'redirected',{value:true});f.mockResolvedValueOnce(r);}const error=await c.savePaidJourneyCustomerFieldDraft(T,F,input()).catch(error=>error);expect(error.delivery).toBe('unknown');expect(error.message).not.toContain('bearer');f.mockResolvedValueOnce(json({ok:true,data:loaded()}));expect(await c.loadPaidJourneyCustomerFieldDraft(T,F)).toEqual(loaded());expect(c.paidJourneyCustomerFieldDraftState(T)).toEqual({phase:'unverified',flowId:F});await expect(c.savePaidJourneyCustomerFieldDraft(T,F,input(1))).rejects.toMatchObject({delivery:'not_sent'});expect(f).toHaveBeenCalledTimes(4);});
 it('double click and reload cannot race the first save or alter financial state',async()=>{const {c,f}=await fixture();let finish!:(r:Response)=>void;f.mockImplementationOnce(()=>new Promise(done=>finish=done));const pending=c.savePaidJourneyCustomerFieldDraft(T,F,input());await expect(c.savePaidJourneyCustomerFieldDraft(T,F,input())).rejects.toMatchObject({delivery:'not_sent'});await expect(c.loadPaidJourneyCustomerFieldDraft(T,F)).rejects.toMatchObject({delivery:'not_sent'});await expect(c.setServiceActive(T,S,false)).rejects.toThrow();expect(c.paidJourneyHoldState()).toEqual({phase:'ready'});finish(json({ok:true,data:receipt()}));await pending;expect(f).toHaveBeenCalledTimes(3);});
 it('CAS conflict permits a fresh read but not blind retry',async()=>{const {c,f}=await fixture();f.mockResolvedValueOnce(json({ok:false,code:'CONFLICT'},409));await expect(c.savePaidJourneyCustomerFieldDraft(T,F,input())).rejects.toMatchObject({delivery:'conflict'});await expect(c.savePaidJourneyCustomerFieldDraft(T,F,input())).rejects.toMatchObject({delivery:'not_sent'});f.mockResolvedValueOnce(json({ok:true,data:loaded(2)}));await c.loadPaidJourneyCustomerFieldDraft(T,F);f.mockResolvedValueOnce(json({ok:true,data:receipt(3)}));await c.savePaidJourneyCustomerFieldDraft(T,F,input(2));expect(f).toHaveBeenCalledTimes(5);});
 it('A-B-A never exposes other actor uncertainty or accepts old late success',async()=>{const {c,f}=await fixture();let finish!:(r:Response)=>void;f.mockImplementationOnce(()=>new Promise(done=>finish=done));const pending=c.savePaidJourneyCustomerFieldDraft(T,F,input());for(const actor of [S,U]){c.signOut();expect(c.paidJourneyCustomerFieldDraftState(T)).toEqual({phase:'ready'});f.mockResolvedValueOnce(json({access_token:'new'})).mockResolvedValueOnce(json({id:actor}));await c.signIn('fixture@example.test','fixture');if(actor===S){expect(c.paidJourneyCustomerFieldDraftState(T)).toEqual({phase:'ready'});await expect(c.loadPaidJourneyCustomerFieldDraft(T,F)).rejects.toMatchObject({delivery:'not_sent'});}}finish(json({ok:true,data:receipt()}));await expect(pending).rejects.toMatchObject({delivery:'unknown'});expect(c.paidJourneyCustomerFieldDraftState(T)).toEqual({phase:'unverified',flowId:F});await expect(c.setServiceActive(T,S,false)).rejects.toThrow();});
 it('401 read does not reconcile an earlier unknown save',async()=>{const {c,f}=await fixture();f.mockRejectedValueOnce(Error('lost'));await expect(c.savePaidJourneyCustomerFieldDraft(T,F,input())).rejects.toMatchObject({delivery:'unknown'});f.mockResolvedValueOnce(json({ok:false,code:'UNAUTHENTICATED'},401));await expect(c.loadPaidJourneyCustomerFieldDraft(T,F)).rejects.toMatchObject({delivery:'rejected'});expect(c.paidJourneyCustomerFieldDraftState(T)).toEqual({phase:'ready'});f.mockResolvedValueOnce(json({access_token:'new'})).mockResolvedValueOnce(json({id:U}));await c.signIn('fixture@example.test','fixture');expect(c.paidJourneyCustomerFieldDraftState(T).phase).toBe('unverified');});
 it('another unknown owner writer cannot be replaced by reading or saving the new field draft',async()=>{const {c,f}=await fixture();f.mockRejectedValueOnce(Error('lost'));await expect(c.savePaidJourneyDraft(T,F,{schemaVersion:1,expectedRevision:0,serviceId:S,name:'Old',presentation:form().presentation,journey:form().journey})).rejects.toMatchObject({delivery:'unknown'});f.mockResolvedValueOnce(json({ok:true,data:loaded()}));await c.loadPaidJourneyCustomerFieldDraft(T,F);await expect(c.savePaidJourneyCustomerFieldDraft(T,F,input(1))).rejects.toMatchObject({delivery:'not_sent'});expect(c.paidJourneyDraftState(T).phase).toBe('unverified');expect(f).toHaveBeenCalledTimes(4);});
 it('rejects widened input, version confusion and financial effects before dispatch',async()=>{const {c,f}=await fixture();for(const v of [{...input(),schemaVersion:1},{...input(),amount:1},{...input(),form:{...form(),price:1}},{...input(),form:{...form(),customerFields:[{...form().customerFields[0],pricingEffect:1}]}},{...input(),form:{...form(),fieldBindings:[]}}])await expect(c.savePaidJourneyCustomerFieldDraft(T,F,v as any)).rejects.toMatchObject({delivery:'not_sent'});expect(f).toHaveBeenCalledTimes(2);});
 it('unknown field draft also fences generic booking RPC without dispatch',async()=>{const {c,f}=await fixture();f.mockRejectedValueOnce(Error('lost'));await expect(c.savePaidJourneyCustomerFieldDraft(T,F,input())).rejects.toMatchObject({delivery:'unknown'});await expect(c.saveDraft({serviceId:S,idempotencyKey:'synthetic-attempt-001',slotStart:'2026-10-09T09:00:00Z',slotEnd:'2026-10-09T10:00:00Z',customer:{name:'Synthetic',email:'synthetic@example.test'}})).rejects.toThrow();expect(f).toHaveBeenCalledTimes(3);});
 it('pending conditional draft read fences other writers until the read finishes',async()=>{const {c,f}=await fixture();let finish!:(r:Response)=>void;f.mockImplementationOnce(()=>new Promise(done=>finish=done));const pending=c.loadPaidJourneyCustomerFieldDraft(T,F);await expect(c.savePaidJourneyDraft(T,F,{schemaVersion:1,expectedRevision:0,serviceId:S,name:'Old',presentation:form().presentation,journey:form().journey})).rejects.toMatchObject({delivery:'not_sent'});await expect(c.setServiceActive(T,S,false)).rejects.toThrow();finish(json({ok:true,data:loaded()}));await pending;expect(f).toHaveBeenCalledTimes(3);});
 it('actual fetch exercises only dedicated draft POST and read paths',async()=>{const seen:Array<{method:string;path:string;body:string}>=[];const server=createServer((req,res)=>{let body='';req.on('data',chunk=>body+=chunk);req.on('end',()=>{seen.push({method:req.method!,path:req.url!,body});res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify({ok:true,data:req.method==='POST'?receipt():loaded()}));});});await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const address=server.address();if(!address||typeof address==='string')throw Error('Listener unavailable');const f:typeof fetch=async(url,init)=>String(url).includes('/auth/v1/token')?json({access_token:'fixture'}):String(url).endsWith('/auth/v1/user')?json({id:U}):fetch('http://127.0.0.1:'+address.port+new URL(String(url)).pathname+new URL(String(url)).search,init);try{const c=createRuntimeClient({url:'https://example.supabase.co',publishableKey:'sb_publishable_synthetic',tenantId:T,bookingApiOrigin:'https://api.example.test'},f);await c.signIn('fixture@example.test','fixture');await c.savePaidJourneyCustomerFieldDraft(T,F,input());await c.loadPaidJourneyCustomerFieldDraft(T,F);expect(seen.map(r=>[r.method,r.path])).toEqual([['POST','/api/paid-journey-customer-field-flows/'+F+'/draft?tenantId='+T],['GET','/api/paid-journey-customer-field-flows/'+F+'/draft?tenantId='+T]]);expect(JSON.parse(seen[0]!.body)).toEqual(input());}finally{server.closeAllConnections();await new Promise<void>(resolve=>server.close(()=>resolve()));}});
});
