import {describe,expect,it,vi} from 'vitest';
import {createRuntimeClient} from './index';
import {createServer} from 'node:http';
const T='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',I='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',V='cccccccc-cccc-4ccc-8ccc-cccccccccccc',S='dddddddd-dddd-4ddd-8ddd-dddddddddddd';
const origin='https://checkout.example.test';
const form=()=>({name:'Cleaning',presentation:{accentColor:'#0e7490',layout:'compact'},journey:{schemaVersion:1,stages:['service','options','schedule','information','review_payment','confirmation'].map(kind=>({id:kind,kind,label:kind,enabled:kind!=='options'}))},customerFields:[{id:'custom_gate',kind:'text',label:'Gate',required:false,maxLength:100}],fieldBindings:[{fieldId:'custom_gate',stageId:'information'}]});
const render=()=>({versionId:V,renderSchemaVersion:9,submissionMode:'paid_journey_customer_field_request',paymentMode:'staging_mock',simulated:true,service:{id:S,name:'Cleaning',durationMinutes:60,price:{amount:12500,currency:'USD'}},form:form()});
const session=()=>({schemaVersion:2 as const,installationId:I,sessionToken:Buffer.alloc(32).toString('base64url'),expiresAt:new Date(Date.now()+900000).toISOString(),render:render()});
const projection=(s=session())=>({schemaVersion:2,installationId:s.installationId,expiresAt:s.expiresAt,render:s.render});
const json=(value:unknown,status=200)=>new Response(JSON.stringify(value),{status,headers:{'content-type':'application/json'}});
const fixture=()=>{const fetch=vi.fn<typeof globalThis.fetch>(),c=createRuntimeClient({url:'https://example.supabase.co',publishableKey:'sb_publishable_fixture',tenantId:T,bookingApiOrigin:'https://api.example.test'},fetch);return{c,fetch};};
describe('private V9 session read SDK',()=>{
 it('reads exact token-bound GET with no owner credentials and returns only immutable public projection',async()=>{const {c,fetch}=fixture(),s=session();fetch.mockResolvedValueOnce(json({ok:true,data:projection(s)}));const read=await c.readPaidJourneyCustomerFieldSession(s as never,{origin});expect(read).toEqual(projection(s));expect(Object.isFrozen(read.render.form)).toBe(true);expect(JSON.stringify(read)).not.toContain(s.sessionToken);expect(fetch).toHaveBeenCalledExactlyOnceWith('https://api.example.test/api/public/paid-journey-customer-field-flow-sessions/render',{method:'GET',credentials:'omit',cache:'no-store',redirect:'error',referrerPolicy:'no-referrer',headers:{Origin:origin,Authorization:'Bearer '+s.sessionToken}});expect(c.paidJourneyCustomerFieldSessionState()).toEqual({phase:'ready'});});
 it.each(['*',origin+'/', 'http://checkout.example.test'])('rejects invalid origin %s before dispatch',async origin=>{const {c,fetch}=fixture();await expect(c.readPaidJourneyCustomerFieldSession(session() as never,{origin})).rejects.toMatchObject({code:'INVALID_REQUEST'});expect(fetch).not.toHaveBeenCalled();});
 it('rejects getters, inherited, symbol and hidden authority without invoking getters',async()=>{const {c,fetch}=fixture(),getter=vi.fn(()=>origin),s=session();for(const options of [Object.create({origin}),{get origin(){return getter();}},{origin,[Symbol('authority')]:true},Object.defineProperty({origin},'hidden',{value:true})])await expect(c.readPaidJourneyCustomerFieldSession(s as never,options as never)).rejects.toMatchObject({code:'INVALID_REQUEST'});await expect(c.readPaidJourneyCustomerFieldSession({...s,get sessionToken(){return getter();}} as never,{origin})).rejects.toMatchObject({code:'INVALID_REQUEST'});expect(getter).not.toHaveBeenCalled();expect(fetch).not.toHaveBeenCalled();});
 it.each(['schema','token','expired','date','ttl'])('denies incompatible input %s before dispatch',async mode=>{const {c,fetch}=fixture(),s=session();const bad=mode==='schema'?{...s,schemaVersion:1}:mode==='token'?{...s,sessionToken:s.sessionToken.slice(0,-1)+'B'}:mode==='expired'?{...s,expiresAt:new Date(Date.now()-1).toISOString()}:mode==='date'?{...s,expiresAt:'2030-02-31T00:00:00Z'}:{...s,expiresAt:new Date(Date.now()+902000).toISOString()};await expect(c.readPaidJourneyCustomerFieldSession(bad as never,{origin})).rejects.toThrow();expect(fetch).not.toHaveBeenCalled();});
 it.each(['tenantId','flowId','publicationGeneration','tokenHash','sessionToken'])('rejects internal projection %s with no leakage',async key=>{const {c,fetch}=fixture(),s=session();fetch.mockResolvedValueOnce(json({ok:true,data:{...projection(s),[key]:'private'}}));await expect(c.readPaidJourneyCustomerFieldSession(s as never,{origin})).rejects.toMatchObject({code:'UNVERIFIED'});expect(fetch).toHaveBeenCalledTimes(1);});
 it.each(['installation','expiry','price','version','form','envelope','legacy'])('rejects changed pinned %s',async mode=>{const {c,fetch}=fixture(),s=session(),p=projection(s);const data=mode==='installation'?{...p,installationId:S}:mode==='expiry'?{...p,expiresAt:new Date(Date.parse(s.expiresAt)+1).toISOString()}:mode==='price'?{...p,render:{...p.render,service:{...p.render.service,price:{amount:1,currency:'USD'}}}}:mode==='version'?{...p,render:{...p.render,versionId:S}}:mode==='form'?{...p,render:{...p.render,form:{...p.render.form,name:'Changed'}}}:mode==='legacy'?{...p,schemaVersion:1}:p;fetch.mockResolvedValueOnce(json(mode==='envelope'?{ok:true,data,extra:true}:{ok:true,data}));await expect(c.readPaidJourneyCustomerFieldSession(s as never,{origin})).rejects.toMatchObject({code:'UNVERIFIED'});});
 it('captures immutable request input while response is pending and aborts without dispatch when already canceled',async()=>{const {c,fetch}=fixture(),s=session(),options={origin};const abort=new AbortController();abort.abort();await expect(c.readPaidJourneyCustomerFieldSession(s as never,{origin,signal:abort.signal})).rejects.toMatchObject({code:'ABORTED'});expect(fetch).not.toHaveBeenCalled();let finish!:(v:unknown)=>void;const response=json({});vi.spyOn(response,'json').mockImplementation(()=>new Promise(resolve=>finish=resolve));fetch.mockResolvedValueOnce(response);const expected=JSON.parse(JSON.stringify(projection(s))),read=c.readPaidJourneyCustomerFieldSession(s as never,options);await Promise.resolve();options.origin='https://changed.example.test';s.render.form.name='Changed';finish({ok:true,data:expected});await expect(read).resolves.toEqual(expected);expect((fetch.mock.calls[0]![1]!.headers as Record<string,string>).Origin).toBe(origin);});
 it.each(['abort','auth','expiry','overlap'])('rejects delayed response on %s context change',async mode=>{const {c,fetch}=fixture(),s=session(),controller=new AbortController();let finish!:(v:unknown)=>void;const response=json({});vi.spyOn(response,'json').mockImplementation(()=>new Promise(resolve=>finish=resolve));fetch.mockResolvedValueOnce(response);const read=c.readPaidJourneyCustomerFieldSession(s as never,{origin,signal:controller.signal});await Promise.resolve();let clock:ReturnType<typeof vi.spyOn>|undefined;if(mode==='abort')controller.abort();if(mode==='auth')c.signOut();if(mode==='expiry')clock=vi.spyOn(Date,'now').mockReturnValue(Date.parse(s.expiresAt));if(mode==='overlap'){fetch.mockResolvedValueOnce(json({ok:true,data:projection(s)}));await c.readPaidJourneyCustomerFieldSession(s as never,{origin});}finish({ok:true,data:projection(s)});try{await expect(read).rejects.toMatchObject({code:mode==='abort'?'ABORTED':mode==='expiry'?'EXPIRED':'STALE_CONTEXT'});}finally{clock?.mockRestore();}});
 it('safe read never settles pending/unknown issuance or enables legacy writes',async()=>{const {c,fetch}=fixture(),s=session();let finish!:(v:unknown)=>void;const response=json({});vi.spyOn(response,'json').mockImplementation(()=>new Promise(resolve=>finish=resolve));fetch.mockResolvedValueOnce(response);const issue=c.issuePaidJourneyCustomerFieldSession(I,{origin});await Promise.resolve();fetch.mockResolvedValueOnce(json({ok:true,data:projection(s)}));await c.readPaidJourneyCustomerFieldSession(s as never,{origin});expect(c.paidJourneyCustomerFieldSessionState().phase).toBe('issuing');finish({ok:true,data:{}});await expect(issue).rejects.toMatchObject({delivery:'unknown'});fetch.mockResolvedValueOnce(json({ok:true,data:projection(s)}));await c.readPaidJourneyCustomerFieldSession(s as never,{origin});expect(c.paidJourneyCustomerFieldSessionState()).toEqual({phase:'unknown'});await expect(c.issuePaidJourneySession(I)).rejects.toMatchObject({delivery:'not_sent'});expect(fetch).toHaveBeenCalledTimes(3);});
 it('public 401 preserves owner context, never retries and never reports provider text',async()=>{const {c,fetch}=fixture(),s=session();fetch.mockResolvedValueOnce(json({access_token:'private'})).mockResolvedValueOnce(json({id:T}));await c.signIn('fixture@example.test','fixture');const revision=c.authContextRevision();fetch.mockResolvedValueOnce(json({private:'provider secret'},401));await expect(c.readPaidJourneyCustomerFieldSession(s as never,{origin})).rejects.toMatchObject({code:'REJECTED'});expect(c.authContextRevision()).toBe(revision);expect(fetch).toHaveBeenCalledTimes(3);});
 it('actual HTTP delayed body rejects account A-B-A and does not expose tokens in state',async()=>{const s=session();let began!:()=>void,finish!:()=>void;const started=new Promise<void>(resolve=>began=resolve);let calls=0;const server=createServer((req,res)=>{calls++;expect(req.method).toBe('GET');expect(req.url).toBe('/api/public/paid-journey-customer-field-flow-sessions/render');expect(req.headers.origin).toBe(origin);expect(req.headers.authorization).toBe('Bearer '+s.sessionToken);expect(req.headers.apikey).toBeUndefined();res.writeHead(200,{'content-type':'application/json'});res.write('{"ok":true,"data":');finish=()=>res.end(JSON.stringify(projection(s))+'}');began();});await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const address=server.address();if(!address||typeof address==='string')throw Error('Loopback unavailable');let actor=T;const transport:typeof fetch=async(url,init)=>String(url).includes('/auth/v1/token')?json({access_token:'private'}):String(url).endsWith('/auth/v1/user')?json({id:actor}):fetch('http://127.0.0.1:'+address.port+new URL(String(url)).pathname,init);try{const c=createRuntimeClient({url:'https://example.supabase.co',publishableKey:'sb_publishable_fixture',tenantId:T,bookingApiOrigin:'https://api.example.test'},transport);await c.signIn('fixture@example.test','fixture');const read=c.readPaidJourneyCustomerFieldSession(s as never,{origin});await started;for(const id of [S,T]){actor=id;await c.signIn('fixture@example.test','fixture');}finish();await expect(read).rejects.toMatchObject({code:'STALE_CONTEXT'});expect(calls).toBe(1);expect(JSON.stringify(c.paidJourneyCustomerFieldSessionState())).not.toContain(s.sessionToken);}finally{server.closeAllConnections();await new Promise<void>(resolve=>server.close(()=>resolve()));}});
 it.each(['transport','JSON','redirect'])('rejects %s without retry or private error exposure',async mode=>{const {c,fetch}=fixture(),s=session();if(mode==='transport')fetch.mockRejectedValueOnce(Error('provider private token'));else if(mode==='JSON')fetch.mockResolvedValueOnce(new Response('{bad'));else{const response=json({ok:true,data:projection(s)});Object.defineProperty(response,'redirected',{value:true});fetch.mockResolvedValueOnce(response);}await expect(c.readPaidJourneyCustomerFieldSession(s as never,{origin})).rejects.toMatchObject({code:'UNVERIFIED'});expect(fetch).toHaveBeenCalledTimes(1);});
 it('preserves successful issuance metadata and its original financial protocol fence after read',async()=>{const {c,fetch}=fixture(),s=session();fetch.mockResolvedValueOnce(json({ok:true,data:s}));const issued=await c.issuePaidJourneyCustomerFieldSession(I,{origin});const before=c.paidJourneyCustomerFieldSessionState();fetch.mockResolvedValueOnce(json({ok:true,data:projection(s)}));await c.readPaidJourneyCustomerFieldSession(issued,{origin});expect(c.paidJourneyCustomerFieldSessionState()).toEqual(before);await expect(c.issuePaidJourneySession(I)).rejects.toMatchObject({delivery:'not_sent'});await expect(c.mockPayPaidJourney(I,issued as never)).rejects.toMatchObject({delivery:'not_sent'});expect(fetch).toHaveBeenCalledTimes(2);});

});
