import {describe,expect,it,vi} from 'vitest';
import {createRuntimeClient} from './index';
import {createServer} from 'node:http';
const T='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',I='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',V='cccccccc-cccc-4ccc-8ccc-cccccccccccc',S='dddddddd-dddd-4ddd-8ddd-dddddddddddd',F='eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',A='ffffffff-ffff-4fff-8fff-ffffffffffff';
const origin='https://checkout.example.test';
const form=()=>({name:'Cleaning',presentation:{accentColor:'#0e7490',layout:'compact'},journey:{schemaVersion:1,stages:['service','options','schedule','information','review_payment','confirmation'].map(kind=>({id:kind,kind,label:kind,enabled:kind!=='options'}))},customerFields:[{id:'custom_gate',kind:'text',label:'Gate',required:false,maxLength:100}],fieldBindings:[{fieldId:'custom_gate',stageId:'information'}]});
const render=()=>({versionId:V,renderSchemaVersion:9,submissionMode:'paid_journey_customer_field_request',paymentMode:'staging_mock',simulated:true,service:{id:S,name:'Cleaning',durationMinutes:60,price:{amount:12500,currency:'USD'}},form:form()});
const json=(value:unknown,status=200)=>new Response(JSON.stringify(value),{status,headers:{'content-type':'application/json'}});
const fixture=()=>{const fetch=vi.fn<typeof globalThis.fetch>().mockResolvedValue(json({ok:true,data:render()}));return {fetch,c:createRuntimeClient({url:'https://example.supabase.co',publishableKey:'sb_publishable_fixture',tenantId:T,bookingApiOrigin:'https://api.example.test'},fetch)};};
describe('V9 public immutable reader SDK',()=>{
 it('reads exact public installation path without tenant, bearer, session or financial capability',async()=>{const {c,fetch}=fixture();const value=await c.loadPaidJourneyCustomerFieldRender(I,{origin});expect(value).toEqual(render());expect(Object.isFrozen(value)).toBe(true);expect(Object.isFrozen(value.form.customerFields[0])).toBe(true);expect(fetch).toHaveBeenCalledExactlyOnceWith('https://api.example.test/api/public/paid-journey-customer-field-installations/'+I+'/render',{method:'GET',credentials:'omit',cache:'no-store',redirect:'error',referrerPolicy:'no-referrer',headers:{Origin:origin}});expect(c.paidJourneyHoldState()).toEqual({phase:'ready'});expect(c.paidJourneyPaymentState()).toEqual({phase:'ready'});});
 it.each(['*',origin+'/',origin+'.evil.test/path','http://checkout.example.test','https://user:password@checkout.example.test'])('rejects malformed exact origin %s before dispatch',async candidate=>{const {c,fetch}=fixture();await expect(c.loadPaidJourneyCustomerFieldRender(I,{origin:candidate})).rejects.toMatchObject({code:'INVALID_REQUEST'});expect(fetch).not.toHaveBeenCalled();});
 it.each(['invalid',I.toUpperCase()])('rejects noncanonical installation %s before dispatch',async id=>{const {c,fetch}=fixture();await expect(c.loadPaidJourneyCustomerFieldRender(id,{origin})).rejects.toMatchObject({code:'INVALID_REQUEST'});expect(fetch).not.toHaveBeenCalled();});
 it('captures options once and rejects getters/extra fields without evaluating them',async()=>{const {c,fetch}=fixture();const getter=vi.fn(()=>origin);await expect(c.loadPaidJourneyCustomerFieldRender(I,{get origin(){return getter();}})).rejects.toMatchObject({code:'INVALID_REQUEST'});await expect(c.loadPaidJourneyCustomerFieldRender(I,{origin,tenantId:T} as never)).rejects.toMatchObject({code:'INVALID_REQUEST'});expect(getter).not.toHaveBeenCalled();expect(fetch).not.toHaveBeenCalled();const options={origin};const pending=c.loadPaidJourneyCustomerFieldRender(I,options);options.origin='https://changed.example.test';await pending;expect(fetch.mock.calls[0]![1]!.headers).toEqual({Origin:origin});});
 it.each([{...render(),renderSchemaVersion:8},{...render(),paymentMode:'live'},{...render(),sessionToken:'private'},{...render(),tenantId:T},{...render(),versionId:V.toUpperCase()},{...render(),service:{...render().service,price:{amount:-1,currency:'USD'}}},{...render(),form:{...form(),fieldBindings:[]}}])('rejects incompatible V9 or authority-widening response %j',async value=>{const {c,fetch}=fixture();fetch.mockResolvedValueOnce(json({ok:true,data:value}));await expect(c.loadPaidJourneyCustomerFieldRender(I,{origin})).rejects.toMatchObject({code:'UNVERIFIED'});expect(fetch).toHaveBeenCalledTimes(1);});
 it.each([401,403,404,409,500])('rejects status %s without auth mutation, fallback or retry',async status=>{const {c,fetch}=fixture();fetch.mockResolvedValueOnce(json({ok:false,code:'PRIVATE_SECRET'},status));await expect(c.loadPaidJourneyCustomerFieldRender(I,{origin})).rejects.toMatchObject({code:'REJECTED',message:'Preview is unavailable in this context.'});expect(fetch).toHaveBeenCalledTimes(1);});
 it('rejects extra envelope fields and redirects',async()=>{const {c,fetch}=fixture();fetch.mockResolvedValueOnce(json({ok:true,data:render(),secret:'private'}));await expect(c.loadPaidJourneyCustomerFieldRender(I,{origin})).rejects.toMatchObject({code:'UNVERIFIED'});const response=json({ok:true,data:render()});Object.defineProperty(response,'redirected',{value:true});fetch.mockResolvedValueOnce(response);await expect(c.loadPaidJourneyCustomerFieldRender(I,{origin})).rejects.toMatchObject({code:'UNVERIFIED'});});
 it('honors cancellation before dispatch and during response body',async()=>{const {c,fetch}=fixture();const controller=new AbortController();controller.abort();await expect(c.loadPaidJourneyCustomerFieldRender(I,{origin,signal:controller.signal})).rejects.toMatchObject({code:'ABORTED'});expect(fetch).not.toHaveBeenCalled();const next=new AbortController(),response=json({ok:true,data:render()});vi.spyOn(response,'json').mockImplementation(async()=>{next.abort();return {ok:true,data:render()};});fetch.mockResolvedValueOnce(response);await expect(c.loadPaidJourneyCustomerFieldRender(I,{origin,signal:next.signal})).rejects.toMatchObject({code:'ABORTED'});expect(fetch.mock.calls[0]![1]!.signal).toBe(next.signal);});
 it('rejects an older overlapping read after a newer installation request',async()=>{const {c,fetch}=fixture();let finish!:(value:Response)=>void;fetch.mockImplementationOnce(()=>new Promise(resolve=>finish=resolve));const old=c.loadPaidJourneyCustomerFieldRender(I,{origin});await c.loadPaidJourneyCustomerFieldRender(S,{origin});finish(json({ok:true,data:render()}));await expect(old).rejects.toMatchObject({code:'STALE_CONTEXT'});});
 it('fences late body results across account A-B-A without sending credentials to public reads',async()=>{const {c,fetch}=fixture();const signIn=async(id:string)=>{fetch.mockResolvedValueOnce(json({access_token:'private'})).mockResolvedValueOnce(json({id}));await c.signIn('fixture@example.test','fixture');};await signIn(A);let finish!:(value:unknown)=>void;const response=json({ok:true,data:render()});vi.spyOn(response,'json').mockImplementationOnce(()=>new Promise(resolve=>finish=resolve));fetch.mockResolvedValueOnce(response);const old=c.loadPaidJourneyCustomerFieldRender(I,{origin});await Promise.resolve();await signIn(S);await signIn(A);finish({ok:true,data:render()});await expect(old).rejects.toMatchObject({code:'STALE_CONTEXT'});const publicCall=fetch.mock.calls.find(call=>String(call[0]).includes('/api/public/'))!;expect(publicCall[1]!.headers).toEqual({Origin:origin});});
 it('does not clear private uncertain publication after public read',async()=>{const {c,fetch}=fixture();fetch.mockResolvedValueOnce(json({access_token:'private'})).mockResolvedValueOnce(json({id:A}));await c.signIn('fixture@example.test','fixture');fetch.mockResolvedValueOnce(json({ok:true,data:{schemaVersion:2,tenantId:T,flowId:F,revision:1,serviceId:S,form:form()}}));await c.loadPaidJourneyCustomerFieldDraft(T,F);fetch.mockRejectedValueOnce(Error('private credentials'));await expect(c.publishPaidJourneyCustomerFieldDraft(T,F,{schemaVersion:2,expectedDraftRevision:1,allowedOrigins:[origin]})).rejects.toMatchObject({delivery:'unknown'});fetch.mockResolvedValueOnce(json({ok:true,data:render()}));await c.loadPaidJourneyCustomerFieldRender(I,{origin});expect(c.paidJourneyCustomerFieldPublicationState(T).phase).toBe('unknown');await expect(c.setServiceActive(T,S,false)).rejects.toThrow();expect(c.paidJourneyPaymentState()).toEqual({phase:'ready'});});
 it('preserves V8 reader strictness against V9 result',async()=>{const {c}=fixture();await expect(c.readPaidJourneyRender(I)).rejects.toMatchObject({delivery:'not_sent'});});
 it('masks lost transport and malformed response JSON without retry',async()=>{const {c,fetch}=fixture();fetch.mockRejectedValueOnce(Error('private bearer'));await expect(c.loadPaidJourneyCustomerFieldRender(I,{origin})).rejects.toMatchObject({code:'UNVERIFIED'});fetch.mockResolvedValueOnce(new Response('{bad'));await expect(c.loadPaidJourneyCustomerFieldRender(I,{origin})).rejects.toMatchObject({code:'UNVERIFIED'});expect(fetch).toHaveBeenCalledTimes(2);});
 it('actual HTTP delayed body rejects A-B-A and carries only public origin context',async()=>{
  let began!:()=>void,finish!:()=>void;const started=new Promise<void>(resolve=>began=resolve);let requests=0;
  const server=createServer((req,res)=>{requests++;expect(req.method).toBe('GET');expect(req.url).toBe('/api/public/paid-journey-customer-field-installations/'+I+'/render');expect(req.headers.authorization).toBeUndefined();expect(req.headers.apikey).toBeUndefined();expect(req.headers.origin).toBe(origin);res.writeHead(200,{'content-type':'application/json'});res.write('{"ok":true,"data":');finish=()=>res.end(JSON.stringify(render())+'}');began();});
  await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const address=server.address();if(!address||typeof address==='string')throw Error('Loopback listener unavailable');let actor=A;
  const transport:typeof fetch=async(url,init)=>String(url).includes('/auth/v1/token')?json({access_token:'private'}):String(url).endsWith('/auth/v1/user')?json({id:actor}):fetch('http://127.0.0.1:'+address.port+new URL(String(url)).pathname,init);
  try{const c=createRuntimeClient({url:'https://example.supabase.co',publishableKey:'sb_publishable_fixture',tenantId:T,bookingApiOrigin:'https://api.example.test'},transport);await c.signIn('fixture@example.test','fixture');const pending=c.loadPaidJourneyCustomerFieldRender(I,{origin});await started;for(const selected of [S,A]){actor=selected;await c.signIn('fixture@example.test','fixture');}finish();await expect(pending).rejects.toMatchObject({code:'STALE_CONTEXT'});expect(requests).toBe(1);expect(c.paidJourneyHoldState()).toEqual({phase:'ready'});expect(c.paidJourneyPaymentState()).toEqual({phase:'ready'});}finally{server.closeAllConnections();await new Promise<void>(resolve=>server.close(()=>resolve()));}
 });
});
