import {afterEach,expect,it,vi} from 'vitest';
import type {Pool} from 'pg';
import type {Server} from 'node:http';
import {OwnerBookingFormAnswers,createBookingFormAnswersReader} from './booking-form-answers';
import {createFlowHttpServer} from './http';
import {FlowError} from './repository';
const id=(n:number)=>`68000000-0000-4000-8000-${String(n).padStart(12,'0')}`,actor=id(1),tenant=id(2),booking=id(3),flow=id(4),version=id(5),origin='https://portal.example.test';
const row={schemaVersion:1,tenantId:tenant,bookingId:booking,status:'recorded',provenance:{flowId:flow,versionId:version,renderSchemaVersion:5,draftRevision:1},answers:[{fieldId:'custom_access',label:'Pinned access',value:' Gate 12 '}]};
function db(value:unknown=row,error?:string){const query=vi.fn(async(sql:string)=>{if(sql.startsWith('select')){if(error)throw{code:error,message:'private details'};return{rows:[{result:value}]};}return{rows:[]};}),release=vi.fn(),connect=vi.fn(async()=>({query,release}));return{query,release,connect,read:createBookingFormAnswersReader({connect} as unknown as Pool)};}
it('uses one fixed service-role read RPC and returns only strict saved informational data',async()=>{const f=db();expect(await f.read(actor,tenant,booking)).toEqual(row);expect(f.query).toHaveBeenNthCalledWith(5,'select public.owner_booking_form_answers($1::uuid,$2::uuid,$3::uuid) as result',[actor,tenant,booking]);expect(f.query).toHaveBeenLastCalledWith('commit');expect(f.release).toHaveBeenCalledWith(false);expect(f.query.mock.calls.every(([sql])=>!(/insert|update|delete|issue_|confirm|lease|ack|retry|from public.flow_requests/i.test(sql)))).toBe(true);});
it.each(['not_recorded','unsupported'])('retains explicit %s without inventing an answer',async status=>{const empty={schemaVersion:1,tenantId:tenant,bookingId:booking,status,provenance:null,answers:[]};expect(await db(empty).read(actor,tenant,booking)).toEqual(empty);});
it.each([{...row,tenantId:id(99)},{...row,bookingId:id(99)},{...row,sessionToken:'private'},{...row,answers:[{fieldId:'custom_access',label:'Pinned',value:'bad\ntext'}]},{...row,answers:[...row.answers,...row.answers]},{...row,provenance:{...row.provenance,draftRevision:0}},{...row,answers:[{fieldId:'custom_price',label:'Price',value:'1',amount:1}]}])('rejects forged or extra saved answer data',async value=>{const f=db(value);await expect(f.read(actor,tenant,booking)).rejects.toMatchObject({code:'NOT_AVAILABLE'});expect(f.query).toHaveBeenLastCalledWith('rollback');});
it('rejects invalid identity before opening a connection',async()=>{const f=db();await expect(f.read('invalid',tenant,booking)).rejects.toMatchObject({code:'INVALID_REQUEST'});expect(f.connect).not.toHaveBeenCalled();});
it.each([['42501','FORBIDDEN'],['P0002','NOT_AVAILABLE'],['42883','UNSUPPORTED_CONFIG'],['40001','CONFLICT'],['unknown','INTERNAL_ERROR']])('redacts SQL failure %s as %s',async(code,expected)=>{await expect(db(row,code).read(actor,tenant,booking)).rejects.toMatchObject({code:expected});});
it('bounds fields, order and strict provenance in the shared contract',()=>{expect(OwnerBookingFormAnswers.safeParse({...row,answers:Array.from({length:11},(_,n)=>({fieldId:'custom_field_'+n,label:'Field',value:'x'}))}).success).toBe(false);expect(OwnerBookingFormAnswers.safeParse({...row,provenance:{...row.provenance,sessionId:id(9)}}).success).toBe(false);expect(OwnerBookingFormAnswers.safeParse({...row,answers:[{fieldId:'custom_access',label:'Pinned',value:'x'.repeat(1001)}]}).success).toBe(false);});
const servers:Server[]=[];afterEach(async()=>{await Promise.all(servers.splice(0).map(server=>new Promise<void>(resolve=>{server.close(()=>resolve());server.closeAllConnections();})));});
async function http(reader=vi.fn(async()=>row)){
 const authenticateOwner=vi.fn(async(token:string)=>token==='owner-test-token'?actor:null),rpc=vi.fn(async()=>{throw Error('Unexpected repository RPC');});
 const server=createFlowHttpServer({repository:{rpc} as never,ownerOrigins:[origin],customerOrigins:['https://checkout.example.test'],authenticateOwner,bookingFormAnswers:reader as never});servers.push(server);await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
 const read=async(path=`/api/booking-form-answers?tenantId=${tenant}&bookingId=${booking}`,token='owner-test-token',method='GET',requestOrigin=origin)=>{const response=await fetch(base+path,{method,headers:{origin:requestOrigin,authorization:`Bearer ${token}`}});return{status:response.status,body:await response.json()};};return{read,reader,authenticateOwner,rpc};
}
it('authenticates freshly and binds the one GET to exact tenant and booking',async()=>{const h=await http();expect((await h.read()).body).toEqual({ok:true,data:row});expect(h.reader).toHaveBeenCalledWith(actor,tenant,booking);await h.read();expect(h.authenticateOwner).toHaveBeenCalledTimes(2);expect(h.rpc).not.toHaveBeenCalled();});
it('denies missing authentication and foreign origin before reading private answers',async()=>{const h=await http();expect((await h.read(undefined,'invalid')).status).toBe(401);expect((await h.read(undefined,'owner-test-token','GET','https://foreign.example.test')).status).toBe(403);expect(h.reader).not.toHaveBeenCalled();});
it.each([`/api/booking-form-answers?tenantId=${tenant}&bookingId=${booking}&actor=${actor}`,`/api/booking-form-answers?tenantId=${tenant}&bookingId=${booking}&bookingId=${booking}`,`/api/booking-form-answers?tenantId=${tenant}`,`/api/booking-form-answers?tenantId=${tenant}&bookingId=bad`])('rejects malformed or forged query %s before helper',async path=>{const h=await http();expect((await h.read(path)).status).toBe(400);expect(h.reader).not.toHaveBeenCalled();});
it('rejects writes and helper DTO mismatches without returning private fields',async()=>{const h=await http();expect((await h.read(undefined,'owner-test-token','POST')).status).toBe(400);expect(h.reader).not.toHaveBeenCalled();h.reader.mockResolvedValue({...row,bookingId:id(99)});expect((await h.read()).status).toBe(500);});
it('preserves owner-helper denial with redacted response',async()=>{const h=await http(vi.fn(async()=>{throw new FlowError('FORBIDDEN');}));expect(await h.read()).toEqual({status:403,body:{ok:false,code:'FORBIDDEN'}});});
