import assert from 'node:assert/strict';
import {Pool} from 'pg';
import {createBusinessProfileInitializer} from './existing-business-profile';
import {createBusinessApi} from './business';
import {createFlowHttpServer} from './http';
assert.equal(process.env.BUSINESS_PROFILE_INITIALIZATION_LOCAL_TEST,'1');
assert.ok(['localhost','127.0.0.1'].includes(process.env.PGHOST??''));assert.equal(process.env.PGPORT,process.env.CI==='true'?'5432':'55436');assert.match(process.env.PGDATABASE??'',/^lumin_phase_a_profile_init_/);
for(const key of ['DATABASE_URL','PGHOSTADDR','PGSERVICE','PGSERVICEFILE','PGOPTIONS','PGPASSFILE'])assert.ok(!process.env[key]);
const pool=new Pool({max:8}),id=(n:number)=>`54000000-0000-4000-8000-${String(n).padStart(12,'0')}`,actor=id(1),tenant=id(2),staff=id(3),other=id(4),worker=id(5),second=id(10),raceTenant=id(11),failed=id(12),origin='https://portal.example.test';
const api=createBusinessApi(pool),initialize=createBusinessProfileInitializer(pool),body={businessType:'HOUSEKEEPING',idempotencyKey:'existing-profile-http-0001'};
const server=createFlowHttpServer({repository:{call:async()=>{throw Error('unexpected customer authority');}},businessOnboarding:true,businessProfileInitialize:initialize,businessCreate:api.create,businessProfile:api.read,ownerOrigins:[origin],customerOrigins:[],authenticateOwner:async token=>token==='owner-token-123456'?actor:token==='staff-token-123456'?staff:token==='other-owner-123456'?other:token==='worker-token-123456'?worker:null});
await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
async function request(path:string,value?:unknown,token='owner-token-123456',o=origin){const r=await fetch(base+path,{method:value===undefined?'GET':'POST',headers:{origin:o,authorization:`Bearer ${token}`,'content-type':'application/json'},...(value===undefined?{}:{body:JSON.stringify(value)})});return{status:r.status,json:await r.json()};}
const init=(t=tenant,value:unknown=body,token?:string)=>request('/api/business-profile/initialize?tenantId='+t,value,token);
async function profileRows(){return(await pool.query('select to_jsonb(b) profile from public.business_profiles b order by tenant_id')).rows;}
try{
 await pool.query("insert into auth.users(id,email) values($1,'init-http-owner@example.test'),($2,'init-http-staff@example.test'),($3,'init-http-other@example.test'),($4,'init-http-worker@example.test')",[actor,staff,other,worker]);
 for(const t of [tenant,second,raceTenant,failed]){await pool.query("insert into public.tenants(id,name,slug,timezone,currency) values($1,'Existing Housekeeping',$2,'America/Los_Angeles','USD')",[t,'profile-http-'+t]);await pool.query("insert into public.tenant_members(tenant_id,user_id,role) values($1,$2,'BUSINESS_OWNER')",[t,actor]);}
 await pool.query("insert into public.tenant_members(tenant_id,user_id,role) values($1,$2,'BUSINESS_STAFF'),($1,$3,'BUSINESS_OWNER')",[tenant,staff,other]);
 const unchanged=(await pool.query('select to_jsonb(t) row from public.tenants t order by id')).rows,unchangedMembers=(await pool.query('select to_jsonb(m) row from public.tenant_members m order by tenant_id,user_id')).rows;
 assert.equal((await request('/api/business-profile?tenantId='+tenant)).status,404);
 for(const token of ['staff-token-123456','worker-token-123456'])assert.equal((await init(tenant,body,token)).status,403);
 assert.equal((await init(second,body,'other-owner-123456')).status,403);assert.equal((await init(tenant,body,'sb_publishable_public_key')).status,401);
 for(const extra of [{actor},{tenantId:second},{role:'BUSINESS_OWNER'},{name:'Rename'},{price:12500},{provider:'stripe'},{businessType:'simple'}])assert.equal((await init(tenant,{...body,...extra})).status,400);
 assert.equal((await request('/api/business-profile/initialize?tenantId='+tenant+'&actor='+actor,body)).status,400);assert.equal((await request('/api/business-profile/initialize?tenantId='+tenant,body,undefined,'https://foreign.example.test')).status,403);
 const same=await Promise.all(Array.from({length:4},()=>init()));assert.ok(same.every(r=>r.status===200));assert.ok(same.every(r=>JSON.stringify(r.json)===JSON.stringify(same[0]!.json)));
 assert.deepEqual(same[0]!.json,{ok:true,data:{schemaVersion:1,tenantId:tenant,businessType:'HOUSEKEEPING',templateVersion:1}});assert.deepEqual((await request('/api/business-profile?tenantId='+tenant)).json,same[0]!.json);
 const stable=await profileRows();assert.equal((await init(tenant,{...body,businessType:'AUTO_DETAILING'})).status,409);assert.equal((await init(tenant,{...body,idempotencyKey:'existing-profile-http-other'})).status,409);assert.equal((await init(tenant,body,'other-owner-123456')).status,409);assert.equal((await init(second)).status,409);assert.deepEqual(await profileRows(),stable);
 const race=await Promise.all([init(raceTenant,{...body,idempotencyKey:'profile-race-key-0001'}),init(raceTenant,{businessType:'AUTO_DETAILING',idempotencyKey:'profile-race-key-0002'})]);assert.deepEqual(race.map(r=>r.status).sort(),[200,409]);const winner=race.findIndex(r=>r.status===200);assert.deepEqual((await init(raceTenant,winner===0?{...body,idempotencyKey:'profile-race-key-0001'}:{businessType:'AUTO_DETAILING',idempotencyKey:'profile-race-key-0002'})).json,race[winner]!.json);
 assert.deepEqual((await pool.query('select to_jsonb(t) row from public.tenants t order by id')).rows,unchanged);assert.deepEqual((await pool.query('select to_jsonb(m) row from public.tenant_members m order by tenant_id,user_id')).rows,unchangedMembers);
 const snap=(await pool.query('select * from public.business_profiles where tenant_id=$1',[tenant])).rows[0];assert.equal(snap.creation_name,'Existing Housekeeping');assert.equal(snap.creation_slug,'profile-http-'+tenant);assert.equal(snap.creation_timezone,'America/Los_Angeles');assert.equal(snap.creation_currency,'USD');
 const newBody={name:snap.creation_name,slug:snap.creation_slug,timezone:snap.creation_timezone,currency:snap.creation_currency,businessType:'HOUSEKEEPING',idempotencyKey:body.idempotencyKey};assert.equal((await request('/api/businesses',newBody)).status,409);assert.deepEqual((await pool.query('select to_jsonb(t) row from public.tenants t order by id')).rows,unchanged);
 const ordinary={...newBody,name:'Ordinary new',slug:'profile-http-ordinary',idempotencyKey:'ordinary-business-http-0001'};const created=await request('/api/businesses',ordinary);assert.equal(created.status,200);assert.deepEqual((await request('/api/businesses',ordinary)).json,created.json);assert.equal((await init(created.json.data.tenantId,{businessType:'HOUSEKEEPING',idempotencyKey:ordinary.idempotencyKey})).status,409);
 await pool.query("create function public.fixture_fail_init_ledger() returns trigger language plpgsql as $$begin if new.tenant_id='54000000-0000-4000-8000-000000000012' then raise exception 'fixture failure';end if;return new;end$$;create trigger fixture_fail_init_ledger before insert on public.business_profile_initializations for each row execute function public.fixture_fail_init_ledger()");
 assert.equal((await init(failed,{...body,idempotencyKey:'profile-http-failure-0001'})).status,500);assert.equal(Number((await pool.query('select count(*) n from public.business_profiles where tenant_id=$1',[failed])).rows[0].n),0);await pool.query('drop trigger fixture_fail_init_ledger on public.business_profile_initializations;drop function public.fixture_fail_init_ledger()');assert.equal((await init(failed,{...body,idempotencyKey:'profile-http-failure-0001'})).status,200);
 await assert.rejects(pool.query("update public.business_profiles set business_type='AUTO_DETAILING' where tenant_id=$1",[tenant]),(e:unknown)=>(e as {code?:string}).code==='55000');await assert.rejects(pool.query('delete from public.business_profile_initializations where tenant_id=$1',[tenant]),(e:unknown)=>(e as {code?:string}).code==='55000');
 await pool.query("update public.tenants set status='inactive' where id=$1",[tenant]);assert.equal((await init()).status,403);await pool.query("update public.tenants set status='active' where id=$1",[tenant]);await pool.query('delete from public.tenant_members where tenant_id=$1 and user_id=$2',[tenant,actor]);assert.equal((await init()).status,403);await pool.query("insert into public.tenant_members(tenant_id,user_id,role) values($1,$2,'BUSINESS_OWNER')",[tenant,actor]);assert.deepEqual((await init()).json,same[0]!.json);
 for(const table of ['services','flow_versions','flow_installations','flow_sessions','flow_requests','customers','bookings','payments','capacity_holds'])assert.equal(Number((await pool.query(`select count(*) n from public.${table}`)).rows[0].n),0);
 console.log('PASS actual HTTP existing-profile initialization: concurrent exact replay and conflicting winner; foreign/staff/worker/revoked/inactive deny; strict body/actor/tenant; bidirectional new-create collision denial and ordinary replay; immutable exact snapshot; no tenant/member changes by initializer; atomic ledger failure; zero catalog/customer/financial writes');
}finally{server.closeAllConnections();await new Promise<void>(resolve=>server.close(()=>resolve()));await pool.end();}
