import assert from 'node:assert/strict';
import {Pool} from 'pg';
import {BusinessType} from '@lumin/contracts';
import {createBusinessApi} from './business';
import {createFlowHttpServer} from './http';
assert.equal(process.env.BUSINESS_LOCAL_TEST,'1');if(process.env.CI==='true'){assert.ok(['localhost','127.0.0.1'].includes(process.env.PGHOST??''));assert.equal(process.env.PGPORT,'5432');}else{assert.equal(process.env.PGHOST,'127.0.0.1');assert.equal(process.env.PGPORT,'55436');}assert.match(process.env.PGDATABASE??'',/^lumin_phase_a_business_/);for(const key of ['DATABASE_URL','PGHOSTADDR','PGSERVICE','PGSERVICEFILE','PGOPTIONS'])assert.ok(!process.env[key]);
const pool=new Pool({max:8}),id=(n:number)=>`45000000-0000-4000-8000-${String(n).padStart(12,'0')}`,actor=id(1),foreign=id(9),uninitialized=id(10),origin='https://portal.example.test',api=createBusinessApi(pool),server=createFlowHttpServer({repository:{call:async()=>{throw Error('unexpected flow writer');}},businessOnboarding:true,businessCreate:api.create,businessProfile:api.read,ownerOrigins:[origin],customerOrigins:[],authenticateOwner:async token=>token==='owner-token-123456'?actor:token==='foreign-token-123456'?foreign:null});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
const body={name:'Housekeeping',slug:'business-http',timezone:'America/Los_Angeles',currency:'USD',businessType:'HOUSEKEEPING',idempotencyKey:'business-http-attempt-0001'};
async function request(path:string,value?:unknown,token='owner-token-123456',o=origin){const r=await fetch(base+path,{method:value===undefined?'GET':'POST',headers:{origin:o,authorization:`Bearer ${token}`,'content-type':'application/json'},...(value===undefined?{}:{body:JSON.stringify(value)})});return{status:r.status,json:await r.json()};}
const create=(value:unknown=body,token?:string)=>request('/api/businesses',value,token),read=(tenant:string,token?:string)=>request('/api/business-profile?tenantId='+tenant,undefined,token);
async function counts(){return(await pool.query('select (select count(*) from public.tenants)::int tenants,(select count(*) from public.tenant_members)::int members,(select count(*) from public.business_profiles)::int profiles')).rows[0];}
try{
 await pool.query("insert into auth.users(id,email) values($1,'business-http@example.test'),($2,'business-foreign-http@example.test')",[actor,foreign]);await pool.query("insert into public.tenants(id,name,slug,timezone,currency) values($1,'Uninitialized','business-http-uninitialized','UTC','USD')",[uninitialized]);await pool.query("insert into public.tenant_members(tenant_id,user_id,role) values($1,$2,'BUSINESS_OWNER')",[uninitialized,actor]);
 assert.equal((await read(uninitialized)).status,404);assert.equal((await create(body,'invalid-token-123456')).status,401);for(const extra of [{actor:foreign},{tenantId:uninitialized},{role:'BUSINESS_OWNER'},{price:12500},{provider:'stripe'}])assert.equal((await create({...body,...extra})).status,400);assert.equal((await request('/api/businesses?tenantId='+uninitialized,body)).status,400);assert.equal((await request('/api/businesses',body,undefined,'https://foreign.example.test')).status,403);
 const race=await Promise.all([create(),create()]);assert.deepEqual(race.map(r=>r.status),[200,200]);assert.deepEqual(race[0].json,race[1].json);const profile=race[0].json.data;assert.deepEqual(Object.keys(profile).sort(),['businessType','schemaVersion','templateVersion','tenantId']);assert.equal(profile.businessType,'HOUSEKEEPING');assert.equal(profile.schemaVersion,1);assert.equal(profile.templateVersion,1);assert.match(profile.tenantId,/^[0-9a-f-]{36}$/);assert.notEqual(profile.tenantId,uninitialized);assert.deepEqual(await counts(),{tenants:2,members:2,profiles:1});assert.deepEqual((await read(profile.tenantId)).json,race[0].json);
 const stable=await counts();assert.equal((await create({...body,businessType:'AUTO_DETAILING'})).status,409);assert.equal((await create({...body,idempotencyKey:'business-http-attempt-0002'})).status,409);assert.equal((await create(body,'foreign-token-123456')).status,409);assert.equal((await read(profile.tenantId,'foreign-token-123456')).status,403);assert.deepEqual(await counts(),stable);
 await assert.rejects(pool.query('update public.business_profiles set business_type=$2 where tenant_id=$1',[profile.tenantId,'AUTO_DETAILING']),(e:unknown)=>(e as {code?:string}).code==='55000');
 for(const role of ['BUSINESS_STAFF']){await pool.query('update public.tenant_members set role=$3 where tenant_id=$1 and user_id=$2',[profile.tenantId,actor,role]);assert.equal((await read(profile.tenantId)).status,403);assert.equal((await create()).status,403);}await pool.query("update public.tenant_members set role='BUSINESS_OWNER' where tenant_id=$1 and user_id=$2",[profile.tenantId,actor]);
 await pool.query("update public.tenants set status='inactive' where id=$1",[profile.tenantId]);assert.equal((await read(profile.tenantId)).status,403);assert.equal((await create()).status,403);await pool.query("update public.tenants set status='active' where id=$1",[profile.tenantId]);await pool.query('delete from public.tenant_members where tenant_id=$1 and user_id=$2',[profile.tenantId,actor]);assert.equal((await read(profile.tenantId)).status,403);assert.equal((await create()).status,403);await pool.query("insert into public.tenant_members(tenant_id,user_id,role) values($1,$2,'BUSINESS_OWNER')",[profile.tenantId,actor]);
 for(const businessType of BusinessType.options){const result=await create({...body,businessType,slug:'business-'+businessType.toLowerCase().replaceAll('_','-'),idempotencyKey:'business-type-'+businessType});assert.equal(result.status,200);assert.equal(result.json.data.businessType,businessType);assert.equal((await read(result.json.data.tenantId)).json.data.businessType,businessType);}
 for(const table of ['services','flow_versions','flow_installations','flow_sessions','bookings','payments','capacity_holds'])assert.equal(Number((await pool.query(`select count(*) n from public.${table}`)).rows[0].n),0);
 console.log('PASS real HTTP staging business onboarding: concurrent actor/key exact replay; six immutable types; no client tenant/actor/price; owner-scoped read; uninitialized404; cross owner/staff/revoked/inactive denied; conflicting body/key no orphan; zero catalog/customer/financial writes');
}finally{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));await pool.end();}
