import {afterEach,expect,it,vi} from 'vitest';
import type {Server} from 'node:http';
import {businessOnboardingEnabled,createBusinessApi} from './business';
import {createFlowHttpServer} from './http';
import {FlowError} from './repository';
const actor='45000000-0000-4000-8000-000000000001',tenant='45000000-0000-4000-8000-000000000002',origin='https://portal.example.test';
const body={name:'Housekeeping',slug:'housekeeping',timezone:'America/Los_Angeles',currency:'USD',businessType:'HOUSEKEEPING' as const,idempotencyKey:'business-attempt-0001'},profile={schemaVersion:1 as const,tenantId:tenant,businessType:'HOUSEKEEPING' as const,templateVersion:1 as const};
let server:Server;afterEach(async()=>{server?.closeAllConnections();if(server)await new Promise<void>(r=>server.close(()=>r()));});
async function setup(enabled=true,value:unknown=profile){const create=vi.fn(async()=>{if(value instanceof Error)throw value;return value as typeof profile;}),read=vi.fn(async()=>{if(value instanceof Error)throw value;return value as typeof profile;}),call=vi.fn();server=createFlowHttpServer({repository:{call},businessOnboarding:enabled,businessCreate:create,businessProfile:read,ownerOrigins:[origin],customerOrigins:[],authenticateOwner:async token=>token==='owner-token-123456'?actor:null});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));return{create,read,call,request:(path='/api/businesses',value:unknown=body,token='owner-token-123456',o=origin,method='POST')=>fetch(`http://127.0.0.1:${(server.address() as {port:number}).port}`+path,{method,headers:{origin:o,authorization:`Bearer ${token}`,'content-type':'application/json'},...(method==='POST'?{body:JSON.stringify(value)}:{})})};}
it('creation requires no tenant and binds only fresh actor plus strict body',async()=>{const f=await setup(),r=await f.request();expect(r.status).toBe(200);expect(await r.json()).toEqual({ok:true,data:profile});expect(r.headers.get('cache-control')).toBe('no-store');expect(f.create).toHaveBeenCalledWith(actor,body);expect(f.call).not.toHaveBeenCalled();});
it.each([{tenantId:tenant},{actor},{businessType:'simple'},{price:1},{provider:'stripe'},{role:'BUSINESS_OWNER'},{timezone:'PST'},{currency:'usd'},{idempotencyKey:'short'}])('rejects widened/invalid creation %j',async extra=>{const f=await setup();expect((await f.request(undefined,{...body,...extra})).status).toBe(400);expect(f.create).not.toHaveBeenCalled();});
it('rejects tenant query, forged identity, customer origin, disabled capability and GET create',async()=>{const f=await setup(false);expect((await f.request()).status).toBe(422);expect((await f.request(undefined,undefined,'forged-token-123456')).status).toBe(401);expect((await f.request(undefined,undefined,undefined,'https://checkout.example.test')).status).toBe(403);expect(f.create).not.toHaveBeenCalled();});
it('rejects query authority and incorrect creation method before writer',async()=>{const f=await setup();expect((await f.request('/api/businesses?tenantId='+tenant)).status).toBe(400);expect((await f.request(undefined,undefined,undefined,undefined,'GET')).status).toBe(404);expect(f.create).not.toHaveBeenCalled();});
it('read returns exact scoped profile and no writes',async()=>{const f=await setup();const r=await f.request('/api/business-profile?tenantId='+tenant,undefined,undefined,undefined,'GET');expect(r.status).toBe(200);expect(await r.json()).toEqual({ok:true,data:profile});expect(f.read).toHaveBeenCalledWith(actor,tenant);expect(f.create).not.toHaveBeenCalled();expect(f.call).not.toHaveBeenCalled();});
it.each(['','?tenantId='+tenant+'&tenantId='+tenant,'?tenantId='+tenant+'&actor='+actor])('rejects widened read query %s',async query=>{const f=await setup();expect((await f.request('/api/business-profile'+query,undefined,undefined,undefined,'GET')).status).toBe(400);expect(f.read).not.toHaveBeenCalled();});
it.each([['FORBIDDEN',403],['NOT_AVAILABLE',404],['CONFLICT',409]] as const)('preserves safe %s',async(code,status)=>{const f=await setup(true,new FlowError(code));expect((await f.request()).status).toBe(status);});
it('rejects inconsistent SQL/HTTP receipts',async()=>{const f=await setup(true,{...profile,businessType:'AUTO_DETAILING'});expect((await f.request()).status).toBe(500);});
it('separate staging gate defaults closed and never enables production',()=>{expect(businessOnboardingEnabled({})).toBe(false);expect(businessOnboardingEnabled({BOOKING_LUMIN_ENV:'staging',BOOKING_LUMIN_BUSINESS_ONBOARDING:'1'})).toBe(true);expect(businessOnboardingEnabled({BOOKING_LUMIN_ENV:'production',BOOKING_LUMIN_BUSINESS_ONBOARDING:'1',BOOKING_LUMIN_FAKE_PAYMENTS:'1'})).toBe(false);expect(businessOnboardingEnabled({BOOKING_LUMIN_ENV:'staging',BOOKING_LUMIN_FAKE_PAYMENTS:'1'})).toBe(false);});
function db(value:unknown=profile,error?:unknown){const release=vi.fn(),query=vi.fn(async(sql:string)=>{if(sql.startsWith('select')){if(error)throw error;return{rows:[{result:value}]};}return{rows:[]};});return{query,release,api:createBusinessApi({connect:async()=>({query,release})} as never)};}
it('fixed creation SQL generates server UUID, passes canonical fields and commits',async()=>{const f=db();expect(await f.api.create(actor,body)).toEqual(profile);const select=f.query.mock.calls.find(c=>c[0].startsWith('select'))!;expect(select[0]).toContain('public.create_staging_business($1::uuid,$2::uuid');expect((select as unknown as [string,unknown[]])[1]).toEqual([actor,expect.stringMatching(/^[0-9a-f-]{36}$/),body.name,body.slug,body.timezone,body.currency,body.businessType,body.idempotencyKey]);expect(f.query).toHaveBeenLastCalledWith('commit');});
it('fixed read SQL binds tenant and rejects foreign receipt before commit',async()=>{const f=db({...profile,tenantId:actor});await expect(f.api.read(actor,tenant)).rejects.toMatchObject({code:'INTERNAL_ERROR'});expect(f.query).toHaveBeenLastCalledWith('rollback');});
it.each([['42501','FORBIDDEN'],['23505','CONFLICT'],['40001','CONFLICT'],['P0002','NOT_AVAILABLE'],['22023','INVALID_REQUEST'],['XX000','INTERNAL_ERROR']])('redacts database error %s',async(code,expected)=>{const f=db(undefined,{code,message:'secret'});await expect(f.api.create(actor,body)).rejects.toMatchObject({code:expected,message:expected});expect(f.query).toHaveBeenLastCalledWith('rollback');});
