import assert from 'node:assert/strict';
import {Pool} from 'pg';
import {createFlowHttpServer} from './http';
import {createFlowRepository} from './repository';
import {createConditionalCustomerFieldRollback} from './conditional-customer-field-rollback';
import {createConditionalCustomerFieldVersionHistoryReader} from './conditional-customer-field-version-history';
import {createConditionalCustomerFieldRollbackReceiptReader} from './conditional-customer-field-rollback-receipt';
import {createCustomerHoldWriter} from './customer-hold';
import {createCustomerMockPayment,createCustomerConfirmation} from './customer-payment';
import {createCustomerAvailabilityReader} from './customer-availability';
assert.equal(process.env.CONDITIONAL_CUSTOMER_FIELD_ROLLBACK_LOCAL_TEST,'1');if(process.env.CI==='true'){assert.ok(['localhost','127.0.0.1'].includes(process.env.PGHOST??''));assert.equal(process.env.PGPORT,'5432');}else{assert.equal(process.env.PGHOST,'127.0.0.1');assert.equal(process.env.PGPORT,'55436');}assert.match(process.env.PGDATABASE??'',/^lumin_phase_a_conditional_rollback_/);for(const key of ['DATABASE_URL','PGHOSTADDR','PGSERVICE','PGSERVICEFILE','PGPASSFILE','PGOPTIONS'])assert.ok(!process.env[key]);
const pool=new Pool({max:8}),id=(n:number)=>`59000000-0000-4000-8000-${String(n).padStart(12,'0')}`,actor=id(1),tenant=id(2),service=id(3),flow=id(4),foreignActor=id(90),foreignTenant=id(91),origin='https://portal.example.test',customerOrigin='https://checkout.example.test',repo=createFlowRepository(pool);
const server=createFlowHttpServer({repository:repo,paidSimplePublication:true,customerHold:createCustomerHoldWriter(pool),customerMockPayment:createCustomerMockPayment(pool,{BOOKING_LUMIN_ENV:'staging',BOOKING_LUMIN_FAKE_PAYMENTS:'1'}),customerConfirmation:createCustomerConfirmation(pool),paidConditionalCustomerFieldVersionHistory:createConditionalCustomerFieldVersionHistoryReader(pool,[customerOrigin]),paidConditionalCustomerFieldRollbackReceipt:createConditionalCustomerFieldRollbackReceiptReader(pool,[customerOrigin]),paidConditionalCustomerFieldRollback:createConditionalCustomerFieldRollback(pool,[customerOrigin]),customerAvailability:createCustomerAvailabilityReader(pool),ownerOrigins:[origin],customerOrigins:[customerOrigin],authenticateOwner:async token=>token==='owner-token-123456'?actor:token==='foreign-token-123456'?foreignActor:null});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
async function post(path:string,body:unknown,token?:string,o=origin){const r=await fetch(base+path,{method:'POST',headers:{origin:o,'content-type':'application/json',...(token?{authorization:`Bearer ${token}`}:{})},body:JSON.stringify(body)});return{status:r.status,json:await r.json()};}
const rollback=(expected=id(103),target=id(101),token='owner-token-123456',t=tenant,f=flow)=>post(`/api/paid-conditional-customer-field-flows/${f}/rollback?tenantId=${t}`,{expectedCurrentVersionId:expected,targetVersionId:target},token);
const fields=(revision:number)=>[{id:'custom_access',kind:'text',label:`Entry instructions ${revision}`,required:true,maxLength:40},{id:'custom_extra',kind:'text',label:'Extra notes',required:true,maxLength:100,when:{fieldId:'custom_access',equals:'gate'}}];
async function publish(revision:number){
 const save=revision===1?'save_paid_simple_draft':revision===2?'save_paid_customer_field_draft':'save_paid_conditional_customer_field_draft';
 await repo.call(save,[actor,tenant,flow,service,revision-1,`Saved ${revision}`,'#4f46e5','stacked',...(revision===1?[]:[revision===2?fields(revision).slice(0,1):fields(revision)])]);
 await repo.call(revision===1?'publish_paid_simple_draft':revision===2?'publish_paid_customer_field_draft':'publish_paid_conditional_customer_field_draft',[actor,tenant,flow,revision,id(100+revision),id(200+revision),[customerOrigin]]);
}
async function read(suffix:string,f=flow,token='owner-token-123456',t=tenant){const r=await fetch(`${base}/api/paid-conditional-customer-field-flows/${f}/${suffix}?tenantId=${t}`,{headers:{origin,authorization:`Bearer ${token}`}});return{status:r.status,json:await r.json()};}
const unchanged=['paid_simple_drafts','flow_versions','flow_installations','bound_flow_versions','bound_flow_services','flow_sessions','flow_requests','bookings','payments','capacity_holds','booking_state_history'];
async function snapshots(){const result:Record<string,unknown>={};for(const table of unchanged)result[table]=(await pool.query(`select coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]'::jsonb) snapshot from public.${table} x`)).rows[0].snapshot;return result;}
try{
 await pool.query("insert into auth.users(id,email) values($1,'rollback-owner@example.test'),($2,'rollback-foreign@example.test')",[actor,foreignActor]);await pool.query("insert into public.tenants(id,name,slug,timezone,currency) values($1,'Rollback','rollback-fixture','UTC','USD'),($2,'Foreign','rollback-foreign-fixture','UTC','USD')",[tenant,foreignTenant]);await pool.query("insert into public.tenant_members(tenant_id,user_id,role) values($1,$2,'BUSINESS_OWNER'),($3,$4,'BUSINESS_OWNER')",[tenant,actor,foreignTenant,foreignActor]);await pool.query("insert into public.services(id,tenant_id,name,archetype,currency,base_price,duration_minutes) values($1,$2,'Housekeeping','simple','USD',12500,60)",[service,tenant]);
 await pool.query('insert into public.scheduling_policies(tenant_id,service_id,lead_time_minutes,horizon_days,slot_interval_minutes) values($1,$2,0,30,30)',[tenant,service]);await pool.query('insert into public.availability_rules(tenant_id,service_id,weekday,start_minute,end_minute,capacity) select $1,$2,n,0,1440,1 from generate_series(0,6)n',[tenant,service]);
 for(let r=1;r<=3;r++)await publish(r);
 const currentSession=await post(`/api/installations/${id(203)}/sessions`,{},undefined,customerOrigin),historicalSession=await post(`/api/installations/${id(201)}/sessions`,{},undefined,customerOrigin);assert.equal(currentSession.status,200);assert.equal(historicalSession.status,200);assert.equal(currentSession.json.data.render.publication.name,'Saved 3');assert.equal(currentSession.json.data.render.renderSchemaVersion,6);assert.deepEqual(currentSession.json.data.render.customerFields,fields(3));assert.equal(historicalSession.json.data.render.renderSchemaVersion,3);assert.equal(historicalSession.json.data.render.publication.name,'Saved 1');
 assert.equal((await rollback(id(103),id(103))).status,409);assert.equal((await rollback(id(102),id(101))).status,409);assert.equal((await rollback(undefined,undefined,'foreign-token-123456')).status,403);assert.equal((await rollback(undefined,undefined,undefined,foreignTenant)).status,403);assert.equal((await rollback(undefined,undefined,'invalid-token-123456')).status,401);
 for(const status of ['inactive','suspended']){await pool.query('update public.tenants set status=$2 where id=$1',[tenant,status]);assert.equal((await rollback()).status,403);assert.equal((await read('versions')).status,403);assert.equal((await read('rollback-receipt')).status,403);}await pool.query("update public.tenants set status='active' where id=$1",[tenant]);await pool.query("update public.tenant_members set role='BUSINESS_STAFF' where tenant_id=$1 and user_id=$2",[tenant,actor]);assert.equal((await rollback()).status,403);assert.equal((await read('versions')).status,403);assert.equal((await read('rollback-receipt')).status,403);await pool.query('delete from public.tenant_members where tenant_id=$1 and user_id=$2',[tenant,actor]);assert.equal((await rollback()).status,403);assert.equal((await read('versions')).status,403);assert.equal((await read('rollback-receipt')).status,403);await pool.query("insert into public.tenant_members(tenant_id,user_id,role) values($1,$2,'BUSINESS_OWNER')",[tenant,actor]);
 await pool.query('update public.services set base_price=13000 where id=$1',[service]);assert.equal((await rollback()).status,422);await pool.query('update public.services set base_price=12500 where id=$1',[service]);
 for(const origins of [['https://foreign.example.test'],[customerOrigin,customerOrigin]]){await pool.query('update public.flow_installations set allowed_origins=$2::jsonb where id=$1',[id(201),JSON.stringify(origins)]);assert.equal((await rollback()).status,403);const unverified=await read('versions');assert.equal(unverified.status,200);assert.equal(unverified.json.data.versions.find((v:any)=>v.versionId===id(101)).publication,null);assert.equal((await read('rollback-receipt')).status,200);}await pool.query('update public.flow_installations set allowed_origins=$2::jsonb where id=$1',[id(201),JSON.stringify([customerOrigin])]);await pool.query('insert into public.flow_installations(id,tenant_id,flow_id,version_id,allowed_origins) values($1,$2,$3,$4,$5::jsonb)',[id(500),tenant,flow,id(101),JSON.stringify([customerOrigin])]);assert.equal((await rollback()).status,404);await pool.query('delete from public.flow_installations where id=$1',[id(500)]);
 // Missing live service binding is denied before any pointer change.
 await pool.query('delete from public.bound_flow_services where tenant_id=$1 and flow_id=$2',[tenant,flow]);assert.equal((await rollback()).status,404);await pool.query('insert into public.bound_flow_services(tenant_id,flow_id,service_id) values($1,$2,$3)',[tenant,flow,service]);
 // Create a real confirmed staging booking before rollback, using the unchanged sole writer.
 const paidStart=new Date();paidStart.setUTCDate(paidStart.getUTCDate()+1);paidStart.setUTCHours(10,0,0,0);
 const paymentBody={schemaVersion:3,idempotencyKey:'conditional-rollback-booking-001',answers:{},customerAnswers:{custom_access:'gate',custom_extra:'Private gate details'},customer:{name:'Private customer',email:'private-rollback@example.test'},requestedStart:paidStart.toISOString()};
 const token=currentSession.json.data.sessionToken;
 assert.equal((await post('/api/flow-sessions/request',{...paymentBody,customerAnswers:{custom_access:'door',custom_extra:'hidden value'}},token,customerOrigin)).status,400);
 assert.equal((await post('/api/flow-sessions/request',paymentBody,token,customerOrigin)).status,200);
 const held=await post('/api/flow-sessions/hold',{},token,customerOrigin);assert.equal(held.status,200);
 const paid=await post('/api/flow-sessions/mock-payment',{},token,customerOrigin);assert.equal(paid.status,200);assert.equal(paid.json.data.state,'confirmed');
 assert.deepEqual((await pool.query('select amount::int,currency,provider,state from public.payments where booking_id=$1',[held.json.data.bookingId])).rows[0],{amount:12500,currency:'USD',provider:'staging_mock',state:'succeeded'});
 assert.equal((await pool.query('select status from public.capacity_holds where booking_id=$1',[held.json.data.bookingId])).rows[0].status,'consumed');
 // An uncommitted RPC holds only the target version tuple, fencing alias FK inserts.
 const guard=await pool.connect(),alias=await pool.connect();try{await guard.query('begin');await guard.query('set local role service_role');await guard.query('select public.rollback_conditional_customer_field_publication($1,$2,$3,$4,$5,$6::jsonb)',[actor,tenant,flow,id(103),id(101),JSON.stringify([customerOrigin])]);await alias.query('begin');await alias.query("set local lock_timeout='100ms'");await alias.query('insert into public.flow_installations(id,tenant_id,flow_id,version_id,allowed_origins) values($1,$2,$3,$4,$5::jsonb)',[id(502),tenant,flow,id(103),JSON.stringify([customerOrigin])]);await alias.query('rollback');await alias.query('begin');await alias.query("set local lock_timeout='100ms'");await assert.rejects(alias.query('insert into public.flow_installations(id,tenant_id,flow_id,version_id,allowed_origins) values($1,$2,$3,$4,$5::jsonb)',[id(501),tenant,flow,id(101),JSON.stringify([customerOrigin])]),(e:unknown)=>(e as {code?:string}).code==='55P03');}finally{await alias.query('rollback');await guard.query('rollback');alias.release();guard.release();}
 const originalHistory=await read('versions');assert.equal(originalHistory.status,200);assert.deepEqual(originalHistory.json.data.versions.map((v:any)=>v.renderSchemaVersion),[6,5,3]);assert.deepEqual(originalHistory.json.data.versions[0].customerFields,fields(3));assert.equal((await read('versions',flow,'foreign-token-123456')).status,403);
 const before=await snapshots();const result=await rollback();assert.deepEqual(result,{status:200,json:{ok:true,data:{flowId:flow,versionId:id(101),installationId:id(201),renderSchemaVersion:3,hostedPath:`/checkout/flow/${id(201)}`}}});assert.deepEqual(await snapshots(),before);assert.deepEqual(await read('rollback-receipt'),result);assert.equal((await read('versions')).json.data.versions.find((v:any)=>v.current).renderSchemaVersion,3);assert.deepEqual(await snapshots(),before);const replayAfterRollback=await post('/api/flow-sessions/mock-payment',{},token,customerOrigin);assert.equal(replayAfterRollback.status,200);assert.equal(replayAfterRollback.json.data.replayed,true);assert.equal(replayAfterRollback.json.data.paymentId,paid.json.data.paymentId);assert.deepEqual(await snapshots(),before);assert.deepEqual((await pool.query('select name,published_version_id from public.flows where id=$1',[flow])).rows[0],{name:'Saved 1',published_version_id:id(101)});assert.equal((await rollback()).status,409);assert.equal((await rollback(id(101),id(102))).status,409);
 // Both already-issued session capabilities retain their immutable installation/version binding.
 const tomorrow=new Date();tomorrow.setUTCDate(tomorrow.getUTCDate()+1);tomorrow.setUTCHours(0,0,0,0);for(const session of [currentSession,historicalSession]){const r=await fetch(base+'/api/flow-sessions/availability?from='+encodeURIComponent(tomorrow.toISOString())+'&to='+encodeURIComponent(new Date(+tomorrow+86400000).toISOString()),{headers:{origin:customerOrigin,authorization:`Bearer ${session.json.data.sessionToken}`}});assert.equal(r.status,200);assert.equal((await r.json()).data.serviceId,service);}
 const forbiddenAnswerBody={schemaVersion:3,idempotencyKey:'rollback-pinned-answer-001',answers:{},customerAnswers:{},customer:{name:'Private customer',email:'private@example.test'},requestedStart:new Date(+tomorrow+36000000).toISOString()};
 assert.equal((await post('/api/flow-sessions/request',forbiddenAnswerBody,currentSession.json.data.sessionToken,customerOrigin)).status,400);
 assert.equal((await post('/api/flow-sessions/request',forbiddenAnswerBody,historicalSession.json.data.sessionToken,customerOrigin)).status,422);
 const newHistoricalSession=await post(`/api/installations/${id(201)}/sessions`,{},undefined,customerOrigin);assert.equal(newHistoricalSession.status,200);assert.equal(newHistoricalSession.json.data.render.publication.name,'Saved 1');const reissuedV6=await post('/api/installations/'+id(203)+'/sessions',{},undefined,customerOrigin);assert.equal(reissuedV6.status,200);assert.deepEqual(reissuedV6.json.data.render.customerFields,fields(3));
 await publish(4);await publish(5);const raceBefore=await snapshots();const race=await Promise.all([rollback(id(105),id(104)),rollback(id(105),id(102))]);assert.deepEqual(race.map(r=>r.status).sort(),[200,409]);assert.deepEqual(await snapshots(),raceBefore);const winning=race.find(r=>r.status===200)!.json.data;assert.equal((await pool.query('select published_version_id from public.flows where id=$1',[flow])).rows[0].published_version_id,winning.versionId);
 if(winning.versionId===id(104)){assert.equal((await rollback(id(104),id(102))).status,200);}assert.equal((await rollback(id(102),id(101))).status,200);assert.deepEqual(await snapshots(),raceBefore);
 await repo.call('save_paid_simple_draft',[actor,tenant,id(700),service,0,'Pure legacy','#4f46e5','compact']);await repo.call('publish_paid_simple_draft',[actor,tenant,id(700),1,id(701),id(702),[customerOrigin]]);await repo.call('save_paid_simple_draft',[actor,tenant,id(700),service,1,'Pure legacy2','#4f46e5','compact']);await repo.call('publish_paid_simple_draft',[actor,tenant,id(700),2,id(703),id(704),[customerOrigin]]);assert.equal((await rollback(id(703),id(701),undefined,tenant,id(700))).status,404);
 // Guarantee a V6 -> V5 result independently of which CAS race target wins.
 for(let revision=1;revision<=2;revision++){await repo.call(revision===1?'save_paid_customer_field_draft':'save_paid_conditional_customer_field_draft',[actor,tenant,id(800),service,revision-1,`V5 only ${revision}`,'#0e7490','compact',revision===1?fields(revision).slice(0,1):fields(revision)]);await repo.call(revision===1?'publish_paid_customer_field_draft':'publish_paid_conditional_customer_field_draft',[actor,tenant,id(800),revision,id(800+revision),id(810+revision),[customerOrigin]]);}
 const v5Before=await snapshots();assert.deepEqual(await rollback(id(802),id(801),undefined,tenant,id(800)),{status:200,json:{ok:true,data:{flowId:id(800),versionId:id(801),installationId:id(811),renderSchemaVersion:5,hostedPath:`/checkout/flow/${id(811)}`}}});assert.deepEqual(await snapshots(),v5Before);const v5Recovery=await read('rollback-receipt',id(800));assert.equal(v5Recovery.status,200);assert.equal(v5Recovery.json.data.renderSchemaVersion,5);assert.deepEqual(await snapshots(),v5Before);assert.equal((await read('versions',id(700))).status,404);
 // Verify lost-response read recovery for a committed prior V6 as well as V3/V5.
 for(let revision=3;revision<=4;revision++){await repo.call('save_paid_conditional_customer_field_draft',[actor,tenant,id(800),service,revision-1,`V6 history ${revision}`,'#0e7490','compact',fields(revision)]);await repo.call('publish_paid_conditional_customer_field_draft',[actor,tenant,id(800),revision,id(800+revision),id(810+revision),[customerOrigin]]);}
 const v6Before=await snapshots(),v6Rollback=await rollback(id(804),id(803),undefined,tenant,id(800));assert.equal(v6Rollback.status,200);assert.equal(v6Rollback.json.data.renderSchemaVersion,6);assert.deepEqual(await read('rollback-receipt',id(800)),v6Rollback);assert.deepEqual(await read('rollback-receipt',id(800)),v6Rollback);assert.equal((await rollback(id(804),id(803),undefined,tenant,id(800))).status,409);assert.deepEqual(await snapshots(),v6Before);
 // The dedicated history endpoint accepts fifty entries and denies overflow atomically.
 for(let revision=1;revision<=51;revision++){await repo.call('save_paid_conditional_customer_field_draft',[actor,tenant,id(900),service,revision-1,`History ${revision}`,'#0e7490','compact',fields(revision)]);await repo.call('publish_paid_conditional_customer_field_draft',[actor,tenant,id(900),revision,id(9000+revision),id(10000+revision),[customerOrigin]]);if(revision===50){const fifty=await read('versions',id(900));assert.equal(fifty.status,200);assert.equal(fifty.json.data.versions.length,50);}}
 const overflowBefore=await snapshots();assert.equal((await read('versions',id(900))).status,404);assert.equal((await read('rollback-receipt',id(900))).status,404);assert.deepEqual(await snapshots(),overflowBefore);
 for(const table of ['bookings','payments','capacity_holds','flow_requests'])assert.equal(Number((await pool.query(`select count(*) n from public.${table}`)).rows[0].n),1);
 console.log('PASS actual HTTP explicit mixed V3/V5/V6 rollback: exact pointer/name CAS; stale/no-op/newer/foreign/staff/revoked/inactive/catalogdrift/origin/ambiguous denials; two concurrent CAS one200/one409; immutable draft/version/install/session rows unchanged; both historical/current-issued sessions remain bound; one existing 12500 TEST confirmed booking/payment/consumed hold unchanged; no rollback financial writes');
}finally{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));await pool.end();}
