import assert from 'node:assert/strict';
import {Pool} from 'pg';
import {createFlowHttpServer} from './http';
import {createFlowRepository} from './repository';
import {createCustomerFieldPublicationReader} from './customer-field-publication-reader';
import {createCustomerAvailabilityReader} from './customer-availability';
import {createCustomerHoldWriter} from './customer-hold';
import {createCustomerMockPayment,createCustomerConfirmation} from './customer-payment';
assert.equal(process.env.CUSTOMER_FIELD_PUBLICATION_LOCAL_TEST,'1');
if(process.env.CI==='true'){assert.ok(['localhost','127.0.0.1'].includes(process.env.PGHOST??''));assert.equal(process.env.PGPORT,'5432');}
else{assert.equal(process.env.PGHOST,'127.0.0.1');assert.equal(process.env.PGPORT,'55436');}
assert.match(process.env.PGDATABASE??'',/^lumin_phase_a_fields_v5_/);for(const key of ['DATABASE_URL','PGHOSTADDR','PGSERVICE','PGSERVICEFILE','PGOPTIONS'])assert.ok(!process.env[key]);
const pool=new Pool({max:8}),id=(n:number)=>`52000000-0000-4000-8000-${String(n).padStart(12,'0')}`,actor=id(1),tenant=id(2),service=id(3),flow=id(4),foreign=id(9),foreignTenant=id(90),ownerOrigin='https://portal.example.test',customerOrigin='https://checkout.example.test';
const server=createFlowHttpServer({repository:createFlowRepository(pool),paidSimplePublication:true,paidCustomerFieldPublication:createCustomerFieldPublicationReader(pool,[customerOrigin]),ownerOrigins:[ownerOrigin],customerOrigins:[customerOrigin],authenticateOwner:async token=>token==='owner-token-123456'?actor:token==='foreign-token-123456'?foreign:null,customerAvailability:createCustomerAvailabilityReader(pool),customerHold:createCustomerHoldWriter(pool),customerMockPayment:createCustomerMockPayment(pool,{BOOKING_LUMIN_ENV:'staging',BOOKING_LUMIN_FAKE_PAYMENTS:'1'}),customerConfirmation:createCustomerConfirmation(pool)});
await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
async function post(path:string,body:unknown,token?:string,origin=customerOrigin){const r=await fetch(base+path,{method:'POST',headers:{origin,'content-type':'application/json',...(token?{authorization:`Bearer ${token}`}:{})},body:JSON.stringify(body)});return{status:r.status,json:await r.json()};}
const draftPath=`/api/paid-simple-flows/${flow}/draft?tenantId=${tenant}`,publishPath=`/api/paid-customer-field-flows/${flow}/publish-draft?tenantId=${tenant}`,legacyPublish=`/api/paid-simple-flows/${flow}/publish-draft?tenantId=${tenant}`;
const legacy={expectedRevision:0,serviceId:service,name:'Saved cleaning',presentation:{accentColor:'#0e7490',layout:'compact'}},fields=[{id:'custom_access',kind:'text',label:'Entry instructions',required:true,maxLength:20},{id:'custom_notes',kind:'text',label:'Notes',required:false,maxLength:4}];
const ownerPost=(path:string,body:unknown,token='owner-token-123456')=>post(path,body,token,ownerOrigin);
const publish=(revision:number)=>ownerPost(publishPath,{expectedDraftRevision:revision,allowedOrigins:[customerOrigin]});
const session=(installation:string)=>post(`/api/installations/${installation}/sessions`,{});
const submittedBody=(start:string,key='v5-http-request-key-001')=>({schemaVersion:2,idempotencyKey:key,answers:{},customerAnswers:{custom_access:' Gate 12 ',custom_notes:'😀😀'},customer:{name:'Customer',email:key+'@example.test'},requestedStart:start});
async function request(token:string,start:string,key?:string){return post('/api/flow-sessions/request',submittedBody(start,key),token);}
async function immutable(){return(await pool.query("select jsonb_agg(to_jsonb(v) order by id) versions from public.flow_versions v")).rows[0].versions;}
async function financial(booking:string){return(await pool.query("select state,pricing,payment_id,(select count(*)::int from public.payments p where p.booking_id=b.id) payment_count,(select status from public.capacity_holds h where h.booking_id=b.id) hold_status from public.bookings b where id=$1",[booking])).rows[0];}
try{
 await pool.query("insert into auth.users(id,email) values($1,'fields-v5-owner@example.test'),($2,'fields-v5-foreign@example.test')",[actor,foreign]);
 await pool.query("insert into public.tenants(id,name,slug,timezone,currency) values($1,'V5','fields-v5-http','UTC','USD'),($2,'Foreign','fields-v5-foreign','UTC','USD')",[tenant,foreignTenant]);
 await pool.query("insert into public.tenant_members(tenant_id,user_id,role) values($1,$2,'BUSINESS_OWNER'),($3,$4,'BUSINESS_OWNER')",[tenant,actor,foreignTenant,foreign]);
 await pool.query("insert into public.services(id,tenant_id,name,archetype,currency,base_price,duration_minutes) values($1,$2,'Catalog cleaning','simple','USD',12500,60)",[service,tenant]);
 await pool.query('insert into public.scheduling_policies(tenant_id,service_id,lead_time_minutes,horizon_days,slot_interval_minutes) values($1,$2,0,30,30)',[tenant,service]);
 await pool.query('insert into public.availability_rules(tenant_id,service_id,weekday,start_minute,end_minute,capacity) select $1,$2,n,0,1440,1 from generate_series(0,6)n',[tenant,service]);
 assert.equal((await ownerPost(draftPath,legacy)).status,200);const v3=await ownerPost(legacyPublish,{expectedDraftRevision:1,allowedOrigins:[customerOrigin]});assert.equal(v3.status,200);const original=(await session(v3.json.data.publication.installationId)).json.data;assert.equal(original.render.renderSchemaVersion,3);
 assert.equal((await publish(1)).status,422);assert.equal((await ownerPost(draftPath,{...legacy,schemaVersion:2,expectedRevision:1,customerFields:fields})).status,200);assert.equal((await ownerPost(legacyPublish,{expectedDraftRevision:2,allowedOrigins:[customerOrigin]})).status,422);
 for(const [body,token,status] of [[{expectedDraftRevision:2,allowedOrigins:[customerOrigin]},'foreign-token-123456',403],[{expectedDraftRevision:1,allowedOrigins:[customerOrigin]},'owner-token-123456',409],[{expectedDraftRevision:2,allowedOrigins:['https://foreign.example.test']},'owner-token-123456',403],[{expectedDraftRevision:2,allowedOrigins:[customerOrigin],price:1},'owner-token-123456',400]] as const)assert.equal((await ownerPost(publishPath,body,token)).status,status);
 const race=await Promise.all([publish(2),publish(2)]);assert.deepEqual(race.map(r=>r.status),[200,200]);assert.deepEqual(race[0],race[1]);const publication=race[0]!.json.data;assert.equal(publication.publication.renderSchemaVersion,5);assert.deepEqual(await publish(2),race[0]);assert.equal(Number((await pool.query('select count(*) n from public.flow_versions')).rows[0].n),2);
 const recoveryPath=`/api/paid-customer-field-flows/${flow}/publication?tenantId=${tenant}`;
 const recover=async(token='owner-token-123456')=>{const response=await fetch(base+recoveryPath,{headers:{origin:ownerOrigin,authorization:`Bearer ${token}`}});return{status:response.status,json:await response.json()};};
 const versionsBeforeRead=await immutable();for(let i=0;i<2;i++)assert.deepEqual(await recover(),{status:200,json:{ok:true,data:publication}});assert.deepEqual(await immutable(),versionsBeforeRead);assert.equal((await recover('foreign-token-123456')).status,404);
 const loaded=await session(publication.publication.installationId);assert.equal(loaded.status,200);const token=loaded.json.data.sessionToken,render=loaded.json.data.render;
 assert.deepEqual(render.customerFields,fields);assert.deepEqual(render.publication,{name:legacy.name,draftRevision:2,presentation:legacy.presentation});assert.deepEqual(render.service.price,{amount:12500,currency:'USD'});
 const tomorrow=new Date();tomorrow.setUTCDate(tomorrow.getUTCDate()+1);tomorrow.setUTCHours(0,0,0,0);const from=tomorrow.toISOString(),to=new Date(+tomorrow+86400000).toISOString();
 const availability=await fetch(base+'/api/flow-sessions/availability?from='+encodeURIComponent(from)+'&to='+encodeURIComponent(to),{headers:{origin:customerOrigin,authorization:`Bearer ${token}`}});assert.equal(availability.status,200);const slots=(await availability.json()).data.slots;assert.ok(slots.length);const start=slots.find((s:{start:string})=>s.start.includes('T10:00:00'))?.start??slots[0].start;
 for(const answers of [{},{custom_access:''},{custom_access:' \u00a0 '},{custom_access:'x'.repeat(21)},{custom_access:'Door',custom_notes:'😀😀a'},{custom_access:'Door',custom_other:'x'},{custom_access:1},{custom_access:'Door\ncode'},{custom_access:'\ud800'},{custom_access:'Door',custom_price:'1'}])assert.equal((await post('/api/flow-sessions/request',{...submittedBody(start),customerAnswers:answers},token)).status,400);
 assert.equal(Number((await pool.query('select count(*) n from public.bookings')).rows[0].n),0);
 assert.equal((await post('/api/flow-sessions/request',{...submittedBody(start),total:1},token)).status,400);assert.equal((await post('/api/flow-sessions/request',{...submittedBody(start),answers:{custom_access:{quantity:1}}},token)).status,400);
 const submitted=await request(token,start);assert.equal(submitted.status,200);assert.deepEqual(await request(token,start),submitted);assert.equal((await post('/api/flow-sessions/request',{...submittedBody(start),customerAnswers:{custom_access:'Changed'}},token)).status,409);
 assert.equal((await post('/api/flow-sessions/request',{idempotencyKey:'legacy-on-v5-request-001',answers:{},customer:submittedBody(start).customer,requestedStart:start},token)).status,422);assert.equal((await request(original.sessionToken,start,'v5-on-legacy-request-001')).status,422);
 const hold=await post('/api/flow-sessions/hold',{},token);assert.equal(hold.status,200);assert.deepEqual(await post('/api/flow-sessions/hold',{},token),hold);const booking=hold.json.data.bookingId;
 assert.deepEqual((await pool.query('select selection,pricing from public.bookings where id=$1',[booking])).rows[0],{selection:{serviceId:service},pricing:{}});assert.deepEqual((await pool.query('select customer_answers,option_answers from public.flow_requests where booking_id=$1',[booking])).rows[0],{customer_answers:submittedBody(start).customerAnswers,option_answers:null});
 await assert.rejects(pool.query("update public.flow_requests set customer_answers='{}' where booking_id=$1",[booking]),{code:'55000'});
 await pool.query("update public.bookings set selection=selection||'{\"price\":1}'::jsonb where id=$1",[booking]);assert.equal((await post('/api/flow-sessions/mock-payment',{},token)).status,422);assert.equal((await financial(booking)).payment_count,0);await pool.query('update public.bookings set selection=$2::jsonb where id=$1',[booking,JSON.stringify({serviceId:service})]);
 assert.equal((await post('/api/flow-sessions/mock-payment',{amount:1},token)).status,400);assert.equal((await post('/api/flow-sessions/mock-payment',{},'b'.repeat(43))).status,403);
 const paid=await post('/api/flow-sessions/mock-payment',{},token);assert.equal(paid.status,200);assert.deepEqual(paid.json.data,{schemaVersion:1,bookingId:booking,paymentId:paid.json.data.paymentId,state:'confirmed',replayed:false,provider:'staging_mock',simulated:true});
 const replay=await post('/api/flow-sessions/mock-payment',{},token);assert.equal(replay.status,200);assert.equal(replay.json.data.replayed,true);assert.equal(replay.json.data.paymentId,paid.json.data.paymentId);assert.equal((await post('/api/flow-sessions/confirm',{},token)).json.data.replayed,true);
 assert.deepEqual((await pool.query('select amount::int,currency,provider,state from public.payments where booking_id=$1',[booking])).rows[0],{amount:12500,currency:'USD',provider:'staging_mock',state:'succeeded'});assert.equal((await financial(booking)).hold_status,'consumed');
 // Editing/publishing a new revision never rewrites either original V3 or V5 installation.
 const before=await immutable();assert.equal((await ownerPost(draftPath,{...legacy,schemaVersion:2,expectedRevision:2,name:'New saved name',customerFields:[{...fields[1]!,required:true},fields[0]!]})).status,200);assert.deepEqual(await immutable(),before);assert.equal((await publish(2)).status,409);
 const next=await publish(3);assert.equal(next.status,200);assert.deepEqual(await recover(),{status:200,json:{ok:true,data:next.json.data}});assert.notEqual(next.json.data.publication.versionId,publication.publication.versionId);const oldLoaded=await session(publication.publication.installationId);assert.deepEqual(oldLoaded.json.data.render,render);assert.deepEqual((await session(v3.json.data.publication.installationId)).json.data.render,original.render);
 // Existing V3 submission remains exact and informational V5 fields never reach it.
 assert.equal((await post('/api/flow-sessions/request',{idempotencyKey:'legacy-after-v5-key-001',answers:{},customer:{name:'Legacy',email:'legacy-v5@example.test'},requestedStart:new Date(Date.parse(start)+6*3600000).toISOString()},original.sessionToken)).status,200);
 await pool.query('update public.services set base_price=13000 where id=$1',[service]);assert.equal((await session(publication.publication.installationId)).status,422);assert.equal((await post('/api/flow-sessions/mock-payment',{},token)).status,422);assert.equal((await publish(3)).status,409);await pool.query('update public.services set base_price=12500 where id=$1',[service]);
 // An expired hold during a blocked existing payment transaction rolls all financial writes back.
 const token2=oldLoaded.json.data.sessionToken,start2=new Date(Date.parse(start)+2*3600000).toISOString();assert.equal((await request(token2,start2,'v5-http-request-key-002')).status,200);const booking2=(await post('/api/flow-sessions/hold',{},token2)).json.data.bookingId;
 await pool.query("update public.capacity_holds set expires_at=clock_timestamp()+interval '2 seconds' where booking_id=$1",[booking2]);const blocker=await pool.connect();try{
  await blocker.query('begin');await blocker.query('lock table public.payments in share row exclusive mode');const pending=post('/api/flow-sessions/mock-payment',{},token2);let waiting=false;
  for(let i=0;i<100;i++){waiting=(await pool.query("select exists(select 1 from pg_stat_activity where datname=current_database() and wait_event_type='Lock' and query='lock table public.payments in share row exclusive mode') waiting")).rows[0].waiting;if(waiting)break;await new Promise(r=>setTimeout(r,10));}
  assert.ok(waiting);await new Promise(r=>setTimeout(r,2100));await blocker.query('rollback');assert.equal((await pending).status,409);
 }finally{await blocker.query('rollback');blocker.release();}
 assert.deepEqual(await financial(booking2),{state:'draft',pricing:{},payment_id:null,payment_count:0,hold_status:'active'});
 // Final capability expiry must also roll back writes after a real lock wait.
 const token3=(await session(publication.publication.installationId)).json.data.sessionToken,start3=new Date(Date.parse(start)+4*3600000).toISOString();assert.equal((await request(token3,start3,'v5-http-request-key-003')).status,200);const booking3=(await post('/api/flow-sessions/hold',{},token3)).json.data.bookingId;
 await pool.query("update public.flow_sessions set expires_at=clock_timestamp()+interval '2 seconds' where token_hash=encode(sha256(convert_to($1,'UTF8')),'hex')",[token3]);const sessionBlocker=await pool.connect();try{
  await sessionBlocker.query('begin');await sessionBlocker.query('lock table public.payments in share row exclusive mode');const pending=post('/api/flow-sessions/mock-payment',{},token3);let waiting=false;
  for(let i=0;i<100;i++){waiting=(await pool.query("select exists(select 1 from pg_stat_activity where datname=current_database() and wait_event_type='Lock' and query='lock table public.payments in share row exclusive mode') waiting")).rows[0].waiting;if(waiting)break;await new Promise(r=>setTimeout(r,10));}
  assert.ok(waiting);await new Promise(r=>setTimeout(r,2100));await sessionBlocker.query('rollback');assert.equal((await pending).status,403);
 }finally{await sessionBlocker.query('rollback');sessionBlocker.release();}
 assert.deepEqual(await financial(booking3),{state:'draft',pricing:{},payment_id:null,payment_count:0,hold_status:'active'});
 await pool.query("update public.flow_sessions set expires_at=clock_timestamp()-interval '1 second' where token_hash=encode(sha256(convert_to($1,'UTF8')),'hex')",[token]);assert.equal((await post('/api/flow-sessions/confirm',{},token)).status,403);
 await pool.query("update public.tenant_members set role='BUSINESS_STAFF' where tenant_id=$1 and user_id=$2",[tenant,actor]);assert.equal((await publish(3)).status,403);assert.equal((await recover()).status,404);await pool.query('delete from public.tenant_members where tenant_id=$1 and user_id=$2',[tenant,actor]);assert.equal((await publish(3)).status,403);
 assert.equal(Number((await pool.query('select count(*) n from public.payments')).rows[0].n),1);
 console.log('PASS actual HTTP V5 exact immutable saved fields; V3 compatibility; concurrent same-revision exact publication replay; malformed/required/UTF16/unknown/financial answer rejection; private exact answer provenance; existing availability/hold/server12500 mock confirmation and replays; catalog/owner/foreign/session expiry; expired hold rollback; no real provider');
}catch(error){const location=error instanceof Error?error.stack?.split('\n').find(s=>s.includes('at <anonymous>')&&s.includes('customer-field-publication.integration.ts')):'';throw new Error('V5 publication integration failed: '+((error as {code?:string}).code??'unknown')+' '+(location??''));}finally{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));await pool.end();}
