import {afterEach,describe,expect,it,vi} from 'vitest';
import type {Pool} from 'pg';
import type {Server} from 'node:http';
import {createFlowHttpServer} from './http';
import {createFlowRepository} from './repository';
import {AnyPaidSimpleDraft,PaidSimpleDraftList,RpcResults,SavePaidCustomerFieldDraft} from './contracts';
const id=(n:number)=>`49000000-0000-4000-8000-${String(n).padStart(12,'0')}`,actor=id(1),tenant=id(2),flow=id(3),service=id(4),origin='https://portal.example.test';
const fields=[{id:'custom_access',kind:'text',label:'Access notes',required:false,maxLength:500},{id:'custom_contact',kind:'text',label:'Contact notes',required:true,maxLength:100}];
const body={schemaVersion:2,expectedRevision:0,serviceId:service,name:'Cleaning',presentation:{accentColor:'#4f46e5',layout:'stacked'},customerFields:fields};
const draft={schemaVersion:2,flowId:flow,revision:1,serviceId:service,name:body.name,presentation:body.presentation,customerFields:fields};
let server:Server;afterEach(async()=>{server?.closeAllConnections();if(server)await new Promise<void>(r=>server.close(()=>r()));});
async function http(enabled=true){const call=vi.fn(async(name:string,p:readonly unknown[])=>name==='get_paid_simple_draft'?draft:{schemaVersion:2,flowId:p[2],revision:Number(p[4])+1});server=createFlowHttpServer({repository:{call},paidSimplePublication:enabled,ownerOrigins:[origin],customerOrigins:['https://checkout.example.test'],authenticateOwner:async token=>token==='owner-token-123456'?actor:null});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));return{call,request:(b:unknown=body,method='POST',token='owner-token-123456',o=origin,q=`tenantId=${tenant}`)=>fetch(`http://127.0.0.1:${(server.address() as {port:number}).port}/api/paid-simple-flows/${flow}/draft?${q}`,{method,headers:{origin:o,authorization:`Bearer ${token}`,'content-type':'application/json'},...(method==='GET'?{}:{body:JSON.stringify(b)})})};}
describe('versioned additional customer field authoring',()=>{
 it('passes exact ordered informational metadata with trusted owner identity',async()=>{const f=await http(),r=await f.request();expect(r.status).toBe(200);expect(await r.json()).toEqual({ok:true,data:{schemaVersion:2,flowId:flow,revision:1}});expect(f.call).toHaveBeenCalledWith('save_paid_customer_field_draft',[actor,tenant,flow,service,0,'Cleaning','#4f46e5','stacked',fields]);const read=await f.request(undefined,'GET');expect(read.status).toBe(200);expect(await read.json()).toEqual({ok:true,data:draft});expect(read.headers.get('cache-control')).toBe('no-store');});
 it.each([{schemaVersion:1},{schemaVersion:3},{schemaVersion:undefined},{customerFields:undefined},{price:1},{tenantId:tenant},{provider:'stripe'},{role:'BUSINESS_OWNER'},{expectedRevision:-1},{expectedRevision:0.5},{expectedRevision:Number.MAX_SAFE_INTEGER},{customerFields:[...fields,fields[0]]},{customerFields:[{...fields[0],kind:'quantity'}]},{customerFields:[{...fields[0],price:1}]},{customerFields:[{...fields[0],label:'bad\u0000'}]}])('rejects widened/unsupported authoring rather than stripping %j',async change=>{const f=await http();expect((await f.request({...body,...change})).status).toBe(400);expect(f.call).not.toHaveBeenCalled();});
 it('keeps legacy receipts compatible and returns full explicit v2 fields in discovery',()=>{const {schemaVersion:_,customerFields:__,...legacy}=draft;expect(AnyPaidSimpleDraft.parse(legacy)).toEqual(legacy);expect(PaidSimpleDraftList.parse({drafts:[draft]})).toEqual({drafts:[draft]});expect(AnyPaidSimpleDraft.safeParse({...draft,schemaVersion:3}).success).toBe(false);expect(AnyPaidSimpleDraft.safeParse({...legacy,customerFields:fields}).success).toBe(false);expect(SavePaidCustomerFieldDraft.parse({...body,customerFields:[...fields].reverse()}).customerFields).toEqual([...fields].reverse());});
 it('requires staging gate, fresh owner and exact origin/query',async()=>{const f=await http(false);expect((await f.request()).status).toBe(422);expect((await f.request(body,'POST','forged-token-123456')).status).toBe(401);expect((await f.request(body,'POST',undefined,'https://checkout.example.test')).status).toBe(403);expect((await f.request(body,'POST',undefined,undefined,`tenantId=${tenant}&schemaVersion=2`)).status).toBe(400);expect(f.call).not.toHaveBeenCalled();});
 it.each([{flowId:id(9),revision:1,schemaVersion:2},{flowId:flow,revision:2,schemaVersion:2},{flowId:flow,revision:1,schemaVersion:1},{flowId:flow,revision:1,schemaVersion:2,price:1}])('rolls back mismatched save evidence before commit %j',async result=>{const query=vi.fn(async(sql:string)=>sql.startsWith('select')?{rows:[{result}]}:{rows:[]}),release=vi.fn(),repo=createFlowRepository({connect:async()=>({query,release})} as unknown as Pool);await expect(repo.call('save_paid_customer_field_draft',[actor,tenant,flow,service,0,'Cleaning','#4f46e5','stacked',fields])).rejects.toMatchObject({code:'INTERNAL_ERROR'});expect(query).toHaveBeenLastCalledWith('rollback');expect(release).toHaveBeenCalledOnce();});
 it('uses fixed parameterized RPC and binds receipt before commit',async()=>{const result={schemaVersion:2,flowId:flow,revision:1},query=vi.fn(async(sql:string)=>sql.startsWith('select')?{rows:[{result}]}:{rows:[]}),repo=createFlowRepository({connect:async()=>({query,release:vi.fn()})} as unknown as Pool);expect(await repo.call('save_paid_customer_field_draft',[actor,tenant,flow,service,0,'Cleaning','#4f46e5','stacked',fields])).toEqual(result);expect(query.mock.calls[2]![0]).toBe('select public.save_paid_customer_field_draft($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::bigint,$6::text,$7::text,$8::text,$9::jsonb) as result');expect(query).toHaveBeenLastCalledWith('commit');expect(RpcResults.get_paid_simple_draft.parse(draft)).toEqual(draft);});
});
