import {afterEach,describe,expect,it,vi} from 'vitest';
import type {Pool} from 'pg';
import type {Server} from 'node:http';
import {createCustomerFieldVersionHistoryReader,CustomerFieldVersionHistory} from './customer-field-version-history';
import {createFlowHttpServer} from './http';
import {FlowError} from './repository';
const id=(n:number)=>`43000000-0000-4000-8000-${String(n).padStart(12,'0')}`,actor=id(1),tenant=id(2),flow=id(3),version=id(4),installation=id(5),origin='https://portal.example.test',customerOrigin='https://checkout.example.test';
const metadata={name:'Pinned draft',draftRevision:2,presentation:{accentColor:'#4f46e5' as const,layout:'compact' as const}};
const snapshot={renderSchemaVersion:5,submissionMode:'paid_customer_field_request',paymentMode:'staging_mock',simulated:true,service:{id:id(6),name:'Housekeeping',durationMinutes:60,price:{amount:12500,currency:'USD'}},publication:metadata,customerFields:[{id:'custom_access',kind:'text' as const,label:'Access instructions',required:true,maxLength:50}]};
const row={tenantId:tenant,flowId:flow,versionId:version,sourceRevision:'2',renderSchemaVersion:5,snapshot,serviceId:snapshot.service.id,boundSnapshot:snapshot.service,config:{key:'paid_customer_field',steps:[{key:'service',kind:'info',title:'Housekeeping'}]},installations:[{installationId:installation,allowedOrigins:[customerOrigin]}]};
const receipt={versionId:version,installationId:installation,renderSchemaVersion:5 as const,hostedPath:`/checkout/flow/${installation}`};
const good={flowId:flow,versions:[{versionId:version,...metadata,renderSchemaVersion:5 as const,customerFields:snapshot.customerFields,current:true,publication:receipt}]};
const access={tenantId:tenant,flowId:flow,currentVersionId:version,currentSchema:5};
function db(rows:unknown[]=[row],authorized:unknown[]=[access],fail=false){const release=vi.fn(),query=vi.fn(async(sql:string)=>{if(sql.startsWith('select')){if(authorized.length!==1||(authorized[0] as typeof access).tenantId!==tenant)throw{code:'42501'};if(fail)throw new Error('private DB detail');const a=authorized[0] as typeof access;return{rows:[{result:{flowId:a.flowId,currentVersionId:a.currentVersionId,currentSchema:a.currentSchema,versions:rows}}]};}return{rows:[]};});return{read:createCustomerFieldVersionHistoryReader({connect:async()=>({query,release})} as unknown as Pool,[customerOrigin]),query,release};}
describe('immutable owner V5 history reader',()=>{
 it('retains earlier V3 metadata without inventing customer fields',async()=>{const {customerFields,...oldSnapshot}=snapshot;const prior={...row,versionId:id(7),sourceRevision:'1',renderSchemaVersion:3,snapshot:{...oldSnapshot,renderSchemaVersion:3,submissionMode:'paid_service_request',publication:{...metadata,draftRevision:1}},config:{...row.config,key:'paid_simple'},installations:[{installationId:id(8),allowedOrigins:[customerOrigin]}]};const result=await db([row,prior]).read(actor,tenant,flow);expect(result.versions[1]).toMatchObject({renderSchemaVersion:3,current:false,publication:{renderSchemaVersion:3}});expect(result.versions[1]).not.toHaveProperty('customerFields');expect(result.versions[0]).toHaveProperty('customerFields',customerFields);});
 it.each([{...snapshot,customerFields:[...snapshot.customerFields,...snapshot.customerFields]},{...snapshot,customerFields:[{...snapshot.customerFields[0],kind:'price'}]},{...snapshot,customerAnswers:{custom_access:'private answer'}},{...snapshot,customerFields:[{...snapshot.customerFields[0],label:'Bad\u0085label'}]}])('rejects tampered definitions or submitted-answer leakage',async bad=>{await expect(db([{...row,snapshot:bad}]).read(actor,tenant,flow)).rejects.toMatchObject({code:'NOT_AVAILABLE'});});
 it('rejects a receipt belonging to a different render schema or widening of V3',()=>{expect(CustomerFieldVersionHistory.safeParse({...good,versions:[{...good.versions[0],publication:{...receipt,renderSchemaVersion:3}}]}).success).toBe(false);expect(CustomerFieldVersionHistory.safeParse({...good,versions:[{...good.versions[0],renderSchemaVersion:3}]}).success).toBe(false);});
 it('uses only fixed owner read RPC with repeatable snapshot',async()=>{const f=db();expect(await f.read(actor,tenant,flow)).toEqual(good);expect(f.query.mock.calls.filter(c=>!c[0].startsWith('select')).map(c=>c[0])).toEqual(['begin isolation level repeatable read',"set local statement_timeout='5s'","set local lock_timeout='3s'",'set local role service_role','commit']);expect(f.query).toHaveBeenNthCalledWith(5,'select public.owner_customer_field_version_history($1::uuid,$2::uuid,$3::uuid) as result',[actor,tenant,flow]);expect(f.release).toHaveBeenCalledOnce();});
 it.each([[],[row,row],[{...row,tenantId:id(9)}],[{...row,flowId:id(9)}],[{...row,renderSchemaVersion:4}],[{...row,sourceRevision:'3'}],[{...row,sourceRevision:'9007199254740992'}],[{...row,snapshot:{...snapshot,publication:undefined}}],[{...row,snapshot:{...snapshot,versionId:version}}],[{...row,boundSnapshot:{...snapshot.service,name:'Changed'}}],[{...row,serviceId:id(9)}],[{...row,config:{...row.config,key:'foreign'}}],[{...row,versionId:id(9)}],[{...row,snapshot:{...snapshot,publication:{...metadata,presentation:{accentColor:'url(x)',layout:'compact'}}}}]].map(rows=>({rows})))('fails the complete history on malformed/legacy/binding evidence',async ({rows})=>{const f=db(rows);await expect(f.read(actor,tenant,flow)).rejects.toMatchObject({code:'NOT_AVAILABLE'});expect(f.query).toHaveBeenLastCalledWith('rollback');});
 it.each([[],[{installationId:installation,allowedOrigins:['https://foreign.example.test']}],[{installationId:installation,allowedOrigins:[customerOrigin,customerOrigin]}],[{installationId:installation,allowedOrigins:['https://checkout.example.test:443']}],row.installations.concat(row.installations),[{installationId:'invalid',allowedOrigins:[customerOrigin]}]].map(installations=>({installations})))('preserves immutable metadata without usable installation receipt',async ({installations})=>{const result=await db([{...row,installations}]).read(actor,tenant,flow);expect(result).toEqual({flowId:flow,versions:[{...good.versions[0]!,publication:null}]});});
 it('returns descending revisions, with only exact current pointer marked',async()=>{const older={...row,versionId:id(7),sourceRevision:'1',snapshot:{...snapshot,publication:{...metadata,name:'Historical name',draftRevision:1}},installations:[]};const result=await db([row,older]).read(actor,tenant,flow);expect(result.versions.map(v=>[v.draftRevision,v.current,v.name])).toEqual([[2,true,'Pinned draft'],[1,false,'Historical name']]);});
 it('rejects overflow and duplicate/unsorted revision identities',async()=>{const rows=Array.from({length:51},(_,i)=>({...row,versionId:id(100+i),sourceRevision:String(51-i),snapshot:{...snapshot,publication:{...metadata,draftRevision:51-i}}}));await expect(db(rows).read(actor,tenant,flow)).rejects.toMatchObject({code:'NOT_AVAILABLE'});expect(CustomerFieldVersionHistory.safeParse({...good,versions:[...good.versions,...good.versions]}).success).toBe(false);});
 it.each([[],[{...access,tenantId:id(9)}]].map(authorized=>({authorized})))('denies absent current owner',async ({authorized})=>{await expect(db([row],authorized).read(actor,tenant,flow)).rejects.toMatchObject({code:'FORBIDDEN'});});
 it('denies missing or non-V5 current flow and redacts database errors',async()=>{await expect(db([row],[{...access,currentSchema:4}]).read(actor,tenant,flow)).rejects.toMatchObject({code:'NOT_AVAILABLE'});await expect(db([row],[access],true).read(actor,tenant,flow)).rejects.toMatchObject({code:'INTERNAL_ERROR',message:'INTERNAL_ERROR'});await expect(db().read('invalid',tenant,flow)).rejects.toMatchObject({code:'INVALID_REQUEST'});});
});
let server:Server;afterEach(async()=>{server?.closeAllConnections();if(server)await new Promise<void>(r=>server.close(()=>r()));});
async function http(value:unknown=good,enabled=true){const read=vi.fn(async()=>{if(value instanceof Error)throw value;return value as typeof good;}),call=vi.fn();server=createFlowHttpServer({repository:{call},paidSimplePublication:enabled,paidCustomerFieldVersionHistory:read,ownerOrigins:[origin],customerOrigins:[customerOrigin],authenticateOwner:async token=>token==='owner-token-123456'?actor:null});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));return{call,read,get:(query=`tenantId=${tenant}`,token='owner-token-123456',o=origin,method='GET')=>fetch(`http://127.0.0.1:${(server.address() as {port:number}).port}/api/paid-customer-field-flows/${flow}/versions?${query}`,{method,headers:{origin:o,authorization:`Bearer ${token}`}})};}
describe('history owner transport',()=>{
 it('returns strict pinned metadata only, binds flow and invokes no writer',async()=>{const f=await http();const r=await f.get();expect(r.status).toBe(200);expect(r.headers.get('cache-control')).toBe('no-store');expect(await r.json()).toEqual({ok:true,data:good});expect(f.read).toHaveBeenCalledWith(actor,tenant,flow);expect(f.call).not.toHaveBeenCalled();});
 it.each(['','tenantId=bad',`tenantId=${tenant}&tenantId=${tenant}`,`tenantId=${tenant}&retry=true`])('denies widened query %s',async q=>{const f=await http();expect((await f.get(q)).status).toBe(400);expect(f.read).not.toHaveBeenCalled();});
 it('requires fresh owner origin, staging gate and GET',async()=>{const f=await http(good,false);expect((await f.get()).status).toBe(422);expect((await f.get(undefined,'invalid-token-123456')).status).toBe(401);expect((await f.get(undefined,undefined,customerOrigin)).status).toBe(403);expect(f.read).not.toHaveBeenCalled();});
 it('rejects mutation and inconsistent identity without writer authority',async()=>{const f=await http({...good,flowId:id(9)});expect((await f.get()).status).toBe(500);expect((await f.get(undefined,undefined,undefined,'POST')).status).toBe(404);expect(f.call).not.toHaveBeenCalled();});
 it.each([['FORBIDDEN',403],['NOT_AVAILABLE',404]] as const)('preserves safe %s failures',async(code,status)=>{const f=await http(new FlowError(code));const r=await f.get();expect(r.status).toBe(status);expect(await r.json()).toEqual({ok:false,code});});
});
