import assert from 'node:assert/strict';
import {Pool} from 'pg';
import {createFlowHttpServer} from './http';
import {createFlowRepository} from './repository';
import {createPaidDraftListReader} from './paid-draft-list-reader';
assert.equal(process.env.CUSTOMER_FIELD_DRAFT_LOCAL_TEST,'1');if(process.env.CI==='true'){assert.ok(['localhost','127.0.0.1'].includes(process.env.PGHOST??''));assert.equal(process.env.PGPORT,'5432');}else{assert.equal(process.env.PGHOST,'127.0.0.1');assert.equal(process.env.PGPORT,'55436');}assert.match(process.env.PGDATABASE??'',/^lumin_phase_a_customer_fields_/);for(const key of ['DATABASE_URL','PGHOSTADDR','PGSERVICE','PGSERVICEFILE','PGOPTIONS'])assert.ok(!process.env[key]);
const pool=new Pool({max:8}),id=(n:number)=>`49000000-0000-4000-8000-${String(n).padStart(12,'0')}`,actor=id(1),tenant=id(2),service=id(3),flow=id(4),foreign=id(9),foreignTenant=id(90),origin='https://portal.example.test',customerOrigin='https://checkout.example.test';
const server=createFlowHttpServer({repository:createFlowRepository(pool),paidSimplePublication:true,paidDrafts:createPaidDraftListReader(pool),ownerOrigins:[origin],customerOrigins:[customerOrigin],authenticateOwner:async token=>token==='owner-token-123456'?actor:token==='foreign-token-123456'?foreign:null});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
async function request(path:string,method='GET',body?:unknown,token='owner-token-123456',o=origin){const r=await fetch(base+path,{method,headers:{origin:o,authorization:`Bearer ${token}`,'content-type':'application/json'},...(method==='GET'?{}:{body:JSON.stringify(body)})});return{status:r.status,json:await r.json()};}
const draftPath=(f=flow,t=tenant)=>`/api/paid-simple-flows/${f}/draft?tenantId=${t}`,publishPath=`/api/paid-simple-flows/${flow}/publish-draft?tenantId=${tenant}`,legacy={expectedRevision:0,serviceId:service,name:'Cleaning',presentation:{accentColor:'#4f46e5',layout:'stacked'}},fields=[{id:'custom_access',kind:'text',label:'Access notes',required:false,maxLength:500},{id:'custom_contact',kind:'text',label:'Contact notes',required:true,maxLength:100}],v2={...legacy,schemaVersion:2,customerFields:fields};
const tables=['flows','flow_versions','flow_installations','bound_flow_services','bound_flow_versions','services','customers','flow_sessions','flow_requests','bookings','payments','capacity_holds','booking_state_history'];
async function stored(){const out=[];for(const table of tables)out.push((await pool.query(`select coalesce(jsonb_agg(x.row order by x.row::text),'[]') rows from(select to_jsonb(t) row from public.${table} t)x`)).rows[0].rows);return out;}
try{
 await pool.query("insert into auth.users(id,email) values($1,'customer-fields-owner@example.test'),($2,'customer-fields-foreign@example.test')",[actor,foreign]);await pool.query("insert into public.tenants(id,name,slug,timezone,currency) values($1,'Fields','customer-fields-http','UTC','USD'),($2,'Foreign','customer-fields-foreign','UTC','USD')",[tenant,foreignTenant]);await pool.query("insert into public.tenant_members(tenant_id,user_id,role) values($1,$2,'BUSINESS_OWNER'),($3,$4,'BUSINESS_OWNER')",[tenant,actor,foreignTenant,foreign]);await pool.query("insert into public.services(id,tenant_id,name,archetype,currency,base_price,duration_minutes) values($1,$2,'Cleaning','simple','USD',12500,60),($3,$4,'Foreign','simple','USD',12500,60)",[service,tenant,id(91),foreignTenant]);
 assert.equal((await request(draftPath())).status,404);assert.deepEqual(await request(draftPath(),'POST',legacy),{status:200,json:{ok:true,data:{flowId:flow,revision:1}}});const legacyRead=await request(draftPath());assert.equal(legacyRead.status,200);assert.ok(!('schemaVersion' in legacyRead.json.data));assert.ok(!('customerFields' in legacyRead.json.data));
 const publication=await request(publishPath,'POST',{expectedDraftRevision:1,allowedOrigins:[customerOrigin]});assert.equal(publication.status,200);const installation=publication.json.data.publication.installationId;const publicSession=await request(`/api/installations/${installation}/sessions`,'POST',{},undefined,customerOrigin);assert.equal(publicSession.status,200);const publicRender=publicSession.json.data.render;
 const immutableBefore=await stored(),upgraded={...v2,expectedRevision:1};assert.deepEqual(await request(draftPath(),'POST',upgraded),{status:200,json:{ok:true,data:{schemaVersion:2,flowId:flow,revision:2}}});const upgradedRead=await request(draftPath());assert.deepEqual(upgradedRead,{status:200,json:{ok:true,data:{schemaVersion:2,flowId:flow,revision:2,serviceId:service,name:legacy.name,presentation:legacy.presentation,customerFields:fields}}});assert.deepEqual(await stored(),immutableBefore);
 assert.equal((await request(draftPath(),'POST',upgraded)).status,409);assert.equal((await request(draftPath(),'POST',{...legacy,expectedRevision:2})).status,422);assert.deepEqual(await request(draftPath()),upgradedRead);assert.equal((await request(publishPath,'POST',{expectedDraftRevision:2,allowedOrigins:[customerOrigin]})).status,422);assert.deepEqual(await stored(),immutableBefore);
 const list=await request('/api/paid-simple-drafts?tenantId='+tenant);assert.equal(list.status,200);assert.deepEqual(list.json.data.drafts,[upgradedRead.json.data]);
 const update={...v2,expectedRevision:2,customerFields:[...fields].reverse()};const race=await Promise.all([request(draftPath(),'POST',update),request(draftPath(),'POST',{...update,customerFields:[{...fields[0]!,required:true},fields[1]!]})]);assert.deepEqual(race.map(r=>r.status).sort(),[200,409]);const current=await request(draftPath());assert.equal(current.json.data.revision,3);const winner=race.findIndex(r=>r.status===200);assert.deepEqual(current.json.data.customerFields,winner===0?update.customerFields:[{...fields[0]!,required:true},fields[1]!]);assert.equal((await request(draftPath(),'POST',update)).status,409);
 const ordered={...v2,expectedRevision:3,customerFields:[...fields].reverse()};assert.equal((await request(draftPath(),'POST',ordered)).status,200);assert.deepEqual((await request(draftPath())).json.data.customerFields,[...fields].reverse());assert.equal((await request(publishPath,'POST',{expectedDraftRevision:4,allowedOrigins:[customerOrigin]})).status,422);assert.deepEqual(await stored(),immutableBefore);
 // A fresh V2 draft never gets a flow/version/installation implicitly.
 const fresh=id(5);assert.equal((await request(draftPath(fresh),'POST',v2)).status,200);assert.equal(Number((await pool.query('select count(*) n from public.flows where id=$1',[fresh])).rows[0].n),0);assert.equal((await request(`/api/paid-simple-flows/${fresh}/publish-draft?tenantId=${tenant}`,'POST',{expectedDraftRevision:1,allowedOrigins:[customerOrigin]})).status,422);
 const legacyOther=id(6);assert.equal((await request(draftPath(legacyOther),'POST',legacy)).status,200);const mixed=await request('/api/paid-simple-drafts?tenantId='+tenant);assert.equal(mixed.status,200);assert.deepEqual(mixed.json.data.drafts.map((d:{flowId:string})=>d.flowId),[flow,fresh,legacyOther]);assert.deepEqual(mixed.json.data.drafts[0].customerFields,[...fields].reverse());assert.ok(!('schemaVersion' in mixed.json.data.drafts[2]));
 for(const change of [{schemaVersion:3},{tenantId:foreignTenant},{price:1},{customerFields:[{...fields[0],label:'bad\nlabel'}]},{customerFields:[fields[0],fields[0]]},{customerFields:[{...fields[0],kind:'quantity'}]},{customerFields:[{...fields[0],id:'custom_price'}]},{customerFields:[{...fields[0],maxLength:1001}]}])assert.equal((await request(draftPath(),'POST',{...v2,expectedRevision:4,...change})).status,400);
 assert.equal((await request(draftPath(),'POST',{...v2,expectedRevision:4,serviceId:id(91)})).status,403);assert.equal((await request(draftPath(),'POST',{...v2,expectedRevision:4},'foreign-token-123456')).status,403);assert.equal((await request(draftPath(flow,foreignTenant),'POST',{...v2,expectedRevision:4})).status,403);assert.equal((await request(draftPath(),'GET',undefined,'forged-token-123456')).status,401);assert.equal((await request(draftPath(),'GET',undefined,undefined,customerOrigin)).status,403);assert.equal((await request(draftPath(flow,foreignTenant),'GET',undefined,'foreign-token-123456')).status,404);
 await pool.query("update public.tenant_members set role='BUSINESS_STAFF' where tenant_id=$1 and user_id=$2",[tenant,actor]);assert.equal((await request(draftPath())).status,403);assert.equal((await request(draftPath(),'POST',{...v2,expectedRevision:4})).status,403);await pool.query('delete from public.tenant_members where tenant_id=$1 and user_id=$2',[tenant,actor]);assert.equal((await request(draftPath())).status,403);await pool.query("insert into public.tenant_members(tenant_id,user_id,role) values($1,$2,'BUSINESS_OWNER')",[tenant,actor]);await pool.query("update public.tenants set status='inactive' where id=$1",[tenant]);assert.equal((await request(draftPath())).status,403);await pool.query("update public.tenants set status='active' where id=$1",[tenant]);
 await pool.query('update public.services set tax_rate_bp=1 where id=$1',[service]);assert.equal((await request(draftPath(),'POST',{...v2,expectedRevision:4})).status,422);assert.equal((await request(draftPath())).status,422);await pool.query('update public.services set tax_rate_bp=0 where id=$1',[service]);assert.deepEqual((await stored()).filter((_,i)=>i!==tables.indexOf('services')),immutableBefore.filter((_,i)=>i!==tables.indexOf('services')));
 const afterSession=await request(`/api/installations/${installation}/sessions`,'POST',{},undefined,customerOrigin);assert.equal(afterSession.status,200);assert.deepEqual(afterSession.json.data.render,publicRender);assert.ok(!('customerFields' in publicRender));assert.equal(Number((await pool.query('select count(*) n from public.flow_versions')).rows[0].n),1);for(const table of ['bookings','payments','capacity_holds','flow_requests'])assert.equal(Number((await pool.query(`select count(*) n from public.${table}`)).rows[0].n),0);
 console.log('PASS actual HTTP customer field drafts: V1 exact compatibility; CAS upgrade and stale replay conflict; deterministic optional/required field ordering and mixed discovery; concurrent CAS one winner; legacy writes and V2 publish denied; existing immutable publication/render unchanged; no customer/financial writes; strict fields/origin/owner/tenant/catalog attacks');
}catch(error){const location=error instanceof Error?error.stack?.split('\n').find(s=>s.includes('at <anonymous>')&&s.includes('customer-field-draft.integration.ts')):'';throw new Error('Customer field draft integration failed: '+((error as {code?:string}).code??'unknown')+' '+(location??''));}finally{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));await pool.end();}
