import type {Pool} from 'pg';
import {randomUUID} from 'node:crypto';
import {isDeepStrictEqual} from 'node:util';
import {z} from 'zod';
import {CreateDetailingOffer,DetailingOfferReceipt,buildDetailingService} from '@lumin/contracts';
import {FlowError} from './repository';
const Uuid=z.string().uuid().transform(s=>s.toLowerCase());
export type DetailingOfferCreator=(actor:string,tenant:string,input:CreateDetailingOffer)=>Promise<DetailingOfferReceipt>;
export type DetailingOfferReader=(actor:string,tenant:string,service:string)=>Promise<DetailingOfferReceipt>;
async function transact(pool:Pool,actor:string,tenant:string,input:CreateDetailingOffer|string):Promise<DetailingOfferReceipt>{const ids=z.tuple([Uuid,Uuid]).safeParse([actor,tenant]);if(!ids.success)throw new FlowError('INVALID_REQUEST');[actor,tenant]=ids.data;const read=typeof input==='string',body=read?Uuid.safeParse(input):CreateDetailingOffer.safeParse(input);if(!body.success)throw new FlowError('INVALID_REQUEST');const client=await pool.connect();let broken=false;try{await client.query(read?'begin isolation level repeatable read':'begin');await client.query("set local statement_timeout='5s'");await client.query("set local lock_timeout='3s'");await client.query('set local role service_role');const result=read?await client.query('select public.owner_detailing_offer($1::uuid,$2::uuid,$3::uuid) as result',[actor,tenant,body.data]):await client.query('select public.create_auto_detailing_offer($1::uuid,$2::uuid,$3::uuid,$4::jsonb) as result',[actor,tenant,randomUUID(),JSON.stringify(body.data)]);const receipt=DetailingOfferReceipt.safeParse(result.rows[0]?.result);if(result.rows.length!==1||!receipt.success||receipt.data.tenantId!==tenant||(read?receipt.data.service.id!==body.data:!isDeepStrictEqual(receipt.data.service,buildDetailingService(receipt.data.service.id,tenant,body.data as CreateDetailingOffer))))throw new FlowError('INTERNAL_ERROR');await client.query('commit');return receipt.data;}catch(error){try{await client.query('rollback');}catch{broken=true;}if(error instanceof FlowError)throw error;const code=(error as {code?:string}).code;throw new FlowError(code==='42501'?'FORBIDDEN':code==='P0002'?'NOT_AVAILABLE':code==='0A000'?'UNSUPPORTED_CONFIG':code==='22023'?'INVALID_REQUEST':['23505','40001','40P01','55P03','57014'].includes(code??'')?'CONFLICT':'INTERNAL_ERROR');}finally{client.release(broken);}}
export function createDetailingOfferCreator(pool:Pool):DetailingOfferCreator{return(actor,tenant,input)=>transact(pool,actor,tenant,input);}
export function createDetailingOfferReader(pool:Pool):DetailingOfferReader{return(actor,tenant,service)=>transact(pool,actor,tenant,service);}
