import {afterEach,expect,it,vi} from 'vitest';
import {request as httpRequest,type Server} from 'node:http';
import {buildDetailingService} from '@lumin/contracts';
import {createPricingEngine} from '@lumin/core';
import {createDetailingPaymentApi,DetailingPaymentReadiness} from './detailing-payment';
import {createFlowHttpServer} from './http';
const id=(n:number)=>`66000000-0000-4000-8000-${String(n).padStart(12,'0')}`,service=id(4),tenant=id(2),origin='https://checkout.example.test',hash='a'.repeat(64),now=Date.parse('2030-01-01T00:00:00.000Z');
const catalog={name:'Detail',description:'',currency:'USD',durationMinutes:60,packages:[{id:'deluxe',label:'Deluxe',amount:15000}],vehicles:[{id:'suv',label:'SUV',multiplierBp:12500}],addons:[{id:'pet-hair',name:'Pet hair',amount:3000}],locations:[{id:'mobile',label:'Mobile',amount:2000}]};
const context={service:buildDetailingService(service,tenant,{...catalog,idempotencyKey:'reservation-fixture-0001'}),catalog,scheduling:{schemaVersion:1,businessType:'AUTO_DETAILING',tenantId:tenant,serviceId:service,timezone:'UTC',windows:[{id:id(10),weekday:3,startMinute:540,endMinute:1020,capacity:1}],policy:{id:id(20),leadTimeMinutes:0,horizonDays:30,slotIntervalMinutes:30}},render:{versionId:id(5),renderSchemaVersion:7,businessType:'AUTO_DETAILING',submissionMode:'detailing_quote',bookingMode:'unavailable',paymentMode:'unavailable',pricingModel:'package_subtotal_vehicle_multiplier',serviceId:service,catalog,publication:{name:'Detail form',presentation:{accentColor:'#4f46e5',layout:'stacked'},draftRevision:1}},installationId:id(6),expiresAt:'2030-01-10T00:00:00.000Z'};
const selection={packageId:'deluxe',vehicleId:'suv',addonIds:['pet-hair'],locationId:'mobile'},input={schemaVersion:1 as const,idempotencyKey:'reservation-test-0001',selection,customer:{name:'Fictional',email:'fictional@example.test'},requestedStart:'2030-01-02T09:00:00.000Z'},pricing=createPricingEngine().price(context.service,{serviceId:service,itemQuantities:{},addonIds:selection.addonIds,answers:{package:{choiceIds:['deluxe']},vehicle:{choiceIds:['suv']},location:{choiceIds:['mobile']}}});
const receipt={schemaVersion:1,versionId:id(5),installationId:id(6),serviceId:service,bookingId:id(30),reference:'LMN-ABC123',selection,pricing,slot:{start:input.requestedStart,end:'2030-01-02T10:00:00.000Z'},state:'draft',confirmed:false,paymentMode:'unavailable'};

const payment=id(40),env={BOOKING_LUMIN_ENV:'staging',BOOKING_LUMIN_FAKE_PAYMENTS:'1',BOOKING_LUMIN_DETAILING_PUBLICATION:'1'};
function fixture(options:{error?:string;drift?:boolean;expired?:boolean;badReceipt?:boolean;confirmed?:boolean}={}){let paid=options.confirmed??false,checks=0;const query=vi.fn(async(sql:string)=>{
 if(sql.includes('detailing_payment_target')){if(options.error)throw Object.assign(Error('private SQL details'),{code:options.error});checks++;return{rows:[{result:{context:options.drift&&checks===2?{...context,render:{...context.render,publication:{...context.render.publication,name:'Drift'}}}:context,receipt,booking:{id:receipt.bookingId,tenant_id:tenant,state:paid?'confirmed':'draft',payment_id:paid?payment:null,pricing},payments:paid?[{id:payment,tenant_id:tenant,provider:'staging_mock',provider_intent_id:'staging_mock:'+receipt.bookingId,state:'succeeded',amount:'25000',currency:'USD'}]:[]}}]};}
 if(sql.startsWith('insert into public.payments')){paid=true;return{rows:[{id:payment}]};}
 if(sql.includes('confirm_succeeded_payment'))return{rows:[{result:{bookingId:options.badReceipt?id(99):receipt.bookingId,paymentId:payment,state:'confirmed',replayed:checks>1}}]};return{rows:[]};
 });let clockChecks=0;const connect=vi.fn(async()=>({query,release:vi.fn()}));return{query,connect,api:createDetailingPaymentApi({connect} as never,[origin],env,()=>options.expired&&++clockChecks>=2?Date.parse(context.expiresAt):now)};}
it('derives exact configurable price and calls the shared sole confirmation, then rechecks before commit',async()=>{const f=fixture();const result=await f.api.mockPayment(hash,origin);expect(result).toMatchObject({bookingId:receipt.bookingId,paymentId:payment,versionId:receipt.versionId,installationId:receipt.installationId,serviceId:service,provider:'staging_mock',simulated:true,state:'confirmed'});expect(f.query).toHaveBeenCalledWith(expect.stringContaining('insert into public.payments'),[tenant,receipt.bookingId,'staging_mock:'+receipt.bookingId,25000,'USD']);expect(f.query.mock.calls.filter(([sql])=>sql.includes('confirm_succeeded_payment'))).toHaveLength(1);expect(f.query.mock.calls.some(([sql])=>sql.includes("state='confirmed'"))).toBe(false);expect(f.query).toHaveBeenLastCalledWith('commit');expect((await f.api.confirm(hash,origin)).replayed).toBe(true);});
it.each([{drift:true},{expired:true},{badReceipt:true}])('rolls back after unsafe final proof %j',async options=>{const f=fixture(options);await expect(f.api.mockPayment(hash,origin)).rejects.toMatchObject({code:options.expired?'FORBIDDEN':options.badReceipt?'INTERNAL_ERROR':'CONFLICT'});expect(f.query).toHaveBeenLastCalledWith('rollback');});
it.each(['42501','40001','55P03','40P01','57014','0A000'])('sanitizes SQLSTATE %s',async error=>{const f=fixture({error});await expect(f.api.mockPayment(hash,origin)).rejects.toMatchObject({code:error==='42501'?'FORBIDDEN':error==='0A000'?'UNSUPPORTED_CONFIG':'CONFLICT'});expect(f.query).toHaveBeenLastCalledWith('rollback');});
it('requires both feature gates and never connects on disabled or spoofed credentials',async()=>{const connect=vi.fn(),pool={connect} as never;for(const disabled of [{},{...env,BOOKING_LUMIN_DETAILING_PUBLICATION:'0'},{...env,BOOKING_LUMIN_FAKE_PAYMENTS:'0'}])await expect(createDetailingPaymentApi(pool,[origin],disabled).mockPayment(hash,origin)).rejects.toMatchObject({code:'UNSUPPORTED_CONFIG'});expect(()=>createDetailingPaymentApi(pool,[origin],{...env,BOOKING_LUMIN_ENV:'production'})).toThrow();const f=fixture();await expect(f.api.mockPayment('token',origin)).rejects.toMatchObject({code:'INVALID_REQUEST'});await expect(f.api.confirm(hash,'https://foreign.example')).rejects.toMatchObject({code:'INVALID_REQUEST'});expect(f.connect).not.toHaveBeenCalled();expect(connect).not.toHaveBeenCalled();});
const servers:Server[]=[];afterEach(async()=>{for(const s of servers.splice(0)){s.closeAllConnections();await new Promise<void>(r=>s.close(()=>r()));}});
it.each(['mock-payment','confirm'])('strict private %s HTTP denies client financial authority and legacy fallback',async route=>{const result={schemaVersion:1 as const,bookingId:receipt.bookingId,paymentId:payment,versionId:receipt.versionId,installationId:receipt.installationId,serviceId:service,state:'confirmed' as const,replayed:false,provider:'staging_mock' as const,simulated:true as const},api={readiness:vi.fn(),mockPayment:vi.fn(async()=>result),confirm:vi.fn(async()=>result)},legacy=vi.fn();const server=createFlowHttpServer({repository:{call:legacy},customerOrigins:[origin],ownerOrigins:[],detailingPublication:true,detailingPaymentApi:api});servers.push(server);await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${(server.address() as {port:number}).port}/api/detailing-flow-sessions/`;
 const post=(body:unknown,path=route,token='a'.repeat(43),o=origin)=>fetch(base+path,{method:'POST',headers:{origin:o,authorization:'Bearer '+token,'content-type':'application/json'},body:JSON.stringify(body)});
 expect((await post({})).status).toBe(200);for(const extra of [{amount:1},{tenantId:tenant},{bookingId:receipt.bookingId},{provider:'stripe'},{state:'succeeded'},{actorId:tenant}])expect((await post(extra)).status).toBe(400);expect((await post({},route+'?tenantId='+tenant)).status).toBe(400);expect((await post({},route,'bad')).status).toBe(401);expect((await post({},route,'a'.repeat(43),'https://foreign.example')).status).toBe(403);expect(legacy).not.toHaveBeenCalled();expect(api[route==='confirm'?'confirm':'mockPayment']).toHaveBeenCalledTimes(1);
});

it.each([false,true])('read-only readiness binds exact %s state without financial invocation',async confirmed=>{const f=fixture({confirmed});const r=await f.api.readiness(hash,origin);expect(r).toEqual({schemaVersion:1,versionId:receipt.versionId,installationId:receipt.installationId,serviceId:service,bookingId:receipt.bookingId,provider:'staging_mock',simulated:true,state:confirmed?'confirmed':'draft',canPay:!confirmed,canConfirm:confirmed});expect(f.query.mock.calls.filter(([sql])=>sql.includes('detailing_payment_target'))).toHaveLength(2);expect(f.query.mock.calls.some(([sql])=>/insert |update |confirm_succeeded_payment/i.test(sql))).toBe(false);expect(f.query).toHaveBeenLastCalledWith('commit');});
it.each([{drift:true},{expired:true},{error:'55P03'},{error:'42501'}])('readiness discards unsafe final context %j',async options=>{const f=fixture(options);await expect(f.api.readiness(hash,origin)).rejects.toMatchObject({code:options.expired||options.error==='42501'?'FORBIDDEN':'CONFLICT'});expect(f.query).toHaveBeenLastCalledWith('rollback');expect(f.query.mock.calls.some(([sql])=>sql.includes('confirm_succeeded_payment')||sql.startsWith('insert'))).toBe(false);});
it('readiness flags default closed before connection and rejects contradictory or secret-bearing receipts',async()=>{const connect=vi.fn();await expect(createDetailingPaymentApi({connect} as never,[origin],{}).readiness(hash,origin)).rejects.toMatchObject({code:'UNSUPPORTED_CONFIG'});expect(connect).not.toHaveBeenCalled();const r=await fixture().api.readiness(hash,origin);for(const changed of [{...r,canPay:false},{...r,canConfirm:true},{...r,tenantId:tenant},{...r,pricing},{...r,provider:'stripe'},{...r,sessionToken:hash}])expect(DetailingPaymentReadiness.safeParse(changed).success).toBe(false);});
it('GET readiness enforces no body/query/mutation and exact private bearer/origin',async()=>{const value=await fixture().api.readiness(hash,origin),readiness=vi.fn(async()=>value),mockPayment=vi.fn(),confirm=vi.fn(),legacy=vi.fn();const server=createFlowHttpServer({repository:{call:legacy},customerOrigins:[origin],ownerOrigins:[],detailingPublication:true,detailingPaymentApi:{readiness,mockPayment,confirm}});servers.push(server);await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${(server.address() as {port:number}).port}/api/detailing-flow-sessions/payment-readiness`;
 const get=(path=base,token='a'.repeat(43),o=origin)=>fetch(path,{headers:{origin:o,authorization:'Bearer '+token}});
 expect((await get()).status).toBe(200);expect(readiness).toHaveBeenCalledWith(expect.stringMatching(/^[0-9a-f]{64}$/),origin);expect((await get(base+'?tenantId='+tenant)).status).toBe(400);expect((await get(base,'bad')).status).toBe(401);expect((await get(base,'a'.repeat(43),'https://foreign.example')).status).toBe(403);expect((await fetch(base,{method:'POST',headers:{origin,authorization:'Bearer '+'a'.repeat(43),'content-type':'application/json'},body:'{}'})).status).toBe(400);
 const bodyStatus=await new Promise<number>((resolve,reject)=>{const req=httpRequest(base,{method:'GET',headers:{origin,authorization:'Bearer '+'a'.repeat(43),'content-length':'2'}},res=>{res.resume();res.on('end',()=>resolve(res.statusCode!));});req.on('error',reject);req.end('{}');});expect(bodyStatus).toBe(400);expect(readiness).toHaveBeenCalledTimes(1);expect(mockPayment).not.toHaveBeenCalled();expect(confirm).not.toHaveBeenCalled();expect(legacy).not.toHaveBeenCalled();
 readiness.mockResolvedValueOnce({...value,canPay:false} as never);expect((await get()).status).toBe(500);
});
