import {createDetailingPaymentApi} from './detailing-payment';
import {buildDetailingService,Selection} from '@lumin/contracts';
import {createPricingEngine} from '@lumin/core';
import assert from 'node:assert/strict';
import {Pool} from 'pg';
import {createFlowHttpServer} from './http';
import {createFlowRepository} from './repository';
import {createDetailingOfferCreator} from './detailing-catalog';
import {createDetailingSchedulingCreator} from './detailing-scheduling';
import {createDetailingPublicationApi} from './detailing-publication';
import {createDetailingAvailabilityReader} from './detailing-availability';
import {createDetailingReservationApi} from './detailing-reservation';
import {createHash} from 'node:crypto';
assert.equal(process.env.DETAILING_PAYMENT_LOCAL_TEST,'1');
if(process.env.CI==='true'){assert.ok(['localhost','127.0.0.1'].includes(process.env.PGHOST??''));assert.equal(process.env.PGPORT,'5432');}else{assert.equal(process.env.PGHOST,'127.0.0.1');assert.equal(process.env.PGPORT,'55436');}
assert.match(process.env.PGDATABASE??'',/^lumin_phase_a_detailing_payment_/);for(const key of ['DATABASE_URL','PGHOSTADDR','PGSERVICE','PGSERVICEFILE','PGPASSFILE','PGOPTIONS'])assert.ok(!process.env[key]);
const pool=new Pool({max:8}),id=(n:number)=>`68000000-0000-4000-8000-${String(n).padStart(12,'0')}`,actor=id(1),tenant=id(2),flow=id(3),foreign=id(8),foreignTenant=id(9),ownerOrigin='https://portal.example.test',origin='https://checkout.example.test';
const server=createFlowHttpServer({repository:createFlowRepository(pool),catalogAuthoring:true,detailingOfferCreate:createDetailingOfferCreator(pool),schedulingAuthoring:true,detailingSchedulingCreate:createDetailingSchedulingCreator(pool),detailingPublication:true,detailingPublicationApi:createDetailingPublicationApi(pool,[origin]),detailingAvailability:createDetailingAvailabilityReader(pool,[origin]),detailingReservationApi:createDetailingReservationApi(pool,[origin]),detailingPaymentApi:createDetailingPaymentApi(pool,[origin],{BOOKING_LUMIN_ENV:'staging',BOOKING_LUMIN_FAKE_PAYMENTS:'1',BOOKING_LUMIN_DETAILING_PUBLICATION:'1'}),ownerOrigins:[ownerOrigin],customerOrigins:[origin],authenticateOwner:async token=>token==='owner-token-123456'?actor:token==='foreign-token-123456'?foreign:null});
await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
async function req(path:string,body:unknown=undefined,token='owner-token-123456',o=ownerOrigin){const response=await fetch(base+path,{method:body===undefined?'GET':'POST',headers:{origin:o,authorization:`Bearer ${token}`,'content-type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});return{status:response.status,json:await response.json()};}
const nextDay=new Date();nextDay.setUTCDate(nextDay.getUTCDate()+1);nextDay.setUTCHours(0,0,0,0);const from=nextDay.toISOString(),to=new Date(nextDay.getTime()+86400000).toISOString();
async function fingerprint(){const data:Record<string,unknown>={};for(const table of ['services','service_questions','service_addons','business_profiles','owner_detailing_catalog_creations','owner_detailing_scheduling','availability_rules','availability_overrides','scheduling_policies','flows','flow_versions','bound_flow_versions','detailing_publications','flow_installations','bookings','capacity_holds','payments','flow_requests'])data[table]=(await pool.query(`select coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]') data from public.${table} x where tenant_id=$1`,[tenant])).rows[0].data;return data;}
try{
 await pool.query("insert into auth.users(id,email) values($1,'availability-owner@example.test'),($2,'availability-foreign@example.test')",[actor,foreign]);for(const [a,t] of [[actor,tenant],[foreign,foreignTenant]])await pool.query('select public.create_staging_business($1,$2,$3,$4,$5,$6,$7,$8)',[a,t,'Detailing availability',t,'UTC','USD','AUTO_DETAILING','detailing-availability-business-'+t]);
 const offer={name:'Scheduled detail package',description:'',currency:'USD',durationMinutes:60,packages:[{id:'basic',label:'Basic',amount:15000}],vehicles:[{id:'suv',label:'SUV',multiplierBp:12500}],addons:[{id:'pet-hair',name:'Pet hair',amount:3000}],locations:[{id:'mobile',label:'Mobile',amount:2000}],idempotencyKey:'detailing-availability-offer-0001'};
 const made=await req('/api/catalog/detailing-offers?tenantId='+tenant,offer);assert.equal(made.status,200,JSON.stringify(made));const service=made.json.data.service.id;
 const schedule={timezone:'UTC',windows:Array.from({length:7},(_,weekday)=>({weekday,startMinute:540,endMinute:1020,capacity:1})),policy:{leadTimeMinutes:0,horizonDays:30,slotIntervalMinutes:30},idempotencyKey:'detailing-availability-schedule-0001'};
 assert.equal((await req(`/api/catalog/detailing-offers/${service}/scheduling?tenantId=${tenant}`,schedule)).status,200);
 const path=(kind:string)=>`/api/detailing-flows/${flow}/${kind}?tenantId=${tenant}`;
 assert.equal((await req(path('draft'),{expectedRevision:0,serviceId:service,name:'Detail appointment',presentation:{accentColor:'#4f46e5',layout:'stacked'}})).status,200);
 const published=await req(path('publish-draft'),{expectedDraftRevision:1,allowedOrigins:[origin]});assert.equal(published.status,200);const receipt=published.json.data.publication;
 const issued=await req(`/api/detailing-installations/${receipt.installationId}/sessions`,{},'',origin);assert.equal(issued.status,200);const token=issued.json.data.sessionToken;
 const url='/api/detailing-flow-sessions/availability?'+new URLSearchParams({from,to}),availability=()=>req(url,undefined,token,origin);
 const empty=await availability();assert.equal(empty.status,200,JSON.stringify(empty));assert.equal(empty.json.data.versionId,receipt.versionId);assert.equal(empty.json.data.installationId,receipt.installationId);assert.equal(empty.json.data.expiresAt,issued.json.data.expiresAt);assert.equal(empty.json.data.serviceId,service);assert.equal(empty.json.data.durationMinutes,60);assert.equal(empty.json.data.timezone,'UTC');assert.equal(empty.json.data.slots.length,15);assert.equal(empty.json.data.slots[0].start,from.replace('00:00:00','09:00:00'));assert.ok(empty.json.data.slots.every((s:{remainingCapacity:number})=>s.remainingCapacity===1));assert.ok(!JSON.stringify(empty).includes(tenant));assert.ok(!JSON.stringify(empty).includes(actor));assert.ok(!JSON.stringify(empty).includes('15000'));
 const selection={packageId:'basic',vehicleId:'suv',addonIds:['pet-hair'],locationId:'mobile'};
 const body={schemaVersion:1,idempotencyKey:'detailing-payment-request-0001',selection,customer:{name:'Fictional payment',email:'payment@example.test'},requestedStart:empty.json.data.slots[0].start};
 const readiness=(t:string)=>req('/api/detailing-flow-sessions/payment-readiness',undefined,t,origin);
 const request=(t:string,b=body)=>req('/api/detailing-flow-sessions/request',b,t,origin),hold=(t:string)=>req('/api/detailing-flow-sessions/hold',{},t,origin),pay=(t:string,b:unknown={})=>req('/api/detailing-flow-sessions/mock-payment',b,t,origin),confirm=(t:string)=>req('/api/detailing-flow-sessions/confirm',{},t,origin);
 const requested=await request(token);assert.equal(requested.status,200,JSON.stringify(requested));const booking=requested.json.data.bookingId;
 assert.equal((await readiness(token)).status,409);assert.equal((await pay(token)).status,409);assert.equal((await hold(token)).status,200);
 const beforeRead=await fingerprint(),ready=await readiness(token);assert.equal(ready.status,200,JSON.stringify(ready));assert.deepEqual(ready.json.data,{schemaVersion:1,versionId:receipt.versionId,installationId:receipt.installationId,serviceId:service,bookingId:booking,provider:'staging_mock',simulated:true,state:'draft',canPay:true,canConfirm:false});assert.deepEqual(await fingerprint(),beforeRead);
 const before=await fingerprint(),race=await Promise.all([pay(token),pay(token)]);assert.deepEqual(race.map(r=>r.status).sort(),[200,200],JSON.stringify(race));assert.deepEqual(race.map(r=>r.json.data.replayed).sort(),[false,true]);
 const result=race.find(r=>!r.json.data.replayed)!.json.data;assert.equal(result.bookingId,booking);assert.equal(result.versionId,receipt.versionId);assert.equal(result.installationId,receipt.installationId);assert.equal(result.serviceId,service);assert.equal(result.provider,'staging_mock');assert.equal(result.simulated,true);assert.equal(result.state,'confirmed');
 const rows=(await pool.query('select b.state,b.payment_id,b.pricing,h.status,p.amount,p.currency,p.provider,p.provider_intent_id from public.bookings b join public.capacity_holds h on h.booking_id=b.id join public.payments p on p.id=b.payment_id where b.id=$1',[booking])).rows;assert.equal(rows.length,1);assert.equal(rows[0].state,'confirmed');assert.equal(rows[0].status,'consumed');assert.equal(Number(rows[0].amount),25000);assert.equal(rows[0].currency,'USD');assert.equal(rows[0].provider_intent_id,'staging_mock:'+booking);
 const counts=async()=>{const r:Record<string,number>={};for(const t of ['bookings','capacity_holds','payments','flow_requests','detailing_request_receipts','durable_outbox'])r[t]=Number((await pool.query(`select count(*) n from public.${t} where tenant_id=$1`,[tenant])).rows[0].n);return r;};const committed=await counts();assert.equal(committed.payments,1);
 const confirmedBefore=await fingerprint(),confirmedReady=await readiness(token);assert.equal(confirmedReady.status,200);assert.deepEqual(confirmedReady.json.data,{...ready.json.data,state:'confirmed',canPay:false,canConfirm:true});assert.deepEqual(await fingerprint(),confirmedBefore);assert.deepEqual(await counts(),committed);
 assert.deepEqual((await pay(token)).json.data,{...result,replayed:true});assert.deepEqual((await confirm(token)).json.data,{...result,replayed:true});assert.deepEqual(await counts(),committed);
 // The existing sole confirmation waits on the payment row, then replays after target commit.
 const holder=await pool.connect(),follower=await pool.connect();try{
  await holder.query('begin');await holder.query('set local role service_role');await holder.query('select public.detailing_payment_target($1,$2,$3::jsonb)',[createHash('sha256').update(token).digest('hex'),origin,JSON.stringify([origin])]);
  await follower.query('begin');await follower.query("set local lock_timeout='3s'");const pid=(await follower.query('select pg_backend_pid() pid')).rows[0].pid;
  const confirmation=follower.query('select public.confirm_succeeded_payment($1::uuid) result',[result.paymentId]);let waiting=false;for(let n=0;n<100;n++){if((await pool.query("select wait_event_type='Lock' waiting from pg_stat_activity where pid=$1",[pid])).rows[0]?.waiting){waiting=true;break;}await new Promise(r=>setTimeout(r,10));}assert.equal(waiting,true,'direct confirmation must wait payment-first');await holder.query('commit');assert.equal((await confirmation).rows[0].result.replayed,true);await follower.query('commit');
 }finally{await holder.query('rollback');await follower.query('rollback');holder.release();follower.release();}
 // Opposite arrival order: direct confirmation holds payment and waits our tenant.
 const tenantFence=await pool.connect(),direct=await pool.connect();try{
  await tenantFence.query('begin');await tenantFence.query('select public.detailing_reservation_context($1,$2,$3::jsonb)',[createHash('sha256').update(token).digest('hex'),origin,JSON.stringify([origin])]);
  await direct.query('begin');await direct.query("set local lock_timeout='3s'");const pid=(await direct.query('select pg_backend_pid() pid')).rows[0].pid;
  const pending=direct.query('select public.confirm_succeeded_payment($1::uuid) result',[result.paymentId]);let waiting=false;for(let n=0;n<100;n++){if((await pool.query("select wait_event_type='Lock' waiting from pg_stat_activity where pid=$1",[pid])).rows[0]?.waiting){waiting=true;break;}await new Promise(r=>setTimeout(r,10));}assert.equal(waiting,true,'direct confirmation must hold payment and await tenant');
  await assert.rejects(tenantFence.query('select public.detailing_payment_target($1,$2,$3::jsonb)',[createHash('sha256').update(token).digest('hex'),origin,JSON.stringify([origin])]),(e:unknown)=>(e as {code?:string}).code==='55P03');await tenantFence.query('rollback');assert.equal((await pending).rows[0].result.replayed,true);await direct.query('commit');
 }finally{await tenantFence.query('rollback');await direct.query('rollback');tenantFence.release();direct.release();}
 assert.deepEqual((await pay(token)).json.data,{...result,replayed:true});
 assert.deepEqual(await counts(),committed);
 for(const extra of [{amount:1},{tenantId:tenant},{bookingId:booking},{provider:'stripe'},{pricing:{}},{state:'succeeded'}])assert.equal((await pay(token,extra)).status,400);
 assert.equal((await pay('bad')).status,401);assert.equal((await req('/api/detailing-flow-sessions/mock-payment',{},token,ownerOrigin)).status,403);assert.equal((await req('/api/detailing-flow-sessions/mock-payment?tenantId='+tenant,{},token,origin)).status,400);
 const issue=async()=>{const r=await req(`/api/detailing-installations/${receipt.installationId}/sessions`,{},'',origin);assert.equal(r.status,200);return r.json.data.sessionToken as string;};
 const expiredToken=await issue(),expired=await request(expiredToken,{...body,idempotencyKey:'detailing-payment-expired-0001',requestedStart:empty.json.data.slots[2].start});assert.equal(expired.status,200);assert.equal((await hold(expiredToken)).status,200);await pool.query("update public.capacity_holds set expires_at=clock_timestamp()-interval '1 second' where booking_id=$1",[expired.json.data.bookingId]);const prior=await counts();assert.equal((await readiness(expiredToken)).status,409);assert.equal((await pay(expiredToken)).status,409);assert.deepEqual(await counts(),prior);
 const rollbackToken=await issue(),rollback=await request(rollbackToken,{...body,idempotencyKey:'detailing-payment-rollback-0001',requestedStart:empty.json.data.slots[4].start});assert.equal(rollback.status,200);assert.equal((await hold(rollbackToken)).status,200);const rollbackBooking=rollback.json.data.bookingId,rollbackHash=createHash('sha256').update(rollbackToken).digest('hex');
 await pool.query("update public.flow_sessions set expires_at=clock_timestamp()+interval '1 second' where token_hash=$1",[rollbackHash]);
 await pool.query(`create function public.detailing_payment_delay() returns trigger language plpgsql as $$begin if new.booking_id='${rollbackBooking}' then perform pg_sleep(1.2);end if;return new;end$$;create trigger detailing_payment_delay after insert on public.payments for each row execute function public.detailing_payment_delay()`);
 const beforeFailure=await counts();assert.equal((await pay(rollbackToken)).status,403);await pool.query('drop trigger detailing_payment_delay on public.payments;drop function public.detailing_payment_delay()');assert.deepEqual(await counts(),beforeFailure);assert.equal((await readiness(rollbackToken)).status,403);assert.deepEqual(await counts(),beforeFailure);assert.equal((await pool.query('select state,payment_id from public.bookings where id=$1',[rollbackBooking])).rows[0].state,'draft');assert.equal((await pool.query('select status from public.capacity_holds where booking_id=$1',[rollbackBooking])).rows[0].status,'active');
 await pool.query("update public.tenant_members set role='BUSINESS_STAFF' where tenant_id=$1 and user_id=$2",[tenant,actor]);assert.equal((await readiness(token)).status,403);assert.equal((await pay(token)).status,403);await pool.query("update public.tenant_members set role='BUSINESS_OWNER' where tenant_id=$1 and user_id=$2",[tenant,actor]);
 await pool.query("update public.service_questions set prompt='Drift' where service_id=$1 and question_key='package'",[service]);assert.equal((await readiness(token)).status,409);assert.equal((await pay(token)).status,409);await pool.query("update public.service_questions set prompt='Detail package' where service_id=$1 and question_key='package'",[service]);
 await pool.query('update public.payments set amount=1 where id=$1',[result.paymentId]);assert.equal((await pay(token)).status,409);await pool.query('update public.payments set amount=25000 where id=$1',[result.paymentId]);
 const after=await fingerprint();for(const table of ['bookings','capacity_holds','payments','flow_requests']){delete before[table];delete after[table];}assert.deepEqual(after,before);
 console.log('PASS readonly readiness draft/confirmed exact identity and unchanged financial/catalog fingerprint; actual Detailing HTTP25000 server-derived staging mock payment, concurrent one payment/confirmation, consumed hold, exact replay/confirm, expiry rollback preserving draft+active hold, expired hold/transport/owner/catalog denial and immutable publication/catalog');
}finally{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));await pool.end();}
