import assert from 'node:assert/strict';
import {Pool} from 'pg';
import {createPricingEngine} from '@lumin/core';
import {Service,Selection,DetailingOfferReceipt} from '@lumin/contracts';
import {createFlowHttpServer} from './http';
import {createFlowRepository} from './repository';
import {createDetailingOfferCreator,createDetailingOfferReader} from './detailing-catalog';
assert.equal(process.env.DETAILING_CATALOG_LOCAL_TEST,'1');if(process.env.CI==='true'){assert.ok(['localhost','127.0.0.1'].includes(process.env.PGHOST??''));assert.equal(process.env.PGPORT,'5432');}else{assert.equal(process.env.PGHOST,'127.0.0.1');assert.equal(process.env.PGPORT,'55436');}assert.match(process.env.PGDATABASE??'',/^lumin_phase_a_detailing_catalog_/);for(const key of ['DATABASE_URL','PGHOSTADDR','PGSERVICE','PGSERVICEFILE','PGPASSFILE','PGOPTIONS'])assert.ok(!process.env[key]);
const pool=new Pool({max:8}),repo=createFlowRepository(pool),id=(n:number)=>`62000000-0000-4000-8000-${String(n).padStart(12,'0')}`,actor=id(1),tenant=id(2),foreign=id(10),foreignTenant=id(20),housekeeping=id(30),origin='https://portal.example.test';
const server=createFlowHttpServer({repository:repo,catalogAuthoring:true,detailingOfferCreate:createDetailingOfferCreator(pool),detailingOfferRead:createDetailingOfferReader(pool),ownerOrigins:[origin],customerOrigins:[],authenticateOwner:async token=>token==='owner-token-123456'?actor:token==='foreign-token-123456'?foreign:null});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
const body={"name":"Detail package menu","description":"Owner authored detailing","currency":"USD","durationMinutes":120,"packages":[{"id":"basic","label":"Basic","amount":8000},{"id":"deluxe","label":"Deluxe","amount":15000}],"vehicles":[{"id":"sedan","label":"Sedan","multiplierBp":10000},{"id":"suv","label":"SUV","multiplierBp":12500}],"addons":[{"id":"pet-hair","name":"Pet hair","amount":3000}],"locations":[{"id":"studio","label":"Studio","amount":0},{"id":"mobile","label":"Mobile visit","amount":2000}],"idempotencyKey":"detailing-create-fixture-001"};
async function request(method='POST',value:unknown=body,t=tenant,service='',token='owner-token-123456',o=origin){const r=await fetch(`${base}/api/catalog/detailing-offers${service?'/'+service:''}?tenantId=${t}`,{method,headers:{origin:o,authorization:`Bearer ${token}`,'content-type':'application/json'},...(method==='POST'?{body:JSON.stringify(value)}:{})});return{status:r.status,json:await r.json()};}
async function catalogState(){const rows:Record<string,unknown>={};for(const table of ['services','service_items','service_addons','service_questions','owner_detailing_catalog_creations'])rows[table]=(await pool.query(`select coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]') data from public.${table} x`)).rows[0].data;return rows;}
async function protectedState(){const rows:Record<string,unknown>={};for(const table of ['business_profiles','availability_rules','scheduling_policies','flow_versions','flow_installations','flow_sessions','flow_requests','bookings','payments','capacity_holds'])rows[table]=(await pool.query(`select coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]') data from public.${table} x`)).rows[0].data;return rows;}
try{
 await pool.query("insert into auth.users(id,email) values($1,'detail-owner@example.test'),($2,'detail-foreign@example.test')",[actor,foreign]);
 for(const [a,t,type,key] of [[actor,tenant,'AUTO_DETAILING','detail-owner-profile-001'],[foreign,foreignTenant,'AUTO_DETAILING','detail-foreign-profile-001'],[actor,housekeeping,'HOUSEKEEPING','detail-housekeeping-profile-001']])await pool.query('select public.create_staging_business($1::uuid,$2::uuid,$3::text,$4::text,$5::text,$6::text,$7::text,$8::text)',[a,t,'Detail business',t,'UTC','USD',type,key]);
 const protectedBefore=await protectedState();
 const invalidBefore=await catalogState();for(const value of [{...body,total:1},{...body,tenantId:foreignTenant},{...body,actor:foreign},{...body,provider:'stripe'},{...body,currency:'EUR'},{...body,packages:[{...body.packages[0]!,amount:-1}]},{...body,packages:[{...body.packages[0]!,amount:1.5}]},{...body,packages:[{...body.packages[0]!,amount:Number.MAX_SAFE_INTEGER}]},{...body,vehicles:[{...body.vehicles[0]!,multiplierBp:-1}]}])assert.equal((await request('POST',value)).status,400);assert.deepEqual(await catalogState(),invalidBefore);
 assert.equal((await request('POST',body,tenant,'','foreign-token-123456')).status,403);assert.equal((await request('POST',body,housekeeping)).status,403);assert.equal((await request('POST',body,tenant,'','bad-token-123456')).status,401);assert.equal((await request('POST',body,tenant,'',undefined,'https://foreign.example.test')).status,403);
 const created=await Promise.all([request(),request()]);assert.deepEqual(created.map(r=>r.status),[200,200]);assert.deepEqual(created[0],created[1]);const receipt=DetailingOfferReceipt.parse(created[0]!.json.data),service=receipt.service.id;assert.equal(receipt.businessType,'AUTO_DETAILING');assert.equal(receipt.pricingModel,'package_subtotal_vehicle_multiplier');
 assert.equal(Number((await pool.query('select count(*) n from public.services where tenant_id=$1',[tenant])).rows[0].n),1);assert.equal(Number((await pool.query('select count(*) n from public.service_questions where service_id=$1',[service])).rows[0].n),3);assert.equal(Number((await pool.query('select count(*) n from public.service_addons where service_id=$1',[service])).rows[0].n),1);assert.equal(Number((await pool.query('select count(*) n from public.owner_detailing_catalog_creations where tenant_id=$1',[tenant])).rows[0].n),1);
 const saved=await catalogState();assert.deepEqual(await request(),created[0]);assert.deepEqual(await request('GET',undefined,tenant,service),created[0]);assert.deepEqual(await catalogState(),saved);assert.ok(!JSON.stringify(receipt).includes(body.idempotencyKey));
 const pricing=createPricingEngine(),configuration=Service.parse(receipt.service),selection=Selection.parse({serviceId:service,addonIds:['pet-hair'],answers:{package:{choiceIds:['deluxe']},vehicle:{choiceIds:['suv']},location:{choiceIds:['mobile']}}});assert.deepEqual(pricing.price(configuration,selection).total,{amount:25000,currency:'USD'});assert.throws(()=>pricing.price(configuration,{...selection,answers:{...selection.answers,vehicle:{choiceIds:['foreign']}}}));
 assert.equal((await request('POST',{...body,packages:[{...body.packages[0]!,amount:8001},body.packages[1]!]})).status,409);assert.deepEqual(await catalogState(),saved);
 await assert.rejects(repo.call('save_paid_simple_draft',[actor,tenant,id(100),service,0,'Detailing must stay configurable','#4f46e5','compact']),{code:'UNSUPPORTED_CONFIG'});
 const partial=await catalogState();await assert.rejects(pool.query('select public.create_auto_detailing_offer($1::uuid,$2::uuid,$3::uuid,$4::jsonb)',[actor,tenant,service,JSON.stringify({...body,idempotencyKey:'detail-partial-failure-001'})]),{code:'23505'});assert.deepEqual(await catalogState(),partial);
 await pool.query('update public.service_addons set price=price+1 where tenant_id=$1 and service_id=$2',[tenant,service]);const drift=await catalogState();assert.equal((await request()).status,409);assert.equal((await request('GET',undefined,tenant,service)).status,404);assert.deepEqual(await catalogState(),drift);await pool.query('update public.service_addons set price=price-1 where tenant_id=$1 and service_id=$2',[tenant,service]);
 // Inject a child-write failure only in this guarded disposable fixture: service insert must roll back too.
 await pool.query("create function public.detailing_fixture_fault() returns trigger language plpgsql as $$begin if new.tenant_id='62000000-0000-4000-8000-000000000002' and new.name='Fixture child fault' then raise exception 'fixture child fault';end if;return new;end$$");await pool.query('create trigger detailing_fixture_fault before insert on public.service_addons for each row execute function public.detailing_fixture_fault()');
 const childBefore=await catalogState();try{assert.equal((await request('POST',{...body,idempotencyKey:'detail-child-failure-001',addons:[{id:'fault',name:'Fixture child fault',amount:0}]})).status,500);assert.deepEqual(await catalogState(),childBefore);}finally{await pool.query('drop trigger detailing_fixture_fault on public.service_addons');await pool.query('drop function public.detailing_fixture_fault()');}
 assert.equal((await request('GET',undefined,foreignTenant,service,'foreign-token-123456')).status,404);assert.equal((await request('GET',undefined,tenant,service,'foreign-token-123456')).status,403);
 await pool.query("update public.tenant_members set role='BUSINESS_STAFF' where tenant_id=$1 and user_id=$2",[tenant,actor]);assert.equal((await request()).status,403);assert.equal((await request('GET',undefined,tenant,service)).status,403);await pool.query('delete from public.tenant_members where tenant_id=$1 and user_id=$2',[tenant,actor]);assert.equal((await request()).status,403);await pool.query("insert into public.tenant_members(tenant_id,user_id,role) values($1,$2,'BUSINESS_OWNER')",[tenant,actor]);
 await pool.query("update public.tenants set status='inactive' where id=$1",[tenant]);assert.equal((await request()).status,403);assert.equal((await request('GET',undefined,tenant,service)).status,403);await pool.query("update public.tenants set status='active' where id=$1",[tenant]);
 assert.deepEqual(await protectedState(),protectedBefore);
 // Replay locks only its service: target child insert/reassignment denied, unrelated service insert succeeds.
 const other=await request('POST',body,foreignTenant,'','foreign-token-123456');assert.equal(other.status,200);const otherService=other.json.data.service.id;
 const guard=await pool.connect(),alias=await pool.connect();try{await guard.query('begin');await guard.query('set local role service_role');await guard.query('select public.create_auto_detailing_offer($1::uuid,$2::uuid,$3::uuid,$4::jsonb)',[actor,tenant,id(900),JSON.stringify(body)]);await alias.query('begin');await alias.query("set local lock_timeout='100ms'");await alias.query("insert into public.service_addons(tenant_id,service_id,addon_key,name,price) values($1,$2,'foreign-alias','Foreign alias',0)",[foreignTenant,otherService]);await alias.query('rollback');await alias.query('begin');await alias.query("set local lock_timeout='100ms'");await assert.rejects(alias.query("insert into public.service_addons(tenant_id,service_id,addon_key,name,price) values($1,$2,'target-alias','Target alias',0)",[tenant,service]),(error:unknown)=>(error as {code?:string}).code==='55P03');await alias.query('rollback');await alias.query('begin');await alias.query("set local lock_timeout='100ms'");await assert.rejects(alias.query("update public.service_addons set tenant_id=$1,service_id=$2,addon_key='reassigned-alias' where tenant_id=$3 and service_id=$4",[tenant,service,foreignTenant,otherService]),(error:unknown)=>(error as {code?:string}).code==='55P03');}finally{await alias.query('rollback');await guard.query('rollback');alias.release();guard.release();}
 const max=Math.floor(Number.MAX_SAFE_INTEGER/10000),large={...body,packages:[{id:'max',label:'Exact integer boundary',amount:max}],vehicles:[{id:'sedan',label:'Sedan',multiplierBp:10000}],addons:[],locations:[],idempotencyKey:'detail-safe-boundary-001'};const maximum=await request('POST',large);assert.equal(maximum.status,200);const maxService=Service.parse(maximum.json.data.service);assert.equal(pricing.price(maxService,Selection.parse({serviceId:maxService.id,answers:{package:{choiceIds:['max']},vehicle:{choiceIds:['sedan']}}})).total.amount,max);assert.equal((await request('POST',{...large,packages:[{...large.packages[0]!,amount:max+1}],idempotencyKey:'detail-overflow-boundary-001'})).status,400);
 assert.deepEqual(await protectedState(),protectedBefore);
 console.log('PASS actual HTTP owner AUTO_DETAILING catalog: immutable profile/currency and tenant/role checks; configurable package/vehicle/addon/location persistence; exact shared-core25000 pricing and safe-integer boundary; same-key concurrent replay one service; changed body/catalog denial; partial failure no orphan; paid_simple remains closed; no scheduling/customer/financial writes');
}finally{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));await pool.end();}
