import {afterEach,expect,it,vi} from 'vitest';
import type {Server} from 'node:http';
import {buildDetailingService} from '@lumin/contracts';
import {createDetailingPublicationApi,detailingPublicationEnabled} from './detailing-publication';
import {createFlowHttpServer} from './http';
const id=(n:number)=>`64000000-0000-4000-8000-${String(n).padStart(12,'0')}`,actor=id(1),tenant=id(2),flow=id(3),service=id(4),version=id(5),installation=id(6),origin='https://portal.example.test',customerOrigin='https://checkout.example.test';
const catalog={name:'Detail menu',description:'',currency:'USD',durationMinutes:120,packages:[{id:'basic',label:'Basic',amount:8000},{id:'deluxe',label:'Deluxe',amount:15000}],vehicles:[{id:'sedan',label:'Sedan',multiplierBp:10000},{id:'suv',label:'SUV',multiplierBp:12500}],addons:[{id:'pet-hair',name:'Pet hair',amount:3000}],locations:[{id:'mobile',label:'Mobile',amount:2000}]},design={accentColor:'#4f46e5' as const,layout:'stacked' as const},draft={schemaVersion:1,businessType:'AUTO_DETAILING',flowId:flow,revision:1,serviceId:service,name:'Published menu',presentation:design};
const render={versionId:version,renderSchemaVersion:7,businessType:'AUTO_DETAILING',submissionMode:'detailing_quote',bookingMode:'unavailable',paymentMode:'unavailable',pricingModel:'package_subtotal_vehicle_multiplier',serviceId:service,catalog,publication:{name:draft.name,presentation:design,draftRevision:1}},expiry='2030-01-01T00:00:00.000Z';
const context={service:buildDetailingService(service,tenant,{...catalog,idempotencyKey:'catalog-fixture-0001'}),catalog,scheduling:{schemaVersion:1,businessType:'AUTO_DETAILING',tenantId:tenant,serviceId:service,timezone:'UTC',windows:[{id:id(7),weekday:1,startMinute:540,endMinute:1020,capacity:1}],policy:{id:id(8),leadTimeMinutes:0,horizonDays:30,slotIntervalMinutes:30}},render,installationId:installation,expiresAt:expiry},choice={packageId:'deluxe',vehicleId:'suv',addonIds:['pet-hair'],locationId:'mobile'};
function db(value:unknown=context,clock?:()=>number){const release=vi.fn(),query=vi.fn(async(sql:string)=>({rows:sql.startsWith('select')?[{result:typeof value==='function'?(value as (sql:string)=>unknown)(sql):value}]:[]}));return{query,release,api:createDetailingPublicationApi({connect:async()=>({query,release})} as never,[customerOrigin],clock)};}
it('quotes exact authoritative multiplied package/addon/location core model, never writes financial rows',async()=>{const f=db();const r=await f.api.quote('a'.repeat(64),customerOrigin,choice);expect(r.pricing.total).toEqual({amount:25000,currency:'USD'});expect(r.selection).toEqual(choice);expect(r.paymentMode).toBe('unavailable');expect(f.query.mock.calls.filter(c=>String(c[0]).startsWith('select'))).toHaveLength(2);expect(f.query).toHaveBeenLastCalledWith('commit');});
it.each([{...choice,packageId:'foreign'},{...choice,vehicleId:'foreign'},{...choice,addonIds:['foreign']},{...choice,addonIds:['pet-hair','pet-hair']},{...choice,locationId:'foreign'},{packageId:'deluxe',vehicleId:'suv',addonIds:[]},{...choice,total:1},{...choice,tenantId:tenant},{...choice,serviceId:service},{...choice,price:25000}])('rejects invalid or monetary selection %j',async b=>{const f=db();await expect(f.api.quote('a'.repeat(64),customerOrigin,b)).rejects.toMatchObject({code:'INVALID_REQUEST'});expect(f.query.mock.calls.some(c=>String(c[0]).includes('insert'))).toBe(false);});
it('keeps exact core rounding at the publication quote boundary',async()=>{const c={...catalog,packages:[{id:'basic',label:'Basic',amount:101}],vehicles:[{id:'sedan',label:'Sedan',multiplierBp:12500}],addons:[],locations:[]},r={...context,catalog:c,service:buildDetailingService(service,tenant,{...c,idempotencyKey:'rounding-fixture-0001'}),render:{...render,catalog:c}};expect((await db(r).api.quote('a'.repeat(64),customerOrigin,{packageId:'basic',vehicleId:'sedan',addonIds:[]})).pricing.total.amount).toBe(126);});
it('rejects changed private service and final expiry before quote commit',async()=>{await expect(db({...context,service:{...context.service,name:'Drift'}}).api.quote('a'.repeat(64),customerOrigin,choice)).rejects.toMatchObject({code:'FORBIDDEN'});let calls=0;const f=db(context,()=>++calls===1?0:Date.parse(expiry));await expect(f.api.quote('a'.repeat(64),customerOrigin,choice)).rejects.toMatchObject({code:'FORBIDDEN'});expect(f.query).toHaveBeenLastCalledWith('rollback');});
it('validates draft receipt before commit and rejects forged saved revision',async()=>{const b={expectedRevision:0,serviceId:service,name:draft.name,presentation:design};expect(await db(draft).api.save(actor,tenant,flow,b)).toEqual(draft);const f=db({...draft,revision:2});await expect(f.api.save(actor,tenant,flow,b)).rejects.toMatchObject({code:'INTERNAL_ERROR'});expect(f.query).toHaveBeenLastCalledWith('rollback');});
it('feature stays staging-only/default closed independent from fake payment',()=>{expect(detailingPublicationEnabled({})).toBe(false);expect(detailingPublicationEnabled({BOOKING_LUMIN_ENV:'production',BOOKING_LUMIN_DETAILING_PUBLICATION:'1'})).toBe(false);expect(detailingPublicationEnabled({BOOKING_LUMIN_ENV:'staging',BOOKING_LUMIN_DETAILING_PUBLICATION:'1'})).toBe(true);expect(detailingPublicationEnabled({BOOKING_LUMIN_ENV:'staging',BOOKING_LUMIN_FAKE_PAYMENTS:'1'})).toBe(false);});
let server:Server;afterEach(async()=>{server?.closeAllConnections();if(server)await new Promise<void>(r=>server.close(()=>r()));});
async function http(enabled=true){const quote=vi.fn(async()=>await db().api.quote('a'.repeat(64),customerOrigin,choice)),session=vi.fn(async()=>({render,expiresAt:expiry})),save=vi.fn(async()=>draft),call=vi.fn();server=createFlowHttpServer({repository:{call},detailingPublication:enabled,detailingPublicationApi:{quote,session,save,read:async()=>draft,publish:async()=>{throw Error();},recover:async()=>{throw Error();}} as never,ownerOrigins:[origin],customerOrigins:[customerOrigin],authenticateOwner:async token=>token==='owner-token-123456'?actor:null});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${(server.address() as {port:number}).port}`;return{quote,session,save,call,post:(path:string,b:unknown,o=customerOrigin,token='a'.repeat(43))=>fetch(base+path,{method:'POST',headers:{origin:o,authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify(b)})};}
it('dedicated HTTP session issues once and keeps legacy RPC closed; quote bearer stays hashed',async()=>{const f=await http(),r=await f.post(`/api/detailing-installations/${installation}/sessions`,{});expect(r.status).toBe(200);expect((await r.json()).data.render.renderSchemaVersion).toBe(7);expect(f.session).toHaveBeenCalledWith(installation,expect.stringMatching(/^[0-9a-f]{64}$/),customerOrigin);expect(f.call).not.toHaveBeenCalled();const q=await f.post('/api/detailing-flow-sessions/quote',choice);expect(q.status).toBe(200);expect(f.quote).toHaveBeenCalledWith(expect.stringMatching(/^[0-9a-f]{64}$/),customerOrigin,choice);});
it('rejects untrusted session/quote bodies, origin and forged owner identity',async()=>{const f=await http();expect((await f.post(`/api/detailing-installations/${installation}/sessions`,{tenantId:tenant})).status).toBe(400);expect((await f.post('/api/detailing-flow-sessions/quote',{...choice,total:1})).status).toBe(400);expect((await f.post('/api/detailing-flow-sessions/quote',choice,'https://foreign.example.test')).status).toBe(403);expect((await f.post('/api/detailing-flow-sessions/quote',choice,customerOrigin,'bad')).status).toBe(401);expect((await f.post(`/api/detailing-flows/${flow}/draft?tenantId=${tenant}`,{expectedRevision:0,serviceId:service,name:draft.name,presentation:design},origin,'bad-token-123456')).status).toBe(401);expect(f.quote).not.toHaveBeenCalled();expect(f.save).not.toHaveBeenCalled();});
it('default gate denies new session capability',async()=>{const f=await http(false);expect((await f.post(`/api/detailing-installations/${installation}/sessions`,{})).status).toBe(422);expect(f.session).not.toHaveBeenCalled();});
