import {buildDetailingService,Selection} from '@lumin/contracts';
import {createPricingEngine} from '@lumin/core';
import assert from 'node:assert/strict';
import {Pool} from 'pg';
import {createFlowHttpServer} from './http';
import {createFlowRepository} from './repository';
import {createDetailingOfferCreator} from './detailing-catalog';
import {createDetailingSchedulingCreator} from './detailing-scheduling';
import {createDetailingPublicationApi} from './detailing-publication';
import {createDetailingAvailabilityReader} from './detailing-availability';
import {createDetailingReservationApi} from './detailing-reservation';
import {createHash} from 'node:crypto';
assert.equal(process.env.DETAILING_RESERVATION_LOCAL_TEST,'1');
if(process.env.CI==='true'){assert.ok(['localhost','127.0.0.1'].includes(process.env.PGHOST??''));assert.equal(process.env.PGPORT,'5432');}else{assert.equal(process.env.PGHOST,'127.0.0.1');assert.equal(process.env.PGPORT,'55436');}
assert.match(process.env.PGDATABASE??'',/^lumin_phase_a_detailing_reservation_/);for(const key of ['DATABASE_URL','PGHOSTADDR','PGSERVICE','PGSERVICEFILE','PGPASSFILE','PGOPTIONS'])assert.ok(!process.env[key]);
const pool=new Pool({max:8}),id=(n:number)=>`66000000-0000-4000-8000-${String(n).padStart(12,'0')}`,actor=id(1),tenant=id(2),flow=id(3),foreign=id(8),foreignTenant=id(9),ownerOrigin='https://portal.example.test',origin='https://checkout.example.test';
const server=createFlowHttpServer({repository:createFlowRepository(pool),catalogAuthoring:true,detailingOfferCreate:createDetailingOfferCreator(pool),schedulingAuthoring:true,detailingSchedulingCreate:createDetailingSchedulingCreator(pool),detailingPublication:true,detailingPublicationApi:createDetailingPublicationApi(pool,[origin]),detailingAvailability:createDetailingAvailabilityReader(pool,[origin]),detailingReservationApi:createDetailingReservationApi(pool,[origin]),ownerOrigins:[ownerOrigin],customerOrigins:[origin],authenticateOwner:async token=>token==='owner-token-123456'?actor:token==='foreign-token-123456'?foreign:null});
await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
async function req(path:string,body:unknown=undefined,token='owner-token-123456',o=ownerOrigin){const response=await fetch(base+path,{method:body===undefined?'GET':'POST',headers:{origin:o,authorization:`Bearer ${token}`,'content-type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});return{status:response.status,json:await response.json()};}
const nextDay=new Date();nextDay.setUTCDate(nextDay.getUTCDate()+1);nextDay.setUTCHours(0,0,0,0);const from=nextDay.toISOString(),to=new Date(nextDay.getTime()+86400000).toISOString();
async function fingerprint(){const data:Record<string,unknown>={};for(const table of ['services','service_questions','service_addons','business_profiles','owner_detailing_catalog_creations','owner_detailing_scheduling','availability_rules','availability_overrides','scheduling_policies','flows','flow_versions','bound_flow_versions','detailing_publications','flow_installations','bookings','capacity_holds','payments','flow_requests'])data[table]=(await pool.query(`select coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]') data from public.${table} x where tenant_id=$1`,[tenant])).rows[0].data;return data;}
try{
 await pool.query("insert into auth.users(id,email) values($1,'availability-owner@example.test'),($2,'availability-foreign@example.test')",[actor,foreign]);for(const [a,t] of [[actor,tenant],[foreign,foreignTenant]])await pool.query('select public.create_staging_business($1,$2,$3,$4,$5,$6,$7,$8)',[a,t,'Detailing availability',t,'UTC','USD','AUTO_DETAILING','detailing-availability-business-'+t]);
 const offer={name:'Scheduled detail package',description:'',currency:'USD',durationMinutes:60,packages:[{id:'basic',label:'Basic',amount:15000}],vehicles:[{id:'suv',label:'SUV',multiplierBp:12500}],addons:[{id:'pet-hair',name:'Pet hair',amount:3000}],locations:[{id:'mobile',label:'Mobile',amount:2000}],idempotencyKey:'detailing-availability-offer-0001'};
 const made=await req('/api/catalog/detailing-offers?tenantId='+tenant,offer);assert.equal(made.status,200,JSON.stringify(made));const service=made.json.data.service.id;
 const schedule={timezone:'UTC',windows:Array.from({length:7},(_,weekday)=>({weekday,startMinute:540,endMinute:1020,capacity:1})),policy:{leadTimeMinutes:0,horizonDays:30,slotIntervalMinutes:30},idempotencyKey:'detailing-availability-schedule-0001'};
 assert.equal((await req(`/api/catalog/detailing-offers/${service}/scheduling?tenantId=${tenant}`,schedule)).status,200);
 const path=(kind:string)=>`/api/detailing-flows/${flow}/${kind}?tenantId=${tenant}`;
 assert.equal((await req(path('draft'),{expectedRevision:0,serviceId:service,name:'Detail appointment',presentation:{accentColor:'#4f46e5',layout:'stacked'}})).status,200);
 const published=await req(path('publish-draft'),{expectedDraftRevision:1,allowedOrigins:[origin]});assert.equal(published.status,200);const receipt=published.json.data.publication;
 const issued=await req(`/api/detailing-installations/${receipt.installationId}/sessions`,{},'',origin);assert.equal(issued.status,200);const token=issued.json.data.sessionToken;
 const url='/api/detailing-flow-sessions/availability?'+new URLSearchParams({from,to}),availability=()=>req(url,undefined,token,origin);
 const empty=await availability();assert.equal(empty.status,200,JSON.stringify(empty));assert.equal(empty.json.data.versionId,receipt.versionId);assert.equal(empty.json.data.installationId,receipt.installationId);assert.equal(empty.json.data.expiresAt,issued.json.data.expiresAt);assert.equal(empty.json.data.serviceId,service);assert.equal(empty.json.data.durationMinutes,60);assert.equal(empty.json.data.timezone,'UTC');assert.equal(empty.json.data.slots.length,15);assert.equal(empty.json.data.slots[0].start,from.replace('00:00:00','09:00:00'));assert.ok(empty.json.data.slots.every((s:{remainingCapacity:number})=>s.remainingCapacity===1));assert.ok(!JSON.stringify(empty).includes(tenant));assert.ok(!JSON.stringify(empty).includes(actor));assert.ok(!JSON.stringify(empty).includes('15000'));
 // Cross-check the fixed SQL verifier against unchanged core IEEE rounding at financial boundaries.
 for(const [amount,bp] of [[101,12500],[101,5000],[Number.MAX_SAFE_INTEGER,0],[Number.MAX_SAFE_INTEGER,1],[9007199254734999,1],[9007199254735000,1]] as const){
  const menu={...offer,packages:[{id:'basic',label:'Basic',amount}],vehicles:[{id:'suv',label:'SUV',multiplierBp:bp}],addons:[],locations:[]},bound=buildDetailingService(id(80),tenant,menu),choices={packageId:'basic',vehicleId:'suv',addonIds:[]};
  const selected=Selection.parse({serviceId:bound.id,addonIds:[],answers:{package:{choiceIds:['basic']},vehicle:{choiceIds:['suv']}}}),price=createPricingEngine().price(bound,selected);
  const checked=(await pool.query('select lumin.detailing_request_model($1::jsonb,$2::jsonb,$3::jsonb,$4::timestamptz) model',[JSON.stringify(bound),JSON.stringify(choices),JSON.stringify({name:'Boundary fictional',email:'boundary@example.test'}),empty.json.data.slots[0].start])).rows[0].model;
  assert.deepEqual(checked.pricing,price,`SQL/core exact rounding amount=${amount} bp=${bp}`);assert.deepEqual(checked.selection,selected);
 }
 const fixedBefore=await fingerprint();
 const selection={packageId:'basic',vehicleId:'suv',addonIds:['pet-hair'],locationId:'mobile'},body={schemaVersion:1,idempotencyKey:'detailing-reservation-request-0001',selection,customer:{name:'Fictional reservation',email:'reservation@example.test'},requestedStart:empty.json.data.slots[0].start};
 const request=(b=body,t=token)=>req('/api/detailing-flow-sessions/request',b,t,origin),hold=(t=token)=>req('/api/detailing-flow-sessions/hold',{},t,origin);
 const initial=await Promise.all([request(),request()]);assert.deepEqual(initial.map(r=>r.status),[200,200],JSON.stringify(initial));assert.deepEqual(initial[0],initial[1]);const accepted=initial[0]!.json.data;assert.deepEqual(accepted.pricing.total,{amount:25000,currency:'USD'});assert.equal(accepted.confirmed,false);assert.equal(accepted.paymentMode,'unavailable');assert.equal(accepted.versionId,receipt.versionId);assert.equal(accepted.installationId,receipt.installationId);assert.equal(accepted.serviceId,service);
 assert.equal((await request({...body,idempotencyKey:'changed-reservation-key-0001'})).status,409);assert.equal((await request({...body,customer:{...body.customer,name:'Changed'}})).status,409);
 for(const invalid of [{...body,total:1},{...body,tenantId:foreignTenant},{...body,serviceId:service},{...body,providerState:'succeeded'},{...body,selection:{...selection,price:1}}])assert.equal((await req('/api/detailing-flow-sessions/request',invalid,token,origin)).status,400);
 const issue=async()=>{const r=await req(`/api/detailing-installations/${receipt.installationId}/sessions`,{},'',origin);assert.equal(r.status,200);return r.json.data.sessionToken as string;};
 const secondToken=await issue();const second=await request({...body,idempotencyKey:'detailing-reservation-request-0002'},secondToken);assert.equal(second.status,200,JSON.stringify(second));assert.notEqual(second.json.data.bookingId,accepted.bookingId);
 const race=await Promise.all([hold(),hold(secondToken)]);assert.deepEqual(race.map(r=>r.status).sort(),[200,409],JSON.stringify(race));const winner=race[0]!.status===200?token:secondToken,loser=winner===token?secondToken:token,winnerReceipt=race.find(r=>r.status===200)!;assert.deepEqual(await hold(winner),winnerReceipt);assert.equal((await hold(loser)).status,409);assert.equal(Number((await pool.query('select count(*) n from public.capacity_holds where tenant_id=$1',[tenant])).rows[0].n),1);assert.deepEqual(await request(),initial[0]);
 const slots=await availability();assert.equal(slots.status,200);assert.equal(slots.json.data.slots.length,13);assert.equal(Number((await pool.query('select count(*) n from public.payments where tenant_id=$1',[tenant])).rows[0].n),0);
 // Current pricing/provenance tampering can never obtain or replay a hold.
 await pool.query("update public.bookings set pricing='{}' where id=$1",[accepted.bookingId]);assert.equal((await hold()).status,409);await pool.query('update public.bookings set pricing=$2::jsonb where id=$1',[accepted.bookingId,JSON.stringify(accepted.pricing)]);
 assert.equal((await req('/api/detailing-flow-sessions/hold',{bookingId:accepted.bookingId},winner,origin)).status,400);assert.equal((await req('/api/detailing-flow-sessions/hold',{},winner,ownerOrigin)).status,403);
 // Replay does not create another booking even when the first response was lost.
 const thirdToken=await issue(),later={...body,idempotencyKey:'detailing-reservation-request-0003',requestedStart:empty.json.data.slots[2].start};const third=await request(later,thirdToken);assert.equal(third.status,200,JSON.stringify(third));const beforeReplay=Number((await pool.query('select count(*) n from public.bookings where tenant_id=$1',[tenant])).rows[0].n);assert.deepEqual(await request(later,thirdToken),third);assert.equal(Number((await pool.query('select count(*) n from public.bookings where tenant_id=$1',[tenant])).rows[0].n),beforeReplay);
 // Final expiry after the canonical allocator ran must roll back its hold.
 const thirdHash=createHash('sha256').update(thirdToken).digest('hex');await pool.query("update public.flow_sessions set expires_at=clock_timestamp()+interval '1 second' where token_hash=$1",[thirdHash]);
 await pool.query(`create function public.detailing_fixture_hold_delay() returns trigger language plpgsql as $$begin if new.booking_id='${third.json.data.bookingId}' then perform pg_sleep(1.2);end if;return new;end$$;create trigger detailing_fixture_hold_delay after insert on public.capacity_holds for each row execute function public.detailing_fixture_hold_delay()`);
 assert.equal((await hold(thirdToken)).status,403);await pool.query('drop trigger detailing_fixture_hold_delay on public.capacity_holds;drop function public.detailing_fixture_hold_delay()');assert.equal(Number((await pool.query('select count(*) n from public.capacity_holds where booking_id=$1',[third.json.data.bookingId])).rows[0].n),0);assert.equal((await request(later,thirdToken)).status,403);
 // A new valid capability can use the still-free slot; no expired receipt renewal.
 const fourthToken=await issue(),fourth=await request({...later,idempotencyKey:'detailing-reservation-request-0004'},fourthToken);assert.equal(fourth.status,200);assert.equal((await hold(fourthToken)).status,200);
 // Failure inserting private provenance rolls back customer, booking, outbox and request.
 const fifthToken=await issue(),fifthHash=createHash('sha256').update(fifthToken).digest('hex'),fifthSession=(await pool.query('select id from public.flow_sessions where token_hash=$1',[fifthHash])).rows[0].id;
 const counts=async()=>{const r:Record<string,number>={};for(const t of ['customers','bookings','flow_requests','detailing_request_receipts','capacity_holds','payments','durable_outbox'])r[t]=Number((await pool.query(`select count(*) n from public.${t} where tenant_id=$1`,[tenant])).rows[0].n);return r;};const beforeFailure=await counts();
 await pool.query(`create function public.detailing_fixture_request_failure() returns trigger language plpgsql as $$begin if new.session_id='${fifthSession}' then raise exception 'FIXTURE_FAILURE';end if;return new;end$$;create trigger detailing_fixture_request_failure before insert on public.detailing_request_receipts for each row execute function public.detailing_fixture_request_failure()`);
 const fifth={...body,idempotencyKey:'detailing-reservation-request-0005',customer:{name:'Rollback fictional',email:'rollback@example.test'},requestedStart:empty.json.data.slots[4].start};assert.equal((await request(fifth,fifthToken)).status,500);await pool.query('drop trigger detailing_fixture_request_failure on public.detailing_request_receipts;drop function public.detailing_fixture_request_failure()');assert.deepEqual(await counts(),beforeFailure);
 // Trusted SQL boundary rejects a substituted price as well as HTTP rejecting monetary keys.
 await assert.rejects(pool.query('select public.submit_detailing_reservation($1,$2,$3::jsonb,$4,$5::jsonb,$6::jsonb,$7::timestamptz,$8::jsonb)',[fifthHash,origin,JSON.stringify([origin]),fifth.idempotencyKey,JSON.stringify(selection),JSON.stringify(fifth.customer),fifth.requestedStart,JSON.stringify({...accepted.pricing,total:{amount:1,currency:'USD'}})]),(error:unknown)=>(error as {code?:string}).code==='22023');assert.deepEqual(await counts(),beforeFailure);
 const resumed=await request(fifth,fifthToken);assert.equal(resumed.status,200,JSON.stringify(resumed));assert.equal((await hold(fifthToken)).status,200);
 await pool.query("update public.tenant_members set role='BUSINESS_STAFF' where tenant_id=$1 and user_id=$2",[tenant,actor]);assert.equal((await hold(winner)).status,403);await pool.query("update public.tenant_members set role='BUSINESS_OWNER' where tenant_id=$1 and user_id=$2",[tenant,actor]);
 await pool.query("update public.tenants set status='inactive' where id=$1",[tenant]);assert.equal((await hold(winner)).status,403);await pool.query("update public.tenants set status='active' where id=$1",[tenant]);
 await pool.query("update public.service_questions set prompt='Drift' where service_id=$1 and question_key='package'",[service]);assert.equal((await hold(winner)).status,409);await pool.query("update public.service_questions set prompt='Detail package' where service_id=$1 and question_key='package'",[service]);
 await pool.query('update public.availability_rules set capacity=2 where service_id=$1 and weekday=0',[service]);assert.equal((await hold(winner)).status,409);await pool.query('update public.availability_rules set capacity=1 where service_id=$1 and weekday=0',[service]);
 for(const route of ['mock-payment','confirm'])assert.ok([404,422].includes((await req('/api/flow-sessions/'+route,{},winner,origin)).status));
 const fixedAfter=await fingerprint();for(const table of ['bookings','capacity_holds','flow_requests']){delete fixedBefore[table];delete fixedAfter[table];}assert.deepEqual(fixedAfter,fixedBefore);assert.equal(Number((await pool.query('select count(*) n from public.payments where tenant_id=$1',[tenant])).rows[0].n),0);
 console.log('PASS actual HTTP server-priced25000 selection/request, exact concurrent replay, one last-slot hold winner, same live hold replay, final-expiry hold rollback, new-session free-slot recovery, atomic provenance failure rollback/resume, SQL/HTTP price/tenant/role/provenance/catalog/schedule tamper denial, immutable catalog/publication and zero payments');
}finally{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));await pool.end();}
