import assert from 'node:assert/strict';
import {Pool} from 'pg';
import {createFlowHttpServer} from './http';
import {createFlowRepository} from './repository';
import {createDetailingOfferCreator} from './detailing-catalog';
import {createDetailingSchedulingCreator} from './detailing-scheduling';
import {createDetailingPublicationApi} from './detailing-publication';
import {createCustomerHoldWriter} from './customer-hold';
import {createCustomerMockPayment} from './customer-payment';
assert.equal(process.env.DETAILING_PUBLICATION_LOCAL_TEST,'1');if(process.env.CI==='true'){assert.ok(['localhost','127.0.0.1'].includes(process.env.PGHOST??''));assert.equal(process.env.PGPORT,'5432');}else{assert.equal(process.env.PGHOST,'127.0.0.1');assert.equal(process.env.PGPORT,'55436');}assert.match(process.env.PGDATABASE??'',/^lumin_phase_a_detailing_publication_/);for(const key of ['DATABASE_URL','PGHOSTADDR','PGSERVICE','PGSERVICEFILE','PGPASSFILE','PGOPTIONS'])assert.ok(!process.env[key]);
const pool=new Pool({max:10}),id=(n:number)=>`64000000-0000-4000-8000-${String(n).padStart(12,'0')}`,actor=id(1),tenant=id(2),foreign=id(9),foreignTenant=id(10),housekeeping=id(11),flow=id(3),ownerOrigin='https://portal.example.test',customerOrigin='https://checkout.example.test';
const server=createFlowHttpServer({repository:createFlowRepository(pool),catalogAuthoring:true,detailingOfferCreate:createDetailingOfferCreator(pool),schedulingAuthoring:true,detailingSchedulingCreate:createDetailingSchedulingCreator(pool),detailingPublication:true,detailingPublicationApi:createDetailingPublicationApi(pool,[customerOrigin]),customerHold:createCustomerHoldWriter(pool),customerMockPayment:createCustomerMockPayment(pool,{BOOKING_LUMIN_ENV:'staging',BOOKING_LUMIN_FAKE_PAYMENTS:'1'}),ownerOrigins:[ownerOrigin],customerOrigins:[customerOrigin],authenticateOwner:async token=>token==='owner-token-123456'?actor:token==='foreign-token-123456'?foreign:null});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
async function req(path:string,body:unknown=undefined,token='owner-token-123456',origin=ownerOrigin,method=body===undefined?'GET':'POST'){const r=await fetch(base+path,{method,headers:{origin,authorization:`Bearer ${token}`,'content-type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});return{status:r.status,json:await r.json()};}
const offer={name:'Detail menu',description:'Owner catalog',currency:'USD',durationMinutes:120,packages:[{id:'basic',label:'Basic',amount:8000},{id:'deluxe',label:'Deluxe',amount:15000}],vehicles:[{id:'sedan',label:'Sedan',multiplierBp:10000},{id:'suv',label:'SUV',multiplierBp:12500}],addons:[{id:'pet-hair',name:'Pet hair',amount:3000}],locations:[{id:'studio',label:'Studio',amount:0},{id:'mobile',label:'Mobile',amount:2000}],idempotencyKey:'detailing-pub-offer-0001'},schedule={timezone:'UTC',windows:Array.from({length:7},(_,weekday)=>({weekday,startMinute:540,endMinute:1020,capacity:1})),policy:{leadTimeMinutes:0,horizonDays:30,slotIntervalMinutes:30},idempotencyKey:'detailing-pub-schedule-0001'};
const path=(kind:string,t=tenant,f=flow)=>`/api/detailing-flows/${f}/${kind}?tenantId=${t}`;
async function fingerprint(tables:string[]){const out:Record<string,unknown>={};for(const table of tables)out[table]=(await pool.query(`select coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]') data from public.${table} x`)).rows[0].data;return out;}
try{
 await pool.query("insert into auth.users(id,email) values($1,'detail-pub-owner@example.test'),($2,'detail-pub-foreign@example.test')",[actor,foreign]);for(const [a,t,type] of [[actor,tenant,'AUTO_DETAILING'],[foreign,foreignTenant,'AUTO_DETAILING'],[actor,housekeeping,'HOUSEKEEPING']])await pool.query('select public.create_staging_business($1,$2,$3,$4,$5,$6,$7,$8)',[a,t,'Detailing business',t,'UTC','USD',type,'detail-pub-business-'+t]);
 const made=await req('/api/catalog/detailing-offers?tenantId='+tenant,offer);assert.equal(made.status,200);const service=made.json.data.service.id;assert.equal((await req(`/api/catalog/detailing-offers/${service}/scheduling?tenantId=${tenant}`,schedule)).status,200);
 const fixedBefore=await fingerprint(['services','service_questions','service_addons','owner_detailing_catalog_creations','owner_detailing_scheduling','availability_rules','scheduling_policies','business_profiles','bookings','payments','capacity_holds','flow_requests']);
 const draft={expectedRevision:0,serviceId:service,name:'Owner published detail menu',presentation:{accentColor:'#4f46e5',layout:'stacked'}};
 for(const b of [{...draft,total:1},{...draft,price:25000},{...draft,tenantId:foreignTenant},{...draft,actor:foreign},{...draft,presentation:{...draft.presentation,accentColor:'url(secret)'}}])assert.equal((await req(path('draft'),b)).status,400);
 assert.equal((await req(path('draft',tenant),draft,'foreign-token-123456')).status,403);assert.equal((await req(path('draft',foreignTenant),draft)).status,403);assert.equal((await req(path('draft',housekeeping),draft)).status,403);assert.equal((await req(path('draft'),draft,'forged-token-123456')).status,401);
 const saved=await req(path('draft'),draft);assert.equal(saved.status,200);assert.deepEqual((await req(path('draft'))).json,saved.json);assert.equal((await req(path('draft'),draft)).status,409);
 const publish={expectedDraftRevision:1,allowedOrigins:[customerOrigin]};assert.equal((await req(path('publish-draft'),{...publish,allowedOrigins:['https://foreign.example.test']})).status,403);const race=await Promise.all([req(path('publish-draft'),publish),req(path('publish-draft'),publish)]);assert.deepEqual(race.map(r=>r.status),[200,200]);assert.deepEqual(race[0],race[1]);const receipt=race[0]!.json.data;assert.equal(receipt.publication.renderSchemaVersion,7);assert.deepEqual(await req(path('publication')),race[0]);assert.equal(Number((await pool.query('select count(*) n from public.flow_versions where flow_id=$1',[flow])).rows[0].n),1);
 const installation=receipt.publication.installationId,session=await req(`/api/detailing-installations/${installation}/sessions`,{},undefined,customerOrigin);assert.equal(session.status,200,JSON.stringify(session));assert.equal(session.json.data.render.renderSchemaVersion,7);assert.equal(session.json.data.render.submissionMode,'detailing_quote');assert.equal(session.json.data.render.paymentMode,'unavailable');assert.equal(session.json.data.render.catalog.packages[1].amount,15000);assert.ok(!JSON.stringify(session.json.data).includes(offer.idempotencyKey));assert.ok(!JSON.stringify(session.json.data).includes(actor));assert.ok(!JSON.stringify(session.json.data).includes(tenant));const token=session.json.data.sessionToken;
 const choice={packageId:'deluxe',vehicleId:'suv',addonIds:['pet-hair'],locationId:'mobile'},quote=()=>req('/api/detailing-flow-sessions/quote',choice,token,customerOrigin);const quoted=await quote();assert.equal(quoted.status,200,JSON.stringify(quoted));assert.deepEqual(quoted.json.data.pricing.total,{amount:25000,currency:'USD'});assert.equal(quoted.json.data.versionId,receipt.publication.versionId);assert.equal(quoted.json.data.installationId,installation);assert.deepEqual(await quote(),quoted);
 for(const b of [{...choice,total:1},{...choice,serviceId:service},{...choice,tenantId:foreignTenant},{...choice,vehicleId:'foreign'},{...choice,addonIds:['foreign']},{...choice,addonIds:['pet-hair','pet-hair']},{...choice,locationId:'foreign'},{packageId:'deluxe',vehicleId:'suv',addonIds:[]}])assert.equal((await req('/api/detailing-flow-sessions/quote',b,token,customerOrigin)).status,400);
 assert.equal((await req('/api/detailing-flow-sessions/quote',choice,token,ownerOrigin)).status,403);assert.equal((await req('/api/detailing-flow-sessions/quote',choice,'bad',customerOrigin)).status,401);
 // Canonical existing customer writers remain closed7; no new booking or financial row.
 const legacyBody={idempotencyKey:'detailing-legacy-attack-001',answers:{package:{choiceIds:['deluxe']},vehicle:{choiceIds:['suv']},location:{choiceIds:['mobile']}},customer:{name:'Fictional',email:'detail-pub-customer@example.test'},requestedStart:new Date(Date.now()+86400000).toISOString()};assert.equal((await req('/api/flow-sessions/request',legacyBody,token,customerOrigin)).status,422);for(const route of ['hold','mock-payment','confirm'])assert.ok([404,422].includes((await req('/api/flow-sessions/'+route,{},token,customerOrigin)).status));assert.equal((await req(`/api/installations/${installation}/sessions`,{},undefined,customerOrigin)).status,422);
 const immutableBefore=await fingerprint(['flow_versions','bound_flow_versions','detailing_publications','flow_installations']);const changed=await req(path('draft'),{...draft,expectedRevision:1,name:'Unpublished new design',presentation:{accentColor:'#0e7490',layout:'compact'}});assert.equal(changed.status,200);assert.equal((await req(path('publication'))).status,404);assert.equal((await req(path('publish-draft'),publish)).status,409);assert.deepEqual(await fingerprint(['flow_versions','bound_flow_versions','detailing_publications','flow_installations']),immutableBefore);assert.deepEqual(await quote(),quoted);
 const second=await req(path('publish-draft'),{...publish,expectedDraftRevision:2});assert.equal(second.status,200);assert.notEqual(second.json.data.publication.versionId,receipt.publication.versionId);assert.deepEqual(await quote(),quoted);const newer=await req(`/api/detailing-installations/${second.json.data.publication.installationId}/sessions`,{},undefined,customerOrigin);assert.equal(newer.status,200);assert.equal(newer.json.data.render.publication.name,'Unpublished new design');assert.deepEqual(await req(path('publication')),second);
 await pool.query('update public.availability_rules set capacity=2 where service_id=$1 and weekday=0',[service]);assert.equal((await quote()).status,409);await pool.query('update public.availability_rules set capacity=1 where service_id=$1 and weekday=0',[service]);await pool.query("update public.service_questions set prompt='Drift' where service_id=$1 and question_key='package'",[service]);assert.equal((await quote()).status,409);await pool.query("update public.service_questions set prompt='Detail package' where service_id=$1 and question_key='package'",[service]);await pool.query("update public.tenants set currency='EUR' where id=$1",[tenant]);assert.equal((await quote()).status,409);await pool.query("update public.tenants set currency='USD' where id=$1",[tenant]);assert.deepEqual(await quote(),quoted);
 await pool.query("update public.tenant_members set role='BUSINESS_STAFF' where tenant_id=$1 and user_id=$2",[tenant,actor]);assert.equal((await req(path('draft'))).status,403);assert.equal((await quote()).status,403);await pool.query("update public.tenant_members set role='BUSINESS_OWNER' where tenant_id=$1 and user_id=$2",[tenant,actor]);await pool.query("update public.tenants set status='inactive' where id=$1",[tenant]);assert.equal((await quote()).status,403);await pool.query("update public.tenants set status='active' where id=$1",[tenant]);
 await pool.query('delete from public.tenant_members where tenant_id=$1 and user_id=$2',[tenant,actor]);assert.equal((await quote()).status,403);await pool.query("insert into public.tenant_members(tenant_id,user_id,role) values($1,$2,'BUSINESS_OWNER')",[tenant,actor]);assert.deepEqual(await quote(),quoted);
 await pool.query('insert into public.flow_installations values($1,$2,$3,$4,$5::jsonb)',[id(98),tenant,flow,receipt.publication.versionId,JSON.stringify([customerOrigin])]);assert.equal((await quote()).status,403);await pool.query('delete from public.flow_installations where id=$1',[id(98)]);assert.deepEqual(await quote(),quoted);
 await pool.query("update public.flow_sessions set expires_at=clock_timestamp()-interval '1 second' where installation_id=$1",[installation]);assert.equal((await quote()).status,403);assert.equal((await req('/api/detailing-flow-sessions/quote',choice,newer.json.data.sessionToken,customerOrigin)).status,200);
 assert.deepEqual(await fingerprint(['services','service_questions','service_addons','owner_detailing_catalog_creations','owner_detailing_scheduling','availability_rules','scheduling_policies','business_profiles','bookings','payments','capacity_holds','flow_requests']),fixedBefore);
 console.log('PASS actual HTTP AUTO_DETAILING save/read/CAS, concurrent immutable7 publish/recovery, exactmenu+schedule lineage,25000 server core quote, foreign/role/currency/catalog/schedule/selection/origin/alias/expiry denial, historical session isolation, all legacy customer writers closed7 and no financial writes');
}finally{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));await pool.end();}
