import {afterEach,expect,it,vi} from 'vitest';
import type {Server} from 'node:http';
import {createFlowHttpServer} from './http';
import {createDetailingSchedulingCreator} from './detailing-scheduling';
import {schedulingAuthoringEnabled} from './owner-scheduling';
import {FlowError} from './repository';
const id=(n:number)=>`47000000-0000-4000-8000-${String(n).padStart(12,'0')}`,actor=id(1),tenant=id(2),service=id(3),origin='https://portal.example.test',body={timezone:'UTC',windows:[{weekday:1,startMinute:540,endMinute:1020,capacity:1 as const}],policy:{leadTimeMinutes:0,horizonDays:30,slotIntervalMinutes:30 as const},idempotencyKey:'schedule-attempt-0001'},receipt={schemaVersion:1 as const,businessType:'AUTO_DETAILING' as const,tenantId:tenant,serviceId:service,timezone:'UTC',windows:[{...body.windows[0]!,id:id(4)}],policy:{...body.policy,id:id(5)}};
let server:Server;afterEach(async()=>{server?.closeAllConnections();if(server)await new Promise<void>(r=>server.close(()=>r()));});
async function http(enabled=true,value:unknown=receipt){const create=vi.fn(async()=>{if(value instanceof Error)throw value;return value as typeof receipt;}),call=vi.fn();server=createFlowHttpServer({repository:{call},schedulingAuthoring:enabled,detailingSchedulingCreate:create,ownerOrigins:[origin],customerOrigins:[],authenticateOwner:async token=>token==='owner-token-123456'?actor:null});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));return{create,call,post:(value:unknown=body,query=`tenantId=${tenant}`,token='owner-token-123456',o=origin,method='POST',s=service)=>fetch(`http://127.0.0.1:${(server.address() as {port:number}).port}/api/catalog/detailing-offers/${s}/scheduling?${query}`,{method,headers:{origin:o,authorization:`Bearer ${token}`,'content-type':'application/json'},...(method==='POST'?{body:JSON.stringify(value)}:{})})};}
it('binds fresh actor/tenant/service and exact explicit setup with no unrelated writer',async()=>{const f=await http(),r=await f.post();expect(r.status).toBe(200);expect(await r.json()).toEqual({ok:true,data:receipt});expect(f.create).toHaveBeenCalledWith(actor,tenant,service,body);expect(f.call).not.toHaveBeenCalled();});
it.each([{actor},{tenantId:tenant},{serviceId:service},{price:12500},{resourceId:id(9)},{workerIds:[]},{capacity:2},{windows:[{weekday:1,startMinute:0,endMinute:1440,capacity:2}]}])('rejects widened authoring %j',async extra=>{const f=await http();expect((await f.post({...body,...extra})).status).toBe(400);expect(f.create).not.toHaveBeenCalled();});
it.each(['',`tenantId=${tenant}&tenantId=${tenant}`,`tenantId=${tenant}&retry=true`])('rejects widened tenant query %s',async query=>{const f=await http();expect((await f.post(body,query)).status).toBe(400);expect(f.create).not.toHaveBeenCalled();});
it('requires fresh identity, exact owner origin and independent gate',async()=>{const f=await http(false);expect((await f.post()).status).toBe(422);expect((await f.post(body,undefined,'forged-token-123456')).status).toBe(401);expect((await f.post(body,undefined,undefined,'https://foreign.example.test')).status).toBe(403);expect(f.create).not.toHaveBeenCalled();});
it('rejects GET and malformed service identity',async()=>{const f=await http();expect((await f.post(body,undefined,undefined,undefined,'GET')).status).toBe(404);expect((await f.post(body,undefined,undefined,undefined,undefined,'bad')).status).toBe(400);expect(f.create).not.toHaveBeenCalled();});
it.each([{...receipt,tenantId:actor},{...receipt,serviceId:actor},{...receipt,timezone:'Europe/Paris'},{...receipt,policy:{...receipt.policy,horizonDays:10}},{...receipt,windows:[{...receipt.windows[0],startMinute:600}]}])('denies mismatched receipt settings',async value=>{const f=await http(true,value);expect((await f.post()).status).toBe(500);});
it.each([['FORBIDDEN',403],['CONFLICT',409],['INVALID_REQUEST',400],['UNSUPPORTED_CONFIG',422]] as const)('preserves safe %s',async(code,status)=>{const f=await http(true,new FlowError(code));expect((await f.post()).status).toBe(status);});
it('gate defaults/production closed independent of fake payments',()=>{expect(schedulingAuthoringEnabled({})).toBe(false);expect(schedulingAuthoringEnabled({BOOKING_LUMIN_ENV:'staging',BOOKING_LUMIN_SCHEDULING_AUTHORING:'1'})).toBe(true);expect(schedulingAuthoringEnabled({BOOKING_LUMIN_ENV:'production',BOOKING_LUMIN_SCHEDULING_AUTHORING:'1'})).toBe(false);expect(schedulingAuthoringEnabled({BOOKING_LUMIN_ENV:'staging',BOOKING_LUMIN_FAKE_PAYMENTS:'1'})).toBe(false);});
function db(value:unknown=receipt,error?:unknown){const release=vi.fn(),query=vi.fn(async(sql:string,..._args:unknown[])=>{if(sql.startsWith('select')){if(error)throw error;return{rows:[{result:value}]};}return{rows:[]};});return{query,release,create:createDetailingSchedulingCreator({connect:async()=>({query,release})} as never)};}
it('fixed RPC transports authored windows, never a new allocator',async()=>{const f=db();expect(await f.create(actor,tenant,service,body)).toEqual(receipt);expect(f.query).toHaveBeenCalledWith('select public.create_auto_detailing_offer_scheduling($1::uuid,$2::uuid,$3::uuid,$4::text,$5::jsonb,$6::integer,$7::integer,$8::integer,$9::text) as result',[actor,tenant,service,'UTC',JSON.stringify(body.windows),0,30,30,body.idempotencyKey]);expect(f.query).toHaveBeenLastCalledWith('commit');});
it('rolls back inconsistent SQL receipt before commit',async()=>{const f=db({...receipt,timezone:'Europe/Paris'});await expect(f.create(actor,tenant,service,body)).rejects.toMatchObject({code:'INTERNAL_ERROR'});expect(f.query).toHaveBeenLastCalledWith('rollback');});
it.each([['42501','FORBIDDEN'],['40001','CONFLICT'],['22023','INVALID_REQUEST'],['XX000','INTERNAL_ERROR']])('redacts SQL failure %s',async(code,expected)=>{const f=db(undefined,{code,message:'secret'});await expect(f.create(actor,tenant,service,body)).rejects.toMatchObject({code:expected,message:expected});expect(f.query).toHaveBeenLastCalledWith('rollback');});
