import assert from 'node:assert/strict';
import {Pool} from 'pg';
import {createFlowHttpServer} from './http';
import {createFlowRepository,createAvailabilityReader} from './repository';
import {createBusinessApi} from './business';
import {createDetailingOfferCreator} from './detailing-catalog';
import {createDetailingSchedulingCreator} from './detailing-scheduling';



assert.equal(process.env.DETAILING_SCHEDULING_LOCAL_TEST,'1');if(process.env.CI==='true'){assert.ok(['localhost','127.0.0.1'].includes(process.env.PGHOST??''));assert.equal(process.env.PGPORT,'5432');}else{assert.equal(process.env.PGHOST,'127.0.0.1');assert.equal(process.env.PGPORT,'55436');}assert.match(process.env.PGDATABASE??'',/^lumin_phase_a_detailing_scheduling_/);for(const key of ['DATABASE_URL','PGHOSTADDR','PGSERVICE','PGSERVICEFILE','PGPASSFILE','PGOPTIONS'])assert.ok(!process.env[key]);
const pool=new Pool({max:10}),failureCodes:string[]=[];const trackedPool={connect:async()=>{const c=await pool.connect();return{query:async(sql:string,params?:unknown[])=>{try{return await c.query(sql,params);}catch(error){if(sql.includes('create_auto_detailing_offer_scheduling'))failureCodes.push((error as {code?:string}).code??'unknown');throw error;}},release:(broken?:boolean)=>c.release(broken)};}};
const id=(n:number)=>`63000000-0000-4000-8000-${String(n).padStart(12,'0')}`,actor=id(1),foreign=id(9),origin='https://portal.example.test',customerOrigin='https://checkout.example.test',business=createBusinessApi(pool),server=createFlowHttpServer({repository:createFlowRepository(pool),businessOnboarding:true,businessCreate:business.create,catalogAuthoring:true,detailingOfferCreate:createDetailingOfferCreator(pool),schedulingAuthoring:true,detailingSchedulingCreate:createDetailingSchedulingCreator(trackedPool as never),availability:createAvailabilityReader(pool),ownerOrigins:[origin],customerOrigins:[customerOrigin],authenticateOwner:async token=>token==='owner-token-123456'?actor:token==='foreign-token-123456'?foreign:null});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
async function post(path:string,body:unknown,token='owner-token-123456',o=origin){const r=await fetch(base+path,{method:'POST',headers:{origin:o,authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify(body)});return{status:r.status,json:await r.json()};}
const body={timezone:'UTC',windows:Array.from({length:7},(_,weekday)=>({weekday,startMinute:540,endMinute:1020,capacity:1})),policy:{leadTimeMinutes:0,horizonDays:30,slotIntervalMinutes:30},idempotencyKey:'scheduling-attempt-0001'};
let tenant:string,service:string;const setup=(b:unknown=body,s=service,t=tenant,token?:string)=>post(`/api/catalog/detailing-offers/${s}/scheduling?tenantId=${t}`,b,token);
const detailing={description:'',currency:'USD',durationMinutes:60,packages:[{id:'basic',label:'Basic',amount:12500}],vehicles:[{id:'sedan',label:'Sedan',multiplierBp:10000}],addons:[],locations:[]};
const offer=(n:number)=>post('/api/catalog/detailing-offers?tenantId='+tenant,{...detailing,name:'Detailing '+n,idempotencyKey:'scheduling-offer-attempt-000'+n});
try{
 await pool.query("insert into auth.users(id,email) values($1,'scheduling-owner-http@example.test'),($2,'scheduling-foreign-http@example.test')",[actor,foreign]);
 const biz=await post('/api/businesses',{name:'Housekeeping',slug:'scheduling-hk-http',timezone:'UTC',currency:'USD',businessType:'AUTO_DETAILING',idempotencyKey:'scheduling-business-attempt-0001'});assert.equal(biz.status,200);tenant=biz.json.data.tenantId;const created=await offer(1);assert.equal(created.status,200);service=created.json.data.service.id;
 async function immutableOffer(){const rows:Record<string,unknown>={};for(const table of ['services','service_questions','service_addons','service_items','owner_detailing_catalog_creations'])rows[table]=(await pool.query(`select coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]') data from public.${table} x where ${table==='services'?'id':'service_id'}=$1`,[service])).rows[0].data;return rows;}const originalOffer=await immutableOffer();
 assert.equal((await setup(body,service,tenant,'foreign-token-123456')).status,403);assert.equal((await setup(body,service,tenant,'forged-token-123456')).status,401);for(const extra of [{timezone:'Europe/Paris'},{price:12500},{tenantId:tenant},{serviceId:service},{windows:[{weekday:1,startMinute:540,endMinute:1020,capacity:2}]},{windows:[{weekday:1,startMinute:540,endMinute:550,capacity:1}]},{policy:{...body.policy,horizonDays:31}}])assert.equal((await setup({...body,...extra})).status,400);
 const auto=await post('/api/businesses',{name:'Housekeeping',slug:'scheduling-housekeeping-http',timezone:'UTC',currency:'USD',businessType:'HOUSEKEEPING',idempotencyKey:'scheduling-business-attempt-0002'});assert.equal((await setup(body,service,auto.json.data.tenantId)).status,403);
 // Unrelated same-tenant rows can become target-specific or tenant-wide without
 // changing tenant_id. Both fresh setup and replay must fence these updates.
 const unrelated=(await offer(8)).json.data.service.id;
 const independent=(await post('/api/businesses',{name:'Independent',slug:'scheduling-independent-http',timezone:'UTC',currency:'USD',businessType:'AUTO_DETAILING',idempotencyKey:'scheduling-independent-business'})).json.data.tenantId;
 const independentOffer=(await post('/api/catalog/detailing-offers?tenantId='+independent,{...detailing,name:'Independent detailing',idempotencyKey:'scheduling-independent-offer'})).json.data.service.id;
 await pool.query('insert into public.availability_rules(id,tenant_id,service_id,weekday,start_minute,end_minute,capacity) values($1,$2,$3,0,0,1440,1)',[id(83),independent,independentOffer]);
 await pool.query('insert into public.availability_rules(id,tenant_id,service_id,weekday,start_minute,end_minute,capacity) values($1,$2,$3,0,0,1440,2)',[id(80),tenant,unrelated]);
 await pool.query("insert into public.availability_overrides(id,tenant_id,service_id,date,kind) values($1,$2,$3,current_date,'closed')",[id(81),tenant,unrelated]);
 await pool.query('insert into public.scheduling_policies(id,tenant_id,service_id) values($1,$2,$3)',[id(82),tenant,unrelated]);
 await pool.query('insert into public.resources(id,tenant_id,name) values($1,$2,$3)',[id(89),tenant,'Concurrent fixture resource']);
 async function proveReassignmentFence(){
  const guard=await pool.connect(),other=await pool.connect();
  try{
   await guard.query('begin');await guard.query('set local role service_role');
   await guard.query('select public.create_auto_detailing_offer_scheduling($1,$2,$3,$4,$5::jsonb,$6,$7,$8,$9)',[actor,tenant,service,'UTC',JSON.stringify(body.windows),0,30,30,body.idempotencyKey]);
   // Service/tenant fences reject concurrent resource and planning opt-in.
   for(const [sql,params] of [["insert into public.service_resources(tenant_id,service_id,resource_id) values($1,$2,$3)",[tenant,service,id(89)]],["insert into public.allocation_policies(tenant_id,service_id,revision,setup_minutes,cleanup_minutes,ttl_seconds,resource_mode) values($1,$2,1,0,0,60,'none')",[tenant,service]]] as const){await other.query('begin');await other.query("set local lock_timeout='100ms'");await assert.rejects(other.query(sql,[...params]),(error:unknown)=>(error as {code?:string}).code==='55P03');await other.query('rollback');}
   // Locks stay scoped to this tenant; another tenant's configuration can update.
   await other.query('begin');await other.query("set local lock_timeout='100ms'");
   assert.equal((await other.query('update public.availability_rules set capacity=2 where id=$1',[id(83)])).rowCount,1);await other.query('rollback');
   for(const [table,row] of [['availability_rules',id(80)],['availability_overrides',id(81)],['scheduling_policies',id(82)]]){
    for(const target of [service,null]){
     await other.query('begin');await other.query("set local lock_timeout='100ms'");
     await assert.rejects(other.query(`update public.${table} set service_id=$1 where id=$2`,[target,row]),(error:unknown)=>(error as {code?:string}).code==='55P03');
     await other.query('rollback');
    }
   }
  }finally{await other.query('rollback');await guard.query('rollback');other.release();guard.release();}
 }
 await proveReassignmentFence();
 // An in-flight setup fences a competing alias rule via tenant FK KEY SHARE.
 const guard=await pool.connect(),alias=await pool.connect();try{await guard.query('begin');await guard.query('set local role service_role');await guard.query('select public.create_auto_detailing_offer_scheduling($1,$2,$3,$4,$5::jsonb,$6,$7,$8,$9)',[actor,tenant,service,'UTC',JSON.stringify(body.windows),0,30,30,body.idempotencyKey]);await alias.query('begin');await alias.query("set local lock_timeout='100ms'");await assert.rejects(alias.query('insert into public.availability_rules(tenant_id,service_id,weekday,start_minute,end_minute,capacity) values($1,$2,0,0,1440,2)',[tenant,service]),(e:unknown)=>(e as {code?:string}).code==='55P03');}finally{await alias.query('rollback');await guard.query('rollback');alias.release();guard.release();}
 failureCodes.length=0;const race=await Promise.all([setup(),setup()]);assert.ok(race.some(r=>r.status===200));assert.ok(race.every(r=>r.status===200||r.status===409));assert.ok(failureCodes.every(code=>['55P03','57014','40P01'].includes(code)),JSON.stringify(failureCodes));console.log('PASS scheduling same-key statuses '+JSON.stringify(race.map(r=>r.status))+' sanitized SQLSTATEs '+JSON.stringify(failureCodes));const settled=await setup();assert.equal(settled.status,200);for(const r of race.filter(r=>r.status===200))assert.deepEqual(r,settled);const receipt=settled.json.data;assert.equal(receipt.serviceId,service);assert.equal(receipt.tenantId,tenant);assert.equal(receipt.windows.length,7);assert.equal(Number((await pool.query('select count(*) n from public.availability_rules where service_id=$1',[service])).rows[0].n),7);assert.equal((await setup({...body,idempotencyKey:'scheduling-attempt-0002'})).status,409);
 await proveReassignmentFence();console.log('PASS fresh and replay fence same-tenant rule/override/policy reassignment into target and tenant-wide NULL');
 // Force the bounded tenant lock timeout, then explicitly reconcile by same-body replay.
 const deadline=await pool.connect();try{await deadline.query('begin');await deadline.query('select id from public.tenants where id=$1 for update',[tenant]);failureCodes.length=0;assert.equal((await setup()).status,409);assert.deepEqual(failureCodes,['55P03']);}finally{await deadline.query('rollback');deadline.release();}failureCodes.length=0;const reconciled=await setup();assert.deepEqual(reconciled,settled,'post-deadline replay SQLSTATEs '+JSON.stringify(failureCodes));console.log('PASS sanitized scheduling lock deadline SQLSTATE55P03; exact subsequent replay, no new configuration');
 const second=(await offer(2)).json.data.service.id,distinct=await Promise.all([setup({...body,idempotencyKey:'scheduling-distinct-0001'},second),setup({...body,idempotencyKey:'scheduling-distinct-0002'},second)]);assert.deepEqual(distinct.map(r=>r.status).sort(),[200,409]);assert.equal(Number((await pool.query('select count(*) n from public.scheduling_policies where service_id=$1',[second])).rows[0].n),1);
 await pool.query('update public.availability_rules set capacity=2 where id=$1',[receipt.windows[0].id]);assert.equal((await setup()).status,409);await pool.query('update public.availability_rules set capacity=1 where id=$1',[receipt.windows[0].id]);
 await pool.query("update public.tenant_members set role='BUSINESS_STAFF' where tenant_id=$1 and user_id=$2",[tenant,actor]);assert.equal((await setup()).status,403);await pool.query("update public.tenant_members set role='BUSINESS_OWNER' where tenant_id=$1 and user_id=$2",[tenant,actor]);await pool.query("update public.tenants set status='inactive' where id=$1",[tenant]);assert.equal((await setup()).status,403);await pool.query("update public.tenants set status='active' where id=$1",[tenant]);await pool.query('delete from public.tenant_members where tenant_id=$1 and user_id=$2',[tenant,actor]);assert.equal((await setup()).status,403);await pool.query("insert into public.tenant_members(tenant_id,user_id,role) values($1,$2,'BUSINESS_OWNER'),($1,$3,'BUSINESS_OWNER')",[tenant,actor,foreign]);assert.equal((await setup(body,service,tenant,'foreign-token-123456')).status,403);
 for(const table of ['flow_versions','flow_installations','flow_sessions','bookings','payments','capacity_holds'])assert.equal(Number((await pool.query(`select count(*) n from public.${table}`)).rows[0].n),0);
 // Actual existing owner availability engine consumes the authored rules and service duration.
 const tomorrow=new Date(Date.now()+86400000);tomorrow.setUTCHours(0,0,0,0);const from=tomorrow.toISOString(),to=new Date(+tomorrow+86400000).toISOString();
 const r=await fetch(base+'/api/availability?tenantId='+tenant+'&serviceId='+service+'&from='+encodeURIComponent(from)+'&to='+encodeURIComponent(to),{headers:{origin,authorization:'Bearer owner-token-123456'}});assert.equal(r.status,200);const available=(await r.json()).data;assert.ok(available.slots.length>0);assert.ok(available.slots.every((s:{start:string;end:string})=>new Date(s.start).getUTCHours()>=9&&new Date(s.end).getUTCHours()<=17&&+new Date(s.end)-+new Date(s.start)===3600000));
 // A legitimate later booking does not turn exact replay into a restore writer.
 await pool.query("insert into public.bookings(id,tenant_id,reference,selection,slot_start,slot_end,idempotency_key) values($1,$2,'LMN-DETAILING-SCHEDULE',jsonb_build_object('serviceId',$3::text),$4,$5,'detailing-schedule-booking-001')",[id(99),tenant,service,available.slots[0].start,available.slots[0].end]);assert.deepEqual(await setup(),settled);
 await pool.query("update public.tenants set currency='EUR' where id=$1",[tenant]);assert.equal((await setup()).status,409);await pool.query("update public.tenants set currency='USD' where id=$1",[tenant]);
 await pool.query("update public.service_questions set prompt='Drift' where service_id=$1 and question_key='package'",[service]);assert.equal((await setup()).status,409);await pool.query("update public.service_questions set prompt='Detail package' where service_id=$1 and question_key='package'",[service]);assert.deepEqual(await setup(),settled);
 await pool.query('insert into public.resources(id,tenant_id,name) values($1,$2,$3)',[id(90),tenant,'Fixture resource']);await pool.query('insert into public.service_resources(tenant_id,service_id,resource_id) values($1,$2,$3)',[tenant,service,id(90)]);assert.equal((await setup()).status,422);await pool.query('delete from public.service_resources where tenant_id=$1 and service_id=$2',[tenant,service]);
 await pool.query("insert into public.allocation_policies(tenant_id,service_id,revision,setup_minutes,cleanup_minutes,ttl_seconds,resource_mode) values($1,$2,1,0,0,60,'none')",[tenant,service]);assert.equal((await setup()).status,422);
 for(const table of ['flow_versions','flow_installations','flow_sessions','payments','capacity_holds'])assert.equal(Number((await pool.query(`select count(*) n from public.${table}`)).rows[0].n),0);
 assert.deepEqual(await immutableOffer(),originalOffer);
 console.log('PASS actual HTTP AUTO_DETAILING explicit capacity1 scheduling: owner/profile/catalog/currency isolation, concurrent single configuration, exact immutable replay including later booking, bounded lock deadline, tenant scoped reassignment fence, existing owner availability, resources/planning closed; no customer/financial authority');
}finally{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));await pool.end();}
