import {expect,it,vi} from 'vitest';
import {buildDetailingService} from '@lumin/contracts';
import {createDetailingAvailabilityReader} from './detailing-availability';
const id=(n:number)=>`65000000-0000-4000-8000-${String(n).padStart(12,'0')}`,service=id(4),tenant=id(2),origin='https://checkout.example.test';
const catalog={name:'Detail',description:'',currency:'USD',durationMinutes:60,packages:[{id:'basic',label:'Basic',amount:8000}],vehicles:[{id:'sedan',label:'Sedan',multiplierBp:10000}],addons:[],locations:[]};
const windows=Array.from({length:7},(_,weekday)=>({id:id(10+weekday),weekday,startMinute:540,endMinute:1020,capacity:1}));
const context={service:buildDetailingService(service,tenant,{...catalog,idempotencyKey:'availability-fixture-0001'}),catalog,scheduling:{schemaVersion:1,businessType:'AUTO_DETAILING',tenantId:tenant,serviceId:service,timezone:'UTC',windows,policy:{id:id(20),leadTimeMinutes:0,horizonDays:30,slotIntervalMinutes:30}},render:{versionId:id(5),renderSchemaVersion:7,businessType:'AUTO_DETAILING',submissionMode:'detailing_quote',bookingMode:'unavailable',paymentMode:'unavailable',pricingModel:'package_subtotal_vehicle_multiplier',serviceId:service,catalog,publication:{name:'Detail form',presentation:{accentColor:'#4f46e5',layout:'stacked'},draftRevision:1}},installationId:id(6),expiresAt:'2030-01-10T00:00:00.000Z'};
const query={from:'2030-01-02T00:00:00.000Z',to:'2030-01-03T00:00:00.000Z'};
function fixture(values:unknown[]= [context,context],clock=()=>Date.parse('2030-01-01T00:00:00.000Z'),consumers:unknown[]=[]){let checks=0;const release=vi.fn(),sql=vi.fn(async(statement:string,args?:unknown[])=>{if(statement.includes('resolve_detailing_flow_session')){const value=values[checks++];if(value instanceof Error)throw value;return{rows:[{result:value}]};}if(statement.includes('from public.availability_rules'))return{rows:windows.map(w=>({...w,tenantId:tenant,serviceId:service}))};if(statement.includes('from public.scheduling_policies'))return{rows:[context.scheduling.policy]};if(statement.includes('from public.capacity_holds'))return{rows:consumers};return{rows:[]};});const connect=vi.fn(async()=>({query:sql,release}));return{sql,release,connect,reader:createDetailingAvailabilityReader({connect} as never,[origin],clock)};}
it('uses existing allocator and authoritative duration/timezone; rechecks exact context before commit',async()=>{const f=fixture(),r=await f.reader('a'.repeat(64),origin,query);expect(r).toMatchObject({versionId:id(5),installationId:id(6),serviceId:service,durationMinutes:60,timezone:'UTC'});expect(r.slots).toHaveLength(15);expect(r.slots[0]).toEqual({start:'2030-01-02T09:00:00.000Z',end:'2030-01-02T10:00:00.000Z',remainingCapacity:1});expect(f.sql.mock.calls.filter(c=>c[0].includes('resolve_detailing_flow_session'))).toHaveLength(2);expect(f.sql).toHaveBeenLastCalledWith('commit');expect(f.sql.mock.calls.some(c=>/insert|update |delete /i.test(c[0]))).toBe(false);});
it('honors canonical existing capacity consumers',async()=>{const f=fixture(undefined,undefined,[{start:'2030-01-02T09:00:00.000Z',end:'2030-01-02T10:00:00.000Z',booking_id:id(30)}]);const r=await f.reader('a'.repeat(64),origin,query);expect(r.slots[0]!.start).toBe('2030-01-02T10:00:00.000Z');expect(r.slots).toHaveLength(13);});
it.each([{...query,tenantId:tenant},{...query,serviceId:service},{...query,to:query.from},{...query,to:'2030-02-01T00:00:00.000Z'}])('rejects query authority/range before DB %j',async input=>{const f=fixture();await expect(f.reader('a'.repeat(64),origin,input)).rejects.toMatchObject({code:'INVALID_REQUEST'});expect(f.connect).not.toHaveBeenCalled();});
it('rejects foreign origin/forged hash before DB',async()=>{const f=fixture();await expect(f.reader('a'.repeat(64),'https://foreign.example.test',query)).rejects.toMatchObject({code:'INVALID_REQUEST'});await expect(f.reader('token',origin,query)).rejects.toMatchObject({code:'INVALID_REQUEST'});expect(f.connect).not.toHaveBeenCalled();});
it('discards slots on final expiry, final context drift or revoked authority',async()=>{let calls=0;const expired=fixture(undefined,()=>++calls>=3?Date.parse(context.expiresAt):Date.parse(query.from));await expect(expired.reader('a'.repeat(64),origin,query)).rejects.toMatchObject({code:'FORBIDDEN'});expect(expired.sql).toHaveBeenLastCalledWith('rollback');const changed=fixture([context,{...context,installationId:id(90)}]);await expect(changed.reader('a'.repeat(64),origin,query)).rejects.toMatchObject({code:'CONFLICT'});expect(changed.sql).toHaveBeenLastCalledWith('rollback');const denied=fixture([context,Object.assign(new Error('private SQL details'),{code:'42501'})]);await expect(denied.reader('a'.repeat(64),origin,query)).rejects.toMatchObject({code:'FORBIDDEN',message:'FORBIDDEN'});});
it('fails closed malformed private snapshot or service binding',async()=>{await expect(fixture([{...context,secret:'never-return'}]).reader('a'.repeat(64),origin,query)).rejects.toMatchObject({code:'INTERNAL_ERROR'});await expect(fixture([{...context,service:{...context.service,name:'Drift'}}]).reader('a'.repeat(64),origin,query)).rejects.toMatchObject({code:'FORBIDDEN'});});
it.each(['55P03','57014','40P01'])('sanitizes finite SQL contention %s',async code=>{const f=fixture([Object.assign(new Error('raw SQL'),{code})]);await expect(f.reader('a'.repeat(64),origin,query)).rejects.toMatchObject({code:'CONFLICT',message:'CONFLICT'});expect(f.sql).toHaveBeenLastCalledWith('rollback');});

// Actual HTTP boundary keeps the dedicated route closed unless explicitly composed.
import {afterEach} from 'vitest';
import type {Server} from 'node:http';
import {createFlowHttpServer} from './http';
const servers:Server[]=[];
afterEach(async()=>{for(const server of servers.splice(0)){server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));}});
async function http(enabled=true,value:unknown=undefined){const read=vi.fn(async(..._args:unknown[])=>value??{schemaVersion:1,versionId:id(5),installationId:id(6),serviceId:service,expiresAt:context.expiresAt,durationMinutes:60,timezone:'UTC',slots:[]});const server=createFlowHttpServer({repository:{call:vi.fn()} as never,customerOrigins:[origin],ownerOrigins:['https://portal.example.test'],detailingPublication:enabled,detailingAvailability:read as never});servers.push(server);await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${(server.address() as {port:number}).port}`;return{read,request:async(suffix='',token='a'.repeat(43),o=origin,method='GET')=>{const response=await fetch(base+'/api/detailing-flow-sessions/availability?'+new URLSearchParams(query)+suffix,{method,headers:{origin:o,authorization:`Bearer ${token}`}});return{status:response.status,json:await response.json()};}};}
it('actual GET validates and hashes private bearer; no customer tenant injection',async()=>{const f=await http();expect((await f.request()).status).toBe(200);expect(f.read).toHaveBeenCalledWith(expect.stringMatching(/^[a-f0-9]{64}$/),origin,query);expect(f.read.mock.calls[0]?.[0]).not.toBe('a'.repeat(43));});
it.each(['&tenantId='+tenant,'&serviceId='+service,'&price=1','&from='+query.from,'&to='+query.to])('actual GET rejects extra/duplicate query %s',async suffix=>{const f=await http();expect((await f.request(suffix)).status).toBe(400);expect(f.read).not.toHaveBeenCalled();});
it('actual route preserves closed gate, exact origin and bearer/method authority',async()=>{expect((await(await http(false)).request()).status).toBe(422);const f=await http();expect((await f.request('','bad')).status).toBe(401);expect((await f.request('','a'.repeat(43),'https://foreign.example.test')).status).toBe(403);expect((await f.request('','a'.repeat(43),origin,'POST')).status).toBe(400);expect(f.read).not.toHaveBeenCalled();});
it('actual route never emits malformed or out-of-range server receipts',async()=>{const f=await http(true,{schemaVersion:1,versionId:id(5),installationId:id(6),serviceId:service,expiresAt:context.expiresAt,durationMinutes:60,timezone:'UTC',slots:[{start:'2030-01-04T09:00:00.000Z',end:'2030-01-04T10:00:00.000Z',remainingCapacity:1}]});expect((await f.request()).status).toBe(500);});
