import {afterEach,expect,it,vi} from 'vitest';
import type {Server} from 'node:http';
import {buildDetailingService} from '@lumin/contracts';
import {createPricingEngine} from '@lumin/core';
import {createDetailingReservationApi} from './detailing-reservation';
import {createFlowHttpServer} from './http';
const mocks=vi.hoisted(()=>({reserve:vi.fn(),availability:vi.fn()}));
vi.mock('./reservation',async()=>({...await vi.importActual<typeof import('./reservation')>('./reservation'),reserveBookingInTransaction:mocks.reserve}));
vi.mock('./repository',async()=>({...await vi.importActual<typeof import('./repository')>('./repository'),readAvailabilitySlots:mocks.availability}));
const id=(n:number)=>`66000000-0000-4000-8000-${String(n).padStart(12,'0')}`,service=id(4),tenant=id(2),origin='https://checkout.example.test',hash='a'.repeat(64),now=Date.parse('2030-01-01T00:00:00.000Z');
const catalog={name:'Detail',description:'',currency:'USD',durationMinutes:60,packages:[{id:'deluxe',label:'Deluxe',amount:15000}],vehicles:[{id:'suv',label:'SUV',multiplierBp:12500}],addons:[{id:'pet-hair',name:'Pet hair',amount:3000}],locations:[{id:'mobile',label:'Mobile',amount:2000}]};
const context={service:buildDetailingService(service,tenant,{...catalog,idempotencyKey:'reservation-fixture-0001'}),catalog,scheduling:{schemaVersion:1,businessType:'AUTO_DETAILING',tenantId:tenant,serviceId:service,timezone:'UTC',windows:[{id:id(10),weekday:3,startMinute:540,endMinute:1020,capacity:1}],policy:{id:id(20),leadTimeMinutes:0,horizonDays:30,slotIntervalMinutes:30}},render:{versionId:id(5),renderSchemaVersion:7,businessType:'AUTO_DETAILING',submissionMode:'detailing_quote',bookingMode:'unavailable',paymentMode:'unavailable',pricingModel:'package_subtotal_vehicle_multiplier',serviceId:service,catalog,publication:{name:'Detail form',presentation:{accentColor:'#4f46e5',layout:'stacked'},draftRevision:1}},installationId:id(6),expiresAt:'2030-01-10T00:00:00.000Z'};
const selection={packageId:'deluxe',vehicleId:'suv',addonIds:['pet-hair'],locationId:'mobile'},input={schemaVersion:1 as const,idempotencyKey:'reservation-test-0001',selection,customer:{name:'Fictional',email:'fictional@example.test'},requestedStart:'2030-01-02T09:00:00.000Z'},pricing=createPricingEngine().price(context.service,{serviceId:service,itemQuantities:{},addonIds:selection.addonIds,answers:{package:{choiceIds:['deluxe']},vehicle:{choiceIds:['suv']},location:{choiceIds:['mobile']}}});
const receipt={schemaVersion:1,versionId:id(5),installationId:id(6),serviceId:service,bookingId:id(30),reference:'LMN-ABC123',selection,pricing,slot:{start:input.requestedStart,end:'2030-01-02T10:00:00.000Z'},state:'draft',confirmed:false,paymentMode:'unavailable'};
const held={bookingId:id(30),holdId:id(31),status:'active',expiresAt:'2030-01-01T00:05:00.000Z'};
function fixture(options:{context?:unknown;receipt?:unknown;finalContext?:unknown;old?:unknown;replayed?:boolean;empty?:boolean;clock?:()=>number;error?:string}={}){let targets=0;const release=vi.fn(),query=vi.fn(async(sql:string,_args?:unknown[])=>{if(options.error&&sql.includes('select public'))throw Object.assign(new Error('private raw SQL'),{code:options.error});if(sql.includes('reservation_context'))return{rows:[{result:options.context??context}]};if(sql.includes('submit_detailing_reservation'))return{rows:[{result:{receipt:options.receipt??receipt,replayed:options.replayed??false}}]};if(sql.includes('reservation_target'))return{rows:[{result:{context:++targets>=1?options.finalContext??options.context??context:context,receipt:options.receipt??receipt}}]};if(sql.includes('from public.capacity_holds'))return{rows:options.old?[options.old]:[]};return{rows:[]};});const connect=vi.fn(async()=>({query,release}));mocks.reserve.mockResolvedValue(held);mocks.availability.mockResolvedValue({serviceId:service,durationMinutes:60,slots:options.empty?[]:[{...receipt.slot,remainingCapacity:1}]});return{query,release,connect,api:createDetailingReservationApi({connect} as never,[origin],options.clock??(()=>now))};}
it('prices authoritative selected package+addons+location with unchanged core multiplier and validates receipt',async()=>{const f=fixture();expect(await f.api.request(hash,origin,input)).toEqual(receipt);expect(receipt.pricing.total.amount).toBe(25000);const args=f.query.mock.calls.find(c=>c[0].includes('submit_detailing'))?.[1] as unknown[];expect(JSON.parse(args[7] as string)).toEqual(pricing);expect(f.query).toHaveBeenLastCalledWith('commit');});
it('checks fresh slot before committing but preserves exact committed replay while own hold consumes capacity',async()=>{const empty=fixture({empty:true});await expect(empty.api.request(hash,origin,input)).rejects.toMatchObject({code:'NOT_AVAILABLE'});expect(empty.query).toHaveBeenLastCalledWith('rollback');const replay=fixture({replayed:true,empty:true});expect(await replay.api.request(hash,origin,input)).toEqual(receipt);expect(replay.query).toHaveBeenLastCalledWith('commit');});
it.each([{...input,total:1},{...input,tenantId:tenant},{...input,selection:{...selection,vehicleId:'foreign'}},{...input,selection:{...selection,addonIds:['foreign']}},{...input,selection:{...selection,packageId:'foreign'}}])('rejects monetary or unsupported selection %j',async body=>{await expect(fixture().api.request(hash,origin,body)).rejects.toMatchObject({code:'INVALID_REQUEST'});});
it('rejects changed response price or version without committing',async()=>{for(const bad of [{...receipt,versionId:id(99)},{...receipt,pricing:{...pricing,total:{amount:1,currency:'USD'}}}]){const f=fixture({receipt:bad});await expect(f.api.request(hash,origin,input)).rejects.toMatchObject({code:'INTERNAL_ERROR'});expect(f.query).toHaveBeenLastCalledWith('rollback');}});
it('rechecks final pinned context and expiry after request',async()=>{const drift=fixture({finalContext:{...context,render:{...context.render,publication:{...context.render.publication,name:'Changed immutable title'}}}});await expect(drift.api.request(hash,origin,input)).rejects.toMatchObject({code:'CONFLICT'});let checks=0;const expired=fixture({clock:()=>++checks>=2?Date.parse(context.expiresAt):now});await expect(expired.api.request(hash,origin,input)).rejects.toMatchObject({code:'FORBIDDEN'});expect(expired.query).toHaveBeenLastCalledWith('rollback');});
it('hold uses persisted target and canonical shared allocator; exact active retry returns same receipt',async()=>{const f=fixture({old:{status:'active',expires_at:held.expiresAt}});const r=await f.api.hold(hash,origin);expect(r).toEqual({schemaVersion:1,versionId:id(5),installationId:id(6),serviceId:service,...held});expect(mocks.reserve).toHaveBeenCalledWith(expect.anything(),tenant,id(30),expect.any(Function),service);expect(f.query).toHaveBeenLastCalledWith('commit');});
it.each([{status:'released',expires_at:held.expiresAt},{status:'consumed',expires_at:held.expiresAt},{status:'active',expires_at:'2000-01-01T00:00:00.000Z'}])('never renews expired/nonactive receipt %j',async old=>{mocks.reserve.mockClear();await expect(fixture({old}).api.hold(hash,origin)).rejects.toMatchObject({code:'CONFLICT'});expect(mocks.reserve).not.toHaveBeenCalled();});
it('rolls back shared hold on final session expiry',async()=>{let checks=0;const f=fixture({clock:()=>++checks>=2?Date.parse(context.expiresAt):now});await expect(f.api.hold(hash,origin)).rejects.toMatchObject({code:'FORBIDDEN'});expect(f.query).toHaveBeenLastCalledWith('rollback');});
it.each(['42501','55P03','40P01','22023'])('sanitizes authority/lock/validation SQLSTATE %s',async error=>{await expect(fixture({error}).api.request(hash,origin,input)).rejects.toMatchObject({message:error==='42501'?'FORBIDDEN':error==='22023'?'INVALID_REQUEST':'CONFLICT'});});
it('rejects spoofed bearer hash and foreign origin before DB',async()=>{const f=fixture();await expect(f.api.hold('token',origin)).rejects.toMatchObject({code:'INVALID_REQUEST'});await expect(f.api.request(hash,'https://foreign.example.test',input)).rejects.toMatchObject({code:'INVALID_REQUEST'});expect(f.connect).not.toHaveBeenCalled();});
const servers:Server[]=[];afterEach(async()=>{for(const s of servers.splice(0)){s.closeAllConnections();await new Promise<void>(r=>s.close(()=>r()));}});
async function http(enabled=true){const api={request:vi.fn(async()=>receipt),hold:vi.fn(async()=>({schemaVersion:1,versionId:id(5),installationId:id(6),serviceId:service,...held}))};const server=createFlowHttpServer({repository:{call:vi.fn()} as never,customerOrigins:[origin],ownerOrigins:['https://portal.example.test'],detailingPublication:enabled,detailingReservationApi:api as never});servers.push(server);await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${(server.address() as {port:number}).port}`;return{api,req:async(kind:string,body:unknown,token='a'.repeat(43),o=origin)=>{const r=await fetch(base+'/api/detailing-flow-sessions/'+kind,{method:'POST',headers:{origin:o,authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify(body)});return{status:r.status,json:await r.json()};}};}
it('actual strict request/empty hold transport hashes bearer and preserves staged gate',async()=>{const f=await http();expect((await f.req('request',input)).status).toBe(200);expect((await f.req('hold',{})).status).toBe(200);expect(f.api.hold).toHaveBeenCalledWith(expect.stringMatching(/^[0-9a-f]{64}$/),origin);expect((await f.req('hold',{bookingId:id(90)})).status).toBe(400);expect((await f.req('request',{...input,total:1})).status).toBe(400);expect((await f.req('request?tenantId='+tenant,input)).status).toBe(400);expect((await f.req('hold',{},'bad')).status).toBe(401);expect((await f.req('hold',{},'a'.repeat(43),'https://foreign.example.test')).status).toBe(403);expect((await(await http(false)).req('request',input)).status).toBe(422);});
