import {afterEach,it,expect,vi} from 'vitest';
import type {Server} from 'node:http';
import {createPricingEngine} from '@lumin/core';
import {Service,Selection,buildDetailingService} from '@lumin/contracts';
import {createDetailingOfferCreator,createDetailingOfferReader} from './detailing-catalog';
import {createFlowHttpServer} from './http';
import {catalogAuthoringEnabled} from './owner-catalog';
const body={name:'Detail package menu',description:'Owner authored detailing',currency:'USD',durationMinutes:120,packages:[{id:'basic',label:'Basic',amount:8000},{id:'deluxe',label:'Deluxe',amount:15000}],vehicles:[{id:'sedan',label:'Sedan',multiplierBp:10000},{id:'suv',label:'SUV',multiplierBp:12500}],addons:[{id:'pet-hair',name:'Pet hair',amount:3000}],locations:[{id:'studio',label:'Studio',amount:0},{id:'mobile',label:'Mobile visit',amount:2000}],idempotencyKey:'detailing-create-fixture-001'};
const id=(n:number)=>`62000000-0000-4000-8000-${String(n).padStart(12,'0')}`,actor=id(1),tenant=id(2),service=id(3),origin='https://portal.example.test';const receipt={schemaVersion:1,tenantId:tenant,businessType:'AUTO_DETAILING',pricingModel:'package_subtotal_vehicle_multiplier',service:buildDetailingService(service,tenant,body)};
function db(value:unknown=receipt,error?:unknown){const release=vi.fn(),query=vi.fn(async(sql:string)=>{if(sql.startsWith('select')){if(error)throw error;return{rows:[{result:value}]};}return{rows:[]};});const pool={connect:async()=>({query,release})} as never;return{query,release,create:createDetailingOfferCreator(pool),read:createDetailingOfferReader(pool)};}
it('prices authoritative read config using the unchanged shared engine and explicit multiplied extras',()=>{const pricing=createPricingEngine(),s=Service.parse(receipt.service);const selection=Selection.parse({serviceId:service,addonIds:['pet-hair'],answers:{package:{choiceIds:['deluxe']},vehicle:{choiceIds:['suv']},location:{choiceIds:['mobile']}}});expect(pricing.price(s,selection).total).toEqual({amount:25000,currency:'USD'});expect(()=>pricing.price(s,{...selection,answers:{...selection.answers,package:{choiceIds:['foreign']}}})).toThrow();const rounded=buildDetailingService(service,tenant,{...body,packages:[{id:'basic',label:'Basic',amount:101}],addons:[],locations:[],vehicles:[{id:'suv',label:'SUV',multiplierBp:12500}]});expect(pricing.price(Service.parse(rounded),Selection.parse({serviceId:service,answers:{package:{choiceIds:['basic']},vehicle:{choiceIds:['suv']}}})).total.amount).toBe(126);});
it('validates initial receipt before commit and uses only fixed owner create/read RPCs',async()=>{const f=db();expect(await f.create(actor,tenant,body)).toEqual(receipt);expect(f.query).toHaveBeenCalledWith('select public.create_auto_detailing_offer($1::uuid,$2::uuid,$3::uuid,$4::jsonb) as result',[actor,tenant,expect.any(String),JSON.stringify(body)]);expect(f.query).toHaveBeenLastCalledWith('commit');expect(await f.read(actor,tenant,service)).toEqual(receipt);expect(f.query).toHaveBeenCalledWith('begin isolation level read committed');expect(f.query).toHaveBeenCalledWith('select public.owner_detailing_offer($1::uuid,$2::uuid,$3::uuid) as result',[actor,tenant,service]);});
it.each([{...receipt,tenantId:id(9)},{...receipt,service:{...receipt.service,currency:'EUR'}},{...receipt,service:{...receipt.service,questions:[]}},{...receipt,total:1}])('rolls back malformed or changed financial evidence before commit',async bad=>{const f=db(bad);await expect(f.create(actor,tenant,body)).rejects.toMatchObject({code:'INTERNAL_ERROR'});expect(f.query).toHaveBeenLastCalledWith('rollback');});
it.each([['42501','FORBIDDEN'],['P0002','NOT_AVAILABLE'],['22023','INVALID_REQUEST'],['40001','CONFLICT'],['55P03','CONFLICT'],['XX000','INTERNAL_ERROR']])('redacts SQL failures %s',async(code,expected)=>{await expect(db(undefined,{code,message:'secret'}).create(actor,tenant,body)).rejects.toMatchObject({code:expected,message:expected});});
it('uses separate default closed staging catalog flag',()=>{expect(catalogAuthoringEnabled({BOOKING_LUMIN_ENV:'staging',BOOKING_LUMIN_CATALOG_AUTHORING:'1'})).toBe(true);for(const env of [{},{BOOKING_LUMIN_ENV:'staging'},{BOOKING_LUMIN_ENV:'production',BOOKING_LUMIN_CATALOG_AUTHORING:'1'}])expect(catalogAuthoringEnabled(env)).toBe(false);});
let server:Server;afterEach(async()=>{server?.closeAllConnections();if(server)await new Promise<void>(r=>server.close(()=>r()));});
async function http(enabled=true,value:unknown=receipt){const create=vi.fn(async()=>value as never),read=vi.fn(async()=>value as never),call=vi.fn();server=createFlowHttpServer({repository:{call},catalogAuthoring:enabled,detailingOfferCreate:create,detailingOfferRead:read,ownerOrigins:[origin],customerOrigins:[],authenticateOwner:async t=>t==='owner-token-123456'?actor:null});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${(server.address() as {port:number}).port}`;return{create,read,call,request:(method='POST',value:unknown=body,query=`tenantId=${tenant}`,token='owner-token-123456',o=origin)=>fetch(base+`/api/catalog/detailing-offers${method==='GET'?'/'+service:''}?${query}`,{method,headers:{origin:o,authorization:`Bearer ${token}`,'content-type':'application/json'},...(method==='POST'?{body:JSON.stringify(value)}:{})})};}
it('strict HTTP owner create/read receipts invoke no generic/financial writer',async()=>{const f=await http();for(const method of ['POST','GET']){const r=await f.request(method);expect(r.status).toBe(200);expect(r.headers.get('cache-control')).toBe('no-store');expect(await r.json()).toEqual({ok:true,data:receipt});}expect(f.create).toHaveBeenCalledWith(actor,tenant,body);expect(f.read).toHaveBeenCalledWith(actor,tenant,service);expect(f.call).not.toHaveBeenCalled();});
it.each(['tenantId=bad',`tenantId=${tenant}&total=1`,`tenantId=${tenant}&tenantId=${tenant}`])('rejects authority query widening',async query=>{const f=await http();expect((await f.request('POST',body,query)).status).toBe(400);expect(f.create).not.toHaveBeenCalled();});
it('fresh owner/exact origin/closed gate remain required',async()=>{const f=await http(false);expect((await f.request()).status).toBe(422);expect((await f.request('POST',body,undefined,'bad-token-123456')).status).toBe(401);expect((await f.request('POST',body,undefined,undefined,'https://foreign.example.test')).status).toBe(403);expect(f.create).not.toHaveBeenCalled();});
it('rejects price/tenant/provider spoofing and malformed writer receipt',async()=>{const f=await http();for(const extra of [{total:1},{tenantId:tenant},{provider:'stripe'},{taxRateBp:825}])expect((await f.request('POST',{...body,...extra})).status).toBe(400);expect(f.create).not.toHaveBeenCalled();server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));const broken=await http(true,{...receipt,service:{...receipt.service,basePrice:1}});expect((await broken.request()).status).toBe(500);});
