import {afterEach,expect,it,vi} from 'vitest';
import type {Server} from 'node:http';
import {createBusinessProfileInitializer} from './existing-business-profile';
import {createFlowHttpServer} from './http';
import {FlowError} from './repository';
const actor='54000000-0000-4000-8000-000000000001',tenant='54000000-0000-4000-8000-000000000002',origin='https://portal.example.test';
const body={businessType:'HOUSEKEEPING' as const,idempotencyKey:'existing-profile-attempt-0001'},profile={schemaVersion:1 as const,tenantId:tenant,businessType:'HOUSEKEEPING' as const,templateVersion:1 as const};
let server:Server|undefined;afterEach(async()=>{server?.closeAllConnections();if(server)await new Promise<void>(r=>server!.close(()=>r()));server=undefined;});
async function http(enabled=true,value:unknown=profile){const initialize=vi.fn(async()=>{if(value instanceof Error)throw value;return value as typeof profile;}),call=vi.fn();server=createFlowHttpServer({repository:{call},businessOnboarding:enabled,businessProfileInitialize:initialize,ownerOrigins:[origin],customerOrigins:[],authenticateOwner:async token=>token==='owner-token-123456'?actor:null});await new Promise<void>(r=>server!.listen(0,'127.0.0.1',r));return{initialize,call,post:(input:unknown=body,query=`tenantId=${tenant}`,token='owner-token-123456',o=origin,method='POST')=>fetch(`http://127.0.0.1:${(server!.address() as {port:number}).port}/api/business-profile/initialize?${query}`,{method,headers:{origin:o,authorization:`Bearer ${token}`,'content-type':'application/json'},...(method==='POST'?{body:JSON.stringify(input)}:{})})};}
it('strict initialization binds exact fresh actor, tenant and operation, returning only existing profile receipt',async()=>{const f=await http(),r=await f.post();expect(r.status).toBe(200);expect(await r.json()).toEqual({ok:true,data:profile});expect(f.initialize).toHaveBeenCalledExactlyOnceWith(actor,tenant,body);expect(f.call).not.toHaveBeenCalled();});
it.each([{actor},{tenantId:tenant},{price:1},{role:'BUSINESS_OWNER'},{name:'Rename'},{provider:'stripe'},{businessType:'simple'},{idempotencyKey:'short'},null,[]])('rejects spoofed or invalid input %j',async extra=>{const f=await http();const value=extra&&typeof extra==='object'&&!Array.isArray(extra)?{...body,...extra}:extra;expect((await f.post(value)).status).toBe(400);expect(f.initialize).not.toHaveBeenCalled();});
it.each(['',`tenantId=${tenant}&tenantId=${tenant}`,`tenantId=${tenant}&actor=${actor}`,'tenantId=invalid'])('rejects missing or widened query %s',async query=>{const f=await http();expect((await f.post(body,query)).status).toBe(400);expect(f.initialize).not.toHaveBeenCalled();});
it('retains closed staging gate, fresh auth, origin and method checks',async()=>{const f=await http(false);expect((await f.post()).status).toBe(422);expect((await f.post(body,undefined,'sb_publishable_public_key')).status).toBe(401);expect((await f.post(body,undefined,undefined,'https://checkout.example.test')).status).toBe(403);expect(f.initialize).not.toHaveBeenCalled();});
it('rejects GET initialization without authorizing writes',async()=>{const f=await http();expect((await f.post(body,undefined,undefined,undefined,'GET')).status).toBe(404);expect(f.initialize).not.toHaveBeenCalled();});
it.each([['FORBIDDEN',403],['CONFLICT',409],['NOT_AVAILABLE',404]] as const)('exposes only safe %s',async(code,status)=>{const f=await http(true,new FlowError(code)),r=await f.post();expect(r.status).toBe(status);expect(await r.json()).toEqual({ok:false,code});});
it.each([{...profile,tenantId:actor},{...profile,businessType:'AUTO_DETAILING'},{...profile,private:'secret'}])('rejects inconsistent HTTP receipt %j',async value=>{const f=await http(true,value);expect((await f.post()).status).toBe(500);});
function db(value:unknown=profile,code?:string){const query=vi.fn(async(sql:string)=>{if(sql.startsWith('select')){if(code)throw Object.assign(Error('private DB detail'),{code});return{rows:[{result:value}]};}return{rows:[]};}),release=vi.fn(),pool={connect:async()=>({query,release})};return{query,release,run:createBusinessProfileInitializer(pool as never)};}
it('fixed parameterized initializer commits only validated binding and releases',async()=>{const f=db();expect(await f.run(actor,tenant,body)).toEqual(profile);expect(f.query).toHaveBeenCalledWith('select public.initialize_staging_business_profile($1::uuid,$2::uuid,$3::text,$4::text) as result',[actor,tenant,body.businessType,body.idempotencyKey]);expect(f.query).toHaveBeenLastCalledWith('commit');expect(f.release).toHaveBeenCalledWith(false);});
it.each([{...profile,tenantId:actor},{...profile,businessType:'AUTO_DETAILING'},{...profile,private:'secret'}])('rolls back inconsistent SQL receipt %j',async value=>{const f=db(value);await expect(f.run(actor,tenant,body)).rejects.toMatchObject({code:'INTERNAL_ERROR'});expect(f.query).toHaveBeenLastCalledWith('rollback');expect(f.query.mock.calls.some(([sql])=>sql==='commit')).toBe(false);});
it.each([['42501','FORBIDDEN'],['40001','CONFLICT'],['55P03','CONFLICT'],['40P01','CONFLICT'],['57014','CONFLICT'],['23505','CONFLICT'],['22023','INVALID_REQUEST'],['XX000','INTERNAL_ERROR']])('sanitizes SQL error %s',async(code,result)=>{const f=db(profile,code);await expect(f.run(actor,tenant,body)).rejects.toMatchObject({code:result,message:result});expect(f.query).toHaveBeenLastCalledWith('rollback');});
