import {afterEach,it,expect,vi} from 'vitest';
import type {Server} from 'node:http';
import {createFlowHttpServer} from './http';
import {createMockPaymentWriter,mockPaymentsEnabled,type MockPaymentWriter} from './mock-payment';
const actor='a5700000-0000-4000-8000-000000000001',tenant='a5700000-0000-4000-8000-000000000002',booking='a5700000-0000-4000-8000-000000000003',payment='a5700000-0000-4000-8000-000000000004',service='a5700000-0000-4000-8000-000000000005';
let server:Server;
afterEach(async()=>{server?.closeAllConnections();if(server)await new Promise<void>(r=>server.close(()=>r()));});
async function setup(mockPayment?:MockPaymentWriter){server=createFlowHttpServer({repository:{call:async()=>{throw Error('unexpected');}},mockPayment,ownerOrigins:['https://portal.example.test'],customerOrigins:[],authenticateOwner:async token=>token==='owner-token-123456'?actor:null});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));return(body:unknown,token='owner-token-123456')=>fetch(`http://127.0.0.1:${(server.address() as {port:number}).port}/api/bookings/mock-payment?tenantId=${tenant}`,{method:'POST',headers:{origin:'https://portal.example.test',authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify(body)});}
it('requires two explicit staging gates and does not connect when disabled',async()=>{expect(mockPaymentsEnabled({})).toBe(false);expect(()=>mockPaymentsEnabled({BOOKING_LUMIN_FAKE_PAYMENTS:'1',BOOKING_LUMIN_ENV:'production'})).toThrow();expect(mockPaymentsEnabled({BOOKING_LUMIN_FAKE_PAYMENTS:'1',BOOKING_LUMIN_ENV:'staging'})).toBe(true);const connect=vi.fn();await expect(createMockPaymentWriter({connect} as never,{})(actor,tenant,booking)).rejects.toMatchObject({code:'UNSUPPORTED_CONFIG'});expect(connect).not.toHaveBeenCalled();});
it('defaults HTTP boundary to unsupported',async()=>{const post=await setup();expect((await post({bookingId:booking})).status).toBe(422);});
it('rejects caller amount/provider/state/tenant before dispatch and authenticates',async()=>{const write=vi.fn<MockPaymentWriter>();const post=await setup(write);for(const extra of [{amount:1},{pricing:{}},{paymentId:payment},{provider:'stripe'},{state:'succeeded'},{tenantId:tenant},{serviceId:booking}])expect((await post({bookingId:booking,...extra})).status).toBe(400);expect((await post({bookingId:booking},'invalid-token-123456')).status).toBe(401);expect(write).not.toHaveBeenCalled();});
it('returns an explicitly simulated receipt with bound identifiers',async()=>{const write=vi.fn<MockPaymentWriter>(async()=>({bookingId:booking,paymentId:payment,state:'confirmed',replayed:false,provider:'staging_mock',simulated:true}));const post=await setup(write);const res=await post({bookingId:booking.toUpperCase()});expect(res.status).toBe(200);expect((await res.json()).data.simulated).toBe(true);expect(write).toHaveBeenCalledWith(actor,tenant,booking);expect((await post({bookingId:payment})).status).toBe(500);});
it('SQL membership denial rolls back before any financial write',async()=>{const query=vi.fn(async()=>({rows:[]}));const release=vi.fn();const writer=createMockPaymentWriter({connect:async()=>({query,release})} as never,{BOOKING_LUMIN_FAKE_PAYMENTS:'1',BOOKING_LUMIN_ENV:'staging'});await expect(writer(actor,tenant,booking)).rejects.toMatchObject({code:'FORBIDDEN'});expect(query.mock.calls).toHaveLength(5);expect(query.mock.calls.at(-1)).toEqual(['rollback']);});
function unsupportedSelectionWriter(selection:unknown,serviceRow?:unknown){const query=vi.fn(async(sql:string)=>{if(sql.startsWith('select t.id'))return{rows:[{id:tenant}]};if(sql.startsWith('select * from public.bookings'))return{rows:[{id:booking,tenant_id:tenant,selection,state:'draft',payment_id:null,pricing:{}}]};if(sql.startsWith('select s.*'))return{rows:serviceRow===undefined?[]:[serviceRow]};return{rows:[]};});const release=vi.fn();return {writer:createMockPaymentWriter({connect:async()=>({query,release})} as never,{BOOKING_LUMIN_FAKE_PAYMENTS:'1',BOOKING_LUMIN_ENV:'staging'}),query};}
it('fails closed before payment for configurable/cart/rental selections',async()=>{for(const selection of [{serviceId:service,answers:{vehicle:{choiceIds:['sedan']}}},{serviceId:service,itemQuantities:{package:1}},{serviceId:service,rentalPeriods:2}]){const h=unsupportedSelectionWriter(selection);await expect(h.writer(actor,tenant,booking)).rejects.toMatchObject({code:'UNSUPPORTED_CONFIG'});expect(h.query.mock.calls.some(([sql])=>String(sql).startsWith('insert into public.payments'))).toBe(false);expect(h.query.mock.calls.some(([sql])=>String(sql).includes('confirm_succeeded_payment'))).toBe(false);expect(h.query.mock.calls.at(-1)).toEqual(['rollback']);}});
it('fails closed for a simple-shaped selection on an unsupported service archetype',async()=>{const h=unsupportedSelectionWriter({serviceId:service});await expect(h.writer(actor,tenant,booking)).rejects.toMatchObject({code:'UNSUPPORTED_CONFIG'});expect(h.query.mock.calls.some(([sql])=>String(sql).startsWith('insert into public.payments'))).toBe(false);expect(h.query.mock.calls.at(-1)).toEqual(['rollback']);});
