/** Independent actual PostgreSQL fixtures; local synthetic authority only. */
import assert from 'node:assert/strict';
import {randomUUID,createHash} from 'node:crypto';
import {Pool,type PoolClient} from 'pg';
import {fixture,publish,install,transaction,profile,key,type Fixture} from './mode-installations-fixtures.js';
export {profile,key,transaction,fixture,publish,install};
export function localPool(){assert.equal(process.env.LOCAL_HARNESS,'1');assert.equal(process.env.FLOW_TEST_DISPOSABLE,'1');assert.equal(process.env.MODE_SESSIONS_TEST_DISPOSABLE,'1');assert.ok(['public','extensions'].includes(process.env.MODE_SESSIONS_CRYPTO_LAYOUT??''));assert.ok(['127.0.0.1','localhost'].includes(process.env.PGHOST??''));assert.ok(['5432','55439'].includes(process.env.PGPORT??''));assert.equal(process.env.PGUSER,'postgres');assert.match(process.env.PGDATABASE??'',/^lumin_mode_session_(?:(?:race|root)_(?:public|extensions)_[a-z0-9_]+|public|extensions)$/);assert.ok(process.env.PGDATABASE!.length<=63);const password=process.env.PGPASSWORD??'';assert.ok(password===''||password==='postgres');for(const name of ['DATABASE_URL','PGHOSTADDR','PGPASSFILE','PGSERVICE','PGSERVICEFILE','PGOPTIONS'])assert.equal(process.env[name]??'','');return new Pool({host:process.env.PGHOST,port:Number(process.env.PGPORT),user:'postgres',database:process.env.PGDATABASE,password:()=>password,ssl:false,pipeline:false,max:8,connectionTimeoutMillis:3000,idleTimeoutMillis:1000,statement_timeout:5000,lock_timeout:5000,idle_in_transaction_session_timeout:1000,application_name:'independent-mode-session'});}
export type Prepared={f:Fixture,published:Record<string,any>,installed:Record<string,any>};
export async function prepared(pool:Pool,mode='iframe',v2=false):Promise<Prepared>{const f=await fixture(pool);if(v2){await transaction(pool,c=>c.query('select public.save_configurable_flow_draft($1,$2,$3,$4,1,$5,$6)',[f.actor,f.tenant,f.flow,f.service,'Configurable',JSON.stringify({authoringVersion:2,config:{key:'request',steps:[{key:'count',questionKey:'count',kind:'question',required:true}]},questionOverrides:{count:{minQty:2,maxQty:4}}})]));}const published=await transaction(pool,c=>publish(c,f,v2?2:1)),installed=await transaction(pool,c=>install(c,f,published.versionId,key(),mode));return {f,published,installed};}
export const hash=()=>createHash('sha256').update('mode-flow-session:v1:'+randomUUID()).digest('hex'); // synthetic test digest, not production entropy proof
export async function rpc(c:Pick<PoolClient,'query'>,name:string,args:unknown[]){assert.ok(['mode_issue_flow_session','mode_submit_flow_request','mode_owner_request_history'].includes(name));return (await c.query(`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) result`,args)).rows[0].result as Record<string,any>;}
export const issueArgs=(p:Prepared,token=hash())=>[p.installed.installationId,token,profile.rendererOrigin,p.installed.mode==='hosted'?null:'https://merchant.example.test',profile.profileVersion,p.published.versionId,p.installed.targetRevision,p.installed.policyRevision];
export const issue=(c:Pick<PoolClient,'query'>,args:unknown[])=>rpc(c,'mode_issue_flow_session',args);
export const requestArgs=(token:string,parent:unknown='https://merchant.example.test',start=new Date(Date.now()+3600000).toISOString(),idempotencyKey=key())=>[token,profile.rendererOrigin,parent,idempotencyKey,JSON.stringify({count:{quantity:2}}),JSON.stringify({name:'Customer',email:'customer@example.test'}),start];
export const submit=(c:Pick<PoolClient,'query'>,args:unknown[])=>rpc(c,'mode_submit_flow_request',args);
export const history=(c:Pick<PoolClient,'query'>,f:Fixture,flow:unknown=f.flow,cursor:Record<string,any>|null=null,limit=100,actor=f.actor)=>rpc(c,'mode_owner_request_history',[actor,f.tenant,flow,cursor?.createdAt??null,cursor?.bookingId??null,limit]);
export async function issued(pool:Pool,p?:Prepared){p??=await prepared(pool);const args=issueArgs(p),session=await transaction(pool,c=>issue(c,args));return {...p,args,session,request:requestArgs(String(args[1]),args[3])};}
export async function snapshot(pool:Pool,tenant:string){const out:Record<string,any>={};for(const table of ['mode_flow_sessions','mode_flow_requests','customers','bookings','durable_outbox','payments','capacity_holds'])out[table]=(await pool.query(`select coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text),'[]') rows from public.${table} t where tenant_id=$1`,[tenant])).rows[0].rows;out.booking_state_history=(await pool.query("select coalesce(jsonb_agg(to_jsonb(h) order by to_jsonb(h)::text),'[]') rows from public.booking_state_history h join public.bookings b on b.id=h.booking_id where b.tenant_id=$1",[tenant])).rows[0].rows;return out;}
export const pause=(ms:number)=>new Promise<void>(resolve=>setTimeout(resolve,ms));
export async function rejected(action:()=>Promise<unknown>,code:string,message?:string){await assert.rejects(action,(error:any)=>{assert.equal(error.code,code);if(message)assert.equal(error.message,message);return true;});}
const observedHolders=new WeakSet<PoolClient>();
export async function holder(pool:Pool){const c=await pool.connect();try{if(!observedHolders.has(c)){c.on('error',()=>{});observedHolders.add(c);}await c.query('begin');await c.query("set local idle_in_transaction_session_timeout='10s'");return c;}catch(error){c.release(true);throw error;}}
export async function expiry(pool:Pool,id:string,seconds=1){console.log('TRUSTED FIXTURE coherent session expiry adjustment');await transaction(pool,async c=>{await c.query('alter table public.mode_flow_sessions disable trigger user');await c.query("with stamp as materialized(select clock_timestamp()+make_interval(secs=>$2) as expires) update public.mode_flow_sessions set issued_at=stamp.expires-interval '15 minutes',expires_at=stamp.expires from stamp where id=$1",[id,seconds]);await c.query('alter table public.mode_flow_sessions enable trigger user');},'owner');}
export async function fault(pool:Pool,table:string,predicate:string){assert.ok(['customers','bookings','booking_state_history','mode_flow_requests','durable_outbox'].includes(table));assert.match(predicate,/^[a-z_.=0-9' :\-]+$/i);const name='s2_fault_'+randomUUID().replaceAll('-','');await pool.query(`create schema ${name}`);await pool.query(`create function ${name}.fail() returns trigger language plpgsql as $$begin if ${predicate} then raise exception 'ACTUAL_S2_LATE_${table.toUpperCase()}' using errcode='P0001';end if;return new;end$$`);await pool.query(`create trigger zz_${name} before insert on public.${table} for each row execute function ${name}.fail()`);return async()=>{await pool.query(`drop trigger zz_${name} on public.${table}`);await pool.query(`drop schema ${name} cascade`);};}
