/** Independent local-only fixtures. No production profile or credential activation. */
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {Client,Pool,type PoolConfig} from 'pg';
export const profile=Object.freeze({profileVersion:'transport-v1',rendererOrigin:'https://renderer.test',apiOrigin:'https://api.test',portalOrigin:'https://portal.test',loaderUrl:'https://renderer.test/assets/booking-lumin-loader.'+'a'.repeat(64)+'.js'});
export function config():PoolConfig{
 assert.equal(process.env.LOCAL_HARNESS,'1');assert.equal(process.env.FLOW_TEST_DISPOSABLE,'1');assert.equal(process.env.MODE_INSTALLATIONS_TEST_DISPOSABLE,'1');
 assert.ok(['127.0.0.1','localhost'].includes(process.env.PGHOST??''));assert.match(process.env.PGPORT??'',/^[1-9][0-9]{0,4}$/);assert.ok(Number(process.env.PGPORT)<=65535);assert.equal(process.env.PGUSER,'postgres');assert.match(process.env.PGDATABASE??'',/^lumin_installation_s1_transport_[a-z0-9_]+$/);assert.ok(process.env.PGDATABASE!.length<=63);
 const password=process.env.PGPASSWORD??'';assert.ok(password===''||password==='postgres');for(const key of ['DATABASE_URL','PGHOSTADDR','PGSERVICE','PGSERVICEFILE','PGPASSFILE','PGOPTIONS'])assert.equal(process.env[key]??'','');
 return {host:process.env.PGHOST,port:Number(process.env.PGPORT),user:'postgres',database:process.env.PGDATABASE,password:()=>password,ssl:false,pipeline:false,max:2,connectionTimeoutMillis:3000,idleTimeoutMillis:5000,statement_timeout:5000,lock_timeout:5000,idle_in_transaction_session_timeout:1000,query_timeout:0,application_name:'mode-transport-independent'};
}
export const pool=()=>new Pool(config());
export const pause=(ms:number)=>new Promise<void>(resolve=>setTimeout(resolve,ms));
export async function observe(check:()=>Promise<boolean>,label:string,ms=8000){const end=performance.now()+ms;do{if(await check())return;await pause(20);}while(performance.now()<end);throw Error('Observation failed: '+label);}
export function pid(client:Client){const value=(client as unknown as {processID:unknown}).processID;assert.ok(Number.isInteger(value)&&Number(value)>0);return Number(value);}
export async function observer(){const c=new Client({...config(),statement_timeout:3000,idle_in_transaction_session_timeout:0});c.on('error',()=>{});await c.connect();const layout=process.env.MODE_INSTALLATIONS_CRYPTO_LAYOUT;assert.ok(layout==='public'||layout==='extensions');assert.equal((await c.query('select n.nspname from pg_extension e join pg_namespace n on n.oid=e.extnamespace where e.extname=$1',['pgcrypto'])).rows[0].nspname,layout);assert.ok((await c.query("select to_regprocedure('public.mode_owner_operation(uuid,uuid,uuid,text,text)') is not null ok")).rows[0].ok);
 await c.query('insert into lumin.installation_profiles(version,renderer_origin,api_origin,portal_origin,loader_sha256) values($1,$2,$3,$4,$5) on conflict do nothing',[profile.profileVersion,profile.rendererOrigin,profile.apiOrigin,profile.portalOrigin,'a'.repeat(64)]);
 const actual=(await c.query('select version,renderer_origin,api_origin,portal_origin,loader_sha256 from lumin.installation_profiles where version=$1',[profile.profileVersion])).rows[0];assert.deepEqual(actual,{version:profile.profileVersion,renderer_origin:profile.rendererOrigin,api_origin:profile.apiOrigin,portal_origin:profile.portalOrigin,loader_sha256:'a'.repeat(64)});return c;}
export type Fixture={actor:string,other:string,tenant:string,service:string,flow:string};
const cfg={key:'transport',steps:[{key:'count',questionKey:'count',kind:'question',required:true}]};
export async function seed(c:Client,v2=false):Promise<Fixture>{const f={actor:randomUUID(),other:randomUUID(),tenant:randomUUID(),service:randomUUID(),flow:randomUUID()};await c.query('begin');try{
 await c.query('insert into auth.users(id,email) values($1,$2),($3,$4)',[f.actor,f.actor+'@example.test',f.other,f.other+'@example.test']);await c.query("insert into public.tenants(id,name,slug,timezone,currency) values($1,'Transport fixture',$2,'UTC','USD')",[f.tenant,f.tenant]);await c.query("insert into public.tenant_members(tenant_id,user_id,role) values($1,$2,'BUSINESS_OWNER'),($1,$3,'BUSINESS_OWNER')",[f.tenant,f.actor,f.other]);await c.query("insert into public.services(id,tenant_id,archetype,name,currency,base_price) values($1,$2,'simple','Transport service','USD',0)",[f.service,f.tenant]);await c.query("insert into public.service_questions(tenant_id,service_id,question_key,prompt,kind,required,unit_price,min_qty,max_qty,choices) values($1,$2,'count','How many?','quantity',true,0,1,5,'[]')",[f.tenant,f.service]);
 if(v2)await c.query('select public.save_configurable_flow_draft($1,$2,$3,$4,0,$5,$6)',[f.actor,f.tenant,f.flow,f.service,'V2 transport',JSON.stringify({authoringVersion:2,config:cfg,questionOverrides:{}})]);else await c.query('select public.save_bound_flow_draft($1,$2,$3,$4,0,$5,$6)',[f.actor,f.tenant,f.flow,f.service,'V1 transport',JSON.stringify(cfg)]);
 await c.query('commit');return f;}catch(error){await c.query('rollback');throw error;}}
export const actor=(f:Fixture)=>({mode:'local_synthetic' as const,userId:f.actor});
export const scope=(f:Fixture)=>({tenantId:f.tenant,flowId:f.flow});
export const publish=(f:Fixture,key='transport_publish_01')=>({...scope(f),expectedDraftRevision:1,idempotencyKey:key});
export const recovery=(f:Fixture,operation:'publish'|'install'|'apply'|'policy',key='transport_publish_01')=>({...scope(f),operation,idempotencyKey:key});
export const install=(f:Fixture,versionId:string,key='transport_install_01')=>({...scope(f),versionId,expectedPublishedVersionId:versionId,mode:'iframe',deploymentProfileVersion:profile.profileVersion,allowedParentOrigins:['https://merchant.test'],idempotencyKey:key});
export async function state(c:Client,f:Fixture){return (await c.query(`select jsonb_build_object(
 'flows',(select coalesce(jsonb_agg(to_jsonb(x) order by id),'[]') from public.flows x where tenant_id=$1),
 'drafts',(select coalesce(jsonb_agg(to_jsonb(x) order by flow_id),'[]') from public.flow_drafts x where tenant_id=$1),
 'versions',(select coalesce(jsonb_agg(to_jsonb(x) order by id),'[]') from public.flow_versions x where tenant_id=$1),
 'bound',(select coalesce(jsonb_agg(to_jsonb(x) order by version_id),'[]') from public.bound_flow_versions x where tenant_id=$1),
 'installations',(select coalesce(jsonb_agg(to_jsonb(x) order by id),'[]') from public.mode_flow_installations x where tenant_id=$1),
 'history',(select coalesce(jsonb_agg(to_jsonb(x) order by installation_id,sequence),'[]') from public.mode_flow_installation_history x where tenant_id=$1),
 'operations',(select coalesce(jsonb_agg(to_jsonb(x) order by actor_id,flow_id,operation,idempotency_key),'[]') from public.mode_flow_owner_operations x where tenant_id=$1),
 'legacyInstall',(select count(*) from public.flow_installations where tenant_id=$1),
 'sessions',(select count(*) from public.flow_sessions where tenant_id=$1),'requests',(select count(*) from public.flow_requests where tenant_id=$1),
 'bookings',(select count(*) from public.bookings where tenant_id=$1),'payments',(select count(*) from public.payments where tenant_id=$1),
 'holds',(select count(*) from public.capacity_holds where tenant_id=$1),'outbox',(select count(*) from public.durable_outbox where tenant_id=$1)) value`,[f.tenant])).rows[0].value;}
export async function blocker(){const c=new Client({...config(),statement_timeout:15000,lock_timeout:15000,idle_in_transaction_session_timeout:0});c.on('error',()=>{});await c.connect();await c.query('begin');return c;}
export async function blocked(c:Client,target:number,holder:number){await observe(async()=>(await c.query("select exists(select 1 from pg_stat_activity where pid=$1 and wait_event_type='Lock' and $2=any(pg_blocking_pids(pid))) ok",[target,holder])).rows[0].ok,'actual blocked PID');console.log('OBSERVED waiting backend '+target+' on '+holder);}
export async function gone(c:Client,target:number){await observe(async()=>!(await c.query('select exists(select 1 from pg_stat_activity where pid=$1) ok',[target])).rows[0].ok,'eventual backend disappearance',9000);}
export async function commitFixture(c:Client){const name='mode_transport_commit_'+randomUUID().replaceAll('-','');const parent=randomUUID();await c.query(`create schema ${name}`);await c.query(`create table ${name}.parent(id uuid primary key)`);await c.query(`create table ${name}.child(id uuid,constraint commit_fk foreign key(id) references ${name}.parent(id) deferrable initially deferred)`);await c.query(`insert into ${name}.parent values($1)`,[parent]);return {parent,defer:`set constraints ${name}.commit_fk deferred`,insert:`insert into ${name}.child values($1)`,lock:`select id from ${name}.parent where id=$1 for update`,cleanup:()=>c.query(`drop schema ${name} cascade`)};}
export async function lateFault(c:Client,key:string){assert.match(key,/^[A-Za-z0-9_-]{16,128}$/);const name='mode_transport_fault_'+randomUUID().replaceAll('-','');await c.query(`create schema ${name}`);await c.query(`create function ${name}.fail() returns trigger language plpgsql as $$begin if new.idempotency_key='${key}' then raise exception 'ACTUAL_TRANSPORT_LATE_FAULT' using errcode='22023';end if;return new;end$$`);await c.query(`create trigger zz_${name} before insert on public.mode_flow_owner_operations for each row execute function ${name}.fail()`);return async()=>{await c.query(`drop trigger zz_${name} on public.mode_flow_owner_operations`);await c.query(`drop schema ${name} cascade`);};}
export async function lateHistoryFault(c:Client,flow:string){assert.match(flow,/^[0-9a-f-]{36}$/);const name='mode_transport_history_'+randomUUID().replaceAll('-','');await c.query(`create schema ${name}`);await c.query(`create function ${name}.fail() returns trigger language plpgsql as $$begin if new.flow_id='${flow}'::uuid then raise exception 'ACTUAL_TRANSPORT_HISTORY_FAULT' using errcode='22023';end if;return new;end$$`);await c.query(`create trigger zz_${name} before insert on public.mode_flow_installation_history for each row execute function ${name}.fail()`);return async()=>{await c.query(`drop trigger zz_${name} on public.mode_flow_installation_history`);await c.query(`drop schema ${name} cascade`);};}
