import {expect,it,vi} from 'vitest';
import {NotificationConfig} from '@lumin/contracts';
import {FlowError} from './repository';
import {createNotificationPlannerConfigApi,StrictNotificationPlannerConfig,type SaveNotificationPlannerConfig} from './notification-planner-config';
const actor='65000000-0000-4000-8000-000000000001',tenant='65000000-0000-4000-8000-000000000002',foreign='65000000-0000-4000-8000-000000000003';
const config={tenantId:tenant,locale:'en-US',timezone:'UTC',sender:{emailFrom:'owner@example.test',emailFromName:'Owner',smsFrom:'+12065550123'},events:[{event:'booking.confirmed' as const,channels:['email' as const]}],reminders:[{id:'day-before',offsetMinutes:1440,channels:['sms' as const]}],templates:[{trigger:'booking.confirmed' as const,channel:'email' as const,locale:'en-US',subject:'Booking {{bookingReference}}',body:'Hello {{customerName}}: {{slotStart}}'},{trigger:'reminder' as const,channel:'sms' as const,locale:'en-US',body:'Reminder {{bookingReference}}'}]};
const body:SaveNotificationPlannerConfig={expectedRevision:0,config},receipt={schemaVersion:1,tenantId:tenant,revision:1,config};
function fixture(value:unknown=receipt,error?:unknown){const release=vi.fn(),query=vi.fn(async(sql:string,..._args:unknown[])=>{if(sql.startsWith('select')){if(error)throw error;return {rows:[{result:value}]};}return {rows:[]};}),connect=vi.fn(async()=>({query,release}));return{query,release,connect,api:createNotificationPlannerConfigApi({connect} as never)};}
it('saves only through a fixed service-role RPC with canonical actor/tenant and exact CAS config',async()=>{const x=fixture();expect(await x.api.save(actor.toUpperCase(),tenant.toUpperCase(),body)).toEqual(receipt);expect(x.query).toHaveBeenCalledWith('select public.save_notification_planner_config($1::uuid,$2::uuid,$3::bigint,$4::jsonb) as result',[actor,tenant,0,JSON.stringify(config)]);expect(x.query).toHaveBeenCalledWith('set local role service_role');expect(x.query).toHaveBeenLastCalledWith('commit');expect(x.release).toHaveBeenCalledWith(false);expect(NotificationConfig.safeParse(receipt.config).success).toBe(true);});
it('read returns only the saved strict receipt or null missing, never defaults/provider sample',async()=>{const x=fixture(null);expect(await x.api.read(actor,tenant)).toBeNull();expect(x.query).toHaveBeenCalledWith('select public.owner_notification_planner_config($1::uuid,$2::uuid) as result',[actor,tenant]);expect(x.query).toHaveBeenLastCalledWith('commit');});
it.each([undefined,null,{...body,actorId:actor},{...body,role:'BUSINESS_OWNER'},{...body,expectedRevision:-1},{...body,expectedRevision:Number.MAX_SAFE_INTEGER},{...body,config:{...config,tenantId:foreign}},{...body,config:{...config,apiKey:'secret'}},{...body,config:{...config,sender:{...config.sender,password:'secret'}}},{...body,config:{...config,events:[{...config.events[0],enabled:true}]}}])('rejects widened or invalid input before pool access',async(input)=>{const x=fixture();await expect(x.api.save(actor,tenant,input)).rejects.toMatchObject({code:'INVALID_REQUEST'});expect(x.connect).not.toHaveBeenCalled();});
it.each(['event','reminder','template','channel','variable','control','locale','timezone','missing','sms-subject','overflow'] as const)('strict planner rejects %s configuration',change=>{const value=structuredClone(config) as any;if(change==='event')value.events.push(value.events[0]);if(change==='reminder')value.reminders.push(value.reminders[0]);if(change==='template')value.templates.push(value.templates[0]);if(change==='channel')value.events[0].channels.push('email');if(change==='variable')value.templates[0].body='{{apiKey}}';if(change==='control')value.templates[0].body='body'+String.fromCharCode(1);if(change==='locale')value.templates[0].locale='es-MX';if(change==='timezone')value.timezone='Invalid/Zone';if(change==='missing')value.templates=[];if(change==='sms-subject')value.templates[1].subject='No';if(change==='overflow')value.templates[0].body='x'.repeat(4001);expect(StrictNotificationPlannerConfig.safeParse(value).success).toBe(false);});
it('plain multiline body and valid astral Unicode are preserved, while malformed Unicode/control/header breaks are rejected',()=>{const value={...config,templates:[{...config.templates[0]!,body:'Hello 😀\n{{customerName}}'},config.templates[1]!]};expect(StrictNotificationPlannerConfig.parse(value).templates[0]!.body).toBe(value.templates[0]!.body);expect(StrictNotificationPlannerConfig.safeParse({...value,sender:{emailFromName:'bad\nheader'}}).success).toBe(false);expect(StrictNotificationPlannerConfig.safeParse({...value,templates:[{...value.templates[0],body:String.fromCharCode(0xd800)},value.templates[1]]}).success).toBe(false);});
it.each([{...receipt,tenantId:foreign},{...receipt,revision:2},{...receipt,providerStatus:'connected'},{...receipt,config:{...config,sender:{token:'secret'}}}])('rolls back malformed or mismatched saved receipt before commit',async(value)=>{const x=fixture(value);await expect(x.api.save(actor,tenant,body)).rejects.toMatchObject({code:'INTERNAL_ERROR'});expect(x.query).toHaveBeenLastCalledWith('rollback');expect(x.query).not.toHaveBeenCalledWith('commit');});
it('refuses a mismatched frozen config even when the revision is plausible',async()=>{const x=fixture({...receipt,config:{...config,locale:'es-MX',templates:config.templates.map(row=>({...row,locale:'es-MX'}))}});await expect(x.api.save(actor,tenant,body)).rejects.toMatchObject({code:'INTERNAL_ERROR'});});
it.each([['42501','FORBIDDEN'],['22023','INVALID_REQUEST'],['P0002','NOT_AVAILABLE'],['40001','CONFLICT'],['55P03','CONFLICT'],['XX000','INTERNAL_ERROR']] as const)('sanitizes SQL %s and never auto-retries CAS',async(code,expected)=>{const x=fixture(undefined,{code,message:'PRIVATE_PROVIDER_SECRET'});await expect(x.api.save(actor,tenant,body)).rejects.toEqual(new FlowError(expected));expect(x.query.mock.calls.filter(([sql])=>sql.startsWith('select'))).toHaveLength(1);expect(x.query).toHaveBeenLastCalledWith('rollback');});
it('invalid actor or tenant fails before any pool call',async()=>{const x=fixture();await expect(x.api.read('forged',tenant)).rejects.toMatchObject({code:'INVALID_REQUEST'});await expect(x.api.read(actor,'forged')).rejects.toMatchObject({code:'INVALID_REQUEST'});expect(x.connect).not.toHaveBeenCalled();});

it('sanitizes pool connection failure before any receipt or provider data can escape',async()=>{const connect=vi.fn(async()=>{throw Error('PRIVATE_CONNECTION_SECRET');}),api=createNotificationPlannerConfigApi({connect} as never);await expect(api.read(actor,tenant)).rejects.toEqual(new FlowError('INTERNAL_ERROR'));await expect(api.save(actor,tenant,body)).rejects.toEqual(new FlowError('INTERNAL_ERROR'));});

it.each(['a..b@example.com','a@b.c','.a@example.com','a.@example.com','a@-example.com','a@example.123'])('rejects sender email %s before any database access',async(emailFrom)=>{const x=fixture();await expect(x.api.save(actor,tenant,{...body,config:{...config,sender:{emailFrom}}})).rejects.toMatchObject({code:'INVALID_REQUEST'});expect(x.connect).not.toHaveBeenCalled();});
it.each(['a@example.com',"owner+tag.o'neil@sub.example.test",'OWNER@EXAMPLE.COM'])('accepts bounded sender email %s with database-compatible grammar',emailFrom=>{expect(StrictNotificationPlannerConfig.safeParse({...config,sender:{emailFrom}}).success).toBe(true);});
