import assert from 'node:assert/strict';
import {Pool} from 'pg';
import {createFlowHttpServer} from './http';
import {createFlowRepository} from './repository';
import {createBusinessApi} from './business';
import {createSimpleOfferCreator} from './owner-catalog';
import {createOfferSchedulingCreator} from './owner-scheduling';
import {createCustomerAvailabilityReader} from './customer-availability';
import {createCustomerHoldWriter} from './customer-hold';
import {createCustomerMockPayment} from './customer-payment';
assert.equal(process.env.SCHEDULING_LOCAL_TEST,'1');if(process.env.CI==='true'){assert.ok(['localhost','127.0.0.1'].includes(process.env.PGHOST??''));assert.equal(process.env.PGPORT,'5432');}else{assert.equal(process.env.PGHOST,'127.0.0.1');assert.equal(process.env.PGPORT,'55436');}assert.match(process.env.PGDATABASE??'',/^lumin_phase_a_scheduling_/);for(const key of ['DATABASE_URL','PGHOSTADDR','PGSERVICE','PGSERVICEFILE','PGOPTIONS'])assert.ok(!process.env[key]);
const pool=new Pool({max:10}),failureCodes:string[]=[];const trackedPool={connect:async()=>{const c=await pool.connect();return{query:async(sql:string,params?:unknown[])=>{try{return await c.query(sql,params);}catch(error){if(sql.includes('create_housekeeping_offer_scheduling'))failureCodes.push((error as {code?:string}).code??'unknown');throw error;}},release:(broken?:boolean)=>c.release(broken)};}};
const id=(n:number)=>`47000000-0000-4000-8000-${String(n).padStart(12,'0')}`,actor=id(1),foreign=id(9),origin='https://portal.example.test',customerOrigin='https://checkout.example.test',business=createBusinessApi(pool),server=createFlowHttpServer({repository:createFlowRepository(pool),businessOnboarding:true,businessCreate:business.create,catalogAuthoring:true,simpleOfferCreate:createSimpleOfferCreator(pool),schedulingAuthoring:true,offerSchedulingCreate:createOfferSchedulingCreator(trackedPool as never),paidSimplePublication:true,customerAvailability:createCustomerAvailabilityReader(pool),customerHold:createCustomerHoldWriter(pool),customerMockPayment:createCustomerMockPayment(pool,{BOOKING_LUMIN_ENV:'staging',BOOKING_LUMIN_FAKE_PAYMENTS:'1'}),ownerOrigins:[origin],customerOrigins:[customerOrigin],authenticateOwner:async token=>token==='owner-token-123456'?actor:token==='foreign-token-123456'?foreign:null});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
async function post(path:string,body:unknown,token='owner-token-123456',o=origin){const r=await fetch(base+path,{method:'POST',headers:{origin:o,authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify(body)});return{status:r.status,json:await r.json()};}
const body={timezone:'UTC',windows:Array.from({length:7},(_,weekday)=>({weekday,startMinute:540,endMinute:1020,capacity:1})),policy:{leadTimeMinutes:0,horizonDays:30,slotIntervalMinutes:30},idempotencyKey:'scheduling-attempt-0001'};
let tenant:string,service:string;const setup=(b:unknown=body,s=service,t=tenant,token?:string)=>post(`/api/catalog/simple-offers/${s}/scheduling?tenantId=${t}`,b,token);
const offer=(n:number)=>post('/api/catalog/simple-offers?tenantId='+tenant,{name:'Cleaning '+n,description:'',price:{amount:12500,currency:'USD'},durationMinutes:60,idempotencyKey:'scheduling-offer-attempt-000'+n});
try{
 await pool.query("insert into auth.users(id,email) values($1,'scheduling-owner-http@example.test'),($2,'scheduling-foreign-http@example.test')",[actor,foreign]);
 const biz=await post('/api/businesses',{name:'Housekeeping',slug:'scheduling-hk-http',timezone:'UTC',currency:'USD',businessType:'HOUSEKEEPING',idempotencyKey:'scheduling-business-attempt-0001'});assert.equal(biz.status,200);tenant=biz.json.data.tenantId;const created=await offer(1);assert.equal(created.status,200);service=created.json.data.service.id;
 assert.equal((await setup(body,service,tenant,'foreign-token-123456')).status,403);assert.equal((await setup(body,service,tenant,'forged-token-123456')).status,401);for(const extra of [{timezone:'Europe/Paris'},{price:12500},{tenantId:tenant},{serviceId:service},{windows:[{weekday:1,startMinute:540,endMinute:1020,capacity:2}]},{windows:[{weekday:1,startMinute:540,endMinute:550,capacity:1}]},{policy:{...body.policy,horizonDays:31}}])assert.equal((await setup({...body,...extra})).status,400);
 const auto=await post('/api/businesses',{name:'Auto',slug:'scheduling-auto-http',timezone:'UTC',currency:'USD',businessType:'AUTO_DETAILING',idempotencyKey:'scheduling-business-attempt-0002'});assert.equal((await setup(body,service,auto.json.data.tenantId)).status,403);
 // An in-flight setup fences a competing alias rule via tenant FK KEY SHARE.
 const guard=await pool.connect(),alias=await pool.connect();try{await guard.query('begin');await guard.query('set local role service_role');await guard.query('select public.create_housekeeping_offer_scheduling($1,$2,$3,$4,$5::jsonb,$6,$7,$8,$9)',[actor,tenant,service,'UTC',JSON.stringify(body.windows),0,30,30,body.idempotencyKey]);await alias.query('begin');await alias.query("set local lock_timeout='100ms'");await assert.rejects(alias.query('insert into public.availability_rules(tenant_id,service_id,weekday,start_minute,end_minute,capacity) values($1,$2,0,0,1440,2)',[tenant,service]),(e:unknown)=>(e as {code?:string}).code==='55P03');}finally{await alias.query('rollback');await guard.query('rollback');alias.release();guard.release();}
 failureCodes.length=0;const race=await Promise.all([setup(),setup()]);assert.ok(race.some(r=>r.status===200));assert.ok(race.every(r=>r.status===200||r.status===409));assert.ok(failureCodes.every(code=>['55P03','57014','40P01'].includes(code)),JSON.stringify(failureCodes));console.log('PASS scheduling same-key statuses '+JSON.stringify(race.map(r=>r.status))+' sanitized SQLSTATEs '+JSON.stringify(failureCodes));const settled=await setup();assert.equal(settled.status,200);for(const r of race.filter(r=>r.status===200))assert.deepEqual(r,settled);const receipt=settled.json.data;assert.equal(receipt.serviceId,service);assert.equal(receipt.tenantId,tenant);assert.equal(receipt.windows.length,7);assert.equal(Number((await pool.query('select count(*) n from public.availability_rules where service_id=$1',[service])).rows[0].n),7);assert.equal((await setup({...body,idempotencyKey:'scheduling-attempt-0002'})).status,409);
 // Force the bounded tenant lock timeout, then explicitly reconcile by same-body replay.
 const deadline=await pool.connect();try{await deadline.query('begin');await deadline.query('select id from public.tenants where id=$1 for update',[tenant]);failureCodes.length=0;assert.equal((await setup()).status,409);assert.deepEqual(failureCodes,['55P03']);}finally{await deadline.query('rollback');deadline.release();}assert.deepEqual(await setup(),settled);console.log('PASS sanitized scheduling lock deadline SQLSTATE55P03; exact subsequent replay, no new configuration');
 const second=(await offer(2)).json.data.service.id,distinct=await Promise.all([setup({...body,idempotencyKey:'scheduling-distinct-0001'},second),setup({...body,idempotencyKey:'scheduling-distinct-0002'},second)]);assert.deepEqual(distinct.map(r=>r.status).sort(),[200,409]);assert.equal(Number((await pool.query('select count(*) n from public.scheduling_policies where service_id=$1',[second])).rows[0].n),1);
 await pool.query('update public.availability_rules set capacity=2 where id=$1',[receipt.windows[0].id]);assert.equal((await setup()).status,409);await pool.query('update public.availability_rules set capacity=1 where id=$1',[receipt.windows[0].id]);
 await pool.query("update public.tenant_members set role='BUSINESS_STAFF' where tenant_id=$1 and user_id=$2",[tenant,actor]);assert.equal((await setup()).status,403);await pool.query("update public.tenant_members set role='BUSINESS_OWNER' where tenant_id=$1 and user_id=$2",[tenant,actor]);await pool.query("update public.tenants set status='inactive' where id=$1",[tenant]);assert.equal((await setup()).status,403);await pool.query("update public.tenants set status='active' where id=$1",[tenant]);await pool.query('delete from public.tenant_members where tenant_id=$1 and user_id=$2',[tenant,actor]);assert.equal((await setup()).status,403);await pool.query("insert into public.tenant_members(tenant_id,user_id,role) values($1,$2,'BUSINESS_OWNER'),($1,$3,'BUSINESS_OWNER')",[tenant,actor,foreign]);assert.equal((await setup(body,service,tenant,'foreign-token-123456')).status,403);
 for(const table of ['flow_versions','flow_installations','flow_sessions','bookings','payments','capacity_holds'])assert.equal(Number((await pool.query(`select count(*) n from public.${table}`)).rows[0].n),0);
 const flow=id(20);assert.equal((await post(`/api/paid-simple-flows/${flow}/draft?tenantId=${tenant}`,{expectedRevision:0,serviceId:service,name:'Scheduled cleaning',presentation:{accentColor:'#4f46e5',layout:'stacked'}})).status,200);const published=await post(`/api/paid-simple-flows/${flow}/publish-draft?tenantId=${tenant}`,{expectedDraftRevision:1,allowedOrigins:[customerOrigin]});assert.equal(published.status,200);const installation=published.json.data.publication.installationId,sessions=await Promise.all([post('/api/installations/'+installation+'/sessions',{},undefined,customerOrigin),post('/api/installations/'+installation+'/sessions',{},undefined,customerOrigin)]);for(const session of sessions)assert.equal(session.status,200);
 const tomorrow=new Date(Date.now()+86400000);tomorrow.setUTCHours(0,0,0,0);const from=tomorrow.toISOString(),to=new Date(+tomorrow+86400000).toISOString();async function availability(token:string){const r=await fetch(base+'/api/flow-sessions/availability?from='+encodeURIComponent(from)+'&to='+encodeURIComponent(to),{headers:{origin:customerOrigin,authorization:`Bearer ${token}`}});assert.equal(r.status,200);return(await r.json()).data.slots as {start:string;end:string}[];}
 const slots=await availability(sessions[0]!.json.data.sessionToken);assert.ok(slots.length>0);assert.ok(slots.every(s=>new Date(s.start).getUTCHours()>=9&&new Date(s.end).getUTCHours()<=17));const start=slots.find(s=>s.start.includes('T10:00:00'))!.start;
 for(let n=0;n<2;n++){const token=sessions[n]!.json.data.sessionToken;assert.equal((await post('/api/flow-sessions/request',{idempotencyKey:'scheduling-request-000'+n,answers:{},customer:{name:'Customer',email:'scheduling-'+n+'@example.test'},requestedStart:start},token,customerOrigin)).status,200);}
 const holds=await Promise.all(sessions.map(s=>post('/api/flow-sessions/hold',{},s.json.data.sessionToken,customerOrigin)));assert.deepEqual(holds.map(h=>h.status).sort(),[200,409]);const winner=holds.findIndex(h=>h.status===200),token=sessions[winner]!.json.data.sessionToken;assert.ok(!(await availability(token)).some(s=>s.start===start));const paid=await post('/api/flow-sessions/mock-payment',{},token,customerOrigin);assert.equal(paid.status,200,JSON.stringify(paid));assert.equal(paid.json.data.state,'confirmed');assert.equal((await pool.query('select amount::int from public.payments where booking_id=$1',[holds[winner]!.json.data.bookingId])).rows[0].amount,12500);assert.equal((await pool.query('select status from public.capacity_holds where booking_id=$1',[holds[winner]!.json.data.bookingId])).rows[0].status,'consumed');assert.deepEqual(await setup(),settled);assert.equal(Number((await pool.query('select count(*) n from public.payments')).rows[0].n),1);
 console.log('PASS actual HTTP owner business/offer/explicit scheduling: exact concurrent replay, different-key one200/one409, tenant FK alias fence, owner/profile/timezone/capacity/drift denials, zero setup financial writes -> existing published public availability with local9-17 -> capacity1 hold race one winner -> staging12500 confirmed consumed -> immutable setup replay after booking');
}finally{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));await pool.end();}
