import assert from 'node:assert/strict';
import {Pool} from 'pg';
import {createFlowHttpServer} from './http';
import {createFlowRepository} from './repository';
import {createBusinessApi} from './business';
import {createSimpleOfferCreator} from './owner-catalog';
import {createCustomerHoldWriter} from './customer-hold';
import {createCustomerMockPayment} from './customer-payment';
assert.equal(process.env.CATALOG_LOCAL_TEST,'1');if(process.env.CI==='true'){assert.ok(['localhost','127.0.0.1'].includes(process.env.PGHOST??''));assert.equal(process.env.PGPORT,'5432');}else{assert.equal(process.env.PGHOST,'127.0.0.1');assert.equal(process.env.PGPORT,'55436');}assert.match(process.env.PGDATABASE??'',/^lumin_phase_a_catalog_/);for(const key of ['DATABASE_URL','PGHOSTADDR','PGSERVICE','PGSERVICEFILE','PGOPTIONS'])assert.ok(!process.env[key]);
const pool=new Pool({max:8}),id=(n:number)=>`46000000-0000-4000-8000-${String(n).padStart(12,'0')}`,actor=id(1),foreign=id(9),origin='https://portal.example.test',customerOrigin='https://checkout.example.test',business=createBusinessApi(pool),server=createFlowHttpServer({repository:createFlowRepository(pool),businessOnboarding:true,businessCreate:business.create,businessProfile:business.read,catalogAuthoring:true,simpleOfferCreate:createSimpleOfferCreator(pool),paidSimplePublication:true,customerHold:createCustomerHoldWriter(pool),customerMockPayment:createCustomerMockPayment(pool,{BOOKING_LUMIN_ENV:'staging',BOOKING_LUMIN_FAKE_PAYMENTS:'1'}),ownerOrigins:[origin],customerOrigins:[customerOrigin],authenticateOwner:async token=>token==='owner-token-123456'?actor:token==='foreign-token-123456'?foreign:null});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
async function post(path:string,body:unknown,token='owner-token-123456',o=origin){const r=await fetch(base+path,{method:'POST',headers:{origin:o,authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify(body)});return{status:r.status,json:await r.json()};}
const body={name:'Home cleaning',description:'Owner-authored fixed visit',price:{amount:12500,currency:'USD'},durationMinutes:60,idempotencyKey:'catalog-offer-attempt-0001'};
let tenant:string;const offer=(b:unknown=body,t=tenant,token?:string)=>post('/api/catalog/simple-offers?tenantId='+t,b,token);
async function serviceCounts(){return(await pool.query('select (select count(*) from public.services)::int services,(select count(*) from public.owner_catalog_creations)::int creations')).rows[0];}
try{
 await pool.query("insert into auth.users(id,email) values($1,'catalog-owner-http@example.test'),($2,'catalog-foreign-http@example.test')",[actor,foreign]);
 const created=await post('/api/businesses',{name:'Owner business',slug:'catalog-hk-http',timezone:'UTC',currency:'USD',businessType:'HOUSEKEEPING',idempotencyKey:'catalog-business-attempt-0001'});assert.equal(created.status,200);tenant=created.json.data.tenantId;
 const auto=await post('/api/businesses',{name:'Auto business',slug:'catalog-auto-http',timezone:'UTC',currency:'USD',businessType:'AUTO_DETAILING',idempotencyKey:'catalog-business-attempt-0002'});assert.equal((await offer(body,auto.json.data.tenantId)).status,403);
 await pool.query("insert into public.tenants(id,name,slug,timezone,currency) values($1,'Uninitialized','catalog-uninitialized-http','UTC','USD')",[id(10)]);await pool.query("insert into public.tenant_members(tenant_id,user_id,role) values($1,$2,'BUSINESS_OWNER')",[id(10),actor]);assert.equal((await offer(body,id(10))).status,404);
 assert.equal((await offer(body,tenant,'foreign-token-123456')).status,403);assert.equal((await offer(body,tenant,'forged-token-123456')).status,401);for(const extra of [{actor:foreign},{tenantId:id(10)},{serviceId:id(3)},{archetype:'simple'},{taxRateBp:0},{provider:'stripe'}])assert.equal((await offer({...body,...extra})).status,400);
 for(const amount of [-1,0,1.5,Number.MAX_SAFE_INTEGER+1])assert.equal((await offer({...body,price:{amount,currency:'USD'}})).status,400);assert.equal((await offer({...body,price:{amount:12500,currency:'EUR'}})).status,400);assert.deepEqual(await serviceCounts(),{services:0,creations:0});
 const concurrent=await Promise.all([offer(),offer()]);assert.deepEqual(concurrent.map(r=>r.status),[200,200]);assert.deepEqual(concurrent[0],concurrent[1]);const receipt=concurrent[0].json.data,service=receipt.service.id;assert.deepEqual(receipt,{schemaVersion:1,tenantId:tenant,service:{id:service,name:body.name,description:body.description,archetype:'simple',price:body.price,durationMinutes:60}});assert.deepEqual(await serviceCounts(),{services:1,creations:1});assert.equal((await offer({...body,price:{amount:13000,currency:'USD'}})).status,409);assert.equal((await offer({...body,name:'Changed name'})).status,409);
 const independent=await Promise.all([offer({...body,name:'Second visit',idempotencyKey:'catalog-offer-attempt-0002'}),offer({...body,name:'Third visit',idempotencyKey:'catalog-offer-attempt-0003'})]);assert.deepEqual(independent.map(r=>r.status),[200,200]);assert.notEqual(independent[0].json.data.service.id,independent[1].json.data.service.id);assert.deepEqual(await serviceCounts(),{services:3,creations:3});
 await pool.query('update public.services set base_price=13000 where id=$1',[service]);assert.equal((await offer()).status,409);await pool.query('update public.services set base_price=12500 where id=$1',[service]);await pool.query('update public.services set description=$2 where id=$1',[service,'Changed']);assert.equal((await offer()).status,409);await pool.query('update public.services set description=$2 where id=$1',[service,body.description]);
 await pool.query("update public.tenant_members set role='BUSINESS_STAFF' where tenant_id=$1 and user_id=$2",[tenant,actor]);assert.equal((await offer()).status,403);await pool.query("update public.tenant_members set role='BUSINESS_OWNER' where tenant_id=$1 and user_id=$2",[tenant,actor]);await pool.query("update public.tenants set status='inactive' where id=$1",[tenant]);assert.equal((await offer()).status,403);await pool.query("update public.tenants set status='active' where id=$1",[tenant]);await pool.query('delete from public.tenant_members where tenant_id=$1 and user_id=$2',[tenant,actor]);assert.equal((await offer()).status,403);await pool.query("insert into public.tenant_members(tenant_id,user_id,role) values($1,$2,'BUSINESS_OWNER')",[tenant,actor]);
 const euro=await post('/api/businesses',{name:'EUR business',slug:'catalog-eur-http',timezone:'Europe/Paris',currency:'EUR',businessType:'HOUSEKEEPING',idempotencyKey:'catalog-business-attempt-0003'});assert.equal((await offer(body,euro.json.data.tenantId)).status,400);assert.equal((await offer({...body,price:{amount:12500,currency:'EUR'}},euro.json.data.tenantId)).status,200);
 // Authoring itself has created no customer, publication, or financial rows.
 for(const table of ['flow_versions','flow_installations','flow_sessions','bookings','payments','capacity_holds'])assert.equal(Number((await pool.query(`select count(*) n from public.${table}`)).rows[0].n),0);
 assert.deepEqual((await pool.query('select lumin.paid_simple_service($1,$2) snapshot',[tenant,service])).rows[0].snapshot,{id:service,name:body.name,durationMinutes:60,price:body.price});
 // Separate test-only scheduling fixture; authoring does not provision availability.
 await pool.query('insert into public.scheduling_policies(tenant_id,service_id,lead_time_minutes,horizon_days,slot_interval_minutes) values($1,$2,0,30,30)',[tenant,service]);await pool.query('insert into public.availability_rules(tenant_id,service_id,weekday,start_minute,end_minute,capacity) select $1,$2,n,0,1440,1 from generate_series(0,6)n',[tenant,service]);
 const flow=id(20);assert.equal((await post(`/api/paid-simple-flows/${flow}/draft?tenantId=${tenant}`,{expectedRevision:0,serviceId:service,name:'Owner-created published cleaning',presentation:{accentColor:'#4f46e5',layout:'stacked'}})).status,200);const published=await post(`/api/paid-simple-flows/${flow}/publish-draft?tenantId=${tenant}`,{expectedDraftRevision:1,allowedOrigins:[customerOrigin]});assert.equal(published.status,200,JSON.stringify(published));const session=await post('/api/installations/'+published.json.data.publication.installationId+'/sessions',{},undefined,customerOrigin);assert.equal(session.status,200);assert.deepEqual(session.json.data.render.service.price,body.price);const token=session.json.data.sessionToken,start=new Date(Date.now()+86400000);start.setUTCHours(10,0,0,0);
 const requested=await post('/api/flow-sessions/request',{idempotencyKey:'catalog-customer-request-0001',answers:{},customer:{name:'Customer',email:'catalog-customer@example.test'},requestedStart:start.toISOString()},token,customerOrigin);assert.equal(requested.status,200,JSON.stringify(requested));const held=await post('/api/flow-sessions/hold',{},token,customerOrigin);assert.equal(held.status,200,JSON.stringify(held));const paid=await post('/api/flow-sessions/mock-payment',{},token,customerOrigin);assert.equal(paid.status,200,JSON.stringify(paid));assert.equal(paid.json.data.state,'confirmed');assert.equal(paid.json.data.provider,'staging_mock');assert.equal((await pool.query('select amount::int from public.payments where booking_id=$1',[held.json.data.bookingId])).rows[0].amount,12500);assert.equal((await pool.query('select status from public.capacity_holds where booking_id=$1',[held.json.data.bookingId])).rows[0].status,'consumed');assert.deepEqual(await offer(),concurrent[0]);
 console.log('PASS real HTTP owner-created HOUSEKEEPING simple offer: exact concurrent replay/different-key no deadlock; owner/profile/tenant/currency/price/drift denials; no authoring customer or financial writes; independently eligible existing helper; separate scheduling fixture -> draft publish -> pinned12500 request/hold/staging test payment confirmed consumed');
}finally{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));await pool.end();}
