import {afterEach,expect,it,vi} from 'vitest';
import type {Server} from 'node:http';
import {createFlowHttpServer} from './http';
import {catalogAuthoringEnabled,createSimpleOfferCreator} from './owner-catalog';
import {FlowError} from './repository';
const id=(n:number)=>`46000000-0000-4000-8000-${String(n).padStart(12,'0')}`,actor=id(1),tenant=id(2),origin='https://portal.example.test',body={name:'Home cleaning',description:'Fixed cleaning visit',price:{amount:12500,currency:'USD'},durationMinutes:60,idempotencyKey:'offer-attempt-0001'},receipt={schemaVersion:1 as const,tenantId:tenant,service:{id:id(3),name:body.name,description:body.description,archetype:'simple' as const,price:body.price,durationMinutes:60}};
let server:Server;afterEach(async()=>{server?.closeAllConnections();if(server)await new Promise<void>(r=>server.close(()=>r()));});
async function http(enabled=true,value:unknown=receipt){const create=vi.fn(async()=>{if(value instanceof Error)throw value;return value as typeof receipt;}),call=vi.fn();server=createFlowHttpServer({repository:{call},catalogAuthoring:enabled,simpleOfferCreate:create,ownerOrigins:[origin],customerOrigins:[],authenticateOwner:async token=>token==='owner-token-123456'?actor:null});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));return{create,call,post:(value:unknown=body,query=`tenantId=${tenant}`,token='owner-token-123456',o=origin,method='POST')=>fetch(`http://127.0.0.1:${(server.address() as {port:number}).port}/api/catalog/simple-offers?${query}`,{method,headers:{origin:o,authorization:`Bearer ${token}`,'content-type':'application/json'},...(method==='POST'?{body:JSON.stringify(value)}:{})})};}
it('binds verified actor and query tenant, exposes only exact created service snapshot',async()=>{const f=await http(),r=await f.post();expect(r.status).toBe(200);expect(r.headers.get('cache-control')).toBe('no-store');expect(await r.json()).toEqual({ok:true,data:receipt});expect(f.create).toHaveBeenCalledWith(actor,tenant,body);expect(f.call).not.toHaveBeenCalled();});
it.each([{actor},{tenantId:tenant},{serviceId:id(3)},{archetype:'simple'},{taxRateBp:0},{rental:null},{questions:[]},{provider:'stripe'},{role:'BUSINESS_OWNER'}])('rejects widened authoring %j',async extra=>{const f=await http();expect((await f.post({...body,...extra})).status).toBe(400);expect(f.create).not.toHaveBeenCalled();});
it.each([-1,0,1.5,Number.MAX_SAFE_INTEGER+1])('rejects invalid monetary amount %s before writer',async amount=>{const f=await http();expect((await f.post({...body,price:{amount,currency:'USD'}})).status).toBe(400);expect(f.create).not.toHaveBeenCalled();});
it.each(['',`tenantId=${tenant}&tenantId=${tenant}`,`tenantId=${tenant}&retry=true`])('rejects widened tenant query %s',async query=>{const f=await http();expect((await f.post(body,query)).status).toBe(400);expect(f.create).not.toHaveBeenCalled();});
it('requires exact origin, fresh identity and separate staging capability',async()=>{const f=await http(false);expect((await f.post()).status).toBe(422);expect((await f.post(body,undefined,'forged-token-123456')).status).toBe(401);expect((await f.post(body,undefined,undefined,'https://checkout.example.test')).status).toBe(403);expect(f.create).not.toHaveBeenCalled();});
it('does not expose GET or update semantics',async()=>{const f=await http();expect((await f.post(body,undefined,undefined,undefined,'GET')).status).toBe(404);expect(f.create).not.toHaveBeenCalled();});
it.each([['FORBIDDEN',403],['NOT_AVAILABLE',404],['INVALID_REQUEST',400],['CONFLICT',409],['UNSUPPORTED_CONFIG',422]] as const)('preserves safe %s',async(code,status)=>{const f=await http(true,new FlowError(code));const r=await f.post();expect(r.status).toBe(status);expect(await r.json()).toEqual({ok:false,code});});
it.each([{...receipt,tenantId:actor},{...receipt,service:{...receipt.service,price:{amount:1,currency:'USD'}}},{...receipt,service:{...receipt.service,name:'Changed'}},{...receipt,service:{...receipt.service,durationMinutes:120}}])('denies inconsistent returned authority',async value=>{const f=await http(true,value);expect((await f.post()).status).toBe(500);});
it('gate defaults closed, is independent of fake payments and stays closed in production',()=>{expect(catalogAuthoringEnabled({})).toBe(false);expect(catalogAuthoringEnabled({BOOKING_LUMIN_ENV:'staging',BOOKING_LUMIN_CATALOG_AUTHORING:'1'})).toBe(true);expect(catalogAuthoringEnabled({BOOKING_LUMIN_ENV:'production',BOOKING_LUMIN_CATALOG_AUTHORING:'1'})).toBe(false);expect(catalogAuthoringEnabled({BOOKING_LUMIN_ENV:'staging',BOOKING_LUMIN_FAKE_PAYMENTS:'1'})).toBe(false);});
function db(value:unknown=receipt,error?:unknown){const release=vi.fn(),query=vi.fn(async(sql:string,..._args:unknown[])=>{if(sql.startsWith('select')){if(error)throw error;return{rows:[{result:value}]};}return{rows:[]};});return{query,release,create:createSimpleOfferCreator({connect:async()=>({query,release})} as never)};}
it('fixed parameterized writer uses generated server UUID and no financial writer',async()=>{const f=db();expect(await f.create(actor,tenant,body)).toEqual(receipt);expect(f.query).toHaveBeenCalledWith('select public.create_housekeeping_simple_offer($1::uuid,$2::uuid,$3::uuid,$4::text,$5::text,$6::bigint,$7::text,$8::integer,$9::text) as result',[actor,tenant,expect.stringMatching(/^[0-9a-f-]{36}$/),body.name,body.description,12500,'USD',60,body.idempotencyKey]);expect(f.query).toHaveBeenLastCalledWith('commit');});
it.each([{...receipt,tenantId:actor},{...receipt,service:{...receipt.service,description:'Changed'}},{...receipt,service:{...receipt.service,price:{amount:1,currency:'USD'}}}])('rolls back malformed SQL snapshot before commit',async value=>{const f=db(value);await expect(f.create(actor,tenant,body)).rejects.toMatchObject({code:'INTERNAL_ERROR'});expect(f.query).toHaveBeenLastCalledWith('rollback');});
it.each([['42501','FORBIDDEN'],['23505','CONFLICT'],['P0002','NOT_AVAILABLE'],['0A000','UNSUPPORTED_CONFIG'],['22023','INVALID_REQUEST'],['XX000','INTERNAL_ERROR']])('redacts SQL failure %s',async(code,expected)=>{const f=db(undefined,{code,message:'secret'});await expect(f.create(actor,tenant,body)).rejects.toMatchObject({code:expected,message:expected});expect(f.query).toHaveBeenLastCalledWith('rollback');});
