import {afterEach,describe,expect,it,vi} from 'vitest';
import type {Server} from 'node:http';
import {createFlowHttpServer,tokenHash} from './http';
import {FlowError} from './repository';
import {createPaidJourneyHoldWriter,PaidJourneyHoldInput,PaidJourneyHoldReceipt} from './paid-journey-hold';
const id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',origin='https://checkout.example.test',token='a'.repeat(43),now=Date.parse('2030-01-01T00:00:00Z');
const input={schemaVersion:1 as const,idempotencyKey:'journey-hold-fixture-0001',requestedStart:'2030-01-01T10:00:00.000Z',customer:{name:'Staging customer',email:'customer@example.test'},answers:{}};
const target={tenantId:id,sessionExpiresAt:'2030-01-01T00:15:00Z',versionId:id,installationId:id,serviceId:id,bookingId:id,reference:'LMN-'+'A'.repeat(32),slot:{start:input.requestedStart,end:'2030-01-01T11:00:00.000Z'}};
const receipt={schemaVersion:1 as const,versionId:id,installationId:id,serviceId:id,bookingId:id,reference:target.reference,state:'draft' as const,confirmed:false as const,paymentMode:'unavailable' as const,slot:target.slot,holdId:id,status:'active' as const,expiresAt:'2030-01-01T00:05:00.000Z',replayed:false};
describe('dedicated atomic V8 request and hold',()=>{
 let server:Server;afterEach(async()=>{if(server){server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));}});
 async function fixture(value:unknown=receipt,enabled=true){const write=vi.fn(async()=>value as never),owner=vi.fn(async()=>null),call=vi.fn(async()=>{throw Error('legacy RPC must not be used');});server=createFlowHttpServer({repository:{call},ownerOrigins:['https://portal.example.test'],customerOrigins:[origin],authenticateOwner:owner,paidJourneySessions:enabled,paidJourneyHold:write,now:()=>now});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));return{write,owner,call,url:`http://127.0.0.1:${(server.address() as {port:number}).port}/api/paid-journey-flow-sessions/hold`};}
 async function send(url:string,value:unknown=input,t=token,o=origin){return fetch(url,{method:'POST',headers:{origin:o,authorization:`Bearer ${t}`,'content-type':'application/json'},body:JSON.stringify(value)});}
 it('passes hashed dedicated bearer and actual origin only to the atomic writer, with strict no-store receipt',async()=>{const f=await fixture(),r=await send(f.url);expect(r.status).toBe(200);expect(r.headers.get('cache-control')).toBe('no-store');expect(r.headers.get('x-request-id')).toBeTruthy();expect(await r.json()).toEqual({ok:true,data:receipt});expect(f.write).toHaveBeenCalledWith(tokenHash(token),origin,input);expect(f.owner).not.toHaveBeenCalled();expect(f.call).not.toHaveBeenCalled();});
 it.each(['tenantId','serviceId','bookingId','actorId','price','capacity','ttl','paymentId','confirmed','origin'])('rejects client authority %s before a writer',async key=>{const f=await fixture();expect((await send(f.url,{...input,[key]:id})).status).toBe(400);expect(f.write).not.toHaveBeenCalled();});
 it.each([{...input,answers:{paid:true}},{...input,customer:{...input.customer,phone:'123'}},{...input,customer:{name:' Name ',email:'customer@example.test'}},{...input,customer:{name:'private\u0000',email:'a@b.test'}},{...input,requestedStart:'2030-02-30T00:00:00Z'},{...input,idempotencyKey:'short'},{...input,requestedStart:'infinity'}])('rejects malformed unsupported fields and dates',async value=>{const f=await fixture();expect((await send(f.url,value)).status).toBe(400);expect(f.write).not.toHaveBeenCalled();});
 it('is gated off, rejects query scope, missing/wrong bearer and owner origin',async()=>{const f=await fixture(undefined,false);expect((await send(f.url)).status).toBe(422);expect(f.write).not.toHaveBeenCalled();});
 it('rejects method, query and spoofed origin without writer calls',async()=>{const f=await fixture();expect((await send(f.url+'?tenantId='+id)).status).toBe(400);expect((await send(f.url,input,'weak')).status).toBe(401);expect((await send(f.url,input,token,'https://portal.example.test')).status).toBe(403);expect((await fetch(f.url,{headers:{origin,authorization:`Bearer ${token}`}})).status).toBe(400);expect((await fetch(f.url,{method:'POST',headers:{origin,'content-type':'application/json'},body:'{}'})).status).toBe(401);expect(f.write).not.toHaveBeenCalled();});
 it.each([{...receipt,tenantId:id},{...receipt,customer:input.customer},{...receipt,paymentMode:'staging_mock'},{...receipt,confirmed:true},{...receipt,expiresAt:'2029-01-01T00:00:00Z'},{...receipt,expiresAt:'2030-01-01T00:06:00Z'},{...receipt,slot:{...receipt.slot,start:'2030-01-01T09:00:00Z'}}])('rejects malformed private or stale receipts',async value=>{const f=await fixture(value);expect((await send(f.url)).status).toBe(500);});
 it('redacts database/provider details from errors',async()=>{const f=await fixture();f.write.mockRejectedValue(new FlowError('CONFLICT'));const r=await send(f.url);expect(r.status).toBe(409);expect(JSON.stringify(await r.json())).not.toContain(token);});
 function database(replayed=false,old?:{status:string;expires_at:string},finalError=false){const statements:string[]=[];const c={query:vi.fn(async(sql:string)=>{statements.push(sql);if(sql.includes('submit_paid_journey_hold_request'))return{rows:[{result:{...target,replayed}}]};if(sql.includes('paid_journey_hold_target')){if(finalError)throw Object.assign(Error('private-database-secret'),{code:'42501'});return{rows:[{result:target}]};}if(sql.includes('select status,expires_at'))return{rows:old?[old]:[]};if(sql.includes("b.state='draft'"))return{rows:[{slot_start:target.slot.start,slot_end:target.slot.end,service_id:id}]};if(sql.includes('s.duration_minutes'))return{rows:[{duration_minutes:60,timezone:'UTC'}]};if(sql.includes('service_resources'))return{rows:[]};if(sql.includes('from public.availability_rules'))return{rows:[{id,tenantId:id,serviceId:id,weekday:2,startMinute:600,endMinute:660,capacity:1}]};if(sql.includes('from public.scheduling_policies'))return{rows:[{leadTimeMinutes:0,horizonDays:60,slotIntervalMinutes:30}]};if(sql.includes('reserve_capacity'))return{rows:[{result:'GRANTED',hold_id:id,hold_status:'active',expires_at:receipt.expiresAt}]};return{rows:[]};}),release:vi.fn()};return{c,statements,pool:{connect:async()=>c} as never};}
 it('uses original capacity serialization within one transaction and verifies final capability before commit',async()=>{const f=database();expect(await createPaidJourneyHoldWriter(f.pool,()=>new Date(now).toISOString())('a'.repeat(64),origin,input)).toEqual(receipt);expect(f.statements.at(-1)).toBe('commit');expect(f.statements.filter(s=>s.includes('reserve_capacity'))).toHaveLength(1);expect(f.c.query.mock.calls.some(([sql])=>sql.includes('flow_sessions'))).toBe(false);});
 it.each([undefined,{status:'released',expires_at:receipt.expiresAt},{status:'active',expires_at:'2029-01-01T00:00:00Z'}])('rejects missing or ended replay holds without renewal',async old=>{const f=database(true,old);await expect(createPaidJourneyHoldWriter(f.pool,()=>new Date(now).toISOString())('a'.repeat(64),origin,input)).rejects.toMatchObject({code:'CONFLICT'});expect(f.statements).toContain('rollback');expect(f.statements.some(s=>s.includes('reserve_capacity'))).toBe(false);});
 it('rolls back request and hold if final session expiry fails',async()=>{const f=database(false,undefined,true);await expect(createPaidJourneyHoldWriter(f.pool,()=>new Date(now).toISOString())('a'.repeat(64),origin,input)).rejects.toMatchObject({code:'FORBIDDEN',message:'FORBIDDEN'});expect(f.statements).toContain('rollback');expect(f.statements).not.toContain('commit');});
 it('rejects invalid hash/shape before opening a connection',async()=>{const connect=vi.fn();await expect(createPaidJourneyHoldWriter({connect} as never)('weak',origin,input)).rejects.toMatchObject({code:'INVALID_REQUEST'});expect(connect).not.toHaveBeenCalled();expect(PaidJourneyHoldInput.safeParse({...input,customer:{...input.customer,name:'\ud800'}}).success).toBe(false);expect(PaidJourneyHoldReceipt.safeParse({...receipt,pricing:{amount:1}}).success).toBe(false);});
});
