import assert from 'node:assert/strict';
import {isIP} from 'node:net';
import {Pool} from 'pg';
import {createPaidJourneyCustomerFieldSessionIssuer} from './paid-journey-customer-field-session';
import {createPaidJourneyCustomerFieldDraftOperations} from './paid-journey-customer-field-draft';
import {createPaidJourneyCustomerFieldPublicationOperations} from './paid-journey-customer-field-publication';
assert.equal(process.env.PAID_JOURNEY_CUSTOMER_FIELD_SESSION_LOCAL_TEST,'1');assert.equal(process.env.PGHOST,'127.0.0.1');assert.equal(process.env.PGUSER,'postgres');
let host='127.0.0.1';if(process.env.CI==='true'){assert.equal(process.env.GITHUB_ACTIONS,'true');assert.equal(process.env.PGPORT,'5432');assert.equal(process.env.PGDATABASE,'lumin_journey_fields_session_ci');host=process.env.PAID_JOURNEY_CUSTOMER_FIELD_SESSION_CI_DATABASE_HOST??'';assert.equal(isIP(host),4);assert.match(host,/^(?:10\.|172\.(?:1[6-9]|2[0-9]|3[01])\.|192\.168\.)/);}else{assert.notEqual(process.env.GITHUB_ACTIONS,'true');assert.equal(process.env.PGPORT,'59069');assert.match(process.env.PGDATABASE??'',/^lumin_journey_fields_session_local_[a-z0-9_]+$/);}for(const key of ['DATABASE_URL','PGHOSTADDR','PGSERVICE','PGSERVICEFILE','PGPASSFILE','PGOPTIONS'])assert.ok(!process.env[key]);
const pool=new Pool({max:6}),id=(n:number)=>`82300000-0000-4000-8000-${String(n).padStart(12,'0')}`,actor=id(1),tenant=id(2),service=id(3),flow=id(4),origin='https://checkout.example.test',secondOrigin='https://second-checkout.example.test';
const issue=createPaidJourneyCustomerFieldSessionIssuer(pool,[origin,secondOrigin]),draft=createPaidJourneyCustomerFieldDraftOperations(pool),publication=createPaidJourneyCustomerFieldPublicationOperations(pool,{configuredCustomerOrigins:[origin,secondOrigin]});
const form={name:'Session fixture',presentation:{accentColor:'#0e7490' as const,layout:'compact' as const},journey:{schemaVersion:1 as const,stages:(['service','options','schedule','information','review_payment','confirmation'] as const).map(kind=>({id:kind,kind,label:kind,enabled:kind!=='options'}))},customerFields:[{id:'custom_gate',kind:'text' as const,label:'Gate',required:false,maxLength:100}],fieldBindings:[{fieldId:'custom_gate',stageId:'information'}]};
const deny=(run:()=>Promise<unknown>,code:string)=>assert.rejects(run,{code});
async function counts(){const n:Record<string,string>={};for(const table of ['bookings','payments','capacity_holds','flow_sessions','paid_journey_sessions','paid_journey_session_generations','paid_journey_holds','paid_journey_hold_bindings','durable_outbox','flow_requests']){if((await pool.query('select to_regclass($1) r',['public.'+table])).rows[0].r)n[table]=(await pool.query(`select count(*)::text n from public.${table}`)).rows[0].n;}return n;}
try{
 assert.deepEqual((await pool.query('select current_database() d,current_user u,host(inet_server_addr()) h,inet_server_port() p')).rows[0],{d:process.env.PGDATABASE,u:'postgres',h:host,p:Number(process.env.PGPORT)});
 const before=await counts();await pool.query("insert into auth.users(id,email) values($1,'session-factory-owner@example.test')",[actor]);await pool.query("insert into public.tenants(id,name,slug,timezone,currency) values($1,'Sessions','session-factory','UTC','USD')",[tenant]);await pool.query("insert into public.tenant_members(tenant_id,user_id,role) values($1,$2,'BUSINESS_OWNER')",[tenant,actor]);await pool.query('select public.initialize_staging_business_profile($1,$2,$3,$4)',[actor,tenant,'HOUSEKEEPING','session_factory_profile']);await pool.query("insert into public.services(id,tenant_id,name,archetype,currency,base_price,duration_minutes) values($1,$2,'Cleaning','simple','USD',12500,60)",[service,tenant]);
 await draft.save(actor,tenant,flow,{schemaVersion:2,serviceId:service,expectedRevision:0,form});await publication.publish(actor,tenant,flow,{schemaVersion:2,expectedDraftRevision:1,allowedOrigins:[origin,secondOrigin]},id(5),id(6));
 const [a,b]=await Promise.all([issue(id(6),'a'.repeat(64),origin),issue(id(6),'a'.repeat(64),origin)]);assert.deepEqual(a,b);assert.equal(a.schemaVersion,2);assert.equal(a.render.versionId,id(5));assert.equal(a.render.service.price.amount,12500);assert.deepEqual(Object.keys(a).sort(),['expiresAt','installationId','render','schemaVersion']);assert.equal((await pool.query('select count(*)::int n from public.paid_journey_customer_field_sessions')).rows[0].n,1);
 await deny(()=>issue(id(6),'a'.repeat(64),secondOrigin),'CONFLICT');await deny(()=>issue(id(6),'b'.repeat(64),'https://foreign.example.test'),'FORBIDDEN');await deny(()=>issue(id(6),'plaintext',origin),'INVALID_REQUEST');await deny(()=>issue(id(6),'b'.repeat(64),origin+'/'),'INVALID_REQUEST');
 for(const role of ['anon','authenticated','service_role']){const client=await pool.connect();try{await client.query('begin');await client.query('set local role '+role);await deny(()=>client.query('select * from public.paid_journey_customer_field_sessions'),'42501');await client.query('rollback');}finally{client.release();}}
 await deny(()=>pool.query("update public.paid_journey_customer_field_sessions set origin=$1 where token_hash=$2",[secondOrigin,'a'.repeat(64)]),'55000');
 await pool.query("insert into public.paid_journey_customer_field_sessions select $1,tenant_id,flow_id,version_id,installation_id,service_id,publication_generation,origin,issued_at-interval '16 minutes',expires_at-interval '16 minutes' from public.paid_journey_customer_field_sessions where token_hash=$2",['e'.repeat(64),'a'.repeat(64)]);await deny(()=>issue(id(6),'e'.repeat(64),origin),'FORBIDDEN');
 await pool.query('update public.services set base_price=13000 where id=$1',[service]);await deny(()=>issue(id(6),'b'.repeat(64),origin),'CONFLICT');await pool.query('update public.services set base_price=12500 where id=$1',[service]);
 await pool.query("update public.tenants set status='suspended' where id=$1",[tenant]);await deny(()=>issue(id(6),'b'.repeat(64),origin),'NOT_AVAILABLE');await pool.query("update public.tenants set status='active' where id=$1",[tenant]);
 await pool.query('update public.services set active=false where id=$1',[service]);await deny(()=>issue(id(6),'b'.repeat(64),origin),'NOT_AVAILABLE');await pool.query('update public.services set active=true where id=$1',[service]);
 await deny(()=>pool.query('select public.issue_paid_journey_session($1,$2,$3)',[id(6),'b'.repeat(64),origin]),'P0002');await deny(()=>pool.query('select public.resolve_paid_journey_session($1,$2)',['a'.repeat(64),origin]),'42501');
 await draft.save(actor,tenant,flow,{schemaVersion:2,serviceId:service,expectedRevision:1,form:{...form,name:'Second snapshot'}});await publication.publish(actor,tenant,flow,{schemaVersion:2,expectedDraftRevision:2,allowedOrigins:[origin,secondOrigin]},id(7),id(8));await deny(()=>issue(id(6),'a'.repeat(64),origin),'NOT_AVAILABLE');await deny(()=>issue(id(8),'a'.repeat(64),origin),'CONFLICT');const fresh=await issue(id(8),'b'.repeat(64),origin);assert.equal(fresh.render.versionId,id(7));assert.equal(fresh.render.form.name,'Second snapshot');assert.equal((await pool.query('select count(*)::int n from public.paid_journey_customer_field_sessions')).rows[0].n,3);
 // Controlled private generation advance models a future restore of the same immutable pointer.
 await pool.query('update public.paid_journey_publication_generations set generation=generation+1 where tenant_id=$1 and flow_id=$2',[tenant,flow]);await deny(()=>issue(id(8),'b'.repeat(64),origin),'FORBIDDEN');const regenerated=await issue(id(8),'c'.repeat(64),origin);assert.equal(regenerated.render.versionId,id(7));
 assert.deepEqual(await counts(),before);console.log('PASS V9 isolated actual session issuance: concurrent exact replay, private privileges, immutable hash/provenance/expiry/origin, catalog/suspension/service gates, stale publication and protocol isolation, unchanged financial/outbox/legacy rows');
}finally{await pool.end();}
