import {afterEach,describe,expect,it,vi} from 'vitest';
import {createPaidJourneyCustomerFieldHoldWriter,PaidJourneyCustomerFieldHoldInput,PaidJourneyCustomerFieldHoldReceipt} from './paid-journey-customer-field-hold';
const {reserve}=vi.hoisted(()=>({reserve:vi.fn()}));vi.mock('./reservation',()=>({reserveBookingInTransaction:reserve}));
const id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',other='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',origin='https://checkout.example.test',now='2030-01-01T00:00:00.000Z';
const form={name:'Cleaning',presentation:{accentColor:'#0e7490',layout:'compact'},journey:{schemaVersion:1,stages:['service','options','schedule','information','review_payment','confirmation'].map(kind=>({id:kind,kind,label:kind,enabled:kind!=='options'}))},customerFields:[{id:'custom_gate',kind:'text',label:'Gate',required:true,maxLength:100},{id:'custom_code',kind:'text',label:'Code',required:true,maxLength:100,when:{fieldId:'custom_gate',equals:'yes'}}],fieldBindings:[{fieldId:'custom_gate',stageId:'information'},{fieldId:'custom_code',stageId:'information'}]};
const render={versionId:id,renderSchemaVersion:9,submissionMode:'paid_journey_customer_field_request',paymentMode:'staging_mock',simulated:true,service:{id,name:'Cleaning',durationMinutes:60,price:{amount:12500,currency:'USD'}},form};
const input={schemaVersion:2 as const,idempotencyKey:'journey-fields-hold-test-0001',requestedStart:'2030-01-01T09:00:00.000Z',customer:{name:'Customer',email:'customer@example.test'},answers:{custom_gate:'no'}};
const target={tenantId:id,sessionExpiresAt:'2030-01-01T00:15:00.000Z',publicationGeneration:2,versionId:id,installationId:id,serviceId:id,bookingId:id,reference:'LMN-'+id.replaceAll('-','').toUpperCase(),slot:{start:input.requestedStart,end:'2030-01-01T10:00:00.000Z'},render};
const hold={bookingId:id,holdId:id,status:'active',expiresAt:'2030-01-01T00:05:00.000Z'};
function fixture(replayed=false,old?:unknown,final:unknown=target,accepted:unknown={...target,replayed}){const statements:string[]=[],query=vi.fn(async(sql:string)=>{statements.push(sql);return{rows:sql.includes('submit_paid_journey_customer_field_hold_request')?[{result:accepted}]:sql.includes('paid_journey_customer_field_hold_target')?[{result:final}]:sql.includes('select status,expires_at')?(old?[old]:[]):[]};}),release=vi.fn(),client={query,release},connect=vi.fn(async()=>client);reserve.mockResolvedValue({...hold});return{client,query,release,connect,statements,writer:createPaidJourneyCustomerFieldHoldWriter({connect} as never,{configuredCustomerOrigins:[origin]},()=>now)};}
afterEach(()=>vi.clearAllMocks());
describe('dedicated private V9 hold factory',()=>{
 it('uses a single transaction with original capacity authority, final provenance and immutable public receipt',async()=>{const f=fixture(),receipt=await f.writer('a'.repeat(64),origin,input);expect(receipt).toEqual({schemaVersion:2,versionId:id,installationId:id,serviceId:id,reference:target.reference,state:'draft',confirmed:false,paymentMode:'unavailable',slot:target.slot,...hold,replayed:false});expect(reserve).toHaveBeenCalledExactlyOnceWith(f.client,id,id,expect.any(Function),id);expect(f.statements[0]).toBe('begin isolation level read committed');expect(f.statements.at(-1)).toBe('commit');expect(f.statements.join(' ')).not.toMatch(/confirm|payment|submit_paid_journey_hold_request|flow_sessions/);expect(Object.isFrozen(receipt)).toBe(true);expect(Object.isFrozen(receipt.slot)).toBe(true);expect(JSON.stringify(receipt)).not.toContain('customer');});
 it.each(['tenantId','serviceId','price','capacity','ttl','paymentId','confirmed'])('rejects injected authority %s before connect',async key=>{const f=fixture();await expect(f.writer('a'.repeat(64),origin,{...input,[key]:other} as never)).rejects.toMatchObject({code:'INVALID_REQUEST'});expect(f.connect).not.toHaveBeenCalled();});
 it.each([{...input,schemaVersion:1},{...input,answers:{price:'1'}},{...input,answers:{custom_amount:'1'}},{...input,customer:{...input.customer,name:' invalid '}},{...input,customer:{...input.customer,name:'bad\ud800'}},{...input,customer:{...input.customer,email:'bad\u0000'}},{...input,requestedStart:'2030-02-30T00:00:00Z'},{...input,idempotencyKey:'short'}])('rejects malformed/legacy input before connection',async body=>{const f=fixture();await expect(f.writer('a'.repeat(64),origin,body as never)).rejects.toMatchObject({code:'INVALID_REQUEST'});expect(f.connect).not.toHaveBeenCalled();});
 it('rejects executable, hidden, inherited or symbol data without calling getters',async()=>{const f=fixture(),getter=vi.fn(()=>input.customer),bad=[Object.create(input),{...input,get customer(){return getter();}},Object.defineProperty({...input},'private',{value:1}),{...input,[Symbol('authority')]:1},{...input,answers:{get custom_gate(){return getter();}}}];for(const body of bad)await expect(f.writer('a'.repeat(64),origin,body as never)).rejects.toMatchObject({code:'INVALID_REQUEST'});expect(getter).not.toHaveBeenCalled();expect(f.connect).not.toHaveBeenCalled();});
 it.each(['*',origin+'/','http://checkout.example.test'])('denies invalid origin %s before connect',async candidate=>{const f=fixture();await expect(f.writer('a'.repeat(64),candidate,input)).rejects.toMatchObject({code:'INVALID_REQUEST'});expect(f.connect).not.toHaveBeenCalled();});
 it('denies unapproved origin and noncanonical hash before connect',async()=>{const f=fixture();await expect(f.writer('a'.repeat(64),'https://other.example.test',input)).rejects.toMatchObject({code:'FORBIDDEN'});await expect(f.writer('A'.repeat(64),origin,input)).rejects.toMatchObject({code:'INVALID_REQUEST'});expect(f.connect).not.toHaveBeenCalled();});
 it.each([{},{custom_gate:'yes'},{custom_gate:'no',custom_code:'hidden'},{custom_gate:'no',custom_unknown:'foreign'}])('validates informational answers to immutable pinned visibility before capacity',async answers=>{const f=fixture();await expect(f.writer('a'.repeat(64),origin,{...input,answers} as never)).rejects.toMatchObject({code:'INVALID_REQUEST'});expect(reserve).not.toHaveBeenCalled();expect(f.statements).toContain('rollback');});
 it('permits required conditional text without deriving any amount',async()=>{const f=fixture();const receipt=await f.writer('a'.repeat(64),origin,{...input,answers:{custom_gate:'yes',custom_code:'exact'}});expect(receipt.paymentMode).toBe('unavailable');expect(receipt).not.toHaveProperty('amount');});
 it.each([undefined,{status:'released',expires_at:hold.expiresAt},{status:'consumed',expires_at:hold.expiresAt},{status:'active',expires_at:'2029-01-01T00:00:00Z'}])('never renews missing/ended replay authority',async old=>{const f=fixture(true,old);await expect(f.writer('a'.repeat(64),origin,input)).rejects.toMatchObject({code:'CONFLICT'});expect(reserve).not.toHaveBeenCalled();expect(f.statements).not.toContain('commit');});
 it('identical replay retains its original active hold instead of minting new authority',async()=>{const f=fixture(true,{status:'active',expires_at:hold.expiresAt}),receipt=await f.writer('a'.repeat(64),origin,input);expect(receipt.replayed).toBe(true);expect(receipt.holdId).toBe(id);expect(receipt.expiresAt).toBe(hold.expiresAt);});
 it.each([{...target,publicationGeneration:3},{...target,sessionExpiresAt:now}])('rolls back if final generation or expiry changed after capacity',async final=>{const f=fixture(false,undefined,final);await expect(f.writer('a'.repeat(64),origin,input)).rejects.toMatchObject({code:'FORBIDDEN'});expect(f.statements).toContain('rollback');expect(f.statements).not.toContain('commit');});
 it.each([{...target,serviceId:other,replayed:false},{...target,slot:{...target.slot,end:'2030-01-01T11:00:00Z'},replayed:false},{...target,reference:'LMN-'+'B'.repeat(32),replayed:false},{...target,private:true,replayed:false}])('denies malformed or foreign private target',async accepted=>{const f=fixture(false,undefined,target,accepted);await expect(f.writer('a'.repeat(64),origin,input)).rejects.toMatchObject({code:'INTERNAL_ERROR'});expect(reserve).not.toHaveBeenCalled();});
 it('rejects a forged capacity booking or excessive TTL before commit',async()=>{for(const value of [{...hold,bookingId:other},{...hold,expiresAt:'2030-01-01T00:06:00Z'}]){const f=fixture();reserve.mockResolvedValue(value);await expect(f.writer('a'.repeat(64),origin,input)).rejects.toMatchObject({code:'INTERNAL_ERROR'});expect(f.statements).not.toContain('commit');}});
 it.each([['42501','FORBIDDEN'],['P0002','NOT_AVAILABLE'],['0A000','UNSUPPORTED_CONFIG'],['22023','INVALID_REQUEST'],['40P01','CONFLICT'],['23505','CONFLICT'],['untrusted','INTERNAL_ERROR']])('sanitizes SQL %s without retry',async(code,expected)=>{const f=fixture();f.query.mockRejectedValueOnce(Object.assign(Error('private database password'),{code}));await expect(f.writer('a'.repeat(64),origin,input)).rejects.toMatchObject({code:expected,message:expected});expect(reserve).not.toHaveBeenCalled();});
 it('disposes failed rollback connections and hides connect/provider failures',async()=>{const f=fixture();reserve.mockRejectedValue(Error('private'));f.query.mockImplementation(async(sql:string)=>{if(sql==='rollback')throw Error('private rollback');return{rows:sql.includes('submit_')?[{result:{...target,replayed:false}}]:[]};});await expect(f.writer('a'.repeat(64),origin,input)).rejects.toMatchObject({code:'INTERNAL_ERROR'});expect(f.release).toHaveBeenCalledWith(true);});
 it('schemas exclude legacy receipt, financial truth and oversized JSON',()=>{expect(PaidJourneyCustomerFieldHoldInput.safeParse({...input,answers:{custom_gate:'x'.repeat(1001)}}).success).toBe(false);expect(PaidJourneyCustomerFieldHoldReceipt.safeParse({...hold,schemaVersion:1}).success).toBe(false);expect(PaidJourneyCustomerFieldHoldReceipt.safeParse({...hold,schemaVersion:2,confirmed:true}).success).toBe(false);});
});