import {afterEach,describe,expect,it,vi} from 'vitest';
import type {Server} from 'node:http';
import {createFlowHttpServer,tokenHash} from './http';
import {createPaidJourneyMockPaymentWriter} from './paid-journey-payment';
const id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',origin='https://checkout.example.test',token='a'.repeat(43);
const receipt={schemaVersion:1,versionId:id,installationId:id,serviceId:id,bookingId:id,paymentId:id,reference:'LMN-'+id.replaceAll('-','').toUpperCase(),state:'confirmed',replayed:false,provider:'staging_mock',simulated:true,amount:12500,currency:'USD'};
describe('dedicated V8 staging mock payment',()=>{
 let server:Server;afterEach(async()=>{if(server){server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));}});
 async function fixture(value:unknown=receipt,enabled=true){const pay=vi.fn(async()=>value as never),legacy=vi.fn(),call=vi.fn(),owner=vi.fn();server=createFlowHttpServer({repository:{call},ownerOrigins:['https://portal.example.test'],customerOrigins:[origin],authenticateOwner:owner,paidJourneySessions:enabled,paidJourneyMockPayment:pay,mockPayment:legacy});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));return{pay,legacy,call,owner,url:`http://127.0.0.1:${(server.address() as {port:number}).port}/api/paid-journey-flow-sessions/mock-payment`};}
 const post=(url:string,body:unknown={},t=token,o=origin)=>fetch(url,{method:'POST',headers:{origin:o,authorization:`Bearer ${t}`,'content-type':'application/json'},body:JSON.stringify(body)});
 it('accepts only customer hash and actual origin, invokes no generic writer',async()=>{const f=await fixture(),r=await post(f.url);expect(r.status).toBe(200);expect(r.headers.get('cache-control')).toBe('no-store');expect(r.headers.get('x-request-id')).toBeTruthy();expect(await r.json()).toEqual({ok:true,data:receipt});expect(f.pay).toHaveBeenCalledWith(tokenHash(token),origin);expect(f.legacy).not.toHaveBeenCalled();expect(f.owner).not.toHaveBeenCalled();expect(f.call).not.toHaveBeenCalled();});
 it('fails closed without dedicated session capability',async()=>{const f=await fixture(undefined,false);expect((await post(f.url)).status).toBe(422);expect(f.pay).not.toHaveBeenCalled();});
 it.each(['amount','currency','tenantId','actorId','serviceId','paymentId','confirmed','sessionToken','origin'])('rejects body authority %s',async key=>{const f=await fixture();expect((await post(f.url,{[key]:id})).status).toBe(400);expect(f.pay).not.toHaveBeenCalled();});
 it('rejects query/body-less method/weak bearer/foreign origin',async()=>{const f=await fixture();expect((await post(f.url+'?tenantId='+id)).status).toBe(400);expect((await fetch(f.url,{headers:{origin,authorization:`Bearer ${token}`}})).status).toBe(400);expect((await post(f.url,{},'weak')).status).toBe(401);expect((await post(f.url,{},token,'https://portal.example.test')).status).toBe(403);expect(f.pay).not.toHaveBeenCalled();});
 it.each([{...receipt,amount:Infinity},{...receipt,amount:-1},{...receipt,amount:Number.MAX_SAFE_INTEGER+1},{...receipt,provider:'stripe'},{...receipt,simulated:false},{...receipt,state:'draft'},{...receipt,tenantId:id},{...receipt,customer:{email:'private'}},{...receipt,reference:'LMN-'+'B'.repeat(32)}])('rejects malformed/financial/private receipts',async value=>{const f=await fixture(value);expect((await post(f.url)).status).toBe(500);});
 const env={BOOKING_LUMIN_FAKE_PAYMENTS:'1',BOOKING_LUMIN_ENV:'staging'};
 function database(value:unknown=receipt,code?:string){const statements:string[]=[];const c={query:vi.fn(async(sql:string)=>{statements.push(sql);if(sql.includes('pay_paid_journey_mock')){if(code)throw Object.assign(Error('private-password'),{code});return{rows:[{result:value}]};}return{rows:[]};}),release:vi.fn()};return{c,statements,pool:{connect:async()=>c} as never};}
 it('narrows role, parameterizes one RPC and validates before commit',async()=>{const f=database();expect(await createPaidJourneyMockPaymentWriter(f.pool,env)('a'.repeat(64),origin)).toEqual(receipt);expect(f.statements).toEqual(['begin',"set local statement_timeout='5s'","set local lock_timeout='3s'",'set local role service_role','select public.pay_paid_journey_mock($1,$2) result','commit']);expect(f.c.query).toHaveBeenCalledWith('select public.pay_paid_journey_mock($1,$2) result',['a'.repeat(64),origin]);});
 it('never enables simulated evidence in production or default config',async()=>{const connect=vi.fn();expect(()=>createPaidJourneyMockPaymentWriter({connect} as never,{...env,BOOKING_LUMIN_ENV:'production'})).toThrow();await expect(createPaidJourneyMockPaymentWriter({connect} as never,{})('a'.repeat(64),origin)).rejects.toMatchObject({code:'UNSUPPORTED_CONFIG'});expect(connect).not.toHaveBeenCalled();});
 it.each([['42501','FORBIDDEN'],['P0002','NOT_AVAILABLE'],['40001','CONFLICT'],['0A000','UNSUPPORTED_CONFIG'],['other','INTERNAL_ERROR']])('rolls back safely for SQL %s',async(code,expected)=>{const f=database(undefined,code);await expect(createPaidJourneyMockPaymentWriter(f.pool,env)('a'.repeat(64),origin)).rejects.toMatchObject({code:expected,message:expected});expect(f.statements.at(-1)).toBe('rollback');});
 it('rolls back malformed receipt and rejects invalid hash without connecting',async()=>{const f=database({...receipt,simulated:false});await expect(createPaidJourneyMockPaymentWriter(f.pool,env)('a'.repeat(64),origin)).rejects.toMatchObject({code:'INTERNAL_ERROR'});expect(f.statements.at(-1)).toBe('rollback');const connect=vi.fn();await expect(createPaidJourneyMockPaymentWriter({connect} as never,env)('weak',origin)).rejects.toMatchObject({code:'INVALID_REQUEST'});expect(connect).not.toHaveBeenCalled();});
});

