import {afterEach,describe,expect,it,vi} from 'vitest';
import {request,type Server} from 'node:http';
import {createFlowHttpServer,tokenHash} from './http';
import {FlowError} from './repository';
const id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',origin='https://checkout.example.test',token=Buffer.alloc(32,19).toString('base64url');
const from='2030-01-01T10:00:00.000Z',to='2030-01-02T10:00:00.000Z';
const receipt={schemaVersion:2,installationId:id,versionId:id,serviceId:id,durationMinutes:60,slots:[{start:from,end:'2030-01-01T11:00:00.000Z',remainingCapacity:1}]};
let server:Server|undefined;
afterEach(async()=>{if(server){server.closeAllConnections();await new Promise<void>((resolve,reject)=>server!.close(error=>error?reject(error):resolve()));server=undefined;}});
async function fixture(value:unknown=receipt,enabled=true){const read=vi.fn(async()=>{if(value instanceof Error)throw value;return value;}),call=vi.fn(async()=>{throw Error('legacy forbidden');}),auth=vi.fn(async()=>null);server=createFlowHttpServer({ownerOrigins:['https://portal.example.test'],customerOrigins:[origin],authenticateOwner:auth,repository:{call} as never,...(enabled?{paidJourneyCustomerFieldAvailability:read as never}:{})});await new Promise<void>(resolve=>server!.listen(0,'127.0.0.1',resolve));return{read,call,auth,url:`http://127.0.0.1:${(server.address() as {port:number}).port}/api/public/paid-journey-customer-field-flow-sessions/availability`};}
const query='?from='+encodeURIComponent(from)+'&to='+encodeURIComponent(to);
const get=(url:string,headers:Record<string,string>={})=>fetch(url,{headers:{origin,authorization:`Bearer ${token}`,...headers}});
describe('private V9 availability HTTP boundary',()=>{
 it('hashes private bearer, passes only bounded window and returns authoritative slots',async()=>{const f=await fixture();const response=await get(f.url+query);expect(response.status).toBe(200);expect((await response.json()).data).toEqual(receipt);expect(f.read).toHaveBeenCalledExactlyOnceWith(tokenHash(token),origin,{from,to});expect(response.headers.get('cache-control')).toBe('no-store');expect(f.call).not.toHaveBeenCalled();expect(f.auth).not.toHaveBeenCalled();});
 it.each(['','?','?from='+from,'?from='+from+'&to='+to+'&tenantId='+id,query+'&from='+from,query+'&to='+to,query+'&serviceId='+id,query+'&price=1','?from=bad&to='+to,'?from='+to+'&to='+from,'?from=2030-01-01T00:00:00Z&to=2030-02-01T00:00:00Z'])('rejects invalid or authority-bearing query %s before dispatch',async suffix=>{const f=await fixture();expect((await get(f.url+suffix)).status).toBe(400);expect(f.read).not.toHaveBeenCalled();expect(f.call).not.toHaveBeenCalled();});
 it.each(['','Bearer forged','Bearer '+token+'=','Bearer '+('A'.repeat(42)+'B'),'Basic '+token])('rejects invalid bearer',async authorization=>{const f=await fixture();expect((await get(f.url+query,{authorization})).status).toBe(401);expect(f.read).not.toHaveBeenCalled();});
 it.each(['','null','*',origin+'/','https://foreign.example.test','https://portal.example.test'])('rejects unapproved origin',async candidate=>{const f=await fixture();expect((await get(f.url+query,{origin:candidate})).status).toBe(403);expect(f.read).not.toHaveBeenCalled();});
 it('rejects actual GET body bytes before reading',async()=>{const f=await fixture();const status=await new Promise<number|undefined>((resolve,reject)=>{const req=request(f.url+query,{method:'GET',headers:{origin,authorization:`Bearer ${token}`,'content-length':'2'}},res=>{res.resume();res.on('end',()=>resolve(res.statusCode));});req.on('error',reject);req.end('{}');});expect(status).toBe(400);expect(f.read).not.toHaveBeenCalled();});
 it('rejects other methods without financial or legacy dispatch',async()=>{const f=await fixture();expect((await fetch(f.url+query,{method:'POST',headers:{origin,authorization:`Bearer ${token}`}})).status).toBe(404);expect(f.read).not.toHaveBeenCalled();expect(f.call).not.toHaveBeenCalled();});
 it('keeps absent capability closed',async()=>{const f=await fixture(receipt,false);expect((await get(f.url+query)).status).toBe(422);expect(f.read).not.toHaveBeenCalled();});
 it.each([{...receipt,tenantId:id},{...receipt,sessionToken:token},{...receipt,schemaVersion:1},{...receipt,slots:[{...receipt.slots[0],remainingCapacity:0}]},{...receipt,slots:[{...receipt.slots[0],start:'2029-12-31T10:00:00.000Z',end:'2029-12-31T11:00:00.000Z'}]},{...receipt,slots:[{...receipt.slots[0],start:to,end:'2030-01-02T11:00:00.000Z'}]}])('rejects malformed/private/out-of-window projection',async value=>{const f=await fixture(value);const response=await get(f.url+query);expect(response.status).toBe(500);expect(JSON.stringify(await response.json())).not.toContain(token);expect(f.call).not.toHaveBeenCalled();});
 it.each([['FORBIDDEN',403],['NOT_AVAILABLE',404],['CONFLICT',409],['UNSUPPORTED_CONFIG',422]] as const)('maps resolver failure safely',async(code,status)=>{const f=await fixture(new FlowError(code));const response=await get(f.url+query);expect(response.status).toBe(status);expect(await response.json()).toEqual({ok:false,code});expect(f.call).not.toHaveBeenCalled();});
});
