import {afterEach,describe,expect,it,vi} from 'vitest';
import {createPaidJourneyCustomerFieldAvailabilityReader,PaidJourneyCustomerFieldAvailabilityQuery,PaidJourneyCustomerFieldAvailabilityReceipt} from './paid-journey-customer-field-availability';
const {compute}=vi.hoisted(()=>({compute:vi.fn()}));
vi.mock('./repository',async()=>({...await vi.importActual<typeof import('./repository')>('./repository'),readAvailabilitySlots:compute}));
const id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',other='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',origin='https://checkout.example.test';
const window={from:'2030-01-01T00:00:00Z',to:'2030-01-02T00:00:00Z'},computed={serviceId:id,durationMinutes:60,slots:[{start:'2030-01-01T10:00:00.000Z',end:'2030-01-01T11:00:00.000Z',remainingCapacity:1}]};
const scope=()=>({schemaVersion:2,tenantId:id,flowId:id,versionId:id,installationId:id,serviceId:id,publicationGeneration:2,expiresAt:new Date(Date.now()+600000).toISOString(),timezone:'UTC',durationMinutes:60});
function fixture(values:unknown[]=[scope()]){const statements:string[]=[],query=vi.fn(async(sql:string)=>{statements.push(sql);return {rows:sql.includes('availability_scope')?[{scope:values.length>1?values.shift():values[0]}]:[]};}),release=vi.fn(),client={query,release},connect=vi.fn(async()=>client);compute.mockResolvedValue(structuredClone(computed));return {reader:createPaidJourneyCustomerFieldAvailabilityReader({connect} as never,{configuredCustomerOrigins:[origin]},()=> '2030-01-01T00:00:00Z'),connect,query,release,statements,client};}
afterEach(()=>vi.clearAllMocks());
describe('private current V9 authoritative availability',()=>{
 it('uses only hashed session scope and existing capacity engine, returns immutable public aliases without private metadata',async()=>{const f=fixture(),result=await f.reader('a'.repeat(64),origin,window);expect(result).toEqual({schemaVersion:2,installationId:id,versionId:id,...computed});expect(compute).toHaveBeenCalledWith(f.client,id,id,{timezone:'UTC',duration_minutes:60},'2030-01-01T00:00:00.000Z','2030-01-02T00:00:00.000Z',expect.any(Function));expect(f.query.mock.calls.filter(([sql])=>sql.includes('availability_scope'))).toHaveLength(2);expect(f.statements).toContain('set local role service_role');expect(f.statements).toContain('commit');expect(f.statements.join(' ')).not.toMatch(/insert|update|delete|hold|confirm|payment/i);for(const value of [result,result.slots,result.slots[0]])expect(Object.isFrozen(value)).toBe(true);});
 it.each([{...window,tenantId:other},{...window,serviceId:other},{...window,price:1},{from:'2030-01-01T00:00:00Z',to:'2030-01-09T00:00:00Z'},{from:'2030-02-30T00:00:00Z',to:'2030-03-01T00:00:00Z'},{from:window.to,to:window.from}])('rejects query authority or invalid range before pool',async input=>{const f=fixture();await expect(f.reader('a'.repeat(64),origin,input)).rejects.toMatchObject({code:'INVALID_REQUEST'});expect(f.connect).not.toHaveBeenCalled();});
 it.each(['*',origin+'/', 'http://checkout.example.test'])('rejects invalid origin %s before pool',async o=>{const f=fixture();await expect(f.reader('a'.repeat(64),o,window)).rejects.toMatchObject({code:'INVALID_REQUEST'});expect(f.connect).not.toHaveBeenCalled();});
 it('rejects unapproved origin and malformed hash before pool',async()=>{const f=fixture();await expect(f.reader('a'.repeat(64),'https://foreign.example.test',window)).rejects.toMatchObject({code:'FORBIDDEN'});await expect(f.reader('rawtoken',origin,window)).rejects.toMatchObject({code:'INVALID_REQUEST'});expect(f.connect).not.toHaveBeenCalled();});
 it.each([{...computed,serviceId:other},{...computed,tenantId:id},{...computed,durationMinutes:30},{...computed,slots:[{...computed.slots[0],end:'2030-01-01T12:00:00.000Z'}]},{...computed,slots:[{...computed.slots[0],remainingCapacity:0}]},{...computed,slots:[{...computed.slots[0],start:'2029-12-31T10:00:00.000Z',end:'2029-12-31T11:00:00.000Z'}]}])('rejects invalid computed/public context without commit',async value=>{const f=fixture();compute.mockResolvedValue(value);await expect(f.reader('a'.repeat(64),origin,window)).rejects.toMatchObject({code:'INTERNAL_ERROR'});expect(f.statements).toContain('rollback');expect(f.statements).not.toContain('commit');});
 it.each([{...scope(),tenantId:'INVALID'},{...scope(),tokenHash:'private'},{...scope(),expiresAt:new Date(Date.now()-1).toISOString()},{...scope(),expiresAt:new Date(Date.now()+20*60000).toISOString()}])('rejects malformed private scope before capacity reads',async value=>{const f=fixture([value]);await expect(f.reader('a'.repeat(64),origin,window)).rejects.toMatchObject({code:'INTERNAL_ERROR'});expect(compute).not.toHaveBeenCalled();});
 it('rejects changed publication generation or tenant between reads before commit',async()=>{for(const change of [{publicationGeneration:3},{tenantId:other}]){const before=scope(),f=fixture([before,{...before,...change}]);await expect(f.reader('a'.repeat(64),origin,window)).rejects.toMatchObject({code:'CONFLICT'});expect(f.statements).not.toContain('commit');}});
 it('final expiry denial never leaks returned slots or extends sessions',async()=>{const f=fixture();let n=0;f.query.mockImplementation(async(sql:string)=>{f.statements.push(sql);if(sql.includes('availability_scope')&&++n===2)throw Object.assign(Error('private bearer'),{code:'42501'});return{rows:sql.includes('availability_scope')?[{scope:scope()}]:[]};});await expect(f.reader('a'.repeat(64),origin,window)).rejects.toMatchObject({code:'FORBIDDEN',message:'FORBIDDEN'});expect(f.statements).not.toContain('commit');});
 it('sanitizes connection and rollback failures, disposing broken clients',async()=>{const f=fixture();compute.mockRejectedValue(Error('private password'));f.query.mockImplementation(async(sql:string)=>{if(sql==='rollback')throw Error('private failure');return{rows:sql.includes('availability_scope')?[{scope:scope()}]:[]};});await expect(f.reader('a'.repeat(64),origin,window)).rejects.toMatchObject({code:'INTERNAL_ERROR',message:'INTERNAL_ERROR'});expect(f.release).toHaveBeenCalledWith(true);});
 it('schemas bound duplicate slots and preserve V8 schema exclusion',()=>{expect(PaidJourneyCustomerFieldAvailabilityQuery.safeParse({...window,origin}).success).toBe(false);expect(PaidJourneyCustomerFieldAvailabilityQuery.safeParse({...window,from:'2030-01-01T00:00:00.'+'0'.repeat(100)+'Z'}).success).toBe(false);expect(PaidJourneyCustomerFieldAvailabilityReceipt.safeParse({schemaVersion:1,installationId:id,versionId:id,...computed}).success).toBe(false);expect(PaidJourneyCustomerFieldAvailabilityReceipt.safeParse({schemaVersion:2,installationId:id,versionId:id,...computed,slots:[computed.slots[0],computed.slots[0]]}).success).toBe(false);});
});
