import {afterEach,describe,expect,it,vi} from 'vitest';
import type {Server} from 'node:http';
import type {Pool} from 'pg';
import {createFlowHttpServer} from './http';
import {createFlowRepository,FlowError} from './repository';
import {SavePaidJourneyDraft} from './paid-journey-draft';
const id=(n:number)=>`69000000-0000-4000-8000-${String(n).padStart(12,'0')}`,actor=id(1),tenant=id(2),service=id(3),flow=id(4),origin='https://portal.example.test';
const journey={schemaVersion:1,stages:['service','options','schedule','information','review_payment','confirmation'].map(kind=>({id:kind,kind,label:kind,enabled:true}))};
const body={schemaVersion:1,expectedRevision:0,serviceId:service,name:'Housekeeping',presentation:{accentColor:'#4f46e5',layout:'stacked'},journey};
const receipt={schemaVersion:1,tenantId:tenant,flowId:flow,revision:1},draft={...receipt,serviceId:service,name:body.name,presentation:body.presentation,journey};
let server:Server;afterEach(async()=>{server?.closeAllConnections();if(server)await new Promise<void>(r=>server.close(()=>r()));});
async function fixture(enabled=true,result?:unknown){const call=vi.fn(async(name:string)=>{if(result instanceof Error)throw result;return result??(name==='get_paid_journey_draft'?draft:receipt);});server=createFlowHttpServer({repository:{call},paidJourneyDrafts:enabled,authenticateOwner:async token=>token==='owner-token-123456'?actor:null,ownerOrigins:[origin],customerOrigins:['https://checkout.example.test']});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));return{call,request:(method='POST',value:unknown=body,query=`tenantId=${tenant}`,token='owner-token-123456',o=origin)=>fetch(`http://127.0.0.1:${(server.address() as {port:number}).port}/api/paid-journey-flows/${flow}/draft?${query}`,{method,headers:{authorization:`Bearer ${token}`,origin:o,'content-type':'application/json'},...(method==='GET'?{}:{body:JSON.stringify(value)})})};}
describe('versioned journey draft HTTP boundary',()=>{
 it('saves only verified actor-bound fields and reads an exact immutable draft contract',async()=>{const f=await fixture();const saved=await f.request();expect(saved.status).toBe(200);expect(await saved.json()).toEqual({ok:true,data:receipt});expect(f.call).toHaveBeenCalledWith('save_paid_journey_draft',[actor,tenant,flow,service,0,'Housekeeping',body.presentation,journey]);const read=await f.request('GET');expect(read.status).toBe(200);expect(read.headers.get('cache-control')).toBe('no-store');expect(read.headers.get('access-control-allow-origin')).toBe(origin);expect(await read.json()).toEqual({ok:true,data:draft});expect(f.call).toHaveBeenCalledWith('get_paid_journey_draft',[actor,tenant,flow]);});
 it.each([{actorId:id(99)},{tenantId:id(99)},{price:1},{paymentMode:'live'},{optionsRequired:false},{requiredInformationalStageIds:[]},{role:'BUSINESS_OWNER'}])('rejects owner authority injection %j',async extra=>{const f=await fixture();expect((await f.request('POST',{...body,...extra})).status).toBe(400);expect(f.call).not.toHaveBeenCalled();});
 it.each([{}, {...journey,schemaVersion:2},{...journey,price:1},{...journey,stages:journey.stages.slice(1)},{...journey,stages:journey.stages.map(s=>s.kind==='schedule'?{...s,enabled:false}:s)},{...journey,stages:[...journey.stages.slice(0,4),journey.stages[3],journey.stages[5]]}])('rejects malformed or bypassing journey %j',async invalid=>{const f=await fixture();expect((await f.request('POST',{...body,journey:invalid})).status).toBe(400);expect(f.call).not.toHaveBeenCalled();});
 it.each([-1,0.5,Number.MAX_SAFE_INTEGER])('rejects invalid CAS revision %s',async expectedRevision=>{const f=await fixture();expect((await f.request('POST',{...body,expectedRevision})).status).toBe(400);expect(f.call).not.toHaveBeenCalled();});
 it('keeps the new route opt-in without relying on legacy publication enablement',async()=>{const f=await fixture(false);expect((await f.request()).status).toBe(422);expect((await f.request('GET')).status).toBe(422);expect(f.call).not.toHaveBeenCalled();});
 it('denies invalid identity and non-owner origins before RPC calls',async()=>{const f=await fixture();expect((await f.request('POST',body,undefined,'bad-token-123456')).status).toBe(401);for(const bad of ['https://checkout.example.test','https://leadgate.example.test','https://portal.example.test.evil.test'])expect((await f.request('GET',body,undefined,undefined,bad)).status).toBe(403);expect(f.call).not.toHaveBeenCalled();});
 it.each(['',`tenantId=${tenant}&tenantId=${tenant}`,`tenantId=${tenant}&actorId=${actor}`])('rejects ambiguous or widened query %s',async query=>{const f=await fixture();expect((await f.request('POST',body,query)).status).toBe(400);expect(f.call).not.toHaveBeenCalled();});
 it.each(['PUT','DELETE','PATCH'])('rejects unsupported method %s without a writer',async method=>{const f=await fixture();expect((await f.request(method)).status).toBe(404);expect(f.call).not.toHaveBeenCalled();});
 it.each(['CONFLICT','FORBIDDEN','NOT_AVAILABLE','UNSUPPORTED_CONFIG'] as const)('uses safe existing errors %s',async code=>{const f=await fixture(true,new FlowError(code));const r=await f.request();expect(r.status).toBe({CONFLICT:409,FORBIDDEN:403,NOT_AVAILABLE:404,UNSUPPORTED_CONFIG:422}[code]);expect(await r.json()).toEqual({ok:false,code});});
 it.each([{...receipt,tenantId:id(99)},{...receipt,flowId:id(99)},{...receipt,revision:2},{...receipt,secret:'private'},{...receipt,schemaVersion:3}])('rejects mismatched or widened saved receipt %j',async invalid=>{const f=await fixture(true,invalid);const r=await f.request();expect(r.status).toBe(500);expect(await r.json()).toEqual({ok:false,code:'INTERNAL_ERROR'});});
 it.each([{...draft,tenantId:id(99)},{...draft,flowId:id(99)},{...draft,price:1},{...draft,name:'bad\ud800'}])('rejects unbound or invalid read evidence %j',async invalid=>{const f=await fixture(true,invalid);const r=await f.request('GET');expect(r.status).toBe(500);expect(await r.json()).toEqual({ok:false,code:'INTERNAL_ERROR'});});
 it('rejects incompatible text, exact design/schema fields and never normalizes published output',async()=>{const f=await fixture();for(const name of ['bad\ud800','bad\u0000'])expect((await f.request('POST',{...body,name})).status).toBe(400);expect(SavePaidJourneyDraft.parse({...body,name:'  Housekeeping  '}).name).toBe('Housekeeping');expect(SavePaidJourneyDraft.safeParse({...body,presentation:{...body.presentation,price:1}}).success).toBe(false);expect(SavePaidJourneyDraft.safeParse({...body,schemaVersion:3}).success).toBe(false);expect(f.call).not.toHaveBeenCalled();});
});
describe('fixed journey repository RPC validation',()=>{
 it.each(['save_paid_journey_draft','get_paid_journey_draft'] as const)('validates %s binding before committing',async name=>{
  const params=name==='save_paid_journey_draft'?[actor,tenant,flow,service,0,body.name,body.presentation,journey]:[actor,tenant,flow];
  const good=name==='save_paid_journey_draft'?receipt:draft;
  for(const result of [good,{...good,tenantId:id(99)},{...good,flowId:id(99)},...(name==='save_paid_journey_draft'?[{...good,revision:2}]:[])]){
   const release=vi.fn(),query=vi.fn(async(sql:string)=>sql.startsWith('select')?{rows:[{result}]}:{rows:[]}),repo=createFlowRepository({connect:async()=>({query,release})} as unknown as Pool);
   if(result===good){expect(await repo.call(name,params)).toEqual(good);expect(query).toHaveBeenLastCalledWith('commit');}else{await expect(repo.call(name,params)).rejects.toMatchObject({code:'INTERNAL_ERROR'});expect(query).toHaveBeenLastCalledWith('rollback');}
   expect(query.mock.calls[2]![0]).toContain(`public.${name}(`);expect(query.mock.calls[2]![0]).not.toContain(actor);expect(release).toHaveBeenCalledOnce();
  }
 });
 it.each([['40001','CONFLICT'],['23505','CONFLICT'],['42501','FORBIDDEN'],['0A000','UNSUPPORTED_CONFIG'],['22023','INVALID_REQUEST'],['P0002','NOT_AVAILABLE'],['XX999','INTERNAL_ERROR']])('maps SQL %s safely',async(code,expected)=>{const query=vi.fn(async(sql:string)=>{if(sql.startsWith('select'))throw Object.assign(Error('private database detail'),{code});return{rows:[]};});const repo=createFlowRepository({connect:async()=>({query,release:vi.fn()})} as unknown as Pool);await expect(repo.call('get_paid_journey_draft',[actor,tenant,flow])).rejects.toMatchObject({code:expected,message:expected});expect(query).toHaveBeenLastCalledWith('rollback');});
});
