import {afterEach,describe,expect,it,vi} from 'vitest';
import type {Server} from 'node:http';
import {createFlowHttpServer} from './http';
const actor='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',tenant='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',flow='cccccccc-cccc-4ccc-8ccc-cccccccccccc',service='dddddddd-dddd-4ddd-8ddd-dddddddddddd',origin='https://portal.example.test';
const form={name:'Cleaning with access notes',presentation:{accentColor:'#4f46e5',layout:'stacked'},journey:{schemaVersion:1,stages:['service','options','schedule','information','review_payment','confirmation'].map(kind=>({id:kind,kind,label:kind,enabled:kind!=='options'}))},customerFields:[{id:'custom_gate',kind:'text',label:'Gate access?',required:true,maxLength:20},{id:'custom_code',kind:'text',label:'Access instructions',required:true,maxLength:100,when:{fieldId:'custom_gate',equals:'yes'}}],fieldBindings:[{fieldId:'custom_gate',stageId:'information'},{fieldId:'custom_code',stageId:'information'}]};
const input={schemaVersion:2,serviceId:service,expectedRevision:0,form},receipt={schemaVersion:2,tenantId:tenant,flowId:flow,revision:1},draft={...receipt,serviceId:service,form};
let server:Server|undefined;
afterEach(async()=>{if(server){server.closeAllConnections();await new Promise<void>((resolve,reject)=>server!.close(error=>error?reject(error):resolve()));server=undefined;}});
async function fixture(readValue:unknown=draft,saveValue:unknown=receipt,enabled=true){const read=vi.fn(async()=>readValue as never),save=vi.fn(async()=>saveValue as never),call=vi.fn(),legacy=vi.fn();server=createFlowHttpServer({repository:{call},ownerOrigins:[origin],customerOrigins:['https://checkout.example.test'],authenticateOwner:async token=>token==='owner-token-123456'?actor:null,paidJourneyDrafts:enabled,paidJourneyCustomerFieldDraftRead:read,paidJourneyCustomerFieldDraftSave:save,paidJourneyRollback:legacy});await new Promise<void>(resolve=>server!.listen(0,'127.0.0.1',resolve));return{read,save,call,legacy,url:`http://127.0.0.1:${(server.address() as {port:number}).port}/api/paid-journey-customer-field-flows/${flow}/draft?tenantId=${tenant}`};}
const headers={origin,authorization:'Bearer owner-token-123456','content-type':'application/json'};
const get=(url:string,extra:Record<string,string>={})=>fetch(url,{headers:{...headers,...extra}});
const post=(url:string,body:unknown=input,extra:Record<string,string>={})=>fetch(url,{method:'POST',headers:{...headers,...extra},body:JSON.stringify(body)});
describe('dedicated ordered customer-field draft HTTP boundary',()=>{
 it('passes only authenticated context and strict informational form to dedicated operations',async()=>{const f=await fixture();expect((await get(f.url)).status).toBe(200);expect(f.read).toHaveBeenCalledExactlyOnceWith(actor,tenant,flow);expect((await post(f.url)).status).toBe(200);expect(f.save).toHaveBeenCalledExactlyOnceWith(actor,tenant,flow,input);expect(f.call).not.toHaveBeenCalled();expect(f.legacy).not.toHaveBeenCalled();});
 it('requires owner credentials and owner origins before any operation',async()=>{const f=await fixture();expect((await get(f.url,{authorization:''})).status).toBe(401);expect((await post(f.url,input,{authorization:'Bearer forged-token-123456'})).status).toBe(401);expect((await post(f.url,input,{origin:'https://checkout.example.test'})).status).toBe(403);expect(f.read).not.toHaveBeenCalled();expect(f.save).not.toHaveBeenCalled();});
 it('fails closed when dedicated authoring is disabled',async()=>{const f=await fixture(draft,receipt,false);expect((await get(f.url)).status).toBe(422);expect((await post(f.url)).status).toBe(422);expect(f.read).not.toHaveBeenCalled();expect(f.save).not.toHaveBeenCalled();});
 it('rejects duplicate or extra context parameters and unsupported methods',async()=>{const f=await fixture();expect((await post(f.url+'&tenantId='+actor)).status).toBe(400);expect((await get(f.url+'&retry=true')).status).toBe(400);expect((await fetch(f.url,{method:'DELETE',headers})).status).toBe(404);expect(f.read).not.toHaveBeenCalled();expect(f.save).not.toHaveBeenCalled();});
 it.each([{...input,tenantId:actor},{...input,actorId:actor},{...input,amount:1},{...input,schemaVersion:1},{...input,form:{...form,total:1}},{...input,form:{...form,fieldBindings:[]}},{...input,form:{...form,customerFields:[{...form.customerFields[0],id:'custom_payment_state'}]}}])('rejects authority or binding tampering before the writer',async body=>{const f=await fixture();expect((await post(f.url,body)).status).toBe(400);expect(f.save).not.toHaveBeenCalled();});
 it.each([{...draft,tenantId:actor},{...draft,flowId:actor},{...draft,secret:'must-not-return'},{...draft,form:{...form,fieldBindings:[]}}])('rejects malformed or foreign read results',async value=>{const f=await fixture(value);const r=await get(f.url);expect(r.status).toBe(500);expect(JSON.stringify(await r.json())).not.toContain('must-not-return');});
 it.each([{...receipt,tenantId:actor},{...receipt,flowId:actor},{...receipt,revision:2},{...receipt,secret:'must-not-return'}])('rejects malformed CAS receipts without retry',async value=>{const f=await fixture(draft,value);expect((await post(f.url)).status).toBe(500);expect(f.save).toHaveBeenCalledTimes(1);expect(f.call).not.toHaveBeenCalled();});
});
