import {afterEach,describe,expect,it,vi} from 'vitest';
import type {Server} from 'node:http';
import {request} from 'node:http';
import {createFlowHttpServer,tokenHash} from './http';
const installation='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',version='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',service='cccccccc-cccc-4ccc-8ccc-cccccccccccc',origin='https://checkout.example.test',ownerOrigin='https://portal.example.test';
const form={name:'Cleaning',presentation:{accentColor:'#0e7490',layout:'compact'},journey:{schemaVersion:1,stages:['service','options','schedule','information','review_payment','confirmation'].map(kind=>({id:kind,kind,label:kind,enabled:true}))},customerFields:[{id:'custom_gate',kind:'text',label:'Gate',required:false,maxLength:100}],fieldBindings:[{fieldId:'custom_gate',stageId:'information'}]};
const render={versionId:version,renderSchemaVersion:9,submissionMode:'paid_journey_customer_field_request',paymentMode:'staging_mock',simulated:true,service:{id:service,name:'Cleaning',durationMinutes:60,price:{amount:12500,currency:'USD'}},form};
const now=Date.now(),receipt={schemaVersion:2,installationId:installation,expiresAt:new Date(now+10*60000).toISOString(),render};
let server:Server|undefined;
afterEach(async()=>{if(server){server.closeAllConnections();await new Promise<void>((resolve,reject)=>server!.close(error=>error?reject(error):resolve()));server=undefined;}});
async function fixture(value:unknown=receipt,enabled=true){const issue=vi.fn(async()=>value),call=vi.fn(async()=>{throw Error('legacy forbidden');}),auth=vi.fn(async()=>null);server=createFlowHttpServer({ownerOrigins:[ownerOrigin],customerOrigins:[origin],authenticateOwner:auth,repository:{call} as never,now:()=>now,...(enabled?{paidJourneyCustomerFieldSessionIssue:issue as never}:{})});await new Promise<void>(resolve=>server!.listen(0,'127.0.0.1',resolve));return{issue,call,auth,url:`http://127.0.0.1:${(server.address() as {port:number}).port}/api/public/paid-journey-customer-field-installations/${installation}/sessions`};}
const post=(url:string,body:unknown={},extra:Record<string,string>={})=>fetch(url,{method:'POST',headers:{origin,'content-type':'application/json',...extra},body:JSON.stringify(body)});
describe('V9 presentation session HTTP boundary',()=>{
 it('creates distinct server tokens while passing only SHA256 hashes to the isolated issuer',async()=>{const f=await fixture();const first=await post(f.url),second=await post(f.url);expect(first.status).toBe(200);expect(second.status).toBe(200);const a=(await first.json()).data,b=(await second.json()).data;expect(a.sessionToken).toMatch(/^[A-Za-z0-9_-]{43}$/);expect(b.sessionToken).not.toBe(a.sessionToken);expect(f.issue).toHaveBeenNthCalledWith(1,installation,tokenHash(a.sessionToken),origin);expect(f.issue).toHaveBeenNthCalledWith(2,installation,tokenHash(b.sessionToken),origin);expect(Object.keys(a).sort()).toEqual(['schemaVersion','installationId','expiresAt','render','sessionToken'].sort());expect(first.headers.get('cache-control')).toBe('no-store');expect(f.call).not.toHaveBeenCalled();expect(f.auth).not.toHaveBeenCalled();});
 it.each([{tenantId:service},{sessionToken:'forged'},{tokenHash:'0'.repeat(64)},{amount:0},{answers:{}},{installationId:installation},[],null])('rejects supplied authority or customer data',async body=>{const f=await fixture();expect((await post(f.url,body)).status).toBe(400);expect(f.issue).not.toHaveBeenCalled();});
 it.each(['',ownerOrigin,'null',origin+'/','https://foreign.example.test'])('rejects invalid origin %s',async candidate=>{const f=await fixture();expect((await post(f.url,{}, {origin:candidate})).status).toBe(403);expect(f.issue).not.toHaveBeenCalled();});
 it('rejects query context, noncanonical identity and wrong methods',async()=>{const f=await fixture();expect((await post(f.url+'?tenantId='+service)).status).toBe(400);expect((await post(f.url.replace(installation,installation.toUpperCase()))).status).toBe(400);expect((await fetch(f.url,{headers:{origin}})).status).toBe(404);expect(f.issue).not.toHaveBeenCalled();expect(f.call).not.toHaveBeenCalled();});
 it('rejects raw bare-query POST bytes without a session write',async()=>{const f=await fixture();const status=await new Promise<number|undefined>((resolve,reject)=>{const req=request(f.url,{method:'POST',path:new URL(f.url).pathname+'?',headers:{origin,'content-type':'application/json','content-length':'2'}},res=>{res.resume();res.on('end',()=>resolve(res.statusCode));});req.on('error',reject);req.end('{}');});expect(status).toBe(400);expect(f.issue).not.toHaveBeenCalled();});
 it('keeps missing capability closed',async()=>{const f=await fixture(receipt,false);expect((await post(f.url)).status).toBe(422);expect(f.issue).not.toHaveBeenCalled();});
 it.each([{...receipt,installationId:version},{...receipt,schemaVersion:1},{...receipt,expiresAt:new Date(now).toISOString()},{...receipt,expiresAt:new Date(now+16*60000).toISOString()},{...receipt,tokenHash:'private'},{...receipt,render:{...render,paymentMode:'live'}}])('rejects mismatched or unsafe issuer receipt without another dispatch',async value=>{const f=await fixture(value);const response=await post(f.url);expect(response.status).toBe(500);expect(JSON.stringify(await response.json())).not.toContain('private');expect(f.issue).toHaveBeenCalledTimes(1);expect(f.call).not.toHaveBeenCalled();});
});
