import {describe,expect,it,vi} from 'vitest';
import {createPaidJourneyCustomerFieldMockPaymentWriter} from './paid-journey-customer-field-payment';
const id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',origin='https://checkout.example.test',hash='a'.repeat(64),env={BOOKING_LUMIN_ENV:'staging',BOOKING_LUMIN_FAKE_PAYMENTS:'1'};
const receipt={schemaVersion:2,versionId:id,installationId:id,serviceId:id,bookingId:id,paymentId:id,reference:'LMN-'+id.replaceAll('-','').toUpperCase(),state:'confirmed',replayed:false,provider:'staging_mock',simulated:true,realPayment:false,productionMoney:false,amount:12500,currency:'USD'};
function fixture(value:unknown=receipt){const query=vi.fn(async(sql:string)=>({rows:sql.includes('pay_paid_journey_customer_field_mock')?[{result:value}]:[]})),release=vi.fn(),connect=vi.fn(async()=>({query,release})),pool={connect};return{pool,query,release,connect,write:createPaidJourneyCustomerFieldMockPaymentWriter(pool as never,env,{configuredCustomerOrigins:[origin]})};}
describe('V9 simulated payment server boundary',()=>{
 it.each([false,true])('returns immutable truthful strict evidence replay=%s',async replayed=>{const f=fixture({...receipt,replayed}),result=await f.write(hash,origin);expect(result).toEqual({...receipt,replayed});expect(Object.isFrozen(result)).toBe(true);expect(f.query).toHaveBeenCalledWith('select public.pay_paid_journey_customer_field_mock($1,$2) result',[hash,origin]);expect(f.query.mock.calls.map(c=>c[0])).toEqual(['begin isolation level read committed',"set local statement_timeout='5s'","set local lock_timeout='3s'",'set local role service_role','select public.pay_paid_journey_customer_field_mock($1,$2) result','commit']);expect(f.release).toHaveBeenCalledWith(false);});
 it.each([{}, {BOOKING_LUMIN_ENV:'staging'}, {BOOKING_LUMIN_ENV:'production'}])('disabled test payment sends nothing',async flags=>{const f=fixture(),write=createPaidJourneyCustomerFieldMockPaymentWriter(f.pool as never,flags,{configuredCustomerOrigins:[origin]});await expect(write(hash,origin)).rejects.toMatchObject({code:'UNSUPPORTED_CONFIG'});expect(f.connect).not.toHaveBeenCalled();});
 it('refuses fake payment enabled outside staging',()=>{const f=fixture();expect(()=>createPaidJourneyCustomerFieldMockPaymentWriter(f.pool as never,{BOOKING_LUMIN_ENV:'production',BOOKING_LUMIN_FAKE_PAYMENTS:'1'},{configuredCustomerOrigins:[origin]})).toThrow('explicit staging');});
 it.each(['', 'A'.repeat(64),'a'.repeat(63),id,'tenant:'+hash])('rejects invalid hash before pool',async value=>{const f=fixture();await expect(f.write(value,origin)).rejects.toMatchObject({code:'INVALID_REQUEST'});expect(f.connect).not.toHaveBeenCalled();});
 it.each(['','*','null',origin+'/',origin+'/path','http://checkout.example.test'])('rejects malformed origin without pool',async value=>{const f=fixture();await expect(f.write(hash,value)).rejects.toMatchObject({code:'INVALID_REQUEST'});expect(f.connect).not.toHaveBeenCalled();});
 it('rejects well formed foreign origin before pool',async()=>{const f=fixture();await expect(f.write(hash,'https://foreign.example.test')).rejects.toMatchObject({code:'FORBIDDEN'});expect(f.connect).not.toHaveBeenCalled();});
 it.each([{...receipt,schemaVersion:1},{...receipt,realPayment:true},{...receipt,productionMoney:true},{...receipt,simulated:false},{...receipt,provider:'stripe'},{...receipt,amount:0},{...receipt,amount:-1},{...receipt,amount:Number.MAX_SAFE_INTEGER+1},{...receipt,amount:1.5},{...receipt,currency:'usd'},{...receipt,reference:'fake'},{...receipt,tenantId:id},{...receipt,sessionToken:'private'},{...receipt,state:'draft'}])('rejects incompatible financial/privacy evidence atomically',async value=>{const f=fixture(value);await expect(f.write(hash,origin)).rejects.toMatchObject({code:'INTERNAL_ERROR'});expect(f.query).toHaveBeenCalledWith('rollback');expect(f.query).not.toHaveBeenCalledWith('commit');});
 it.each([['42501','FORBIDDEN'],['P0002','NOT_AVAILABLE'],['0A000','UNSUPPORTED_CONFIG'],['40001','CONFLICT'],['40P01','CONFLICT'],['55P03','CONFLICT'],['57014','CONFLICT'],['22023','CONFLICT'],['23505','CONFLICT'],['23P01','CONFLICT'],['private','INTERNAL_ERROR']])('sanitizes SQL failure %s and never retries',async(code,expected)=>{const f=fixture();f.query.mockImplementation(async(sql:string)=>{if(sql.includes('pay_paid_journey_customer_field_mock'))throw Object.assign(Error('private connection sentinel'),{code});return{rows:[]};});await expect(f.write(hash,origin)).rejects.toMatchObject({code:expected,message:expected});expect(f.connect).toHaveBeenCalledOnce();expect(f.query.mock.calls.filter(c=>c[0].includes('pay_paid_journey_customer_field_mock'))).toHaveLength(1);});
 it('sanitizes connection failure',async()=>{const f=fixture();f.connect.mockRejectedValueOnce(Error('private secret'));await expect(f.write(hash,origin)).rejects.toMatchObject({code:'INTERNAL_ERROR',message:'INTERNAL_ERROR'});});
 it('marks client broken after rollback fails',async()=>{const f=fixture({});f.query.mockImplementation(async sql=>{if(sql==='rollback')throw Error('broken');return{rows:sql.includes('pay_paid_journey_customer_field_mock')?[{result:{}}]:[]};});await expect(f.write(hash,origin)).rejects.toMatchObject({code:'INTERNAL_ERROR'});expect(f.release).toHaveBeenCalledWith(true);});
});