import {afterEach,describe,expect,it,vi} from 'vitest';
import {request,type Server} from 'node:http';
import {createFlowHttpServer,tokenHash} from './http';
import {FlowError} from './repository';
import {createPaidJourneyAvailabilityReader,PaidJourneyAvailabilityQuery,PaidJourneyAvailabilityReceipt} from './paid-journey-availability';
const origin='https://checkout.example.test',token='a'.repeat(43),service='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
const receipt={schemaVersion:1 as const,serviceId:service,durationMinutes:60,slots:[{start:'2030-01-01T10:00:00.000Z',end:'2030-01-01T11:00:00.000Z',remainingCapacity:1}]};
const query='?from=2030-01-01T00:00:00Z&to=2030-01-02T00:00:00Z';
describe('dedicated V8 availability',()=>{
 let server:Server;afterEach(async()=>{if(server){server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));}});
 async function fixture(value:unknown=receipt,enabled=true){const read=vi.fn(async()=>value as any),owner=vi.fn(async()=>null),call=vi.fn(async()=>{throw Error('unexpected RPC writer');});server=createFlowHttpServer({repository:{call},ownerOrigins:['https://portal.example.test'],customerOrigins:[origin],authenticateOwner:owner,paidJourneySessions:enabled,paidJourneyAvailability:read});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));return{read,owner,call,url:`http://127.0.0.1:${(server.address() as {port:number}).port}/api/paid-journey-flow-sessions/availability`};}
 it('hashes only customer bearer, exact actual origin and normalized bounded range; no owner or writers',async()=>{const f=await fixture();const r=await fetch(f.url+query,{headers:{origin,authorization:`Bearer ${token}`}});expect(r.status).toBe(200);expect(r.headers.get('cache-control')).toBe('no-store');expect(r.headers.get('x-request-id')).toBeTruthy();expect(await r.json()).toEqual({ok:true,data:receipt});expect(f.read).toHaveBeenCalledWith(tokenHash(token),origin,{from:'2030-01-01T00:00:00.000Z',to:'2030-01-02T00:00:00.000Z'});expect(f.owner).not.toHaveBeenCalled();expect(f.call).not.toHaveBeenCalled();});
 it.each(['&tenantId=x','&serviceId=x','&price=1','&origin=x','&actorId=x','&from=2030-01-01T00:00:00Z'])('rejects client scope/authority query %s',async extra=>{const f=await fixture();expect((await fetch(f.url+query+extra,{headers:{origin,authorization:`Bearer ${token}`}})).status).toBe(400);expect(f.read).not.toHaveBeenCalled();});
 it.each(['?from=2030-01-01T00:00:00Z&to=2030-01-09T00:00:00Z','?from=2030-01-02T00:00:00Z&to=2030-01-01T00:00:00Z','?from=2030-02-30T00:00:00Z&to=2030-03-01T00:00:00Z','?from=infinity&to=infinity','?from=2030-01-01T00:00:00Z'])('rejects invalid bounded datewindow %s',async suffix=>{const f=await fixture();expect((await fetch(f.url+suffix,{headers:{origin,authorization:`Bearer ${token}`}})).status).toBe(400);expect(f.read).not.toHaveBeenCalled();});
 it('fails closed by default, missing bearer, forged origin and wrong method',async()=>{const f=await fixture(undefined,false);expect((await fetch(f.url+query,{headers:{origin,authorization:`Bearer ${token}`}})).status).toBe(422);expect(f.read).not.toHaveBeenCalled();});
 it('rejects owner origin, missing/invalid token and wrong method',async()=>{const f=await fixture();for(const headers of [{origin},{origin,authorization:'Bearer weak'},{origin:'https://portal.example.test',authorization:`Bearer ${token}`}] as Record<string,string>[])expect((await fetch(f.url+query,{headers})).status).toBe(headers.origin===origin?401:403);expect((await fetch(f.url+query,{method:'POST',headers:{origin,authorization:`Bearer ${token}`},body:'{}'})).status).toBe(400);expect(f.read).not.toHaveBeenCalled();});
 it('rejects a body-bearing GET before resolving any customer scope',async()=>{const f=await fixture();const status=await new Promise<number>((resolve,reject)=>{const r=request(f.url+query,{method:'GET',headers:{origin,authorization:`Bearer ${token}`,'content-length':'2'}},response=>{response.resume();response.on('end',()=>resolve(response.statusCode!));});r.on('error',reject);r.end('{}');});expect(status).toBe(400);expect(f.read).not.toHaveBeenCalled();});
 it.each([{...receipt,tenantId:service},{...receipt,price:1},{...receipt,slots:[{...receipt.slots[0],tokenHash:'private'}]},{...receipt,slots:[{...receipt.slots[0],end:'2030-01-01T12:00:00.000Z'}]},{...receipt,slots:[{...receipt.slots[0],remainingCapacity:0}]},{...receipt,slots:[{...receipt.slots[0],start:'2029-12-31T10:00:00.000Z',end:'2029-12-31T11:00:00.000Z'}]}])('rejects malformed/private/unbounded result',async bad=>{const f=await fixture(bad);expect((await fetch(f.url+query,{headers:{origin,authorization:`Bearer ${token}`}})).status).toBe(500);});
 it('transaction rejects expiry at final resolution before commit',async()=>{let checks=0;const statements:string[]=[];const c={query:async(sql:string)=>{statements.push(sql);if(sql.includes('paid_journey_availability_scope')){if(++checks===2)throw Object.assign(Error('private'),{code:'42501'});return{rows:[{scope:{tenantId:service,serviceId:service,timezone:'UTC',durationMinutes:60}}]};}return{rows:[]};},release:vi.fn()};await expect(createPaidJourneyAvailabilityReader({connect:async()=>c} as never,()=> '2030-01-01T00:00:00Z')('a'.repeat(64),origin,{from:'2030-01-01T00:00:00Z',to:'2030-01-02T00:00:00Z'})).rejects.toMatchObject({code:'FORBIDDEN',message:'FORBIDDEN'});expect(statements).toContain('rollback');expect(statements).not.toContain('commit');});
 it('schemas reject duplicates and unsafe private scope before database use',async()=>{expect(PaidJourneyAvailabilityReceipt.safeParse({...receipt,slots:[receipt.slots[0],receipt.slots[0]]}).success).toBe(false);expect(PaidJourneyAvailabilityQuery.safeParse({from:'2030-01-01T00:00:00Z',to:'2030-01-02T00:00:00Z',tenantId:service}).success).toBe(false);const connect=vi.fn();await expect(createPaidJourneyAvailabilityReader({connect} as never)('bad',origin,{from:'x',to:'y'})).rejects.toMatchObject({code:'INVALID_REQUEST'});expect(connect).not.toHaveBeenCalled();});
});
