import {afterEach,describe,expect,it,vi} from 'vitest';
import {request,type Server} from 'node:http';
import {createFlowHttpServer,tokenHash} from './http';
import {FlowError} from './repository';
const id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',origin='https://checkout.example.test',token=Buffer.alloc(32,19).toString('base64url');
const receipt={schemaVersion:2,installationId:id,versionId:id,serviceId:id,bookingId:id,paymentId:id,reference:'LMN-AAAAAAAAAAAA4AAA8AAAAAAAAAAAAAAA',state:'confirmed',provider:'staging_mock',simulated:true,realPayment:false,productionMoney:false,amount:12500,currency:'USD',replayed:false};
let server:Server|undefined;
afterEach(async()=>{if(server){server.closeAllConnections();await new Promise<void>((resolve,reject)=>server!.close(error=>error?reject(error):resolve()));server=undefined;}});
async function fixture(value:unknown=receipt,enabled=true){const write=vi.fn(async()=>{if(value instanceof Error)throw value;return value;}),call=vi.fn(async()=>{throw Error('legacy forbidden');}),auth=vi.fn(async()=>null),legacyHold=vi.fn(),legacyPay=vi.fn();server=createFlowHttpServer({ownerOrigins:['https://portal.example.test'],customerOrigins:[origin],authenticateOwner:auth,repository:{call} as never,paidJourneySessions:true,paidJourneyHold:legacyHold as never,paidJourneyMockPayment:legacyPay as never,...(enabled?{paidJourneyCustomerFieldMockPayment:write as never}:{})});await new Promise<void>(resolve=>server!.listen(0,'127.0.0.1',resolve));return{write,call,auth,legacyHold,legacyPay,url:'http://127.0.0.1:'+(server.address() as {port:number}).port+'/api/public/paid-journey-customer-field-flow-sessions/mock-payment'};}
const post=(url:string,body:unknown={},headers:Record<string,string>={})=>fetch(url,{method:'POST',headers:{origin,authorization:'Bearer '+token,'content-type':'application/json',...headers},body:JSON.stringify(body)});
function noFallback(f:Awaited<ReturnType<typeof fixture>>){expect(f.call).not.toHaveBeenCalled();expect(f.auth).not.toHaveBeenCalled();expect(f.legacyHold).not.toHaveBeenCalled();expect(f.legacyPay).not.toHaveBeenCalled();}
function untouched(f:Awaited<ReturnType<typeof fixture>>){expect(f.write).not.toHaveBeenCalled();noFallback(f);}
describe('conditional customer-field staging mock-payment HTTP authority',()=>{
 it.each([false,true])('passes only canonical bearer hash and exact origin, replay=%s',async replayed=>{const f=await fixture({...receipt,replayed});const response=await post(f.url);expect(response.status).toBe(200);expect(await response.json()).toEqual({ok:true,data:{...receipt,replayed}});expect(f.write).toHaveBeenCalledExactlyOnceWith(tokenHash(token),origin);expect(response.headers.get('cache-control')).toBe('no-store');expect(response.headers.get('access-control-allow-origin')).toBe(origin);noFallback(f);});
 it.each(['?','?tenantId='+id,'?bookingId='+id,'?price=1'])('denies all query authority %s',async query=>{const f=await fixture();const status=query==='?'?await new Promise<number|undefined>((resolve,reject)=>{const req=request(f.url,{method:'POST',path:new URL(f.url).pathname+'?',headers:{origin,authorization:'Bearer '+token,'content-type':'application/json'}},res=>{res.resume();res.on('end',()=>resolve(res.statusCode));});req.on('error',reject);req.end('{}');}):(await post(f.url+query)).status;expect(status).toBe(400);untouched(f);});
 it.each(['','Bearer forged','Bearer '+token+'=','Bearer '+('A'.repeat(42)+'B'),'Basic '+token])('denies noncanonical bearer %s',async authorization=>{const f=await fixture();expect((await post(f.url,{}, {authorization})).status).toBe(401);untouched(f);});
 it.each(['','null','*',origin+'/','https://foreign.example.test','https://portal.example.test'])('denies foreign origins %s',async candidate=>{const f=await fixture();expect((await post(f.url,{}, {origin:candidate})).status).toBe(403);untouched(f);});
 it.each(['GET','PUT','DELETE','PATCH'])('denies non-POST %s',async method=>{const f=await fixture();expect((await fetch(f.url,{method,headers:{origin,authorization:'Bearer '+token}})).status).toBe(404);untouched(f);});
 it.each(['tenantId','serviceId','price','amount','currency','paymentId','bookingId','confirmed','role','customer','answers','idempotencyKey'])('denies client authority %s',async key=>{const f=await fixture();expect((await post(f.url,{[key]:id})).status).toBe(400);untouched(f);});
 it.each([null,[],1,'payment'])('denies non-object bodies',async body=>{const f=await fixture();expect((await post(f.url,body)).status).toBe(400);untouched(f);});
 it.each(['text/plain','application/x-www-form-urlencoded'])('denies non-json content %s',async contentType=>{const f=await fixture();expect((await post(f.url,{}, {'content-type':contentType})).status).toBe(400);untouched(f);});
 it('disabled writer cannot fall back to legacy confirmation',async()=>{const f=await fixture(receipt,false);expect((await post(f.url)).status).toBe(422);untouched(f);});
 it.each([{...receipt,realPayment:true},{...receipt,productionMoney:true},{...receipt,provider:'stripe'},{...receipt,simulated:false},{...receipt,amount:-1},{...receipt,amount:1.5},{...receipt,currency:'usd'},{...receipt,state:'draft'},{...receipt,reference:'LMN-OTHER'},{...receipt,customerEmail:'private@example.test'},{...receipt,token},{...receipt,schemaVersion:1}])('rejects forged financial/provider/private receipt',async value=>{const f=await fixture(value);const response=await post(f.url);expect(response.status).toBe(500);expect(await response.json()).toEqual({ok:false,code:'INTERNAL_ERROR'});expect(f.write).toHaveBeenCalledOnce();noFallback(f);});
 it.each([['FORBIDDEN',403],['CONFLICT',409],['NOT_AVAILABLE',404],['UNSUPPORTED_CONFIG',422]] as const)('preserves deterministic failure %s without exposing private errors',async(code,status)=>{const f=await fixture(new FlowError(code));const response=await post(f.url);expect(response.status).toBe(status);expect(await response.json()).toEqual({ok:false,code});noFallback(f);});
 it('does not reflect internal database credentials or messages',async()=>{const f=await fixture(new Error('private-db-password-canary'));const response=await post(f.url);expect(response.status).toBe(500);expect(await response.text()).not.toContain('canary');noFallback(f);});
});