import {describe,expect,it,vi} from 'vitest';
import {createPaidJourneyCustomerFieldPublicReader} from './paid-journey-customer-field-public-reader';
const installation='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',version='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',service='cccccccc-cccc-4ccc-8ccc-cccccccccccc',origin='https://checkout.example.test';
const form={name:'Cleaning',presentation:{accentColor:'#0e7490',layout:'compact'},journey:{schemaVersion:1,stages:['service','options','schedule','information','review_payment','confirmation'].map(kind=>({id:kind,kind,label:kind,enabled:kind!=='options'}))},customerFields:[{id:'custom_gate',kind:'text',label:'Gate',required:false,maxLength:100}],fieldBindings:[{fieldId:'custom_gate',stageId:'information'}]};
const render={versionId:version,renderSchemaVersion:9,submissionMode:'paid_journey_customer_field_request',paymentMode:'staging_mock',simulated:true,service:{id:service,name:'Cleaning',durationMinutes:60,price:{amount:12500,currency:'USD'}},form};
function db(result:unknown=render,code?:string){const statements:string[]=[];const client={query:vi.fn(async(sql:string)=>{statements.push(sql);if(sql.includes('get_paid_journey_customer_field_render')){if(code)throw Object.assign(Error('private connection data'),{code});return{rows:[{result}]};}return{rows:[]};}),release:vi.fn()};return{pool:{connect:async()=>client} as never,client,statements};}
describe('V9 immutable public reader',()=>{
 it('uses a single narrow service-role read RPC and returns immutable published price',async()=>{const f=db();const value=await createPaidJourneyCustomerFieldPublicReader(f.pool,[origin])(installation,origin);expect(value).toEqual(render);expect(f.statements).toEqual(['begin',"set local statement_timeout='5s'","set local lock_timeout='3s'",'set local role service_role','select public.get_paid_journey_customer_field_render($1::uuid,$2::text) result','commit']);expect(f.client.query).toHaveBeenCalledWith('select public.get_paid_journey_customer_field_render($1::uuid,$2::text) result',[installation,origin]);expect(f.client.release).toHaveBeenCalledWith(false);});
 it.each(['*',origin+'/',origin+'.evil.test','https://foreign.example.test','http://checkout.example.test'])('rejects malformed or unconfigured origin %s before connecting',async candidate=>{const connect=vi.fn();await expect(createPaidJourneyCustomerFieldPublicReader({connect} as never,[origin])(installation,candidate)).rejects.toBeInstanceOf(Error);expect(connect).not.toHaveBeenCalled();});
 it.each(['not-uuid',installation.toUpperCase()])('rejects noncanonical installation %s',async candidate=>{const connect=vi.fn();await expect(createPaidJourneyCustomerFieldPublicReader({connect} as never,[origin])(candidate,origin)).rejects.toMatchObject({code:'INVALID_REQUEST'});expect(connect).not.toHaveBeenCalled();});
 it.each([{...render,renderSchemaVersion:8},{...render,secret:'private'},{...render,paymentMode:'live'},{...render,service:{...render.service,price:{amount:-1,currency:'USD'}}}])('rejects malformed V9 render before commit',async value=>{const f=db(value);await expect(createPaidJourneyCustomerFieldPublicReader(f.pool,[origin])(installation,origin)).rejects.toMatchObject({code:'INTERNAL_ERROR'});expect(f.statements.at(-1)).toBe('rollback');expect(f.statements).not.toContain('commit');});
 it.each([['P0002','NOT_AVAILABLE'],['42501','FORBIDDEN'],['0A000','UNSUPPORTED_CONFIG'],['55P03','CONFLICT'],['22023','INVALID_REQUEST'],['unknown','INTERNAL_ERROR']])('maps database failure %s without leaking data',async(code,expected)=>{const f=db(undefined,code);await expect(createPaidJourneyCustomerFieldPublicReader(f.pool,[origin])(installation,origin)).rejects.toMatchObject({code:expected,message:expected});expect(f.statements.at(-1)).toBe('rollback');});
 it('discards a client if rollback fails',async()=>{const f=db({...render,secret:'private'});const original=f.client.query.getMockImplementation()!;f.client.query.mockImplementation(async(sql:string)=>{if(sql==='rollback')throw Error('private rollback');return original(sql);});await expect(createPaidJourneyCustomerFieldPublicReader(f.pool,[origin])(installation,origin)).rejects.toMatchObject({code:'INTERNAL_ERROR'});expect(f.client.release).toHaveBeenCalledWith(true);});
 it('validates configured origins at construction',()=>{expect(()=>createPaidJourneyCustomerFieldPublicReader(db().pool,['*'])).toThrow();expect(()=>createPaidJourneyCustomerFieldPublicReader(db().pool,[origin,origin])).toThrow();});
});
