import {request as rawRequest} from 'node:http';
import {afterEach,describe,expect,it,vi} from 'vitest';
import type {Server} from 'node:http';
import type {Pool} from 'pg';
import {createFlowHttpServer} from './http';
import {createFlowRepository,FlowError} from './repository';
const id=(n:number)=>`71000000-0000-4000-8000-${String(n).padStart(12,'0')}`,actor=id(1),tenant=id(2),flow=id(4),owner='https://portal.example.test',customer='https://checkout.example.test';
const body={schemaVersion:1,expectedDraftRevision:1,allowedOrigins:[customer]};
const render={versionId:id(5),renderSchemaVersion:8,submissionMode:'paid_journey_request',paymentMode:'staging_mock',simulated:true,service:{id:id(3),name:'Cleaning',durationMinutes:60,price:{amount:12500,currency:'USD'}},form:{name:'Journey',presentation:{accentColor:'#4f46e5',layout:'stacked'},journey:{schemaVersion:1,stages:['service','options','schedule','information','review_payment','confirmation'].map(kind=>({id:kind,kind,label:kind,enabled:kind!=='options'}))}}};
let server:Server;afterEach(async()=>{server?.closeAllConnections();if(server)await new Promise<void>(r=>server.close(()=>r()));});
async function fixture(enabled=true,mutate?:(v:any)=>any){const call=vi.fn(async(name:string,params:readonly unknown[])=>{const v=name==='get_paid_journey_render'?render:{schemaVersion:1,tenantId:tenant,flowId:flow,draftRevision:1,versionId:params[4],installationId:params[5],renderSchemaVersion:8,replayed:false};return mutate?mutate(v):v;});server=createFlowHttpServer({repository:{call},paidJourneyPublication:enabled,ownerOrigins:[owner],customerOrigins:[customer],authenticateOwner:async token=>token==='owner-token-123456'?actor:null});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${(server.address() as {port:number}).port}`;return{call,publish:(value:unknown=body,method='POST',query=`tenantId=${tenant}`,origin=owner,token='owner-token-123456')=>fetch(`${base}/api/paid-journey-flows/${flow}/publish-draft?${query}`,{method,headers:{origin,authorization:`Bearer ${token}`,'content-type':'application/json'},...(method==='GET'?{}:{body:JSON.stringify(value)})}),read:(path='',origin=customer,method='GET')=>fetch(`${base}/api/paid-journey-installations/${id(6)}/render${path}`,{method,headers:{origin}})};}
describe('V8 publication and independent read HTTP boundary',()=>{
 it('uses verified actor and server origins, random IDs, exact no-store receipt without hosted capability claims',async()=>{const f=await fixture();const r=await f.publish();expect(r.status).toBe(200);expect(r.headers.get('cache-control')).toBe('no-store');const v=(await r.json()).data;expect(v).toMatchObject({schemaVersion:1,tenantId:tenant,flowId:flow,draftRevision:1,renderSchemaVersion:8,replayed:false});expect(v.hostedPath).toBeUndefined();expect(f.call).toHaveBeenCalledWith('publish_paid_journey_draft',[actor,tenant,flow,1,v.versionId,v.installationId,[customer],[customer]]);});
 it('returns only strict immutable V8 snapshot to exact customer origin without owner auth',async()=>{const f=await fixture();const r=await f.read();expect(r.status).toBe(200);expect(r.headers.get('access-control-allow-origin')).toBe(customer);expect(r.headers.get('cache-control')).toBe('no-store');expect(await r.json()).toEqual({ok:true,data:render});expect(f.call).toHaveBeenCalledWith('get_paid_journey_render',[id(6),customer]);});
 it('default-disabled gates make no RPC',async()=>{const f=await fixture(false);expect((await f.publish()).status).toBe(422);expect((await f.read()).status).toBe(422);expect(f.call).not.toHaveBeenCalled();});
 it.each([{actorId:id(99)},{tenantId:id(99)},{approvedOrigins:[customer]},{price:1},{paymentMode:'live'},{replayed:true},{expectedDraftRevision:0},{expectedDraftRevision:1.5},{schemaVersion:8},{allowedOrigins:[customer,customer]},{allowedOrigins:['*']}])('rejects malformed/forged owner input %j',async extra=>{const f=await fixture();expect((await f.publish({...body,...extra})).status).toBe(400);expect(f.call).not.toHaveBeenCalled();});
 it('rejects unapproved origins/credentials and never uses owner data as customer origin',async()=>{const f=await fixture();expect((await f.publish({...body,allowedOrigins:['https://foreign.example.test']})).status).toBe(403);expect((await f.publish(body,'POST',undefined,customer)).status).toBe(403);expect((await f.publish(body,'POST',undefined,undefined,'invalid-token-123456')).status).toBe(401);for(const o of [owner,'https://leadgate.example.test','https://checkout.example.test.evil'])expect((await f.read('',o)).status).toBe(403);expect(f.call).not.toHaveBeenCalled();});
 it.each(['',`tenantId=${tenant}&tenantId=${tenant}`,`tenantId=${tenant}&actorId=${actor}`])('rejects widened owner query %s',async query=>{const f=await fixture();expect((await f.publish(body,'POST',query)).status).toBe(400);expect(f.call).not.toHaveBeenCalled();});
 it.each(['?tenantId=x','?origin=https://checkout.example.test'])('rejects reader query overrides %s',async query=>{const f=await fixture();expect((await f.read(query)).status).toBe(400);expect(f.call).not.toHaveBeenCalled();});
 it('rejects body-bearing read before RPC',async()=>{const f=await fixture();const result=await new Promise<number>((resolve,reject)=>{const req=rawRequest({host:'127.0.0.1',port:(server.address() as {port:number}).port,path:`/api/paid-journey-installations/${id(6)}/render`,method:'GET',headers:{origin:customer,'content-length':'2'}},res=>{res.resume();res.on('end',()=>resolve(res.statusCode!));});req.on('error',reject);req.end('{}');});expect(result).toBe(400);expect(f.call).not.toHaveBeenCalled();});
 it('rejects wrong methods without writers',async()=>{const f=await fixture();expect((await f.publish(body,'GET')).status).toBe(404);expect((await f.read('',customer,'POST')).status).toBe(404);expect(f.call).not.toHaveBeenCalled();});
 it.each([{tenantId:id(99)},{flowId:id(99)},{draftRevision:2},{versionId:id(99)},{installationId:id(99)},{renderSchemaVersion:7},{secret:'private'}])('rejects mismatched publication receipt %j',async bad=>{const f=await fixture(true,v=>({...v,...bad}));expect((await f.publish()).status).toBe(500);});
 it('valid replay returns original IDs without granting retry authority',async()=>{const f=await fixture(true,v=>({...v,replayed:true,versionId:id(5),installationId:id(6)}));const r=await f.publish();expect(r.status).toBe(200);expect((await r.json()).data).toMatchObject({replayed:true,versionId:id(5),installationId:id(6)});});
 it.each([{tenantId:tenant},{actorId:actor},{draftRevision:1},{renderSchemaVersion:7},{service:{...render.service,price:{amount:-1,currency:'USD'}}}])('rejects widened/malformed public snapshot %j',async bad=>{const f=await fixture(true,v=>({...v,...bad}));const r=await f.read();expect(r.status).toBe(500);expect(await r.json()).toEqual({ok:false,code:'INTERNAL_ERROR'});});
});
describe('fixed V8 repository RPC',()=>{
 it('binds receipt before committing, including tenant and generated IDs',async()=>{const params=[actor,tenant,flow,1,id(5),id(6),[customer],[customer]];for(const bad of [null,{tenantId:id(99)},{flowId:id(99)},{draftRevision:2},{installationId:id(99)},{versionId:id(99)}]){const result={schemaVersion:1,tenantId:tenant,flowId:flow,draftRevision:1,versionId:id(5),installationId:id(6),renderSchemaVersion:8,replayed:false,...bad};const query=vi.fn(async(sql:string)=>sql.startsWith('select')?{rows:[{result}]}:{rows:[]});const repo=createFlowRepository({connect:async()=>({query,release:vi.fn()})} as unknown as Pool);if(bad===null){expect(await repo.call('publish_paid_journey_draft',params)).toEqual(result);expect(query).toHaveBeenLastCalledWith('commit');}else{await expect(repo.call('publish_paid_journey_draft',params)).rejects.toMatchObject({code:'INTERNAL_ERROR'});expect(query).toHaveBeenLastCalledWith('rollback');}expect(query.mock.calls.find(c=>c[0].startsWith('select'))![0]).toBe('select public.publish_paid_journey_draft($1::uuid,$2::uuid,$3::uuid,$4::bigint,$5::uuid,$6::uuid,$7::jsonb,$8::jsonb) as result');}});
 it.each([['40001','CONFLICT'],['55P03','CONFLICT'],['40P01','CONFLICT'],['57014','CONFLICT'],['42501','FORBIDDEN'],['0A000','UNSUPPORTED_CONFIG'],['P0002','NOT_AVAILABLE'],['XX999','INTERNAL_ERROR']])('maps SQL %s safely',async(code,expected)=>{const query=vi.fn(async(sql:string)=>{if(sql.startsWith('select'))throw Object.assign(Error('private connection'),{code});return{rows:[]};});const repo=createFlowRepository({connect:async()=>({query,release:vi.fn()})} as unknown as Pool);await expect(repo.call('publish_paid_journey_draft',[actor,tenant,flow,1,id(5),id(6),[customer],[customer]])).rejects.toMatchObject({code:expected,message:expected});expect(query).toHaveBeenLastCalledWith('rollback');});
});
