import assert from 'node:assert/strict';
import {isIP} from 'node:net';
import {Pool} from 'pg';
import {createPaidJourneyCustomerFieldHoldWriter} from './paid-journey-customer-field-hold';
import {createPaidJourneyCustomerFieldSessionIssuer} from './paid-journey-customer-field-session';
import {createPaidJourneyCustomerFieldDraftOperations} from './paid-journey-customer-field-draft';
import {createPaidJourneyCustomerFieldPublicationOperations} from './paid-journey-customer-field-publication';
import {createPaidJourneyCustomerFieldMockPaymentWriter} from './paid-journey-customer-field-payment';
import {createPaidJourneyMockPaymentWriter} from './paid-journey-payment';
import {createMockPaymentWriter} from './mock-payment';
assert.equal(process.env.PAID_JOURNEY_CUSTOMER_FIELD_PAYMENT_LOCAL_TEST,'1');assert.equal(process.env.PGHOST,'127.0.0.1');assert.equal(process.env.PGUSER,'postgres');
let host='127.0.0.1';if(process.env.CI==='true'){assert.equal(process.env.GITHUB_ACTIONS,'true');assert.equal(process.env.PGPORT,'5432');assert.equal(process.env.PGDATABASE,'lumin_journey_fields_payment_ci');host=process.env.PAID_JOURNEY_CUSTOMER_FIELD_PAYMENT_CI_DATABASE_HOST??'';assert.equal(isIP(host),4);assert.match(host,/^(?:10\.|172\.(?:1[6-9]|2[0-9]|3[01])\.|192\.168\.)/);}else{assert.notEqual(process.env.GITHUB_ACTIONS,'true');assert.equal(process.env.PGPORT,'59069');assert.match(process.env.PGDATABASE??'',/^lumin_journey_fields_payment_local_[a-z0-9_]+$/);}for(const key of ['DATABASE_URL','PGHOSTADDR','PGSERVICE','PGSERVICEFILE','PGPASSFILE','PGOPTIONS'])assert.ok(!process.env[key]);
const pool=new Pool({max:8}),id=(n:number)=>`86400000-0000-4000-8000-${String(n).padStart(12,'0')}`,actor=id(1),tenant=id(2),service=id(3),flow=id(4),foreignActor=id(21),foreignTenant=id(22),foreignService=id(23),foreignFlow=id(24),origin='https://checkout.example.test',otherOrigin='https://second.example.test';
const issue=createPaidJourneyCustomerFieldSessionIssuer(pool,[origin,otherOrigin]),write=createPaidJourneyCustomerFieldHoldWriter(pool,{configuredCustomerOrigins:[origin,otherOrigin]}),draft=createPaidJourneyCustomerFieldDraftOperations(pool),pub=createPaidJourneyCustomerFieldPublicationOperations(pool,{configuredCustomerOrigins:[origin,otherOrigin]}),legacyPay=createMockPaymentWriter(pool,{BOOKING_LUMIN_ENV:'staging',BOOKING_LUMIN_FAKE_PAYMENTS:'1'});
const form={name:'Hold',presentation:{accentColor:'#0e7490' as const,layout:'compact' as const},journey:{schemaVersion:1 as const,stages:(['service','options','schedule','information','review_payment','confirmation'] as const).map(kind=>({id:kind,kind,label:kind,enabled:kind!=='options'}))},customerFields:[{id:'custom_gate',kind:'text' as const,label:'Gate',required:true,maxLength:100},{id:'custom_code',kind:'text' as const,label:'Code',required:true,maxLength:100,when:{fieldId:'custom_gate',equals:'yes'}}],fieldBindings:[{fieldId:'custom_gate',stageId:'information'},{fieldId:'custom_code',stageId:'information'}]};
const deny=(run:()=>Promise<unknown>,code:string)=>assert.rejects(run,{code});
async function counts(){const result:Record<string,string>={};for(const table of ['bookings','customers','payments','capacity_holds','paid_journey_customer_field_requests','paid_journey_requests','flow_sessions','paid_journey_sessions','paid_journey_holds','paid_journey_hold_bindings','durable_outbox','flow_requests'])if((await pool.query('select to_regclass($1) r',['public.'+table])).rows[0].r)result[table]=(await pool.query(`select count(*)::text n from public.${table}`)).rows[0].n;return result;}
async function financial(){return(await pool.query('select (select count(*) from public.payments)::text payments,(select count(*) from public.durable_outbox)::text outbox,(select count(*) from public.bookings where state=\'confirmed\')::text confirmed')).rows[0];}
async function wait(query:string){let waiting=false;for(let n=0;n<80&&!waiting;n++){waiting=(await pool.query("select exists(select 1 from pg_stat_activity where datname=current_database() and wait_event_type='Lock' and query like $1) waiting",[query])).rows[0].waiting;if(!waiting)await new Promise(r=>setTimeout(r,10));}assert.equal(waiting,true,'actual lock wait required');}
try{
 assert.deepEqual((await pool.query('select current_database() d,current_user u,host(inet_server_addr()) h,inet_server_port() p')).rows[0],{d:process.env.PGDATABASE,u:'postgres',h:host,p:Number(process.env.PGPORT)});
 const day=new Date(Date.now()+86400000);day.setUTCHours(0,0,0,0);const start=new Date(day.getTime()+9*3600000).toISOString(),end=new Date(day.getTime()+10*3600000).toISOString(),later=new Date(day.getTime()+11*3600000).toISOString();
 for(const [a,t,s,f,v,i] of [[actor,tenant,service,flow,id(5),id(6)],[foreignActor,foreignTenant,foreignService,foreignFlow,id(25),id(26)]] as const){await pool.query('insert into auth.users(id,email) values($1,$2)',[a,a+'@example.test']);await pool.query("insert into public.tenants(id,name,slug,timezone,currency) values($1,'Hold',$2,'UTC','USD')",[t,t]);await pool.query("insert into public.tenant_members(tenant_id,user_id,role) values($1,$2,'BUSINESS_OWNER')",[t,a]);await pool.query('select public.initialize_staging_business_profile($1,$2,$3,$4)',[a,t,'HOUSEKEEPING','hold_'+a]);await pool.query("insert into public.services(id,tenant_id,name,archetype,currency,base_price,duration_minutes) values($1,$2,'Cleaning','simple','USD',12500,60)",[s,t]);await draft.save(a,t,f,{schemaVersion:2,serviceId:s,expectedRevision:0,form});await pub.publish(a,t,f,{schemaVersion:2,expectedDraftRevision:1,allowedOrigins:[origin,otherOrigin]},v,i);await pool.query('insert into public.availability_rules(tenant_id,service_id,weekday,start_minute,end_minute,capacity) values($1,$2,$3,540,900,1)',[t,s,day.getUTCDay()]);await pool.query('insert into public.scheduling_policies(tenant_id,service_id,lead_time_minutes,horizon_days,slot_interval_minutes) values($1,$2,0,60,30)',[t,s]);}

 const pay=createPaidJourneyCustomerFieldMockPaymentWriter(pool,{BOOKING_LUMIN_ENV:'staging',BOOKING_LUMIN_FAKE_PAYMENTS:'1'},{configuredCustomerOrigins:[origin,otherOrigin]}),oldPay=createPaidJourneyMockPaymentWriter(pool,{BOOKING_LUMIN_ENV:'staging',BOOKING_LUMIN_FAKE_PAYMENTS:'1'});
 for(const hash of ['a','b','c','d','e','1','2'])await issue(id(6),hash.repeat(64),origin);await issue(id(26),'f'.repeat(64),origin);
 const input={schemaVersion:2 as const,idempotencyKey:'fields-payment-integration-0001',requestedStart:start,customer:{name:'Customer',email:'customer@example.test'},answers:{custom_gate:'yes',custom_code:'price-free information'}},initial=await financial();
 await deny(()=>pay('a'.repeat(64),origin),'NOT_AVAILABLE');const held=await write('a'.repeat(64),origin,input);await deny(()=>legacyPay(actor,tenant,held.bookingId),'UNSUPPORTED_CONFIG');await deny(()=>oldPay('a'.repeat(64),origin),'FORBIDDEN');await deny(()=>pay('a'.repeat(64),otherOrigin),'FORBIDDEN');assert.deepEqual(await financial(),initial);
 const requestsBefore=(await pool.query('select * from public.paid_journey_customer_field_requests order by token_hash')).rows,sessionsBefore=(await pool.query('select * from public.paid_journey_customer_field_sessions order by token_hash')).rows;
 const results=await Promise.all([pay('a'.repeat(64),origin),pay('a'.repeat(64),origin)]);assert.deepEqual(results.map(r=>r.replayed).sort(),[false,true]);const first=results[0]!;for(const result of results){assert.deepEqual({...result,replayed:false},{...first,replayed:false});assert.equal(result.amount,12500);assert.equal(result.currency,'USD');assert.equal(result.realPayment,false);assert.equal(result.productionMoney,false);assert.equal(result.simulated,true);assert.equal(result.bookingId,held.bookingId);}
 assert.deepEqual(await financial(),{payments:'1',outbox:'1',confirmed:'1'});assert.equal((await pool.query('select status from public.capacity_holds where id=$1',[held.holdId])).rows[0].status,'consumed');assert.deepEqual((await pool.query('select * from public.paid_journey_customer_field_requests order by token_hash')).rows,requestsBefore);assert.deepEqual((await pool.query('select * from public.paid_journey_customer_field_sessions order by token_hash')).rows,sessionsBefore);await deny(()=>write('a'.repeat(64),origin,input),'NOT_AVAILABLE');await deny(()=>legacyPay(actor,tenant,held.bookingId),'UNSUPPORTED_CONFIG');assert.equal((await pay('a'.repeat(64),origin)).replayed,true);
 const mixedInput={...input,requestedStart:end},mixed=await write('b'.repeat(64),origin,mixedInput);const race=await Promise.allSettled([pay('b'.repeat(64),origin),write('b'.repeat(64),origin,mixedInput)]);assert.equal(race[0]!.status,'fulfilled');if(race[1]!.status==='rejected')assert.equal(race[1]!.reason.code,'NOT_AVAILABLE');assert.deepEqual(await financial(),{payments:'2',outbox:'2',confirmed:'2'});
 const failed=await write('c'.repeat(64),origin,{...input,requestedStart:later});await pool.query('update public.services set base_price=13000 where id=$1',[service]);await deny(()=>pay('c'.repeat(64),origin),'CONFLICT');await pool.query("update public.services set base_price=12500,currency='EUR' where id=$1",[service]);await deny(()=>pay('c'.repeat(64),origin),'CONFLICT');await pool.query("update public.services set currency='USD',active=false where id=$1",[service]);await deny(()=>pay('c'.repeat(64),origin),'NOT_AVAILABLE');await pool.query('update public.services set active=true where id=$1',[service]);await pool.query("update public.tenants set status='suspended' where id=$1",[tenant]);await deny(()=>pay('c'.repeat(64),origin),'NOT_AVAILABLE');await pool.query("update public.tenants set status='active' where id=$1",[tenant]);
 await pool.query("update public.capacity_holds set expires_at=clock_timestamp()-interval '1 second' where id=$1",[failed.holdId]);await deny(()=>pay('c'.repeat(64),origin),'CONFLICT');assert.deepEqual(await financial(),{payments:'2',outbox:'2',confirmed:'2'});await pool.query("update public.capacity_holds set expires_at=clock_timestamp()+interval '5 minutes' where id=$1",[failed.holdId]);

 // Expiry after an actual payment-table lock wait rolls the complete financial attempt back.
 await pool.query("with moment as materialized(select clock_timestamp()+interval '2 seconds' stamp) insert into public.paid_journey_customer_field_sessions select $1,tenant_id,flow_id,version_id,installation_id,service_id,publication_generation,origin,stamp-interval '15 minutes',stamp from public.paid_journey_customer_field_sessions cross join moment where token_hash=$2",['8'.repeat(64),'d'.repeat(64)]);
 const expiryStart=new Date(day.getTime()+13*3600000).toISOString();await write('8'.repeat(64),origin,{...input,requestedStart:expiryStart,customer:{name:'Expiry',email:'expiry@example.test'}});const beforeExpiry=await financial(),lock=await pool.connect();try{await lock.query('begin');await lock.query('lock table public.payments in share mode');const pending=deny(()=>pay('8'.repeat(64),origin),'FORBIDDEN');await wait('select public.pay_paid_journey_customer_field_mock%');const remaining=Number((await pool.query('select greatest(0,extract(epoch from expires_at-clock_timestamp())*1000) remaining from public.paid_journey_customer_field_sessions where token_hash=$1',['8'.repeat(64)])).rows[0].remaining);await new Promise(resolve=>setTimeout(resolve,remaining+30));await lock.query('commit');await pending;}finally{await lock.query('rollback');lock.release();}assert.deepEqual(await financial(),beforeExpiry);assert.equal((await pay('c'.repeat(64),origin)).replayed,false);
 assert.deepEqual(await financial(),{payments:'3',outbox:'3',confirmed:'3'});

 // A delayed booking-state trigger cannot turn an expired hold into a confirmed payment.
 const lateStart=new Date(day.getTime()+14*3600000).toISOString(),late=await write('e'.repeat(64),origin,{...input,requestedStart:lateStart,customer:{name:'Late',email:'late@example.test'}}),lateBefore=await financial(),slow=await pool.connect();try{await slow.query(`create function pg_temp.slow_v9_confirmation() returns trigger language plpgsql as $$begin if new.id='${late.bookingId}'::uuid and new.state='confirmed' then perform pg_sleep(1.5);end if;return new;end$$`);await slow.query('create trigger v9_payment_late_confirmation before update of state on public.bookings for each row execute function pg_temp.slow_v9_confirmation()');await pool.query("update public.capacity_holds set expires_at=clock_timestamp()+interval '1 second' where id=$1",[late.holdId]);const lateSnapshot=(await pool.query('select to_jsonb(b) booking,to_jsonb(h) hold from public.bookings b join public.capacity_holds h on h.booking_id=b.id where b.id=$1',[late.bookingId])).rows;await deny(()=>pay('e'.repeat(64),origin),'CONFLICT');assert.deepEqual(await financial(),lateBefore);assert.deepEqual((await pool.query('select to_jsonb(b) booking,to_jsonb(h) hold from public.bookings b join public.capacity_holds h on h.booking_id=b.id where b.id=$1',[late.bookingId])).rows,lateSnapshot);const row=(await pool.query('select state,payment_id,pricing from public.bookings where id=$1',[late.bookingId])).rows[0];assert.deepEqual(row,{state:'draft',payment_id:null,pricing:{}});}finally{await slow.query('drop trigger if exists v9_payment_late_confirmation on public.bookings');slow.release();}
 await deny(()=>pool.query("update public.business_profiles set business_type='AUTO_DETAILING' where tenant_id=$1",[tenant]),'55000');
 const foreign=await write('f'.repeat(64),origin,input);const foreignPayment=await pay('f'.repeat(64),origin);assert.equal(foreignPayment.serviceId,foreignService);assert.equal(foreignPayment.bookingId,foreign.bookingId);assert.equal((await pool.query('select tenant_id from public.payments where id=$1',[foreignPayment.paymentId])).rows[0].tenant_id,foreignTenant);
 for(const role of ['anon','authenticated']){const client=await pool.connect();try{await client.query('begin');await client.query('set local role '+role);await deny(()=>client.query('select public.pay_paid_journey_customer_field_mock($1,$2)',['a'.repeat(64),origin]),'42501');await client.query('rollback');}finally{client.release();}}
 await draft.save(actor,tenant,flow,{schemaVersion:2,serviceId:service,expectedRevision:1,form:{...form,name:'B'}});await pub.publish(actor,tenant,flow,{schemaVersion:2,expectedDraftRevision:2,allowedOrigins:[origin,otherOrigin]},id(7),id(8));await deny(()=>pay('a'.repeat(64),origin),'NOT_AVAILABLE');await issue(id(8),'7'.repeat(64),origin);await draft.save(actor,tenant,flow,{schemaVersion:2,serviceId:service,expectedRevision:2,form});await pub.publish(actor,tenant,flow,{schemaVersion:2,expectedDraftRevision:3,allowedOrigins:[origin,otherOrigin]},id(9),id(10));await deny(()=>pay('7'.repeat(64),origin),'NOT_AVAILABLE');
 assert.equal((await pool.query("select count(*)::text n from public.payments where provider<>'staging_mock'")).rows[0].n,'0');assert.equal((await pool.query('select count(*)::text n from public.paid_journey_requests')).rows[0].n,'0');console.log('PASS V9 simulated payment: sole confirmation, consumed holds, one outbox per booking, concurrent replay, mixed holds, immutable money, tenant/profile/generation and legacy exclusions');
}finally{await pool.end();}
