import {afterEach,describe,expect,it,vi} from 'vitest';
import type {Pool} from 'pg';
import type {Server} from 'node:http';
import {createPaidPublicationReader} from './paid-publication-reader';
import {createFlowHttpServer} from './http';
const id=(n:number)=>`38000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const actor=id(1),tenant=id(2),flow=id(3),version=id(4),installation=id(5),origin='https://portal.example.test';
const snapshot={renderSchemaVersion:3,submissionMode:'paid_service_request',paymentMode:'staging_mock',simulated:true,service:{id:id(6),name:'Housekeeping',durationMinutes:60,price:{amount:12500,currency:'USD'}}};
const row={tenantId:tenant,flowId:flow,versionId:version,installationId:installation,renderSchemaVersion:3,snapshot};
const receipt={versionId:version,installationId:installation,renderSchemaVersion:3 as const,hostedPath:`/checkout/flow/${installation}`};
function db(rows:unknown[],fail=false){const release=vi.fn();const query=vi.fn(async(sql:string)=>{if(sql.startsWith('select')){if(fail)throw new Error('private connection detail');return{rows};}return{rows:[]};});const pool={connect:async()=>({query,release})} as unknown as Pool;return{query,release,read:createPaidPublicationReader(pool)};}
describe('paid publication read authority',()=>{
 it('uses one parameterized SELECT in a read-only transaction, never writer RPCs',async()=>{const f=db([row]);expect(await f.read(actor,tenant,flow)).toEqual(receipt);expect(f.query.mock.calls.map(c=>c[0]).filter(s=>!s.startsWith('select'))).toEqual(['begin read only','set local role service_role','commit']);const sql=f.query.mock.calls[2]![0];expect(sql).toContain("m.role='BUSINESS_OWNER'");expect(sql).toContain("t.status='active'");expect(sql).toContain("f.status='active'");expect(sql).toContain('v.id=f.published_version_id');expect(sql).toContain('i.version_id=v.id');expect(f.query).toHaveBeenNthCalledWith(3,expect.any(String),[tenant,actor,flow]);expect(sql).not.toContain(actor);expect(f.release).toHaveBeenCalledOnce();});
 it.each([[],[row,row],[{...row,tenantId:id(9)}],[{...row,flowId:id(9)}],[{...row,renderSchemaVersion:1}],[{...row,versionId:'invalid'}],[{...row,installationId:'invalid'}],[{...row,snapshot:null}],[{...row,snapshot:{...snapshot,paymentMode:'stripe'}}],[{...row,snapshot:{...snapshot,versionId:version}}],[{...row,snapshot:{...snapshot,service:{...snapshot.service,price:{amount:0,currency:'USD'}}}}]].map(rows=>({rows})))('denies missing, ambiguous, foreign or malformed publication %j',async ({rows})=>expect(await db(rows).read(actor,tenant,flow)).toBeNull());
 it('rolls back and redacts failures',async()=>{const f=db([],true);await expect(f.read(actor,tenant,flow)).rejects.toMatchObject({code:'INTERNAL_ERROR',message:'INTERNAL_ERROR'});expect(f.query).toHaveBeenLastCalledWith('rollback');expect(f.release).toHaveBeenCalledOnce();});
 it('rejects invalid identifiers before database acquisition',async()=>{const f=db([row]);await expect(f.read('invalid',tenant,flow)).rejects.toMatchObject({code:'INVALID_REQUEST'});expect(f.query).not.toHaveBeenCalled();});
});
let server:Server;afterEach(async()=>{server?.closeAllConnections();if(server)await new Promise<void>(r=>server.close(()=>r()));});
async function fixture(enabled=true,existing:unknown=receipt){const call=vi.fn(async()=>{throw new Error('writer forbidden');});const read=vi.fn(async()=>existing as typeof receipt);const authenticateOwner=vi.fn(async token=>token==='owner-token-123456'?actor:null);server=createFlowHttpServer({repository:{call},ownerOrigins:[origin],customerOrigins:['https://checkout.example.test'],authenticateOwner,paidSimplePublication:enabled,paidPublication:read});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${(server.address() as {port:number}).port}`;return{call,read,authenticateOwner,get:(query=`tenantId=${tenant}`,token='owner-token-123456',o=origin,method='GET',path=flow)=>fetch(`${base}/api/paid-simple-flows/${path}/publication?${query}`,{method,headers:{origin:o,authorization:`Bearer ${token}`}})};}
describe('paid publication recovery HTTP',()=>{
 it('returns the exact existing receipt after fresh owner verification on every read',async()=>{const f=await fixture();for(let n=0;n<2;n++){const r=await f.get();expect(r.status).toBe(200);expect(r.headers.get('cache-control')).toBe('no-store');expect(await r.json()).toEqual({ok:true,data:receipt});}expect(f.authenticateOwner).toHaveBeenCalledTimes(2);expect(f.read).toHaveBeenCalledWith(actor,tenant,flow);expect(f.call).not.toHaveBeenCalled();});
 it.each(['','tenantId=bad',`tenantId=${tenant}&tenantId=${tenant}`,`tenantId=${tenant}&serviceId=${id(6)}`,`tenantId=${tenant}&retry=true`])('rejects ambiguous or widened query %s',async query=>{const f=await fixture();expect((await f.get(query)).status).toBe(400);expect(f.read).not.toHaveBeenCalled();expect(f.call).not.toHaveBeenCalled();});
 it('requires fresh identity, exact owner origin, GET and valid flow identifier',async()=>{const f=await fixture();expect((await f.get(undefined,'invalid-owner-123456')).status).toBe(401);expect((await f.get(undefined,undefined,'https://checkout.example.test')).status).toBe(403);expect((await f.get(undefined,undefined,origin+'/')).status).toBe(403);expect((await f.get(undefined,undefined,origin,'POST')).status).toBe(404);expect((await f.get(undefined,undefined,origin,'GET','invalid')).status).toBe(400);expect(f.read).not.toHaveBeenCalled();});
 it('keeps the staging gate closed',async()=>{const f=await fixture(false);expect((await f.get()).status).toBe(422);expect(f.read).not.toHaveBeenCalled();});
 it('reports absence only as NOT_AVAILABLE without retry or writer authority',async()=>{const f=await fixture(true,null);const r=await f.get();expect(r.status).toBe(404);expect(await r.json()).toEqual({ok:false,code:'NOT_AVAILABLE'});expect(f.call).not.toHaveBeenCalled();});
 it.each([{...receipt,hostedPath:'https://foreign.example.test'},{...receipt,renderSchemaVersion:2},{...receipt,retryAllowed:true}])('rejects widened/corrupt reader receipt %j',async existing=>{const f=await fixture(true,existing);expect((await f.get()).status).toBe(500);expect(f.call).not.toHaveBeenCalled();});
});
