import {describe,expect,it,vi} from 'vitest';
import {createPaidJourneyCustomerFieldSessionReader} from './paid-journey-customer-field-session-read';
const id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',hash='a'.repeat(64),origin='https://checkout.example.test';
const form={name:'Cleaning',presentation:{accentColor:'#0e7490',layout:'compact'},journey:{schemaVersion:1,stages:['service','options','schedule','information','review_payment','confirmation'].map(kind=>({id:kind,kind,label:kind,enabled:true}))},customerFields:[{id:'custom_gate',kind:'text',label:'Gate',required:false,maxLength:100}],fieldBindings:[{fieldId:'custom_gate',stageId:'information'}]};
const context=()=>({schemaVersion:2,tenantId:id,flowId:id,versionId:id,installationId:id,serviceId:id,publicationGeneration:2,expiresAt:new Date(Date.now()+600000).toISOString(),render:{versionId:id,renderSchemaVersion:9,submissionMode:'paid_journey_customer_field_request',paymentMode:'staging_mock',simulated:true,service:{id,name:'Cleaning',durationMinutes:60,price:{amount:12500,currency:'USD'}},form}});
function fixture(value:unknown=context(),code?:string){const statements:string[]=[];const client={query:vi.fn(async(sql:string)=>{statements.push(sql);if(sql.includes('resolve_paid_journey_customer_field_session')){if(code)throw Object.assign(Error('private connection'),{code});return {rows:[{result:value}]};}return {rows:[]};}),release:vi.fn()};return {client,statements,read:createPaidJourneyCustomerFieldSessionReader({connect:async()=>client} as never,{configuredCustomerOrigins:[origin]})};}
describe('private V9 session resolution',()=>{
 it('calls only the narrow resolver and freezes immutable context',async()=>{const f=fixture();const value=await f.read(hash,origin);expect(Object.isFrozen(value)).toBe(true);expect(Object.isFrozen(value.render.form)).toBe(true);expect(f.client.query).toHaveBeenCalledWith('select public.resolve_paid_journey_customer_field_session($1::text,$2::text) result',[hash,origin]);expect(f.statements).toEqual(['begin',"set local statement_timeout='5s'","set local lock_timeout='3s'",'set local role service_role','select public.resolve_paid_journey_customer_field_session($1::text,$2::text) result','commit']);expect(value).not.toHaveProperty('tokenHash');});
 it.each(['plaintext',hash.toUpperCase(),'a'.repeat(63)])('rejects unhashed/noncanonical token %s before connection',async value=>{const f=fixture();await expect(f.read(value,origin)).rejects.toMatchObject({code:'INVALID_REQUEST'});expect(f.client.query).not.toHaveBeenCalled();});
 it.each(['*',origin+'/','https://foreign.example.test','http://checkout.example.test'])('rejects malformed or unapproved origin %s',async value=>{const f=fixture();await expect(f.read(hash,value)).rejects.toBeInstanceOf(Error);expect(f.client.query).not.toHaveBeenCalled();});
 it.each([{...context(),schemaVersion:1},{...context(),tokenHash:hash},{...context(),customerAnswers:{}},{...context(),serviceId:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'},{...context(),versionId:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'},{...context(),tenantId:id.toUpperCase()},{...context(),publicationGeneration:0},{...context(),publicationGeneration:Number.MAX_SAFE_INTEGER+1},{...context(),expiresAt:new Date(Date.now()-1).toISOString()},{...context(),expiresAt:new Date(Date.now()+3600000).toISOString()},{...context(),render:{...context().render,renderSchemaVersion:8}}])('rejects malformed context before commit %j',async value=>{const f=fixture(value);await expect(f.read(hash,origin)).rejects.toMatchObject({code:'INTERNAL_ERROR'});expect(f.statements.at(-1)).toBe('rollback');expect(f.statements).not.toContain('commit');});
 it.each([['42501','FORBIDDEN'],['P0002','NOT_AVAILABLE'],['40001','CONFLICT'],['22023','INVALID_REQUEST'],['0A000','UNSUPPORTED_CONFIG'],['unknown','INTERNAL_ERROR']])('masks resolver errors %s',async(code,expected)=>{const f=fixture(undefined,code);await expect(f.read(hash,origin)).rejects.toMatchObject({code:expected,message:expected});});
 it('discards connection when rollback fails',async()=>{const f=fixture({...context(),secret:'private'});const old=f.client.query.getMockImplementation()!;f.client.query.mockImplementation(async(sql:string)=>{if(sql==='rollback')throw Error('private');return old(sql);});await expect(f.read(hash,origin)).rejects.toMatchObject({code:'INTERNAL_ERROR'});expect(f.client.release).toHaveBeenCalledWith(true);});
 it('rejects invalid configured origins',()=>{expect(()=>createPaidJourneyCustomerFieldSessionReader({} as never,{configuredCustomerOrigins:['*']})).toThrow();});
});
