import {expect,it,vi} from 'vitest';
import {createPaidJourneyCustomerFieldSessionIssuer,paidJourneyCustomerFieldSessionExpiryValid} from './paid-journey-customer-field-session';
const installation='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',version='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',service='cccccccc-cccc-4ccc-8ccc-cccccccccccc',origin='https://checkout.example.test',hash='a'.repeat(64);
const form={name:'Questions',presentation:{accentColor:'#0e7490',layout:'compact'},journey:{schemaVersion:1,stages:['service','options','schedule','information','review_payment','confirmation'].map(kind=>({id:kind,kind,label:kind,enabled:kind!=='options'}))},customerFields:[{id:'custom_gate',kind:'text',label:'Gate',required:false,maxLength:100}],fieldBindings:[{fieldId:'custom_gate',stageId:'information'}]};
const render={versionId:version,renderSchemaVersion:9,submissionMode:'paid_journey_customer_field_request',paymentMode:'staging_mock',simulated:true,service:{id:service,name:'Cleaning',durationMinutes:60,price:{amount:12500,currency:'USD'}},form};
const receipt=()=>({schemaVersion:2,installationId:installation,expiresAt:new Date(Date.now()+14*60000).toISOString(),render});
function database(value:unknown=receipt(),code?:string){const client={query:vi.fn(async(sql:string)=>{if(sql.startsWith('select public.')){if(code)throw Object.assign(Error('private password'),{code});return{rows:[{result:value}]};}return{rows:[]};}),release:vi.fn()};return{client,pool:{connect:vi.fn(async()=>client)}};}
const issuer=(db:ReturnType<typeof database>)=>createPaidJourneyCustomerFieldSessionIssuer(db.pool as never,[origin]);
it('issues strict presentation-only receipt using narrow service RPC without plaintext',async()=>{const value=receipt(),db=database(value);expect(await issuer(db)(installation,hash,origin)).toEqual(value);expect(db.client.query).toHaveBeenCalledWith('set local role service_role');expect(db.client.query).toHaveBeenCalledWith('select public.issue_paid_journey_customer_field_session($1::uuid,$2::text,$3::text) result',[installation,hash,origin]);expect(db.client.query).toHaveBeenCalledWith('commit');expect(Object.isFrozen((await issuer(db)(installation,hash,origin)).render.form)).toBe(true);});
for(const [id,token,browser] of [['bad',hash,origin],[installation.toUpperCase(),hash,origin],[installation,'plaintext',origin],[installation,hash.toUpperCase(),origin],[installation,'b'.repeat(63),origin],[installation,hash,'*'],[installation,hash,origin+'/'],[installation,hash,'http://localhost:3000']])it('rejects malformed input before DB '+id+token!.slice(0,2)+browser,async()=>{const db=database();await expect(issuer(db)(id!,token!,browser!)).rejects.toMatchObject({code:'INVALID_REQUEST'});expect(db.pool.connect).not.toHaveBeenCalled();});
it('rejects origins missing from configured allowlist before DB',async()=>{const db=database();await expect(issuer(db)(installation,hash,'https://foreign.example.test')).rejects.toMatchObject({code:'FORBIDDEN'});expect(db.pool.connect).not.toHaveBeenCalled();});
for(const value of [{...receipt(),schemaVersion:1},{...receipt(),installationId:version},{...receipt(),tokenHash:hash},{...receipt(),tenantId:service},{...receipt(),expiresAt:new Date(Date.now()-1).toISOString()},{...receipt(),expiresAt:new Date(Date.now()+16*60000).toISOString()},{...receipt(),render:{...render,renderSchemaVersion:8}},{...receipt(),render:{...render,service:{...render.service,price:{amount:-1,currency:'USD'}}}},{...receipt(),render:{...render,form:{...form,fieldBindings:[]}}}])it('rejects widened/malformed receipt '+JSON.stringify(value),async()=>{const db=database(value);await expect(issuer(db)(installation,hash,origin)).rejects.toMatchObject({code:'INTERNAL_ERROR'});expect(db.client.query).not.toHaveBeenCalledWith('commit');expect(db.client.query).toHaveBeenCalledWith('rollback');});
for(const [sql,code] of [['42501','FORBIDDEN'],['P0002','NOT_AVAILABLE'],['40001','CONFLICT'],['40P01','CONFLICT'],['23505','CONFLICT'],['22023','INVALID_REQUEST'],['55000','INTERNAL_ERROR']])it('redacts failures and never retries '+sql,async()=>{const db=database(undefined,sql);await expect(issuer(db)(installation,hash,origin)).rejects.toMatchObject({code});expect(db.client.query.mock.calls.filter(([q])=>q.includes('issue_paid_'))).toHaveLength(1);});
it('uncertain commit does not retry and disposes failed rollback connection',async()=>{const db=database(),original=db.client.query;db.client.query=vi.fn(async(q:string)=>{if(['commit','rollback'].includes(q))throw Error('private password');return original(q)});await expect(issuer(db)(installation,hash,origin)).rejects.toMatchObject({code:'INTERNAL_ERROR'});expect(db.client.release).toHaveBeenCalledWith(true);expect(db.client.query.mock.calls.filter(([q])=>q.includes('issue_paid_'))).toHaveLength(1);});
it('expiry guard rejects invalid clock, expired and unbounded receipts',()=>{const now=Date.now();expect(paidJourneyCustomerFieldSessionExpiryValid({expiresAt:new Date(now+900000).toISOString()},now)).toBe(true);for(const expiresAt of ['bad',new Date(now).toISOString(),new Date(now+901001).toISOString()])expect(paidJourneyCustomerFieldSessionExpiryValid({expiresAt},now)).toBe(false);expect(paidJourneyCustomerFieldSessionExpiryValid(receipt(),NaN)).toBe(false);});
