import {afterEach,describe,expect,it,vi} from 'vitest';
import {request,type Server} from 'node:http';
import {createFlowHttpServer,tokenHash} from './http';
import {FlowError} from './repository';
const id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',origin='https://checkout.example.test',token=Buffer.alloc(32,19).toString('base64url');
const now=Date.parse('2030-01-01T00:00:00.000Z'),start='2030-01-02T10:00:00.000Z',end='2030-01-02T11:00:00.000Z';
const input={schemaVersion:2,idempotencyKey:'conditional-hold-http-0001',requestedStart:start,customer:{name:'Staging Customer',email:'customer@example.test'},answers:{custom_gate:'no'}};
const receipt={schemaVersion:2,installationId:id,versionId:id,serviceId:id,bookingId:id,reference:'LMN-AAAAAAAAAAAA4AAA8AAAAAAAAAAAAAAA',state:'draft',confirmed:false,paymentMode:'unavailable',slot:{start,end},holdId:id,status:'active',expiresAt:new Date(now+300000).toISOString(),replayed:false};
let server:Server|undefined;
afterEach(async()=>{if(server){server.closeAllConnections();await new Promise<void>((resolve,reject)=>server!.close(error=>error?reject(error):resolve()));server=undefined;}});
async function fixture(value:unknown=receipt,enabled=true,clock=()=>now){const write=vi.fn(async()=>{if(value instanceof Error)throw value;return value;}),call=vi.fn(async()=>{throw Error('legacy forbidden');}),auth=vi.fn(async()=>null),legacyHold=vi.fn(),legacyPay=vi.fn();server=createFlowHttpServer({ownerOrigins:['https://portal.example.test'],customerOrigins:[origin],authenticateOwner:auth,now:clock,repository:{call} as never,paidJourneySessions:true,paidJourneyHold:legacyHold as never,paidJourneyMockPayment:legacyPay as never,...(enabled?{paidJourneyCustomerFieldHold:write as never}:{})});await new Promise<void>(resolve=>server!.listen(0,'127.0.0.1',resolve));return{write,call,auth,legacyHold,legacyPay,url:'http://127.0.0.1:'+(server.address() as {port:number}).port+'/api/public/paid-journey-customer-field-flow-sessions/hold'};}
const post=(url:string,body:unknown=input,headers:Record<string,string>={})=>fetch(url,{method:'POST',headers:{origin,authorization:'Bearer '+token,'content-type':'application/json',...headers},body:JSON.stringify(body)});
function untouched(f:Awaited<ReturnType<typeof fixture>>){expect(f.write).not.toHaveBeenCalled();expect(f.call).not.toHaveBeenCalled();expect(f.auth).not.toHaveBeenCalled();expect(f.legacyHold).not.toHaveBeenCalled();expect(f.legacyPay).not.toHaveBeenCalled();}
describe('private conditional customer-field hold HTTP boundary',()=>{
 it.each([false,true])('hashes canonical bearer and projects only draft hold with replay=%s',async replayed=>{const f=await fixture({...receipt,replayed});const response=await post(f.url);expect(response.status).toBe(200);expect(await response.json()).toEqual({ok:true,data:{...receipt,replayed}});expect(f.write).toHaveBeenCalledExactlyOnceWith(tokenHash(token),origin,input);expect(response.headers.get('cache-control')).toBe('no-store');expect(response.headers.get('access-control-allow-origin')).toBe(origin);expect(f.call).not.toHaveBeenCalled();expect(f.auth).not.toHaveBeenCalled();expect(f.legacyHold).not.toHaveBeenCalled();expect(f.legacyPay).not.toHaveBeenCalled();});
 it.each(['?','?tenantId='+id,'?serviceId='+id,'?price=1','?from='+start])('rejects all query authority before writer %s',async query=>{const f=await fixture();const status=query==='?'?await new Promise<number|undefined>((resolve,reject)=>{const req=request(f.url,{method:'POST',path:new URL(f.url).pathname+'?',headers:{origin,authorization:'Bearer '+token,'content-type':'application/json'}},res=>{res.resume();res.on('end',()=>resolve(res.statusCode));});req.on('error',reject);req.end(JSON.stringify(input));}):(await post(f.url+query)).status;expect(status).toBe(400);untouched(f);});
 it.each(['','Bearer forged','Bearer '+token+'=','Bearer '+('A'.repeat(42)+'B'),'Basic '+token])('rejects missing or noncanonical bearer %s',async authorization=>{const f=await fixture();expect((await post(f.url,input,{authorization})).status).toBe(401);untouched(f);});
 it.each(['','null','*',origin+'/','https://foreign.example.test','https://portal.example.test'])('rejects unapproved browser origin %s',async candidate=>{const f=await fixture();expect((await post(f.url,input,{origin:candidate})).status).toBe(403);untouched(f);});
 it.each(['GET','PUT','DELETE','PATCH'])('rejects non-POST without fallback %s',async method=>{const f=await fixture();const response=await fetch(f.url,{method,headers:{origin,authorization:'Bearer '+token}});expect(response.status).toBe(404);untouched(f);});
 it.each(['tenantId','serviceId','price','capacity','ttl','paymentId','confirmed','role'])('rejects injected body authority %s',async key=>{const f=await fixture();expect((await post(f.url,{...input,[key]:id})).status).toBe(400);untouched(f);});
 it.each([{},null,[],{...input,schemaVersion:1},{...input,requestedStart:'invalid'},{...input,customer:{...input.customer,tenantId:id}},{...input,idempotencyKey:'short'},{...input,answers:{custom_gate:1}}])('rejects malformed input before writer',async body=>{const f=await fixture();expect((await post(f.url,body)).status).toBe(400);untouched(f);});
 it.each(['text/plain','application/x-www-form-urlencoded'])('rejects non-json body %s',async contentType=>{const f=await fixture();expect((await post(f.url,input,{'content-type':contentType})).status).toBe(400);untouched(f);});
 it('keeps unconfigured V9 capability closed despite configured legacy writers',async()=>{const f=await fixture(receipt,false);expect((await post(f.url)).status).toBe(422);untouched(f);});
 it.each([{...receipt,tenantId:id},{...receipt,sessionToken:token},{...receipt,answers:input.answers},{...receipt,render:{}},{...receipt,confirmed:true},{...receipt,paymentMode:'staging_mock'},{...receipt,state:'confirmed'},{...receipt,reference:'fake'},{...receipt,slot:{start:end,end:'2030-01-02T12:00:00.000Z'}},{...receipt,slot:{start,end:'2030-01-04T10:00:00.000Z'}},{...receipt,expiresAt:new Date(now).toISOString()},{...receipt,expiresAt:new Date(now+301001).toISOString()}])('rejects private, financial or mismatched output',async value=>{const f=await fixture(value);const response=await post(f.url);expect(response.status).toBe(500);expect(await response.json()).toEqual({ok:false,code:'INTERNAL_ERROR'});expect(f.call).not.toHaveBeenCalled();expect(f.legacyPay).not.toHaveBeenCalled();});
 it.each([['FORBIDDEN',403],['NOT_AVAILABLE',404],['CONFLICT',409],['UNSUPPORTED_CONFIG',422]] as const)('maps transactional writer failure %s safely',async(code,status)=>{const f=await fixture(new FlowError(code));const response=await post(f.url);expect(response.status).toBe(status);expect(await response.json()).toEqual({ok:false,code});expect(f.call).not.toHaveBeenCalled();expect(f.legacyHold).not.toHaveBeenCalled();expect(f.legacyPay).not.toHaveBeenCalled();});
 it('drops a receipt that expires while its writer resolves',async()=>{let instant=now;const f=await fixture(receipt,true,()=>instant);f.write.mockImplementationOnce(async()=>{instant=now+300001;return receipt;});expect((await post(f.url)).status).toBe(500);expect(f.write).toHaveBeenCalledOnce();expect(f.legacyPay).not.toHaveBeenCalled();});
 it('allows exact customer preflight without calling any writer',async()=>{const f=await fixture();const response=await fetch(f.url,{method:'OPTIONS',headers:{origin,'access-control-request-method':'POST','access-control-request-headers':'authorization,content-type'}});expect(response.status).toBe(204);expect(response.headers.get('access-control-allow-origin')).toBe(origin);untouched(f);});
});