import {afterEach,describe,expect,it,vi} from 'vitest';
import {request,type Server} from 'node:http';
import {createFlowHttpServer,tokenHash} from './http';
const id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',origin='https://checkout.example.test',token=Buffer.alloc(32,19).toString('base64url');
const now=Date.now();
const render={versionId:id,renderSchemaVersion:9,submissionMode:'paid_journey_customer_field_request',paymentMode:'staging_mock',simulated:true,service:{id,name:'Cleaning',durationMinutes:60,price:{amount:12500,currency:'USD'}},form:{name:'Cleaning',presentation:{accentColor:'#0e7490',layout:'compact'},journey:{schemaVersion:1,stages:['service','options','schedule','information','review_payment','confirmation'].map(kind=>({id:kind,kind,label:kind,enabled:true}))},customerFields:[{id:'custom_gate',kind:'text',label:'Gate',required:false,maxLength:100}],fieldBindings:[{fieldId:'custom_gate',stageId:'information'}]}};
const context={schemaVersion:2,tenantId:id,flowId:id,versionId:id,installationId:id,serviceId:id,publicationGeneration:2,expiresAt:new Date(now+600000).toISOString(),render};
let server:Server|undefined;
afterEach(async()=>{if(server){server.closeAllConnections();await new Promise<void>((resolve,reject)=>server!.close(error=>error?reject(error):resolve()));server=undefined;}});
async function fixture(value:unknown=context,enabled=true){const read=vi.fn(async()=>value),call=vi.fn(async()=>{throw Error('legacy forbidden');}),auth=vi.fn(async()=>null);server=createFlowHttpServer({ownerOrigins:['https://portal.example.test'],customerOrigins:[origin],authenticateOwner:auth,repository:{call} as never,now:()=>now,...(enabled?{paidJourneyCustomerFieldSessionRead:read as never}:{})});await new Promise<void>(resolve=>server!.listen(0,'127.0.0.1',resolve));return{read,call,auth,url:`http://127.0.0.1:${(server.address() as {port:number}).port}/api/public/paid-journey-customer-field-flow-sessions/render`};}
const get=(url:string,headers:Record<string,string>={})=>fetch(url,{headers:{origin,authorization:`Bearer ${token}`,...headers}});
describe('private V9 session HTTP read boundary',()=>{
 it('hashes the bearer and projects only public immutable render metadata',async()=>{const f=await fixture();const response=await get(f.url);expect(response.status).toBe(200);const data=(await response.json()).data;expect(data).toEqual({schemaVersion:2,installationId:id,expiresAt:context.expiresAt,render});expect(f.read).toHaveBeenCalledExactlyOnceWith(tokenHash(token),origin);expect(response.headers.get('cache-control')).toBe('no-store');expect(f.call).not.toHaveBeenCalled();expect(f.auth).not.toHaveBeenCalled();});
 it.each(['','Bearer forged','Bearer '+token+'=','Bearer '+('A'.repeat(42)+'B'),'Basic '+token])('rejects malformed authorization before reading',async authorization=>{const f=await fixture();expect((await get(f.url,{authorization})).status).toBe(401);expect(f.read).not.toHaveBeenCalled();});
 it.each(['','null','*',origin+'/','https://foreign.example.test','https://portal.example.test'])('rejects unapproved browser origin %s',async candidate=>{const f=await fixture();expect((await get(f.url,{origin:candidate})).status).toBe(403);expect(f.read).not.toHaveBeenCalled();});
 it('rejects query authority and non-read methods without legacy dispatch',async()=>{const f=await fixture();expect((await get(f.url+'?tenantId='+id)).status).toBe(400);expect((await fetch(f.url,{method:'POST',headers:{origin,authorization:`Bearer ${token}`}})).status).toBe(404);expect(f.read).not.toHaveBeenCalled();expect(f.call).not.toHaveBeenCalled();});
 it.each(['?','body'])('rejects actual raw GET %s bytes',async kind=>{const f=await fixture();const status=await new Promise<number|undefined>((resolve,reject)=>{const req=request(f.url,{method:'GET',path:new URL(f.url).pathname+(kind==='?'?'?':''),headers:{origin,authorization:`Bearer ${token}`,...(kind==='body'?{'content-length':'2'}:{})}},res=>{res.resume();res.on('end',()=>resolve(res.statusCode));});req.on('error',reject);req.end(kind==='body'?'{}':undefined);});expect(status).toBe(400);expect(f.read).not.toHaveBeenCalled();});
 it('keeps disabled capability closed',async()=>{const f=await fixture(context,false);expect((await get(f.url)).status).toBe(422);expect(f.read).not.toHaveBeenCalled();});
 it.each([{...context,tokenHash:'private'},{...context,expiresAt:new Date(now).toISOString()},{...context,expiresAt:new Date(now+16*60000).toISOString()},{...context,versionId:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'},{...context,publicationGeneration:0},{...context,render:{...render,paymentMode:'live'}}])('rejects malformed private context without leaking it',async value=>{const f=await fixture(value);const response=await get(f.url);expect(response.status).toBe(500);expect(JSON.stringify(await response.json())).not.toContain('private');expect(f.read).toHaveBeenCalledTimes(1);expect(f.call).not.toHaveBeenCalled();});
});
