import assert from 'node:assert/strict';
import {isIP} from 'node:net';
import {Pool} from 'pg';
import {createPaidJourneyCustomerFieldHoldWriter} from './paid-journey-customer-field-hold';
import {createPaidJourneyCustomerFieldSessionIssuer} from './paid-journey-customer-field-session';
import {createPaidJourneyCustomerFieldDraftOperations} from './paid-journey-customer-field-draft';
import {createPaidJourneyCustomerFieldPublicationOperations} from './paid-journey-customer-field-publication';
import {createMockPaymentWriter} from './mock-payment';
assert.equal(process.env.PAID_JOURNEY_CUSTOMER_FIELD_HOLD_LOCAL_TEST,'1');assert.equal(process.env.PGHOST,'127.0.0.1');assert.equal(process.env.PGUSER,'postgres');
let host='127.0.0.1';if(process.env.CI==='true'){assert.equal(process.env.GITHUB_ACTIONS,'true');assert.equal(process.env.PGPORT,'5432');assert.equal(process.env.PGDATABASE,'lumin_journey_fields_hold_ci');host=process.env.PAID_JOURNEY_CUSTOMER_FIELD_HOLD_CI_DATABASE_HOST??'';assert.equal(isIP(host),4);assert.match(host,/^(?:10\.|172\.(?:1[6-9]|2[0-9]|3[01])\.|192\.168\.)/);}else{assert.notEqual(process.env.GITHUB_ACTIONS,'true');assert.equal(process.env.PGPORT,'59069');assert.match(process.env.PGDATABASE??'',/^lumin_journey_fields_hold_local_[a-z0-9_]+$/);}for(const key of ['DATABASE_URL','PGHOSTADDR','PGSERVICE','PGSERVICEFILE','PGPASSFILE','PGOPTIONS'])assert.ok(!process.env[key]);
const pool=new Pool({max:8}),id=(n:number)=>`85400000-0000-4000-8000-${String(n).padStart(12,'0')}`,actor=id(1),tenant=id(2),service=id(3),flow=id(4),foreignActor=id(21),foreignTenant=id(22),foreignService=id(23),foreignFlow=id(24),origin='https://checkout.example.test',otherOrigin='https://second.example.test';
const issue=createPaidJourneyCustomerFieldSessionIssuer(pool,[origin,otherOrigin]),write=createPaidJourneyCustomerFieldHoldWriter(pool,{configuredCustomerOrigins:[origin,otherOrigin]}),draft=createPaidJourneyCustomerFieldDraftOperations(pool),pub=createPaidJourneyCustomerFieldPublicationOperations(pool,{configuredCustomerOrigins:[origin,otherOrigin]}),legacyPay=createMockPaymentWriter(pool,{BOOKING_LUMIN_ENV:'staging',BOOKING_LUMIN_FAKE_PAYMENTS:'1'});
const form={name:'Hold',presentation:{accentColor:'#0e7490' as const,layout:'compact' as const},journey:{schemaVersion:1 as const,stages:(['service','options','schedule','information','review_payment','confirmation'] as const).map(kind=>({id:kind,kind,label:kind,enabled:kind!=='options'}))},customerFields:[{id:'custom_gate',kind:'text' as const,label:'Gate',required:true,maxLength:100},{id:'custom_code',kind:'text' as const,label:'Code',required:true,maxLength:100,when:{fieldId:'custom_gate',equals:'yes'}}],fieldBindings:[{fieldId:'custom_gate',stageId:'information'},{fieldId:'custom_code',stageId:'information'}]};
const deny=(run:()=>Promise<unknown>,code:string)=>assert.rejects(run,{code});
async function counts(){const result:Record<string,string>={};for(const table of ['bookings','customers','payments','capacity_holds','paid_journey_customer_field_requests','paid_journey_requests','flow_sessions','paid_journey_sessions','paid_journey_holds','paid_journey_hold_bindings','durable_outbox','flow_requests'])if((await pool.query('select to_regclass($1) r',['public.'+table])).rows[0].r)result[table]=(await pool.query(`select count(*)::text n from public.${table}`)).rows[0].n;return result;}
async function financial(){return(await pool.query('select (select count(*) from public.payments)::text payments,(select count(*) from public.durable_outbox)::text outbox,(select count(*) from public.bookings where state=\'confirmed\')::text confirmed')).rows[0];}
async function wait(query:string){let waiting=false;for(let n=0;n<80&&!waiting;n++){waiting=(await pool.query("select exists(select 1 from pg_stat_activity where datname=current_database() and wait_event_type='Lock' and query like $1) waiting",[query])).rows[0].waiting;if(!waiting)await new Promise(r=>setTimeout(r,10));}assert.equal(waiting,true,'actual lock wait required');}
try{
 assert.deepEqual((await pool.query('select current_database() d,current_user u,host(inet_server_addr()) h,inet_server_port() p')).rows[0],{d:process.env.PGDATABASE,u:'postgres',h:host,p:Number(process.env.PGPORT)});
 const day=new Date(Date.now()+86400000);day.setUTCHours(0,0,0,0);const start=new Date(day.getTime()+9*3600000).toISOString(),end=new Date(day.getTime()+10*3600000).toISOString(),later=new Date(day.getTime()+11*3600000).toISOString();
 for(const [a,t,s,f,v,i] of [[actor,tenant,service,flow,id(5),id(6)],[foreignActor,foreignTenant,foreignService,foreignFlow,id(25),id(26)]] as const){await pool.query('insert into auth.users(id,email) values($1,$2)',[a,a+'@example.test']);await pool.query("insert into public.tenants(id,name,slug,timezone,currency) values($1,'Hold',$2,'UTC','USD')",[t,t]);await pool.query("insert into public.tenant_members(tenant_id,user_id,role) values($1,$2,'BUSINESS_OWNER')",[t,a]);await pool.query('select public.initialize_staging_business_profile($1,$2,$3,$4)',[a,t,'HOUSEKEEPING','hold_'+a]);await pool.query("insert into public.services(id,tenant_id,name,archetype,currency,base_price,duration_minutes) values($1,$2,'Cleaning','simple','USD',12500,60)",[s,t]);await draft.save(a,t,f,{schemaVersion:2,serviceId:s,expectedRevision:0,form});await pub.publish(a,t,f,{schemaVersion:2,expectedDraftRevision:1,allowedOrigins:[origin,otherOrigin]},v,i);await pool.query('insert into public.availability_rules(tenant_id,service_id,weekday,start_minute,end_minute,capacity) values($1,$2,$3,540,720,1)',[t,s,day.getUTCDay()]);await pool.query('insert into public.scheduling_policies(tenant_id,service_id,lead_time_minutes,horizon_days,slot_interval_minutes) values($1,$2,0,60,30)',[t,s]);}
 for(const hash of ['a','b','c','d','e','1','2'])await issue(id(6),hash.repeat(64),origin);await issue(id(26),'f'.repeat(64),origin);
 const input={schemaVersion:2 as const,idempotencyKey:'fields-hold-integration-0001',requestedStart:start,customer:{name:'Customer',email:'customer@example.test'},answers:{custom_gate:'no'}},initial=await counts(),financialBefore=await financial(),sessionsBefore=(await pool.query('select * from public.paid_journey_customer_field_sessions order by token_hash')).rows;
 for(const key of ['tenantId','serviceId','price','capacity','ttl','paymentId','confirmed'])await deny(()=>write('a'.repeat(64),origin,{...input,[key]:foreignTenant} as never),'INVALID_REQUEST');for(const answers of [{},{custom_gate:'yes'},{custom_gate:'no',custom_code:'hidden'},{custom_gate:'no',custom_unknown:'foreign'}])await deny(()=>write('a'.repeat(64),origin,{...input,answers} as never),'INVALID_REQUEST');await deny(()=>write('a'.repeat(64),otherOrigin,input),'FORBIDDEN');await deny(()=>write('9'.repeat(64),origin,input),'NOT_AVAILABLE');await deny(()=>write('a'.repeat(64),origin,{...input,requestedStart:new Date(day.getTime()+8*3600000).toISOString()}),'NOT_AVAILABLE');assert.deepEqual(await counts(),initial);
 const repeated=await Promise.all([write('a'.repeat(64),origin,input),write('a'.repeat(64),origin,input)]);assert.deepEqual(repeated.map(r=>r.replayed).sort(),[false,true]);const won=repeated[0]!;for(const value of repeated)assert.deepEqual({...value,replayed:false},{...won,replayed:false});assert.equal(won.confirmed,false);assert.equal(won.paymentMode,'unavailable');assert.equal(won.state,'draft');assert.equal(won.serviceId,service);assert.equal(won.slot.start,start);assert.equal(won.slot.end,end);assert.deepEqual(Object.keys(won).sort(),['schemaVersion','versionId','installationId','serviceId','bookingId','reference','state','confirmed','paymentMode','slot','holdId','status','expiresAt','replayed'].sort());
 const afterOne=await counts();assert.equal(Number(afterOne.bookings),Number(initial.bookings)+1);assert.equal(Number(afterOne.capacity_holds),Number(initial.capacity_holds)+1);assert.equal(Number(afterOne.paid_journey_customer_field_requests),1);assert.equal(afterOne.payments,'0');assert.equal(afterOne.paid_journey_requests,'0');assert.equal(afterOne.flow_requests,'0');
 await deny(()=>write('a'.repeat(64),origin,{...input,idempotencyKey:'different-key-0000001'}),'CONFLICT');await deny(()=>write('a'.repeat(64),origin,{...input,answers:{custom_gate:'yes',custom_code:'changed'}}),'CONFLICT');await deny(()=>write('a'.repeat(64),origin,{...input,customer:{name:'Other',email:'other@example.test'}}),'CONFLICT');assert.deepEqual(await counts(),afterOne);
 const linked=(await pool.query('select b.state,b.payment_id,b.selection,b.pricing,b.idempotency_key,r.canonical_payload,r.published_render,r.publication_generation from public.bookings b join public.paid_journey_customer_field_requests r on r.booking_id=b.id where b.id=$1',[won.bookingId])).rows[0];assert.equal(linked.state,'draft');assert.equal(linked.payment_id,null);assert.deepEqual(linked.selection,{serviceId:service});assert.deepEqual(linked.pricing,{});assert.equal(linked.idempotency_key,'paid-journey:fields:'+'a'.repeat(64));assert.deepEqual(linked.canonical_payload,{customer:input.customer,answers:input.answers,requestedStart:start});assert.equal(linked.published_render.versionId,id(5));
 // Prove the actual legacy financial writer refuses this reserved identity.
 await deny(()=>legacyPay(actor,tenant,won.bookingId),'UNSUPPORTED_CONFIG');await deny(()=>pool.query('select public.assert_legacy_mock_payment_booking($1,$2)',[tenant,won.bookingId]),'0A000');await deny(()=>legacyPay(foreignActor,tenant,won.bookingId),'FORBIDDEN');assert.deepEqual(await counts(),afterOne);
 const raceInput={...input,requestedStart:end,customer:{name:'Race',email:'race@example.test'},answers:{custom_gate:'yes',custom_code:'exact'}},raced=await Promise.allSettled([write('b'.repeat(64),origin,raceInput),write('c'.repeat(64),origin,raceInput)]);assert.equal(raced.filter(r=>r.status==='fulfilled').length,1);assert.equal(raced.filter(r=>r.status==='rejected'&&r.reason.code==='CONFLICT').length,1);const afterRace=await counts();assert.equal(Number(afterRace.bookings),Number(afterOne.bookings)+1);assert.equal(Number(afterRace.capacity_holds),Number(afterOne.capacity_holds)+1);assert.equal(Number(afterRace.paid_journey_customer_field_requests),2);
 const foreign=await write('f'.repeat(64),origin,input);assert.equal(foreign.serviceId,foreignService);assert.equal((await pool.query('select tenant_id from public.bookings where id=$1',[foreign.bookingId])).rows[0].tenant_id,foreignTenant);
 // Configuration writer goes first: the hold waits then observes changed hours.
 const config=await pool.connect(),beforeConfig=await counts();try{await config.query('begin');await config.query('update public.availability_rules set start_minute=0,end_minute=60 where tenant_id=$1',[tenant]);const blocked=deny(()=>write('d'.repeat(64),origin,{...input,requestedStart:later,customer:{name:'Config',email:'config@example.test'}}),'NOT_AVAILABLE');await wait('select public.submit_paid_journey_customer_field_hold_request%');await config.query('commit');await blocked;}finally{await config.query('rollback');config.release();}assert.deepEqual(await counts(),beforeConfig);await pool.query('update public.availability_rules set start_minute=540,end_minute=720 where tenant_id=$1',[tenant]);
 await pool.query('update public.services set base_price=13000 where id=$1',[service]);await deny(()=>write('d'.repeat(64),origin,{...input,requestedStart:later}),'CONFLICT');await pool.query('update public.services set base_price=12500,active=false where id=$1',[service]);await deny(()=>write('d'.repeat(64),origin,{...input,requestedStart:later}),'NOT_AVAILABLE');await pool.query('update public.services set active=true where id=$1',[service]);await pool.query("update public.tenants set status='suspended' where id=$1",[tenant]);await deny(()=>write('d'.repeat(64),origin,{...input,requestedStart:later}),'NOT_AVAILABLE');await pool.query("update public.tenants set status='active' where id=$1",[tenant]);
 // Expiry after actual capacity lock wait rolls back customer, request, draft and hold.
 await pool.query("with moment as materialized(select clock_timestamp()+interval '2 seconds' stamp) insert into public.paid_journey_customer_field_sessions select $1,tenant_id,flow_id,version_id,installation_id,service_id,publication_generation,origin,stamp-interval '15 minutes',stamp from public.paid_journey_customer_field_sessions cross join moment where token_hash=$2",['8'.repeat(64),'a'.repeat(64)]);const blocker=await pool.connect(),beforeExpiry=await counts();try{await blocker.query('begin');await blocker.query('select pg_advisory_xact_lock(hashtextextended($1,0))',['lumin:service-capacity:'+tenant+':'+service]);const pending=deny(()=>write('8'.repeat(64),origin,{...input,requestedStart:later,customer:{name:'Expiry',email:'expiry@example.test'}}),'FORBIDDEN');await wait('select * from public.reserve_capacity%');const remaining=Number((await pool.query('select greatest(0,extract(epoch from expires_at-clock_timestamp())*1000) remaining from public.paid_journey_customer_field_sessions where token_hash=$1',['8'.repeat(64)])).rows[0].remaining);await new Promise(r=>setTimeout(r,remaining+30));await blocker.query('commit');await pending;}finally{await blocker.query('rollback');blocker.release();}assert.deepEqual(await counts(),beforeExpiry);
 const liveSessions=(await pool.query("select * from public.paid_journey_customer_field_sessions where token_hash<>'8'||repeat('8',63) order by token_hash")).rows;assert.deepEqual(liveSessions,sessionsBefore);
 await pool.query("update public.capacity_holds set expires_at=clock_timestamp()-interval '1 second' where id=$1",[won.holdId]);const beforeEnded=await counts();await deny(()=>write('a'.repeat(64),origin,input),'CONFLICT');assert.deepEqual(await counts(),beforeEnded);await pool.query("update public.capacity_holds set status='released' where id=$1",[won.holdId]);await deny(()=>write('a'.repeat(64),origin,input),'CONFLICT');
 for(const role of ['anon','authenticated','service_role']){const c=await pool.connect();try{await c.query('begin');await c.query('set local role '+role);await deny(()=>c.query('select * from public.paid_journey_customer_field_requests'),'42501');await c.query('rollback');if(role!=='service_role'){await c.query('begin');await c.query('set local role '+role);await deny(()=>c.query('select public.paid_journey_customer_field_hold_target($1,$2)',['a'.repeat(64),origin]),'42501');await c.query('rollback');}}finally{c.release();}}
 await deny(()=>pool.query('update public.paid_journey_customer_field_requests set idempotency_key=$1 where token_hash=$2',['forged-immutable-key','a'.repeat(64)]),'55000');await deny(()=>pool.query('select public.submit_paid_journey_hold_request($1,$2,$3,$4,$5,$6)',['a'.repeat(64),origin,input.idempotencyKey,input.customer,{},start]),'42501');
 await draft.save(actor,tenant,flow,{schemaVersion:2,serviceId:service,expectedRevision:1,form:{...form,name:'B'}});await pub.publish(actor,tenant,flow,{schemaVersion:2,expectedDraftRevision:2,allowedOrigins:[origin,otherOrigin]},id(7),id(8));await deny(()=>write('1'.repeat(64),origin,{...input,requestedStart:later}),'NOT_AVAILABLE');await issue(id(8),'7'.repeat(64),origin);await draft.save(actor,tenant,flow,{schemaVersion:2,serviceId:service,expectedRevision:2,form});await pub.publish(actor,tenant,flow,{schemaVersion:2,expectedDraftRevision:3,allowedOrigins:[origin,otherOrigin]},id(9),id(10));await deny(()=>write('7'.repeat(64),origin,{...input,requestedStart:later}),'NOT_AVAILABLE');await issue(id(10),'6'.repeat(64),origin);assert.equal((await write('6'.repeat(64),origin,{...input,requestedStart:later})).installationId,id(10));assert.deepEqual(await financial(),financialBefore);
 console.log('PASS V9 actual hold: same-session replay, last-slot one winner, private provenance/answers, tenant isolation, actual legacy payment denial, stale config/expiry lock waits and generation rotation; zero financial writes');
}finally{await pool.end();}