import {afterEach,describe,expect,it,vi} from 'vitest';
import type {Server} from 'node:http';
import {createFlowHttpServer} from './http';
const actor='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',tenant='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',flow='cccccccc-cccc-4ccc-8ccc-cccccccccccc',service='dddddddd-dddd-4ddd-8ddd-dddddddddddd',version='eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',installation='ffffffff-ffff-4fff-8fff-ffffffffffff',origin='https://portal.example.test',customerOrigin='https://checkout.example.test';
const form={name:'Housekeeping',presentation:{accentColor:'#0e7490',layout:'compact'},journey:{schemaVersion:1,stages:['service','options','schedule','information','review_payment','confirmation'].map(kind=>({id:kind,kind,label:kind,enabled:true}))},customerFields:[{id:'custom_gate',kind:'text',label:'Gate',required:false,maxLength:100}],fieldBindings:[{fieldId:'custom_gate',stageId:'information'}]};
const input={schemaVersion:2,expectedDraftRevision:1,allowedOrigins:[customerOrigin]},receipt={schemaVersion:2,tenantId:tenant,flowId:flow,draftRevision:1,versionId:version,installationId:installation,renderSchemaVersion:9,replayed:true};
const {replayed:_,...metadata}=receipt;
const publication={...metadata,allowedOrigins:[customerOrigin],render:{versionId:version,renderSchemaVersion:9,submissionMode:'paid_journey_customer_field_request',paymentMode:'staging_mock',simulated:true,service:{id:service,name:'Cleaning',durationMinutes:60,price:{amount:12500,currency:'USD'}},form}};
let server:Server|undefined;
afterEach(async()=>{if(server){server.closeAllConnections();await new Promise<void>((resolve,reject)=>server!.close(error=>error?reject(error):resolve()));server=undefined;}});
async function fixture(value:unknown=publication,result:unknown=receipt,enabled=true){const read=vi.fn(async()=>value),publish=vi.fn(async()=>result),call=vi.fn(async()=>{throw Error('legacy writer forbidden');});server=createFlowHttpServer({ownerOrigins:[origin],customerOrigins:[customerOrigin],authenticateOwner:async token=>token==='owner-token-123456'?actor:null,repository:{call} as never,paidJourneyDrafts:enabled,paidJourneyCustomerFieldPublication:{read,publish} as never});await new Promise<void>(resolve=>server!.listen(0,'127.0.0.1',resolve));return{read,publish,call,url:`http://127.0.0.1:${(server.address() as {port:number}).port}/api/paid-journey-customer-field-flows/${flow}`};}
const headers={origin,authorization:'Bearer owner-token-123456','content-type':'application/json'};
const get=(url:string,extra:Record<string,string>={})=>fetch(url+'/publication?tenantId='+tenant,{headers:{...headers,...extra}});
const post=(url:string,body:unknown=input,extra:Record<string,string>={})=>fetch(url+'/publish?tenantId='+tenant,{method:'POST',headers:{...headers,...extra},body:JSON.stringify(body)});
describe('dedicated immutable conditional journey publication HTTP authority',()=>{
 it('dispatches explicit owner publication with server-created aliases and authenticated read only',async()=>{const f=await fixture();expect((await post(f.url)).status).toBe(200);expect(f.publish).toHaveBeenCalledExactlyOnceWith(actor,tenant,flow,input,expect.stringMatching(/^[0-9a-f-]{36}$/),expect.stringMatching(/^[0-9a-f-]{36}$/));expect((await get(f.url)).status).toBe(200);expect(f.read).toHaveBeenCalledExactlyOnceWith(actor,tenant,flow);expect(f.call).not.toHaveBeenCalled();});
 it('requires owner auth and exact owner origin before any publication dispatch',async()=>{const f=await fixture();expect((await post(f.url,input,{authorization:''})).status).toBe(401);expect((await get(f.url,{authorization:'Bearer forged-token-123456'})).status).toBe(401);expect((await post(f.url,input,{origin:customerOrigin})).status).toBe(403);expect(f.publish).not.toHaveBeenCalled();expect(f.read).not.toHaveBeenCalled();});
 it('rejects disabled authoring and legacy methods without RPC fallback',async()=>{const f=await fixture(publication,receipt,false);expect((await post(f.url)).status).toBe(422);expect((await get(f.url)).status).toBe(422);expect(f.publish).not.toHaveBeenCalled();expect(f.read).not.toHaveBeenCalled();expect(f.call).not.toHaveBeenCalled();});
 it('rejects duplicate context and malformed read bodies',async()=>{const f=await fixture();expect((await fetch(f.url+'/publication?tenantId='+tenant+'&tenantId='+actor,{headers})).status).toBe(400);expect((await fetch(f.url+'/publication?tenantId='+tenant,{method:'POST',headers,body:'{}'})).status).toBe(404);expect(f.read).not.toHaveBeenCalled();});
 it.each([{...input,schemaVersion:1},{...input,expectedDraftRevision:0},{...input,tenantId:actor},{...input,versionId:version},{...input,price:1},{...input,allowedOrigins:['*']},{...input,allowedOrigins:[customerOrigin+'/']}])('rejects input or financial authority tampering',async body=>{const f=await fixture();expect((await post(f.url,body)).status).toBe(400);expect(f.publish).not.toHaveBeenCalled();});
 it('rejects syntactically valid unapproved origins before publication',async()=>{const f=await fixture();expect((await post(f.url,{...input,allowedOrigins:['https://foreign.example.test']})).status).toBe(403);expect(f.publish).not.toHaveBeenCalled();});
 it.each([{...receipt,tenantId:actor},{...receipt,flowId:actor},{...receipt,draftRevision:2},{...receipt,replayed:false},{...receipt,secret:'must-not-return'}])('rejects foreign or malformed receipts without repeating writes',async result=>{const f=await fixture(publication,result);const r=await post(f.url);expect(r.status).toBe(500);expect(JSON.stringify(await r.json())).not.toContain('must-not-return');expect(f.publish).toHaveBeenCalledTimes(1);expect(f.call).not.toHaveBeenCalled();});
 it.each([{...publication,tenantId:actor},{...publication,flowId:actor},{...publication,allowedOrigins:['https://foreign.example.test']},{...publication,render:{...publication.render,versionId:actor}},{...publication,secret:'must-not-return'}])('rejects invalid immutable owner reads',async value=>{const f=await fixture(value);const r=await get(f.url);expect(r.status).toBe(500);expect(JSON.stringify(await r.json())).not.toContain('must-not-return');expect(f.publish).not.toHaveBeenCalled();});
});
