import assert from 'node:assert/strict';
import {Pool} from 'pg';
import {createFlowHttpServer} from './http';
import {createFlowRepository} from './repository';
import {createPaidInstallHealthReader} from './paid-install-health';
import {createCustomerHoldWriter} from './customer-hold';
import {createCustomerMockPayment} from './customer-payment';
import {PaidInstallHealth} from '@lumin/contracts';
assert.equal(process.env.PAID_HEALTH_LOCAL_TEST,'1');if(process.env.CI==='true'){assert.ok(['localhost','127.0.0.1'].includes(process.env.PGHOST??''));assert.equal(process.env.PGPORT,'5432');}else{assert.equal(process.env.PGHOST,'127.0.0.1');assert.equal(process.env.PGPORT,'55436');}assert.match(process.env.PGDATABASE??'',/^lumin_phase_a_health_/);for(const key of ['DATABASE_URL','PGHOSTADDR','PGSERVICE','PGSERVICEFILE','PGOPTIONS'])assert.ok(!process.env[key]);
const pool=new Pool(),id=(n:number)=>`48000000-0000-4000-8000-${String(n).padStart(12,'0')}`,actor=id(1),tenant=id(2),foreign=id(9),origin='https://portal.example.test',customerOrigin='https://checkout.example.test';
const server=createFlowHttpServer({repository:createFlowRepository(pool),paidSimplePublication:true,paidInstallHealth:createPaidInstallHealthReader(pool,[customerOrigin]),customerHold:createCustomerHoldWriter(pool),customerMockPayment:createCustomerMockPayment(pool,{BOOKING_LUMIN_ENV:'staging',BOOKING_LUMIN_FAKE_PAYMENTS:'1'}),ownerOrigins:[origin],customerOrigins:[customerOrigin],authenticateOwner:async token=>token==='owner-token-123456'?actor:token==='foreign-token-123456'?foreign:null});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
async function post(path:string,body:unknown,token?:string,o=origin){const r=await fetch(base+path,{method:'POST',headers:{origin:o,'content-type':'application/json',...(token?{authorization:`Bearer ${token}`}:{})},body:JSON.stringify(body)});return{status:r.status,json:await r.json()};}
async function get(flow=id(3),t=tenant,token='owner-token-123456',o=origin){const r=await fetch(base+`/api/paid-simple-flows/${flow}/health?tenantId=${t}`,{headers:{origin:o,authorization:`Bearer ${token}`}});return{status:r.status,json:await r.json()};}
const tables=['flows','flow_versions','flow_installations','flow_sessions','flow_requests','bookings','payments','capacity_holds','booking_state_history'];
async function stored(){const out=[];for(const table of tables)out.push((await pool.query(`select coalesce(jsonb_agg(x.row order by x.row::text),'[]') rows from(select to_jsonb(t) row from public.${table} t)x`)).rows[0].rows);return out;}
try{
 await pool.query("insert into auth.users(id,email) values($1,'health-owner@example.test'),($2,'health-foreign@example.test')",[actor,foreign]);await pool.query("insert into public.tenants(id,name,slug,timezone,currency) values($1,'Health','health-fixture','UTC','USD'),($2,'Foreign','health-foreign','UTC','USD')",[tenant,id(90)]);await pool.query("insert into public.tenant_members(tenant_id,user_id,role) values($1,$2,'BUSINESS_OWNER'),($3,$4,'BUSINESS_OWNER')",[tenant,actor,id(90),foreign]);
 for(const [n,schema] of [[3,3],[4,4]] as const){
  const service=id(10+n),flow=id(n);await pool.query("insert into public.services(id,tenant_id,name,archetype,currency,base_price,duration_minutes) values($1,$2,'Cleaning','simple','USD',12500,60)",[service,tenant]);
  if(schema===4)await pool.query("insert into public.service_questions(tenant_id,service_id,question_key,prompt,kind,required,choices) values($1,$2,'access','Access?','single_choice',true,$3::jsonb)",[tenant,service,JSON.stringify([{id:'present',label:'Present',priceDelta:0,priceMultiplierBp:10000},{id:'key',label:'Key',priceDelta:0,priceMultiplierBp:10000}])]);
  await pool.query('insert into public.availability_rules(tenant_id,service_id,weekday,start_minute,end_minute,capacity) select $1,$2,n,0,1440,1 from generate_series(0,6)n',[tenant,service]);await pool.query('insert into public.scheduling_policies(tenant_id,service_id,lead_time_minutes,horizon_days,slot_interval_minutes) values($1,$2,0,30,30)',[tenant,service]);
  assert.equal((await get(flow)).status,404);const publication=await post(`/api/${schema===3?'paid-simple':'paid-option'}-flows/${flow}/publish?tenantId=${tenant}`,{serviceId:service,name:'Health cleaning',allowedOrigins:[customerOrigin]},'owner-token-123456');assert.equal(publication.status,200);const installation=publication.json.data.installationId;
  const empty=await get(flow);assert.equal(empty.status,200);assert.ok(PaidInstallHealth.safeParse(empty.json.data).success);assert.equal(empty.json.data.status,'unknown');assert.equal(empty.json.data.customerEvidence.issuedSessionCount,0);assert.equal(empty.json.data.customerEvidence.lastSuccessfulLoadAt,null);
  const session=await post('/api/installations/'+installation+'/sessions',{},undefined,customerOrigin);assert.equal(session.status,200);const token=session.json.data.sessionToken,issued=(await get(flow)).json.data;assert.equal(issued.customerEvidence.issuedSessionCount,1);assert.equal(issued.customerEvidence.lastSuccessfulLoadAt,null);assert.equal(issued.status,'unknown');
  const tomorrow=new Date(Date.now()+86400000);tomorrow.setUTCHours(10,0,0,0);const request=await post('/api/flow-sessions/request',{idempotencyKey:'health-request-attempt-'+schema,answers:schema===3?{}:{access:{choiceIds:['present']}},customer:{name:'Customer',email:'health-'+schema+'@example.test'},requestedStart:tomorrow.toISOString()},token,customerOrigin);assert.equal(request.status,200);const hold=await post('/api/flow-sessions/hold',{},token,customerOrigin);assert.equal(hold.status,200);assert.equal((await get(flow)).json.data.customerEvidence.confirmedStagingBookingCount,0);const paid=await post('/api/flow-sessions/mock-payment',{},token,customerOrigin);assert.equal(paid.status,200);const booking=hold.json.data.bookingId;
  const before=await stored(),confirmed=await get(flow);assert.equal(confirmed.status,200);assert.equal(confirmed.json.data.customerEvidence.confirmedStagingBookingCount,1);assert.ok(confirmed.json.data.customerEvidence.lastConfirmedStagingBookingAt);assert.equal(confirmed.json.data.customerEvidence.lastSuccessfulLoadAt,null);assert.equal(confirmed.json.data.status,'unknown');assert.deepEqual(await stored(),before);
  await pool.query("update public.flow_sessions set expires_at=clock_timestamp()-interval '1 second',revoked=true where tenant_id=$1 and flow_id=$2",[tenant,flow]);assert.deepEqual(await get(flow),confirmed);
  const provenance=(await pool.query('delete from public.flow_requests where booking_id=$1 returning *',[booking])).rows[0];assert.equal((await get(flow)).json.data.customerEvidence.confirmedStagingBookingCount,0);await pool.query('insert into public.flow_requests(tenant_id,session_id,booking_id,idempotency_key,request_hash,option_answers) values($1,$2,$3,$4,$5,$6::jsonb)',[provenance.tenant_id,provenance.session_id,booking,provenance.idempotency_key,provenance.request_hash,provenance.option_answers===null?null:JSON.stringify(provenance.option_answers)]);
  if(schema===4){await pool.query("update public.flow_requests set option_answers='{\"access\":{\"choiceIds\":[\"invalid\"]}}' where booking_id=$1",[booking]);assert.equal((await get(flow)).json.data.customerEvidence.confirmedStagingBookingCount,0);await pool.query('update public.flow_requests set option_answers=$2::jsonb where booking_id=$1',[booking,provenance.option_answers===null?null:JSON.stringify(provenance.option_answers)]);}
  await pool.query("update public.payments set provider='unproven' where booking_id=$1",[booking]);assert.equal((await get(flow)).json.data.customerEvidence.confirmedStagingBookingCount,0);await pool.query("update public.payments set provider='staging_mock' where booking_id=$1",[booking]);
  if(schema===4){const choices=(await pool.query('select choices from public.service_questions where service_id=$1',[service])).rows[0].choices;await pool.query("update public.service_questions set choices=jsonb_set(choices,'{0,label}','\"Changed\"') where service_id=$1",[service]);assert.equal((await get(flow)).json.data.catalog.status,'incompatible');assert.equal((await get(flow)).json.data.customerEvidence.confirmedStagingBookingCount,1);await pool.query('update public.service_questions set choices=$2::jsonb where service_id=$1',[service,JSON.stringify(choices)]);}
  await pool.query('update public.services set base_price=13000 where id=$1',[service]);assert.equal((await get(flow)).json.data.catalog.status,'incompatible');assert.equal((await get(flow)).json.data.customerEvidence.confirmedStagingBookingCount,1);await pool.query('update public.services set base_price=12500,active=false where id=$1',[service]);assert.equal((await get(flow)).json.data.catalog.status,'unavailable');await pool.query('update public.services set active=true where id=$1',[service]);
  await pool.query('insert into public.flow_installations(id,tenant_id,flow_id,version_id,allowed_origins) values($1,$2,$3,$4,$5::jsonb)',[id(50+n),tenant,flow,publication.json.data.versionId,JSON.stringify([customerOrigin])]);assert.equal((await get(flow)).json.data.installation.receipt,null);assert.equal((await get(flow)).json.data.status,'degraded');await pool.query('delete from public.flow_installations where id=$1',[id(50+n)]);
  await pool.query('update public.flow_installations set allowed_origins=$2::jsonb where id=$1',[installation,JSON.stringify(['https://foreign.example.test'])]);assert.equal((await get(flow)).json.data.installation.receipt,null);assert.equal((await get(flow)).json.data.customerEvidence.confirmedStagingBookingCount,0);await pool.query('update public.flow_installations set allowed_origins=$2::jsonb where id=$1',[installation,JSON.stringify([customerOrigin])]);
 }
 // Privileged malformed fixture: publication/private service disagree. No coercion.
 await pool.query("insert into public.flows(id,tenant_id,name,status) values($1,$2,'Malformed','active'),($3,$2,'Legacy','active')",[id(20),tenant,id(22)]);
 await pool.query('insert into public.flow_versions(id,tenant_id,flow_id,source_revision,submission_mode,config,render_schema_version,paid_snapshot) select $1,$2,$3,1,v.submission_mode,v.config,v.render_schema_version,v.paid_snapshot from public.flow_versions v join public.flows f on f.published_version_id=v.id where f.id=$4',[id(21),tenant,id(20),id(3)]);
 await pool.query("insert into public.bound_flow_versions(tenant_id,flow_id,version_id,service_id,service_snapshot) select $1,$2,$3,$4,jsonb_set(b.service_snapshot,'{name}','\"Wrong binding\"') from public.bound_flow_versions b join public.flows f on f.published_version_id=b.version_id where f.id=$5",[tenant,id(20),id(21),id(13),id(3)]);
 await pool.query('insert into public.bound_flow_services values($1,$2,$3)',[tenant,id(20),id(13)]);await pool.query('update public.flows set published_version_id=$2 where id=$1',[id(20),id(21)]);assert.equal((await get(id(20))).status,404);
 await pool.query('insert into public.flow_versions(id,tenant_id,flow_id,source_revision,submission_mode,config,render_schema_version) select $1,$2,$3,1,v.submission_mode,v.config,1 from public.flow_versions v join public.flows f on f.published_version_id=v.id where f.id=$4',[id(23),tenant,id(22),id(3)]);await pool.query('update public.flows set published_version_id=$2 where id=$1',[id(22),id(23)]);assert.equal((await get(id(22))).status,404);
 const missing=await post(`/api/paid-simple-flows/${id(30)}/publish?tenantId=${tenant}`,{serviceId:id(13),name:'Missing installation',allowedOrigins:[customerOrigin]},'owner-token-123456');assert.equal(missing.status,200);await pool.query('delete from public.flow_installations where id=$1',[missing.json.data.installationId]);assert.equal((await get(id(30))).json.data.installation.status,'unavailable');assert.equal((await get(id(30))).json.data.status,'degraded');
 assert.equal((await get(id(3),tenant,'foreign-token-123456')).status,403);assert.equal((await get(id(3),id(90))).status,403);assert.equal((await get(id(3),tenant,'forged-token-123456')).status,401);assert.equal((await get(id(3),tenant,undefined,customerOrigin)).status,403);await pool.query("update public.tenant_members set role='BUSINESS_STAFF' where tenant_id=$1 and user_id=$2",[tenant,actor]);assert.equal((await get()).status,403);await pool.query('delete from public.tenant_members where tenant_id=$1 and user_id=$2',[tenant,actor]);assert.equal((await get()).status,403);await pool.query("insert into public.tenant_members(tenant_id,user_id,role) values($1,$2,'BUSINESS_OWNER')",[tenant,actor]);await pool.query("update public.tenants set status='inactive' where id=$1",[tenant]);assert.equal((await get()).status,403);await pool.query("update public.tenants set status='active' where id=$1",[tenant]);
 const before=await stored();for(let n=0;n<3;n++)assert.equal((await get()).status,200);assert.deepEqual(await stored(),before);
 console.log('PASS actual HTTP V3/V4 owner health: unknown not healthy; issuance not browser load; exact staging confirmation provenance; expired/revoked historical evidence; missing/invalid request/payment excluded; current catalog drift/unavailable; ambiguous/unapproved binding degraded; foreign/staff/revoked/inactive denied; all publication/customer/financial rows unchanged by reads');
}catch(error){throw new Error('Health integration failed: '+((error as {code?:string}).code??(error instanceof Error?error.message:'unknown')));}finally{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));await pool.end();}
