import assert from 'node:assert/strict';
import {isIP} from 'node:net';
import {Pool} from 'pg';
import {createPaidJourneyCustomerFieldAvailabilityReader} from './paid-journey-customer-field-availability';
import {createPaidJourneyCustomerFieldSessionIssuer} from './paid-journey-customer-field-session';
import {createPaidJourneyCustomerFieldDraftOperations} from './paid-journey-customer-field-draft';
import {createPaidJourneyCustomerFieldPublicationOperations} from './paid-journey-customer-field-publication';
assert.equal(process.env.PAID_JOURNEY_CUSTOMER_FIELD_AVAILABILITY_LOCAL_TEST,'1');assert.equal(process.env.PGHOST,'127.0.0.1');assert.equal(process.env.PGUSER,'postgres');
let host='127.0.0.1';if(process.env.CI==='true'){assert.equal(process.env.GITHUB_ACTIONS,'true');assert.equal(process.env.PGPORT,'5432');assert.equal(process.env.PGDATABASE,'lumin_journey_fields_availability_ci');host=process.env.PAID_JOURNEY_CUSTOMER_FIELD_AVAILABILITY_CI_DATABASE_HOST??'';assert.equal(isIP(host),4);assert.match(host,/^(?:10\.|172\.(?:1[6-9]|2[0-9]|3[01])\.|192\.168\.)/);}else{assert.notEqual(process.env.GITHUB_ACTIONS,'true');assert.equal(process.env.PGPORT,'59069');assert.match(process.env.PGDATABASE??'',/^lumin_journey_fields_availability_local_[a-z0-9_]+$/);}for(const key of ['DATABASE_URL','PGHOSTADDR','PGSERVICE','PGSERVICEFILE','PGPASSFILE','PGOPTIONS'])assert.ok(!process.env[key]);
const pool=new Pool({max:6}),id=(n:number)=>`84400000-0000-4000-8000-${String(n).padStart(12,'0')}`,actor=id(1),tenant=id(2),service=id(3),flow=id(4),foreignActor=id(21),foreignTenant=id(22),foreignService=id(23),foreignFlow=id(24),origin='https://checkout.example.test',otherOrigin='https://second.example.test';
const issue=createPaidJourneyCustomerFieldSessionIssuer(pool,[origin,otherOrigin]),read=createPaidJourneyCustomerFieldAvailabilityReader(pool,{configuredCustomerOrigins:[origin,otherOrigin]}),draft=createPaidJourneyCustomerFieldDraftOperations(pool),pub=createPaidJourneyCustomerFieldPublicationOperations(pool,{configuredCustomerOrigins:[origin,otherOrigin]});
const form={name:'Availability',presentation:{accentColor:'#0e7490' as const,layout:'compact' as const},journey:{schemaVersion:1 as const,stages:(['service','options','schedule','information','review_payment','confirmation'] as const).map(kind=>({id:kind,kind,label:kind,enabled:kind!=='options'}))},customerFields:[{id:'custom_gate',kind:'text' as const,label:'Gate',required:false,maxLength:100}],fieldBindings:[{fieldId:'custom_gate',stageId:'information'}]};
const deny=(run:()=>Promise<unknown>,code:string)=>assert.rejects(run,{code});
async function counts(){const result:Record<string,string>={};for(const table of ['bookings','payments','capacity_holds','flow_sessions','paid_journey_sessions','paid_journey_holds','paid_journey_hold_bindings','durable_outbox','flow_requests'])if((await pool.query('select to_regclass($1) r',['public.'+table])).rows[0].r)result[table]=(await pool.query(`select count(*)::text n from public.${table}`)).rows[0].n;return result;}
async function sessions(){return(await pool.query('select * from public.paid_journey_customer_field_sessions order by token_hash')).rows;}
try{
 assert.deepEqual((await pool.query('select current_database() d,current_user u,host(inet_server_addr()) h,inet_server_port() p')).rows[0],{d:process.env.PGDATABASE,u:'postgres',h:host,p:Number(process.env.PGPORT)});
 for(const [a,t,s,f,v,i] of [[actor,tenant,service,flow,id(5),id(6)],[foreignActor,foreignTenant,foreignService,foreignFlow,id(25),id(26)]] as const){await pool.query('insert into auth.users(id,email) values($1,$2)',[a,a+'@example.test']);await pool.query("insert into public.tenants(id,name,slug,timezone,currency) values($1,'Availability',$2,'UTC','USD')",[t,t]);await pool.query("insert into public.tenant_members(tenant_id,user_id,role) values($1,$2,'BUSINESS_OWNER')",[t,a]);await pool.query('select public.initialize_staging_business_profile($1,$2,$3,$4)',[a,t,'HOUSEKEEPING','availability_'+a]);await pool.query("insert into public.services(id,tenant_id,name,archetype,currency,base_price,duration_minutes) values($1,$2,'Cleaning','simple','USD',12500,60)",[s,t]);await draft.save(a,t,f,{schemaVersion:2,serviceId:s,expectedRevision:0,form});await pub.publish(a,t,f,{schemaVersion:2,expectedDraftRevision:1,allowedOrigins:[origin,otherOrigin]},v,i);}
 await issue(id(6),'a'.repeat(64),origin);await issue(id(26),'f'.repeat(64),origin);
 const day=new Date(Date.now()+86400000);day.setUTCHours(0,0,0,0);const from=day.toISOString(),to=new Date(day.getTime()+86400000).toISOString(),query={from,to},start=new Date(day.getTime()+9*3600000).toISOString(),end=new Date(day.getTime()+10*3600000).toISOString();
 for(const [t,s,capacity] of [[tenant,service,1],[foreignTenant,foreignService,8]] as const){await pool.query('insert into public.availability_rules(tenant_id,service_id,weekday,start_minute,end_minute,capacity) values($1,$2,$3,540,660,$4)',[t,s,day.getUTCDay(),capacity]);await pool.query('insert into public.scheduling_policies(tenant_id,service_id,lead_time_minutes,horizon_days,slot_interval_minutes) values($1,$2,0,60,30)',[t,s]);}
 const before=await counts(),beforeSessions=await sessions(),[first,parallel]=await Promise.all([read('a'.repeat(64),origin,query),read('a'.repeat(64),origin,query)]);assert.deepEqual(first,parallel);assert.equal(first.slots.length,3);assert.equal(first.slots[0]!.start,start);assert.ok(first.slots.every(slot=>slot.remainingCapacity===1));assert.equal(first.serviceId,service);assert.equal(first.installationId,id(6));assert.deepEqual(Object.keys(first).sort(),['durationMinutes','installationId','schemaVersion','serviceId','slots','versionId']);const foreign=await read('f'.repeat(64),origin,query);assert.equal(foreign.serviceId,foreignService);assert.ok(foreign.slots.every(slot=>slot.remainingCapacity===8));assert.deepEqual(await counts(),before);assert.deepEqual(await sessions(),beforeSessions);
 await deny(()=>read('unknown',origin,query),'INVALID_REQUEST');await deny(()=>read('b'.repeat(64),origin,query),'NOT_AVAILABLE');await deny(()=>read('a'.repeat(64),otherOrigin,query),'FORBIDDEN');await deny(()=>read('a'.repeat(64),'https://foreign.example.test',query),'FORBIDDEN');await deny(()=>read('a'.repeat(64),origin,{...query,tenantId:foreignTenant} as never),'INVALID_REQUEST');await deny(()=>read('a'.repeat(64),origin,{...query,serviceId:foreignService} as never),'INVALID_REQUEST');
 for(const role of ['anon','authenticated','service_role']){const c=await pool.connect();try{await c.query('begin');await c.query('set local role '+role);if(role==='service_role')assert.equal((await c.query('select public.paid_journey_customer_field_availability_scope($1,$2) scope',['a'.repeat(64),origin])).rows[0].scope.tenantId,tenant);else await deny(()=>c.query('select public.paid_journey_customer_field_availability_scope($1,$2)',['a'.repeat(64),origin]),'42501');await c.query('rollback');await c.query('begin');await c.query('set local role '+role);await deny(()=>c.query('select * from public.paid_journey_customer_field_sessions'),'42501');await c.query('rollback');}finally{c.release();}}
 await deny(()=>pool.query("update public.business_profiles set business_type='AUTO_DETAILING' where tenant_id=$1",[tenant]),'55000');await deny(()=>draft.save(foreignActor,tenant,id(50),{schemaVersion:2,serviceId:service,expectedRevision:0,form}),'FORBIDDEN');await deny(()=>draft.save(actor,tenant,id(51),{schemaVersion:2,serviceId:foreignService,expectedRevision:0,form}),'FORBIDDEN');
 // Existing controlled consumers are fixtures; reads never create or confirm them.
 await pool.query("insert into public.bookings(id,tenant_id,reference,state,selection,slot_start,slot_end,idempotency_key) values($1,$2,'LMN-FIELDS-AVAIL','pending_payment',$3,$4,$5,'fields-availability-0001')",[id(81),tenant,JSON.stringify({serviceId:service}),start,end]);let value=await read('a'.repeat(64),origin,query);assert.equal(value.slots.length,1);assert.equal(value.slots[0]!.start,end);
 await pool.query("insert into public.capacity_holds(id,tenant_id,service_id,slot_start,slot_end,booking_id,hold_key,status,expires_at) values($1,$2,$3,$4,$5,$6,'fields-avail-fixture','active',now()+interval '10 minutes')",[id(82),tenant,service,start,end,id(81)]);value=await read('a'.repeat(64),origin,query);assert.equal(value.slots.length,1);assert.equal(value.slots[0]!.remainingCapacity,1);
 const consumerBefore=await counts();await pool.query("insert into public.availability_overrides(tenant_id,service_id,date,kind) values($1,$2,$3,'closed')",[tenant,service,from.slice(0,10)]);assert.equal((await read('a'.repeat(64),origin,query)).slots.length,0);await pool.query('delete from public.availability_overrides where tenant_id=$1',[tenant]);assert.deepEqual(await counts(),consumerBefore);
 await pool.query('update public.services set base_price=13000 where id=$1',[service]);await deny(()=>read('a'.repeat(64),origin,query),'CONFLICT');await pool.query('update public.services set base_price=12500,active=false where id=$1',[service]);await deny(()=>read('a'.repeat(64),origin,query),'NOT_AVAILABLE');await pool.query('update public.services set active=true where id=$1',[service]);await pool.query("update public.tenants set status='suspended' where id=$1",[tenant]);await deny(()=>read('a'.repeat(64),origin,query),'NOT_AVAILABLE');await pool.query("update public.tenants set status='active' where id=$1",[tenant]);
 await pool.query("insert into public.paid_journey_customer_field_sessions select $1,tenant_id,flow_id,version_id,installation_id,service_id,publication_generation,origin,issued_at-interval '16 minutes',expires_at-interval '16 minutes' from public.paid_journey_customer_field_sessions where token_hash=$2",['e'.repeat(64),'a'.repeat(64)]);await deny(()=>read('e'.repeat(64),origin,query),'FORBIDDEN');
 await pool.query("with moment as materialized(select clock_timestamp()+interval '2 seconds' stamp) insert into public.paid_journey_customer_field_sessions select $1,tenant_id,flow_id,version_id,installation_id,service_id,publication_generation,origin,stamp-interval '15 minutes',stamp from public.paid_journey_customer_field_sessions cross join moment where token_hash=$2",['d'.repeat(64),'a'.repeat(64)]);const blocker=await pool.connect();try{await blocker.query('begin');await blocker.query('select 1 from public.services where id=$1 for update',[service]);const pending=read('d'.repeat(64),origin,query),denied=deny(()=>pending,'FORBIDDEN');let waiting=false;for(let n=0;n<40&&!waiting;n++){waiting=(await pool.query("select exists(select 1 from pg_stat_activity where datname=current_database() and wait_event_type='Lock' and query like 'select public.paid_journey_customer_field_availability_scope%') waiting")).rows[0].waiting;if(!waiting)await new Promise(r=>setTimeout(r,10));}assert.equal(waiting,true);const remaining=Number((await pool.query('select greatest(0,extract(epoch from expires_at-clock_timestamp())*1000) remaining from public.paid_journey_customer_field_sessions where token_hash=$1',['d'.repeat(64)])).rows[0].remaining);await new Promise(r=>setTimeout(r,remaining+30));await blocker.query('commit');await denied;}finally{await blocker.query('rollback');blocker.release();}
 const beforeRepublish=await counts(),lastSessions=await sessions();await read('a'.repeat(64),origin,query);assert.deepEqual(await counts(),beforeRepublish);assert.deepEqual(await sessions(),lastSessions);
 await draft.save(actor,tenant,flow,{schemaVersion:2,serviceId:service,expectedRevision:1,form:{...form,name:'B'}});await pub.publish(actor,tenant,flow,{schemaVersion:2,expectedDraftRevision:2,allowedOrigins:[origin,otherOrigin]},id(7),id(8));await deny(()=>read('a'.repeat(64),origin,query),'NOT_AVAILABLE');await issue(id(8),'b'.repeat(64),origin);await draft.save(actor,tenant,flow,{schemaVersion:2,serviceId:service,expectedRevision:2,form});await pub.publish(actor,tenant,flow,{schemaVersion:2,expectedDraftRevision:3,allowedOrigins:[origin,otherOrigin]},id(9),id(10));await deny(()=>read('a'.repeat(64),origin,query),'NOT_AVAILABLE');await deny(()=>read('b'.repeat(64),origin,query),'NOT_AVAILABLE');await issue(id(10),'c'.repeat(64),origin);assert.equal((await read('c'.repeat(64),origin,query)).installationId,id(10));await deny(()=>pool.query('select public.paid_journey_availability_scope($1,$2)',['c'.repeat(64),origin]),'42501');
 console.log('PASS V9 availability actual factory/SQL: pinned tenant+profile+catalog+origin/current generation/expiry including lock wait, capacity/dedup/closure/private privileges, no read writes');
}finally{await pool.end();}
