import {expect,it,vi} from 'vitest';
import {createPaidJourneyCustomerFieldPublicationOperations,PublishPaidJourneyCustomerFieldDraft} from './paid-journey-customer-field-publication';
const actor='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',tenant='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',flow='cccccccc-cccc-4ccc-8ccc-cccccccccccc',service='dddddddd-dddd-4ddd-8ddd-dddddddddddd',version='eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',installation='ffffffff-ffff-4fff-8fff-ffffffffffff',origin='https://checkout.example.test';
const form={name:'Housekeeping',presentation:{accentColor:'#0e7490',layout:'compact'},journey:{schemaVersion:1,stages:['service','options','schedule','information','review_payment','confirmation'].map(kind=>({id:kind,kind,label:kind,enabled:true}))},customerFields:[{id:'custom_gate',kind:'text',label:'Gate',required:false,maxLength:100},{id:'custom_code',kind:'text',label:'Code',required:false,maxLength:100,when:{fieldId:'custom_gate',equals:'yes'}}],fieldBindings:[{fieldId:'custom_gate',stageId:'information'},{fieldId:'custom_code',stageId:'information'}]};
const input={schemaVersion:2,expectedDraftRevision:1,allowedOrigins:[origin]};
const receipt={schemaVersion:2,tenantId:tenant,flowId:flow,draftRevision:1,versionId:version,installationId:installation,renderSchemaVersion:9,replayed:false};
const {replayed:_,...metadata}=receipt;
const owner={...metadata,allowedOrigins:[origin],render:{versionId:version,renderSchemaVersion:9,submissionMode:'paid_journey_customer_field_request',paymentMode:'staging_mock',simulated:true,service:{id:service,name:'Cleaning',durationMinutes:60,price:{amount:12500,currency:'USD'}},form}};
function database(returnReceipt:unknown=receipt,returnOwner:unknown=owner,code?:string){const client={query:vi.fn(async(sql:string)=>{if(sql.startsWith('select public.')){if(code)throw Object.assign(Error('private database password'),{code});return{rows:[{result:sql.includes('publish_')?returnReceipt:returnOwner}]};}return{rows:[]};}),release:vi.fn()};return{client,pool:{connect:vi.fn(async()=>client)}};}
function api(db:ReturnType<typeof database>){return createPaidJourneyCustomerFieldPublicationOperations(db.pool as never,{configuredCustomerOrigins:[origin]});}
it('explicit publication and authenticated owner read validate exact immutable receipt',async()=>{const db=database();expect(await api(db).publish(actor,tenant,flow,input as never,version,installation)).toEqual(receipt);expect(await api(db).read(actor,tenant,flow)).toEqual(owner);expect(db.client.query.mock.calls.filter(([sql])=>sql==='commit')).toHaveLength(2);});
it('same revision explicit replay permits original aliases only after owner verification',async()=>{const db=database({...receipt,replayed:true});expect(await api(db).publish(actor,tenant,flow,input as never,actor,actor)).toEqual({...receipt,replayed:true});});
for(const bad of [undefined,{...input,schemaVersion:1},{...input,expectedDraftRevision:0},{...input,expectedDraftRevision:1.5},{...input,price:1},{...input,allowedOrigins:['*']},{...input,allowedOrigins:[origin+'/']},{...input,allowedOrigins:[origin,origin]}])it('rejects malformed input before transport '+JSON.stringify(bad),async()=>{const db=database();await expect(api(db).publish(actor,tenant,flow,bad as never,version,installation)).rejects.toMatchObject({code:'INVALID_REQUEST'});expect(db.pool.connect).not.toHaveBeenCalled();});
it('rejects unapproved origins before connection',async()=>{const db=database();await expect(api(db).publish(actor,tenant,flow,{...input,allowedOrigins:['https://foreign.example.test']} as never,version,installation)).rejects.toMatchObject({code:'FORBIDDEN'});expect(db.pool.connect).not.toHaveBeenCalled();});
for(const bad of [{...receipt,tenantId:actor},{...receipt,flowId:actor},{...receipt,draftRevision:2},{...receipt,versionId:actor},{...receipt,installationId:actor},{...receipt,secret:'hidden'},{...receipt,renderSchemaVersion:8}])it('rejects forged publication receipt '+JSON.stringify(bad),async()=>{const db=database(bad);await expect(api(db).publish(actor,tenant,flow,input as never,version,installation)).rejects.toMatchObject({code:'INTERNAL_ERROR'});expect(db.client.query).not.toHaveBeenCalledWith('commit');});
for(const bad of [{...owner,tenantId:actor},{...owner,flowId:actor},{...owner,versionId:actor},{...owner,render:{...owner.render,provider:'stripe'}},{...owner,render:{...owner.render,renderSchemaVersion:8}},{...owner,render:{...owner.render,service:{...owner.render.service,price:{amount:-1,currency:'USD'}}}},{...owner,allowedOrigins:['https://foreign.example.test']},{...owner,secret:'hidden'}])it('rejects malformed owner snapshot '+JSON.stringify(bad),async()=>{const db=database(receipt,bad);await expect(api(db).read(actor,tenant,flow)).rejects.toMatchObject({code:'INTERNAL_ERROR'});expect(db.client.query).not.toHaveBeenCalledWith('commit');});
for(const [sql,expected] of [['42501','FORBIDDEN'],['P0002','NOT_AVAILABLE'],['40001','CONFLICT'],['40P01','CONFLICT'],['0A000','UNSUPPORTED_CONFIG'],['55000','INTERNAL_ERROR']])it('redacts database failure '+sql,async()=>{const db=database(receipt,owner,sql);await expect(api(db).publish(actor,tenant,flow,input as never,version,installation)).rejects.toMatchObject({code:expected});expect(db.client.query.mock.calls.filter(([query])=>query.includes('publish_'))).toHaveLength(1);expect(db.client.query).toHaveBeenCalledWith('rollback');});
it('captures caller origins before asynchronous connection',async()=>{const db=database();let release!:()=>void;db.pool.connect=vi.fn(async()=>{await new Promise<void>(resolve=>{release=resolve});return db.client});const mutable={...input,allowedOrigins:[origin]};const pending=api(db).publish(actor,tenant,flow,mutable as never,version,installation);mutable.allowedOrigins[0]='https://foreign.example.test';release();await pending;expect((db.client.query.mock.calls as unknown as [string,unknown[]][]).find(([query])=>query.includes('publish_'))?.[1][6]).toBe(JSON.stringify([origin]));});
it('never retries uncertain commit and disposes broken rollback connection',async()=>{const db=database();const original=db.client.query;db.client.query=vi.fn(async(sql:string)=>{if(sql==='commit'||sql==='rollback')throw Error('private database password');return original(sql)});await expect(api(db).publish(actor,tenant,flow,input as never,version,installation)).rejects.toMatchObject({code:'INTERNAL_ERROR'});expect(db.client.release).toHaveBeenCalledWith(true);expect(db.client.query.mock.calls.filter(([query])=>query.includes('publish_'))).toHaveLength(1);});
