import assert from "node:assert/strict";
import {randomUUID} from "node:crypto";
import {z} from "zod";
import {Pool} from "pg";
import {LOCAL_FIXTURE as F} from "./fixtures";
import {createFlowHttpServer} from "./http";
import {createTenantProfileReader,createAvailabilityReader,createFlowRepository} from "./repository";
import {createDraftWriter} from "./draft";

const blocked=["DATABASE_URL","PGHOSTADDR","PGSERVICE","PGSERVICEFILE","PGPASSFILE","PGOPTIONS"];
if(process.env.LOCAL_HARNESS!=="1"||process.env.FLOW_TEST_DISPOSABLE!=="1"||process.env.PGHOST!=="127.0.0.1"||process.env.PGUSER!=="postgres"||!/^(?:\d{4,5})$/.test(process.env.PGPORT??"")||!/^lumin_[a-z0-9_]+$/.test(process.env.PGDATABASE??"")||blocked.some(key=>process.env[key]!==undefined))throw Error("explicit disposable loopback rental HTTP fixture configuration required");
const pool=new Pool({host:"127.0.0.1",port:Number(process.env.PGPORT),database:process.env.PGDATABASE,user:"postgres",password:process.env.PGPASSWORD,max:8,connectionTimeoutMillis:5000,idleTimeoutMillis:5000,statement_timeout:10000});
const tenant=randomUUID(),foreignTenant=randomUUID(),service=randomUUID(),foreignService=randomUUID(),resource=randomUUID(),run=randomUUID();
const owner=randomUUID(),staff=randomUUID(),foreignOwner=randomUUID();
const ownerToken="rental-owner-"+run,staffToken="rental-staff-"+run,foreignToken="rental-foreign-"+run;
const identity=async(token:string)=>token===ownerToken?owner:token===staffToken?staff:token===foreignToken?foreignOwner:null;
const day=new Date();day.setUTCHours(0,0,0,0);day.setUTCDate(day.getUTCDate()+1);
const slotStart=new Date(day.getTime()+10*60*60*1000).toISOString(),slotEnd=new Date(day.getTime()+11*60*60*1000).toISOString(),from=day.toISOString(),to=new Date(day.getTime()+86400000-1).toISOString();
const rentalSelection={serviceId:service,itemQuantities:{},addonIds:[],answers:{},rentalPeriods:1};
const Profile=z.object({schemaVersion:z.literal(1),profile:z.object({id:z.literal(tenant),name:z.literal("HTTP Rental"),slug:z.string().startsWith("rental-"),timezone:z.literal("UTC"),currency:z.literal("USD"),status:z.literal("active")}).strict()}).strict();
const Slots=z.object({schemaVersion:z.literal(1),serviceId:z.literal(service),durationMinutes:z.literal(60),slots:z.array(z.object({start:z.string().datetime(),end:z.string().datetime(),remainingCapacity:z.number().int().positive()}).strict())}).strict();
const Draft=z.object({schemaVersion:z.literal(1),bookingId:z.string().uuid(),reference:z.string().min(1),state:z.literal("draft")}).strict();
type ReservationResult={result:"GRANTED"|"NO_CAPACITY";reservation_id:string|null;reservation_status:"held"|"consumed"|null;expires_at:string|null};
const server=createFlowHttpServer({repository:createFlowRepository(pool),authenticateOwner:identity,ownerOrigins:[F.ownerOrigin],customerOrigins:[F.customerOrigin],tenantProfile:createTenantProfileReader(pool),availability:createAvailabilityReader(pool,()=>new Date().toISOString()),draft:createDraftWriter(pool)});
let base="";
async function request(path:string,body:unknown|undefined,token=ownerToken){const response=await fetch(base+path,{method:body===undefined?"GET":"POST",redirect:"error",signal:AbortSignal.timeout(10000),headers:{origin:F.ownerOrigin,authorization:"Bearer "+token,"content-type":"application/json"},...(body===undefined?{}:{body:JSON.stringify(body)})});assert.match(response.headers.get("content-type")??"",/^application\/json/);return{status:response.status,body:await response.json()};}
async function success<T>(path:string,schema:z.ZodType<T>,body:unknown|undefined,token=ownerToken){const reply=await request(path,body,token);assert.equal(reply.status,200);return schema.parse(z.object({ok:z.literal(true),data:z.unknown()}).strict().parse(reply.body).data);}
// The HTTP server has no resource reservation route. This direct call is therefore
// explicitly scoped to the service-role resource authority, while profile,
// availability, tenant context and draft creation remain HTTP-authenticated.
async function reserve(tenantId:string,resourceId:string,bookingId:string):Promise<ReservationResult>{const c=await pool.connect();try{await c.query("begin");await c.query("set local role service_role");const result=await c.query<ReservationResult>("select result,reservation_id,reservation_status,expires_at from public.reserve_resource($1::uuid,$2::uuid,$3::timestamptz,$4::timestamptz,$5::uuid,interval '5 minutes')",[tenantId,resourceId,slotStart,slotEnd,bookingId]);await c.query("commit");assert.equal(result.rows.length,1);return result.rows[0]!;}catch(error){await c.query("rollback").catch(()=>{});throw error;}finally{c.release();}}
async function release(bookingId:string){const c=await pool.connect();try{await c.query("begin");await c.query("set local role service_role");const result=await c.query<{released:number}>("select public.release_resource_holds($1::uuid) released",[bookingId]);await c.query("commit");return Number(result.rows[0]?.released??0);}catch(error){await c.query("rollback").catch(()=>{});throw error;}finally{c.release();}}
try{
 await pool.query("insert into auth.users(id,email) values($1,$2),($3,$4),($5,$6) on conflict(id) do nothing",[owner,"http-rental-owner-"+run+"@example.test",staff,"http-rental-staff-"+run+"@example.test",foreignOwner,"http-rental-foreign-"+run+"@example.test"]);
 await pool.query("insert into public.tenants(id,name,slug,timezone,currency) values($1,'HTTP Rental',$3,'UTC','USD'),($2,'HTTP Foreign Rental',$4,'UTC','USD')",[tenant,foreignTenant,"rental-"+run,"foreign-rental-"+run]);
 await pool.query("insert into public.tenant_members(tenant_id,user_id,role) values($1,$2,'BUSINESS_OWNER'),($1,$3,'BUSINESS_STAFF'),($4,$5,'BUSINESS_OWNER')",[tenant,owner,staff,foreignTenant,foreignOwner]);
 await pool.query("insert into public.services(id,tenant_id,name,archetype,currency,base_price,duration_minutes,tax_rate_bp,rental) values($1,$2,'Vehicle rental','rental','USD',0,60,0,$3::jsonb),($4,$5,'Foreign rental','rental','USD',0,60,0,$3::jsonb)",[service,tenant,JSON.stringify({periodMinutes:60,pricePerPeriod:15000,minPeriods:1,maxPeriods:4,depositAmount:0}),foreignService,foreignTenant]);
 await pool.query("insert into public.resources(id,tenant_id,name,kind,capacity,active) values($1,$2,'Synthetic rental vehicle','vehicle',1,true)",[resource,tenant]);
 await pool.query("insert into public.service_resources(tenant_id,service_id,resource_id,quantity_required) values($1,$2,$3,1)",[tenant,service,resource]);
 await pool.query("insert into public.scheduling_policies(tenant_id,service_id,lead_time_minutes,horizon_days,slot_interval_minutes) values($1,$2,0,30,30)",[tenant,service]);
 await pool.query("insert into public.availability_rules(tenant_id,service_id,weekday,start_minute,end_minute,capacity) select $1,$2,n,540,1020,1 from generate_series(0,6)n",[tenant,service]);
 await new Promise<void>(resolve=>server.listen(0,"127.0.0.1",resolve));base="http://127.0.0.1:"+((server.address() as {port:number}).port);
 assert.deepEqual(await success("/health",z.object({mode:z.literal("LOCAL_HARNESS"),providerConnections:z.literal(false)}),undefined),{mode:"LOCAL_HARNESS",providerConnections:false});
 await success("/api/profile?tenantId="+tenant,Profile,undefined);assert.equal((await request("/api/profile?tenantId="+foreignTenant,undefined)).status,404);assert.equal((await request("/api/profile?tenantId="+tenant,undefined,"invalid-synthetic-token")).status,401);assert.equal((await request("/api/profile?tenantId="+tenant,undefined,foreignToken)).status,404);
 const params=new URLSearchParams({tenantId:tenant,serviceId:service,from,to});const available=await success("/api/availability?"+params.toString(),Slots,undefined);assert.ok(available.slots.some(slot=>slot.start===slotStart&&slot.end===slotEnd));assert.equal((await request("/api/availability?"+new URLSearchParams({tenantId:foreignTenant,serviceId:service,from,to}).toString(),undefined)).status,404);
 const draftInput={idempotencyKey:"http-rental-a-"+run,serviceId:service,slotStart,slotEnd,selection:rentalSelection,customer:{name:"HTTP Rental Customer",email:"http-rental-"+run+"@example.test"}};
 const bookingA=await success("/api/bookings/draft?tenantId="+tenant,Draft,draftInput);const bookingB=await success("/api/bookings/draft?tenantId="+tenant,Draft,{...draftInput,idempotencyKey:"http-rental-b-"+run},staffToken);assert.deepEqual(await success("/api/bookings/draft?tenantId="+tenant,Draft,draftInput),bookingA);assert.equal((await request("/api/bookings/draft?tenantId="+foreignTenant,draftInput)).status,403);assert.equal((await request("/api/bookings/draft?tenantId="+tenant,draftInput,foreignToken)).status,403);assert.equal((await request("/api/bookings/draft?tenantId="+tenant,{...draftInput,serviceId:foreignService,idempotencyKey:"http-rental-foreign-"+run})).status,404);
 const invalidRentalSelection={...rentalSelection};delete (invalidRentalSelection as {rentalPeriods?:number}).rentalPeriods;assert.equal((await request("/api/bookings/draft?tenantId="+tenant,{...draftInput,selection:invalidRentalSelection,idempotencyKey:"http-rental-invalid-periods-"+run})).status,422);
 const foreignBooking=await success("/api/bookings/draft?tenantId="+foreignTenant,Draft,{...draftInput,serviceId:foreignService,idempotencyKey:"http-rental-foreign-owner-"+run,customer:{name:"Foreign Rental",email:"foreign-"+run+"@example.test"}},foreignToken);
 const stored=await pool.query<{idempotency_key:string;selection:unknown;state:string;pricing:unknown;payment_id:string|null}>("select idempotency_key,selection,state,pricing,payment_id from public.bookings where id=any($1::uuid[]) order by idempotency_key",[[bookingA.bookingId,bookingB.bookingId]]);assert.equal(stored.rows.length,2);for(const row of stored.rows){assert.deepEqual(row.selection,rentalSelection,"canonical rental Selection v1 persisted exactly");assert.equal(row.state,"draft");assert.deepEqual(row.pricing,{});assert.equal(row.payment_id,null);}
 const attempts=await Promise.all([reserve(tenant,resource,bookingA.bookingId),reserve(tenant,resource,bookingB.bookingId)]);assert.deepEqual(attempts.map(x=>x.result).sort(),["GRANTED","NO_CAPACITY"]);const winner=attempts.find(x=>x.result==="GRANTED")!,loser=attempts.find(x=>x.result==="NO_CAPACITY")!;assert.equal(winner.reservation_status,"held");assert.ok(winner.reservation_id);assert.deepEqual(loser,{result:"NO_CAPACITY",reservation_id:null,reservation_status:null,expires_at:null});
 const foreign=await reserve(foreignTenant,resource,foreignBooking.bookingId);assert.deepEqual(foreign,{result:"NO_CAPACITY",reservation_id:null,reservation_status:null,expires_at:null});const winnerBooking=attempts[0]?.result==="GRANTED"?bookingA.bookingId:bookingB.bookingId;const replay=await reserve(tenant,resource,winnerBooking);assert.equal(replay.result,"GRANTED");assert.equal(replay.reservation_id,winner.reservation_id);assert.equal(replay.expires_at,winner.expires_at);
 const persisted=await pool.query("select count(*)::int n from public.resource_reservations where tenant_id=$1 and resource_id=$2 and status in ('held','consumed')",[tenant,resource]);assert.equal(persisted.rows[0]?.n,1);const effects=await pool.query("select (select count(*)::int from public.payments where booking_id in ($1::uuid,$2::uuid,$3::uuid)) payments,(select count(*)::int from public.capacity_holds where booking_id in ($1::uuid,$2::uuid,$3::uuid)) capacity_holds,(select count(*)::int from public.bookings where id in ($1::uuid,$2::uuid,$3::uuid) and state='confirmed') confirmed",[bookingA.bookingId,bookingB.bookingId,foreignBooking.bookingId]);assert.deepEqual(effects.rows[0],{payments:0,capacity_holds:0,confirmed:0});assert.equal(await release(winnerBooking),1);const after=await pool.query("select count(*)::int n from public.resource_reservations where tenant_id=$1 and resource_id=$2 and status in ('held','consumed')",[tenant,resource]);assert.equal(after.rows[0]?.n,0);
 console.log("PASS disposable HTTP rental flow plus scoped service-role resource race: authenticated profile/availability/draft, one GRANTED/one NO_CAPACITY, foreign-resource denial, idempotent replay, release, and no payment/capacity/confirmation side effects");
}finally{try{server.closeAllConnections();if(server.listening)await new Promise<void>((resolve,reject)=>server.close(error=>error?reject(error):resolve()));await pool.query("delete from public.tenants where id in ($1::uuid,$2::uuid)",[tenant,foreignTenant]);await pool.query("delete from auth.users where id in ($1::uuid,$2::uuid,$3::uuid)",[owner,staff,foreignOwner]);assert.equal((await pool.query("select count(*)::int count from public.tenants where id in ($1::uuid,$2::uuid)",[tenant,foreignTenant])).rows[0].count,0);assert.equal((await pool.query("select count(*)::int count from auth.users where id in ($1::uuid,$2::uuid,$3::uuid)",[owner,staff,foreignOwner])).rows[0].count,0);}finally{await pool.end();}}
