// @vitest-environment jsdom
import {afterEach,describe,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen} from '@testing-library/react';
import {ConditionalCustomerFieldForm,editConditionalCustomerAnswer} from '../src/ConditionalCustomerFieldForm';
import {canonicalizeConditionalCustomerFieldAnswers} from '@lumin/contracts';
afterEach(cleanup);
const fields=[{id:'custom_access',kind:'text',label:'Access',required:true,maxLength:20},{id:'custom_gate',kind:'text',label:'Gate code',required:true,maxLength:20,when:{fieldId:'custom_access',equals:'gate'}},{id:'custom_notes',kind:'text',label:'Gate notes',required:false,maxLength:30,when:{fieldId:'custom_gate',equals:'123'}}];
const configuration={schemaVersion:3,customerFields:fields};
describe('conditional customer field editing',()=>{
 it('removes deactivated descendant values only on an explicit visible source edit',()=>{const original={custom_access:'gate',custom_gate:'123',custom_notes:'Private note'};expect(editConditionalCustomerAnswer(configuration,original,'custom_access','key')).toEqual({custom_access:'key'});expect(original.custom_notes).toBe('Private note');});
 it('removes only descendants that became hidden and preserves exact values',()=>{expect(editConditionalCustomerAnswer(configuration,{custom_access:'gate',custom_gate:'123',custom_notes:'Note'},'custom_gate',' 234 ')).toEqual({custom_access:'gate',custom_gate:' 234 '});});
 it('activates a required field without fabricating an answer',()=>{const next=editConditionalCustomerAnswer(configuration,{custom_access:'key'},'custom_access','gate');expect(next).toEqual({custom_access:'gate'});expect(()=>canonicalizeConditionalCustomerFieldAnswers(configuration,next)).toThrow();});
 it('does not revive discarded hidden answers when a source is reactivated',()=>{const hidden=editConditionalCustomerAnswer(configuration,{custom_access:'gate',custom_gate:'123'},'custom_access','key');expect(editConditionalCustomerAnswer(configuration,hidden,'custom_access','gate')).toEqual({custom_access:'gate'});});
 it.each(['custom_gate','custom_price','custom_unknown'])('rejects editing hidden or unknown %s',id=>{expect(()=>editConditionalCustomerAnswer(configuration,{custom_access:'key'},id,'123')).toThrow();});
 it.each([{custom_access:'key',custom_gate:'123'},{custom_access:'gate',custom_unknown:'secret'}])('rejects invalid current state rather than laundering it',answers=>{expect(()=>editConditionalCustomerAnswer(configuration,answers,'custom_access','key')).toThrow();});
 it.each(['a'.repeat(21),'\u0000','\ud800'])('rejects oversized or invalid edited text',value=>{expect(()=>editConditionalCustomerAnswer(configuration,{},'custom_access',value)).toThrow();});
 it('renders only visible fields with associated labels and native requiredness',()=>{render(<ConditionalCustomerFieldForm configuration={configuration} answers={{custom_access:'gate'}} onChange={()=>{}}/>);expect(screen.getByLabelText('Access')).toHaveProperty('required',true);expect(screen.getByLabelText('Gate code')).toHaveProperty('required',true);expect(screen.queryByLabelText(/Gate notes/)).toBeNull();});
 it('emits an explicit source edit with hidden descendants cleared',()=>{const onChange=vi.fn();render(<ConditionalCustomerFieldForm configuration={configuration} answers={{custom_access:'gate',custom_gate:'123',custom_notes:'secret'}} onChange={onChange}/>);fireEvent.change(screen.getByLabelText('Access'),{target:{value:'key'}});expect(onChange).toHaveBeenCalledExactlyOnceWith({custom_access:'key'});});
 it('freezes all controls during uncertain or pending submission',()=>{const onChange=vi.fn();render(<ConditionalCustomerFieldForm configuration={configuration} answers={{}} onChange={onChange} disabled/>);expect(screen.getByRole('group')).toHaveProperty('disabled',true);expect(onChange).not.toHaveBeenCalled();});
 it.each([{configuration:{...configuration,schemaVersion:2},answers:{}},{configuration,answers:{custom_unknown:'private secret'}},{configuration,answers:{custom_access:'key',custom_gate:'private secret'}}])('fails closed without rendering or exposing malformed answers',props=>{render(<ConditionalCustomerFieldForm {...props} onChange={()=>{}}/>);expect(screen.getByRole('alert')).toBeTruthy();expect(screen.queryAllByRole('textbox')).toHaveLength(0);expect(document.body.textContent).not.toContain('private secret');});
});
