import {it,expect,vi} from 'vitest';
import {ConfigurableRender,SessionRender,clearHiddenAnswers,canonicalConfigurableAnswers,canonicalPaidOptionAnswers,visibleSteps} from '../src/configurable';
import {createFlowClient} from '../src/client';
const id='11111111-1111-4111-8111-111111111111';
const render=ConfigurableRender.parse({versionId:id,renderSchemaVersion:2,submissionMode:'unconfirmed_request',service:{id,name:'Test',durationMinutes:30,questions:[{id:'hasOwnProperty',prompt:'Mode',kind:'single_choice',required:false,choices:[{id:'toString',label:'More'},{id:'no',label:'Less'}]},{id:'count',prompt:'Count',kind:'quantity',required:false,choices:[],minQty:0,maxQty:3},{id:'multi',prompt:'Options',kind:'multi_choice',required:false,choices:[{id:'😀',label:'First'},{id:'é',label:'Second'}]}]},config:{key:'test',steps:[{key:'mode',questionKey:'hasOwnProperty',kind:'question',required:false},{key:'count',questionKey:'count',kind:'question',required:true,visibleWhen:{field:'hasOwnProperty',op:'eq',value:'toString'}},{key:'multi',questionKey:'multi',kind:'question',required:false}]}});
const reply=(data:unknown)=>new Response(JSON.stringify({ok:true,data}));
it('inherited-looking optional names remain absent; explicit choice controls visibility',()=>{expect(visibleSteps(render,{}).map(s=>s.questionKey)).toEqual(['hasOwnProperty','multi']);expect(canonicalConfigurableAnswers(render,{})).toEqual({});expect(visibleSteps(render,{hasOwnProperty:{choiceIds:['toString']}})).toHaveLength(3);});
it('clears hidden answers atomically and preserves visible optional answers',()=>{const input={hasOwnProperty:{choiceIds:['no']},count:{quantity:2},multi:{choiceIds:['é']}};expect(clearHiddenAnswers(render,input)).toEqual({hasOwnProperty:{choiceIds:['no']},multi:{choiceIds:['é']}});expect(input.count.quantity).toBe(2);expect(()=>canonicalConfigurableAnswers(render,input)).toThrow('HIDDEN_ANSWER');});
it('enforces visible step requiredness despite optional catalog floor, quantity zero and bounds',()=>{const a={hasOwnProperty:{choiceIds:['toString']}};expect(()=>canonicalConfigurableAnswers(render,a)).toThrow('MISSING_REQUIRED');expect(canonicalConfigurableAnswers(render,{...a,count:{quantity:0}})).toMatchObject({count:{quantity:0}});expect(()=>canonicalConfigurableAnswers(render,{...a,count:{quantity:4}})).toThrow();});
it('canonicalizes multi selections by pinned Unicode ordinal and preserves semantic retries',()=>{expect(canonicalConfigurableAnswers(render,{multi:{choiceIds:['é','😀']}})).toEqual({multi:{choiceIds:['😀','é']}});expect(()=>canonicalConfigurableAnswers(render,{multi:{choiceIds:['é','é']}})).toThrow();});
it('strict union preserves legacy shape and rejects unknown or downgraded markers',()=>{const legacy={versionId:id,config:{key:'old',steps:[]},service:render.service};expect(SessionRender.safeParse({...legacy,config:{key:'old',steps:[{key:'mode',questionKey:'hasOwnProperty',kind:'question',required:false}]}}).success).toBe(true);for(const change of [{renderSchemaVersion:3},{submissionMode:'confirmed'},{payment:true}])expect(SessionRender.safeParse({...render,...change}).success).toBe(false);});
it('V2 transport uses separate POST namespace and mandatory returned discriminator',async()=>{const fetcher=vi.fn(async(_url:string,_options:RequestInit)=>reply({flowId:id,revision:2,authoringVersion:2}));const c=createFlowClient('https://api.example',false,fetcher as unknown as typeof fetch);await c.saveConfigurable('token',id,id,{expectedRevision:1,serviceId:id,name:'Request',authoring:{authoringVersion:2,config:render.config,questionOverrides:{}}});expect(fetcher.mock.calls[0]![0]).toContain('/api/configurable-flows/');expect(fetcher.mock.calls[0]![1]).toMatchObject({method:'POST',credentials:'omit'});const bad=createFlowClient('https://api.example',false,async()=>reply({flowId:id,revision:2}));await expect(bad.saveConfigurable('token',id,id,{expectedRevision:1,serviceId:id,name:'Request',authoring:{authoringVersion:2,config:render.config,questionOverrides:{}}})).rejects.toMatchObject({code:'INTERNAL_ERROR'});});
it('V2 session responses still reject late parsed bodies after logout',async()=>{let done!:(x:unknown)=>void;const c=createFlowClient('https://api.example',false,async()=>({ok:true,json:()=>new Promise(r=>done=r)}) as Response);const pending=c.session(id);await Promise.resolve();c.invalidate();done({ok:true,data:{sessionToken:'a'.repeat(43),expiresAt:'2099-01-01T00:00:00Z',render}});await expect(pending).rejects.toMatchObject({code:'UNAUTHENTICATED'});});

const optionRender={versionId:id,renderSchemaVersion:4 as const,submissionMode:'paid_option_request' as const,paymentMode:'staging_mock' as const,simulated:true as const,service:{id,name:'Pinned options',durationMinutes:30,price:{amount:12500,currency:'USD'},questions:[{id:'hasOwnProperty',prompt:'Choose a visit',kind:'single_choice' as const,required:true as const,choices:[{id:'toString',label:'First visit'},{id:'return',label:'Return visit'}]}] as [{id:string;prompt:string;kind:'single_choice';required:true;choices:{id:string;label:string}[]}]} };
it('V4 parses only the shared pinned required option contract with no legacy fallback or caller prices',()=>{
 expect(SessionRender.parse(optionRender)).toEqual(optionRender);const q=optionRender.service.questions[0];for(const value of [{...optionRender,renderSchemaVersion:5},{...optionRender,submissionMode:'paid_service_request'},{...optionRender,paymentMode:'stripe'},{...optionRender,simulated:false},{...optionRender,config:{steps:[]}},{...optionRender,service:{...optionRender.service,questions:[]}},{...optionRender,service:{...optionRender.service,questions:[q,q]}},{...optionRender,service:{...optionRender.service,questions:[{...q,required:false}]}},{...optionRender,service:{...optionRender.service,questions:[{...q,choices:[q.choices[0]]}]}},{...optionRender,service:{...optionRender.service,questions:[{...q,choices:Array.from({length:11},(_,i)=>({id:String(i),label:'Choice'}))}]}},{...optionRender,service:{...optionRender.service,questions:[{...q,choices:[q.choices[0],q.choices[0]]}]}},{...optionRender,service:{...optionRender.service,questions:[{...q,choices:[{...q.choices[0],price:1},q.choices[1]]}]}},{...optionRender,service:{...optionRender.service,questions:[{...q,id:'__proto__'}]}}])expect(SessionRender.safeParse(value).success).toBe(false);
});
it('V4 canonical answers require exactly one own catalog choice and remain immutable after input edits',()=>{
 const input={hasOwnProperty:{choiceIds:['toString']}};const result=canonicalPaidOptionAnswers(optionRender,input);expect(result).toEqual(input);input.hasOwnProperty.choiceIds[0]='return';expect(result).toEqual({hasOwnProperty:{choiceIds:['toString']}});for(const value of [{},{foreign:{choiceIds:['toString']}},{hasOwnProperty:{choiceIds:[]}},{hasOwnProperty:{choiceIds:['toString','return']}},{hasOwnProperty:{choiceIds:['foreign']}},{hasOwnProperty:{choiceIds:['toString'],quantity:0}},{hasOwnProperty:{choiceIds:['toString']},foreign:{choiceIds:['return']}},Object.create({hasOwnProperty:{choiceIds:['toString']}}),{hasOwnProperty:Object.create({choiceIds:['toString']})}])expect(()=>canonicalPaidOptionAnswers(optionRender,value as never)).toThrow();
});
