import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {fileURLToPath,pathToFileURL} from 'node:url';
const sha='0123456789abcdef0123456789abcdef01234567',id=n=>`10000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const probe=()=>({schemaVersion:1,result:'PASS',environment:'staging',releaseSha:sha,checks:[{check:'health',status:200,requestId:id(1)},{check:'ready',status:200,requestId:id(2)},{check:'version',status:200,requestId:id(3)},{check:'anonymous_owner_history',status:401,requestId:id(4)},{check:'foreign_owner_history',status:403,requestId:id(5)}],requestIdsUnique:true,spoofedIdRejected:true,readOnly:true,authenticatedOwnerAcceptance:false,providerDeliveryProof:false});
const row=n=>({event:'staging_request',schemaVersion:1,service:'booking-lumin-api',environment:'staging',releaseSha:sha,requestId:id(n),method:n<=5?'GET':'POST',routeFamily:n===1?'health':n===2?'readiness':n===3?'version':n<=5?'owner_notifications':'customer_flow',outcome:'completed',statusCode:n===4?401:n===5?403:200,durationMs:1,durationCapped:false});
const raw=record=>({id:'render-log-'+record.requestId,labels:{instance:'PRIVATE_INSTANCE',canary:'lumin_observability_header_canary',secret:'PRIVATE_LABEL'},message:JSON.stringify(record),timestamp:'2026-10-05T12:34:56.123456789Z'});
export async function runSelfTest(module){const {validateObservabilityLogs}=module??await import('./phase-a-staging-observability-logs.mjs');let checks=0;
 const validate=(records=Array.from({length:100},(_,i)=>row(i+1)),evidence=probe(),expected=sha)=>validateObservabilityLogs(expected,evidence,records);
 const rejected=(records,evidence=probe(),expected=sha)=>{assert.throws(()=>validate(records,evidence,expected),error=>{assert.equal(error.code,'INVALID_EVIDENCE');assert.equal(error.message,'Offline observability records could not be verified.');assert(!JSON.stringify(error).includes('PRIVATE'));return true;});checks++;};
 for(const records of [Array.from({length:5},(_,i)=>row(i+1)),Array.from({length:100},(_,i)=>row(i+1)),Array.from({length:100},(_,i)=>raw(row(i+1))).reverse(),Array.from({length:100},(_,i)=>i%2?raw(row(i+1)):row(i+1))]){const evidence=probe(),before=JSON.stringify({records,evidence}),result=validate(records,evidence);assert.deepEqual(result,{schemaVersion:1,result:'PASS',recordsValidated:records.length,matchedRequests:5,requestIds:[1,2,3,4,5].map(id)});assert.equal(JSON.stringify({records,evidence}),before,'pure validator');assert(Object.isFrozen(result)&&Object.isFrozen(result.requestIds));assert(!/PRIVATE|canary|message|labels|timestamp|https:/.test(JSON.stringify(result)));checks++;}
 const labels={};let labelGetter=false;Object.defineProperty(labels,'secret',{enumerable:true,get(){labelGetter=true;throw Error('PRIVATE_GETTER');}});const labelRows=Array.from({length:5},(_,i)=>({...raw(row(i+1)),labels:i===0?labels:[]}));assert.equal(validate(labelRows).matchedRequests,5);assert(!labelGetter);checks++;
 for(const method of ['GET','POST','PUT','PATCH','DELETE','HEAD','OPTIONS','OTHER']){const records=Array.from({length:6},(_,i)=>row(i+1));records[5].method=method;assert.equal(validate(records).recordsValidated,6);checks++;}
 for(const routeFamily of ['health','readiness','version','customer_flow','owner_notifications','owner_booking','owner_business','owner_catalog','owner_publication','owner_roster','other']){const records=Array.from({length:6},(_,i)=>row(i+1));records[5].routeFamily=routeFamily;assert.equal(validate(records).recordsValidated,6);checks++;}
 for(const background of [{...row(6),outcome:'aborted',statusCode:null},{...row(6),durationMs:0},{...row(6),durationMs:300000,durationCapped:false},{...row(6),durationMs:300000,durationCapped:true},{...row(6),statusCode:999},{...row(6),statusCode:100}]){assert.equal(validate([...Array.from({length:5},(_,i)=>row(i+1)),background]).recordsValidated,6);checks++;}
 const changes=[{event:'PRIVATE'},{schemaVersion:2},{service:'PRIVATE_SERVICE'},{environment:'production'},{releaseSha:null},{releaseSha:'a'.repeat(40)},{releaseSha:sha.toUpperCase()},{requestId:'PRIVATE_ID'},{requestId:'10000000-0000-1000-8000-000000000006'},{requestId:'10000000-0000-4000-0000-000000000006'},{method:'PRIVATE_METHOD'},{routeFamily:'PRIVATE_ROUTE_QUERY'},{outcome:'PRIVATE'},{outcome:'aborted'},{statusCode:null},{statusCode:99},{statusCode:1000},{statusCode:200.5},{statusCode:'200'},{durationMs:-1},{durationMs:300001},{durationMs:1.5},{durationMs:NaN},{durationMs:Infinity},{durationMs:'1'},{durationCapped:'false'},{durationCapped:true},{headers:'PRIVATE_TOKEN'},{query:'lumin_observability_query_canary'},{message:'PRIVATE_RAW_ERROR'}];
 for(const change of changes){const records=Array.from({length:6},(_,i)=>row(i+1));records[5]={...records[5],...change};rejected(records);}
 for(const missing of Object.keys(row(1))){const records=Array.from({length:6},(_,i)=>row(i+1));delete records[5][missing];rejected(records);}
 for(const change of [{method:'POST'},{routeFamily:'owner_booking'},{outcome:'aborted',statusCode:null},{statusCode:404}]){const records=Array.from({length:6},(_,i)=>row(i+1));records[3]={...records[3],...change};rejected(records);}
 const missing=Array.from({length:6},(_,i)=>row(i+1));missing[3]=row(7);rejected(missing);rejected([...Array.from({length:5},(_,i)=>row(i+1)),row(4)]);rejected([...Array.from({length:6},(_,i)=>row(i+1)),row(6)]);
 const wrongProbe=[{result:'FAIL'},{schemaVersion:2},{environment:'production'},{releaseSha:'a'.repeat(40)},{requestIdsUnique:false},{spoofedIdRejected:false},{readOnly:false},{authenticatedOwnerAcceptance:true},{providerDeliveryProof:true},{query:'PRIVATE'}];for(const change of wrongProbe)rejected(Array.from({length:5},(_,i)=>row(i+1)),{...probe(),...change});
 for(const modify of [p=>p.checks.pop(),p=>p.checks.push(p.checks[0]),p=>p.checks.reverse(),p=>p.checks[3].status=403,p=>p.checks[3].requestId=id(1),p=>p.checks[3].requestId='PRIVATE',p=>p.checks[3].method='GET']){const p=probe();modify(p);rejected(Array.from({length:5},(_,i)=>row(i+1)),p);}
 for(const expected of [null,'',sha.toUpperCase(),'PRIVATE',sha+'0',sha+'\n'])rejected(Array.from({length:5},(_,i)=>row(i+1)),probe(),expected);
 for(const entries of [null,{},[],[row(1)],Array.from({length:1001},(_,i)=>row(i+1))])rejected(entries);
 for(const change of [{id:7},{id:''},{id:'x'.repeat(257)},{labels:null},{labels:'PRIVATE'},{timestamp:7},{timestamp:''},{timestamp:'x'.repeat(129)},{message:'PRIVATE not JSON'},{message:'PRIVATE'.repeat(1000)},{message:'prefix '+JSON.stringify(row(6))},{message:JSON.stringify({...row(6),recipient:'PRIVATE'})},{extra:'PRIVATE'}]){const records=Array.from({length:6},(_,i)=>raw(row(i+1)));records[5]={...records[5],...change};rejected(records);}
 let invoked=false;const protectedRow=row(6);Object.defineProperty(protectedRow,'method',{enumerable:true,get(){invoked=true;throw Error('PRIVATE_ACCESSOR');}});rejected([...Array.from({length:5},(_,i)=>row(i+1)),protectedRow]);assert(!invoked);
 const protectedRaw=raw(row(6));Object.defineProperty(protectedRaw,'message',{enumerable:true,get(){invoked=true;throw Error('PRIVATE_ACCESSOR');}});rejected([...Array.from({length:5},(_,i)=>row(i+1)),protectedRaw]);assert(!invoked);
 const protectedArray=Array.from({length:6},(_,i)=>row(i+1));Object.defineProperty(protectedArray,'5',{enumerable:true,get(){invoked=true;throw Error('PRIVATE_ACCESSOR');}});rejected(protectedArray);assert(!invoked);const sparse=Array.from({length:6},(_,i)=>row(i+1));delete sparse[5];rejected(sparse);
 const extraArray=Array.from({length:5},(_,i)=>row(i+1));extraArray.secret='PRIVATE';rejected(extraArray);const symbolRow=row(6);symbolRow[Symbol('PRIVATE')]='PRIVATE';rejected([...Array.from({length:5},(_,i)=>row(i+1)),symbolRow]);
 const thousand=Array.from({length:1000},(_,i)=>row(i+1));assert.equal(validate(thousand).recordsValidated,1000);checks++;
 const maxMessage=raw(row(6));maxMessage.message=JSON.stringify(row(6)).padStart(4096,' ');assert.equal(validate([...Array.from({length:5},(_,i)=>row(i+1)),maxMessage]).recordsValidated,6);checks++;
 const originalParse=JSON.parse;let parsed=0;try{JSON.parse=(...args)=>{parsed++;return originalParse(...args);};for(const message of [JSON.stringify(row(6)).padStart(4097,' '),JSON.stringify({...row(6),raw:'é'.repeat(3000)})]){parsed=0;rejected([...Array.from({length:5},(_,i)=>row(i+1)),{...raw(row(6)),message}]);assert.equal(parsed,0,'oversized messages rejected before parsing');}}finally{JSON.parse=originalParse;}
 let proxyInvoked=false;const traps={getPrototypeOf(){proxyInvoked=true;throw Error('PRIVATE_PROXY');},ownKeys(){proxyInvoked=true;throw Error('PRIVATE_PROXY');},getOwnPropertyDescriptor(){proxyInvoked=true;throw Error('PRIVATE_PROXY');}};
 rejected(new Proxy(Array.from({length:5},(_,i)=>row(i+1)),traps));rejected([...Array.from({length:5},(_,i)=>row(i+1)),new Proxy(row(6),traps)]);rejected(Array.from({length:5},(_,i)=>row(i+1)),new Proxy(probe(),traps));rejected([...Array.from({length:5},(_,i)=>row(i+1)),{...raw(row(6)),labels:new Proxy({},traps)}]);assert(!proxyInvoked);
 const revoked=Proxy.revocable(row(6),{});revoked.revoke();rejected([...Array.from({length:5},(_,i)=>row(i+1)),revoked.proxy]);
 const script=fileURLToPath(new URL('./phase-a-staging-observability-logs.mjs',import.meta.url));
 for(const args of [[],['--file','PRIVATE_PATH'],['--stdin','--expected-release-sha',sha],['--expected-release-sha','PRIVATE'],['--token','PRIVATE']]){const bad=spawnSync(process.execPath,[script,...args],{input:'PRIVATE_INPUT',encoding:'utf8',timeout:5000});assert.equal(bad.status,1);assert.deepEqual(JSON.parse(bad.stderr),{result:'FAIL',code:'INVALID_EVIDENCE'});assert(!bad.stderr.includes('PRIVATE'));assert.equal(bad.stdout,'');checks++;}
 const imported=spawnSync(process.execPath,['--input-type=module','-e',`globalThis.fetch=()=>{throw Error('NETWORK_ON_IMPORT');};await import(${JSON.stringify(pathToFileURL(script).href)});console.log('IMPORT_SAFE');`],{encoding:'utf8',timeout:5000});assert.equal(imported.status,0);assert.equal(imported.stdout.trim(),'IMPORT_SAFE');assert.equal(imported.stderr,'');checks++;
 return{result:'PASS',checks,networkCalls:0};
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href)console.log(JSON.stringify(await runSelfTest()));
