import { test } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { validateRuntimeRunEnvironment } from './run-mode-runtime-browser.mjs';
const valid=()=>({LOCAL_HARNESS:'1',FLOW_TEST_DISPOSABLE:'1',MODE_INSTALLATIONS_TEST_DISPOSABLE:'1',MODE_DOCUMENT_TEST_DISPOSABLE:'1',MODE_RUNTIME_TEST_DISPOSABLE:'1',MODE_DOCUMENT_CRYPTO_LAYOUT:'public',PGHOST:'127.0.0.1',PGUSER:'postgres',PGDATABASE:'lumin_mode_document_runtime_runner',PGPORT:'55439',...Object.fromEntries(['API','RENDERER','PORTAL','MERCHANT','SECOND','FORBIDDEN','UNTRUSTED'].map((role,i)=>['MODE_DOCUMENT_'+role+'_PORT',String(56000+i)]))});
test('accepts both layouts and freezes bounded selection',()=>{for(const layout of ['public','extensions']){const selection=validateRuntimeRunEnvironment({...valid(),MODE_DOCUMENT_CRYPTO_LAYOUT:layout});assert.deepEqual(selection,{layout});assert.ok(Object.isFrozen(selection));}});
test('requires every local disposable flag',()=>{for(const key of ['LOCAL_HARNESS','FLOW_TEST_DISPOSABLE','MODE_INSTALLATIONS_TEST_DISPOSABLE','MODE_DOCUMENT_TEST_DISPOSABLE','MODE_RUNTIME_TEST_DISPOSABLE'])for(const value of [undefined,'0','true'])assert.throws(()=>validateRuntimeRunEnvironment({...valid(),[key]:value}),/RUNTIME_RUN_CONFIGURATION_INVALID/);});
test('rejects remote and nonisolated database selectors',()=>{for(const [key,values] of Object.entries({PGHOST:['db.example','::1',''],PGUSER:['service_role',''],PGDATABASE:['postgres','lumin_mode_owner_test','lumin_mode_document_runtime_','lumin_mode_document_runtime_'+'x'.repeat(36)],MODE_DOCUMENT_CRYPTO_LAYOUT:['unknown','']}))for(const value of values)assert.throws(()=>validateRuntimeRunEnvironment({...valid(),[key]:value}));});
test('rejects alternative connection selectors and private passwords',()=>{for(const key of ['DATABASE_URL','PGHOSTADDR','PGSERVICE','PGSERVICEFILE','PGPASSFILE','PGOPTIONS','PGPASSWORD'])assert.throws(()=>validateRuntimeRunEnvironment({...valid(),[key]:'PRIVATE_SENTINEL'}));for(const password of [undefined,'','postgres'])assert.doesNotThrow(()=>validateRuntimeRunEnvironment({...valid(),PGPASSWORD:password}));});
test('requires canonical bounded database port',()=>{for(const port of ['0','06543','65536','1e3',' 55439','55439 ',undefined])assert.throws(()=>validateRuntimeRunEnvironment({...valid(),PGPORT:port}));for(const port of ['1','65535'])assert.doesNotThrow(()=>validateRuntimeRunEnvironment({...valid(),PGPORT:port}));});
test('requires seven distinct unprivileged listener ports',()=>{for(const role of ['API','RENDERER','PORTAL','MERCHANT','SECOND','FORBIDDEN','UNTRUSTED'])for(const port of [undefined,'1023','65536','056000','1e4','56000 '])assert.throws(()=>validateRuntimeRunEnvironment({...valid(),['MODE_DOCUMENT_'+role+'_PORT']:port}));assert.throws(()=>validateRuntimeRunEnvironment({...valid(),MODE_DOCUMENT_UNTRUSTED_PORT:'56000'}));for(const port of ['1024','65535'])assert.doesNotThrow(()=>validateRuntimeRunEnvironment({...valid(),MODE_DOCUMENT_API_PORT:port}));});
test('startup failure emits only fixed valid JSON and fails before provisioning',()=>{const result=spawnSync(process.execPath,['scripts/run-mode-runtime-browser.mjs'],{encoding:'utf8',env:{...process.env,LOCAL_HARNESS:'PRIVATE_SENTINEL'},timeout:10000,windowsHide:true});assert.equal(result.status,1);assert.equal(result.stderr,'');assert.equal(result.stdout.includes('PRIVATE_SENTINEL'),false);assert.deepEqual(JSON.parse(result.stdout),{schemaVersion:1,status:'failed',category:'CONFIGURATION_FAILED',artifacts:[]});});


test('HTTP startup denies invalid configuration before TLS or SQL and keeps output fixed',()=>{const result=spawnSync(process.execPath,['scripts/run-mode-runtime-http.mjs'],{encoding:'utf8',env:{...process.env,LOCAL_HARNESS:'PRIVATE_SENTINEL'},timeout:10000,windowsHide:true});assert.equal(result.status,1);assert.equal(result.stderr,'');assert.deepEqual(JSON.parse(result.stdout),{schemaVersion:1,status:'failed',category:'CONFIGURATION_FAILED'});});
