import {ConnectedBusinessProfileInitializer} from './ConnectedBusinessProfileInitializer';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {BusinessType,CreateBusiness,CreateSimpleOffer,type BusinessProfile} from '@lumin/contracts';
import {ConnectedOfferScheduling} from './ConnectedOfferScheduling';
import {getBusinessTemplateDefaults} from '@lumin/templates';
import {BusinessOnboardingError,type RuntimeClient,type BusinessCreationState,type BusinessProfileRead,type SimpleOfferState,type SimpleOfferContext} from '@lumin/runtime-client';
const types:Record<BusinessType,string>={HOUSEKEEPING:'Housekeeping',AUTO_DETAILING:'Auto detailing',VEHICLE_RENTAL:'Vehicle rental',EQUIPMENT_RENTAL:'Equipment rental',EVENT_RENTAL:'Event rental',JUNK_REMOVAL:'Junk removal'};
function BusinessDefaults({profile}:{profile:BusinessProfile}){
 const defaults=getBusinessTemplateDefaults(profile);
 return <section aria-label={'Unapplied setup defaults for business '+profile.tenantId}><h3>Unapplied setup defaults</h3><p>Business: {profile.tenantId}. Suggested catalog language: {defaults.catalog.plural}; option group: {defaults.catalog.optionsLabel}; resource group: {defaults.context.resourceLabel}.</p><p>These are structural defaults from the verified business type. They are not applied or persisted here. No prices, inventory, capacities or booking eligibility are configured by this description.</p></section>;
}
type Client=Pick<RuntimeClient,'initializeBusinessProfile'|'businessProfileInitializationState'|'businessProfileInitializationLocked'|'createBusiness'|'businessCreationState'|'businessProfile'|'simpleOfferContext'|'createSimpleOffer'|'simpleOfferState'|'createOfferScheduling'|'offerSchedulingState'>;
type Fields={name:string;slug:string;timezone:string;currency:string;businessType:string};
const empty:Fields={name:'',slug:'',timezone:'',currency:'',businessType:''};
type Props={client:Client;tenantId:string;role?:string;firstBusinessEligible?:boolean;staging:boolean;apiConfigured:boolean;contextBusy?:boolean;onStateChange:()=>void;onOpen:(profile:BusinessProfile)=>Promise<void>};
export function ConnectedBusinessOnboarding(props:Props){
 if(!props.staging||!props.apiConfigured)return <section aria-label="Business onboarding"><h2>Business setup</h2><p>New-business onboarding is unavailable in this workspace. It requires the connected staging API and an explicitly enabled server capability; production and default capability remain unavailable.</p></section>;
 if(props.role!=='BUSINESS_OWNER'&&!(props.firstBusinessEligible===true&&props.role===undefined&&props.tenantId===''))return <section aria-label="Business onboarding"><h2>Business setup</h2><p>Creation is available to a verified business owner or a freshly signed-in account with a successful empty membership lookup. Existing staff or worker memberships do not qualify.</p></section>;
 return <ConnectedBusinessOnboardingOwner {...props}/>;
}
function ConnectedBusinessOnboardingOwner({client,tenantId,contextBusy=false,onStateChange,onOpen,firstBusinessEligible,role}:Props){
 const [open,setOpen]=useState(false),[fields,setFields]=useState<Fields>(empty),[review,setReview]=useState<{client:Client;tenantId:string;body:CreateBusiness}|null>(null);
 const [snapshot,setSnapshot]=useState<{client:Client;state:BusinessCreationState}>(()=>({client,state:client.businessCreationState()}));
 const [error,setError]=useState(''),[opening,setOpening]=useState(false),[profileRead,setProfileRead]=useState<{client:Client;tenantId:string;loading:boolean;value?:BusinessProfileRead;error:string}>({client,tenantId,loading:false,error:''});
 const returnFocus=useRef(false),generation=useRef(0),inFlight=useRef(false),profileInFlight=useRef(false),cancelRef=useRef<HTMLButtonElement>(null),reviewRef=useRef<HTMLButtonElement>(null);
 useEffect(()=>{generation.current++;inFlight.current=false;profileInFlight.current=false;setOpen(false);setFields(empty);setReview(null);setSnapshot({client,state:client.businessCreationState()});setError('');setOpening(false);setProfileRead({client,tenantId,loading:false,error:''});return()=>{generation.current++;};},[client,tenantId]);
 const state=snapshot.client===client?snapshot.state:client.businessCreationState(),pending=state.phase==='checking'||state.phase==='creating',initializationLocked=client.businessProfileInitializationLocked(),locked=pending||state.phase==='unknown'||initializationLocked;
 const reviewed=review?.client===client&&review.tenantId===tenantId?review:null;
 const currentProfile=profileRead.client===client&&profileRead.tenantId===tenantId?profileRead:undefined;
 useEffect(()=>{if(reviewed)cancelRef.current?.focus();else if(returnFocus.current){returnFocus.current=false;reviewRef.current?.focus();}},[reviewed]);
 function closeReview(){returnFocus.current=true;setReview(null);}
 function checkSession(){setSnapshot({client,state:client.businessCreationState()});onStateChange();}
 function prepare(event:FormEvent){event.preventDefault();if(contextBusy||locked||state.phase==='created'||state.phase==='unavailable')return;const parsed=CreateBusiness.safeParse({...fields,name:fields.name.trim(),idempotencyKey:crypto.randomUUID()});if(!parsed.success){setError('Enter a business name, lowercase slug, named IANA timezone, three-letter uppercase currency and one fixed business type.');return;}setError('');setReview({client,tenantId,body:parsed.data});}
 async function send(body:CreateBusiness){
  if(inFlight.current||pending)return;const at=generation.current;inFlight.current=true;setReview(null);setError('');
  const promise=client.createBusiness(body);checkSession();
  try{await promise;if(at===generation.current)checkSession();}
  catch(error){if(at===generation.current){setError(error instanceof BusinessOnboardingError?error.message:'Business creation outcome could not be verified. Check this session state before another action.');checkSession();}}
  finally{if(at===generation.current)inFlight.current=false;}
 }
 async function readProfile(){if(profileInFlight.current)return;const at=generation.current;profileInFlight.current=true;setProfileRead({client,tenantId,loading:true,error:''});try{const value=await client.businessProfile(tenantId);if(at===generation.current)setProfileRead({client,tenantId,loading:false,value,error:''});}catch(error){if(at===generation.current)setProfileRead({client,tenantId,loading:false,error:error instanceof BusinessOnboardingError?error.message:'Business type is unverified.'});}finally{if(at===generation.current)profileInFlight.current=false;}}
 async function openCreated(){if(state.phase!=='created'||opening||inFlight.current)return;const at=generation.current;setOpening(true);setError('');try{await onOpen(state.profile);}catch(error){if(at===generation.current)setError(error instanceof Error?error.message:'The created business owner membership could not be verified. The creation receipt is retained.');}finally{if(at===generation.current)setOpening(false);}}
 const shown=open||state.phase!=='ready';
 return <section aria-label="Business onboarding" style={{minWidth:0,overflowWrap:'anywhere'}}><h2>Business setup</h2>{firstBusinessEligible&&tenantId===''&&<p>Your verified membership lookup returned no assigned businesses. You can create your first staging business; the server grants owner membership only after successful creation.</p>}<p>This creates a separate staging business. Its business type is permanent and cannot be changed here. It never assigns a type to your existing business. Creating a business does not configure services, templates or payments.</p><p>The server onboarding capability must be explicitly enabled in staging; it is unavailable in production and disabled by default.</p>
 {tenantId&&<button type="button" disabled={currentProfile?.loading||pending} onClick={()=>void readProfile()}>Check current business type</button>}{currentProfile?.loading&&<p role="status">Checking current business type...</p>}{currentProfile?.error&&<p role="alert">{currentProfile.error}</p>}{currentProfile?.value?.status==='uninitialized'&&<p role="status">This existing business is uninitialized: no authoritative business type is recorded. Creating a separate business will not initialize or change this one.</p>}{currentProfile?.value?.status==='initialized'&&<p>Current business type: {types[currentProfile.value.profile.businessType]}. Permanent type; template contract version {currentProfile.value.profile.templateVersion}.</p>}
 {currentProfile?.value?.status==='initialized'&&<BusinessDefaults profile={currentProfile.value.profile}/>}
 {tenantId&&<ConnectedBusinessProfileInitializer client={client} tenantId={tenantId} role={role} uninitialized={currentProfile?.value?.status==='uninitialized'} blocked={contextBusy||pending||state.phase==='unknown'||opening} onStateChange={checkSession} onInitialized={profile=>setProfileRead({client,tenantId,loading:false,value:{status:'initialized',profile},error:''})}/>}
 {!shown&&<button type="button" disabled={contextBusy||initializationLocked} onClick={()=>setOpen(true)}>Create a new staging business</button>}
 {shown&&state.phase==='ready'&&<form onSubmit={prepare}><fieldset disabled={contextBusy||!!reviewed} className="form-stack" style={{minWidth:0}}><legend>New business details</legend><label>New business name<input required maxLength={200} value={fields.name} onChange={event=>setFields({...fields,name:event.target.value})}/></label><label>New business slug<input required minLength={2} maxLength={100} pattern="[a-z0-9][a-z0-9-]*[a-z0-9]" value={fields.slug} onChange={event=>setFields({...fields,slug:event.target.value})}/></label><p>Use a unique lowercase slug with letters, numbers and internal hyphens.</p><label>New business timezone<input required maxLength={100} placeholder="America/Los_Angeles or UTC" value={fields.timezone} onChange={event=>setFields({...fields,timezone:event.target.value})}/></label><label>New business currency<input required minLength={3} maxLength={3} pattern="[A-Z]{3}" value={fields.currency} onChange={event=>setFields({...fields,currency:event.target.value})}/></label><label>Permanent business type<select required value={fields.businessType} onChange={event=>setFields({...fields,businessType:event.target.value})}><option value="">Choose a fixed business type</option>{BusinessType.options.map(type=><option key={type} value={type}>{types[type]}</option>)}</select></label><button ref={reviewRef} type="submit">Review new business</button></fieldset></form>}
 {reviewed&&<div role="dialog" aria-label="Review permanent business type" onKeyDown={event=>{if(event.key==='Escape'){event.preventDefault();closeReview();}}}><h3>Review new staging business</h3><dl><dt>Name</dt><dd>{reviewed.body.name}</dd><dt>Slug</dt><dd>{reviewed.body.slug}</dd><dt>Timezone</dt><dd>{reviewed.body.timezone}</dd><dt>Currency</dt><dd>{reviewed.body.currency}</dd><dt>Permanent business type</dt><dd>{types[reviewed.body.businessType]}</dd></dl><p>Confirm this permanent type for a new, separate business. This is not a type toggle, and it will not change your current business. Use test data only.</p><button ref={cancelRef} type="button" onClick={()=>{closeReview();}}>Cancel new business</button><button type="button" disabled={contextBusy||locked} onClick={()=>void send(reviewed.body)}>Confirm create staging business</button></div>}
 {state.phase!=='ready'&&state.phase!=='unavailable'&&<><p>Frozen attempt key: {state.attempt.idempotencyKey}</p><p>Attempt details: {state.attempt.name}; slug {state.attempt.slug}; timezone {state.attempt.timezone}; currency {state.attempt.currency}; permanent type {types[state.attempt.businessType]}.</p></>}
 {pending&&<><p role="status">{state.phase==='checking'?'Checking fresh business membership...':'Creating the reviewed staging business...'}</p><button type="button" onClick={checkSession}>Check this session's business creation state</button></>}
 {state.phase==='unknown'&&<><p role="alert">Business creation is unverified. Details and key are frozen. Do not create a different attempt; retry only this same attempt with the same signed-in account.</p><button type="button" disabled={contextBusy} onClick={()=>void send(state.attempt)}>Retry this same business creation</button></>}
 {state.phase==='unavailable'&&<p role="status">Business onboarding is unavailable. The server staging capability is disabled; no business creation is confirmed.</p>}
 {state.phase==='created'&&<><BusinessDefaults profile={state.profile}/><p role="status">Server creation receipt verified. New business ID: {state.profile.tenantId}; permanent type: {types[state.profile.businessType]}; template contract version: {state.profile.templateVersion}.</p><p>Refresh and verify your owner membership before opening this business. The receipt alone does not configure its catalog or prove its workspace is ready.</p><button type="button" disabled={opening||contextBusy} onClick={()=>void openCreated()}>{opening?'Checking created business owner membership...':'Open created business'}</button></>}
 {(state.phase==='created'&&state.profile.businessType==='HOUSEKEEPING'&&state.profile.tenantId===tenantId||currentProfile?.value?.status==='initialized'&&currentProfile.value.profile.businessType==='HOUSEKEEPING')&&<HousekeepingOffer client={client} tenantId={tenantId} contextBusy={contextBusy||initializationLocked} onStateChange={onStateChange} resumed={!(state.phase==='created'&&state.profile.tenantId===tenantId)}/>}
 {error&&<p role="alert">{error}</p>}
 </section>;
}

function HousekeepingOffer({client,tenantId,contextBusy,onStateChange,resumed}:{client:Client;tenantId:string;contextBusy:boolean;onStateChange:()=>void;resumed:boolean}){
 const [snapshot,setSnapshot]=useState(()=>({client,tenantId,state:client.simpleOfferState(tenantId)})),[context,setContext]=useState<{client:Client;tenantId:string;value:SimpleOfferContext}|null>(null),[checking,setChecking]=useState(false),[error,setError]=useState('');
 const [acknowledged,setAcknowledged]=useState(false),[fields,setFields]=useState({name:'',description:'',amount:'',duration:''}),[review,setReview]=useState<{client:Client;tenantId:string;body:CreateSimpleOffer}|null>(null);
 const generation=useRef(0),inFlight=useRef(false),cancel=useRef<HTMLButtonElement>(null),reviewButton=useRef<HTMLButtonElement>(null),restoreFocus=useRef(false);
 useEffect(()=>{generation.current++;inFlight.current=false;setSnapshot({client,tenantId,state:client.simpleOfferState(tenantId)});setContext(null);setReview(null);setAcknowledged(false);setFields({name:'',description:'',amount:'',duration:''});setChecking(false);setError('');return()=>{generation.current++;};},[client,tenantId]);
 const state:SimpleOfferState=snapshot.client===client&&snapshot.tenantId===tenantId?snapshot.state:{phase:'ready'},verified=context?.client===client&&context.tenantId===tenantId?context.value:undefined,reviewed=review?.client===client&&review.tenantId===tenantId?review:null;
 const pending=state.phase==='checking'||state.phase==='creating',initializationLocked=client.businessProfileInitializationLocked(),locked=pending||state.phase==='unknown'||initializationLocked;
 useEffect(()=>{if(reviewed)cancel.current?.focus();else if(restoreFocus.current){restoreFocus.current=false;reviewButton.current?.focus();}},[reviewed]);
 function sync(){setSnapshot({client,tenantId,state:client.simpleOfferState(tenantId)});onStateChange();}
 function close(){restoreFocus.current=true;setReview(null);}
 async function check(){if(inFlight.current||locked||contextBusy)return;const at=generation.current;inFlight.current=true;setChecking(true);setContext(null);setError('');try{const value=await client.simpleOfferContext(tenantId);if(at===generation.current)setContext({client,tenantId,value});}catch(error){if(at===generation.current)setError(error instanceof Error?error.message:'Owner offer context remains unverified.');}finally{if(at===generation.current){inFlight.current=false;setChecking(false);}}}
 function prepare(event:FormEvent){event.preventDefault();if(!verified||locked||checking||contextBusy||state.phase==='created'||resumed&&!acknowledged)return;
  if(!/^[0-9]+$/.test(fields.amount)||!/^[0-9]+$/.test(fields.duration)){setError('Enter whole numbers for minor-unit price and minutes.');return;}
  const parsed=CreateSimpleOffer.safeParse({name:fields.name.trim(),description:fields.description,price:{amount:Number(fields.amount),currency:verified.currency},durationMinutes:Number(fields.duration),idempotencyKey:crypto.randomUUID()});
  if(!parsed.success){setError('Use a positive safe integer price in minor units and a duration from 5 to 1440 minutes.');return;}setError('');setReview({client,tenantId,body:parsed.data});
 }
 async function send(body:CreateSimpleOffer){if(inFlight.current||pending||contextBusy)return;const at=generation.current;inFlight.current=true;setReview(null);setError('');const promise=client.createSimpleOffer(tenantId,body);sync();try{await promise;if(at===generation.current)sync();}catch(error){if(at===generation.current){setError(error instanceof Error?error.message:'Offer creation remains unverified.');sync();}}finally{if(at===generation.current)inFlight.current=false;}}
 return <section aria-label="Housekeeping simple offer setup" style={{minWidth:0,overflowWrap:'anywhere'}}><h3>Create a housekeeping simple offer</h3><p>This explicit staging action creates one authoritative service price. It does not configure availability, publish a booking form, reserve a time or take payment. Other business types are not supported here. Catalog authoring requires an explicitly enabled staging server capability; it is disabled by default and unavailable in production.</p>
 {resumed&&<p role="note">Setup can resume from this verified existing business. This only creates a new offer; it does not update an existing price. An earlier offer may have been saved even if its receipt was lost. Reloading clears this page's attempt memory. If an earlier attempt is unresolved, do not create a replacement key or duplicate offer here; retain its original details and key for assisted recovery.</p>}
 {state.phase==='ready'&&<><button type="button" disabled={checking||contextBusy} onClick={()=>void check()}>Verify owner and offer currency</button>{checking&&<p role="status">Checking current owner, housekeeping profile and currency...</p>}{verified&&<form onSubmit={prepare}><fieldset className="form-stack" disabled={!!reviewed||contextBusy||checking} style={{minWidth:0}}><legend>Housekeeping offer details</legend><p>Verified business: {tenantId}. Currency: {verified.currency}.</p><label>Offer name<input required maxLength={200} value={fields.name} onChange={event=>setFields({...fields,name:event.target.value})}/></label><label>Offer description<textarea maxLength={2000} value={fields.description} onChange={event=>setFields({...fields,description:event.target.value})}/></label><label>Offer price in minor units<input required inputMode="numeric" pattern="[0-9]+" value={fields.amount} onChange={event=>setFields({...fields,amount:event.target.value})}/></label><p>Enter whole minor units in {verified.currency}. For USD, 12500 means $125.00. No currency conversion is performed.</p><label>Offer duration in minutes<input required inputMode="numeric" pattern="[0-9]+" value={fields.duration} onChange={event=>setFields({...fields,duration:event.target.value})}/></label><>{resumed&&<label><input type="checkbox" checked={acknowledged} onChange={event=>setAcknowledged(event.target.checked)}/>I have no unresolved earlier offer creation attempt</label>}<button ref={reviewButton} type="submit" disabled={resumed&&!acknowledged}>Review housekeeping offer price</button></></fieldset></form>}</>}
 {reviewed&&<div role="dialog" aria-label="Review authoritative offer price" onKeyDown={event=>{if(event.key==='Escape'){event.preventDefault();close();}}}><h4>Review authoritative service price</h4><p>Business: {tenantId}. {reviewed.body.name}; {reviewed.body.price.amount} minor units {reviewed.body.price.currency}; {reviewed.body.durationMinutes} minutes.</p><p>Description: {reviewed.body.description||'None'}. Confirming writes this new service and its price to the business catalog. This does not publish or enable appointment availability.</p><button ref={cancel} type="button" onClick={close}>Cancel offer creation</button><button type="button" disabled={contextBusy||locked} onClick={()=>void send(reviewed.body)}>Confirm create housekeeping offer</button></div>}
 {pending&&<p role="status">Checking or creating the reviewed offer...</p>}{(pending||state.phase==='unknown')&&<button type="button" onClick={sync}>Check this session's offer state</button>}
 {state.phase==='unknown'&&<><p role="alert">Offer creation is unverified. The account, business, details and attempt key remain frozen. Do not create another attempt.</p><p>Frozen offer: {state.attempt.name}; {state.attempt.price.amount} minor units {state.attempt.price.currency}; {state.attempt.durationMinutes} minutes. Attempt key: {state.attempt.idempotencyKey}.</p><button type="button" disabled={contextBusy} onClick={()=>void send(state.attempt)}>Retry this same housekeeping offer</button></>}
 {state.phase==='created'&&<><p role="status">Server offer receipt verified. Service ID: {state.receipt.service.id}; {state.receipt.service.name}; {state.receipt.service.price.amount} minor units {state.receipt.service.price.currency}; {state.receipt.service.durationMinutes} minutes.</p><p>Refresh the catalog to read this service. Availability and publication are not configured by this receipt.</p></>}{state.phase==='created'&&<ConnectedOfferScheduling client={client} tenantId={tenantId} offer={state.receipt} contextBusy={contextBusy} onStateChange={onStateChange}/>}
 {error&&<p role="alert">{error}</p>}</section>;
}
