import {afterEach,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {MemoryRouter} from 'react-router-dom';
import {createRuntimeClient} from '@lumin/runtime-client';
import {ConnectedSettings,CONNECTED_SETTINGS_SECTIONS} from './ConnectedSettings';
import {useLayoutEffect,type ComponentProps} from 'react';
const tenant='11111111-1111-4111-8111-111111111111',foreign='33333333-3333-4333-8333-333333333333';
const context={tenantId:tenant,name:'Verified business',slug:'verified-business',timezone:'America/Los_Angeles',currency:'USD',status:'active' as const};
const profile={status:'initialized' as const,profile:{schemaVersion:1 as const,tenantId:tenant,businessType:'HOUSEKEEPING' as const,templateVersion:1 as const}};
type Client=ComponentProps<typeof ConnectedSettings>['client'];
function fixture():Client{return{authContextRevision:vi.fn(()=>0),memberships:vi.fn(async()=>[{tenant_id:tenant,role:'BUSINESS_OWNER'}]),ownerBusinessContext:vi.fn(async()=>context),businessProfile:vi.fn(async()=>profile)};}
function settings(client=fixture(),path='/settings',props:Partial<ComponentProps<typeof ConnectedSettings>>={}){return render(<MemoryRouter initialEntries={[path]}><ConnectedSettings client={client} tenantId={tenant} role="BUSINESS_OWNER" setupAvailable {...props}/></MemoryRouter>);}
afterEach(()=>{cleanup();vi.restoreAllMocks();});
it.each(CONNECTED_SETTINGS_SECTIONS)('resolves exact nested %s deep link with13 native keyboard-accessible section links and no automatic request',async(id,label)=>{const client=fixture();settings(client,'/settings/'+id);expect(screen.getByRole('heading',{level:2,name:label})).toBeTruthy();const links=screen.getByRole('navigation',{name:'Settings sections'}).querySelectorAll('a');expect(links).toHaveLength(13);expect([...links].map(link=>link.textContent)).toEqual(CONNECTED_SETTINGS_SECTIONS.map(([,name])=>name));const active=screen.getByRole('link',{name:label});expect(active).toHaveAttribute('href','/settings/'+id);expect(active).toHaveAttribute('aria-current','page');active.focus();expect(active).toHaveFocus();expect(client.memberships).not.toHaveBeenCalled();expect(client.ownerBusinessContext).not.toHaveBeenCalled();expect(client.businessProfile).not.toHaveBeenCalled();if(id!=='business'&&id!=='business-type'){expect(screen.getByRole('status')).toHaveTextContent('not available yet');expect(screen.queryByRole('button')).toBeNull();}});
it('refreshes fresh exact owner metadata and immutable type without inputs, writes, mock members or provider claims',async()=>{const client=fixture();settings(client);fireEvent.click(screen.getByRole('button',{name:'Refresh verified business settings'}));await screen.findByText('Verified business');expect(screen.getByText('America/Los_Angeles')).toBeTruthy();expect(screen.getByText('USD')).toBeTruthy();expect(screen.getByText(/Verified permanent business type: Housekeeping/)).toBeTruthy();expect(client.memberships).toHaveBeenCalledTimes(2);expect(client.ownerBusinessContext).toHaveBeenCalledWith(tenant);expect(client.businessProfile).toHaveBeenCalledWith(tenant);expect(screen.queryByRole('textbox')).toBeNull();expect(screen.queryByRole('combobox')).toBeNull();expect(screen.queryByRole('table')).toBeNull();expect(document.body.textContent).not.toMatch(/connected successfully|healthy|revenue/i);fireEvent.click(screen.getByRole('link',{name:'BUSINESS TYPE & TEMPLATE'}));expect(screen.getByText('Unapplied template description')).toBeTruthy();expect(screen.getByRole('link',{name:'Go to existing business setup controls'})).toHaveAttribute('href','#connected-business-setup');expect(client.memberships).toHaveBeenCalledTimes(2);});
it.each(['HOUSEKEEPING','AUTO_DETAILING','VEHICLE_RENTAL','EQUIPMENT_RENTAL','EVENT_RENTAL','JUNK_REMOVAL'] as const)('uses only verified %s profile for unapplied template description',async(businessType)=>{const client=fixture();vi.mocked(client.businessProfile).mockResolvedValue({status:'initialized',profile:{...profile.profile,businessType}});settings(client,'/settings/business-type');fireEvent.click(screen.getByRole('button',{name:'Refresh verified business settings'}));await screen.findByText('Unapplied template description');expect(screen.getByText(/These structural defaults are descriptive only/)).toBeTruthy();expect(screen.queryByRole('combobox')).toBeNull();expect(screen.queryByRole('button',{name:/apply|publish|save|initialize/i})).toBeNull();});
it('uninitialized is a truthful read result with no inferred template or automatic initialization',async()=>{const client=fixture();vi.mocked(client.businessProfile).mockResolvedValue({status:'uninitialized',tenantId:tenant});settings(client,'/settings/business-type');fireEvent.click(screen.getByRole('button',{name:'Refresh verified business settings'}));await screen.findByText(/This existing business is uninitialized/);expect(screen.queryByText('Unapplied template description')).toBeNull();expect(screen.queryByText(/Verified permanent business type/)).toBeNull();expect(screen.queryByRole('combobox')).toBeNull();});
it.each([[{tenant_id:tenant,role:'BUSINESS_STAFF'}],[{tenant_id:foreign,role:'BUSINESS_OWNER'}],[{tenant_id:tenant,role:'BUSINESS_OWNER',email:'private@example.test'}],[]].map(members=>[members] as const))('invalid or foreign fresh owner membership prevents all profile reads and PII display',async(members)=>{const client=fixture();vi.mocked(client.memberships).mockResolvedValue(members);settings(client);fireEvent.click(screen.getByRole('button',{name:'Refresh verified business settings'}));await screen.findByRole('alert');expect(client.ownerBusinessContext).not.toHaveBeenCalled();expect(client.businessProfile).not.toHaveBeenCalled();expect(document.body.textContent).not.toContain('private@example.test');expect(screen.queryByText('Verified business')).toBeNull();});
it('membership lookup failure is denied, sanitized and not mistaken for an empty or owner result',async()=>{const client=fixture();vi.mocked(client.memberships).mockRejectedValue(Error('private-token-and-PII'));settings(client);fireEvent.click(screen.getByRole('button',{name:'Refresh verified business settings'}));await screen.findByRole('alert');expect(document.body.textContent).not.toContain('private-token-and-PII');expect(client.ownerBusinessContext).not.toHaveBeenCalled();});
it('staff and signed-out selection do not read settings even when a client object is supplied',()=>{const client=fixture();settings(client,'/settings/business',{role:'BUSINESS_STAFF'});expect(screen.queryByRole('button')).toBeNull();expect(screen.getByRole('alert')).toHaveTextContent('authenticated business owner');expect(client.memberships).not.toHaveBeenCalled();});
it('profile capability unavailable does not invent a type or hide independently verified business locale',async()=>{const client=fixture();vi.mocked(client.businessProfile).mockRejectedValue(Error('private-server-error'));settings(client);fireEvent.click(screen.getByRole('button',{name:'Refresh verified business settings'}));await screen.findByText('Verified business');expect(screen.getByRole('alert')).toHaveTextContent('type and template remain unverified or unavailable');expect(screen.getByText('USD')).toBeTruthy();expect(screen.queryByText(/Verified permanent business type/)).toBeNull();expect(document.body.textContent).not.toContain('private-server-error');});
it('rejects widened or foreign business identity receipt without granting local defaults',async()=>{const client=fixture();vi.mocked(client.ownerBusinessContext).mockResolvedValue({...context,tenantId:foreign});vi.mocked(client.businessProfile).mockResolvedValue({status:'initialized',profile:{...profile.profile,tenantId:foreign}});settings(client);fireEvent.click(screen.getByRole('button',{name:'Refresh verified business settings'}));await screen.findAllByRole('alert');expect(screen.queryByText('Verified business')).toBeNull();expect(screen.queryByText(/Verified permanent business type/)).toBeNull();});
it('client/business replacement drops late metadata and synchronously hides the prior business',async()=>{const client=fixture();let finish!:(value:typeof context)=>void;vi.mocked(client.ownerBusinessContext).mockImplementation(()=>new Promise(resolve=>finish=resolve));const view=settings(client);fireEvent.click(screen.getByRole('button',{name:'Refresh verified business settings'}));await waitFor(()=>expect(finish).toBeTypeOf('function'));const other=fixture();view.rerender(<MemoryRouter><ConnectedSettings client={other} tenantId={foreign} role="BUSINESS_OWNER"/></MemoryRouter>);finish(context);await waitFor(()=>expect(screen.queryByText(/Checking fresh owner/)).toBeNull());expect(screen.queryByText('Verified business')).toBeNull();expect(screen.queryByText('USD')).toBeNull();expect(other.ownerBusinessContext).not.toHaveBeenCalled();});
it('unknown nested addresses stay closed and narrow container navigation wraps without fixed widths',()=>{settings(fixture(),'/settings/unknown-section');expect(screen.getByRole('heading',{name:'Settings section not found'})).toBeTruthy();expect(screen.queryByRole('button')).toBeNull();const root=screen.getByRole('region',{name:'Connected settings'});expect(root).toHaveStyle({minWidth:'0',maxWidth:'100%',overflowWrap:'anywhere'});expect(screen.getByRole('navigation',{name:'Settings sections'}).querySelector('ul')).toHaveStyle({flexWrap:'wrap',maxWidth:'100%'});});

it('render-time scope guard removes already verified prior-business metadata before passive cleanup on client replacement',async()=>{
 const old=fixture(),next=fixture();let observed='';
 function Observer({client}:{client:Client}){useLayoutEffect(()=>{observed=document.body.textContent??'';},[client]);return <ConnectedSettings client={client} tenantId={tenant} role="BUSINESS_OWNER"/>;}
 const view=render(<MemoryRouter><Observer client={old}/></MemoryRouter>);fireEvent.click(screen.getByRole('button',{name:'Refresh verified business settings'}));await screen.findByText('Verified business');view.rerender(<MemoryRouter><Observer client={next}/></MemoryRouter>);expect(observed).not.toContain('Verified business');expect(observed).not.toContain('America/Los_Angeles');expect(next.memberships).not.toHaveBeenCalled();
});

it.each(['business','type'] as const)('does not display a fulfilled sibling after delayed %s read invalidates real client authentication',async(failing)=>{
 const json=(value:unknown,status=200)=>new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json'}});
 let finish!:(response:Response)=>void;const token='synthetic-settings-owner-token';
 const transport=vi.fn<typeof fetch>(async input=>{const url=String(input);if(url.includes('/token?'))return json({access_token:token});if(url.endsWith('/user'))return json({id:'22222222-2222-4222-8222-222222222222'});if(url.includes('/tenant_members?'))return json([{tenant_id:tenant,role:'BUSINESS_OWNER'}]);if(url.includes('/api/business-profile?'))return failing==='type'?new Promise(resolve=>finish=resolve):json({ok:true,data:profile.profile});if(url.includes('/api/profile?'))return failing==='business'?new Promise(resolve=>finish=resolve):json({ok:true,data:{schemaVersion:1,profile:{id:tenant,name:context.name,slug:context.slug,timezone:context.timezone,currency:context.currency,status:'active'}}});throw Error('Unexpected request');});
 const client=createRuntimeClient({url:'https://example.supabase.co',publishableKey:'sb_publishable_synthetic_fixture',tenantId:tenant,allowMembershipDiscovery:true,bookingApiOrigin:'https://api.example.test'},transport);
 await client.signIn('owner@example.test','synthetic');settings(client);fireEvent.click(screen.getByRole('button',{name:'Refresh verified business settings'}));await waitFor(()=>expect(finish).toBeTypeOf('function'));finish(json({ok:false,code:'UNAUTHENTICATED'},401));await screen.findByText(/Fresh owner membership for this exact business could not be verified/);
 expect(screen.queryByText('Verified business')).toBeNull();expect(screen.queryByText(/Verified permanent business type/)).toBeNull();expect(screen.queryByText('USD')).toBeNull();expect(document.body.textContent).not.toContain(token);await expect(client.memberships()).rejects.toThrow();expect(transport.mock.calls.filter(([,options])=>options?.method==='POST')).toHaveLength(1);
});
it('a final revoked membership drops both successful settings reads',async()=>{const client=fixture();vi.mocked(client.memberships).mockResolvedValueOnce([{tenant_id:tenant,role:'BUSINESS_OWNER'}]).mockResolvedValueOnce([{tenant_id:tenant,role:'BUSINESS_STAFF'}]);settings(client);fireEvent.click(screen.getByRole('button',{name:'Refresh verified business settings'}));await screen.findByRole('alert');expect(screen.queryByText('Verified business')).toBeNull();expect(screen.queryByText(/Verified permanent business type/)).toBeNull();});

it.each(['22222222-2222-4222-8222-222222222222','44444444-4444-4444-8444-444444444444'])('rejects same-client reauthentication to actor %s after a sibling has fulfilled',async(nextActor)=>{
 const json=(value:unknown)=>new Response(JSON.stringify(value),{status:200,headers:{'Content-Type':'application/json'}});let actor='22222222-2222-4222-8222-222222222222';let finish!:(response:Response)=>void;
 const transport=vi.fn<typeof fetch>(async input=>{const url=String(input);if(url.includes('/token?'))return json({access_token:'synthetic-token'});if(url.endsWith('/user'))return json({id:actor});if(url.includes('/tenant_members?'))return json([{tenant_id:tenant,role:'BUSINESS_OWNER'}]);if(url.includes('/api/business-profile?'))return new Promise(resolve=>finish=resolve);if(url.includes('/api/profile?'))return json({ok:true,data:{schemaVersion:1,profile:{id:tenant,name:context.name,slug:context.slug,timezone:context.timezone,currency:context.currency,status:'active'}}});throw Error('Unexpected request');});
 const client=createRuntimeClient({url:'https://example.supabase.co',publishableKey:'sb_publishable_synthetic_fixture',tenantId:tenant,allowMembershipDiscovery:true,bookingApiOrigin:'https://api.example.test'},transport);await client.signIn('owner@example.test','synthetic');settings(client);fireEvent.click(screen.getByRole('button',{name:'Refresh verified business settings'}));await waitFor(()=>expect(finish).toBeTypeOf('function'));await waitFor(()=>expect(transport.mock.calls.some(([url])=>String(url).includes('/api/profile?'))).toBe(true));client.signOut();actor=nextActor;await client.signIn('owner@example.test','synthetic');finish(json({ok:true,data:profile.profile}));await screen.findByText(/Fresh owner membership for this exact business could not be verified/);expect(screen.queryByText('Verified business')).toBeNull();expect(screen.queryByText(/Verified permanent business type/)).toBeNull();expect(await client.memberships()).toEqual([{tenant_id:tenant,role:'BUSINESS_OWNER'}]);
});
