import {afterEach,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {useLayoutEffect} from 'react';
import {ConfirmationReceiptStatus} from '@lumin/contracts';
import {createRuntimeClient,ConfirmationReceiptStatusError} from '@lumin/runtime-client';
import {ConnectedConfirmationReceipts,type ConfirmationReceiptsClient} from './ConnectedConfirmationReceipts';
const tenant='11111111-1111-4111-8111-111111111111',booking='22222222-2222-4222-8222-222222222222',foreign='33333333-3333-4333-8333-333333333333';
const receipt=(email=false,sms=false)=>ConfirmationReceiptStatus.parse({schemaVersion:1,tenantId:tenant,bookingId:booking,channels:[{channel:'email',receiptRecorded:email},{channel:'sms',receiptRecorded:sms}]});
function fixture(value=receipt()){let auth=0;const client:ConfirmationReceiptsClient={authContextRevision:vi.fn(()=>auth),readConfirmationReceiptStatus:vi.fn(async()=>value)};return{client,reauth:()=>{auth++;}};}
const setup=(client?:ConfirmationReceiptsClient)=>render(<ConnectedConfirmationReceipts client={client} tenantId={tenant} bookingId={booking}/>);
const refresh=()=>fireEvent.click(screen.getByRole('button',{name:'Refresh confirmation receipts'}));
afterEach(()=>{cleanup();vi.restoreAllMocks();});
it('starts unverified and never automatically reads or invents false flags',()=>{const f=fixture();setup(f.client);expect(screen.getByRole('status')).toHaveTextContent('not been checked');expect(screen.queryByRole('table')).toBeNull();expect(f.client.readConfirmationReceiptStatus).not.toHaveBeenCalled();const button=screen.getByRole('button',{name:'Refresh confirmation receipts'});button.focus();expect(button).toHaveFocus();});
it.each([[false,false],[true,false],[false,true],[true,true]])('shows only recorded receipt flags email=%s/SMS=%s with their truthful limits',async(email,sms)=>{
 const f=fixture(receipt(email,sms));setup(f.client);refresh();const table=await screen.findByRole('table');expect(screen.getByRole('rowheader',{name:'Email'})).toBeTruthy();expect(screen.getByRole('rowheader',{name:'SMS'})).toBeTruthy();const cells=table.querySelectorAll('td');expect(cells[0]).toHaveTextContent(email?'Successful-send receipt recorded':'No successful-send receipt recorded');expect(cells[1]).toHaveTextContent(sms?'Successful-send receipt recorded':'No successful-send receipt recorded');expect(screen.getByText(/does not verify delivery to the customer or prove provider activation/)).toBeTruthy();expect(table.textContent).not.toMatch(/pending|failed|delivered|simulated|staging|UTC|provider/i);expect(f.client.readConfirmationReceiptStatus).toHaveBeenCalledWith(tenant,booking);expect(screen.getByRole('region',{name:'Confirmation receipt records'})).toHaveStyle({minWidth:'0',maxWidth:'100%',overflowWrap:'anywhere'});expect(table).toHaveStyle({maxWidth:'100%',tableLayout:'fixed'});
});
it('withholds prior flags during a fresh read and after an unverified read instead of showing false or stale success',async()=>{const f=fixture(receipt(true,true));setup(f.client);refresh();await screen.findByRole('table');let fail!:(error:Error)=>void;vi.mocked(f.client.readConfirmationReceiptStatus).mockImplementation(()=>new Promise((_resolve,reject)=>fail=reject));refresh();expect(screen.queryByRole('table')).toBeNull();expect(screen.getByRole('button')).toBeDisabled();fail(Error('private-recipient-and-token'));await screen.findByRole('alert');expect(screen.queryByRole('table')).toBeNull();expect(screen.queryByText('No successful-send receipt recorded')).toBeNull();expect(document.body.textContent).not.toContain('private-recipient-and-token');});
it.each(['tenant','booking','client','auth'] as const)('drops rendered receipts before passive effects when %s changes',async(change)=>{const f=fixture(receipt(true,true)),next=fixture();let observed='';function Observer({client,t,b}:{client:ConfirmationReceiptsClient;t:string;b:string}){useLayoutEffect(()=>{observed=document.body.textContent??'';});return <ConnectedConfirmationReceipts client={client} tenantId={t} bookingId={b}/>;}const view=render(<Observer client={f.client} t={tenant} b={booking}/>);refresh();await screen.findByRole('table');if(change==='auth')f.reauth();view.rerender(<Observer client={change==='client'?next.client:f.client} t={change==='tenant'?foreign:tenant} b={change==='booking'?foreign:booking}/>);expect(observed).not.toContain('Successful-send receipt recorded');expect(screen.queryByRole('table')).toBeNull();});
it.each(['tenant','booking','client','auth'] as const)('ignores a late receipt when %s changes',async(change)=>{const f=fixture();let finish!:(value:ConfirmationReceiptStatus)=>void;vi.mocked(f.client.readConfirmationReceiptStatus).mockImplementation(()=>new Promise(resolve=>finish=resolve));const view=setup(f.client);refresh();const next=fixture();if(change==='auth')f.reauth();view.rerender(<ConnectedConfirmationReceipts client={change==='client'?next.client:f.client} tenantId={change==='tenant'?foreign:tenant} bookingId={change==='booking'?foreign:booking}/>);finish(receipt(true,true));await waitFor(()=>expect(screen.getByRole('button')).toBeEnabled());expect(screen.queryByRole('table')).toBeNull();});
it('drops late same-client authentication results even without an external rerender and releases the read control',async()=>{const f=fixture();let finish!:(value:ConfirmationReceiptStatus)=>void;vi.mocked(f.client.readConfirmationReceiptStatus).mockImplementation(()=>new Promise(resolve=>finish=resolve));setup(f.client);refresh();f.reauth();finish(receipt(true,true));await waitFor(()=>expect(screen.getByRole('button')).toBeEnabled());expect(screen.queryByRole('table')).toBeNull();});
it('prevents overlapping reads and has no send or queue retry control',async()=>{const f=fixture();let finish!:(value:ConfirmationReceiptStatus)=>void;vi.mocked(f.client.readConfirmationReceiptStatus).mockImplementation(()=>new Promise(resolve=>finish=resolve));setup(f.client);const button=screen.getByRole('button');fireEvent.click(button);fireEvent.click(button);expect(f.client.readConfirmationReceiptStatus).toHaveBeenCalledTimes(1);expect(screen.getAllByRole('button')).toHaveLength(1);finish(receipt());await screen.findByRole('table');});
it.each([{...receipt(),tenantId:foreign},{...receipt(),bookingId:foreign},{...receipt(),delivered:true},{...receipt(),channels:[{channel:'email',receiptRecorded:'true'},{channel:'sms',receiptRecorded:false}]}])('rejects malformed or foreign flags without displaying any rows',async(value)=>{const f=fixture();vi.mocked(f.client.readConfirmationReceiptStatus).mockResolvedValue(value as ConfirmationReceiptStatus);setup(f.client);refresh();await screen.findByRole('alert');expect(screen.queryByRole('table')).toBeNull();});
it('shows unavailable capability without an invented read result',()=>{setup();expect(screen.getByRole('status')).toHaveTextContent('unavailable');expect(screen.queryByRole('button')).toBeNull();expect(screen.queryByRole('table')).toBeNull();});
it.each(['FORBIDDEN','UNAUTHENTICATED','UNSUPPORTED_CONFIG','NOT_AVAILABLE'] as const)('renders sanitized %s read failure without any recorded flags',async(code)=>{const f=fixture();vi.mocked(f.client.readConfirmationReceiptStatus).mockRejectedValue(new ConfirmationReceiptStatusError(code,'raw-private-value'));setup(f.client);refresh();await screen.findByRole('alert');expect(screen.queryByRole('table')).toBeNull();expect(document.body.textContent).not.toContain('raw-private-value');});
it('uses the real client fresh owner gate and never reaches the receipt API for a staff membership',async()=>{const json=(value:unknown)=>new Response(JSON.stringify(value),{status:200,headers:{'Content-Type':'application/json'}});const transport=vi.fn<typeof fetch>(async input=>{const url=String(input);if(url.includes('/token?'))return json({access_token:'synthetic-private-token'});if(url.endsWith('/user'))return json({id:'44444444-4444-4444-8444-444444444444'});if(url.includes('/tenant_members?'))return json([{tenant_id:tenant,role:'BUSINESS_STAFF'}]);throw Error('Receipt API should not be called');});const client=createRuntimeClient({url:'https://example.supabase.co',publishableKey:'sb_publishable_fixture',tenantId:tenant,bookingApiOrigin:'https://api.example.test',allowMembershipDiscovery:true},transport);await client.signIn('owner@example.test','synthetic');setup(client);refresh();await screen.findByRole('alert');expect(screen.getByRole('alert')).toHaveTextContent('authenticated owner');expect(transport.mock.calls.some(([url])=>String(url).includes('/api/confirmation-receipts'))).toBe(false);expect(document.body.textContent).not.toContain('synthetic-private-token');});
it('accepts an explicit first refresh immediately after commit before passive effects can run',async()=>{
 const f=fixture(receipt(true,false));
 function EarliestRefresh(){useLayoutEffect(()=>{fireEvent.click(screen.getByRole('button',{name:'Refresh confirmation receipts'}));},[]);return <ConnectedConfirmationReceipts client={f.client} tenantId={tenant} bookingId={booking}/>;}
 render(<EarliestRefresh/>);await screen.findByRole('table');expect(f.client.readConfirmationReceiptStatus).toHaveBeenCalledTimes(1);expect(screen.getByText('Successful-send receipt recorded')).toBeTruthy();
});
