import {afterEach,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {createRuntimeClient} from '@lumin/runtime-client';
import {ConnectedBusinessOnboarding} from './ConnectedBusinessOnboarding';
const tenant='11111111-1111-4111-8111-111111111111',actor='22222222-2222-4222-8222-222222222222',created='33333333-3333-4333-8333-333333333333';
const profile={schemaVersion:1,tenantId:created,businessType:'HOUSEKEEPING',templateVersion:1};
const json=(value:unknown,status=200)=>new Response(JSON.stringify(value),{status});
afterEach(()=>{cleanup();vi.restoreAllMocks();vi.unstubAllGlobals();});
async function fixture(action:()=>Promise<Response>,role='BUSINESS_OWNER'){
 const calls=vi.fn<typeof fetch>(async input=>String(input).includes('/auth/v1/token')?json({access_token:'private-onboarding-owner'}):String(input).includes('/auth/v1/user')?json({id:actor}):String(input).includes('/tenant_members?')?json(role==='NONE'?[]:[{tenant_id:tenant,role}]):action());
 const client=createRuntimeClient({url:'https://example.supabase.co',publishableKey:'sb_publishable_fixture',tenantId:tenant,bookingApiOrigin:'https://api.example.test'},calls);await client.signIn('owner@example.test','fixture');return{client,calls};
}
function fill(){fireEvent.click(screen.getByRole('button',{name:'Create a new staging business'}));for(const [label,value] of [['New business name','New housekeeping'],['New business slug','new-housekeeping'],['New business timezone','America/Los_Angeles'],['New business currency','USD'],['Permanent business type','HOUSEKEEPING']] as const)fireEvent.change(screen.getByLabelText(label),{target:{value}});fireEvent.click(screen.getByRole('button',{name:'Review new business'}));}
const props={tenantId:tenant,role:'BUSINESS_OWNER',staging:true,apiConfigured:true};
it('reviews exactly six permanent types and creates only after confirmation, then explicitly opens the receipt',async()=>{
 const {client,calls}=await fixture(async()=>json({ok:true,data:profile}));const onOpen=vi.fn(async()=>{});render(<ConnectedBusinessOnboarding client={client} {...props} onStateChange={()=>{}} onOpen={onOpen}/>);expect(calls).toHaveBeenCalledTimes(2);fill();expect(screen.getAllByRole('option')).toHaveLength(7);expect(screen.getByRole('dialog',{name:'Review permanent business type'})).toBeTruthy();expect(screen.getByRole('button',{name:'Cancel new business'})).toHaveFocus();expect(screen.getByLabelText('New business name')).toBeDisabled();expect(calls).toHaveBeenCalledTimes(2);fireEvent.keyDown(screen.getByRole('dialog'),{key:'Escape'});expect(screen.queryByRole('dialog')).toBeNull();expect(screen.getByRole('button',{name:'Review new business'})).toHaveFocus();fireEvent.click(screen.getByRole('button',{name:'Review new business'}));fireEvent.click(screen.getByRole('button',{name:'Confirm create staging business'}));await screen.findByText(/Server creation receipt verified/);expect(onOpen).not.toHaveBeenCalled();expect(calls).toHaveBeenCalledTimes(4);const sent=JSON.parse(String(calls.mock.calls[3]?.[1]?.body));expect(sent).toEqual({name:'New housekeeping',slug:'new-housekeeping',timezone:'America/Los_Angeles',currency:'USD',businessType:'HOUSEKEEPING',idempotencyKey:expect.any(String)});expect(Object.keys(sent)).not.toContain('tenantId');expect(document.body.textContent).not.toContain('private-onboarding-owner');fireEvent.click(screen.getByRole('button',{name:'Open created business'}));await waitFor(()=>expect(onOpen).toHaveBeenCalledExactlyOnceWith(profile));
});
it.each([{role:'BUSINESS_STAFF',staging:true,apiConfigured:true},{role:'BUSINESS_OWNER',staging:false,apiConfigured:true},{role:'BUSINESS_OWNER',staging:true,apiConfigured:false}])('blocks creation for unavailable or unauthorized workspace %j',async(gates)=>{
 const {client,calls}=await fixture(async()=>{throw Error('unexpected');});render(<ConnectedBusinessOnboarding client={client} tenantId={tenant} {...gates} onStateChange={()=>{}} onOpen={async()=>{}}/>);expect(screen.queryByRole('button',{name:'Create a new staging business'})).toBeNull();expect(screen.queryByRole('button',{name:'Check current business type'})).toBeNull();expect(calls).toHaveBeenCalledTimes(2);
});
it('reports a server-disabled staging capability without a receipt or a retry/new attempt',async()=>{
 const {client,calls}=await fixture(async()=>json({ok:false,code:'UNSUPPORTED_CONFIG'},422));render(<ConnectedBusinessOnboarding client={client} {...props} onStateChange={()=>{}} onOpen={async()=>{}}/>);fill();fireEvent.click(screen.getByRole('button',{name:'Confirm create staging business'}));await screen.findByText(/server staging capability is disabled/);expect(screen.queryByText(/Server creation receipt verified/)).toBeNull();expect(screen.queryByRole('button',{name:'Retry this same business creation'})).toBeNull();expect(screen.queryByRole('button',{name:'Review new business'})).toBeNull();expect(calls).toHaveBeenCalledTimes(4);
});
it('reads an existing uninitialized business honestly and never assigns a type to it',async()=>{
 const {client,calls}=await fixture(async()=>json({ok:false,code:'NOT_AVAILABLE'},404));render(<ConnectedBusinessOnboarding client={client} {...props} onStateChange={()=>{}} onOpen={async()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:'Check current business type'}));await screen.findByText(/This existing business is uninitialized/);expect(calls.mock.calls[2]?.[0]).toBe('https://api.example.test/api/business-profile?tenantId='+tenant);expect(calls.mock.calls[2]?.[1]?.method).toBe('GET');expect(screen.queryByLabelText('Permanent business type')).toBeNull();expect(screen.queryByText(/Current business type:/)).toBeNull();
});
it('retains frozen key/body after lost delivery, remounts locked, and retries only explicitly with identical body',async()=>{
 let n=0;const {client,calls}=await fixture(async()=>++n===1?Promise.reject(Error('PRIVATE-NETWORK-ERROR')):json({ok:true,data:profile}));const first=render(<ConnectedBusinessOnboarding client={client} {...props} onStateChange={()=>{}} onOpen={async()=>{}}/>);fill();fireEvent.click(screen.getByRole('button',{name:'Confirm create staging business'}));await screen.findByRole('button',{name:'Retry this same business creation'});const state=client.businessCreationState();expect(state.phase).toBe('unknown');first.unmount();render(<ConnectedBusinessOnboarding client={client} {...props} onStateChange={()=>{}} onOpen={async()=>{}}/>);expect(screen.queryByLabelText('New business name')).toBeNull();expect(calls).toHaveBeenCalledTimes(4);expect(client.businessCreationState()).toEqual(state);fireEvent.click(screen.getByRole('button',{name:'Retry this same business creation'}));await screen.findByText(/Server creation receipt verified/);expect(calls.mock.calls[3]?.[1]?.body).toBe(calls.mock.calls[5]?.[1]?.body);expect(calls).toHaveBeenCalledTimes(6);expect(document.body.textContent).not.toContain('PRIVATE-NETWORK-ERROR');
});
it('does not unlock an earlier uncertain attempt after a same-body conflict response',async()=>{
 let n=0;const {client,calls}=await fixture(async()=>json({ok:false,code:++n===1?'INTERNAL_ERROR':'CONFLICT'},n===1?500:409));render(<ConnectedBusinessOnboarding client={client} {...props} onStateChange={()=>{}} onOpen={async()=>{}}/>);fill();fireEvent.click(screen.getByRole('button',{name:'Confirm create staging business'}));await screen.findByRole('button',{name:'Retry this same business creation'});const state=client.businessCreationState();fireEvent.click(screen.getByRole('button',{name:'Retry this same business creation'}));await screen.findByText(/response does not prove an earlier attempt failed/);expect(client.businessCreationState()).toEqual(state);expect(screen.queryByRole('button',{name:'Create a new staging business'})).toBeNull();expect(calls).toHaveBeenCalledTimes(6);
});
it('recovers local pending state after remount without automatic POST or permanent busy controls',async()=>{
 let finish!:(response:Response)=>void;const {client,calls}=await fixture(()=>new Promise(r=>finish=r));const first=render(<ConnectedBusinessOnboarding client={client} {...props} onStateChange={()=>{}} onOpen={async()=>{}}/>);fill();fireEvent.click(screen.getByRole('button',{name:'Confirm create staging business'}));await waitFor(()=>expect(finish).toBeTypeOf('function'));first.unmount();render(<ConnectedBusinessOnboarding client={client} {...props} onStateChange={()=>{}} onOpen={async()=>{}}/>);finish(json({ok:true,data:profile}));await waitFor(()=>expect(client.businessCreationState().phase).toBe('created'));fireEvent.click(screen.getByRole('button',{name:"Check this session's business creation state"}));await screen.findByRole('button',{name:'Open created business'});expect(calls).toHaveBeenCalledTimes(4);
});
it('retains a verified creation receipt when opening its owner context fails',async()=>{
 const {client}=await fixture(async()=>json({ok:true,data:profile}));render(<ConnectedBusinessOnboarding client={client} {...props} onStateChange={()=>{}} onOpen={async()=>{throw Error('Owner membership remains unverified.');}}/>);fill();fireEvent.click(screen.getByRole('button',{name:'Confirm create staging business'}));await screen.findByText(/Server creation receipt verified/);fireEvent.click(screen.getByRole('button',{name:'Open created business'}));await screen.findByText('Owner membership remains unverified.');expect(screen.getByText(/Server creation receipt verified/)).toHaveTextContent(created);expect(screen.getByRole('button',{name:'Open created business'})).toBeEnabled();
});
it('drops old-client review/profile and late creation receipts on context replacement',async()=>{
 let finish!:(response:Response)=>void;const first=await fixture(()=>new Promise(r=>finish=r)),second=await fixture(async()=>{throw Error('unexpected');});const {rerender}=render(<ConnectedBusinessOnboarding client={first.client} {...props} onStateChange={()=>{}} onOpen={async()=>{}}/>);fill();fireEvent.click(screen.getByRole('button',{name:'Confirm create staging business'}));await waitFor(()=>expect(finish).toBeTypeOf('function'));rerender(<ConnectedBusinessOnboarding client={second.client} {...props} tenantId={created} onStateChange={()=>{}} onOpen={async()=>{}}/>);finish(json({ok:true,data:profile}));await waitFor(()=>expect(first.client.businessCreationState().phase).toBe('created'));expect(screen.queryByText(/Server creation receipt verified/)).toBeNull();expect(screen.queryByRole('dialog')).toBeNull();expect(second.calls).toHaveBeenCalledTimes(2);
});

it('suppresses a late current-business profile read after selected tenant changes',async()=>{
 let finish!:(response:Response)=>void;const {client,calls}=await fixture(()=>new Promise(r=>finish=r));const {rerender}=render(<ConnectedBusinessOnboarding client={client} {...props} onStateChange={()=>{}} onOpen={async()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:'Check current business type'}));await waitFor(()=>expect(finish).toBeTypeOf('function'));rerender(<ConnectedBusinessOnboarding client={client} {...props} tenantId={created} onStateChange={()=>{}} onOpen={async()=>{}}/>);finish(json({ok:true,data:{...profile,tenantId:tenant}}));await waitFor(()=>expect(screen.queryByText(/Checking current business type/)).toBeNull());expect(screen.queryByText(/Current business type:/)).toBeNull();expect(screen.queryByText(/This existing business is uninitialized/)).toBeNull();expect(calls).toHaveBeenCalledTimes(3);
});

it('shows structural defaults only from verified profile receipts, never from a raw selected type or uninitialized business',async()=>{
 const {client,calls}=await fixture(async()=>json({ok:true,data:{...profile,tenantId:tenant,businessType:'AUTO_DETAILING'}}));render(<ConnectedBusinessOnboarding client={client} {...props} onStateChange={()=>{}} onOpen={async()=>{}}/>);fill();expect(screen.queryByRole('heading',{name:'Unapplied setup defaults'})).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Cancel new business'}));fireEvent.click(screen.getByRole('button',{name:'Check current business type'}));await screen.findByRole('heading',{name:'Unapplied setup defaults'});expect(screen.getByText(/Suggested catalog language: Detailing services/)).toHaveTextContent('resource group: Technicians');expect(screen.getByText(/They are not applied or persisted here/)).toBeTruthy();expect(screen.queryByText(/option group: Cleaning options/)).toBeNull();expect(calls).toHaveBeenCalledTimes(3);
});

it.each([['HOUSEKEEPING','Cleaners'],['AUTO_DETAILING','Technicians'],['VEHICLE_RENTAL','Fleet'],['EQUIPMENT_RENTAL','Equipment'],['EVENT_RENTAL','Inventory'],['JUNK_REMOVAL','Crews']] as const)('uses verified %s contextual resource terminology without adding primary navigation',async(businessType,resourceLabel)=>{
 const {client}=await fixture(async()=>json({ok:true,data:{...profile,tenantId:tenant,businessType}}));render(<ConnectedBusinessOnboarding client={client} {...props} onStateChange={()=>{}} onOpen={async()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:'Check current business type'}));await screen.findByRole('heading',{name:'Unapplied setup defaults'});expect(screen.getByText(/Suggested catalog language:/)).toHaveTextContent('resource group: '+resourceLabel+'.');expect(screen.queryByRole('navigation')).toBeNull();expect(screen.queryByRole('link',{name:resourceLabel})).toBeNull();expect(screen.getByText(/They are not applied or persisted here/)).toBeTruthy();
});

it('offers first-business review only with explicit verified empty membership eligibility and keeps owner role unassigned',async()=>{
 const {client,calls}=await fixture(async()=>json({ok:true,data:profile}),'NONE');render(<ConnectedBusinessOnboarding client={client} {...props} role={undefined} tenantId="" firstBusinessEligible onStateChange={()=>{}} onOpen={async()=>{}}/>);expect(screen.getByText(/verified membership lookup returned no assigned businesses/)).toBeTruthy();expect(screen.queryByRole('button',{name:'Check current business type'})).toBeNull();fill();expect(calls).toHaveBeenCalledTimes(2);fireEvent.click(screen.getByRole('button',{name:'Confirm create staging business'}));await screen.findByText(/Server creation receipt verified/);expect(calls).toHaveBeenCalledTimes(4);expect(calls.mock.calls[2]?.[0]).toContain('user_id=eq.'+actor);expect(screen.getByRole('button',{name:'Open created business'})).toBeEnabled();
});
it.each([{role:undefined,tenantId:'',firstBusinessEligible:false},{role:'BUSINESS_STAFF',tenantId:tenant,firstBusinessEligible:true},{role:'WORKER',tenantId:tenant,firstBusinessEligible:true},{role:undefined,tenantId:tenant,firstBusinessEligible:true}])('does not treat unverified, nonempty, staff or worker context as first-business eligibility %j',async(context)=>{
 const {client,calls}=await fixture(async()=>{throw Error('unexpected');});render(<ConnectedBusinessOnboarding client={client} {...props} {...context} onStateChange={()=>{}} onOpen={async()=>{}}/>);expect(screen.queryByRole('button',{name:'Create a new staging business'})).toBeNull();expect(screen.queryByLabelText('Permanent business type')).toBeNull();expect(calls).toHaveBeenCalledTimes(2);
});
it('keeps a first-business uncertain attempt frozen across remount and retries explicitly with the exact same key and body',async()=>{
 let n=0;const {client,calls}=await fixture(async()=>++n===1?Promise.reject(Error('lost')):json({ok:true,data:profile}),'NONE');const component=<ConnectedBusinessOnboarding client={client} {...props} role={undefined} tenantId="" firstBusinessEligible onStateChange={()=>{}} onOpen={async()=>{}}/>;const first=render(component);fill();fireEvent.click(screen.getByRole('button',{name:'Confirm create staging business'}));await screen.findByRole('button',{name:'Retry this same business creation'});first.unmount();render(component);expect(screen.queryByRole('button',{name:'Create a new staging business'})).toBeNull();expect(calls).toHaveBeenCalledTimes(4);fireEvent.click(screen.getByRole('button',{name:'Retry this same business creation'}));await screen.findByText(/Server creation receipt verified/);expect(calls.mock.calls[3]?.[1]?.body).toBe(calls.mock.calls[5]?.[1]?.body);
});

async function offerFixture(action:(input:string,init?:RequestInit)=>Promise<Response>){
 const calls=vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>{const path=String(input);if(path.includes('/token?'))return json({access_token:'private-offer-owner'});if(path.endsWith('/user'))return json({id:actor});if(path.includes('/tenant_members?'))return json([{tenant_id:created,role:'BUSINESS_OWNER'}]);if(path.endsWith('/api/businesses')||path.includes('/business-profile?'))return json({ok:true,data:profile});if(path.includes('/api/profile?'))return json({ok:true,data:{schemaVersion:1,profile:{id:created,name:'New housekeeping',slug:'new-housekeeping',timezone:'UTC',currency:'USD',status:'active'}}});return action(path,init);});
 const client=createRuntimeClient({url:'https://example.supabase.co',publishableKey:'sb_publishable_fixture',tenantId:tenant,bookingApiOrigin:'https://api.example.test'},calls);await client.signIn('owner@example.test','fixture');await client.createBusiness({name:'New housekeeping',slug:'new-housekeeping',timezone:'UTC',currency:'USD',businessType:'HOUSEKEEPING',idempotencyKey:'business-created-offer-0001'});return{client,calls};
}
const createdOffer={schemaVersion:1,tenantId:created,service:{id:tenant,name:'Standard clean',description:'Reviewed description',archetype:'simple',price:{amount:12500,currency:'USD'},durationMinutes:60}};
async function reviewOffer(){fireEvent.click(screen.getByRole('button',{name:'Verify owner and offer currency'}));await screen.findByLabelText('Offer name');for(const [label,value] of [['Offer name','Standard clean'],['Offer description','Reviewed description'],['Offer price in minor units','12500'],['Offer duration in minutes','60']] as const)fireEvent.change(screen.getByLabelText(label),{target:{value}});fireEvent.click(screen.getByRole('button',{name:'Review housekeeping offer price'}));}
it('reviews the authoritative offer price after fresh owner profile checks and writes only on explicit confirmation',async()=>{
 const {client,calls}=await offerFixture(async()=>json({ok:true,data:createdOffer}));render(<ConnectedBusinessOnboarding client={client} {...props} tenantId={created} onStateChange={()=>{}} onOpen={async()=>{}}/>);expect(screen.queryByLabelText('Offer name')).toBeNull();await reviewOffer();expect(screen.getByRole('dialog',{name:'Review authoritative offer price'})).toHaveTextContent('12500 minor units USD; 60 minutes');expect(screen.getByRole('button',{name:'Cancel offer creation'})).toHaveFocus();expect(screen.getByLabelText('Offer name')).toBeDisabled();expect(calls.mock.calls.filter(call=>String(call[0]).includes('/simple-offers'))).toHaveLength(0);fireEvent.keyDown(screen.getByRole('dialog'),{key:'Escape'});expect(screen.getByRole('button',{name:'Review housekeeping offer price'})).toHaveFocus();fireEvent.click(screen.getByRole('button',{name:'Review housekeeping offer price'}));fireEvent.click(screen.getByRole('button',{name:'Confirm create housekeeping offer'}));await screen.findByText(/Server offer receipt verified/);expect(calls.mock.calls.filter(call=>String(call[0]).includes('/simple-offers'))).toHaveLength(1);expect(screen.getByText(/Availability and publication are not configured/)).toBeTruthy();expect(screen.getByRole('button',{name:'Verify scheduling owner and timezone'})).toBeEnabled();expect(document.body.textContent).not.toContain('private-offer-owner');
});
it.each(['0','1.5','9007199254740992','-1'])('rejects invalid minor-unit price %s without a writer',async(amount)=>{const {client,calls}=await offerFixture(async()=>{throw Error('unexpected');});render(<ConnectedBusinessOnboarding client={client} {...props} tenantId={created} onStateChange={()=>{}} onOpen={async()=>{}}/>);await reviewOffer();fireEvent.click(screen.getByRole('button',{name:'Cancel offer creation'}));fireEvent.change(screen.getByLabelText('Offer price in minor units'),{target:{value:amount}});fireEvent.submit(screen.getByLabelText('Offer name').closest('form')!);expect(screen.queryByRole('dialog')).toBeNull();expect(calls.mock.calls.filter(call=>String(call[0]).includes('/simple-offers'))).toHaveLength(0);});
it('keeps lost offer delivery frozen across remount and retries the exact body only explicitly',async()=>{
 let n=0;const {client,calls}=await offerFixture(async()=>++n===1?Promise.reject(Error('private failure')):json({ok:true,data:createdOffer}));const element=<ConnectedBusinessOnboarding client={client} {...props} tenantId={created} onStateChange={()=>{}} onOpen={async()=>{}}/>;const first=render(element);await reviewOffer();fireEvent.click(screen.getByRole('button',{name:'Confirm create housekeeping offer'}));await screen.findByRole('button',{name:'Retry this same housekeeping offer'});const locked=client.simpleOfferState(created);first.unmount();render(element);expect(screen.queryByLabelText('Offer name')).toBeNull();expect(client.simpleOfferState(created)).toEqual(locked);expect(calls.mock.calls.filter(call=>String(call[0]).includes('/simple-offers'))).toHaveLength(1);fireEvent.click(screen.getByRole('button',{name:'Retry this same housekeeping offer'}));await screen.findByText(/Server offer receipt verified/);const writes=calls.mock.calls.filter(call=>String(call[0]).includes('/simple-offers'));expect(writes).toHaveLength(2);expect(writes[0]?.[1]?.body).toBe(writes[1]?.[1]?.body);
});
it('recovers pending offer state after remount without another POST and suppresses another tenant view',async()=>{
 let finish!:(response:Response)=>void;const {client,calls}=await offerFixture(()=>new Promise(resolve=>finish=resolve));const element=<ConnectedBusinessOnboarding client={client} {...props} tenantId={created} onStateChange={()=>{}} onOpen={async()=>{}}/>;const first=render(element);await reviewOffer();fireEvent.click(screen.getByRole('button',{name:'Confirm create housekeeping offer'}));await waitFor(()=>expect(finish).toBeTypeOf('function'));first.unmount();const second=render(element);finish(json({ok:true,data:createdOffer}));await waitFor(()=>expect(client.simpleOfferState(created).phase).toBe('created'));fireEvent.click(screen.getByRole('button',{name:"Check this session's offer state"}));await screen.findByText(/Server offer receipt verified/);second.rerender(<ConnectedBusinessOnboarding client={client} {...props} tenantId={tenant} onStateChange={()=>{}} onOpen={async()=>{}}/>);expect(screen.queryByLabelText('Housekeeping simple offer setup')).toBeNull();expect(calls.mock.calls.filter(call=>String(call[0]).includes('/simple-offers'))).toHaveLength(1);
});

it('drops a late verified offer currency when the selected business changes without posting',async()=>{const {client,calls}=await offerFixture(async()=>{throw Error('unexpected');});let finish!:(response:Response)=>void;calls.mockImplementationOnce(()=>new Promise(resolve=>finish=resolve));const view=render(<ConnectedBusinessOnboarding client={client} {...props} tenantId={created} onStateChange={()=>{}} onOpen={async()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:'Verify owner and offer currency'}));await waitFor(()=>expect(finish).toBeTypeOf('function'));view.rerender(<ConnectedBusinessOnboarding client={client} {...props} tenantId={tenant} onStateChange={()=>{}} onOpen={async()=>{}}/>);finish(json([{tenant_id:created,role:'BUSINESS_OWNER'}]));await waitFor(()=>expect(calls).toHaveBeenCalledTimes(7));expect(screen.queryByLabelText('Offer name')).toBeNull();expect(screen.queryByLabelText('Housekeeping simple offer setup')).toBeNull();expect(calls.mock.calls.some(call=>String(call[0]).includes('/simple-offers'))).toBe(false);});

async function resumedOfferFixture(profileResponse:Response=json({ok:true,data:profile}),role='BUSINESS_OWNER'){
 const calls=vi.fn(async(input:RequestInfo|URL)=>{const path=String(input);if(path.includes('/token?'))return json({access_token:'private-resumed-owner'});if(path.endsWith('/user'))return json({id:actor});if(path.includes('/tenant_members?'))return json([{tenant_id:created,role}]);if(path.includes('/business-profile?'))return profileResponse.clone();if(path.includes('/api/profile?'))return json({ok:true,data:{schemaVersion:1,profile:{id:created,name:'Persisted housekeeping',slug:'persisted-housekeeping',timezone:'UTC',currency:'USD',status:'active'}}});if(path.includes('/simple-offers'))return json({ok:true,data:createdOffer});throw Error('Unexpected request');});
 const client=createRuntimeClient({url:'https://example.supabase.co',publishableKey:'sb_publishable_fixture',tenantId:created,bookingApiOrigin:'https://api.example.test'},calls);await client.signIn('owner@example.test','fixture');return{client,calls};
}
it('resumes a persisted housekeeping business after fresh sign-in without a RAM creation receipt and requires deliberate uncertainty acknowledgment',async()=>{const {client,calls}=await resumedOfferFixture();expect(client.businessCreationState()).toEqual({phase:'ready'});render(<ConnectedBusinessOnboarding client={client} {...props} tenantId={created} onStateChange={()=>{}} onOpen={async()=>{}}/>);expect(screen.queryByRole('button',{name:'Verify owner and offer currency'})).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Check current business type'}));await screen.findByRole('button',{name:'Verify owner and offer currency'});expect(screen.getByRole('note')).toHaveTextContent('do not create a replacement key or duplicate offer');fireEvent.click(screen.getByRole('button',{name:'Verify owner and offer currency'}));await screen.findByLabelText('Offer name');expect(screen.getByRole('button',{name:'Review housekeeping offer price'})).toBeDisabled();for(const [label,value] of [['Offer name','Standard clean'],['Offer description','Reviewed description'],['Offer price in minor units','12500'],['Offer duration in minutes','60']] as const)fireEvent.change(screen.getByLabelText(label),{target:{value}});fireEvent.submit(screen.getByLabelText('Offer name').closest('form')!);expect(screen.queryByRole('dialog')).toBeNull();fireEvent.click(screen.getByRole('checkbox',{name:'I have no unresolved earlier offer creation attempt'}));fireEvent.click(screen.getByRole('button',{name:'Review housekeeping offer price'}));expect(screen.getByRole('dialog',{name:'Review authoritative offer price'})).toBeTruthy();expect(calls.mock.calls.some(call=>String(call[0]).includes('/simple-offers'))).toBe(false);fireEvent.click(screen.getByRole('button',{name:'Confirm create housekeeping offer'}));await screen.findByText(/Server offer receipt verified/);expect(calls.mock.calls.filter(call=>String(call[0]).includes('/simple-offers'))).toHaveLength(1);expect(calls.mock.calls.some(call=>String(call[0]).endsWith('/api/businesses'))).toBe(false);expect(document.body.textContent).not.toContain('private-resumed-owner');});
it.each([json({ok:false,code:'NOT_AVAILABLE'},404),json({ok:true,data:{...profile,businessType:'AUTO_DETAILING'}}),json({ok:true,data:{...profile,tenantId:tenant}})])('does not expose resumed creation for uninitialized, unsupported or foreign profile %#',async(response)=>{const {client,calls}=await resumedOfferFixture(response);render(<ConnectedBusinessOnboarding client={client} {...props} tenantId={created} onStateChange={()=>{}} onOpen={async()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:'Check current business type'}));await waitFor(()=>expect(calls).toHaveBeenCalledTimes(3));await waitFor(()=>expect(screen.queryByText('Checking current business type...')).toBeNull());expect(screen.queryByRole('button',{name:'Verify owner and offer currency'})).toBeNull();expect(screen.queryByLabelText('Offer name')).toBeNull();expect(calls.mock.calls.some(call=>String(call[0]).includes('/simple-offers'))).toBe(false);});
it('does not expose resumed offer setup to staff even if the persisted business is housekeeping',async()=>{const {client,calls}=await resumedOfferFixture(undefined,'BUSINESS_STAFF');render(<ConnectedBusinessOnboarding client={client} {...props} tenantId={created} role="BUSINESS_STAFF" onStateChange={()=>{}} onOpen={async()=>{}}/>);expect(screen.queryByRole('button',{name:'Check current business type'})).toBeNull();expect(screen.queryByRole('button',{name:'Verify owner and offer currency'})).toBeNull();expect(calls).toHaveBeenCalledTimes(2);});
it('suppresses a late persisted-housekeeping profile after tenant selection changes',async()=>{const {client,calls}=await resumedOfferFixture();let finish!:(response:Response)=>void;calls.mockImplementationOnce(()=>new Promise(resolve=>finish=resolve));const view=render(<ConnectedBusinessOnboarding client={client} {...props} tenantId={created} onStateChange={()=>{}} onOpen={async()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:'Check current business type'}));await waitFor(()=>expect(finish).toBeTypeOf('function'));view.rerender(<ConnectedBusinessOnboarding client={client} {...props} tenantId={tenant} onStateChange={()=>{}} onOpen={async()=>{}}/>);finish(json({ok:true,data:profile}));await waitFor(()=>expect(screen.queryByText('Checking current business type...')).toBeNull());expect(screen.queryByRole('button',{name:'Verify owner and offer currency'})).toBeNull();expect(screen.queryByLabelText('Offer name')).toBeNull();});
