import {useEffect,useRef,useState} from 'react';
import {PaidInstallHealth} from '@lumin/contracts';
import {PublicationError,type PaidInstallReceipt,type RuntimeClient} from '@lumin/runtime-client';
type Client=Pick<RuntimeClient,'paidPublicationHealth'>;
type Props={client:Client;tenantId:string;flowId:string;receipt:PaidInstallReceipt};
type View={client:Client;selection:string;phase:'idle'|'checking'|'checked'|'failed';health?:PaidInstallHealth;error:string};
const validId=(value:string)=>/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(value);
export function ConnectedPublicationHealth(props:Props){const receipt=props.receipt;if(!validId(props.tenantId)||!validId(props.flowId)||!receipt||Object.keys(receipt).length!==4||!['versionId','installationId','renderSchemaVersion','hostedPath'].every(key=>Object.hasOwn(receipt,key))||!validId(receipt.versionId)||!validId(receipt.installationId)||(receipt.renderSchemaVersion!==3&&receipt.renderSchemaVersion!==4)||receipt.hostedPath!=='/checkout/flow/'+receipt.installationId)return <section aria-label="Publication install evidence"><p role="alert">Choose a verified publication receipt before checking install evidence.</p></section>;return <HealthEvidence {...props}/>;}
function HealthEvidence({client,tenantId,flowId,receipt}:Props){
 const selection=JSON.stringify([tenantId,flowId,receipt.versionId,receipt.installationId,receipt.renderSchemaVersion,receipt.hostedPath]),generation=useRef(0),inFlight=useRef(false);
 const [snapshot,setSnapshot]=useState<View>(()=>({client,selection,phase:'idle',error:''}));
 useEffect(()=>{generation.current++;inFlight.current=false;setSnapshot({client,selection,phase:'idle',error:''});return()=>{generation.current++;};},[client,selection]);
 const view:View=snapshot.client===client&&snapshot.selection===selection?snapshot:{client,selection,phase:'idle',error:''};
 async function check(){if(inFlight.current)return;const at=generation.current;inFlight.current=true;setSnapshot({client,selection,phase:'checking',error:''});try{
  const value=await client.paidPublicationHealth(tenantId,flowId,{...receipt});const parsed=PaidInstallHealth.safeParse(value),bound=parsed?.success?parsed.data:undefined,r=bound?.installation.receipt;
  if(!bound||bound.flowId!==flowId||bound.versionId!==receipt.versionId||bound.renderSchemaVersion!==receipt.renderSchemaVersion||r&&(r.installationId!==receipt.installationId||r.versionId!==receipt.versionId||r.renderSchemaVersion!==receipt.renderSchemaVersion||r.hostedPath!==receipt.hostedPath))throw new PublicationError('not_sent','Install evidence does not match this selected publication receipt.');
  if(at===generation.current)setSnapshot({client,selection,phase:'checked',health:bound,error:''});
 }catch(error){if(at===generation.current)setSnapshot({client,selection,phase:'failed',error:error instanceof PublicationError?error.message:'Install evidence could not be checked. Browser load health remains unverified.'});}finally{if(at===generation.current)inFlight.current=false;}}
 const health=view.phase==='checked'?view.health:undefined;
 return <section aria-label="Publication install evidence" style={{minWidth:0,overflowWrap:'anywhere'}}><h3>Install evidence</h3><p>Selected publication: {flowId}; version: {receipt.versionId}; installation: {receipt.installationId}.</p><p>This read-only staging check does not load a customer form, publish, retry an uncertain writer or change installation settings. A publication link and session issuance do not prove that a browser loaded the form.</p><button type="button" disabled={view.phase==='checking'} onClick={()=>void check()}>{view.phase==='checking'?'Checking install evidence...':'Check install evidence'}</button>
 {view.phase==='checking'&&<p role="status">Checking current server evidence...</p>}{view.phase==='idle'&&<p role="status">Install evidence has not been checked. Browser load health is unverified.</p>}{view.error&&<p role="alert">{view.error}</p>}
 {health&&<><p role="status">Install evidence at last check: {health.status==='unknown'?'Unknown':'Degraded'}. Browser load health is unverified.</p><p>{health.installation.status==='available'?'The server returned the matching installation receipt. This does not prove browser loading.':'The installation could not be verified by this check. This does not prove that no installation exists.'}</p><p>Catalog at last check: {health.catalog.status==='compatible'?'Compatible with this pinned version':health.catalog.status==='incompatible'?'Incompatible with this pinned version':'Unavailable for verification'}.</p><p>Stored issued sessions for this version: {health.customerEvidence.sessionCountCapped?'at least ':''}{health.customerEvidence.issuedSessionCount.toLocaleString('en-US')}. Session issuance is not successful browser-load evidence.</p><p>Browser-load evidence: unavailable. Last successful browser load: unavailable.</p><p>TEST currently confirmed staging bookings for this version: {health.customerEvidence.bookingCountCapped?'at least ':''}{health.customerEvidence.confirmedStagingBookingCount.toLocaleString('en-US')}. These counts use simulated staging payments. Completed, cancelled and refunded bookings are excluded. They do not prove live payments or install health.</p><p>Last currently confirmed TEST staging booking: {health.customerEvidence.lastConfirmedStagingBookingAt??'unavailable'}.</p><p>Test payment evidence: staging mock, simulated, enabled. Browser loading remains unverified even when a test booking was confirmed.</p></>}
 </section>;
}
