import {useEffect,useRef,useState,type FormEvent} from 'react';
import {CreateOfferScheduling,SimpleOfferReceipt} from '@lumin/contracts';
import {BusinessOnboardingError,type RuntimeClient,type OfferSchedulingState,type SimpleOfferContext} from '@lumin/runtime-client';
type Client=Pick<RuntimeClient,'simpleOfferContext'|'createOfferScheduling'|'offerSchedulingState'>;
type Props={client:Client;tenantId:string;offer:SimpleOfferReceipt;contextBusy?:boolean;onStateChange:()=>void};
const weekdays=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
const empty={start:'',end:'',lead:'',horizon:'',interval:''};
const minute=(value:string)=>/^([01][0-9]|2[0-3]):[0-5][0-9]$/.test(value)?Number(value.slice(0,2))*60+Number(value.slice(3)):NaN;
const time=(value:number)=>String(Math.floor(value/60)).padStart(2,'0')+':'+String(value%60).padStart(2,'0');
export function ConnectedOfferScheduling(props:Props){const parsed=SimpleOfferReceipt.safeParse(props.offer);if(!parsed.success||parsed.data.tenantId!==props.tenantId.toLowerCase())return <section aria-label="Offer scheduling setup"><p role="alert">Scheduling requires a valid offer receipt for this exact business.</p></section>;return <SchedulingOwner {...props} offer={parsed.data}/>;}
function SchedulingOwner({client,tenantId,offer,contextBusy=false,onStateChange}:Props){
 const serviceId=offer.service.id,[fields,setFields]=useState(empty),[days,setDays]=useState<number[]>([]),[context,setContext]=useState<{client:Client;tenantId:string;serviceId:string;value:SimpleOfferContext}|null>(null),[checking,setChecking]=useState(false),[error,setError]=useState('');
 const [snapshot,setSnapshot]=useState(()=>({client,tenantId,serviceId,state:client.offerSchedulingState(tenantId,serviceId)})),[review,setReview]=useState<{client:Client;tenantId:string;serviceId:string;body:CreateOfferScheduling}|null>(null);
 const generation=useRef(0),inFlight=useRef(false),cancelRef=useRef<HTMLButtonElement>(null),reviewRef=useRef<HTMLButtonElement>(null),restoreFocus=useRef(false);
 useEffect(()=>{generation.current++;inFlight.current=false;setFields(empty);setDays([]);setContext(null);setReview(null);setChecking(false);setError('');setSnapshot({client,tenantId,serviceId,state:client.offerSchedulingState(tenantId,serviceId)});return()=>{generation.current++;};},[client,tenantId,serviceId]);
 const state:OfferSchedulingState=snapshot.client===client&&snapshot.tenantId===tenantId&&snapshot.serviceId===serviceId?snapshot.state:{phase:'ready'},verified=context?.client===client&&context.tenantId===tenantId&&context.serviceId===serviceId?context.value:undefined,reviewed=review?.client===client&&review.tenantId===tenantId&&review.serviceId===serviceId?review:null;
 const pending=state.phase==='checking'||state.phase==='creating',locked=pending||state.phase==='unknown';
 useEffect(()=>{if(reviewed)cancelRef.current?.focus();else if(restoreFocus.current){restoreFocus.current=false;reviewRef.current?.focus();}},[reviewed]);
 function close(){restoreFocus.current=true;setReview(null);}
 function sync(){setSnapshot({client,tenantId,serviceId,state:client.offerSchedulingState(tenantId,serviceId)});onStateChange();}
 async function check(){if(inFlight.current||locked||contextBusy)return;const at=generation.current;inFlight.current=true;setChecking(true);setContext(null);setReview(null);setError('');try{const value=await client.simpleOfferContext(tenantId);if(at===generation.current)setContext({client,tenantId,serviceId,value});}catch(error){if(at===generation.current)setError(error instanceof BusinessOnboardingError?error.message:'Business scheduling context is unverified.');}finally{if(at===generation.current){inFlight.current=false;setChecking(false);}}}
 function prepare(event:FormEvent){event.preventDefault();if(!verified||locked||checking||contextBusy||state.phase==='configured')return;
  if(!/^[0-9]+$/.test(fields.lead)||!/^[0-9]+$/.test(fields.horizon)){setError('Use whole minutes for lead time and whole days for the horizon.');return;}
  const body=CreateOfferScheduling.safeParse({timezone:verified.timezone,windows:[...days].sort((a,b)=>a-b).map(weekday=>({weekday,startMinute:minute(fields.start),endMinute:minute(fields.end),capacity:1})),policy:{leadTimeMinutes:Number(fields.lead),horizonDays:Number(fields.horizon),slotIntervalMinutes:Number(fields.interval)},idempotencyKey:crypto.randomUUID()});
  if(!body.success||body.data.windows.some(window=>window.endMinute-window.startMinute<offer.service.durationMinutes)){setError('Select at least one weekday and a same-day window that fits the offer duration, lead time 0 to 10080 minutes, horizon 1 to 30 days and a 15, 30 or 60 minute interval.');return;}setError('');setReview({client,tenantId,serviceId,body:body.data});
 }
 async function send(body:CreateOfferScheduling){if(inFlight.current||pending||contextBusy)return;const at=generation.current;inFlight.current=true;setReview(null);setError('');const promise=client.createOfferScheduling(tenantId,serviceId,body);sync();try{await promise;if(at===generation.current)sync();}catch(error){if(at===generation.current){setError(error instanceof BusinessOnboardingError?error.message:'Scheduling outcome remains unverified. Check this session state.');sync();}}finally{if(at===generation.current)inFlight.current=false;}}
 return <section aria-label="Offer scheduling setup" style={{minWidth:0,overflowWrap:'anywhere'}}><h3>Configure offer scheduling</h3><p>Offer: {offer.service.name}; service ID: {serviceId}; duration: {offer.service.durationMinutes} minutes. Capacity is fixed at 1. This explicit create-only action does not publish a form, reserve a time or confirm a booking.</p><p>Scheduling requires an explicitly enabled staging server capability. No hours or policy are applied automatically. After a full reload, a lost attempt cannot be recovered here without its original key and settings; do not create a replacement attempt.</p>
 {state.phase==='ready'&&<><button type="button" disabled={checking||contextBusy} onClick={()=>void check()}>Verify scheduling owner and timezone</button>{checking&&<p role="status">Checking current scheduling owner, profile and timezone...</p>}{verified&&<form onSubmit={prepare}><fieldset className="form-stack" disabled={!!reviewed||contextBusy||checking} style={{minWidth:0}}><legend>Business-local scheduling</legend><p>Verified business timezone (read-only): {verified.timezone}. Common hours apply to each selected weekday. Overnight windows are not supported.</p><fieldset><legend>Weekdays</legend>{weekdays.map((label,weekday)=><label key={label}><input type="checkbox" checked={days.includes(weekday)} onChange={event=>setDays(event.target.checked?[...days,weekday]:days.filter(day=>day!==weekday))}/>{label}</label>)}</fieldset><label>Common start time<input required type="time" step="60" value={fields.start} onChange={event=>setFields({...fields,start:event.target.value})}/></label><label>Common end time<input required type="time" step="60" value={fields.end} onChange={event=>setFields({...fields,end:event.target.value})}/></label><p>Capacity per window: 1 (fixed).</p><label>Lead time in minutes<input required inputMode="numeric" pattern="[0-9]+" value={fields.lead} onChange={event=>setFields({...fields,lead:event.target.value})}/></label><label>Booking horizon in days<input required inputMode="numeric" pattern="[0-9]+" value={fields.horizon} onChange={event=>setFields({...fields,horizon:event.target.value})}/></label><label>Slot interval in minutes<select required value={fields.interval} onChange={event=>setFields({...fields,interval:event.target.value})}><option value="">Choose interval</option>{[15,30,60].map(interval=><option key={interval} value={interval}>{interval}</option>)}</select></label><button ref={reviewRef} type="submit">Review offer scheduling</button></fieldset></form>}</>}
 {reviewed&&<div role="dialog" aria-label="Review offer scheduling" onKeyDown={event=>{if(event.key==='Escape'){event.preventDefault();close();}}}><h4>Review business-local hours and policy</h4><p>Business: {tenantId}; offer: {serviceId}; timezone: {reviewed.body.timezone}. Capacity: 1.</p><ul>{reviewed.body.windows.map(window=><li key={window.weekday}>{weekdays[window.weekday]}: {time(window.startMinute)} to {time(window.endMinute)}</li>)}</ul><p>Lead time: {reviewed.body.policy.leadTimeMinutes} minutes; horizon: {reviewed.body.policy.horizonDays} days; slot interval: {reviewed.body.policy.slotIntervalMinutes} minutes.</p><p>Confirming writes these scheduling settings. Available slots still depend on server rules and current capacity. This does not publish or confirm a booking.</p><button ref={cancelRef} type="button" onClick={close}>Cancel scheduling setup</button><button type="button" disabled={contextBusy||locked} onClick={()=>void send(reviewed.body)}>Confirm configure offer scheduling</button></div>}
 {pending&&<p role="status">Checking or configuring the reviewed scheduling...</p>}{(pending||state.phase==='unknown')&&<button type="button" onClick={sync}>Check this session's scheduling state</button>}
 {state.phase==='unknown'&&<><p role="alert">Scheduling creation is unverified. Account, business, offer, key and settings remain frozen. Do not start a different attempt.</p><p>Frozen timezone: {state.attempt.timezone}; key: {state.attempt.idempotencyKey}; lead: {state.attempt.policy.leadTimeMinutes} minutes; horizon: {state.attempt.policy.horizonDays} days; interval: {state.attempt.policy.slotIntervalMinutes} minutes.</p><ul>{state.attempt.windows.map(window=><li key={window.weekday}>{weekdays[window.weekday]}: {time(window.startMinute)} to {time(window.endMinute)}; capacity 1</li>)}</ul><button type="button" disabled={contextBusy} onClick={()=>void send(state.attempt)}>Retry this same scheduling setup</button></>}
 {state.phase==='configured'&&<><p role="status">Server scheduling receipt verified. Scheduling is configured for service {state.receipt.serviceId} in {state.receipt.timezone}. Policy ID: {state.receipt.policy.id}.</p><ul>{state.receipt.windows.map(window=><li key={window.id}>{weekdays[window.weekday]}: {time(window.startMinute)} to {time(window.endMinute)}; capacity 1; rule ID: {window.id}</li>)}</ul><p>Verified policy: lead {state.receipt.policy.leadTimeMinutes} minutes; horizon {state.receipt.policy.horizonDays} days; interval {state.receipt.policy.slotIntervalMinutes} minutes. This receipt does not publish a form, guarantee a slot or confirm a booking.</p></>}{error&&<p role="alert">{error}</p>}</section>;
}
