import {afterEach,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen} from '@testing-library/react';
import {useState} from 'react';
import type {CustomerDraftTextField} from '@lumin/runtime-client';
import {ConnectedCustomerDraftFields} from './ConnectedCustomerDraftFields';
afterEach(cleanup);
const first:CustomerDraftTextField={id:'custom_notes',kind:'text',label:'Access notes',required:false,maxLength:500};
function Fields({initial=[]}:{initial?:CustomerDraftTextField[]}){const [fields,setFields]=useState(initial);return <ConnectedCustomerDraftFields fields={fields} disabled={false} onChange={setFields}/>;}
it('adds text metadata without submitting, exposes native keyboard controls, and preserves ordered IDs on move/remove',()=>{const submit=vi.fn();render(<form onSubmit={event=>{event.preventDefault();submit();}}><Fields initial={[first]}/></form>);const add=screen.getByRole('button',{name:'Add text field'});add.focus();expect(add).toHaveFocus();expect(add).toHaveAttribute('type','button');fireEvent.click(add);fireEvent.change(screen.getByRole('textbox',{name:'Field 2 label'}),{target:{value:'Room location'}});fireEvent.click(screen.getByRole('checkbox',{name:'Field 2 required'}));fireEvent.change(screen.getByRole('spinbutton',{name:'Field 2 maximum length'}),{target:{value:'100'}});fireEvent.click(screen.getByRole('button',{name:'Move field 2 up'}));expect(screen.getByRole('textbox',{name:'Field 1 label'})).toHaveValue('Room location');expect(screen.getByRole('textbox',{name:'Field 1 ID'})).toHaveValue('custom_field_1');expect(screen.getByRole('checkbox',{name:'Field 1 required'})).toBeChecked();expect(screen.getByRole('spinbutton',{name:'Field 1 maximum length'})).toHaveValue(100);expect(screen.getByRole('button',{name:'Move field 1 up'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'Remove field 1'}));expect(screen.getByRole('textbox',{name:'Field 1 ID'})).toHaveValue('custom_notes');expect(submit).not.toHaveBeenCalled();});
it('bounds count to ten, avoids generated ID collisions, and validates labels/length without truncation',()=>{render(<Fields initial={Array.from({length:10},(_,index)=>({...first,id:'custom_field_'+(index+1) }))}/>);expect(screen.getByRole('button',{name:'Add text field'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'Remove field 1'}));fireEvent.click(screen.getByRole('button',{name:'Add text field'}));expect(screen.getByRole('textbox',{name:'Field 10 ID'})).toHaveValue('custom_field_1');expect(screen.getByRole('alert')).toHaveTextContent('Check informational fields');fireEvent.change(screen.getByRole('textbox',{name:'Field 10 label'}),{target:{value:'Good label'}});expect(screen.queryByRole('alert')).toBeNull();fireEvent.change(screen.getByRole('spinbutton',{name:'Field 10 maximum length'}),{target:{value:'1.5'}});expect(screen.getByRole('alert')).toBeVisible();fireEvent.change(screen.getByRole('spinbutton',{name:'Field 10 maximum length'}),{target:{value:'1001'}});expect(screen.getByRole('alert')).toBeVisible();fireEvent.change(screen.getByRole('spinbutton',{name:'Field 10 maximum length'}),{target:{value:'1000'}});expect(screen.queryByRole('alert')).toBeNull();fireEvent.change(screen.getByRole('textbox',{name:'Field 10 label'}),{target:{value:' space '}});expect(screen.getByRole('alert')).toBeVisible();});
it('keeps unknown/pending editing locks and constrains fields/buttons inside a narrow container',()=>{const onChange=vi.fn();render(<div style={{width:320}}><ConnectedCustomerDraftFields fields={[first]} disabled onChange={onChange}/></div>);for(const control of screen.getAllByRole('button'))expect(control).toBeDisabled();expect(screen.getByRole('textbox',{name:'Field 1 ID'})).toHaveAttribute('readonly');fireEvent.click(screen.getByRole('button',{name:'Remove field 1'}));fireEvent.change(screen.getByRole('textbox',{name:'Field 1 label'}),{target:{value:'Changed'}});expect(onChange).not.toHaveBeenCalled();expect(screen.getByRole('region',{name:'Informational customer text fields'})).toHaveStyle({minWidth:'0',maxWidth:'100%'});expect(screen.getByRole('button',{name:'Remove field 1'}).parentElement).toHaveStyle({flexWrap:'wrap'});});
