import {afterEach,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {MemoryRouter} from 'react-router-dom';
import {ConnectedPortal} from './ConnectedPortal';
const tenant='11111111-1111-4111-8111-111111111111',user='22222222-2222-4222-8222-222222222222',service='33333333-3333-4333-8333-333333333333';
const config={url:'https://example.supabase.co',publishableKey:'sb_publishable_synthetic',tenantId:'',bookingApiOrigin:'https://api.example.test'};
const json=(value:unknown)=>new Response(JSON.stringify(value));
afterEach(()=>{cleanup();vi.unstubAllGlobals();});
function setup(role:string,publish:()=>Promise<Response>){
 const fetcher=vi.fn(async(input:RequestInfo|URL,_options?:RequestInit)=>{const url=String(input);if(url.includes('/auth/v1/token'))return json({access_token:'synthetic-owner-private-token'});if(url.includes('/auth/v1/user'))return json({id:user});if(url.includes('/tenant_members'))return json([{tenant_id:tenant,role}]);if(url.includes('/services?'))return json([{id:service,tenant_id:tenant,name:'Housekeeping',currency:'USD',duration_minutes:60,base_price:12500,active:true}]);if(url.includes('/bookings?'))return json([]);if(url.includes('/publish?'))return publish();throw Error('unexpected');});
 vi.stubGlobal('fetch',fetcher);render(<MemoryRouter initialEntries={['/embed']}><ConnectedPortal config={config} staging/></MemoryRouter>);return fetcher;
}
async function login(){fireEvent.change(screen.getByLabelText('Email'),{target:{value:'owner@example.test'}});fireEvent.change(screen.getByLabelText('Password'),{target:{value:'fixture-only'}});fireEvent.click(screen.getByText('Sign in'));await screen.findByText('Sign out');}
it('connects canonical /embed publication to the closure-held signed-in owner token',async()=>{
 const fetcher=setup('BUSINESS_OWNER',async()=>json({ok:true,data:{versionId:user,installationId:service,renderSchemaVersion:3,hostedPath:'/checkout/flow/'+service}}));await login();await screen.findByText('Publish staging test form');fireEvent.change(screen.getByLabelText('Simple service'),{target:{value:service}});fireEvent.change(screen.getByLabelText('Form name'),{target:{value:'Owner test booking'}});fireEvent.click(screen.getByText('Publish staging test form'));await screen.findByText('Staging form published');const call=fetcher.mock.calls.find(([url])=>String(url).includes('/publish?'));expect(call).toBeDefined();expect(call?.[1]?.headers).toMatchObject({Authorization:'Bearer synthetic-owner-private-token'});expect(document.body.textContent).not.toContain('synthetic-owner-private-token');expect(screen.queryByText('This section is not available yet.')).toBeNull();
});
it('keeps staff out of publication and clears pending publication on sign-out',async()=>{
 const staff=setup('BUSINESS_STAFF',async()=>{throw Error('unexpected');});await login();await screen.findByText('Only a business owner can publish a staging paid form.');expect(staff.mock.calls.some(([url])=>String(url).includes('/publish?'))).toBe(false);cleanup();let resolve!:(response:Response)=>void;setup('BUSINESS_OWNER',()=>new Promise<Response>(r=>resolve=r));await login();await screen.findByText('Publish staging test form');fireEvent.change(screen.getByLabelText('Simple service'),{target:{value:service}});fireEvent.change(screen.getByLabelText('Form name'),{target:{value:'Owner test booking'}});fireEvent.click(screen.getByText('Publish staging test form'));await waitFor(()=>expect(resolve).toBeTypeOf('function'));fireEvent.click(screen.getByText('Sign out'));resolve(json({ok:true,data:{versionId:user,installationId:service,renderSchemaVersion:3,hostedPath:'/checkout/flow/'+service}}));await screen.findByText('Sign in to your business');expect(screen.queryByText('Staging form published')).toBeNull();expect(screen.queryByRole('link',{name:'Open staging booking form'})).toBeNull();
});

function businessSetup(memberAfterCreate:'owner'|'staff'|'missing'='owner'){
 let created=false;const business='44444444-4444-4444-8444-444444444444';
 const fetcher=vi.fn<typeof fetch>(async(input)=>{const url=String(input);if(url.includes('/auth/v1/token'))return json({access_token:'synthetic-owner-private-token'});if(url.includes('/auth/v1/user'))return json({id:user});if(url.includes('/tenant_members'))return json([{tenant_id:tenant,role:'BUSINESS_OWNER'},...(created&&memberAfterCreate!=='missing'?[{tenant_id:business,role:memberAfterCreate==='owner'?'BUSINESS_OWNER':'BUSINESS_STAFF'}]:[])]);if(url.includes('/services?'))return json([]);if(url.includes('/bookings?'))return json([]);if(url.endsWith('/api/businesses')){created=true;return json({ok:true,data:{schemaVersion:1,tenantId:business,businessType:'HOUSEKEEPING',templateVersion:1}});}throw Error('unexpected');});vi.stubGlobal('fetch',fetcher);render(<MemoryRouter initialEntries={['/embed']}><ConnectedPortal config={config} staging/></MemoryRouter>);return{fetcher,business};
}
async function createBusinessReview(){fireEvent.click(screen.getByRole('button',{name:'Create a new staging business'}));for(const [label,value] of [['New business name','Separate test business'],['New business slug','separate-test-business'],['New business timezone','UTC'],['New business currency','USD'],['Permanent business type','HOUSEKEEPING']] as const)fireEvent.change(screen.getByLabelText(label),{target:{value}});fireEvent.click(screen.getByRole('button',{name:'Review new business'}));fireEvent.click(screen.getByRole('button',{name:'Confirm create staging business'}));await screen.findByText(/Server creation receipt verified/);}
it('keeps the old business selected after creation and selects the exact new tenant only after fresh owner membership verification',async()=>{
 const {fetcher,business}=businessSetup();await login();await screen.findByRole('button',{name:'Create a new staging business'});await createBusinessReview();expect(screen.getByLabelText('Business')).toHaveValue(tenant);fireEvent.click(screen.getByRole('button',{name:'Open created business'}));await waitFor(()=>expect(screen.getByLabelText('Business')).toHaveValue(business));const reads=fetcher.mock.calls.filter(([url])=>String(url).includes('/tenant_members'));expect(reads).toHaveLength(3);expect(fetcher.mock.calls.some(([url])=>String(url).includes('/bookings?')&&String(url).includes('tenant_id=eq.'+business))).toBe(true);expect(document.body.textContent).not.toContain('synthetic-owner-private-token');
});
it.each(['staff','missing'] as const)('retains creation receipt and old context if fresh created-tenant owner membership is %s',async(role)=>{
 businessSetup(role);await login();await createBusinessReview();fireEvent.click(screen.getByRole('button',{name:'Open created business'}));await screen.findByText(/created business owner membership could not be verified/);expect(screen.getByLabelText('Business')).toHaveValue(tenant);expect(screen.getByText(/Server creation receipt verified/)).toBeTruthy();expect(screen.getByRole('button',{name:'Open created business'})).toBeEnabled();
});
it('keeps a pending creation from changing selected business and drops its late receipt after sign-out',async()=>{
 let finish!:(response:Response)=>void;const fetcher=vi.fn<typeof fetch>(async input=>{const url=String(input);if(url.includes('/auth/v1/token'))return json({access_token:'synthetic-owner-private-token'});if(url.includes('/auth/v1/user'))return json({id:user});if(url.includes('/tenant_members'))return json([{tenant_id:tenant,role:'BUSINESS_OWNER'}]);if(url.includes('/services?')||url.includes('/bookings?'))return json([]);return new Promise(r=>finish=r);});vi.stubGlobal('fetch',fetcher);render(<MemoryRouter initialEntries={['/embed']}><ConnectedPortal config={config} staging/></MemoryRouter>);await login();fireEvent.click(screen.getByRole('button',{name:'Create a new staging business'}));for(const [label,value] of [['New business name','Separate test'],['New business slug','separate-test'],['New business timezone','UTC'],['New business currency','USD'],['Permanent business type','HOUSEKEEPING']] as const)fireEvent.change(screen.getByLabelText(label),{target:{value}});fireEvent.click(screen.getByRole('button',{name:'Review new business'}));fireEvent.click(screen.getByRole('button',{name:'Confirm create staging business'}));await waitFor(()=>expect(finish).toBeTypeOf('function'));expect(screen.getByLabelText('Business')).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'Sign out'}));finish(json({ok:true,data:{schemaVersion:1,tenantId:service,businessType:'HOUSEKEEPING',templateVersion:1}}));await screen.findByText('Sign in to your business');expect(screen.queryByText(/Server creation receipt verified/)).toBeNull();expect(screen.queryByRole('button',{name:'Open created business'})).toBeNull();
});

it('does not overwrite a newer business selection with a late created-owner membership read',async()=>{
 const next='44444444-4444-4444-8444-444444444444',business='55555555-5555-4555-8555-555555555555';let membershipReads=0,finish!:(response:Response)=>void;
 const memberships=[{tenant_id:tenant,role:'BUSINESS_OWNER'},{tenant_id:next,role:'BUSINESS_OWNER'}];const fetcher=vi.fn<typeof fetch>(async input=>{const url=String(input);if(url.includes('/auth/v1/token'))return json({access_token:'synthetic-owner-private-token'});if(url.includes('/auth/v1/user'))return json({id:user});if(url.includes('/tenant_members')){membershipReads++;return membershipReads===3?new Promise(r=>finish=r):json(memberships);}if(url.includes('/services?')||url.includes('/bookings?'))return json([]);if(url.endsWith('/api/businesses'))return json({ok:true,data:{schemaVersion:1,tenantId:business,businessType:'HOUSEKEEPING',templateVersion:1}});throw Error('unexpected');});vi.stubGlobal('fetch',fetcher);render(<MemoryRouter initialEntries={['/embed']}><ConnectedPortal config={config} staging/></MemoryRouter>);await login();await createBusinessReview();fireEvent.click(screen.getByRole('button',{name:'Open created business'}));await waitFor(()=>expect(finish).toBeTypeOf('function'));fireEvent.change(screen.getByLabelText('Business'),{target:{value:next}});await waitFor(()=>expect(screen.getByLabelText('Business')).toHaveValue(next));finish(json([...memberships,{tenant_id:business,role:'BUSINESS_OWNER'}]));await waitFor(()=>expect(membershipReads).toBe(3));expect(screen.getByLabelText('Business')).toHaveValue(next);expect(screen.getByText(/Server creation receipt verified/)).toHaveTextContent(business);
});

it('lets a freshly authenticated zero-membership account create its first business and opens it only after exact fresh owner verification',async()=>{
 const business='66666666-6666-4666-8666-666666666666';let created=false;const fetcher=vi.fn<typeof fetch>(async input=>{const url=String(input);if(url.includes('/auth/v1/token'))return json({access_token:'fresh-account-private-token'});if(url.includes('/auth/v1/user'))return json({id:user});if(url.includes('/tenant_members'))return json(created?[{tenant_id:business,role:'BUSINESS_OWNER'}]:[]);if(url.endsWith('/api/businesses')){created=true;return json({ok:true,data:{schemaVersion:1,tenantId:business,businessType:'HOUSEKEEPING',templateVersion:1}});}if(url.includes('/services?')||url.includes('/bookings?'))return json([]);throw Error('unexpected');});vi.stubGlobal('fetch',fetcher);render(<MemoryRouter initialEntries={['/embed']}><ConnectedPortal config={config} staging/></MemoryRouter>);await login();expect(screen.getByText('No business membership is assigned to this account.')).toBeTruthy();expect(screen.queryByLabelText('Business')).toBeNull();expect(screen.getByText(/verified membership lookup returned no assigned businesses/)).toBeTruthy();expect(fetcher.mock.calls.some(([url])=>String(url).includes('/bookings?'))).toBe(false);await createBusinessReview();expect(screen.queryByLabelText('Business')).toBeNull();expect(fetcher.mock.calls.some(([url])=>String(url).includes('/bookings?'))).toBe(false);fireEvent.click(screen.getByRole('button',{name:'Open created business'}));await waitFor(()=>expect(screen.getByLabelText('Business')).toHaveValue(business));expect(fetcher.mock.calls.filter(([url])=>String(url).includes('/tenant_members'))).toHaveLength(3);expect(fetcher.mock.calls.filter(([url])=>String(url).endsWith('/api/businesses'))).toHaveLength(1);expect(fetcher.mock.calls.some(([url])=>String(url).includes('/bookings?')&&String(url).includes('tenant_id=eq.'+business))).toBe(true);expect(document.body.textContent).not.toContain('fresh-account-private-token');
});
it.each(['failed','foreign','staff','worker'])('does not enter zero-membership onboarding after a %s membership result',async(kind)=>{
 const fetcher=vi.fn<typeof fetch>(async input=>{const url=String(input);if(url.includes('/auth/v1/token'))return json({access_token:'fresh-account-private-token'});if(url.includes('/auth/v1/user'))return json({id:user});if(url.includes('/tenant_members'))return kind==='failed'?new Response(JSON.stringify({error:'private'}),{status:403}):json(kind==='foreign'?[{tenant_id:tenant,role:'BUSINESS_OWNER',user_id:service}]:[{tenant_id:tenant,role:kind==='staff'?'BUSINESS_STAFF':'WORKER'}]);if(url.includes('/services?')||url.includes('/bookings?'))return json([]);throw Error('unexpected');});vi.stubGlobal('fetch',fetcher);render(<MemoryRouter initialEntries={['/embed']}><ConnectedPortal config={config} staging/></MemoryRouter>);fireEvent.change(screen.getByLabelText('Email'),{target:{value:'existing-account@example.test'}});fireEvent.change(screen.getByLabelText('Password'),{target:{value:'fixture'}});fireEvent.click(screen.getByRole('button',{name:'Sign in'}));if(kind==='failed'||kind==='foreign')await screen.findByRole('alert');else await screen.findByRole('button',{name:'Sign out'});expect(screen.queryByRole('button',{name:'Create a new staging business'})).toBeNull();expect(screen.queryByText(/verified membership lookup returned no assigned businesses/)).toBeNull();expect(fetcher.mock.calls.some(([url])=>String(url).endsWith('/api/businesses'))).toBe(false);
});
it('keeps a first-business receipt without context selection if fresh created-tenant membership is still missing',async()=>{
 let created=false;const fetcher=vi.fn<typeof fetch>(async input=>{const url=String(input);if(url.includes('/auth/v1/token'))return json({access_token:'fresh-account-private-token'});if(url.includes('/auth/v1/user'))return json({id:user});if(url.includes('/tenant_members'))return json([]);if(url.endsWith('/api/businesses')){created=true;return json({ok:true,data:{schemaVersion:1,tenantId:service,businessType:'HOUSEKEEPING',templateVersion:1}});}throw Error('unexpected');});vi.stubGlobal('fetch',fetcher);render(<MemoryRouter initialEntries={['/embed']}><ConnectedPortal config={config} staging/></MemoryRouter>);await login();await createBusinessReview();fireEvent.click(screen.getByRole('button',{name:'Open created business'}));await screen.findByText(/created business owner membership could not be verified/);expect(created).toBe(true);expect(screen.queryByLabelText('Business')).toBeNull();expect(screen.getByText(/Server creation receipt verified/)).toHaveTextContent(service);expect(screen.getByRole('button',{name:'Open created business'})).toBeEnabled();
});
