import {useEffect,useId,useRef,useState,type ReactNode,type KeyboardEvent} from 'react';
export const BOOKING_FORM_AREAS=['Build','Design','Preview','Publish','Install & Health'] as const;
export type BookingFormArea=typeof BOOKING_FORM_AREAS[number];
type Props={client:unknown;tenantId:string;panels:Record<BookingFormArea,ReactNode>;status:(select:(area:BookingFormArea)=>void)=>ReactNode;initialArea?:BookingFormArea};
export function ConnectedBookingFormWorkspace({client,tenantId,panels,status,initialArea='Build'}:Props){
 const id=useId(),refs=useRef<(HTMLButtonElement|null)[]>([]),[snapshot,setSnapshot]=useState({client,tenantId,active:initialArea,focused:initialArea});
 const scoped=snapshot.client===client&&snapshot.tenantId===tenantId?snapshot:{client,tenantId,active:initialArea,focused:initialArea};
 useEffect(()=>{setSnapshot({client,tenantId,active:initialArea,focused:initialArea});},[client,tenantId]);
 function select(area:BookingFormArea){setSnapshot({client,tenantId,active:area,focused:area});refs.current[BOOKING_FORM_AREAS.indexOf(area)]?.focus();}
 function key(event:KeyboardEvent<HTMLButtonElement>,index:number){let next:number|undefined;if(event.key==='ArrowRight')next=(index+1)%BOOKING_FORM_AREAS.length;else if(event.key==='ArrowLeft')next=(index+BOOKING_FORM_AREAS.length-1)%BOOKING_FORM_AREAS.length;else if(event.key==='Home')next=0;else if(event.key==='End')next=BOOKING_FORM_AREAS.length-1;else if(event.key==='Enter'||event.key===' '){event.preventDefault();select(BOOKING_FORM_AREAS[index]!);return;}if(next!==undefined){event.preventDefault();setSnapshot({...scoped,focused:BOOKING_FORM_AREAS[next]!});refs.current[next]?.focus();}}
 return <div style={{minWidth:0,maxWidth:'100%',overflowWrap:'anywhere'}}><div role="tablist" aria-label="Booking Form workspace" style={{display:'flex',flexWrap:'wrap',gap:8,maxWidth:'100%',minWidth:0}}>{BOOKING_FORM_AREAS.map((area,index)=><button key={area} ref={node=>{refs.current[index]=node;}} type="button" role="tab" id={id+'-tab-'+index} aria-controls={id+'-panel-'+index} aria-selected={scoped.active===area} tabIndex={scoped.focused===area?0:-1} onFocus={()=>setSnapshot(previous=>({...(previous.client===client&&previous.tenantId===tenantId?previous:scoped),focused:area}))} onKeyDown={event=>key(event,index)} onClick={()=>select(area)} style={{maxWidth:'100%',whiteSpace:'normal',fontWeight:scoped.active===area?700:400,textDecoration:scoped.active===area?'underline':'none'}}>{area}</button>)}</div><div aria-label="Booking Form action status">{status(select)}</div>{BOOKING_FORM_AREAS.map((area,index)=><div key={area} role="tabpanel" id={id+'-panel-'+index} aria-labelledby={id+'-tab-'+index} hidden={scoped.active!==area} tabIndex={0} style={{display:scoped.active===area?'block':'none',minWidth:0,maxWidth:'100%'}}>{panels[area]}</div>)}</div>;
}
