import {useEffect,useId,useRef,useState,type FormEvent,type KeyboardEvent} from 'react';
import {CustomerDraftFields,ConditionalCustomerFields} from '@lumin/contracts';
import {PAID_SIMPLE_ACCENT_COLORS,PublicationError,type ConditionalInstallReceipt,type ConditionalVersionHistory,type RuntimeClient} from '@lumin/runtime-client';

type Client=Pick<RuntimeClient,'conditionalVersionHistory'|'rollbackConditionalPublication'|'reconcileConditionalRollback'|'conditionalRollbackState'>&Partial<Pick<RuntimeClient,'authContextRevision'>>;
export type ConnectedConditionalVersionHistoryProps={client:Client;tenantId:string;blocked:boolean;onStateChange:()=>void;onVerifiedHistory?:(history:ConditionalVersionHistory,authRevision:number)=>void;onViewCurrentInstallation?:(history:ConditionalVersionHistory,authRevision:number)=>void;currentInstallationBlocked?:boolean;onHistoryInvalidated?:()=>void};
type View={client:Client;tenantId:string;auth:number;flowId:string;phase:'idle'|'loading'|'loaded'|'failed';history?:ConditionalVersionHistory;error:string};
type Review={client:Client;tenantId:string;auth:number;flowId:string;currentVersionId:string;targetVersionId:string;targetName:string;targetRevision:number;targetPublication:ConditionalInstallReceipt};
const checkoutOrigin='https://booking-lumin-checkout-staging.netlify.app';
const uuid=(v:unknown):v is string=>typeof v==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/.test(v);
const exact=(v:unknown,keys:string[]):v is Record<string,unknown>=>!!v&&typeof v==='object'&&!Array.isArray(v)&&Object.keys(v).length===keys.length&&keys.every(key=>Object.hasOwn(v,key));
function safeReceipt(value:unknown):value is ConditionalInstallReceipt{return exact(value,['versionId','installationId','renderSchemaVersion','hostedPath'])&&uuid(value.versionId)&&uuid(value.installationId)&&(value.renderSchemaVersion===3||value.renderSchemaVersion===5||value.renderSchemaVersion===6)&&value.hostedPath==='/checkout/flow/'+value.installationId;}
function safeHistory(value:unknown,flowId:string):value is ConditionalVersionHistory{
 if(!exact(value,['flowId','versions'])||value.flowId!==flowId||!Array.isArray(value.versions)||value.versions.length<1||value.versions.length>50)return false;
 let previous=Infinity,current=0,hasConditional=false;const ids=new Set<string>(),installs=new Set<string>();
 for(const v of value.versions){
  if(!exact(v,['versionId','renderSchemaVersion','draftRevision','name','presentation','current','publication',...((v?.renderSchemaVersion===5||v?.renderSchemaVersion===6)?['customerFields']:[])])||!uuid(v.versionId)||ids.has(v.versionId)||!Number.isSafeInteger(v.draftRevision)||Number(v.draftRevision)<1||Number(v.draftRevision)>=previous||typeof v.name!=='string'||v.name.length<1||v.name.length>200||!exact(v.presentation,['accentColor','layout'])||!(PAID_SIMPLE_ACCENT_COLORS as readonly unknown[]).includes(v.presentation.accentColor)||(v.presentation.layout!=='compact'&&v.presentation.layout!=='stacked')||typeof v.current!=='boolean'||(v.renderSchemaVersion!==3&&v.renderSchemaVersion!==5&&v.renderSchemaVersion!==6))return false;
  if(v.publication!==null&&(!safeReceipt(v.publication)||v.publication.versionId!==v.versionId||v.publication.renderSchemaVersion!==v.renderSchemaVersion||installs.has(v.publication.installationId)))return false;
  if(v.publication)installs.add(v.publication.installationId);if(v.renderSchemaVersion===5&&!CustomerDraftFields.safeParse(v.customerFields).success)return false;if(v.renderSchemaVersion===6){if(!ConditionalCustomerFields.safeParse(v.customerFields).success)return false;hasConditional=true;}
  ids.add(v.versionId);previous=Number(v.draftRevision);if(v.current)current++;
 }
 return current===1&&hasConditional;
}
export function ConnectedConditionalVersionHistory(props:ConnectedConditionalVersionHistoryProps){
 if(!uuid(props.tenantId.toLowerCase()))return <section aria-label="Conditional publication history"><p role="alert">Choose a verified business before checking publication history.</p></section>;
 return <HistoryPanel {...props} tenantId={props.tenantId.toLowerCase()}/>;
}
function HistoryPanel({client,tenantId,blocked,onStateChange,onVerifiedHistory,onViewCurrentInstallation,currentInstallationBlocked,onHistoryInvalidated}:ConnectedConditionalVersionHistoryProps){
 const auth=client.authContextRevision?.()??0;
 const initial=():View=>({client,tenantId,auth,flowId:'',phase:'idle',error:''}),[snapshot,setSnapshot]=useState<View>(initial),[selected,setSelected]=useState(''),[reviewSnapshot,setReview]=useState<Review|null>(null),[checking,setChecking]=useState(false),[,setTick]=useState(0);
 const generation=useRef(0),inFlight=useRef(false),context=useRef({client,tenantId,auth}),reviewButton=useRef<HTMLButtonElement>(null),refreshButton=useRef<HTMLButtonElement>(null),cancelButton=useRef<HTMLButtonElement>(null),confirmButton=useRef<HTMLButtonElement>(null),titleId=useId();context.current={client,tenantId,auth};
 useEffect(()=>{generation.current++;inFlight.current=false;setSnapshot(initial());setSelected('');setReview(null);setChecking(false);return()=>{generation.current++;};},[client,tenantId,auth]);
 useEffect(()=>{if(blocked)onHistoryInvalidated?.();},[blocked]);
 const view=snapshot.client===client&&snapshot.tenantId===tenantId&&snapshot.auth===auth?snapshot:initial(),review=reviewSnapshot?.client===client&&reviewSnapshot.tenantId===tenantId&&reviewSnapshot.auth===auth?reviewSnapshot:null;
 useEffect(()=>{if(review)cancelButton.current?.focus();},[review]);
 const rollback=client.conditionalRollbackState(tenantId),locked=rollback.phase==='rolling_back'||rollback.phase==='unknown',current=view.history?.versions.find(v=>v.current),targets=view.history?.versions.filter(v=>!v.current&&v.publication&&current&&v.draftRevision<current.draftRevision)??[];
 const active=(at:number)=>at===generation.current&&context.current.client===client&&context.current.tenantId===tenantId&&context.current.auth===auth&&(client.authContextRevision?.()??0)===auth;
 const notify=()=>{setTick(n=>n+1);onStateChange();};
 function edit(value:string){if(locked||inFlight.current)return;onHistoryInvalidated?.();generation.current++;setSelected('');setReview(null);setSnapshot({client,tenantId,auth,flowId:value,phase:'idle',error:''});}
 async function refresh(event:FormEvent){
  event.preventDefault();if(inFlight.current||rollback.phase==='rolling_back')return;const flowId=(locked?rollback.flowId:view.flowId).trim().toLowerCase();if(!uuid(flowId)){setSnapshot({...view,error:'Enter the known form ID for this business.'});return;}
  onHistoryInvalidated?.();const at=++generation.current;inFlight.current=true;setSelected('');setReview(null);setSnapshot({client,tenantId,auth,flowId,phase:'loading',error:''});
  try{const history=await client.conditionalVersionHistory(tenantId,flowId);if(!safeHistory(history,flowId))throw new PublicationError('not_sent','Publication history could not be validated. No installation or rollback authority was granted.');if(active(at)){setSnapshot({client,tenantId,auth,flowId,phase:'loaded',history,error:''});onVerifiedHistory?.(history,auth);}}
  catch(error){if(active(at))setSnapshot({client,tenantId,auth,flowId,phase:'failed',error:error instanceof PublicationError?error.message:'Publication history could not be checked. An uncertain action remains locked.'});}
  finally{if(active(at))inFlight.current=false;}
 }
 function viewCurrentInstallation(){if(blocked||currentInstallationBlocked||locked||inFlight.current||view.phase!=='loaded'||!view.history||!safeHistory(view.history,view.flowId)||(client.authContextRevision?.()??0)!==auth||current?.renderSchemaVersion!==6||current.publication?.renderSchemaVersion!==6)return;onViewCurrentInstallation?.(view.history,auth);}
 function closeReview(){setReview(null);(reviewButton.current&&!reviewButton.current.disabled?reviewButton.current:refreshButton.current)?.focus();}
 function reviewTarget(){if((client.authContextRevision?.()??0)!==auth||blocked||locked||inFlight.current||!current?.publication||!view.history)return;const target=targets.find(v=>v.versionId===selected);if(!target?.publication)return;setReview({client,tenantId,auth,flowId:view.history.flowId,currentVersionId:current.versionId,targetVersionId:target.versionId,targetName:target.name,targetRevision:target.draftRevision,targetPublication:{...target.publication}});}
 function trap(event:KeyboardEvent){if(event.key==='Escape'){event.preventDefault();closeReview();}else if(event.key==='Tab'){event.preventDefault();const focus=document.activeElement;const next=event.shiftKey?(focus===cancelButton.current?confirmButton.current:cancelButton.current):(focus===confirmButton.current?cancelButton.current:confirmButton.current);(next?.disabled?cancelButton.current:next)?.focus();}}
 async function confirm(){
  if((client.authContextRevision?.()??0)!==auth||!review||blocked||locked||inFlight.current)return;const at=generation.current,reviewed=review;inFlight.current=true;setReview(null);setSelected('');setSnapshot({...view,history:undefined,error:''});
  onHistoryInvalidated?.();const pending=client.rollbackConditionalPublication(tenantId,reviewed.flowId,{expectedCurrentVersionId:reviewed.currentVersionId,targetVersionId:reviewed.targetVersionId});notify();
  try{await pending;if(active(at)){setSnapshot({...view,history:undefined,error:''});notify();}}
  catch(error){if(active(at)){setSnapshot({...view,history:undefined,error:error instanceof PublicationError?error.message:'Rollback outcome is unverified. Check its frozen target receipt without repeating rollback.'});notify();}}
  finally{if(active(at))inFlight.current=false;}
 }
 async function reconcile(){
  if((client.authContextRevision?.()??0)!==auth||inFlight.current||checking||rollback.phase!=='unknown')return;onHistoryInvalidated?.();const at=generation.current;inFlight.current=true;setChecking(true);setSnapshot({...view,error:''});
  try{await client.reconcileConditionalRollback(tenantId);if(active(at)){setSnapshot({...view,history:undefined,error:''});notify();}}
  catch(error){if(active(at))setSnapshot({...view,error:error instanceof PublicationError?error.message:'The rollback receipt could not be verified. The frozen target remains locked.'});}
  finally{if(active(at)){inFlight.current=false;setChecking(false);}}
 }
 const verified=rollback.phase==='verified'&&exact(rollback.receipt,['flowId','versionId','installationId','renderSchemaVersion','hostedPath'])&&uuid(rollback.flowId)&&rollback.receipt.flowId===rollback.flowId&&safeReceipt({versionId:rollback.receipt.versionId,installationId:rollback.receipt.installationId,renderSchemaVersion:rollback.receipt.renderSchemaVersion,hostedPath:rollback.receipt.hostedPath})?rollback:null;
 return <section aria-label="Conditional publication history" style={{minWidth:0,maxWidth:'100%',overflowWrap:'anywhere'}}>
  <div aria-hidden={review?true:undefined}>
   <h2>Conditional published form history</h2><p>Check the immutable names, designs and informational field definitions published for a known form. This read does not verify an uncertain save, publication or rollback. Links open the staging customer form.</p>
   <form onSubmit={refresh}><label>Conditional publication history form ID<input value={locked?rollback.flowId:view.flowId} disabled={locked||view.phase==='loading'} onChange={event=>edit(event.target.value)} style={{boxSizing:'border-box',width:'100%',maxWidth:'100%',minWidth:0}}/></label><button ref={refreshButton} type="submit" disabled={view.phase==='loading'||rollback.phase==='rolling_back'||checking}>{view.phase==='loading'?'Refreshing conditional publication history...':'Refresh conditional publication history'}</button></form>
   {view.phase==='loading'&&<p role="status">Checking published form history...</p>}{view.error&&<p role="alert">{view.error}</p>}
   {view.history&&<><p>Form ID: {view.history.flowId}</p><ol style={{paddingInlineStart:24}}>{view.history.versions.map(version=><li key={version.versionId}><h3>{version.name}</h3><p>Published draft revision: {version.draftRevision}; version ID: {version.versionId}</p><p>{version.current?'Current version at last history check':'Historical version'}. Form type: {version.renderSchemaVersion===6?'Conditional informational fields':version.renderSchemaVersion===5?'Informational text fields':'Simple form'}.</p><p>Pinned design: {version.presentation.layout==='compact'?'Compact':'Stacked'}; accent color {version.presentation.accentColor}.</p>{version.renderSchemaVersion!==3&&<><h4>Published informational fields, in order</h4>{version.customerFields.length?<ol>{version.customerFields.map(field=><li key={field.id}>{field.label}; ID: {field.id}; {field.required?'Required':'Optional'}; maximum length: {field.maxLength}. {'when' in field&&field.when&&<>Shown when {field.when.fieldId} equals {field.when.equals}.</>}</li>)}</ol>:<p>No additional informational fields.</p>}<p>These are field definitions. Customer answers are not shown.</p></>}{version.publication?<><p>Installation ID: {version.publication.installationId}</p><a href={checkoutOrigin+version.publication.hostedPath} target="_blank" rel="noopener noreferrer">Open published revision {version.draftRevision}: {version.name}</a></>:<p>No verified installation link for this version.</p>}</li>)}</ol>
   {current?.renderSchemaVersion===6&&current.publication?.renderSchemaVersion===6&&onViewCurrentInstallation&&<><button type="button" disabled={blocked||currentInstallationBlocked||locked||view.phase!=='loaded'||checking} onClick={viewCurrentInstallation}>View current conditional installation</button><p>This selects the conditional version current at the last history check. It does not publish, edit the draft, verify an uncertain action or certify customer loading.</p></>}
   {!!targets.length&&current?.publication&&<><label>Prior conditional-lineage version<select value={selected} disabled={blocked||locked||view.phase==='loading'||checking} onChange={event=>{setSelected(event.target.value);setReview(null);}} style={{maxWidth:'100%',minWidth:0}}><option value="">Choose a prior version</option>{targets.map(target=><option key={target.versionId} value={target.versionId}>Revision {target.draftRevision}: {target.name}</option>)}</select></label><button ref={reviewButton} type="button" disabled={!selected||blocked||locked||checking} onClick={reviewTarget}>Review conditional rollback</button></>}
   </>}
   {blocked&&<p>Rollback is unavailable while another draft or publication action is pending or uncertain. Read-only receipt recovery remains available for an uncertain rollback.</p>}
   {locked&&<><p role="status">{rollback.phase==='rolling_back'?'Restoring the reviewed published version...':'Rollback outcome is unverified. Draft and publication changes remain locked. Do not repeat rollback.'}</p><p>Frozen rollback form: {rollback.flowId}; target version: {rollback.targetVersionId}; target installation: {rollback.targetPublication.installationId}.</p><button type="button" onClick={notify}>Check this session's rollback state</button>{rollback.phase==='unknown'&&<button type="button" disabled={checking||view.phase==='loading'} onClick={()=>void reconcile()}>{checking?'Checking rollback receipt...':'Check conditional rollback outcome'}</button>}</>}
   {verified&&<><p role="status">Rollback target verified at last check: {verified.receipt.versionId}; form: {verified.flowId}; installation: {verified.receipt.installationId}.</p><a href={checkoutOrigin+verified.receipt.hostedPath} target="_blank" rel="noopener noreferrer">Open last verified rollback target</a><p>This records the restored state at that check. A later publication may have changed the current version. Refresh history for current evidence before another review.</p></>}
  </div>
  {review&&<div role="dialog" aria-modal="true" aria-labelledby={titleId} onKeyDown={trap} style={{position:'fixed',inset:0,zIndex:1000,background:'rgba(0,0,0,.4)',display:'grid',placeItems:'center',padding:16,overflow:'auto'}}><div style={{boxSizing:'border-box',background:'white',color:'#111827',padding:20,width:'100%',maxWidth:520,minWidth:0,overflowWrap:'anywhere'}}><h3 id={titleId}>Review conditional publication rollback</h3><p>Restore {review.targetName}, published draft revision {review.targetRevision}, as the current publication for form {review.flowId}.</p><p>Expected current version: {review.currentVersionId}.</p><p>Target version: {review.targetVersionId}; existing installation: {review.targetPublication.installationId}.</p><p>This changes the current published version. It does not edit the saved draft, alter historical versions or reprice bookings. The server checks the current version and catalog eligibility. If the response is lost, check the receipt; do not repeat the action.</p><button ref={cancelButton} type="button" onClick={closeReview}>Cancel rollback</button><button ref={confirmButton} type="button" disabled={blocked||locked} onClick={()=>void confirm()}>Confirm conditional publication rollback</button></div></div>}
 </section>;
}
