import {afterEach,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {createRuntimeClient} from '@lumin/runtime-client';
import {buildDetailingService,CreateDetailingOffer} from '@lumin/contracts';
import {ConnectedDetailingCatalog} from './ConnectedDetailingCatalog';
const tenant='11111111-1111-4111-8111-111111111111',actor='22222222-2222-4222-8222-222222222222',service='33333333-3333-4333-8333-333333333333';
const json=(value:unknown,status=200)=>new Response(JSON.stringify(value),{status});
afterEach(()=>{cleanup();vi.restoreAllMocks();});
async function fixture(action?:(body:CreateDetailingOffer)=>Promise<Response>){let role='BUSINESS_OWNER',type='AUTO_DETAILING',currency='USD';
 const calls=vi.fn<typeof fetch>(async(input,options)=>{const path=String(input);if(path.includes('/token?'))return json({access_token:'private-detail-ui'});if(path.endsWith('/user'))return json({id:actor});if(path.includes('/tenant_members?'))return json([{tenant_id:tenant,role}]);if(path.includes('/business-profile?'))return json({ok:true,data:{schemaVersion:1,tenantId:tenant,businessType:type,templateVersion:1}});if(path.includes('/api/profile?'))return json({ok:true,data:{schemaVersion:1,profile:{id:tenant,name:'Detail business',slug:'detail-business',timezone:'America/Los_Angeles',currency,status:'active'}}});if(path.includes('/detailing-offers?')){const body=CreateDetailingOffer.parse(JSON.parse(String(options?.body)));return action?action(body):json({ok:true,data:{schemaVersion:1,tenantId:tenant,businessType:'AUTO_DETAILING',pricingModel:'package_subtotal_vehicle_multiplier',service:buildDetailingService(service,tenant,body)}});}throw Error('unexpected private-error');});
 const client=createRuntimeClient({url:'https://example.supabase.co',publishableKey:'sb_publishable_test',tenantId:tenant,bookingApiOrigin:'https://api.example.test'},calls);await client.signIn('owner@example.test','fixture');return{client,calls,setRole:(v:string)=>role=v,setType:(v:string)=>type=v,setCurrency:(v:string)=>currency=v};
}
const props={tenantId:tenant,role:'BUSINESS_OWNER',staging:true,apiConfigured:true,onStateChange:()=>{}};
async function fill(){fireEvent.click(screen.getByRole('button',{name:'Check detailing catalog eligibility'}));await screen.findByLabelText('Detailing service name');for(const [label,value] of [['Detailing service name','Detail test'],['Detailing duration in minutes','90'],['Package 1 ID','basic'],['Package 1 label','Basic'],['Package 1 amount in minor units','10000'],['Vehicle 1 ID','suv'],['Vehicle 1 label','SUV'],['Vehicle 1 multiplier in basis points','12500']] as const)fireEvent.change(screen.getByLabelText(label),{target:{value}});fireEvent.click(screen.getByRole('checkbox',{name:'I have no unresolved earlier detailing creation attempt'}));}
function posts(calls:ReturnType<typeof vi.fn<typeof fetch>>){return calls.mock.calls.filter(call=>String(call[0]).includes('/detailing-offers?')&&call[1]?.method==='POST');}
it('authoring requires fresh eligibility, explicit price review and keyboard confirmation with no automatic write',async()=>{const {client,calls}=await fixture();render(<ConnectedDetailingCatalog client={client} {...props}/>);expect(calls).toHaveBeenCalledTimes(2);expect(screen.queryByLabelText('Detailing service name')).toBeNull();await fill();fireEvent.click(screen.getByRole('button',{name:'Review detailing catalog prices'}));const dialog=screen.getByRole('dialog',{name:'Review authoritative detailing prices'});expect(dialog).toHaveTextContent('Package options: basic: Basic = 10000 minor units');expect(dialog).toHaveTextContent('vehicle multiplier covers the package, addons and location together');expect(screen.getByRole('button',{name:'Cancel detailing creation'})).toHaveFocus();expect(screen.getByLabelText('Package 1 ID')).toBeDisabled();expect(posts(calls)).toHaveLength(0);fireEvent.keyDown(dialog,{key:'Tab'});expect(screen.getByRole('button',{name:'Confirm create detailing catalog'})).toHaveFocus();fireEvent.keyDown(dialog,{key:'Tab',shiftKey:true});expect(screen.getByRole('button',{name:'Cancel detailing creation'})).toHaveFocus();fireEvent.keyDown(dialog,{key:'Escape'});expect(screen.queryByRole('dialog')).toBeNull();expect(screen.getByRole('button',{name:'Review detailing catalog prices'})).toHaveFocus();fireEvent.click(screen.getByRole('button',{name:'Review detailing catalog prices'}));fireEvent.click(screen.getByRole('button',{name:'Confirm create detailing catalog'}));await screen.findByText(/Server detailing catalog receipt verified/);expect(posts(calls)).toHaveLength(1);expect(JSON.parse(String(posts(calls)[0]?.[1]?.body))).toMatchObject({currency:'USD',packages:[{id:'basic',label:'Basic',amount:10000}],vehicles:[{id:'suv',label:'SUV',multiplierBp:12500}],addons:[],locations:[],idempotencyKey:expect.any(String)});expect(document.body.textContent).not.toContain('private-detail-ui');expect(screen.queryByRole('button',{name:/publish|pay/i})).toBeNull();});
it('fictional arithmetic multiplies the entire selected subtotal including addon and location, without network effects',async()=>{const {client,calls}=await fixture();render(<ConnectedDetailingCatalog client={client} {...props}/>);await fill();fireEvent.click(screen.getByRole('button',{name:'Add addon'}));fireEvent.click(screen.getByRole('button',{name:'Add location'}));for(const [label,value] of [['Addon 1 ID','pet-hair'],['Addon 1 label','Pet hair'],['Addon 1 amount in minor units','2000'],['Location 1 ID','mobile'],['Location 1 label','Mobile'],['Location 1 amount in minor units','1000']] as const)fireEvent.change(screen.getByLabelText(label),{target:{value}});const before=calls.mock.calls.length;fireEvent.click(screen.getByRole('button',{name:'Preview fictional arithmetic'}));fireEvent.click(screen.getByRole('checkbox',{name:'Preview addon: Pet hair'}));expect(screen.getByRole('region',{name:'Fictional detailing arithmetic preview'})).toHaveTextContent('Additive subtotal: 13000 minor units USD. Vehicle multiplier: 12500 basis points. Rounded example result: 16250 minor units USD');expect(screen.getByText(/not a server quote/)).toBeTruthy();expect(calls).toHaveBeenCalledTimes(before);fireEvent.change(screen.getByLabelText('Package 1 amount in minor units'),{target:{value:'20000'}});expect(screen.queryByRole('region',{name:'Fictional detailing arithmetic preview'})).toBeNull();});
it.each(['-1','1.5','1e4','9007199254740992'])('invalid package minor units %s cannot enter review or POST',async(value)=>{const {client,calls}=await fixture();render(<ConnectedDetailingCatalog client={client} {...props}/>);await fill();fireEvent.change(screen.getByLabelText('Package 1 amount in minor units'),{target:{value}});fireEvent.submit(screen.getByLabelText('Package 1 ID').closest('form')!);expect(screen.queryByRole('dialog')).toBeNull();expect(screen.getByRole('alert')).toHaveTextContent('exact safe integer');expect(posts(calls)).toHaveLength(0);});
it.each(['BUSINESS_STAFF','HOUSEKEEPING'])('unsupported %s cannot expose detailing prices or writer',async(value)=>{const x=await fixture();if(value==='HOUSEKEEPING')x.setType(value);const view=render(<ConnectedDetailingCatalog client={x.client} {...props} role={value==='BUSINESS_STAFF'?value:props.role}/>);if(value==='HOUSEKEEPING'){fireEvent.click(screen.getByRole('button',{name:'Check detailing catalog eligibility'}));await screen.findByRole('alert');}expect(screen.queryByLabelText('Detailing service name')).toBeNull();expect(posts(x.calls)).toHaveLength(0);if(value==='BUSINESS_STAFF')expect(x.calls).toHaveBeenCalledTimes(2);view.unmount();});
it('lost delivery freezes review across remount and explicit retry repeats exact body; generic errors expose no server secrets',async()=>{let n=0;const x=await fixture(async(body)=>++n===1?Promise.reject(Error('private-server-secret')):json({ok:true,data:{schemaVersion:1,tenantId:tenant,businessType:'AUTO_DETAILING',pricingModel:'package_subtotal_vehicle_multiplier',service:buildDetailingService(service,tenant,body)}}));const element=<ConnectedDetailingCatalog client={x.client} {...props}/>;const view=render(element);await fill();fireEvent.click(screen.getByRole('button',{name:'Review detailing catalog prices'}));fireEvent.click(screen.getByRole('button',{name:'Confirm create detailing catalog'}));await screen.findByRole('button',{name:'Retry this same detailing creation'});view.unmount();render(element);expect(screen.queryByLabelText('Package 1 ID')).toBeNull();expect(posts(x.calls)).toHaveLength(1);expect(document.body.textContent).not.toContain('private-server-secret');fireEvent.click(screen.getByRole('button',{name:'Retry this same detailing creation'}));await screen.findByText(/Server detailing catalog receipt verified/);expect(posts(x.calls)).toHaveLength(2);expect(posts(x.calls)[0]?.[1]?.body).toBe(posts(x.calls)[1]?.[1]?.body);});
it('pending remount settles through explicit state check without a duplicate writer',async()=>{let finish!:(v:Response)=>void,frozen!:CreateDetailingOffer;const x=await fixture(body=>{frozen=body;return new Promise(resolve=>finish=resolve);});const element=<ConnectedDetailingCatalog client={x.client} {...props}/>;const view=render(element);await fill();fireEvent.click(screen.getByRole('button',{name:'Review detailing catalog prices'}));fireEvent.click(screen.getByRole('button',{name:'Confirm create detailing catalog'}));await waitFor(()=>expect(finish).toBeTypeOf('function'));view.unmount();render(element);finish(json({ok:true,data:{schemaVersion:1,tenantId:tenant,businessType:'AUTO_DETAILING',pricingModel:'package_subtotal_vehicle_multiplier',service:buildDetailingService(service,tenant,frozen)}}));await waitFor(()=>expect(x.client.detailingOfferState(tenant).phase).toBe('created'));fireEvent.click(screen.getByRole('button',{name:"Check this session's detailing state"}));await screen.findByText(/Server detailing catalog receipt verified/);expect(posts(x.calls)).toHaveLength(1);});
it('fresh currency drift after owner review prevents POST and keeps catalog unverified',async()=>{const x=await fixture();render(<ConnectedDetailingCatalog client={x.client} {...props}/>);await fill();fireEvent.click(screen.getByRole('button',{name:'Review detailing catalog prices'}));x.setCurrency('EUR');fireEvent.click(screen.getByRole('button',{name:'Confirm create detailing catalog'}));await screen.findByRole('alert');expect(posts(x.calls)).toHaveLength(0);expect(x.client.detailingOfferState(tenant)).toEqual({phase:'ready'});});
it('client and business replacement immediately hide old fields and discard late eligibility responses',async()=>{const x=await fixture();let finish!:(v:Response)=>void;x.calls.mockImplementationOnce(()=>new Promise(resolve=>finish=resolve));const view=render(<ConnectedDetailingCatalog client={x.client} {...props}/>);fireEvent.click(screen.getByRole('button',{name:'Check detailing catalog eligibility'}));await waitFor(()=>expect(finish).toBeTypeOf('function'));const other=await fixture();view.rerender(<ConnectedDetailingCatalog client={other.client} {...props} tenantId={actor}/>);finish(json([{tenant_id:tenant,role:'BUSINESS_OWNER'}]));await waitFor(()=>expect(x.calls).toHaveBeenCalledTimes(5));expect(screen.queryByLabelText('Detailing service name')).toBeNull();expect(posts(x.calls)).toHaveLength(0);});
