import {afterEach,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import jsQR from 'jsqr';
import {PNG} from 'pngjs';
import type {PaidCustomerFieldPublicationReceipt} from '@lumin/runtime-client';
import {ConnectedBookingLinkQr} from './ConnectedBookingLinkQr';
const encoder=vi.hoisted(()=>({png:vi.fn(),svg:vi.fn()}));
vi.mock('qrcode',async importOriginal=>{const original=await importOriginal<typeof import('qrcode')>();return {...original,toDataURL:encoder.png,toString:encoder.svg};});
const tenant='11111111-1111-4111-8111-111111111111',otherTenant='22222222-2222-4222-8222-222222222222',flow='33333333-3333-4333-8333-333333333333',version='44444444-4444-4444-8444-444444444444',installation='55555555-5555-4555-8555-555555555555',otherInstallation='66666666-6666-4666-8666-666666666666';
const checkoutOrigin='https://booking-lumin-checkout-staging.netlify.app';
const expected:PaidCustomerFieldPublicationReceipt={flowId:flow,draftRevision:2,publication:{versionId:version,installationId:installation,renderSchemaVersion:5,hostedPath:'/checkout/flow/'+installation}};
const props={tenantId:tenant,checkoutOrigin,expected},link=checkoutOrigin+expected.publication.hostedPath;
afterEach(()=>{cleanup();vi.resetAllMocks();vi.unstubAllGlobals();});
async function realEncoder(){const original=await vi.importActual<typeof import('qrcode')>('qrcode');encoder.png.mockImplementation(original.toDataURL);encoder.svg.mockImplementation(original.toString);}
it('does nothing on mount and generates a real independently decoded PNG containing only the approved URL',async()=>{await realEncoder();const fetch=vi.fn();vi.stubGlobal('fetch',fetch);render(<ConnectedBookingLinkQr {...props}/>);expect(encoder.png).not.toHaveBeenCalled();expect(encoder.svg).not.toHaveBeenCalled();expect(screen.queryByRole('img')).toBeNull();const button=screen.getByRole('button',{name:'Generate PNG QR'});button.focus();expect(button).toHaveFocus();fireEvent.click(button);const download=await screen.findByRole('link',{name:'Download PNG QR'});const url=download.getAttribute('href')!;expect(download).toHaveAttribute('download','booking-link-'+installation+'.png');const image=PNG.sync.read(Buffer.from(url.split(',')[1]!,'base64'));const result=jsQR(new Uint8ClampedArray(image.data),image.width,image.height);expect(result?.data).toBe(link);expect(encoder.png).toHaveBeenCalledWith(link,expect.objectContaining({type:'image/png',margin:4}));expect(fetch).not.toHaveBeenCalled();expect(screen.getByLabelText('QR booking URL')).toHaveValue(link);expect(screen.getByRole('img')).toHaveAttribute('src',url);});
it('generates a downloadable standalone SVG without inserting SVG or HTML into the page',async()=>{await realEncoder();render(<ConnectedBookingLinkQr {...props}/>);fireEvent.click(screen.getByRole('button',{name:'Generate SVG QR'}));const download=await screen.findByRole('link',{name:'Download SVG QR'});const svg=decodeURIComponent(download.getAttribute('href')!.split(',')[1]!);expect(svg).toMatch(/^<svg /);expect(svg).toContain('<path');expect(svg).not.toMatch(/<script|foreignObject|href=|onload=/i);expect(svg).not.toContain(link);expect(document.querySelector('svg')).toBeNull();expect(encoder.svg).toHaveBeenCalledWith(link,expect.objectContaining({type:'svg'}));expect(encoder.png).not.toHaveBeenCalled();});
it.each([
 ['other origin',{checkoutOrigin:'https://merchant.example'}],['nonexact origin',{checkoutOrigin:checkoutOrigin+'/'}],['API origin',{checkoutOrigin:'https://api.example.test'}],['invalid tenant',{tenantId:'foreign'}],['unknown schema',{expected:{...expected,publication:{...expected.publication,renderSchemaVersion:3}}}],['query secret',{expected:{...expected,publication:{...expected.publication,hostedPath:expected.publication.hostedPath+'?sessionToken=private'}}}],['redirect',{expected:{...expected,publication:{...expected.publication,hostedPath:'//merchant.example'}}}],['extra field',{expected:{...expected,sessionToken:'private'}}],['invalid revision',{expected:{...expected,draftRevision:0}}],['foreign path',{expected:{...expected,publication:{...expected.publication,hostedPath:'/checkout/flow/'+otherInstallation}}}]
])('rejects %s without generating or displaying an unapproved link',async(_label,changed)=>{render(<ConnectedBookingLinkQr {...props} {...changed as Partial<typeof props>}/>);expect(screen.getByRole('alert')).toHaveTextContent('approved published');expect(screen.queryByRole('button')).toBeNull();expect(screen.queryByRole('link')).toBeNull();expect(encoder.png).not.toHaveBeenCalled();expect(document.body).not.toHaveTextContent('private');});
it.each(['tenant','receipt'] as const)('drops pending output and clears downloads when %s changes',async change=>{let finish!:(value:string)=>void;encoder.png.mockReturnValue(new Promise<string>(resolve=>finish=resolve));const view=render(<ConnectedBookingLinkQr {...props}/>);fireEvent.click(screen.getByRole('button',{name:'Generate PNG QR'}));await waitFor(()=>expect(encoder.png).toHaveBeenCalledOnce());expect(screen.getByRole('button',{name:'Generate SVG QR'})).toBeDisabled();const next=change==='tenant'?{...props,tenantId:otherTenant}:{...props,expected:{...expected,publication:{...expected.publication,installationId:otherInstallation,hostedPath:'/checkout/flow/'+otherInstallation}}};view.rerender(<ConnectedBookingLinkQr {...next}/>);finish('data:image/png;base64,aGVsbG8=');await waitFor(()=>expect(screen.getByRole('button',{name:'Generate PNG QR'})).toBeEnabled());expect(screen.queryByRole('img')).toBeNull();expect(screen.queryByRole('link')).toBeNull();expect(encoder.png).toHaveBeenCalledOnce();});
it('clears an already generated artifact immediately on publication change',async()=>{encoder.png.mockResolvedValue('data:image/png;base64,aGVsbG8=');const view=render(<ConnectedBookingLinkQr {...props}/>);fireEvent.click(screen.getByRole('button',{name:'Generate PNG QR'}));await screen.findByRole('link',{name:'Download PNG QR'});view.rerender(<ConnectedBookingLinkQr {...props} expected={{...expected,draftRevision:3}}/>);expect(screen.queryByRole('img')).toBeNull();expect(screen.queryByRole('link')).toBeNull();expect(encoder.png).toHaveBeenCalledOnce();});
it('shows a generic secret-safe generation error and retries only after another click',async()=>{encoder.png.mockRejectedValueOnce(Error('sessionToken=secret private-answer')).mockResolvedValueOnce('data:image/png;base64,aGVsbG8=');render(<ConnectedBookingLinkQr {...props}/>);fireEvent.click(screen.getByRole('button',{name:'Generate PNG QR'}));await screen.findByRole('alert');expect(document.body).not.toHaveTextContent('secret');expect(document.body).not.toHaveTextContent('private-answer');expect(encoder.png).toHaveBeenCalledOnce();fireEvent.click(screen.getByRole('button',{name:'Generate PNG QR'}));await screen.findByRole('link',{name:'Download PNG QR'});expect(encoder.png).toHaveBeenCalledTimes(2);});
it('rejects unexpected encoder formats and embedded active SVG content',async()=>{encoder.svg.mockResolvedValue('<svg xmlns="http://www.w3.org/2000/svg"><script>private</script></svg>\n');render(<ConnectedBookingLinkQr {...props}/>);fireEvent.click(screen.getByRole('button',{name:'Generate SVG QR'}));await screen.findByRole('alert');expect(screen.queryByRole('link')).toBeNull();expect(document.body).not.toHaveTextContent('private');encoder.png.mockResolvedValue('https://qr-service.example/private');fireEvent.click(screen.getByRole('button',{name:'Generate PNG QR'}));await waitFor(()=>expect(encoder.png).toHaveBeenCalledOnce());expect(screen.queryByRole('link')).toBeNull();});
