import {useEffect,useRef,useState,type FormEvent} from 'react';
import {BusinessType,CreateBusiness,type BusinessProfile} from '@lumin/contracts';
import {getBusinessTemplateDefaults} from '@lumin/templates';
import {BusinessOnboardingError,type RuntimeClient,type BusinessCreationState,type BusinessProfileRead} from '@lumin/runtime-client';
const types:Record<BusinessType,string>={HOUSEKEEPING:'Housekeeping',AUTO_DETAILING:'Auto detailing',VEHICLE_RENTAL:'Vehicle rental',EQUIPMENT_RENTAL:'Equipment rental',EVENT_RENTAL:'Event rental',JUNK_REMOVAL:'Junk removal'};
function BusinessDefaults({profile}:{profile:BusinessProfile}){
 const defaults=getBusinessTemplateDefaults(profile);
 return <section aria-label={'Unapplied setup defaults for business '+profile.tenantId}><h3>Unapplied setup defaults</h3><p>Business: {profile.tenantId}. Suggested catalog language: {defaults.catalog.plural}; option group: {defaults.catalog.optionsLabel}; resource group: {defaults.context.resourceLabel}.</p><p>These are structural defaults from the verified business type. They are not applied or persisted here. No prices, inventory, capacities or booking eligibility are configured by this description.</p></section>;
}
type Client=Pick<RuntimeClient,'createBusiness'|'businessCreationState'|'businessProfile'>;
type Fields={name:string;slug:string;timezone:string;currency:string;businessType:string};
const empty:Fields={name:'',slug:'',timezone:'',currency:'',businessType:''};
type Props={client:Client;tenantId:string;role?:string;firstBusinessEligible?:boolean;staging:boolean;apiConfigured:boolean;contextBusy?:boolean;onStateChange:()=>void;onOpen:(profile:BusinessProfile)=>Promise<void>};
export function ConnectedBusinessOnboarding(props:Props){
 if(!props.staging||!props.apiConfigured)return <section aria-label="Business onboarding"><h2>Business setup</h2><p>New-business onboarding is unavailable in this workspace. It requires the connected staging API and an explicitly enabled server capability; production and default capability remain unavailable.</p></section>;
 if(props.role!=='BUSINESS_OWNER'&&!(props.firstBusinessEligible===true&&props.role===undefined&&props.tenantId===''))return <section aria-label="Business onboarding"><h2>Business setup</h2><p>Creation is available to a verified business owner or a freshly signed-in account with a successful empty membership lookup. Existing staff or worker memberships do not qualify.</p></section>;
 return <ConnectedBusinessOnboardingOwner {...props}/>;
}
function ConnectedBusinessOnboardingOwner({client,tenantId,contextBusy=false,onStateChange,onOpen,firstBusinessEligible}:Props){
 const [open,setOpen]=useState(false),[fields,setFields]=useState<Fields>(empty),[review,setReview]=useState<{client:Client;tenantId:string;body:CreateBusiness}|null>(null);
 const [snapshot,setSnapshot]=useState<{client:Client;state:BusinessCreationState}>(()=>({client,state:client.businessCreationState()}));
 const [error,setError]=useState(''),[opening,setOpening]=useState(false),[profileRead,setProfileRead]=useState<{client:Client;tenantId:string;loading:boolean;value?:BusinessProfileRead;error:string}>({client,tenantId,loading:false,error:''});
 const returnFocus=useRef(false),generation=useRef(0),inFlight=useRef(false),profileInFlight=useRef(false),cancelRef=useRef<HTMLButtonElement>(null),reviewRef=useRef<HTMLButtonElement>(null);
 useEffect(()=>{generation.current++;inFlight.current=false;profileInFlight.current=false;setOpen(false);setFields(empty);setReview(null);setSnapshot({client,state:client.businessCreationState()});setError('');setOpening(false);setProfileRead({client,tenantId,loading:false,error:''});return()=>{generation.current++;};},[client,tenantId]);
 const state=snapshot.client===client?snapshot.state:client.businessCreationState(),pending=state.phase==='checking'||state.phase==='creating',locked=pending||state.phase==='unknown';
 const reviewed=review?.client===client&&review.tenantId===tenantId?review:null;
 const currentProfile=profileRead.client===client&&profileRead.tenantId===tenantId?profileRead:undefined;
 useEffect(()=>{if(reviewed)cancelRef.current?.focus();else if(returnFocus.current){returnFocus.current=false;reviewRef.current?.focus();}},[reviewed]);
 function closeReview(){returnFocus.current=true;setReview(null);}
 function checkSession(){setSnapshot({client,state:client.businessCreationState()});onStateChange();}
 function prepare(event:FormEvent){event.preventDefault();if(contextBusy||locked||state.phase==='created'||state.phase==='unavailable')return;const parsed=CreateBusiness.safeParse({...fields,name:fields.name.trim(),idempotencyKey:crypto.randomUUID()});if(!parsed.success){setError('Enter a business name, lowercase slug, named IANA timezone, three-letter uppercase currency and one fixed business type.');return;}setError('');setReview({client,tenantId,body:parsed.data});}
 async function send(body:CreateBusiness){
  if(inFlight.current||pending)return;const at=generation.current;inFlight.current=true;setReview(null);setError('');
  const promise=client.createBusiness(body);checkSession();
  try{await promise;if(at===generation.current)checkSession();}
  catch(error){if(at===generation.current){setError(error instanceof BusinessOnboardingError?error.message:'Business creation outcome could not be verified. Check this session state before another action.');checkSession();}}
  finally{if(at===generation.current)inFlight.current=false;}
 }
 async function readProfile(){if(profileInFlight.current)return;const at=generation.current;profileInFlight.current=true;setProfileRead({client,tenantId,loading:true,error:''});try{const value=await client.businessProfile(tenantId);if(at===generation.current)setProfileRead({client,tenantId,loading:false,value,error:''});}catch(error){if(at===generation.current)setProfileRead({client,tenantId,loading:false,error:error instanceof BusinessOnboardingError?error.message:'Business type is unverified.'});}finally{if(at===generation.current)profileInFlight.current=false;}}
 async function openCreated(){if(state.phase!=='created'||opening||inFlight.current)return;const at=generation.current;setOpening(true);setError('');try{await onOpen(state.profile);}catch(error){if(at===generation.current)setError(error instanceof Error?error.message:'The created business owner membership could not be verified. The creation receipt is retained.');}finally{if(at===generation.current)setOpening(false);}}
 const shown=open||state.phase!=='ready';
 return <section aria-label="Business onboarding" style={{minWidth:0,overflowWrap:'anywhere'}}><h2>Business setup</h2>{firstBusinessEligible&&tenantId===''&&<p>Your verified membership lookup returned no assigned businesses. You can create your first staging business; the server grants owner membership only after successful creation.</p>}<p>This creates a separate staging business. Its business type is permanent and cannot be changed here. It never assigns a type to your existing business. Creating a business does not configure services, templates or payments.</p><p>The server onboarding capability must be explicitly enabled in staging; it is unavailable in production and disabled by default.</p>
 {tenantId&&<button type="button" disabled={currentProfile?.loading} onClick={()=>void readProfile()}>Check current business type</button>}{currentProfile?.loading&&<p role="status">Checking current business type...</p>}{currentProfile?.error&&<p role="alert">{currentProfile.error}</p>}{currentProfile?.value?.status==='uninitialized'&&<p role="status">This existing business is uninitialized: no authoritative business type is recorded. Creating a separate business will not initialize or change this one.</p>}{currentProfile?.value?.status==='initialized'&&<p>Current business type: {types[currentProfile.value.profile.businessType]}. Permanent type; template contract version {currentProfile.value.profile.templateVersion}.</p>}
 {currentProfile?.value?.status==='initialized'&&<BusinessDefaults profile={currentProfile.value.profile}/>}
 {!shown&&<button type="button" disabled={contextBusy} onClick={()=>setOpen(true)}>Create a new staging business</button>}
 {shown&&state.phase==='ready'&&<form onSubmit={prepare}><fieldset disabled={contextBusy||!!reviewed} className="form-stack" style={{minWidth:0}}><legend>New business details</legend><label>New business name<input required maxLength={200} value={fields.name} onChange={event=>setFields({...fields,name:event.target.value})}/></label><label>New business slug<input required minLength={2} maxLength={100} pattern="[a-z0-9][a-z0-9-]*[a-z0-9]" value={fields.slug} onChange={event=>setFields({...fields,slug:event.target.value})}/></label><p>Use a unique lowercase slug with letters, numbers and internal hyphens.</p><label>New business timezone<input required maxLength={100} placeholder="America/Los_Angeles or UTC" value={fields.timezone} onChange={event=>setFields({...fields,timezone:event.target.value})}/></label><label>New business currency<input required minLength={3} maxLength={3} pattern="[A-Z]{3}" value={fields.currency} onChange={event=>setFields({...fields,currency:event.target.value})}/></label><label>Permanent business type<select required value={fields.businessType} onChange={event=>setFields({...fields,businessType:event.target.value})}><option value="">Choose a fixed business type</option>{BusinessType.options.map(type=><option key={type} value={type}>{types[type]}</option>)}</select></label><button ref={reviewRef} type="submit">Review new business</button></fieldset></form>}
 {reviewed&&<div role="dialog" aria-label="Review permanent business type" onKeyDown={event=>{if(event.key==='Escape'){event.preventDefault();closeReview();}}}><h3>Review new staging business</h3><dl><dt>Name</dt><dd>{reviewed.body.name}</dd><dt>Slug</dt><dd>{reviewed.body.slug}</dd><dt>Timezone</dt><dd>{reviewed.body.timezone}</dd><dt>Currency</dt><dd>{reviewed.body.currency}</dd><dt>Permanent business type</dt><dd>{types[reviewed.body.businessType]}</dd></dl><p>Confirm this permanent type for a new, separate business. This is not a type toggle, and it will not change your current business. Use test data only.</p><button ref={cancelRef} type="button" onClick={()=>{closeReview();}}>Cancel new business</button><button type="button" disabled={contextBusy||locked} onClick={()=>void send(reviewed.body)}>Confirm create staging business</button></div>}
 {state.phase!=='ready'&&state.phase!=='unavailable'&&<><p>Frozen attempt key: {state.attempt.idempotencyKey}</p><p>Attempt details: {state.attempt.name}; slug {state.attempt.slug}; timezone {state.attempt.timezone}; currency {state.attempt.currency}; permanent type {types[state.attempt.businessType]}.</p></>}
 {pending&&<><p role="status">{state.phase==='checking'?'Checking fresh business membership...':'Creating the reviewed staging business...'}</p><button type="button" onClick={checkSession}>Check this session's business creation state</button></>}
 {state.phase==='unknown'&&<><p role="alert">Business creation is unverified. Details and key are frozen. Do not create a different attempt; retry only this same attempt with the same signed-in account.</p><button type="button" disabled={contextBusy} onClick={()=>void send(state.attempt)}>Retry this same business creation</button></>}
 {state.phase==='unavailable'&&<p role="status">Business onboarding is unavailable. The server staging capability is disabled; no business creation is confirmed.</p>}
 {state.phase==='created'&&<><BusinessDefaults profile={state.profile}/><p role="status">Server creation receipt verified. New business ID: {state.profile.tenantId}; permanent type: {types[state.profile.businessType]}; template contract version: {state.profile.templateVersion}.</p><p>Refresh and verify your owner membership before opening this business. The receipt alone does not configure its catalog or prove its workspace is ready.</p><button type="button" disabled={opening||contextBusy} onClick={()=>void openCreated()}>{opening?'Checking created business owner membership...':'Open created business'}</button></>}
 {error&&<p role="alert">{error}</p>}
 </section>;
}
