import {afterEach,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {createRuntimeClient,type PaidSimpleFieldOwnerDraft,type PaidCustomerFieldPublicationState} from '@lumin/runtime-client';
import {ConnectedCustomerFieldPublication} from './ConnectedCustomerFieldPublication';
const tenant='11111111-1111-4111-8111-111111111111',flow='22222222-2222-4222-8222-222222222222',service='33333333-3333-4333-8333-333333333333',version='44444444-4444-4444-8444-444444444444',installation='55555555-5555-4555-8555-555555555555',other='66666666-6666-4666-8666-666666666666';
const draft:PaidSimpleFieldOwnerDraft={schemaVersion:2,flowId:flow,revision:3,serviceId:service,name:'Access visit',presentation:{accentColor:'#0f766e',layout:'compact'},customerFields:[{id:'custom_notes',kind:'text',label:'Access notes',required:false,maxLength:100}]};
const receipt={flowId:flow,draftRevision:3,publication:{versionId:version,installationId:installation,renderSchemaVersion:5 as const,hostedPath:'/checkout/flow/'+installation}};
const json=(value:unknown,status=200)=>new Response(JSON.stringify(value),{status});
afterEach(()=>{cleanup();vi.restoreAllMocks();});
async function fixture(handler:(url:string,init?:RequestInit)=>Promise<Response>){
 const calls=vi.fn<typeof fetch>(async(input,init)=>String(input).includes('/auth/v1/token')?json({access_token:'synthetic-owner-token'}):String(input).includes('/auth/v1/user')?json({id:other}):String(input).includes('/api/paid-simple-flows/'+flow+'/draft?')?json({ok:true,data:draft}):handler(String(input),init));
 const client=createRuntimeClient({url:'https://fixture.supabase.co',publishableKey:'sb_publishable_fixture',tenantId:tenant,bookingApiOrigin:'https://api.example.test'},calls);await client.signIn('owner@example.test','fixture');await client.loadPaidSimpleDraft(tenant,flow);return{client,calls};
}
it('does not publish on mount and sends only the explicitly reviewed saved revision and canonical origin',async()=>{
 const {client,calls}=await fixture(async()=>json({ok:true,data:receipt})),onStateChange=vi.fn();render(<ConnectedCustomerFieldPublication client={client} tenantId={tenant} draft={draft} pristine available blocked={false} onStateChange={onStateChange}/>);
 expect(calls).toHaveBeenCalledTimes(3);fireEvent.click(screen.getByRole('button',{name:'Publish saved informational fields'}));await screen.findByText('Informational-field publication verified at the last check.');expect(calls).toHaveBeenCalledTimes(4);expect(JSON.parse(calls.mock.calls[3]![1]!.body as string)).toEqual({expectedDraftRevision:3,allowedOrigins:['https://booking-lumin-checkout-staging.netlify.app']});expect(screen.getByRole('link',{name:'Open published informational-field booking form'})).toHaveAttribute('href','https://booking-lumin-checkout-staging.netlify.app'+receipt.publication.hostedPath);expect(screen.getByRole('button',{name:'Publish saved informational fields'})).toBeDisabled();expect(onStateChange).toHaveBeenCalled();
});
it.each([{pristine:false,available:true,blocked:false},{pristine:true,available:false,blocked:false},{pristine:true,available:true,blocked:true}])('blocks publication for unreviewed or unavailable scope %j',async flags=>{
 const {client,calls}=await fixture(async()=>{throw Error('unexpected');});render(<ConnectedCustomerFieldPublication client={client} tenantId={tenant} draft={draft} {...flags} onStateChange={()=>{}}/>);expect(screen.getByRole('button',{name:'Publish saved informational fields'})).toBeDisabled();expect(calls).toHaveBeenCalledTimes(3);
});
it('retains a lost publication across remount and recovers the same receipt using GET without a second writer',async()=>{
 const {client,calls}=await fixture(async(_url,init)=>init?.method==='POST'?Promise.reject(Error('private-provider-secret')):json({ok:true,data:receipt}));const first=render(<ConnectedCustomerFieldPublication client={client} tenantId={tenant} draft={draft} pristine available blocked={false} onStateChange={()=>{}}/>);
 fireEvent.click(screen.getByRole('button',{name:'Publish saved informational fields'}));await screen.findByText(/Publication outcome is unverified/);const frozen=client.paidCustomerFieldPublicationState(tenant);expect(frozen.phase).toBe('unknown');expect(document.body.textContent).not.toContain('private-provider-secret');first.unmount();render(<ConnectedCustomerFieldPublication client={client} tenantId={tenant} draft={{...draft,revision:4}} pristine available blocked={false} onStateChange={()=>{}}/>);
 expect(screen.getByText(/saved revision: 3/)).toBeTruthy();expect(calls).toHaveBeenCalledTimes(4);fireEvent.click(screen.getByRole('button',{name:'Check field publication receipt'}));await screen.findByText('Informational-field publication verified at the last check.');expect(calls.mock.calls.slice(3).map(([,init])=>init?.method)).toEqual(['POST','GET']);expect(client.paidCustomerFieldPublicationState(tenant).phase).toBe('published');
});
it('metadata-only missing-receipt recovery never offers a writer retry',async()=>{
 const {client,calls}=await fixture(async()=>json({ok:false,code:'NOT_AVAILABLE'},404));render(<ConnectedCustomerFieldPublication client={client} tenantId={tenant} draft={draft} pristine available blocked={false} onStateChange={()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:'Check field publication receipt'}));await screen.findByText(/This read-only recovery has no original request body/);expect(screen.getByRole('button',{name:'Retry the same field publication'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:"Check this session's field publication state"}));expect(screen.getByRole('button',{name:'Retry the same field publication'})).toBeDisabled();expect(calls.mock.calls.slice(3).map(([,init])=>init?.method)).toEqual(['GET']);
});
it('explicit retry preserves the original frozen POST body while changed local draft data cannot replace it',async()=>{
 let writes=0;const {client,calls}=await fixture(async()=>++writes===1?Promise.reject(Error('lost')):json({ok:true,data:receipt}));const first=render(<ConnectedCustomerFieldPublication client={client} tenantId={tenant} draft={draft} pristine available blocked={false} onStateChange={()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:'Publish saved informational fields'}));await screen.findByText(/Publication outcome is unverified/);const original=calls.mock.calls[3]![1]!.body;first.unmount();render(<ConnectedCustomerFieldPublication client={client} tenantId={tenant} draft={{...draft,revision:4,name:'Other local edit'}} pristine={false} available blocked={false} onStateChange={()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:'Retry the same field publication'}));await screen.findByText('Informational-field publication verified at the last check.');expect(calls.mock.calls[4]![1]!.body).toBe(original);
});
it('suppresses a late receipt after switching business and never displays its link under the new tenant',async()=>{
 let resolve!:(response:Response)=>void;const {client,calls}=await fixture(()=>new Promise<Response>(r=>resolve=r));const {rerender}=render(<ConnectedCustomerFieldPublication client={client} tenantId={tenant} draft={draft} pristine available blocked={false} onStateChange={()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:'Publish saved informational fields'}));await waitFor(()=>expect(resolve).toBeTypeOf('function'));rerender(<ConnectedCustomerFieldPublication client={client} tenantId={other} pristine={false} available blocked={false} onStateChange={()=>{}}/>);resolve(json({ok:true,data:receipt}));await waitFor(()=>expect(client.paidCustomerFieldPublicationState(tenant).phase).toBe('published'));expect(screen.queryByRole('link',{name:'Open published informational-field booking form'})).toBeNull();expect(document.body.textContent).not.toContain(version);expect(calls).toHaveBeenCalledTimes(4);
});
it('withholds an installation link for an invalid receipt supplied by a stale client adapter',async()=>{
 const {client,calls}=await fixture(async()=>{throw Error('unexpected');});vi.spyOn(client,'paidCustomerFieldPublicationState').mockReturnValue({phase:'published',flowId:flow,draftRevision:3,receipt:{...receipt,publication:{...receipt.publication,hostedPath:'https://foreign.example/steal'}}} as PaidCustomerFieldPublicationState);render(<ConnectedCustomerFieldPublication client={client} tenantId={tenant} draft={draft} pristine available blocked={false} onStateChange={()=>{}}/>);expect(screen.getByRole('alert')).toHaveTextContent('receipt could not be verified');expect(screen.queryByRole('link')).toBeNull();expect(calls).toHaveBeenCalledTimes(3);
});
