import {afterEach,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {createRuntimeClient} from '@lumin/runtime-client';
import {ConnectedOfferScheduling} from './ConnectedOfferScheduling';
const tenant='11111111-1111-4111-8111-111111111111',actor='22222222-2222-4222-8222-222222222222',service='33333333-3333-4333-8333-333333333333',rule='44444444-4444-4444-8444-444444444444';
const offer={schemaVersion:1 as const,tenantId:tenant,service:{id:service,name:'Standard clean',description:'Reviewed offer',archetype:'simple' as const,price:{amount:12500,currency:'USD'},durationMinutes:60}};
const receipt={schemaVersion:1,tenantId:tenant,serviceId:service,timezone:'America/Los_Angeles',windows:[{id:rule,weekday:1,startMinute:540,endMinute:1020,capacity:1}],policy:{id:actor,leadTimeMinutes:60,horizonDays:14,slotIntervalMinutes:30}};
const json=(value:unknown,status=200)=>new Response(JSON.stringify(value),{status});
afterEach(()=>{cleanup();vi.restoreAllMocks();});
async function fixture(action:()=>Promise<Response>){let membershipRole='BUSINESS_OWNER',timezone='America/Los_Angeles',businessType='HOUSEKEEPING';
 const calls=vi.fn<typeof fetch>(async(input)=>{const path=String(input);if(path.includes('/token?'))return json({access_token:'private-scheduling-owner'});if(path.endsWith('/user'))return json({id:actor});if(path.includes('/tenant_members?'))return json([{tenant_id:tenant,role:membershipRole}]);if(path.includes('/business-profile?'))return json({ok:true,data:{schemaVersion:1,tenantId:tenant,businessType,templateVersion:1}});if(path.includes('/api/profile?'))return json({ok:true,data:{schemaVersion:1,profile:{id:tenant,name:'Housekeeping',slug:'housekeeping',timezone,currency:'USD',status:'active'}}});if(path.includes('/scheduling?'))return action();if(path.includes('/simple-offers?'))return json({ok:true,data:offer});throw Error('unexpected');});
 const client=createRuntimeClient({url:'https://example.supabase.co',publishableKey:'sb_publishable_fixture',tenantId:tenant,bookingApiOrigin:'https://api.example.test'},calls);await client.signIn('owner@example.test','fixture');await client.createSimpleOffer(tenant,{name:offer.service.name,description:offer.service.description,price:offer.service.price,durationMinutes:60,idempotencyKey:'known-offer-attempt-0001'});return{client,calls,setRole:(role:string)=>membershipRole=role,setTimezone:(value:string)=>timezone=value,setBusinessType:(value:string)=>businessType=value};
}
const props={tenantId:tenant,offer,onStateChange:()=>{}};
async function review(){fireEvent.click(screen.getByRole('button',{name:'Verify scheduling owner and timezone'}));await screen.findByLabelText('Common start time');fireEvent.click(screen.getByRole('checkbox',{name:'Monday'}));for(const [label,value] of [['Common start time','09:00'],['Common end time','17:00'],['Lead time in minutes','60'],['Booking horizon in days','14'],['Slot interval in minutes','30']] as const)fireEvent.change(screen.getByLabelText(label),{target:{value}});fireEvent.click(screen.getByRole('button',{name:'Review offer scheduling'}));}
it('reviews selected business-local hours and fixed capacity before exactly one explicit write',async()=>{const {client,calls}=await fixture(async()=>json({ok:true,data:receipt}));render(<ConnectedOfferScheduling client={client} {...props}/>);expect(screen.queryByLabelText('Common start time')).toBeNull();expect(screen.getByText(/No hours or policy are applied automatically/)).toBeTruthy();await review();expect(screen.getByRole('dialog',{name:'Review offer scheduling'})).toHaveTextContent('Monday: 09:00 to 17:00');expect(screen.getByRole('dialog')).toHaveTextContent('Lead time: 60 minutes; horizon: 14 days; slot interval: 30 minutes');expect(screen.getByRole('button',{name:'Cancel scheduling setup'})).toHaveFocus();expect(screen.getByLabelText('Common start time')).toBeDisabled();expect(calls.mock.calls.filter(call=>String(call[0]).includes('/scheduling?'))).toHaveLength(0);fireEvent.keyDown(screen.getByRole('dialog'),{key:'Escape'});expect(screen.getByRole('button',{name:'Review offer scheduling'})).toHaveFocus();fireEvent.click(screen.getByRole('button',{name:'Review offer scheduling'}));fireEvent.click(screen.getByRole('button',{name:'Confirm configure offer scheduling'}));await screen.findByText(/Server scheduling receipt verified/);const posts=calls.mock.calls.filter(call=>String(call[0]).includes('/scheduling?'));expect(posts).toHaveLength(1);expect(JSON.parse(String(posts[0]?.[1]?.body))).toEqual({timezone:'America/Los_Angeles',windows:[{weekday:1,startMinute:540,endMinute:1020,capacity:1}],policy:{leadTimeMinutes:60,horizonDays:14,slotIntervalMinutes:30},idempotencyKey:expect.any(String)});expect(screen.getByText(/This receipt does not publish a form/)).toBeTruthy();expect(document.body.textContent).not.toContain('private-scheduling-owner');});
it.each([['Common end time','09:30'],['Common end time','08:00'],['Lead time in minutes','10081'],['Booking horizon in days','31'],['Lead time in minutes','1.5']] as const)('rejects invalid %s=%s without a scheduling writer',async(label,value)=>{const {client,calls}=await fixture(async()=>{throw Error('unexpected');});render(<ConnectedOfferScheduling client={client} {...props}/>);await review();fireEvent.click(screen.getByRole('button',{name:'Cancel scheduling setup'}));fireEvent.change(screen.getByLabelText(label),{target:{value}});fireEvent.submit(screen.getByLabelText('Common start time').closest('form')!);expect(screen.queryByRole('dialog')).toBeNull();expect(calls.mock.calls.some(call=>String(call[0]).includes('/scheduling?'))).toBe(false);});
it('sorts unique selected weekdays regardless of click order',async()=>{const {client,calls}=await fixture(async()=>{throw Error('unexpected');});render(<ConnectedOfferScheduling client={client} {...props}/>);await review();fireEvent.click(screen.getByRole('button',{name:'Cancel scheduling setup'}));fireEvent.click(screen.getByRole('checkbox',{name:'Friday'}));fireEvent.click(screen.getByRole('checkbox',{name:'Sunday'}));fireEvent.click(screen.getByRole('button',{name:'Review offer scheduling'}));expect(screen.getAllByRole('listitem').map(element=>element.textContent)).toEqual(['Sunday: 09:00 to 17:00','Monday: 09:00 to 17:00','Friday: 09:00 to 17:00']);expect(calls.mock.calls.some(call=>String(call[0]).includes('/scheduling?'))).toBe(false);});
it('freezes lost delivery across remount and explicitly retries the exact same key and body',async()=>{let n=0;const {client,calls}=await fixture(async()=>++n===1?Promise.reject(Error('lost-private')):json({ok:true,data:receipt}));const element=<ConnectedOfferScheduling client={client} {...props}/>;const first=render(element);await review();fireEvent.click(screen.getByRole('button',{name:'Confirm configure offer scheduling'}));await screen.findByRole('button',{name:'Retry this same scheduling setup'});const locked=client.offerSchedulingState(tenant,service);first.unmount();render(element);expect(screen.queryByLabelText('Common start time')).toBeNull();expect(client.offerSchedulingState(tenant,service)).toEqual(locked);expect(calls.mock.calls.filter(call=>String(call[0]).includes('/scheduling?'))).toHaveLength(1);fireEvent.click(screen.getByRole('button',{name:'Retry this same scheduling setup'}));await screen.findByText(/Server scheduling receipt verified/);const posts=calls.mock.calls.filter(call=>String(call[0]).includes('/scheduling?'));expect(posts).toHaveLength(2);expect(posts[0]?.[1]?.body).toBe(posts[1]?.[1]?.body);});
it('recovers pending state after remount without a second POST',async()=>{let finish!:(response:Response)=>void;const {client,calls}=await fixture(()=>new Promise(resolve=>finish=resolve));const element=<ConnectedOfferScheduling client={client} {...props}/>;const first=render(element);await review();fireEvent.click(screen.getByRole('button',{name:'Confirm configure offer scheduling'}));await waitFor(()=>expect(finish).toBeTypeOf('function'));first.unmount();render(element);finish(json({ok:true,data:receipt}));await waitFor(()=>expect(client.offerSchedulingState(tenant,service).phase).toBe('configured'));fireEvent.click(screen.getByRole('button',{name:"Check this session's scheduling state"}));await screen.findByText(/Server scheduling receipt verified/);expect(calls.mock.calls.filter(call=>String(call[0]).includes('/scheduling?'))).toHaveLength(1);});
it('does not POST if timezone or owner role changes after the price-independent scheduling review',async()=>{const setup=await fixture(async()=>{throw Error('unexpected');});render(<ConnectedOfferScheduling client={setup.client} {...props}/>);await review();setup.setTimezone('UTC');fireEvent.click(screen.getByRole('button',{name:'Confirm configure offer scheduling'}));await screen.findByText(/reviewed timezone no longer matches/);expect(setup.calls.mock.calls.some(call=>String(call[0]).includes('/scheduling?'))).toBe(false);expect(setup.client.offerSchedulingState(tenant,service)).toEqual({phase:'ready'});});
it('keeps staff or unsupported profile checks from exposing scheduling inputs',async()=>{const setup=await fixture(async()=>{throw Error('unexpected');});setup.setRole('BUSINESS_STAFF');render(<ConnectedOfferScheduling client={setup.client} {...props}/>);fireEvent.click(screen.getByRole('button',{name:'Verify scheduling owner and timezone'}));await screen.findByText(/Fresh owner membership/);expect(screen.queryByLabelText('Common start time')).toBeNull();expect(setup.calls.mock.calls.some(call=>String(call[0]).includes('/scheduling?'))).toBe(false);});
it('drops late scheduling context on tenant replacement and rejects a foreign receipt before controls',async()=>{const {client,calls}=await fixture(async()=>{throw Error('unexpected');});let finish!:(response:Response)=>void;calls.mockImplementationOnce(()=>new Promise(resolve=>finish=resolve));const view=render(<ConnectedOfferScheduling client={client} {...props}/>);fireEvent.click(screen.getByRole('button',{name:'Verify scheduling owner and timezone'}));await waitFor(()=>expect(finish).toBeTypeOf('function'));view.rerender(<ConnectedOfferScheduling client={client} {...props} tenantId={actor}/>);finish(json([{tenant_id:tenant,role:'BUSINESS_OWNER'}]));await waitFor(()=>expect(calls).toHaveBeenCalledTimes(9));expect(screen.queryByLabelText('Common start time')).toBeNull();expect(screen.queryByRole('button',{name:'Verify scheduling owner and timezone'})).toBeNull();expect(screen.getByText(/valid offer receipt for this exact business/)).toBeTruthy();});
