import {useEffect,useRef,useState,type FormEvent} from 'react';
import {BusinessType,type BusinessProfile} from '@lumin/contracts';
import {BusinessOnboardingError,type RuntimeClient,type BusinessProfileInitializationInput} from '@lumin/runtime-client';
type Client=Pick<RuntimeClient,'initializeBusinessProfile'|'businessProfileInitializationState'>;
type Props={client:Client;tenantId:string;role?:string;uninitialized:boolean;blocked:boolean;onStateChange:()=>void;onInitialized:(profile:BusinessProfile)=>void};
const names:Record<BusinessType,string>={HOUSEKEEPING:'Housekeeping',AUTO_DETAILING:'Auto detailing',VEHICLE_RENTAL:'Vehicle rental',EQUIPMENT_RENTAL:'Equipment rental',EVENT_RENTAL:'Event rental',JUNK_REMOVAL:'Junk removal'};
export function ConnectedBusinessProfileInitializer(props:Props){if(props.role!=='BUSINESS_OWNER'||!props.tenantId)return null;return <OwnerInitializer {...props}/>;}
function OwnerInitializer({client,tenantId,uninitialized,blocked,onStateChange,onInitialized}:Props){
 const [type,setType]=useState(''),[error,setError]=useState(''),[review,setReview]=useState<{client:Client;tenantId:string;body:BusinessProfileInitializationInput}|null>(null);
 const [snapshot,setSnapshot]=useState(()=>({client,tenantId,state:client.businessProfileInitializationState(tenantId)}));
 const generation=useRef(0),inFlight=useRef(false),cancelRef=useRef<HTMLButtonElement>(null),reviewRef=useRef<HTMLButtonElement>(null),returnFocus=useRef(false);
 useEffect(()=>{generation.current++;inFlight.current=false;setType('');setError('');setReview(null);setSnapshot({client,tenantId,state:client.businessProfileInitializationState(tenantId)});return()=>{generation.current++;};},[client,tenantId]);
 const state=snapshot.client===client&&snapshot.tenantId===tenantId?snapshot.state:client.businessProfileInitializationState(tenantId),pending=state.phase==='checking'||state.phase==='initializing',reviewed=review?.client===client&&review.tenantId===tenantId?review:null;
 useEffect(()=>{if(reviewed)cancelRef.current?.focus();else if(returnFocus.current){returnFocus.current=false;reviewRef.current?.focus();}},[reviewed]);
 function close(){returnFocus.current=true;setReview(null);}
 function sync(){const next=client.businessProfileInitializationState(tenantId);setSnapshot({client,tenantId,state:next});onStateChange();if(next.phase==='initialized')onInitialized(next.profile);}
 function prepare(event:FormEvent){event.preventDefault();if(blocked||!uninitialized||state.phase!=='ready')return;const result=BusinessType.safeParse(type);if(!result.success){setError('Choose one permanent business type.');return;}setError('');setReview({client,tenantId,body:{businessType:result.data,idempotencyKey:crypto.randomUUID()}});}
 async function send(body:BusinessProfileInitializationInput){if(blocked||pending||inFlight.current)return;const at=generation.current;inFlight.current=true;setReview(null);setError('');const promise=client.initializeBusinessProfile(tenantId,body);sync();try{await promise;if(at===generation.current)sync();}catch(error){if(at===generation.current){setError(error instanceof BusinessOnboardingError?error.message:'Business type initialization remains unverified. Keep the original attempt.');sync();}}finally{if(at===generation.current)inFlight.current=false;}}
 if(state.phase==='ready'&&!uninitialized)return null;
 return <section aria-label="Initialize existing business" style={{minWidth:0,overflowWrap:'anywhere'}}><h3>Initialize this existing business</h3><p>Business: {tenantId}. Assign its permanent business type once. This does not create another business or configure services, prices, hours or payments.</p><p>Attempt memory stays in this signed-in client. If an earlier initialization receipt was lost, keep its original key and type; do not start a replacement attempt after reloading. A current profile read does not prove which operation committed.</p>
 {state.phase==='ready'&&uninitialized&&<form onSubmit={prepare}><fieldset className="form-stack" disabled={blocked||!!reviewed} style={{minWidth:0}}><label>Existing business permanent type<select required value={type} onChange={event=>setType(event.target.value)}><option value="">Choose a permanent type</option>{BusinessType.options.map(value=><option key={value} value={value}>{names[value]}</option>)}</select></label><p>This type cannot be changed here after initialization. Review it before confirming.</p><button ref={reviewRef} type="submit">Review existing business type</button></fieldset></form>}
 {reviewed&&<div role="dialog" aria-modal="true" aria-label="Review existing permanent business type" onKeyDown={event=>{if(event.key==='Escape'){event.preventDefault();close();}if(event.key==='Tab'){event.preventDefault();const buttons=event.currentTarget.querySelectorAll<HTMLButtonElement>('button');(document.activeElement===buttons[0]?buttons[1]:buttons[0])?.focus();}}}><h4>Review permanent business type</h4><p>Existing business: {tenantId}</p><p>Permanent type: {names[reviewed.body.businessType]}</p><p>Confirm this one-time initialization for this business. It is permanent, not a type toggle. Use staging test data only.</p><button ref={cancelRef} type="button" onClick={close}>Cancel initialization</button><button type="button" disabled={blocked} onClick={()=>void send(reviewed.body)}>Confirm permanent business type</button></div>}
 {(state.phase==='checking'||state.phase==='initializing'||state.phase==='unknown'||state.phase==='initialized')&&<p>Frozen initialization key: {state.attempt.idempotencyKey}; permanent type: {names[state.attempt.businessType]}.</p>}
 {pending&&<><p role="status">{state.phase==='checking'?'Checking fresh owner and uninitialized business evidence...':'Initializing the reviewed permanent business type...'}</p><button type="button" onClick={sync}>Check this session's initialization state</button></>}
 {state.phase==='unknown'&&<><p role="alert">Initialization status is unverified. It may have succeeded. Keep the frozen key and type; do not start a different attempt. A profile read cannot verify which operation committed.</p><button type="button" disabled={blocked} onClick={()=>void send(state.attempt)}>Retry this same initialization</button></>}
 {state.phase==='blocked'&&<p role="alert">A frozen initialization belongs to another signed-in account. Sign in with its original account to verify it. Other owner writes remain locked.</p>}
 {state.phase==='initialized'&&<p role="status">Permanent business type receipt verified for this existing business: {names[state.profile.businessType]}. Services and scheduling remain separate setup actions.</p>}
 {state.phase==='unavailable'&&<p role="status">Existing-business initialization is unavailable. The server staging capability must be enabled; no initialized receipt is confirmed.</p>}
 {error&&<p role="alert">{error}</p>}
 </section>;
}
