import {render,screen,fireEvent,waitFor,cleanup} from '@testing-library/react';
import {afterEach,expect,it,vi} from 'vitest';
import {createRuntimeClient,PaidJourneyDraftError,type PaidJourneyCustomerFieldDraftState,type PaidJourneyCustomerFieldOwnerDraft} from '@lumin/runtime-client';
import {ConnectedJourneyCustomerFieldDraft,type JourneyCustomerFieldDraftClient} from './ConnectedJourneyCustomerFieldDraft';
const tenant='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',flow='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',service='cccccccc-cccc-4ccc-8ccc-cccccccccccc',other='dddddddd-dddd-4ddd-8ddd-dddddddddddd';
const profile={schemaVersion:1 as const,tenantId:tenant,businessType:'HOUSEKEEPING' as const,templateVersion:1 as const};
const form={name:'Stored questions',presentation:{accentColor:'#0e7490' as const,layout:'compact' as const},journey:{schemaVersion:1 as const,stages:(['service','options','schedule','information','review_payment','confirmation'] as const).map(kind=>({id:kind,kind,label:kind,enabled:kind!=='options'}))},customerFields:[{id:'custom_gate',kind:'text' as const,label:'Gate',required:false,maxLength:100}],fieldBindings:[{fieldId:'custom_gate',stageId:'information'}]};
const draft:PaidJourneyCustomerFieldOwnerDraft={schemaVersion:2,tenantId:tenant,flowId:flow,serviceId:service,revision:2,form};
const props={tenantId:tenant,role:'BUSINESS_OWNER',staging:true,services:[{id:service,tenant_id:tenant,name:'Cleaning',currency:'USD',duration_minutes:60,base_price:12500,active:true}],catalogLoading:false};
afterEach(()=>{cleanup();sessionStorage.clear();Object.defineProperty(navigator,'clipboard',{configurable:true,value:undefined});});
function fixture(){let auth=1,state:PaidJourneyCustomerFieldDraftState={phase:'ready'},global=false;const client:JourneyCustomerFieldDraftClient={authContextRevision:()=>auth,simpleOfferLocked:()=>global||['saving','unverified'].includes(state.phase),businessProfile:vi.fn(async()=>({status:'initialized' as const,profile})),paidJourneyCustomerFieldDraftState:()=>state,loadPaidJourneyCustomerFieldDraft:vi.fn(async()=>{state={phase:'loaded',flowId:flow,revision:2,draft};return draft;}),savePaidJourneyCustomerFieldDraft:vi.fn(async(_tenant,id,input)=>{state={phase:'saved',flowId:id,revision:input.expectedRevision+1};return{schemaVersion:2 as const,tenantId:tenant,flowId:id,revision:input.expectedRevision+1};})};return {client,changeAuth:()=>auth++,setState:(value:PaidJourneyCustomerFieldDraftState)=>state=value,globalLock:()=>global=true};}
async function open(){fireEvent.click(screen.getByRole('button',{name:'Check customer questions editor'}));await screen.findByRole('form',{name:'Save conditional journey draft'});}
function edit(){fireEvent.change(screen.getByLabelText('Customer questions service'),{target:{value:service}});fireEvent.change(screen.getByLabelText('Customer questions form name'),{target:{value:'New questions'}});}
async function load(){fireEvent.change(screen.getByLabelText('Customer questions draft ID'),{target:{value:flow}});fireEvent.click(screen.getByRole('button',{name:'Reload customer questions draft'}));await screen.findByText('Loaded conditional journey revision 2.');}
it.each([{role:'BUSINESS_STAFF'},{role:undefined},{staging:false},{tenantId:'bad'}])('does not expose authoring for ineligible context %j',extra=>{const {client}=fixture();render(<ConnectedJourneyCustomerFieldDraft {...props} {...extra} client={client}/>);expect(screen.queryByRole('button')).toBeNull();expect(client.businessProfile).not.toHaveBeenCalled();});
it('requires an explicit profile check and never autosaves, autoloads or publishes',async()=>{const {client}=fixture();render(<ConnectedJourneyCustomerFieldDraft {...props} client={client}/>);expect(screen.queryByLabelText('Customer questions form name')).toBeNull();expect(client.businessProfile).not.toHaveBeenCalled();await open();expect(client.businessProfile).toHaveBeenCalledWith(tenant);expect(client.savePaidJourneyCustomerFieldDraft).not.toHaveBeenCalled();expect(client.loadPaidJourneyCustomerFieldDraft).not.toHaveBeenCalled();expect(screen.getByText(/Publishing and independent hosted checkout/)).toBeVisible();expect(screen.queryByRole('link')).toBeNull();});
it.each(['foreign','rental','malformed'] as const)('rejects %s profile before authoring',async kind=>{const {client}=fixture();vi.mocked(client.businessProfile).mockResolvedValue({status:'initialized',profile:kind==='foreign'?{...profile,tenantId:other}:kind==='rental'?{...profile,businessType:'VEHICLE_RENTAL'}:{...profile,secret:'private'}} as never);render(<ConnectedJourneyCustomerFieldDraft {...props} client={client}/>);fireEvent.click(screen.getByRole('button',{name:'Check customer questions editor'}));await screen.findByRole('alert');expect(screen.queryByLabelText('Customer questions form name')).toBeNull();expect(client.savePaidJourneyCustomerFieldDraft).not.toHaveBeenCalled();expect(document.body.textContent).not.toContain('private');});
it('saves dedicated conditional fields, design and exact stage bindings with only a browser locator',async()=>{const {client}=fixture();render(<ConnectedJourneyCustomerFieldDraft {...props} client={client}/>);await open();edit();fireEvent.click(screen.getByRole('button',{name:'Add customer text field'}));fireEvent.change(screen.getByLabelText('Field 1 label'),{target:{value:'Access question'}});fireEvent.click(screen.getByLabelText('Field 1 required'));fireEvent.change(screen.getByLabelText('Field 1 maximum length'),{target:{value:'80'}});fireEvent.click(screen.getByRole('button',{name:'Add customer text field'}));fireEvent.change(screen.getByLabelText('Field 2 show when'),{target:{value:'custom_field_1'}});fireEvent.change(screen.getByLabelText('Field 2 condition value'),{target:{value:'yes'}});fireEvent.change(screen.getByLabelText('Customer questions accent'),{target:{value:'#0e7490'}});fireEvent.change(screen.getByLabelText('Customer questions layout'),{target:{value:'compact'}});expect(client.savePaidJourneyCustomerFieldDraft).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Save customer questions draft'}));await screen.findByText(/Saved conditional journey revision 1/);const [t,id,input]=vi.mocked(client.savePaidJourneyCustomerFieldDraft).mock.calls[0]!;expect(t).toBe(tenant);expect(id).toMatch(/^[0-9a-f-]{36}$/);expect(id).not.toBe(flow);expect(input).toMatchObject({schemaVersion:2,expectedRevision:0,serviceId:service,form:{name:'New questions',presentation:{accentColor:'#0e7490',layout:'compact'},customerFields:[{id:'custom_field_1',label:'Access question',required:true,maxLength:80},{id:'custom_field_2',when:{fieldId:'custom_field_1',equals:'yes'}}],fieldBindings:[{fieldId:'custom_field_1',stageId:'information'},{fieldId:'custom_field_2',stageId:'information'}]}});expect(Object.keys(input).sort()).toEqual(['expectedRevision','form','schemaVersion','serviceId']);expect(sessionStorage.length).toBe(1);expect(sessionStorage.getItem('lumin.journey-fields:'+tenant)).toBe(id);expect(JSON.stringify(sessionStorage)).not.toContain('Access question');});
it('adds a real information step with a bound field and persists valid field order',async()=>{const {client}=fixture();render(<ConnectedJourneyCustomerFieldDraft {...props} client={client}/>);await open();edit();fireEvent.click(screen.getByRole('button',{name:'Add customer text field'}));fireEvent.click(screen.getByRole('button',{name:'Add customer information step'}));expect(screen.getByLabelText('Field 2 step')).toHaveValue('informational_1');fireEvent.change(screen.getByLabelText('Field 2 step'),{target:{value:'information'}});fireEvent.click(screen.getByLabelText('Show Additional information 1 step'));fireEvent.click(screen.getByRole('button',{name:'Move field 2 earlier'}));fireEvent.click(screen.getByRole('button',{name:'Save customer questions draft'}));await screen.findByText(/Saved conditional journey revision 1/);const input=vi.mocked(client.savePaidJourneyCustomerFieldDraft).mock.calls[0]![2];expect(input.form.customerFields.map(f=>f.id)).toEqual(['custom_field_2','custom_field_1']);expect(input.form.fieldBindings.map(b=>b.fieldId)).toEqual(['custom_field_2','custom_field_1']);});
it('prevents dependent field reorder/removal from silently breaking the condition',async()=>{const {client}=fixture();render(<ConnectedJourneyCustomerFieldDraft {...props} client={client}/>);await open();edit();fireEvent.click(screen.getByRole('button',{name:'Add customer text field'}));fireEvent.click(screen.getByRole('button',{name:'Add customer text field'}));fireEvent.change(screen.getByLabelText('Field 2 show when'),{target:{value:'custom_field_1'}});expect(screen.getByRole('button',{name:'Remove field 1'})).toBeDisabled();expect(screen.getByRole('button',{name:'Move field 2 earlier'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'Move field 2 earlier'}));expect(screen.getByLabelText('Field 2 show when')).toHaveValue('custom_field_1');expect(client.savePaidJourneyCustomerFieldDraft).not.toHaveBeenCalled();});
it('disables saves for invalid field length or backwards stage bindings',async()=>{const {client}=fixture();render(<ConnectedJourneyCustomerFieldDraft {...props} client={client}/>);await open();edit();fireEvent.click(screen.getByRole('button',{name:'Add customer text field'}));fireEvent.change(screen.getByLabelText('Field 1 maximum length'),{target:{value:'0'}});expect(screen.getByRole('button',{name:'Save customer questions draft'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'Save customer questions draft'}));expect(client.savePaidJourneyCustomerFieldDraft).not.toHaveBeenCalled();fireEvent.change(screen.getByLabelText('Field 1 maximum length'),{target:{value:'100'}});fireEvent.click(screen.getByRole('button',{name:'Add customer information step'}));fireEvent.change(screen.getByLabelText('Field 1 step'),{target:{value:'informational_1'}});fireEvent.change(screen.getByLabelText('Field 2 step'),{target:{value:'information'}});expect(screen.getByRole('button',{name:'Save customer questions draft'})).toBeDisabled();});
it('requires dirty reload and discard reviews and retains edits when cancelled',async()=>{const {client}=fixture();render(<ConnectedJourneyCustomerFieldDraft {...props} client={client}/>);await open();await load();fireEvent.change(screen.getByLabelText('Field 1 label'),{target:{value:'Private local edit'}});fireEvent.click(screen.getByRole('button',{name:'Reload customer questions draft'}));expect(client.loadPaidJourneyCustomerFieldDraft).toHaveBeenCalledTimes(1);fireEvent.click(screen.getByRole('button',{name:'Keep customer questions edits'}));expect(screen.getByLabelText('Field 1 label')).toHaveValue('Private local edit');fireEvent.click(screen.getByRole('button',{name:'Discard customer questions edits'}));fireEvent.click(screen.getByRole('button',{name:'Discard edits and restore saved questions'}));expect(screen.getByLabelText('Field 1 label')).toHaveValue('Gate');fireEvent.change(screen.getByLabelText('Customer questions form name'),{target:{value:'Edited'}});fireEvent.click(screen.getByRole('button',{name:'Reload customer questions draft'}));fireEvent.click(screen.getByRole('button',{name:'Discard edits and reload customer questions'}));await waitFor(()=>expect(client.loadPaidJourneyCustomerFieldDraft).toHaveBeenCalledTimes(2));expect(client.savePaidJourneyCustomerFieldDraft).not.toHaveBeenCalled();});
it('uses stored locator after remount without storing or autoloading form content',async()=>{const {client}=fixture();const view=render(<ConnectedJourneyCustomerFieldDraft {...props} client={client}/>);await open();await load();expect(sessionStorage.getItem('lumin.journey-fields:'+tenant)).toBe(flow);view.unmount();render(<ConnectedJourneyCustomerFieldDraft {...props} client={client}/>);expect(client.loadPaidJourneyCustomerFieldDraft).toHaveBeenCalledTimes(1);await open();expect(screen.getByLabelText('Customer questions draft ID')).toHaveValue(flow);expect(screen.getByLabelText('Customer questions form name')).toHaveValue('');expect(screen.getByLabelText('Customer questions draft ID')).not.toHaveValue(form.name);});
it.each(['Mobile','Tablet','Desktop'] as const)('shows %s read-only preview without customer API calls',async size=>{const {client}=fixture();render(<ConnectedJourneyCustomerFieldDraft {...props} client={client}/>);await open();await load();fireEvent.click(screen.getByRole('button',{name:size+' customer questions preview'}));expect(screen.getByLabelText(size+' customer questions preview frame')).toHaveStyle({maxWidth:size==='Mobile'?'375px':size==='Tablet'?'768px':'1100px'});expect(screen.getByRole('button',{name:size+' customer questions preview'})).toHaveAttribute('aria-pressed','true');expect(client.savePaidJourneyCustomerFieldDraft).not.toHaveBeenCalled();});
it('retains dirty CAS revision and honors current central conflict/global writer locks',async()=>{const {client,setState,globalLock}=fixture();render(<ConnectedJourneyCustomerFieldDraft {...props} client={client}/>);await open();await load();fireEvent.change(screen.getByLabelText('Field 1 label'),{target:{value:'Edit'}});setState({phase:'conflict',flowId:flow});fireEvent.submit(screen.getByRole('form',{name:'Save conditional journey draft'}));expect(client.savePaidJourneyCustomerFieldDraft).not.toHaveBeenCalled();globalLock();fireEvent.change(screen.getByLabelText('Customer questions draft ID'),{target:{value:other}});expect(screen.getByLabelText('Customer questions draft ID')).toHaveValue(flow);expect(client.loadPaidJourneyCustomerFieldDraft).toHaveBeenCalledTimes(1);});
it('blocks duplicate pending dispatch and freezes every replacement writer on unknown save',async()=>{const {client,setState}=fixture();let reject!:(error:Error)=>void;vi.mocked(client.savePaidJourneyCustomerFieldDraft).mockImplementation(async(_t,id)=>{setState({phase:'saving',flowId:id});return new Promise((_resolve,r)=>reject=r);});render(<ConnectedJourneyCustomerFieldDraft {...props} client={client}/>);await open();edit();const formElement=screen.getByRole('form',{name:'Save conditional journey draft'});fireEvent.submit(formElement);fireEvent.submit(formElement);expect(client.savePaidJourneyCustomerFieldDraft).toHaveBeenCalledTimes(1);reject(new PaidJourneyDraftError('unknown','private transport secret'));await screen.findByText(/Conditional save outcome is unverified/);expect(screen.getByRole('button',{name:'Save customer questions draft'})).toBeDisabled();expect(screen.getByRole('button',{name:'Start new customer questions draft'})).toBeDisabled();expect(screen.getByLabelText('Customer questions draft ID')).toBeDisabled();expect(document.body.textContent).not.toContain('private transport secret');});
it('hides private edits and rejects late saved receipt after same-owner auth A-B-A',async()=>{const {client,changeAuth}=fixture();let finish!:(value:never)=>void;vi.mocked(client.savePaidJourneyCustomerFieldDraft).mockImplementation(async()=>new Promise(resolve=>finish=resolve));const view=render(<ConnectedJourneyCustomerFieldDraft {...props} client={client}/>);await open();edit();fireEvent.change(screen.getByLabelText('Customer questions form name'),{target:{value:'Private owner draft'}});fireEvent.submit(screen.getByRole('form',{name:'Save conditional journey draft'}));const id=vi.mocked(client.savePaidJourneyCustomerFieldDraft).mock.calls[0]![1];changeAuth();view.rerender(<ConnectedJourneyCustomerFieldDraft {...props} client={client}/>);changeAuth();view.rerender(<ConnectedJourneyCustomerFieldDraft {...props} client={client}/>);finish({schemaVersion:2,tenantId:tenant,flowId:id,revision:1} as never);await new Promise(r=>setTimeout(r,0));expect(document.body.textContent).not.toContain('Private owner draft');expect(screen.queryByText(/Saved conditional journey revision/)).toBeNull();expect(screen.getByRole('button',{name:'Check customer questions editor'})).toBeDisabled();});
it('keeps dispatched uncertainty across client replacement and clears private editor data',async()=>{const first=fixture(),second=fixture();vi.mocked(first.client.savePaidJourneyCustomerFieldDraft).mockImplementation(async()=>new Promise(()=>{}));const view=render(<ConnectedJourneyCustomerFieldDraft {...props} client={first.client}/>);await open();edit();fireEvent.submit(screen.getByRole('form',{name:'Save conditional journey draft'}));view.rerender(<ConnectedJourneyCustomerFieldDraft {...props} client={second.client}/>);await waitFor(()=>expect(screen.queryByLabelText('Customer questions form name')).toBeNull());expect(screen.getByRole('button',{name:'Check customer questions editor'})).toBeDisabled();expect(second.client.savePaidJourneyCustomerFieldDraft).not.toHaveBeenCalled();});
it.each([{...draft,tenantId:other},{...draft,form:{...form,price:1}},{...draft,serviceId:other},{...draft,privateToken:'secret'}])('rejects malformed or foreign read without displaying it',async value=>{const {client}=fixture();vi.mocked(client.loadPaidJourneyCustomerFieldDraft).mockResolvedValue(value as never);render(<ConnectedJourneyCustomerFieldDraft {...props} client={client}/>);await open();fireEvent.change(screen.getByLabelText('Customer questions draft ID'),{target:{value:flow}});fireEvent.click(screen.getByRole('button',{name:'Reload customer questions draft'}));await screen.findByText(/Stored conditional journey could not be verified/);expect(screen.getByLabelText('Customer questions form name')).toHaveValue('');expect(document.body.textContent).not.toContain('secret');});
async function actualClient(mode:'success'|'unknown'='success'){let saved=draft;const json=(data:unknown)=>new Response(JSON.stringify(data),{status:200});const transport=vi.fn<typeof fetch>(async(url,request)=>{const path=String(url);if(path.includes('/auth/v1/token'))return json({access_token:'synthetic-token'});if(path.includes('/auth/v1/user'))return json({id:other});if(path.includes('/api/business-profile?'))return json({ok:true,data:profile});if(path.includes('/api/paid-journey-customer-field-flows/')){const id=path.split('/api/paid-journey-customer-field-flows/')[1]!.split('/')[0]!;if(request?.method==='POST'){if(mode==='unknown')throw Error('private transport');const body=JSON.parse(String(request.body));saved={schemaVersion:2,tenantId:tenant,flowId:id,serviceId:body.serviceId,revision:body.expectedRevision+1,form:body.form};return json({ok:true,data:{schemaVersion:2,tenantId:tenant,flowId:id,revision:saved.revision}});}return json({ok:true,data:saved});}throw Error('unexpected path');});const client=createRuntimeClient({url:'https://example.supabase.co',publishableKey:'sb_publishable_synthetic',tenantId:tenant,bookingApiOrigin:'https://api.example.test'},transport);await client.signIn('owner@example.test','synthetic');return {client,transport};}
it('runs actual SDK strict CAS transport then explicitly reloads persisted form and bindings',async()=>{const {client,transport}=await actualClient();render(<ConnectedJourneyCustomerFieldDraft {...props} client={client}/>);await open();edit();fireEvent.click(screen.getByRole('button',{name:'Add customer text field'}));fireEvent.click(screen.getByRole('button',{name:'Save customer questions draft'}));await screen.findByText(/Saved conditional journey revision 1/);const request=transport.mock.calls.find(([,r])=>r?.method==='POST'&&String(r.body).includes('fieldBindings'))!;expect(request[1]).toMatchObject({credentials:'omit',cache:'no-store',redirect:'error',referrerPolicy:'no-referrer'});expect(new Headers(request[1]?.headers).has('Origin')).toBe(false);expect(JSON.parse(String(request[1]?.body))).toMatchObject({schemaVersion:2,expectedRevision:0,serviceId:service,form:{name:'New questions',fieldBindings:[{fieldId:'custom_field_1',stageId:'information'}]}});fireEvent.click(screen.getByRole('button',{name:'Reload customer questions draft'}));await screen.findByText('Loaded conditional journey revision 1.');expect(screen.getByLabelText('Field 1 label')).toHaveValue('Additional information 1');expect(client.paidJourneyCustomerFieldDraftState(tenant).phase).toBe('loaded');expect(document.body.textContent).not.toContain('synthetic-token');});
it('actual SDK unknown save remains locked after remount without a second POST or read',async()=>{const {client,transport}=await actualClient('unknown');const view=render(<ConnectedJourneyCustomerFieldDraft {...props} client={client}/>);await open();edit();fireEvent.click(screen.getByRole('button',{name:'Save customer questions draft'}));await screen.findByText(/Conditional save outcome is unverified/);view.unmount();render(<ConnectedJourneyCustomerFieldDraft {...props} client={client}/>);expect(screen.getByRole('button',{name:'Check customer questions editor'})).toBeDisabled();expect(client.paidJourneyCustomerFieldDraftState(tenant).phase).toBe('unverified');expect(transport.mock.calls.filter(([url])=>String(url).includes('/api/paid-journey-customer-field-flows/'))).toHaveLength(1);});

it('reorders fields across information steps while preserving valid forward binding slots',async()=>{const {client}=fixture();render(<ConnectedJourneyCustomerFieldDraft {...props} client={client}/>);await open();edit();fireEvent.click(screen.getByRole('button',{name:'Add customer text field'}));fireEvent.click(screen.getByRole('button',{name:'Add customer information step'}));fireEvent.click(screen.getByRole('button',{name:'Move field 2 earlier'}));expect(screen.getByLabelText('Field 1 step')).toHaveValue('information');expect(screen.getByLabelText('Field 2 step')).toHaveValue('informational_1');expect(screen.getByRole('button',{name:'Save customer questions draft'})).toBeEnabled();fireEvent.click(screen.getByRole('button',{name:'Save customer questions draft'}));await screen.findByText(/Saved conditional journey revision 1/);const saved=vi.mocked(client.savePaidJourneyCustomerFieldDraft).mock.calls[0]![2];expect(saved.form.customerFields.map(f=>f.id)).toEqual(['custom_field_2','custom_field_1']);expect(saved.form.fieldBindings).toEqual([{fieldId:'custom_field_2',stageId:'information'},{fieldId:'custom_field_1',stageId:'informational_1'}]);});
it.each(['foreign','revision','schema','extra'] as const)('retains local uncertainty for %s save receipt even if a typed client accepts it',async kind=>{const {client}=fixture();vi.mocked(client.savePaidJourneyCustomerFieldDraft).mockImplementation(async(_t,id,input)=>({schemaVersion:kind==='schema'?1:2,tenantId:kind==='foreign'?other:tenant,flowId:id,revision:input.expectedRevision+(kind==='revision'?2:1),...(kind==='extra'?{privateToken:'secret'}:{})}) as never);render(<ConnectedJourneyCustomerFieldDraft {...props} client={client}/>);await open();edit();fireEvent.click(screen.getByRole('button',{name:'Save customer questions draft'}));await screen.findByText(/Conditional save outcome is unverified/);expect(screen.getByRole('button',{name:'Save customer questions draft'})).toBeDisabled();expect(screen.getByLabelText('Customer questions form name')).toHaveValue('New questions');expect(document.body.textContent).not.toContain('secret');expect(screen.queryByText(/Saved conditional journey revision/)).toBeNull();});
it('retains a local conflict until explicit reload even when a typed client omits central conflict state',async()=>{const {client}=fixture();vi.mocked(client.savePaidJourneyCustomerFieldDraft).mockRejectedValue(new PaidJourneyDraftError('conflict','private stale detail'));render(<ConnectedJourneyCustomerFieldDraft {...props} client={client}/>);await open();await load();fireEvent.change(screen.getByLabelText('Field 1 label'),{target:{value:'Retained stale edit'}});fireEvent.submit(screen.getByRole('form',{name:'Save conditional journey draft'}));await screen.findByText(/The stored draft changed/);expect(screen.getByRole('button',{name:'Save customer questions draft'})).toBeDisabled();fireEvent.submit(screen.getByRole('form',{name:'Save conditional journey draft'}));expect(client.savePaidJourneyCustomerFieldDraft).toHaveBeenCalledTimes(1);expect(screen.getByLabelText('Field 1 label')).toHaveValue('Retained stale edit');expect(document.body.textContent).not.toContain('private stale detail');});
it('discards late profile and draft reads across tenant replacement',async()=>{const {client}=fixture();let finish!:(value:never)=>void;vi.mocked(client.loadPaidJourneyCustomerFieldDraft).mockImplementation(async()=>new Promise(resolve=>finish=resolve));const view=render(<ConnectedJourneyCustomerFieldDraft {...props} client={client}/>);await open();fireEvent.change(screen.getByLabelText('Customer questions draft ID'),{target:{value:flow}});fireEvent.click(screen.getByRole('button',{name:'Reload customer questions draft'}));view.rerender(<ConnectedJourneyCustomerFieldDraft {...props} tenantId={other} client={client}/>);finish({...draft,form:{...form,name:'Private old tenant'}} as never);await new Promise(r=>setTimeout(r,0));expect(document.body.textContent).not.toContain('Private old tenant');expect(screen.queryByLabelText('Customer questions form name')).toBeNull();expect(client.savePaidJourneyCustomerFieldDraft).not.toHaveBeenCalled();});
const version='eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',installation='ffffffff-ffff-4fff-8fff-ffffffffffff',checkoutOrigin='https://checkout.example.test';
const published=()=>({schemaVersion:2 as const,tenantId:tenant,flowId:flow,draftRevision:2,versionId:version,installationId:installation,renderSchemaVersion:9 as const,replayed:false});
const ownerPublication=()=>{const {replayed:_,...metadata}=published();return {...metadata,allowedOrigins:[checkoutOrigin],render:{versionId:version,renderSchemaVersion:9 as const,submissionMode:'paid_journey_customer_field_request' as const,paymentMode:'staging_mock' as const,simulated:true as const,service:{id:service,name:'Cleaning',durationMinutes:60,price:{amount:12500,currency:'USD'}},form}};};
function publicationFixture(){const result=fixture();result.client.publishPaidJourneyCustomerFieldDraft=vi.fn(async()=>published());result.client.readPaidJourneyCustomerFieldOwnerPublication=vi.fn(async()=>ownerPublication());result.client.paidJourneyCustomerFieldPublicationState=()=>({phase:'ready'});return result;}
async function reviewPublication(){fireEvent.change(screen.getByLabelText('Approved customer questions Checkout origins'),{target:{value:checkoutOrigin}});fireEvent.click(screen.getByRole('button',{name:'Review customer questions publication'}));await screen.findByRole('region',{name:'Review customer questions publication'});}
it('requires loaded clean revision, explicit review and one confirm before publication',async()=>{const {client}=publicationFixture();render(<ConnectedJourneyCustomerFieldDraft {...props} client={client}/>);await open();expect(screen.getByRole('button',{name:'Review customer questions publication'})).toBeDisabled();await load();await reviewPublication();expect(client.publishPaidJourneyCustomerFieldDraft).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Cancel customer questions publication'}));expect(client.publishPaidJourneyCustomerFieldDraft).not.toHaveBeenCalled();await reviewPublication();fireEvent.click(screen.getByRole('button',{name:'Confirm customer questions publication'}));await screen.findByText(/Published immutable customer questions revision 2/);expect(client.publishPaidJourneyCustomerFieldDraft).toHaveBeenCalledExactlyOnceWith(tenant,flow,{schemaVersion:2,expectedDraftRevision:2,allowedOrigins:[checkoutOrigin]});expect(screen.queryByRole('link')).toBeNull();expect(document.body.textContent).toContain('Booking submission is not connected yet');});
it.each(['*','http://localhost:3000',checkoutOrigin+'/',checkoutOrigin+','+checkoutOrigin])('rejects unapproved origin shape %s without dispatch',async origin=>{const {client}=publicationFixture();render(<ConnectedJourneyCustomerFieldDraft {...props} client={client}/>);await open();await load();fireEvent.change(screen.getByLabelText('Approved customer questions Checkout origins'),{target:{value:origin}});fireEvent.click(screen.getByRole('button',{name:'Review customer questions publication'}));await screen.findByText(/Enter unique exact HTTPS/);expect(client.publishPaidJourneyCustomerFieldDraft).not.toHaveBeenCalled();});
it('editing after review removes authorization and requires a fresh saved revision',async()=>{const {client}=publicationFixture();render(<ConnectedJourneyCustomerFieldDraft {...props} client={client}/>);await open();await load();await reviewPublication();fireEvent.change(screen.getByLabelText('Field 1 label'),{target:{value:'Changed question'}});expect(screen.queryByRole('button',{name:'Confirm customer questions publication'})).toBeNull();expect(screen.getByRole('button',{name:'Review customer questions publication'})).toBeDisabled();expect(client.publishPaidJourneyCustomerFieldDraft).not.toHaveBeenCalled();});
it('owner snapshot is immutable evidence and never replaces editable fields',async()=>{const {client}=publicationFixture();client.readPaidJourneyCustomerFieldOwnerPublication=vi.fn(async()=>({...ownerPublication(),render:{...ownerPublication().render,form:{...form,name:'Published original'}}}));render(<ConnectedJourneyCustomerFieldDraft {...props} client={client}/>);await open();await load();fireEvent.change(screen.getByLabelText('Customer questions form name'),{target:{value:'Unsaved local name'}});fireEvent.click(screen.getByRole('button',{name:'Read current customer questions publication'}));await screen.findByRole('region',{name:'Immutable customer questions publication'});expect(screen.getByLabelText('Customer questions form name')).toHaveValue('Unsaved local name');expect(screen.getByText('Published original')).toBeVisible();expect(client.publishPaidJourneyCustomerFieldDraft).not.toHaveBeenCalled();});
it('unverified publication remains locally fenced after evidence read and client replacement',async()=>{const first=publicationFixture(),second=publicationFixture();first.client.publishPaidJourneyCustomerFieldDraft=vi.fn(async()=>{throw Error('private bearer')});const view=render(<ConnectedJourneyCustomerFieldDraft {...props} client={first.client}/>);await open();await load();await reviewPublication();fireEvent.click(screen.getByRole('button',{name:'Confirm customer questions publication'}));await screen.findByText(/Publication outcome is unverified/);fireEvent.click(screen.getByRole('button',{name:'Read current customer questions publication'}));await screen.findByRole('region',{name:'Immutable customer questions publication'});expect(screen.getByRole('button',{name:'Review customer questions publication'})).toBeDisabled();view.rerender(<ConnectedJourneyCustomerFieldDraft {...props} client={second.client}/>);await waitFor(()=>expect(screen.queryByLabelText('Customer questions form name')).toBeNull());expect(screen.getByRole('button',{name:'Check customer questions editor'})).toBeDisabled();expect(document.body.textContent).not.toContain('private bearer');});
it('rejects foreign owner publication and never reveals its form',async()=>{const {client}=publicationFixture();client.readPaidJourneyCustomerFieldOwnerPublication=vi.fn(async()=>({...ownerPublication(),tenantId:other,render:{...ownerPublication().render,form:{...form,name:'Foreign private form'}}}));render(<ConnectedJourneyCustomerFieldDraft {...props} client={client}/>);await open();await load();fireEvent.click(screen.getByRole('button',{name:'Read current customer questions publication'}));await screen.findByText(/current publication could not be verified/);expect(document.body.textContent).not.toContain('Foreign private form');});
it('actual SDK delayed publication JSON across A-B-A keeps unknown and blocks second write',async()=>{let actor=other,finish!:(v:unknown)=>void,started!:()=>void;const began=new Promise<void>(resolve=>started=resolve);const json=(v:unknown)=>new Response(JSON.stringify(v),{status:200});let publishes=0;const transport=vi.fn<typeof fetch>(async(url,request)=>{const path=String(url);if(path.includes('/auth/v1/token'))return json({access_token:'synthetic'});if(path.endsWith('/auth/v1/user'))return json({id:actor});if(path.includes('/api/business-profile?'))return json({ok:true,data:profile});if(path.includes('/publish?')){publishes++;const response=json({ok:true,data:published()});vi.spyOn(response,'json').mockImplementation(()=>new Promise(resolve=>{finish=resolve;started();}));return response;}if(path.includes('/draft?'))return json({ok:true,data:draft});if(path.includes('/publication?'))return json({ok:true,data:ownerPublication()});throw Error('Unexpected path');});const client=createRuntimeClient({url:'https://example.supabase.co',publishableKey:'sb_publishable_synthetic',tenantId:tenant,bookingApiOrigin:'https://api.example.test'},transport);await client.signIn('owner@example.test','synthetic');const view=render(<ConnectedJourneyCustomerFieldDraft {...props} client={client}/>);await open();await load();await reviewPublication();fireEvent.click(screen.getByRole('button',{name:'Confirm customer questions publication'}));await began;for(const selected of [service,other]){actor=selected;await client.signIn('owner@example.test','synthetic');view.rerender(<ConnectedJourneyCustomerFieldDraft {...props} client={client}/>);}finish({ok:true,data:published()});await waitFor(()=>expect(client.paidJourneyCustomerFieldPublicationState(tenant).phase).toBe('unknown'));expect(screen.queryByLabelText('Customer questions form name')).toBeNull();expect(screen.getByRole('button',{name:'Check customer questions editor'})).toBeDisabled();expect(publishes).toBe(1);expect(screen.queryByText(/Published immutable/)).toBeNull();});
it('actual SDK stale publication CAS locks writers until explicit same-draft reload',async()=>{const {client,transport}=await actualClient();render(<ConnectedJourneyCustomerFieldDraft {...props} client={client}/>);await open();await load();await reviewPublication();transport.mockResolvedValueOnce(new Response(JSON.stringify({ok:false,code:'CONFLICT'}),{status:409}));fireEvent.click(screen.getByRole('button',{name:'Confirm customer questions publication'}));await screen.findByText(/Publication was not accepted/);expect(client.paidJourneyCustomerFieldPublicationState(tenant).phase).toBe('conflict');expect(screen.getByRole('button',{name:'Save customer questions draft'})).toBeDisabled();expect(screen.getByRole('button',{name:'Review customer questions publication'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'Reload rejected customer questions publication draft'}));await screen.findByText('Loaded conditional journey revision 2.');expect(client.paidJourneyCustomerFieldPublicationState(tenant).phase).toBe('ready');expect(screen.getByRole('button',{name:'Review customer questions publication'})).toBeEnabled();expect(transport.mock.calls.filter(([url,r])=>String(url).includes('/publish?')&&r?.method==='POST')).toHaveLength(1);});
it('malformed typed publication receipt retains local fence without a success claim',async()=>{const {client}=publicationFixture();client.publishPaidJourneyCustomerFieldDraft=vi.fn(async()=>({...published(),tenantId:other}) as never);render(<ConnectedJourneyCustomerFieldDraft {...props} client={client}/>);await open();await load();await reviewPublication();fireEvent.click(screen.getByRole('button',{name:'Confirm customer questions publication'}));await screen.findByText(/Publication outcome is unverified/);expect(screen.queryByText(/Published immutable customer questions/)).toBeNull();expect(screen.getByRole('button',{name:'Save customer questions draft'})).toBeDisabled();expect(client.publishPaidJourneyCustomerFieldDraft).toHaveBeenCalledTimes(1);});
it.each([{allowedOrigins:[checkoutOrigin+' ']},{allowedOrigins:[checkoutOrigin,checkoutOrigin]},{allowedOrigins:['*']}])('rejects malformed exact owner origin evidence %j',async ({allowedOrigins})=>{const {client}=publicationFixture();client.readPaidJourneyCustomerFieldOwnerPublication=vi.fn(async()=>({...ownerPublication(),allowedOrigins}));render(<ConnectedJourneyCustomerFieldDraft {...props} client={client}/>);await open();await load();fireEvent.click(screen.getByRole('button',{name:'Read current customer questions publication'}));await screen.findByText(/current publication could not be verified/);expect(screen.queryByRole('region',{name:'Immutable customer questions publication'})).toBeNull();});

it('maps strictly read V9 owner publication origins to the explicit read-only route',async()=>{const {client}=publicationFixture();render(<ConnectedJourneyCustomerFieldDraft {...props} client={client}/>);await open();await load();expect(screen.queryByRole('link')).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Read current customer questions publication'}));const link=await screen.findByRole('link',{name:'Open published form preview (staging) - '+checkoutOrigin});expect(link).toHaveAttribute('href',checkoutOrigin+'/checkout/journey-fields/flow/'+installation);expect(link).toHaveAttribute('rel','noopener noreferrer');expect(screen.getByText(/Scheduling, reservations, payments and confirmation are not connected/)).toBeVisible();expect(client.publishPaidJourneyCustomerFieldDraft).not.toHaveBeenCalled();});
it.each(['https://foreign.example/path','https://foreign.example?token=private','https://foreign.example#private'])('rejects non-origin installation redirects %s',async origin=>{const {client}=publicationFixture();client.readPaidJourneyCustomerFieldOwnerPublication=vi.fn(async()=>({...ownerPublication(),allowedOrigins:[origin]}));render(<ConnectedJourneyCustomerFieldDraft {...props} client={client}/>);await open();await load();fireEvent.click(screen.getByRole('button',{name:'Read current customer questions publication'}));await screen.findByText(/current publication could not be verified/);expect(screen.queryByRole('link')).toBeNull();});


it('offers verified published URLs for explicit copying without publishing or copying editable origins',async()=>{
 const {client}=publicationFixture();const secondOrigin='https://second.example.test';
 client.readPaidJourneyCustomerFieldOwnerPublication=vi.fn(async()=>({...ownerPublication(),allowedOrigins:[checkoutOrigin,secondOrigin]}));
 const write=vi.fn().mockResolvedValue(undefined);Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:write}});
 render(<ConnectedJourneyCustomerFieldDraft {...props} client={client}/>);await open();await load();
 expect(screen.queryByRole('button',{name:/Copy Published form URL/})).toBeNull();
 fireEvent.change(screen.getByLabelText('Approved customer questions Checkout origins'),{target:{value:'https://unsaved.example.test'}});
 fireEvent.click(screen.getByRole('button',{name:'Read current customer questions publication'}));
 const label='Published form URL (staging) - '+secondOrigin;
 const field=await screen.findByLabelText(label);expect(field).toHaveAttribute('readonly');
 expect(field).toHaveValue(secondOrigin+'/checkout/journey-fields/flow/'+installation);expect(write).not.toHaveBeenCalled();
 fireEvent.click(screen.getByRole('button',{name:'Copy '+label}));await screen.findByText('Copied '+label+'.');
 expect(write).toHaveBeenCalledExactlyOnceWith(secondOrigin+'/checkout/journey-fields/flow/'+installation);
 expect(client.publishPaidJourneyCustomerFieldDraft).not.toHaveBeenCalled();expect(client.savePaidJourneyCustomerFieldDraft).not.toHaveBeenCalled();
});
it('keeps a selectable published URL when clipboard permission is denied without reflecting browser errors',async()=>{
 const {client}=publicationFixture();const write=vi.fn().mockRejectedValue(Error('private clipboard detail'));
 Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:write}});
 render(<ConnectedJourneyCustomerFieldDraft {...props} client={client}/>);await open();await load();
 fireEvent.click(screen.getByRole('button',{name:'Read current customer questions publication'}));
 const label='Published form URL (staging) - '+checkoutOrigin;await screen.findByLabelText(label);
 fireEvent.click(screen.getByRole('button',{name:'Copy '+label}));await screen.findByText('Could not copy '+label+'. Select and copy it manually.');
 expect(screen.getByLabelText(label)).toHaveValue(checkoutOrigin+'/checkout/journey-fields/flow/'+installation);
 expect(document.body.textContent).not.toContain('private clipboard detail');
});
it('removes published copy controls and ignores an outstanding copy after business selection changes',async()=>{
 const {client}=publicationFixture();let finish!:()=>void;const write=vi.fn(()=>new Promise<void>(resolve=>{finish=resolve;}));
 Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:write}});
 const view=render(<ConnectedJourneyCustomerFieldDraft {...props} client={client}/>);await open();await load();
 fireEvent.click(screen.getByRole('button',{name:'Read current customer questions publication'}));
 const button=await screen.findByRole('button',{name:'Copy Published form URL (staging) - '+checkoutOrigin});fireEvent.click(button);
 view.rerender(<ConnectedJourneyCustomerFieldDraft {...props} tenantId={other} client={client}/>);
 await waitFor(()=>expect(screen.queryByRole('button',{name:/Copy Published form URL/})).toBeNull());finish();
 await waitFor(()=>expect(screen.queryByText(/^Copied Published form URL/)).toBeNull());expect(write).toHaveBeenCalledTimes(1);
});


it('previews V9 conditional branches locally without saving fictional answers or changing the draft',async()=>{
 const {client}=fixture();render(<ConnectedJourneyCustomerFieldDraft {...props} client={client}/>);await open();edit();
 fireEvent.click(screen.getByRole('button',{name:'Add customer text field'}));fireEvent.click(screen.getByRole('button',{name:'Add customer text field'}));
 fireEvent.change(screen.getByLabelText('Field 2 show when'),{target:{value:'custom_field_1'}});fireEvent.change(screen.getByLabelText('Field 2 condition value'),{target:{value:'yes'}});
 expect(screen.queryByRole('textbox',{name:'Preview value: Additional information 2'})).toBeNull();
 const source=screen.getByRole('textbox',{name:'Preview value: Additional information 1'});
 fireEvent.change(source,{target:{value:'yes'}});expect(screen.getByRole('textbox',{name:'Preview value: Additional information 2'})).toBeVisible();
 fireEvent.change(screen.getByRole('textbox',{name:'Preview value: Additional information 2'}),{target:{value:'Fictional branch value'}});
 expect(client.savePaidJourneyCustomerFieldDraft).not.toHaveBeenCalled();expect(JSON.stringify(sessionStorage)).not.toContain('Fictional');
 fireEvent.click(screen.getByRole('button',{name:'Reset preview scenario'}));expect(source).toHaveValue('');expect(screen.queryByRole('textbox',{name:'Preview value: Additional information 2'})).toBeNull();
 fireEvent.click(screen.getByRole('button',{name:'Save customer questions draft'}));await screen.findByText(/Saved conditional journey revision 1/);
 const saved=vi.mocked(client.savePaidJourneyCustomerFieldDraft).mock.calls[0]![2];expect(JSON.stringify(saved)).not.toContain('Fictional');expect(saved.form.customerFields[1]!.when).toEqual({fieldId:'custom_field_1',equals:'yes'});
});
it('resets the V9 scenario when journey definitions change and suppresses it for invalid step bindings',async()=>{
 const {client}=fixture();render(<ConnectedJourneyCustomerFieldDraft {...props} client={client}/>);await open();edit();fireEvent.click(screen.getByRole('button',{name:'Add customer text field'}));
 fireEvent.change(screen.getByRole('textbox',{name:'Preview value: Additional information 1'}),{target:{value:'Fictional'}});
 fireEvent.change(screen.getByLabelText('Customer questions form name'),{target:{value:'Updated draft name'}});
 expect(screen.getByRole('textbox',{name:'Preview value: Additional information 1'})).toHaveValue('');
 fireEvent.click(screen.getByRole('button',{name:'Add customer information step'}));
 fireEvent.change(screen.getByLabelText('Field 1 step'),{target:{value:'informational_1'}});fireEvent.change(screen.getByLabelText('Field 2 step'),{target:{value:'information'}});
 expect(screen.queryByRole('region',{name:'Conditional draft preview'})).toBeNull();expect(screen.getByText(/Fix the draft fields and journey step bindings/)).toBeVisible();
});
it('locks fictional V9 inputs during a pending save and removes them after a tenant change',async()=>{
 const {client}=fixture();let finish!:(value:unknown)=>void;vi.mocked(client.savePaidJourneyCustomerFieldDraft).mockImplementation(()=>new Promise(resolve=>{finish=resolve as (value:unknown)=>void;}));
 const view=render(<ConnectedJourneyCustomerFieldDraft {...props} client={client}/>);await open();edit();fireEvent.click(screen.getByRole('button',{name:'Add customer text field'}));
 fireEvent.change(screen.getByRole('textbox',{name:'Preview value: Additional information 1'}),{target:{value:'Fictional'}});fireEvent.click(screen.getByRole('button',{name:'Save customer questions draft'}));
 expect(screen.getByRole('textbox',{name:'Preview value: Additional information 1'})).toBeDisabled();expect(screen.getByRole('button',{name:'Reset preview scenario'})).toBeDisabled();
 view.rerender(<ConnectedJourneyCustomerFieldDraft {...props} tenantId={other} client={client}/>);expect(screen.queryByRole('region',{name:'Conditional draft preview'})).toBeNull();
 finish({});await waitFor(()=>expect(screen.queryByText(/Saved conditional journey/)).toBeNull());
});
