import {afterEach,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor,within} from '@testing-library/react';
import {createRuntimeClient,PublicationError,type CustomerFieldRollbackReceipt,type RuntimeClient} from '@lumin/runtime-client';
import {ConnectedCustomerFieldHistory} from './ConnectedCustomerFieldHistory';
const tenant='11111111-1111-4111-8111-111111111111',flow='22222222-2222-4222-8222-222222222222',version='33333333-3333-4333-8333-333333333333',installation='44444444-4444-4444-8444-444444444444',prior='55555555-5555-4555-8555-555555555555',priorInstallation='66666666-6666-4666-8666-666666666666',actor='77777777-7777-4777-8777-777777777777';
const fields=[{id:'custom_access',kind:'text',label:'Entry instructions',required:true,maxLength:100},{id:'custom_notes',kind:'text',label:'Notes',required:false,maxLength:50}];
const history={flowId:flow,versions:[{versionId:version,renderSchemaVersion:5,draftRevision:3,name:'Current cleaning',presentation:{accentColor:'#0e7490',layout:'compact'},current:true,publication:{versionId:version,installationId:installation,renderSchemaVersion:5,hostedPath:'/checkout/flow/'+installation},customerFields:fields},{versionId:prior,renderSchemaVersion:3,draftRevision:1,name:'Prior cleaning',presentation:{accentColor:'#be123c',layout:'stacked'},current:false,publication:{versionId:prior,installationId:priorInstallation,renderSchemaVersion:3,hostedPath:'/checkout/flow/'+priorInstallation}}]};
const receipt:CustomerFieldRollbackReceipt={flowId:flow,versionId:prior,installationId:priorInstallation,renderSchemaVersion:3,hostedPath:'/checkout/flow/'+priorInstallation};
const json=(value:unknown,status=200)=>new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json'}});
afterEach(()=>{cleanup();vi.restoreAllMocks();});
async function fixture(action:(path:string,init?:RequestInit)=>Promise<Response>){const calls=vi.fn<typeof fetch>(async(input,init)=>{const path=String(input);return path.includes('/token?')?json({access_token:'private-history-owner'}):path.endsWith('/user')?json({id:actor}):action(path,init);});const client=createRuntimeClient({url:'https://example.supabase.co',publishableKey:'sb_publishable_fixture',tenantId:tenant,bookingApiOrigin:'https://api.example.test'},calls);await client.signIn('owner@example.test','fixture');return{client,calls};}
const props={tenantId:tenant,blocked:false,onStateChange:vi.fn()};
async function load(){fireEvent.change(screen.getByLabelText('Publication history form ID'),{target:{value:flow}});fireEvent.click(screen.getByRole('button',{name:'Refresh publication history'}));await screen.findByRole('heading',{name:'Current cleaning'});}
async function review(){fireEvent.change(screen.getByLabelText('Prior published version'),{target:{value:prior}});fireEvent.click(screen.getByRole('button',{name:'Review rollback'}));return screen.findByRole('dialog',{name:'Review publication rollback'});}
it('does not issue HTTP on mount; explicit history displays immutable ordered definitions and canonical links only',async()=>{const {client,calls}=await fixture(async()=>json({ok:true,data:history}));render(<ConnectedCustomerFieldHistory client={client} {...props}/>);expect(calls).toHaveBeenCalledTimes(2);await load();expect(calls).toHaveBeenCalledTimes(3);expect(screen.getByText(/Current version at last history check/)).toBeTruthy();expect(screen.getByText(/Historical version/)).toBeTruthy();const definitions=screen.getAllByText(/ID: custom_/);expect(definitions[0]).toHaveTextContent('Entry instructions; ID: custom_access; Required; maximum length: 100');expect(definitions[1]).toHaveTextContent('Notes; ID: custom_notes; Optional; maximum length: 50');expect(screen.getByText(/Customer answers are not shown/)).toBeTruthy();expect(screen.getByRole('link',{name:'Open published revision 3: Current cleaning'})).toHaveAttribute('href','https://booking-lumin-checkout-staging.netlify.app/checkout/flow/'+installation);expect(screen.getByRole('link',{name:'Open published revision 1: Prior cleaning'})).toHaveAttribute('rel','noopener noreferrer');expect(document.body).not.toHaveTextContent('private-history-owner');expect(calls.mock.calls[2]?.[1]?.method).toBe('GET');});
it('review is explicit, focuses cancel, traps Tab, supports Escape and restores review focus without POST',async()=>{const {client,calls}=await fixture(async()=>json({ok:true,data:history}));render(<ConnectedCustomerFieldHistory client={client} {...props}/>);await load();const dialog=await review(),cancel=within(dialog).getByRole('button',{name:'Cancel rollback'}),confirm=within(dialog).getByRole('button',{name:'Confirm publication rollback'});expect(cancel).toHaveFocus();fireEvent.keyDown(cancel,{key:'Tab'});expect(confirm).toHaveFocus();fireEvent.keyDown(confirm,{key:'Tab'});expect(cancel).toHaveFocus();fireEvent.keyDown(cancel,{key:'Tab',shiftKey:true});expect(confirm).toHaveFocus();fireEvent.keyDown(confirm,{key:'Escape'});expect(screen.queryByRole('dialog')).toBeNull();expect(screen.getByRole('button',{name:'Review rollback'})).toHaveFocus();expect(calls).toHaveBeenCalledTimes(3);await review();fireEvent.click(screen.getByRole('button',{name:'Cancel rollback'}));expect(screen.queryByRole('dialog')).toBeNull();expect(calls).toHaveBeenCalledTimes(3);});
it('confirms only the reviewed current and target; verified copy is historical evidence',async()=>{const {client,calls}=await fixture(async(path,init)=>{if(init?.method==='POST'){expect(JSON.parse(String(init.body))).toEqual({expectedCurrentVersionId:version,targetVersionId:prior});return json({ok:true,data:receipt});}return json({ok:true,data:history});});render(<ConnectedCustomerFieldHistory client={client} {...props}/>);await load();await review();expect(calls).toHaveBeenCalledTimes(3);fireEvent.click(screen.getByRole('button',{name:'Confirm publication rollback'}));await screen.findByText(/Rollback target verified at last check/);expect(screen.getByText(/A later publication may have changed the current version/)).toBeTruthy();expect(screen.getByRole('link',{name:'Open last verified rollback target'})).toHaveAttribute('href','https://booking-lumin-checkout-staging.netlify.app/checkout/flow/'+priorInstallation);expect(calls.mock.calls.filter(call=>call[1]?.method==='POST')).toHaveLength(2);});
it.each([3,5])('lost rollback response survives remount; explicit GET recovers schema%i with no POST retry even while blocked',async(schema)=>{const target={...receipt,renderSchemaVersion:schema},mixed={...history,versions:[history.versions[0],{...history.versions[1],renderSchemaVersion:schema,publication:{...history.versions[1]!.publication,renderSchemaVersion:schema},...(schema===5?{customerFields:fields}:{})}]};const {client,calls}=await fixture(async(path,init)=>init?.method==='POST'?json({ok:false,code:'INTERNAL_ERROR'},500):json({ok:true,data:path.includes('/rollback-receipt?')?target:mixed}));const view=render(<ConnectedCustomerFieldHistory client={client} {...props}/>);await load();await review();fireEvent.click(screen.getByRole('button',{name:'Confirm publication rollback'}));await screen.findByText(/Rollback outcome is unverified\. Draft/);view.unmount();render(<ConnectedCustomerFieldHistory client={client} {...props} blocked/>);expect(screen.getByLabelText('Publication history form ID')).toHaveValue(flow);expect(screen.getByLabelText('Publication history form ID')).toBeDisabled();expect(screen.getByRole('button',{name:'Check rollback outcome'})).toBeEnabled();const count=calls.mock.calls.length;fireEvent.click(screen.getByRole('button',{name:'Check rollback outcome'}));await screen.findByText(/Rollback target verified at last check/);expect(calls).toHaveBeenCalledTimes(count+1);expect(String(calls.mock.calls.at(-1)?.[0])).toContain('/rollback-receipt?tenantId='+tenant);expect(calls.mock.calls.filter(call=>String(call[0]).includes('/rollback?'))).toHaveLength(1);});
it('remount during pending POST can observe settled session state without replay, then recover by GET',async()=>{let finish!:(response:Response)=>void;const {client,calls}=await fixture(async(path,init)=>init?.method==='POST'?new Promise(resolve=>finish=resolve):json({ok:true,data:path.includes('/rollback-receipt?')?receipt:history}));const view=render(<ConnectedCustomerFieldHistory client={client} {...props}/>);await load();await review();fireEvent.click(screen.getByRole('button',{name:'Confirm publication rollback'}));await screen.findByText(/Restoring the reviewed published version/);view.unmount();render(<ConnectedCustomerFieldHistory client={client} {...props}/>);expect(screen.getByText(/Restoring the reviewed published version/)).toBeTruthy();finish(json({ok:false,code:'INTERNAL_ERROR'},500));await waitFor(()=>expect(client.customerFieldRollbackState(tenant).phase).toBe('unknown'));const count=calls.mock.calls.length;fireEvent.click(screen.getByRole('button',{name:"Check this session's rollback state"}));expect(calls).toHaveBeenCalledTimes(count);expect(screen.getByRole('button',{name:'Check rollback outcome'})).toBeEnabled();fireEvent.click(screen.getByRole('button',{name:'Check rollback outcome'}));await screen.findByText(/Rollback target verified at last check/);expect(calls.mock.calls.filter(call=>String(call[0]).includes('/rollback?'))).toHaveLength(1);});
it('another pending action blocks review and confirm, including a block that arrives while dialog is open',async()=>{const {client,calls}=await fixture(async()=>json({ok:true,data:history}));const view=render(<ConnectedCustomerFieldHistory client={client} {...props} blocked/>);await load();expect(screen.getByLabelText('Prior published version')).toBeDisabled();view.rerender(<ConnectedCustomerFieldHistory client={client} {...props}/>);await review();view.rerender(<ConnectedCustomerFieldHistory client={client} {...props} blocked/>);expect(screen.getByRole('button',{name:'Confirm publication rollback'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'Confirm publication rollback'}));expect(calls).toHaveBeenCalledTimes(3);fireEvent.keyDown(screen.getByRole('dialog'),{key:'Escape'});expect(screen.queryByRole('dialog')).toBeNull();expect(screen.getByRole('button',{name:'Refresh publication history'})).toHaveFocus();});
it('stale CAS409 removes review and requires fresh explicit history without a repeated POST',async()=>{const {client,calls}=await fixture(async(_path,init)=>init?.method==='POST'?json({ok:false,code:'CONFLICT'},409):json({ok:true,data:history}));render(<ConnectedCustomerFieldHistory client={client} {...props}/>);await load();await review();fireEvent.click(screen.getByRole('button',{name:'Confirm publication rollback'}));await screen.findByRole('alert');expect(screen.queryByRole('dialog')).toBeNull();expect(screen.queryByRole('button',{name:'Review rollback'})).toBeNull();expect(client.customerFieldRollbackState(tenant)).toEqual({phase:'ready'});expect(calls.mock.calls.filter(call=>String(call[0]).includes('/rollback?'))).toHaveLength(1);});
it.each([json({ok:false,code:'NOT_AVAILABLE'},404),json({ok:true,data:{...receipt,versionId:version}}),json({ok:true,data:{...receipt,installationId:installation,hostedPath:'/checkout/flow/'+installation}})])('unavailable or mismatched receipt keeps uncertain rollback frozen',async(reply)=>{const {client,calls}=await fixture(async(path,init)=>init?.method==='POST'?json({ok:false,code:'INTERNAL_ERROR'},500):path.includes('/rollback-receipt?')?reply:json({ok:true,data:history}));render(<ConnectedCustomerFieldHistory client={client} {...props}/>);await load();await review();fireEvent.click(screen.getByRole('button',{name:'Confirm publication rollback'}));await screen.findByText(/Rollback outcome is unverified\. Draft/);const state=client.customerFieldRollbackState(tenant);fireEvent.click(screen.getByRole('button',{name:'Check rollback outcome'}));await waitFor(()=>expect(screen.getByRole('button',{name:'Check rollback outcome'})).toBeEnabled());expect(client.customerFieldRollbackState(tenant)).toEqual(state);expect(screen.queryByText(/Rollback target verified/)).toBeNull();expect(calls.mock.calls.filter(call=>String(call[0]).includes('/rollback?'))).toHaveLength(1);});
it('history refresh while uncertain is read-only and never reveals a retry action',async()=>{const {client,calls}=await fixture(async(_path,init)=>init?.method==='POST'?json({ok:false,code:'INTERNAL_ERROR'},500):json({ok:true,data:history}));render(<ConnectedCustomerFieldHistory client={client} {...props}/>);await load();await review();fireEvent.click(screen.getByRole('button',{name:'Confirm publication rollback'}));await screen.findByText(/Rollback outcome is unverified\. Draft/);const state=client.customerFieldRollbackState(tenant);fireEvent.click(screen.getByRole('button',{name:'Refresh publication history'}));await screen.findByRole('heading',{name:'Current cleaning'});expect(client.customerFieldRollbackState(tenant)).toEqual(state);expect(screen.getByRole('button',{name:'Review rollback'})).toBeDisabled();expect(screen.queryByRole('button',{name:/retry/i})).toBeNull();expect(calls.mock.calls.filter(call=>String(call[0]).includes('/rollback?'))).toHaveLength(1);});
it('drops late history on business/client change and does not retain old form identifiers',async()=>{let finish!:(response:Response)=>void;const first=await fixture(async()=>new Promise(resolve=>finish=resolve)),second=await fixture(async()=>{throw Error('unexpected request');});const view=render(<ConnectedCustomerFieldHistory client={first.client} {...props}/>);fireEvent.change(screen.getByLabelText('Publication history form ID'),{target:{value:flow}});fireEvent.click(screen.getByRole('button',{name:'Refresh publication history'}));view.rerender(<ConnectedCustomerFieldHistory client={second.client} {...props} tenantId={version}/>);finish(json({ok:true,data:history}));await waitFor(()=>expect(screen.queryByText(/Checking published form history/)).toBeNull());expect(screen.queryByRole('heading',{name:'Current cleaning'})).toBeNull();expect(screen.getByLabelText('Publication history form ID')).toHaveValue('');expect(second.calls).toHaveBeenCalledTimes(2);});
it('late rollback completion after a business change cannot show old receipt or notify the new context',async()=>{let finish!:(response:Response)=>void;const {client}=await fixture(async(_path,init)=>init?.method==='POST'?new Promise(resolve=>finish=resolve):json({ok:true,data:history})),changed=vi.fn();const view=render(<ConnectedCustomerFieldHistory client={client} {...props} onStateChange={changed}/>);await load();await review();fireEvent.click(screen.getByRole('button',{name:'Confirm publication rollback'}));const notified=changed.mock.calls.length;view.rerender(<ConnectedCustomerFieldHistory client={client} {...props} tenantId={version} onStateChange={changed}/>);finish(json({ok:true,data:receipt}));await waitFor(()=>expect(client.customerFieldRollbackState(tenant).phase).toBe('verified'));expect(screen.queryByText(/Rollback target verified/)).toBeNull();expect(changed).toHaveBeenCalledTimes(notified);});
it('rejects unapproved paths and withheld installation before linking or reviewing',async()=>{const invalid={...history,versions:history.versions.map(v=>({...v,publication:{...v.publication,hostedPath:'https://foreign.example.test'}}))};const {client,calls}=await fixture(async()=>json({ok:true,data:invalid}));render(<ConnectedCustomerFieldHistory client={client} {...props}/>);fireEvent.change(screen.getByLabelText('Publication history form ID'),{target:{value:flow}});fireEvent.click(screen.getByRole('button',{name:'Refresh publication history'}));await screen.findByRole('alert');expect(screen.queryByRole('link')).toBeNull();expect(screen.queryByRole('button',{name:'Review rollback'})).toBeNull();expect(calls).toHaveBeenCalledTimes(3);});
it('null installation retains metadata but cannot become a rollback target',async()=>{const {client}=await fixture(async()=>json({ok:true,data:{...history,versions:[history.versions[0],{...history.versions[1],publication:null}]}}));render(<ConnectedCustomerFieldHistory client={client} {...props}/>);await load();expect(screen.getByRole('heading',{name:'Prior cleaning'})).toBeTruthy();expect(screen.getByText(/No verified installation link/)).toBeTruthy();expect(screen.queryByRole('button',{name:'Review rollback'})).toBeNull();});
it('bounds the narrow container and review frame without hiding metadata',async()=>{const {client}=await fixture(async()=>json({ok:true,data:history}));render(<div style={{width:320}}><ConnectedCustomerFieldHistory client={client} {...props}/></div>);await load();expect(screen.getByRole('region',{name:'Customer field publication history'})).toHaveStyle({minWidth:'0',maxWidth:'100%',overflowWrap:'anywhere'});expect(screen.getByLabelText('Publication history form ID')).toHaveStyle({maxWidth:'100%',boxSizing:'border-box'});const dialog=await review();expect(dialog.firstElementChild).toHaveStyle({width:'100%',maxWidth:'520px',minWidth:'0',boxSizing:'border-box'});});

it('offers only the validated current V5 installation, explicitly and read-only, and invalidates before refresh/edit',async()=>{
 const {client,calls}=await fixture(async()=>json({ok:true,data:history}));const choose=vi.fn(),invalid=vi.fn();const view=render(<ConnectedCustomerFieldHistory client={client} {...props} onViewCurrentInstallation={choose} onHistoryInvalidated={invalid}/>);
 expect(screen.queryByRole('button',{name:'View current installation'})).toBeNull();await load();const count=calls.mock.calls.length;expect(choose).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'View current installation'}));expect(choose).toHaveBeenCalledWith(history,client.authContextRevision());expect(calls).toHaveBeenCalledTimes(count);
 view.rerender(<ConnectedCustomerFieldHistory client={client} {...props} blocked onViewCurrentInstallation={choose} onHistoryInvalidated={invalid}/>);expect(screen.getByRole('button',{name:'View current installation'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'View current installation'}));expect(choose).toHaveBeenCalledTimes(1);expect(invalid).toHaveBeenCalled();
 view.rerender(<ConnectedCustomerFieldHistory client={client} {...props} onViewCurrentInstallation={choose} onHistoryInvalidated={invalid}/>);invalid.mockClear();fireEvent.change(screen.getByLabelText('Publication history form ID'),{target:{value:prior}});expect(invalid).toHaveBeenCalledTimes(1);expect(screen.queryByRole('button',{name:'View current installation'})).toBeNull();
});
it.each(['simple','missing','historical','malformed'] as const)('never grants current V5 installation selection from %s evidence',async kind=>{
 const value=structuredClone(history);if(kind==='simple'){value.versions[0]!.current=false;value.versions[1]!.current=true;}else if(kind==='missing')value.versions[0]!.publication=null as never;else if(kind==='historical'){value.versions[0]!.current=false;}else value.versions[0]!.publication.hostedPath='https://unapproved.example';
 const {client}=await fixture(async()=>json({ok:true,data:value}));const choose=vi.fn();render(<ConnectedCustomerFieldHistory client={client} {...props} onViewCurrentInstallation={choose}/>);fireEvent.change(screen.getByLabelText('Publication history form ID'),{target:{value:flow}});fireEvent.click(screen.getByRole('button',{name:'Refresh publication history'}));await waitFor(()=>expect(screen.queryByText('Checking published form history...')).toBeNull());expect(screen.queryByRole('button',{name:'View current installation'})).toBeNull();expect(choose).not.toHaveBeenCalled();
});

it.each(['unmount','tenant','client','auth'] as const)('cannot expose or notify installation evidence after a pending history read loses %s identity',async change=>{
 let finish!:(response:Response)=>void;const first=await fixture(async()=>new Promise(resolve=>finish=resolve)),second=await fixture(async()=>{throw Error('unexpected');});const verified=vi.fn(),choose=vi.fn();const view=render(<ConnectedCustomerFieldHistory client={first.client} {...props} onVerifiedHistory={verified} onViewCurrentInstallation={choose}/>);fireEvent.change(screen.getByLabelText('Publication history form ID'),{target:{value:flow}});fireEvent.click(screen.getByRole('button',{name:'Refresh publication history'}));await waitFor(()=>expect(finish).toBeTypeOf('function'));
 if(change==='unmount')view.unmount();else {if(change==='auth')first.client.signOut();view.rerender(<ConnectedCustomerFieldHistory client={change==='client'?second.client:first.client} {...props} tenantId={change==='tenant'?version:tenant} onVerifiedHistory={verified} onViewCurrentInstallation={choose}/>);}
 finish(json({ok:true,data:history}));await waitFor(()=>expect(screen.queryByText('Checking published form history...')).toBeNull());expect(verified).not.toHaveBeenCalled();expect(choose).not.toHaveBeenCalled();expect(screen.queryByRole('button',{name:'View current installation'})).toBeNull();expect(document.body.textContent).not.toContain(installation);expect(second.calls).toHaveBeenCalledTimes(2);
});
it('uses the current explicit selection callback after replacement without triggering either callback automatically',async()=>{
 const {client,calls}=await fixture(async()=>json({ok:true,data:history}));const old=vi.fn(),current=vi.fn();const view=render(<ConnectedCustomerFieldHistory client={client} {...props} onViewCurrentInstallation={old}/>);await load();view.rerender(<ConnectedCustomerFieldHistory client={client} {...props} onViewCurrentInstallation={current}/>);expect(old).not.toHaveBeenCalled();expect(current).not.toHaveBeenCalled();const before=calls.mock.calls.length;fireEvent.click(screen.getByRole('button',{name:'View current installation'}));expect(old).not.toHaveBeenCalled();expect(current).toHaveBeenCalledWith(history,client.authContextRevision());expect(calls).toHaveBeenCalledTimes(before);
});


it.each(['not_sent','rejected','unknown'] as const)('never renders typed history error details (%s) and supports an explicit read retry',async delivery=>{
 const {client}=await fixture(async()=>json({ok:true,data:history}));
 const read=vi.spyOn(client,'customerFieldVersionHistory');
 const error=new PublicationError(delivery,'private typed error: bearer secret');
 const message=vi.fn(()=> 'private typed error: bearer secret');Object.defineProperty(error,'message',{configurable:true,get:message});
 read.mockRejectedValueOnce(error);
 render(<ConnectedCustomerFieldHistory client={client} {...props}/>);
 fireEvent.change(screen.getByLabelText('Publication history form ID'),{target:{value:flow}});
 fireEvent.click(screen.getByRole('button',{name:'Refresh publication history'}));
 expect(await screen.findByRole('alert')).toHaveTextContent('Publication history could not be checked. An uncertain action remains locked.');
 expect(document.body.textContent).not.toContain('private typed error');expect(message).not.toHaveBeenCalled();
 expect(screen.queryByRole('link')).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Refresh publication history'}));
 await screen.findByRole('heading',{name:'Current cleaning'});expect(read).toHaveBeenCalledTimes(2);
});
it('sanitizes a rejected rollback while requiring fresh history before another review',async()=>{
 const {client,calls}=await fixture(async(_path,init)=>init?.method==='POST'?json({ok:false,code:'CONFLICT'},409):json({ok:true,data:history}));
 const rollback=client.rollbackCustomerFieldPublication;
 vi.spyOn(client,'rollbackCustomerFieldPublication').mockImplementation(async(...args)=>{try{return await rollback(...args);}catch(error){throw new PublicationError((error as PublicationError).delivery,'private rejection detail');}});
 render(<ConnectedCustomerFieldHistory client={client} {...props}/>);await load();await review();
 fireEvent.click(screen.getByRole('button',{name:'Confirm publication rollback'}));
 expect(await screen.findByRole('alert')).toHaveTextContent('Rollback was not accepted. Refresh publication history and review eligibility before another explicit action.');
 expect(document.body.textContent).not.toContain('private rejection detail');expect(screen.queryByRole('button',{name:'Review rollback'})).toBeNull();
 expect(calls.mock.calls.filter(([url])=>String(url).includes('/rollback?'))).toHaveLength(1);
 fireEvent.click(screen.getByRole('button',{name:'Refresh publication history'}));await screen.findByRole('heading',{name:'Current cleaning'});
 expect(screen.getByRole('button',{name:'Review rollback'})).toBeDisabled();
});
it('sanitizes uncertain writer and receipt errors without unlocking or repeating the rollback',async()=>{
 let receiptAvailable=false;
 const {client,calls}=await fixture(async(path,init)=>init?.method==='POST'?json({ok:false,code:'INTERNAL_ERROR'},500):path.includes('/rollback-receipt?')?receiptAvailable?json({ok:true,data:receipt}):json({ok:false,code:'NOT_AVAILABLE'},404):json({ok:true,data:history}));
 const rollback=client.rollbackCustomerFieldPublication,reconcile=client.reconcileCustomerFieldRollback;
 vi.spyOn(client,'rollbackCustomerFieldPublication').mockImplementation(async(...args)=>{try{return await rollback(...args);}catch{throw new PublicationError('unknown','private writer detail');}});
 vi.spyOn(client,'reconcileCustomerFieldRollback').mockImplementation(async(...args)=>{try{return await reconcile(...args);}catch{throw new PublicationError('unknown','private receipt detail');}});
 render(<ConnectedCustomerFieldHistory client={client} {...props}/>);await load();await review();
 fireEvent.click(screen.getByRole('button',{name:'Confirm publication rollback'}));
 expect(await screen.findByRole('alert')).toHaveTextContent('Rollback outcome is unverified. Check its frozen target receipt without repeating rollback.');
 const frozen=client.customerFieldRollbackState(tenant);expect(frozen.phase).toBe('unknown');
 fireEvent.click(screen.getByRole('button',{name:'Check rollback outcome'}));
 await waitFor(()=>expect(screen.getByRole('alert')).toHaveTextContent('The rollback receipt could not be verified. The frozen target remains locked.'));
 expect(client.customerFieldRollbackState(tenant)).toEqual(frozen);expect(document.body.textContent).not.toContain('private writer detail');expect(document.body.textContent).not.toContain('private receipt detail');
 receiptAvailable=true;fireEvent.click(screen.getByRole('button',{name:'Check rollback outcome'}));await screen.findByText(/Rollback target verified at last check/);
 expect(calls.mock.calls.filter(([url])=>String(url).includes('/rollback?'))).toHaveLength(1);
 expect(calls.mock.calls.filter(([url])=>String(url).includes('/rollback-receipt?'))).toHaveLength(2);
});
