import {useEffect,useRef,useState,type FormEvent} from 'react';
import {BusinessProfile} from '@lumin/contracts';
import {PaidJourneyCustomerFieldForm,} from '@lumin/workflow';
import {PAID_SIMPLE_ACCENT_COLORS,PaidJourneyDraftError,type RuntimeClient,type ServiceRow,type PaidJourneyCustomerFieldOwnerDraft} from '@lumin/runtime-client';
export type JourneyCustomerFieldDraftClient=Pick<RuntimeClient,'businessProfile'|'authContextRevision'|'simpleOfferLocked'|'savePaidJourneyCustomerFieldDraft'|'loadPaidJourneyCustomerFieldDraft'|'paidJourneyCustomerFieldDraftState'>;
type Props={client:JourneyCustomerFieldDraftClient;tenantId:string;role?:string;staging:boolean;services:ServiceRow[];catalogLoading:boolean};
type Mutable<T>=T extends readonly (infer V)[]?Mutable<V>[]:T extends object?{ -readonly [K in keyof T]:Mutable<T[K]>}:T;
type Form=Mutable<PaidJourneyCustomerFieldForm>;
type Input={schemaVersion:2;serviceId:string;expectedRevision:number;form:Form};
const uuid=(value:string)=>/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/.test(value);
const copy=<T,>(value:unknown):T=>JSON.parse(JSON.stringify(value)) as T;
const initialForm=():Form=>({name:'',presentation:{accentColor:'#4f46e5',layout:'stacked'},journey:{schemaVersion:1,stages:(['service','options','schedule','information','review_payment','confirmation'] as const).map(kind=>({id:kind,kind,label:kind==='information'?'Customer information':kind.replaceAll('_',' '),enabled:kind!=='options'}))},customerFields:[],fieldBindings:[]});
const blank=():Input=>({schemaVersion:2,serviceId:'',expectedRevision:0,form:initialForm()});
const storageKey=(tenant:string)=>'lumin.journey-fields:'+tenant;
function locator(tenant:string){try{const value=sessionStorage.getItem(storageKey(tenant));return value&&uuid(value)?value:'';}catch{return '';}}
function remember(tenant:string,id:string){try{if(id&&uuid(id))sessionStorage.setItem(storageKey(tenant),id);else sessionStorage.removeItem(storageKey(tenant));}catch{/* Locator storage is optional; no draft content is stored. */}}
function exact(value:unknown,keys:string[]):value is Record<string,unknown>{return !!value&&typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).sort().join(',')===[...keys].sort().join(',');}
function verifiedDraft(value:unknown,tenant:string,flow:string):PaidJourneyCustomerFieldOwnerDraft|undefined{if(!exact(value,['schemaVersion','tenantId','flowId','serviceId','revision','form'])||value.schemaVersion!==2||value.tenantId!==tenant||value.flowId!==flow||typeof value.serviceId!=='string'||!uuid(value.serviceId)||!Number.isSafeInteger(value.revision)||Number(value.revision)<1)return;const form=PaidJourneyCustomerFieldForm.safeParse(value.form);if(form.success)return {schemaVersion:2,tenantId:tenant,flowId:flow,serviceId:value.serviceId,revision:Number(value.revision),form:form.data};}
function draftInput(value:PaidJourneyCustomerFieldOwnerDraft):Input{return {schemaVersion:2,serviceId:value.serviceId,expectedRevision:value.revision,form:copy<Form>(value.form)};}
/** A draft-only staging editor; its preview never reserves, publishes or takes payment. */
export function ConnectedJourneyCustomerFieldDraft(props:Props){const fences=useRef(new Set<string>()),auth=props.client.authContextRevision();if(!props.staging||props.role!=='BUSINESS_OWNER'||!uuid(props.tenantId))return null;return <Editor key={props.tenantId+':'+auth} {...props} auth={auth} fences={fences.current}/>;}
function Editor({client,tenantId,role,staging,services,catalogLoading,auth,fences}:Props&{auth:number;fences:Set<string>}){
 const initial=()=>({client,tenantId,auth,verified:false,flowId:locator(tenantId),input:blank(),baseline:undefined as PaidJourneyCustomerFieldOwnerDraft|undefined,dirty:false,conflict:false,notice:'',error:''});
 const [snapshot,setSnapshot]=useState(initial),[busy,setBusy]=useState(false),[review,setReview]=useState<'reload'|'discard'|{id:string}>(),[viewport,setViewport]=useState<'Mobile'|'Tablet'|'Desktop'>('Mobile');
 const epoch=useRef(0),pending=useRef(false),context=useRef({client,tenantId,auth,role,staging});context.current={client,tenantId,auth,role,staging};
 useEffect(()=>{epoch.current++;pending.current=false;setSnapshot(initial());setBusy(false);setReview(undefined);return()=>{epoch.current++;};},[client,tenantId,auth,role,staging]);
 const view=snapshot.client===client&&snapshot.tenantId===tenantId&&snapshot.auth===auth?snapshot:initial();
 const state=client.paidJourneyCustomerFieldDraftState(tenantId),unknown=(!busy&&fences.has(tenantId))||state.phase==='unverified';
 const live=(at:number)=>at===epoch.current&&context.current.client===client&&context.current.tenantId===tenantId&&context.current.auth===auth&&context.current.role==='BUSINESS_OWNER'&&context.current.staging&&client.authContextRevision()===auth;
 const allowed=()=>staging&&role==='BUSINESS_OWNER'&&uuid(tenantId)&&!catalogLoading&&client.authContextRevision()===auth;
 const lockedNow=()=>{const latest=client.paidJourneyCustomerFieldDraftState(tenantId);return fences.has(tenantId)||['unverified','saving','loading'].includes(latest.phase)||client.simpleOfferLocked();};
 const blocked=busy||catalogLoading||unknown||['saving','loading'].includes(state.phase)||client.simpleOfferLocked();
 const eligible=services.filter(s=>s.tenant_id===tenantId&&s.active&&uuid(s.id)&&Number.isSafeInteger(s.base_price)&&s.base_price>0&&s.duration_minutes>=5&&s.duration_minutes<=1440);
 const validation=PaidJourneyCustomerFieldForm.safeParse(view.input.form),ready=validation.success&&eligible.some(s=>s.id===view.input.serviceId);
 function edit(action:(input:Input)=>void){if(pending.current||blocked||lockedNow()||!view.verified||!allowed())return;const input=copy<Input>(view.input);action(input);setReview(undefined);setSnapshot({...view,input,dirty:true,notice:'Unsaved conditional journey edits.',error:''});}
 function identity(id:string){if(pending.current||blocked||lockedNow()||!allowed())return;remember(tenantId,id);setReview(undefined);setSnapshot({...view,flowId:id,input:blank(),baseline:undefined,dirty:false,conflict:false,error:'',notice:'Draft identity selected. Explicitly load to verify stored fields.'});}
 async function check(){if(pending.current||blocked||lockedNow()||!allowed())return;const at=++epoch.current;pending.current=true;setBusy(true);setReview(undefined);setSnapshot({...view,verified:false,error:'',notice:''});try{const value=await client.businessProfile(tenantId),profile=value.status==='initialized'?BusinessProfile.safeParse(value.profile):undefined;if(live(at))setSnapshot({...view,verified:!!(profile?.success&&profile.data.tenantId===tenantId&&profile.data.businessType==='HOUSEKEEPING'),notice:'',error:profile?.success&&profile.data.tenantId===tenantId&&profile.data.businessType==='HOUSEKEEPING'?'':'Conditional journey drafting requires a verified Housekeeping business.'});}catch{if(live(at))setSnapshot({...view,verified:false,error:'Business profile could not be verified. No draft was changed.'});}finally{if(live(at)){pending.current=false;setBusy(false);}}}
 async function load(){if(pending.current||blocked||lockedNow()||!view.verified||!allowed()||!uuid(view.flowId))return;const at=++epoch.current;pending.current=true;setBusy(true);setReview(undefined);setSnapshot({...view,error:'',notice:''});try{const response=await client.loadPaidJourneyCustomerFieldDraft(tenantId,view.flowId),draft=verifiedDraft(response,tenantId,view.flowId);if(live(at)){if(!draft||!eligible.some(s=>s.id===draft.serviceId))setSnapshot({...view,error:'Stored conditional journey could not be verified. Your edits were retained.'});else{remember(tenantId,draft.flowId);setSnapshot({...view,input:draftInput(draft),baseline:draft,dirty:false,conflict:false,error:'',notice:`Loaded conditional journey revision ${draft.revision}.`});}}}catch{if(live(at))setSnapshot({...view,error:'Stored conditional journey could not be read. Your edits were retained; no save was sent.'});}finally{if(live(at)){pending.current=false;setBusy(false);}}}
 async function save(event:FormEvent){event.preventDefault();if(pending.current||blocked||lockedNow()||!view.verified||!allowed()||!ready||view.conflict||client.paidJourneyCustomerFieldDraftState(tenantId).phase==='conflict'||(view.flowId&&!uuid(view.flowId)))return;const at=++epoch.current,id=view.flowId||crypto.randomUUID(),input=copy<Input>(view.input);pending.current=true;fences.add(tenantId);remember(tenantId,id);setBusy(true);setReview(undefined);setSnapshot({...view,flowId:id,error:'',notice:''});try{const receipt=await client.savePaidJourneyCustomerFieldDraft(tenantId,id,input);if(live(at)){if(!exact(receipt,['schemaVersion','tenantId','flowId','revision'])||receipt.schemaVersion!==2||receipt.tenantId!==tenantId||receipt.flowId!==id||receipt.revision!==input.expectedRevision+1||!Number.isSafeInteger(receipt.revision))setSnapshot({...view,flowId:id,error:'Save outcome is unverified. Do not repeat or replace this write.'});else{fences.delete(tenantId);setSnapshot({...view,flowId:id,input:{...input,expectedRevision:receipt.revision},baseline:undefined,dirty:false,conflict:false,error:'',notice:`Saved conditional journey revision ${receipt.revision}. Reload explicitly to verify stored fields.`});}}}catch(error){if(live(at)){const known=error instanceof PaidJourneyDraftError&&['not_sent','rejected','conflict'].includes(error.delivery);if(known)fences.delete(tenantId);setSnapshot({...view,flowId:id,conflict:known&&error.delivery==='conflict',error:known?error.delivery==='conflict'?'The stored draft changed. Keep your edits and explicitly reload before saving.':'No verified save was accepted. Keep your edits and check service compatibility or pending operations.':'Save outcome is unverified. Do not repeat or replace this write.'});}}finally{if(live(at)){pending.current=false;setBusy(false);}}}
 function discard(){if(blocked||lockedNow()||!view.baseline||!allowed())return;setSnapshot({...view,input:draftInput(view.baseline),dirty:false,error:'',notice:'Unsaved edits discarded locally. No save was sent.'});setReview(undefined);}
 function addField(){edit(input=>{if(input.form.customerFields.length>=10)return;let n=1;while(input.form.customerFields.some(f=>f.id==='custom_field_'+n))n++;const id='custom_field_'+n;input.form.customerFields.push({id,kind:'text',label:'Additional information '+n,required:false,maxLength:100});input.form.fieldBindings.push({fieldId:id,stageId:input.form.fieldBindings.at(-1)?.stageId??'information'});});}
 function canMoveField(index:number,direction:number){const fields=[...view.input.form.customerFields],destination=index+direction;if(destination<0||destination>=fields.length)return false;[fields[index],fields[destination]]=[fields[destination]!,fields[index]!];const positions=new Map(fields.map((f,i)=>[f.id,i]));return !fields.some((f,i)=>f.when&&(positions.get(f.when.fieldId)??Infinity)>=i);}
 function moveField(index:number,direction:number){edit(input=>{const destination=index+direction;if(destination<0||destination>=input.form.customerFields.length)return;const fields=input.form.customerFields;[fields[index],fields[destination]]=[fields[destination]!,fields[index]!];const positions=new Map(fields.map((f,i)=>[f.id,i]));if(fields.some((f,i)=>f.when&&(positions.get(f.when.fieldId)??Infinity)>=i)){input.form=copy<Form>(view.input.form);return;}const slots=input.form.fieldBindings.map(b=>b.stageId);input.form.fieldBindings=fields.map((f,i)=>({fieldId:f.id,stageId:slots[i]!}));});}
 function addStep(){edit(input=>{if(input.form.journey.stages.length>=16||input.form.customerFields.length>=10)return;let n=1;while(input.form.journey.stages.some(s=>s.id==='informational_'+n))n++;const stageId='informational_'+n;input.form.journey.stages.splice(input.form.journey.stages.findIndex(s=>s.kind==='review_payment'),0,{id:stageId,kind:'informational',label:'Additional information '+n,enabled:true});let f=1;while(input.form.customerFields.some(field=>field.id==='custom_field_'+f))f++;const fieldId='custom_field_'+f;input.form.customerFields.push({id:fieldId,kind:'text',label:'Additional information '+f,required:false,maxLength:100});input.form.fieldBindings.push({fieldId,stageId});});}
 if(!staging||role!=='BUSINESS_OWNER'||!uuid(tenantId))return null;
 return <section aria-label="Conditional journey draft" style={{minWidth:0,maxWidth:'100%',overflowWrap:'anywhere'}}><h2>Customer questions draft</h2><p>Staging authoring for a simple Housekeeping service. These settings never change authoritative prices or publish a customer form.</p><button type="button" disabled={blocked} onClick={()=>void check()}>Check customer questions editor</button>
 {view.verified&&<><form aria-label="Save conditional journey draft" onSubmit={event=>void save(event)}><fieldset disabled={blocked} style={{minWidth:0,maxWidth:'100%'}}><legend>Conditional journey draft</legend><button type="button" onClick={()=>view.dirty?setReview({id:''}):identity('')}>Start new customer questions draft</button><details><summary>Open a known customer questions draft</summary><label>Customer questions draft ID<input style={{maxWidth:'100%',boxSizing:'border-box'}} value={view.flowId} onChange={e=>view.dirty?setReview({id:e.target.value}):identity(e.target.value)}/></label><p>Only this locator is stored for refresh. Customer answers and form content are never stored in the browser session.</p></details><button type="button" disabled={!uuid(view.flowId)} onClick={()=>view.dirty?setReview('reload'):void load()}>Reload customer questions draft</button><label>Customer questions service<select style={{maxWidth:'100%',boxSizing:'border-box'}} value={view.input.serviceId} onChange={e=>edit(i=>{i.serviceId=e.target.value;})}><option value="">Choose a service</option>{eligible.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><p>The server checks current simple-service compatibility on every save and load.</p><label>Customer questions form name<input style={{maxWidth:'100%',boxSizing:'border-box'}} maxLength={200} value={view.input.form.name} onChange={e=>edit(i=>{i.form.name=e.target.value;})}/></label>
 <ol>{view.input.form.journey.stages.map((stage,index)=><li key={stage.id}><label>{stage.id} question step label<input style={{maxWidth:'100%',boxSizing:'border-box'}} maxLength={80} value={stage.label} onChange={e=>edit(i=>{i.form.journey.stages[index]!.label=e.target.value;})}/></label>{stage.kind==='informational'&&<label><input style={{maxWidth:'100%',boxSizing:'border-box'}} type="checkbox" checked={stage.enabled} onChange={e=>edit(i=>{i.form.journey.stages[index]!.enabled=e.target.checked;})}/>Show {stage.label} step</label>}</li>)}</ol><button type="button" disabled={view.input.form.customerFields.length>=10||view.input.form.journey.stages.length>=16} onClick={addStep}>Add customer information step</button>
 <p>Conditions use earlier questions. Clear dependent conditions before moving or removing their source question.</p><button type="button" disabled={view.input.form.customerFields.length>=10} onClick={addField}>Add customer text field</button><ol>{view.input.form.customerFields.map((field,index)=><li key={field.id}><h3>Customer field {index+1}</h3><label>Field {index+1} label<input style={{maxWidth:'100%',boxSizing:'border-box'}} maxLength={100} value={field.label} onChange={e=>edit(i=>{i.form.customerFields[index]!.label=e.target.value;})}/></label><label><input style={{maxWidth:'100%',boxSizing:'border-box'}} type="checkbox" checked={field.required} onChange={e=>edit(i=>{i.form.customerFields[index]!.required=e.target.checked;})}/>Field {index+1} required</label><label>Field {index+1} maximum length<input style={{maxWidth:'100%',boxSizing:'border-box'}} type="number" min={1} max={1000} value={field.maxLength} onChange={e=>edit(i=>{i.form.customerFields[index]!.maxLength=Number(e.target.value);})}/></label><label>Field {index+1} step<select style={{maxWidth:'100%',boxSizing:'border-box'}} value={view.input.form.fieldBindings[index]?.stageId??''} onChange={e=>edit(i=>{i.form.fieldBindings[index]!.stageId=e.target.value;})}>{view.input.form.journey.stages.filter(s=>s.enabled&&(s.kind==='information'||s.kind==='informational')).map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select></label><label>Field {index+1} show when<select style={{maxWidth:'100%',boxSizing:'border-box'}} value={field.when?.fieldId??''} onChange={e=>edit(i=>{const value=i.form.customerFields[index]!;if(e.target.value)value.when={fieldId:e.target.value,equals:'yes'};else delete value.when;})}><option value="">Always shown</option>{view.input.form.customerFields.slice(0,index).map(source=><option key={source.id} value={source.id}>{source.label}</option>)}</select></label>{field.when&&<label>Field {index+1} condition value<input style={{maxWidth:'100%',boxSizing:'border-box'}} maxLength={1000} value={field.when.equals} onChange={e=>edit(i=>{i.form.customerFields[index]!.when!.equals=e.target.value;})}/></label>}<button type="button" disabled={!canMoveField(index,-1)} onClick={()=>moveField(index,-1)}>Move field {index+1} earlier</button><button type="button" disabled={!canMoveField(index,1)} onClick={()=>moveField(index,1)}>Move field {index+1} later</button><button type="button" disabled={view.input.form.customerFields.some(f=>f.when?.fieldId===field.id)} onClick={()=>edit(i=>{const stage=i.form.fieldBindings[index]!.stageId;i.form.customerFields.splice(index,1);i.form.fieldBindings.splice(index,1);if(!i.form.fieldBindings.some(b=>b.stageId===stage)){const empty=i.form.journey.stages.find(s=>s.id===stage);if(empty?.kind==='informational')empty.enabled=false;}})}>Remove field {index+1}</button></li>)}</ol>
 <label>Customer questions accent<select style={{maxWidth:'100%',boxSizing:'border-box'}} value={view.input.form.presentation.accentColor} onChange={e=>edit(i=>{i.form.presentation.accentColor=e.target.value as Form['presentation']['accentColor'];})}>{PAID_SIMPLE_ACCENT_COLORS.map(color=><option key={color} value={color}>{color}</option>)}</select></label><label>Customer questions layout<select style={{maxWidth:'100%',boxSizing:'border-box'}} value={view.input.form.presentation.layout} onChange={e=>edit(i=>{i.form.presentation.layout=e.target.value as 'stacked'|'compact';})}><option value="stacked">Stacked</option><option value="compact">Compact</option></select></label><button type="submit" disabled={!ready||view.conflict||state.phase==='conflict'||(!!view.flowId&&!uuid(view.flowId))}>Save customer questions draft</button><button type="button" disabled={!view.dirty||!view.baseline} onClick={()=>setReview('discard')}>Discard customer questions edits</button></fieldset></form>
 {!validation.success&&view.dirty&&<p role="alert">Check the form name, field definitions, conditions and ordered step bindings before saving.</p>}
 {review&&<section aria-label="Review customer questions replacement"><p>This replaces unsaved draft edits locally. No save or publication is sent.</p><button type="button" disabled={blocked} onClick={()=>review==='reload'?void load():review==='discard'?discard():identity(review.id)}>Discard edits and {review==='reload'?'reload customer questions':review==='discard'?'restore saved questions':'change customer questions ID'}</button><button type="button" onClick={()=>setReview(undefined)}>Keep customer questions edits</button></section>}
 <section aria-label="Read-only customer questions preview"><h3>Draft preview</h3>{(['Mobile','Tablet','Desktop'] as const).map(size=><button key={size} type="button" aria-pressed={viewport===size} onClick={()=>setViewport(size)}>{size} customer questions preview</button>)}<div aria-label={viewport+' customer questions preview frame'} style={{width:'100%',maxWidth:viewport==='Mobile'?375:viewport==='Tablet'?768:1100,minWidth:0,boxSizing:'border-box',overflowWrap:'anywhere',border:'1px solid '+view.input.form.presentation.accentColor,padding:16}}><h4>{view.input.form.name||'Untitled draft'}</h4><ol>{view.input.form.journey.stages.filter(s=>s.enabled).map(stage=><li key={stage.id}>{stage.label}<ul>{view.input.form.fieldBindings.filter(b=>b.stageId===stage.id).map(binding=>{const field=view.input.form.customerFields.find(f=>f.id===binding.fieldId);return <li key={binding.fieldId}>{field?.label}{field?.required?' (Required)':''}{field?.when?' (Conditional)':''}</li>;})}</ul></li>)}</ol></div><p>Read-only draft preview. It does not collect customer answers, reserve capacity or take payment.</p></section><p>Publishing and independent hosted checkout for this conditional journey draft are not available. Existing published forms remain separate.</p></>}
 {unknown&&<p role="alert">Conditional save outcome is unverified. Saving, reloading, replacing and discarding remain locked. No read or preview can settle this write.</p>}{view.notice&&<p role="status">{view.notice}</p>}{view.error&&<p role="alert">{view.error}</p>}</section>;
}
