import {afterEach,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {createRuntimeClient,type ServiceRow} from '@lumin/runtime-client';
import {PaidSimplePublisher,STAGING_CHECKOUT_ORIGIN} from './PaidSimplePublisher';
const tenant='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222',serviceId='33333333-3333-4333-8333-333333333333';
const service:ServiceRow={id:serviceId,tenant_id:tenant,name:'Housekeeping',currency:'USD',duration_minutes:60,base_price:12500,active:true};
const receipt={versionId:other,installationId:serviceId,renderSchemaVersion:3,hostedPath:'/checkout/flow/'+serviceId};
const json=(value:unknown,status=200)=>new Response(JSON.stringify(value),{status});
afterEach(()=>{cleanup();vi.restoreAllMocks();vi.unstubAllGlobals();});
async function fixture(publish:()=>Promise<Response>){
 const calls=vi.fn<typeof fetch>(async(input)=>String(input).includes('/auth/v1/token')?json({access_token:'synthetic-owner-private-token'}):String(input).includes('/auth/v1/user')?json({id:other}):publish());
 const client=createRuntimeClient({url:'https://example.supabase.co',publishableKey:'sb_publishable_synthetic',tenantId:tenant,bookingApiOrigin:'https://api.example.test'},calls);await client.signIn('owner@example.test','fixture');return{client,calls};
}
function fill(){fireEvent.change(screen.getByLabelText('Simple service'),{target:{value:serviceId}});fireEvent.change(screen.getByLabelText('Form name'),{target:{value:'Housekeeping booking'}});}
it('publishes only on an explicit owner action and shows the immutable canonical link and iframe receipt',async()=>{
 const {client,calls}=await fixture(async()=>json({ok:true,data:receipt}));render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service,{...service,id:other,active:false},{...service,id:tenant,base_price:0},{...service,id:tenant,tenant_id:other}]} staging/>);
 expect(calls).toHaveBeenCalledTimes(2);expect(screen.getByLabelText('Checkout origin')).toHaveValue(STAGING_CHECKOUT_ORIGIN);expect(Array.from((screen.getByLabelText('Simple service') as HTMLSelectElement).options)).toHaveLength(2);fill();fireEvent.click(screen.getByText('Publish staging test form'));await screen.findByText('Staging form published');expect(calls).toHaveBeenCalledTimes(3);expect(screen.getByRole('link',{name:'Open staging booking form'})).toHaveAttribute('href',STAGING_CHECKOUT_ORIGIN+receipt.hostedPath);expect(screen.getByLabelText('Website iframe code')).toHaveValue(`<iframe src="${STAGING_CHECKOUT_ORIGIN+receipt.hostedPath}" title="Booking Lumin staging test booking" width="100%" height="720" style="border:0"></iframe>`);expect(screen.getByText(receipt.versionId)).toBeTruthy();expect(screen.queryByText('Publish staging test form')).toBeNull();expect(document.body.textContent).not.toContain('synthetic-owner-private-token');
});
it.each([{role:'BUSINESS_STAFF',staging:true},{role:'BUSINESS_OWNER',staging:false}])('blocks staff or nonstaging publication in the UI: %j',async(props)=>{
 const {client,calls}=await fixture(async()=>{throw Error('unexpected');});render(<PaidSimplePublisher client={client} tenantId={tenant} services={[service]} {...props}/>);expect(screen.queryByText('Publish staging test form')).toBeNull();expect(screen.queryByLabelText('Form name')).toBeNull();expect(screen.queryByLabelText('Publication attempt ID')).toBeNull();expect(screen.queryByRole('button',{name:'Check publication receipt'})).toBeNull();expect(screen.queryByRole('button',{name:'Refresh saved forms'})).toBeNull();expect(screen.queryByRole('button',{name:'Save draft'})).toBeNull();expect(screen.queryByLabelText('Draft accent color')).toBeNull();expect(calls).toHaveBeenCalledTimes(2);
});
it('keeps unknown delivery locked after remount, with no new identity or automatic replay',async()=>{
 const {client,calls}=await fixture(async()=>{throw Error('private-server-token');});const first=render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fill();fireEvent.click(screen.getByText('Publish staging test form'));await screen.findByText(/Publishing again is locked/);expect(screen.queryByText('Publish staging test form')).toBeNull();const attempt=client.paidSimplePublicationState(tenant);expect(attempt.phase).toBe('unknown');first.unmount();render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);await screen.findByText(/Publishing again is locked/);expect(client.paidSimplePublicationState(tenant)).toEqual(attempt);expect(calls).toHaveBeenCalledTimes(3);expect(document.body.textContent).not.toContain('private-server-token');expect(screen.getByRole('button',{name:'Check publication receipt'})).toBeEnabled();
});
it('clears the form and discards a late receipt when the selected business changes',async()=>{
 let resolve!:(response:Response)=>void;const {client,calls}=await fixture(()=>new Promise<Response>(r=>resolve=r));const {rerender}=render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fill();fireEvent.click(screen.getByText('Publish staging test form'));await waitFor(()=>expect(resolve).toBeTypeOf('function'));rerender(<PaidSimplePublisher client={client} tenantId={other} role="BUSINESS_OWNER" services={[{...service,tenant_id:other}]} staging/>);expect(screen.getByLabelText('Form name')).toHaveValue('');resolve(json({ok:true,data:receipt}));await waitFor(()=>expect(client.paidSimplePublicationState(tenant).phase).toBe('published'));expect(screen.queryByText('Staging form published')).toBeNull();expect(screen.queryByText(receipt.versionId)).toBeNull();expect(calls).toHaveBeenCalledTimes(3);
});
it('shows definitive rejection without fabricating publication, and preserves unknown server outcomes',async()=>{
 const {client}=await fixture(async()=>json({ok:false,code:'UNSUPPORTED_CONFIG'},422));render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fill();fireEvent.click(screen.getByText('Publish staging test form'));await screen.findByText('This service does not support the staging paid form.');expect(screen.queryByText('Staging form published')).toBeNull();expect(screen.getByText('Publish staging test form')).toBeEnabled();
});

it('recovers a known attempt after reload only on an explicit read and shows its canonical installation',async()=>{
 const {client,calls}=await fixture(async()=>json({ok:true,data:receipt}));render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fireEvent.change(screen.getByLabelText('Publication attempt ID'),{target:{value:other}});expect(calls).toHaveBeenCalledTimes(2);fireEvent.click(screen.getByRole('button',{name:'Check publication receipt'}));await screen.findByText('Staging form published');expect(calls).toHaveBeenCalledTimes(3);expect(calls.mock.calls[2]?.[0]).toBe('https://api.example.test/api/paid-simple-flows/'+other+'/publication?tenantId='+tenant);expect(calls.mock.calls[2]?.[1]?.method).toBe('GET');expect(screen.getByRole('link',{name:'Open staging booking form'})).toHaveAttribute('href',STAGING_CHECKOUT_ORIGIN+receipt.hostedPath);expect(screen.getByText('Publication attempt')).toBeTruthy();expect(screen.getByLabelText('Publication attempt ID')).toHaveValue(other);expect(screen.getByLabelText('Publication attempt ID')).toHaveAttribute('readonly');expect(document.body.textContent).not.toContain('synthetic-owner-private-token');expect(screen.queryByText('Publish staging test form')).toBeNull();
});
it('keeps a not-found lookup locked and allows only an explicit same-attempt read',async()=>{
 let n=0;const {client,calls}=await fixture(async()=>++n===1?json({ok:false,code:'NOT_AVAILABLE'},404):json({ok:true,data:receipt}));render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fireEvent.change(screen.getByLabelText('Publication attempt ID'),{target:{value:other}});fireEvent.click(screen.getByRole('button',{name:'Check publication receipt'}));await screen.findByText(/No active receipt was found/);expect(screen.queryByText('Publish staging test form')).toBeNull();expect(screen.getByLabelText('Publication attempt ID')).toHaveValue(other);expect(screen.getByLabelText('Publication attempt ID')).toHaveAttribute('readonly');expect(calls).toHaveBeenCalledTimes(3);fireEvent.click(screen.getByRole('button',{name:'Check publication receipt'}));await screen.findByText('Staging form published');expect(calls.mock.calls.slice(2).every(([,options])=>options?.method==='GET')).toBe(true);
});
it('checks an unknown POST attempt without replay or a new identity',async()=>{
 let n=0;const {client,calls}=await fixture(async()=>++n===1?Promise.reject(Error('private-response-secret')):json({ok:true,data:receipt}));render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fill();fireEvent.click(screen.getByText('Publish staging test form'));await screen.findByText(/Publishing again is locked/);const state=client.paidSimplePublicationState(tenant);expect(state.phase).toBe('unknown');fireEvent.click(screen.getByRole('button',{name:'Check publication receipt'}));await screen.findByText('Staging form published');if(state.phase==='unknown')expect(calls.mock.calls[3]?.[0]).toContain('/'+state.flowId+'/publication?');expect(calls.mock.calls[2]?.[1]?.method).toBe('POST');expect(calls.mock.calls[3]?.[1]?.method).toBe('GET');expect(document.body.textContent).not.toContain('private-response-secret');
});
it('clears the recovery field and discards a late receipt on tenant changes',async()=>{
 let resolve!:(response:Response)=>void;const {client}=await fixture(()=>new Promise<Response>(r=>resolve=r));const {rerender}=render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fireEvent.change(screen.getByLabelText('Publication attempt ID'),{target:{value:other}});fireEvent.click(screen.getByRole('button',{name:'Check publication receipt'}));await waitFor(()=>expect(resolve).toBeTypeOf('function'));rerender(<PaidSimplePublisher client={client} tenantId={other} role="BUSINESS_OWNER" services={[{...service,tenant_id:other}]} staging/>);expect(screen.getByLabelText('Publication attempt ID')).toHaveValue('');resolve(json({ok:true,data:receipt}));await waitFor(()=>expect(client.paidSimplePublicationState(tenant).phase).toBe('published'));expect(screen.queryByText('Staging form published')).toBeNull();expect(client.paidSimplePublicationState(other)).toEqual({phase:'ready'});
});
it('rejects invalid recovery IDs without a network read or hiding the publication form',async()=>{
 const {client,calls}=await fixture(async()=>{throw Error('unexpected');});render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fireEvent.change(screen.getByLabelText('Publication attempt ID'),{target:{value:'invalid'}});fireEvent.click(screen.getByRole('button',{name:'Check publication receipt'}));await screen.findByText('Enter the exact publication attempt ID for this business.');expect(calls).toHaveBeenCalledTimes(2);expect(screen.getByText('Publish staging test form')).toBeEnabled();
});

const savedForms=[{flowId:other,name:'Saved housekeeping',publication:receipt},{flowId:serviceId,name:'Another saved form',publication:{versionId:tenant,installationId:other,renderSchemaVersion:3,hostedPath:'/checkout/flow/'+other}}];
it('refreshes saved names and canonical links explicitly, then checks selected receipts without any publication writer',async()=>{
 let n=0;const {client,calls}=await fixture(async()=>++n===1?json({ok:true,data:{publications:savedForms}}):json({ok:true,data:savedForms[n-2]!.publication}));render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);expect(calls).toHaveBeenCalledTimes(2);fireEvent.click(screen.getByRole('button',{name:'Refresh saved forms'}));await screen.findByText('Saved housekeeping');expect(calls).toHaveBeenCalledTimes(3);expect(screen.getByRole('link',{name:'Open saved form: Saved housekeeping'})).toHaveAttribute('href',STAGING_CHECKOUT_ORIGIN+receipt.hostedPath);expect(screen.getByText('Current version at last refresh: '+receipt.versionId)).toBeTruthy();expect(screen.queryByText('Staging form published')).toBeNull();expect(client.paidSimplePublicationState(tenant)).toEqual({phase:'ready'});fireEvent.click(screen.getByRole('button',{name:'Check receipt for Saved housekeeping'}));await screen.findByText('Staging form published');expect(screen.getByLabelText('Publication attempt ID')).toHaveValue(other);fireEvent.click(screen.getByRole('button',{name:'Check receipt for Another saved form'}));await waitFor(()=>expect(screen.getByLabelText('Publication attempt ID')).toHaveValue(serviceId));expect(screen.getByRole('link',{name:'Open staging booking form'})).toHaveAttribute('href',STAGING_CHECKOUT_ORIGIN+savedForms[1]!.publication.hostedPath);expect(calls.mock.calls.slice(2).every(([,options])=>options?.method==='GET'&&!options?.body)).toBe(true);expect(calls.mock.calls[2]?.[0]).toBe('https://api.example.test/api/paid-simple-flows?tenantId='+tenant);expect(calls.mock.calls[3]?.[0]).toContain('/'+other+'/publication?tenantId='+tenant);expect(calls.mock.calls[4]?.[0]).toContain('/'+serviceId+'/publication?tenantId='+tenant);expect(document.body.textContent).not.toContain('synthetic-owner-private-token');expect(screen.queryByText('Publish staging test form')).toBeNull();
});
it.each(['empty','unavailable'])('retains an unknown attempt after an explicit %s saved list response',async(kind)=>{
 let n=0;const {client,calls}=await fixture(async()=>++n===1?Promise.reject(Error('private-secret')):kind==='empty'?json({ok:true,data:{publications:[]}}):json({ok:false,code:'NOT_AVAILABLE'},404));render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fill();fireEvent.click(screen.getByText('Publish staging test form'));await screen.findByText(/Publishing again is locked/);const original=client.paidSimplePublicationState(tenant);fireEvent.click(screen.getByRole('button',{name:'Refresh saved forms'}));await screen.findByText(kind==='empty'?/No current saved forms were returned/:/saved form list could not be verified/);expect(client.paidSimplePublicationState(tenant)).toEqual(original);expect(screen.queryByText('Publish staging test form')).toBeNull();expect(calls).toHaveBeenCalledTimes(4);expect(calls.mock.calls[3]?.[1]?.method).toBe('GET');expect(document.body.textContent).not.toContain('private-secret');
});
it('permits only the matching unknown attempt from a saved list and never switches its identity',async()=>{
 let n=0;const {client,calls}=await fixture(async()=>{if(++n===1)throw Error('ambiguous');const state=client.paidSimplePublicationState(tenant);if(n===2&&state.phase==='unknown')return json({ok:true,data:{publications:[{flowId:state.flowId,name:'Matching attempt',publication:receipt},savedForms[0]!].sort((a,b)=>a.flowId<b.flowId?-1:1)}});return json({ok:true,data:receipt});});render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fill();fireEvent.click(screen.getByText('Publish staging test form'));await screen.findByText(/Publishing again is locked/);const original=client.paidSimplePublicationState(tenant);fireEvent.click(screen.getByRole('button',{name:'Refresh saved forms'}));await screen.findByText('Matching attempt');expect(screen.getByRole('button',{name:'Check receipt for Saved housekeeping'})).toBeDisabled();expect(screen.getByRole('button',{name:'Check receipt for Matching attempt'})).toBeEnabled();expect(client.paidSimplePublicationState(tenant)).toEqual(original);fireEvent.click(screen.getByRole('button',{name:'Check receipt for Matching attempt'}));await screen.findByText('Staging form published');if(original.phase==='unknown')expect(calls.mock.calls[4]?.[0]).toContain('/'+original.flowId+'/publication?');expect(calls.mock.calls[4]?.[1]?.method).toBe('GET');
});
it('keeps saved form selection disabled while publication is in flight',async()=>{
 let resolve!:(response:Response)=>void,n=0;const {client,calls}=await fixture(async()=>++n===1?new Promise<Response>(r=>resolve=r):json({ok:true,data:{publications:savedForms}}));render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fill();fireEvent.click(screen.getByText('Publish staging test form'));await screen.findByText('Publishing the staging form...');fireEvent.click(screen.getByRole('button',{name:'Refresh saved forms'}));await screen.findByText('Saved housekeeping');expect(screen.getByRole('button',{name:'Check receipt for Saved housekeeping'})).toBeDisabled();expect(client.paidSimplePublicationState(tenant).phase).toBe('publishing');expect(calls).toHaveBeenCalledTimes(4);resolve(json({ok:true,data:receipt}));await screen.findByText('Staging form published');
});
it('clears saved forms on tenant change and drops an old late list without disturbing a newer refresh',async()=>{
 let resolveOld!:(response:Response)=>void,resolveNew!:(response:Response)=>void,n=0;const {client,calls}=await fixture(async()=>++n===1?new Promise<Response>(r=>resolveOld=r):new Promise<Response>(r=>resolveNew=r));const {rerender}=render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fireEvent.click(screen.getByRole('button',{name:'Refresh saved forms'}));await waitFor(()=>expect(resolveOld).toBeTypeOf('function'));rerender(<PaidSimplePublisher client={client} tenantId={other} role="BUSINESS_OWNER" services={[{...service,tenant_id:other}]} staging/>);fireEvent.click(screen.getByRole('button',{name:'Refresh saved forms'}));await waitFor(()=>expect(resolveNew).toBeTypeOf('function'));resolveOld(json({ok:true,data:{publications:savedForms}}));await waitFor(()=>expect(calls).toHaveBeenCalledTimes(4));expect(screen.queryByText('Saved housekeeping')).toBeNull();expect(screen.getByRole('button',{name:'Refreshing saved forms...'})).toBeDisabled();resolveNew(json({ok:true,data:{publications:[{...savedForms[0],name:'New business form'}]}}));await screen.findByText('New business form');expect(screen.queryByText('Saved housekeeping')).toBeNull();expect(calls.mock.calls[3]?.[0]).toBe('https://api.example.test/api/paid-simple-flows?tenantId='+other);
});

function fillDraft(){fireEvent.change(screen.getByLabelText('Draft simple service'),{target:{value:serviceId}});fireEvent.change(screen.getByLabelText('Draft name'),{target:{value:'Housekeeping design'}});}
it('explicitly saves design choices and loads persisted fields after a remount without publishing them',async()=>{
 let n=0;const {client,calls}=await fixture(async()=>{const state=client.paidSimpleDraftState(tenant);if(state.phase==='ready')throw Error('fixture requires bound draft');return ++n<=2?json({ok:true,data:{flowId:state.flowId,revision:n}}):json({ok:true,data:{flowId:state.flowId,revision:2,serviceId,name:'Housekeeping design',presentation:{accentColor:'#2563eb',layout:'compact'}}});});const first=render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);expect(calls).toHaveBeenCalledTimes(2);fillDraft();fireEvent.change(screen.getByLabelText('Draft name'),{target:{value:' Housekeeping design '}});fireEvent.change(screen.getByLabelText('Draft accent color'),{target:{value:'#be123c'}});fireEvent.change(screen.getByLabelText('Draft layout'),{target:{value:'compact'}});fireEvent.click(screen.getByRole('button',{name:'Save draft'}));await screen.findByText('Draft revision 1 saved. This draft is not published.');const id=(screen.getByLabelText('Draft ID') as HTMLInputElement).value;expect(id).toMatch(/^[0-9a-f-]{36}$/);expect(screen.getByLabelText('Draft name')).toHaveValue('Housekeeping design');expect(JSON.parse(calls.mock.calls[2]?.[1]?.body as string)).toEqual({serviceId,name:'Housekeeping design',presentation:{accentColor:'#be123c',layout:'compact'},expectedRevision:0});expect(screen.queryByText('Staging form published')).toBeNull();fireEvent.change(screen.getByLabelText('Draft accent color'),{target:{value:'#2563eb'}});fireEvent.click(screen.getByRole('button',{name:'Save draft'}));await screen.findByText('Draft revision 2 saved. This draft is not published.');expect(JSON.parse(calls.mock.calls[3]?.[1]?.body as string).expectedRevision).toBe(1);first.unmount();render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);expect(screen.getByLabelText('Draft ID')).toHaveValue(id);expect(screen.getByLabelText('Draft name')).toHaveValue('');fireEvent.click(screen.getByRole('button',{name:'Load draft'}));await screen.findByText(/Current draft revision 2 loaded/);expect(screen.getByLabelText('Draft name')).toHaveValue('Housekeeping design');expect(screen.getByLabelText('Draft accent color')).toHaveValue('#2563eb');expect(screen.getByLabelText('Draft layout')).toHaveValue('compact');expect(calls.mock.calls[4]?.[1]?.method).toBe('GET');expect(calls.mock.calls.slice(2).every(([url])=>String(url).includes('/'+id+'/draft?tenantId='+tenant))).toBe(true);expect(client.paidSimplePublicationState(tenant)).toEqual({phase:'ready'});expect(document.body.textContent).not.toContain('synthetic-owner-private-token');
});
it('requires loading an existing draft, retains conflict edits, then saves with the fresh server revision',async()=>{
 let n=0;const {client,calls}=await fixture(async()=>++n===1?json({ok:true,data:{flowId:other,revision:7,serviceId,name:'Server draft',presentation:{accentColor:'#0e7490',layout:'stacked'}}}):n===2?json({ok:false,code:'CONFLICT'},409):n===3?json({ok:true,data:{flowId:other,revision:8,serviceId,name:'Another owner edit',presentation:{accentColor:'#2563eb',layout:'compact'}}}):json({ok:true,data:{flowId:other,revision:9}}));render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fireEvent.change(screen.getByLabelText('Draft ID'),{target:{value:other}});expect(screen.getByRole('button',{name:'Save draft'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'Load draft'}));await screen.findByText(/Current draft revision 7 loaded/);expect(screen.getByLabelText('Draft accent color')).toHaveValue('#0e7490');fireEvent.change(screen.getByLabelText('Draft name'),{target:{value:'My unsaved name'}});fireEvent.click(screen.getByRole('button',{name:'Save draft'}));await screen.findByText(/draft revision changed/);expect(screen.getByLabelText('Draft name')).toHaveValue('My unsaved name');expect(screen.getByRole('button',{name:'Save draft'})).toBeDisabled();expect(JSON.parse(calls.mock.calls[3]?.[1]?.body as string).expectedRevision).toBe(7);fireEvent.click(screen.getByRole('button',{name:'Load draft'}));await screen.findByText(/Current draft revision 8 loaded/);expect(screen.getByLabelText('Draft name')).toHaveValue('Another owner edit');expect(screen.getByLabelText('Draft layout')).toHaveValue('compact');fireEvent.change(screen.getByLabelText('Draft name'),{target:{value:'Updated draft'}});fireEvent.click(screen.getByRole('button',{name:'Save draft'}));await screen.findByText('Draft revision 9 saved. This draft is not published.');expect(JSON.parse(calls.mock.calls[5]?.[1]?.body as string).expectedRevision).toBe(8);expect(screen.queryByText('Staging form published')).toBeNull();
});
it('keeps uncertain draft saves locked after remount and missing reads without changing publication uncertainty',async()=>{
 let n=0;const {client,calls}=await fixture(async()=>{if(++n===1)return json({ok:false,code:'INTERNAL_ERROR'},500);if(n===2)throw Error('private-draft-secret');if(n===3)return json({ok:false,code:'NOT_AVAILABLE'},404);const state=client.paidSimpleDraftState(tenant);if(state.phase==='ready')throw Error('fixture requires draft');return json({ok:true,data:{flowId:state.flowId,revision:1,serviceId,name:'Current persisted draft',presentation:{accentColor:'#0f766e',layout:'stacked'}}});});await client.publishPaidSimple(tenant,other,{serviceId,name:'Unverified publication',checkoutOrigin:STAGING_CHECKOUT_ORIGIN}).catch(()=>{});const publication=client.paidSimplePublicationState(tenant);const first=render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fillDraft();fireEvent.click(screen.getByRole('button',{name:'Save draft'}));await screen.findByText(/Draft save status is unverified/);const id=(screen.getByLabelText('Draft ID') as HTMLInputElement).value;expect(screen.getByRole('button',{name:'Save draft'})).toBeDisabled();first.unmount();render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);expect(screen.getByLabelText('Draft ID')).toHaveValue(id);expect(screen.getByLabelText('Draft ID')).toHaveAttribute('readonly');fireEvent.click(screen.getByRole('button',{name:'Load draft'}));await screen.findByText(/This draft is unavailable/);expect(screen.getByRole('button',{name:'Save draft'})).toBeDisabled();expect(client.paidSimplePublicationState(tenant)).toEqual(publication);fireEvent.click(screen.getByRole('button',{name:'Load draft'}));await screen.findByText(/Current draft revision 1 loaded/);expect(screen.getByLabelText('Draft name')).toHaveValue('Current persisted draft');expect(screen.getByRole('button',{name:'Save draft'})).toBeEnabled();expect(client.paidSimplePublicationState(tenant)).toEqual(publication);expect(calls).toHaveBeenCalledTimes(6);expect(calls.mock.calls[4]?.[1]?.method).toBe('GET');expect(calls.mock.calls[5]?.[1]?.method).toBe('GET');expect(document.body.textContent).not.toContain('private-draft-secret');expect(screen.queryByText('Staging form published')).toBeNull();
});
it('permits an explicit corrected first draft after definitive rejection, without any automatic retry',async()=>{
 let n=0;const {client,calls}=await fixture(async()=>{if(++n===1)return json({ok:false,code:'UNSUPPORTED_CONFIG'},422);const state=client.paidSimpleDraftState(tenant);if(state.phase==='ready')throw Error('fixture requires draft');return json({ok:true,data:{flowId:state.flowId,revision:1}});});render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fillDraft();fireEvent.click(screen.getByRole('button',{name:'Save draft'}));await screen.findByText(/does not support staging paid drafts/);expect(screen.getByLabelText('Draft name')).toHaveValue('Housekeeping design');expect(screen.getByLabelText('Draft ID')).toHaveValue('');expect(calls).toHaveBeenCalledTimes(3);fireEvent.click(screen.getByRole('button',{name:'Save draft'}));await screen.findByText('Draft revision 1 saved. This draft is not published.');expect(JSON.parse(calls.mock.calls[3]?.[1]?.body as string).expectedRevision).toBe(0);expect(calls).toHaveBeenCalledTimes(4);
});
it('clears draft fields on tenant change and cannot show a late old save receipt',async()=>{
 let resolve!:(response:Response)=>void;const {client}=await fixture(()=>new Promise<Response>(r=>resolve=r));const {rerender}=render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fillDraft();fireEvent.change(screen.getByLabelText('Draft accent color'),{target:{value:'#be123c'}});fireEvent.click(screen.getByRole('button',{name:'Save draft'}));await waitFor(()=>expect(resolve).toBeTypeOf('function'));const id=(screen.getByLabelText('Draft ID') as HTMLInputElement).value;rerender(<PaidSimplePublisher client={client} tenantId={other} role="BUSINESS_OWNER" services={[{...service,tenant_id:other}]} staging/>);expect(screen.getByLabelText('Draft ID')).toHaveValue('');expect(screen.getByLabelText('Draft name')).toHaveValue('');expect(screen.getByLabelText('Draft accent color')).toHaveValue('#4f46e5');resolve(json({ok:true,data:{flowId:id,revision:1}}));await waitFor(()=>expect(client.paidSimpleDraftState(tenant).phase).toBe('saved'));expect(screen.queryByText('Draft revision 1 saved. This draft is not published.')).toBeNull();expect(client.paidSimpleDraftState(other)).toEqual({phase:'ready'});
});
it('discards a late draft load after sign-out and does not expose draft controls to staff',async()=>{
 let resolve!:(response:Response)=>void;const {client}=await fixture(()=>new Promise<Response>(r=>resolve=r));const {rerender}=render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fireEvent.change(screen.getByLabelText('Draft ID'),{target:{value:other}});fireEvent.click(screen.getByRole('button',{name:'Load draft'}));await waitFor(()=>expect(resolve).toBeTypeOf('function'));client.signOut();rerender(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_STAFF" services={[service]} staging/>);resolve(json({ok:true,data:{flowId:other,revision:1,serviceId,name:'Private old draft',presentation:{accentColor:'#be123c',layout:'compact'}}}));await waitFor(()=>expect(client.paidSimpleDraftState(tenant)).toEqual({phase:'ready'}));expect(screen.queryByText('Private old draft')).toBeNull();expect(screen.queryByLabelText('Draft name')).toBeNull();
});
it('validates draft IDs and prevents overflowing a maximum persisted revision',async()=>{
 const {client,calls}=await fixture(async()=>json({ok:true,data:{flowId:other,revision:Number.MAX_SAFE_INTEGER,serviceId,name:'Last draft revision',presentation:{accentColor:'#2563eb',layout:'compact'}}}));render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fireEvent.change(screen.getByLabelText('Draft ID'),{target:{value:'invalid'}});fireEvent.click(screen.getByRole('button',{name:'Load draft'}));await screen.findByText('Enter a known draft ID before loading.');expect(calls).toHaveBeenCalledTimes(2);fireEvent.change(screen.getByLabelText('Draft ID'),{target:{value:other}});fireEvent.click(screen.getByRole('button',{name:'Load draft'}));await screen.findByText('The maximum draft revision was reached. Further saves are unavailable.');expect(screen.getByRole('button',{name:'Save draft'})).toBeDisabled();expect(calls).toHaveBeenCalledTimes(3);
});

it.each(['saved','uncertain'])('reconciles a remounted pending %s draft save without another POST or replacement identity',async(outcome)=>{
 let resolve!:(response:Response)=>void,n=0;const {client,calls}=await fixture(async()=>{if(++n===1)return new Promise<Response>(r=>resolve=r);const state=client.paidSimpleDraftState(tenant);if(state.phase==='ready')throw Error('fixture requires draft');if(outcome==='uncertain'&&n===2)return json({ok:false,code:'NOT_AVAILABLE'},404);return json({ok:true,data:{flowId:state.flowId,revision:1,serviceId,name:'Current persisted design',presentation:{accentColor:'#2563eb',layout:'compact'}}});});const first=render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fillDraft();fireEvent.click(screen.getByRole('button',{name:'Save draft'}));await waitFor(()=>expect(resolve).toBeTypeOf('function'));const id=(screen.getByLabelText('Draft ID') as HTMLInputElement).value;first.unmount();render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);expect(screen.getByRole('button',{name:'Load draft'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:"Check this session's draft state"}));expect(screen.getByRole('button',{name:'Load draft'})).toBeDisabled();expect(calls).toHaveBeenCalledTimes(3);resolve(outcome==='saved'?json({ok:true,data:{flowId:id,revision:1}}):json({ok:false,code:'INTERNAL_ERROR'},500));await waitFor(()=>expect(client.paidSimpleDraftState(tenant).phase).toBe(outcome==='saved'?'saved':'unverified'));fireEvent.click(screen.getByRole('button',{name:"Check this session's draft state"}));expect(screen.getByRole('button',{name:'Load draft'})).toBeEnabled();expect(screen.getByLabelText('Draft ID')).toHaveValue(id);expect(screen.getByLabelText('Draft name')).toHaveValue('');if(outcome==='uncertain'){expect(screen.getByRole('button',{name:'Save draft'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'Load draft'}));await screen.findByText(/This draft is unavailable/);expect(screen.getByRole('button',{name:'Save draft'})).toBeDisabled();expect(screen.getByLabelText('Draft ID')).toHaveValue(id);}fireEvent.click(screen.getByRole('button',{name:'Load draft'}));await screen.findByText(/Current draft revision 1 loaded/);expect(screen.getByLabelText('Draft name')).toHaveValue('Current persisted design');expect(screen.getByRole('button',{name:'Save draft'})).toBeEnabled();expect(calls.mock.calls.slice(2).filter(([,options])=>options?.method==='POST')).toHaveLength(1);expect(calls.mock.calls.slice(3).every(([,options])=>options?.method==='GET')).toBe(true);expect(client.paidSimplePublicationState(tenant)).toEqual({phase:'ready'});
});
it('reconciles a remounted pending draft load and permits an explicit fresh read after completion',async()=>{
 let resolve!:(response:Response)=>void,n=0;const dto={flowId:other,revision:4,serviceId,name:'Stored design',presentation:{accentColor:'#0f766e',layout:'stacked'}};const {client,calls}=await fixture(async()=>++n===1?new Promise<Response>(r=>resolve=r):json({ok:true,data:dto}));const first=render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fireEvent.change(screen.getByLabelText('Draft ID'),{target:{value:other}});fireEvent.click(screen.getByRole('button',{name:'Load draft'}));await waitFor(()=>expect(resolve).toBeTypeOf('function'));first.unmount();render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);expect(screen.getByRole('button',{name:'Load draft'})).toBeDisabled();resolve(json({ok:true,data:dto}));await waitFor(()=>expect(client.paidSimpleDraftState(tenant).phase).toBe('loaded'));fireEvent.click(screen.getByRole('button',{name:"Check this session's draft state"}));expect(screen.getByRole('button',{name:'Load draft'})).toBeEnabled();expect(calls).toHaveBeenCalledTimes(3);fireEvent.click(screen.getByRole('button',{name:'Load draft'}));await screen.findByText(/Current draft revision 4 loaded/);expect(screen.getByLabelText('Draft name')).toHaveValue('Stored design');expect(screen.getByRole('button',{name:'Save draft'})).toBeEnabled();expect(calls).toHaveBeenCalledTimes(4);expect(calls.mock.calls.slice(2).every(([,options])=>options?.method==='GET')).toBe(true);
});
it('reconciles a remounted pending publication through its existing session-state check without repeating the writer',async()=>{
 let resolve!:(response:Response)=>void;const {client,calls}=await fixture(()=>new Promise<Response>(r=>resolve=r));const first=render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fill();fireEvent.click(screen.getByText('Publish staging test form'));await waitFor(()=>expect(resolve).toBeTypeOf('function'));first.unmount();render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);resolve(json({ok:true,data:receipt}));await waitFor(()=>expect(client.paidSimplePublicationState(tenant).phase).toBe('published'));fireEvent.click(screen.getByRole('button',{name:"Check this session's receipt"}));await screen.findByText('Staging form published');expect(calls).toHaveBeenCalledTimes(3);expect(calls.mock.calls[2]?.[1]?.method).toBe('POST');expect(screen.queryByText('Publish staging test form')).toBeNull();
});
it('permits a fresh explicit receipt read after remounting an in-flight publication recovery without any writer',async()=>{
 let resolve!:(response:Response)=>void,n=0;const {client,calls}=await fixture(async()=>++n===1?new Promise<Response>(r=>resolve=r):json({ok:true,data:receipt}));const first=render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fireEvent.change(screen.getByLabelText('Publication attempt ID'),{target:{value:other}});fireEvent.click(screen.getByRole('button',{name:'Check publication receipt'}));await waitFor(()=>expect(resolve).toBeTypeOf('function'));first.unmount();render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);expect(screen.getByRole('button',{name:'Check publication receipt'})).toBeEnabled();resolve(json({ok:true,data:receipt}));await waitFor(()=>expect(client.paidSimplePublicationState(tenant).phase).toBe('published'));fireEvent.click(screen.getByRole('button',{name:'Check publication receipt'}));await screen.findByText('Staging form published');expect(calls).toHaveBeenCalledTimes(4);expect(calls.mock.calls.slice(2).every(([,options])=>options?.method==='GET')).toBe(true);
});

const publishDraftDto={flowId:other,revision:3,serviceId,name:'Stored design',presentation:{accentColor:'#0f766e',layout:'compact'}};
async function loadKnownDraft(){fireEvent.change(screen.getByLabelText('Draft ID'),{target:{value:other}});fireEvent.click(screen.getByRole('button',{name:'Load draft'}));await screen.findByText(/Current draft revision 3 loaded/);}
it('publishes only pristine loaded server fields and displays the canonical immutable saved revision receipt',async()=>{
 let n=0;const {client,calls}=await fixture(async()=>++n===1?json({ok:true,data:publishDraftDto}):json({ok:true,data:{flowId:other,draftRevision:3,publication:receipt}}));render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);expect(screen.getByRole('button',{name:'Publish saved draft'})).toBeDisabled();await loadKnownDraft();expect(screen.getByRole('button',{name:'Publish saved draft'})).toBeEnabled();fireEvent.change(screen.getByLabelText('Draft name'),{target:{value:'Unsaved name'}});expect(screen.getByRole('button',{name:'Publish saved draft'})).toBeDisabled();fireEvent.change(screen.getByLabelText('Draft name'),{target:{value:publishDraftDto.name}});fireEvent.click(screen.getByRole('button',{name:'Publish saved draft'}));await screen.findByText('Staging form published');expect(calls.mock.calls[3]?.[0]).toContain('/'+other+'/publish-draft?tenantId='+tenant);expect(JSON.parse(calls.mock.calls[3]?.[1]?.body as string)).toEqual({expectedDraftRevision:3,allowedOrigins:[STAGING_CHECKOUT_ORIGIN]});expect(screen.getByText(/Published draft revision: 3; immutable version:/)).toBeTruthy();expect(screen.getByRole('link',{name:'Open staging booking form'})).toHaveAttribute('href',STAGING_CHECKOUT_ORIGIN+receipt.hostedPath);expect((screen.getByLabelText('Website iframe code') as HTMLTextAreaElement).value).toContain(STAGING_CHECKOUT_ORIGIN+receipt.hostedPath);expect(screen.queryByText('Publish staging test form')).toBeNull();expect(screen.getByRole('button',{name:'Publish saved draft'})).toBeDisabled();
});
it('freezes a lost saved publication through remount and conflict then explicitly retries identical bytes without draft changes',async()=>{
 let n=0;const {client,calls}=await fixture(async()=>++n===1?json({ok:true,data:publishDraftDto}):n===2?Promise.reject(Error('private failure')):n===3?json({ok:false,code:'CONFLICT'},409):json({ok:true,data:{flowId:other,draftRevision:3,publication:receipt}}));const first=render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);await loadKnownDraft();fireEvent.click(screen.getByRole('button',{name:'Publish saved draft'}));await screen.findByRole('button',{name:'Retry this saved-draft publication'});expect(screen.getByLabelText('Draft name')).toBeDisabled();expect(screen.getByRole('button',{name:'Load draft'})).toBeDisabled();first.unmount();render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);expect(calls).toHaveBeenCalledTimes(4);fireEvent.click(screen.getByRole('button',{name:'Retry this saved-draft publication'}));await screen.findByText(/This response does not prove the earlier attempt failed/);expect(screen.getByRole('button',{name:'Save draft'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'Retry this saved-draft publication'}));await screen.findByText('Staging form published');expect(calls.mock.calls.slice(3).every(([url,options])=>String(url).includes('/'+other+'/publish-draft?')&&options?.body===calls.mock.calls[3]?.[1]?.body)).toBe(true);expect(document.body.textContent).not.toContain('private failure');
});
it('settles an in-flight saved publication after remount only through explicit session reconciliation with no extra writer',async()=>{
 let n=0,resolve!:(response:Response)=>void;const {client,calls}=await fixture(async()=>++n===1?json({ok:true,data:publishDraftDto}):new Promise(r=>resolve=r));const first=render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);await loadKnownDraft();fireEvent.click(screen.getByRole('button',{name:'Publish saved draft'}));await waitFor(()=>expect(resolve).toBeTypeOf('function'));first.unmount();render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);expect(screen.getByRole('button',{name:'Publish saved draft'})).toBeDisabled();resolve(json({ok:true,data:{flowId:other,draftRevision:3,publication:receipt}}));await waitFor(()=>expect(client.paidSimpleSavedDraftPublicationState(tenant).phase).toBe('published'));fireEvent.click(screen.getByRole('button',{name:"Check this session's saved publication state"}));await screen.findByText('Staging form published');expect(screen.getByRole('button',{name:'Load draft'})).toBeEnabled();expect(calls).toHaveBeenCalledTimes(4);
});
it('allows a fresh draft read after first definitive conflict but never publishes a legacy uncertain attempt',async()=>{
 let n=0;const {client,calls}=await fixture(async()=>++n===1?json({ok:true,data:publishDraftDto}):n===2?json({ok:false,code:'CONFLICT'},409):n===3?json({ok:true,data:publishDraftDto}):json({ok:false,code:'INTERNAL_ERROR'},500));render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);await loadKnownDraft();fireEvent.click(screen.getByRole('button',{name:'Publish saved draft'}));await screen.findByText(/Saved-draft publication was rejected/);expect(screen.getByRole('button',{name:'Publish saved draft'})).toBeDisabled();expect(screen.getByRole('button',{name:'Load draft'})).toBeEnabled();fireEvent.click(screen.getByRole('button',{name:'Load draft'}));await screen.findByText(/Current draft revision 3 loaded/);fill();fireEvent.click(screen.getByRole('button',{name:'Publish staging test form'}));await screen.findByText(/Publishing again is locked/);expect(screen.getByRole('button',{name:'Publish saved draft'})).toBeDisabled();expect(calls).toHaveBeenCalledTimes(6);
});

it.each([['Draft simple service',''],['Draft accent color','#be123c'],['Draft layout','stacked']])('denies saved publication with unsaved %s changes',async(label,value)=>{
 const {client,calls}=await fixture(async()=>json({ok:true,data:publishDraftDto}));render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);await loadKnownDraft();fireEvent.change(screen.getByLabelText(label),{target:{value}});expect(screen.getByRole('button',{name:'Publish saved draft'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'Publish saved draft'}));expect(calls).toHaveBeenCalledTimes(3);
});
it('drops a late saved publication receipt when the selected tenant changes without leaking old fields or version',async()=>{
 let n=0,resolve!:(response:Response)=>void;const {client}=await fixture(async()=>++n===1?json({ok:true,data:publishDraftDto}):new Promise(r=>resolve=r));const {rerender}=render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);await loadKnownDraft();fireEvent.click(screen.getByRole('button',{name:'Publish saved draft'}));await waitFor(()=>expect(resolve).toBeTypeOf('function'));rerender(<PaidSimplePublisher client={client} tenantId={other} role="BUSINESS_OWNER" services={[{...service,tenant_id:other}]} staging/>);expect(screen.getByLabelText('Draft name')).toHaveValue('');resolve(json({ok:true,data:{flowId:other,draftRevision:3,publication:receipt}}));await waitFor(()=>expect(client.paidSimpleSavedDraftPublicationState(tenant).phase).toBe('published'));expect(screen.queryByText('Staging form published')).toBeNull();expect(screen.queryByText(/Published draft revision:/)).toBeNull();expect(client.paidSimpleSavedDraftPublicationState(other)).toEqual({phase:'ready'});
});

it('reconciles an uncertain pending saved publication after remount without replaying and leaves only explicit frozen retry available',async()=>{
 let n=0,resolve!:(response:Response)=>void;const {client,calls}=await fixture(async()=>++n===1?json({ok:true,data:publishDraftDto}):new Promise(r=>resolve=r));const first=render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);await loadKnownDraft();fireEvent.click(screen.getByRole('button',{name:'Publish saved draft'}));await waitFor(()=>expect(resolve).toBeTypeOf('function'));first.unmount();render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);resolve(json({ok:false,code:'INTERNAL_ERROR'},500));await waitFor(()=>expect(client.paidSimpleSavedDraftPublicationState(tenant).phase).toBe('unknown'));fireEvent.click(screen.getByRole('button',{name:"Check this session's saved publication state"}));expect(screen.getByRole('button',{name:'Retry this saved-draft publication'})).toBeEnabled();expect(screen.getByRole('button',{name:'Save draft'})).toBeDisabled();expect(screen.getByRole('button',{name:'Load draft'})).toBeDisabled();expect(screen.queryByRole('button',{name:'Check publication receipt'})).toBeNull();expect(screen.queryByText('Staging form published')).toBeNull();expect(calls).toHaveBeenCalledTimes(4);
});
