import {useEffect,useRef,useState,type FormEvent} from 'react';
import {formatMoney} from '@lumin/contracts';
import {PaidSimpleDraftPreview} from './PaidSimpleDraftPreview';
import {PublicationError,type RuntimeClient,type ServiceRow,type PaidSimplePublicationState,type SavedPaidSimplePublication,PAID_SIMPLE_ACCENT_COLORS,PaidSimpleDraftError,type PaidSimpleDraftState,type PaidSimplePresentation,type PaidSimpleOwnerDraft,type PaidSimpleVersionHistory} from '@lumin/runtime-client';
export const STAGING_CHECKOUT_ORIGIN='https://booking-lumin-checkout-staging.netlify.app';
type PublisherClient=Pick<RuntimeClient,'publishPaidSimple'|'recoverPaidSimplePublication'|'listPaidSimplePublications'|'paidSimplePublicationState'|'loadPaidSimpleDraft'|'savePaidSimpleDraft'|'paidSimpleDraftState'|'publishPaidSimpleDraft'|'paidSimpleSavedDraftPublicationState'|'listPaidSimpleDrafts'|'paidSimpleVersionHistory'|'rollbackPaidSimplePublication'|'reconcilePaidSimpleRollback'|'paidSimpleRollbackState'>;
type SavedForms={phase:'idle'|'loading'|'loaded'|'failed';items:readonly SavedPaidSimplePublication[];error:string};
type SavedDrafts={phase:'idle'|'loading'|'loaded'|'failed';items:readonly PaidSimpleOwnerDraft[];error:string};
type DraftFields={flowId:string;serviceId:string;name:string;presentation:PaidSimplePresentation};
type DraftEditorState={client:PublisherClient;tenantId:string;state:PaidSimpleDraftState;fields:DraftFields;notice:string;error:string};
function draftEditorState(client:PublisherClient,tenantId:string):DraftEditorState{
 const state=client.paidSimpleDraftState(tenantId);
 const fields:DraftFields=state.phase==='loaded'?{flowId:state.flowId,serviceId:state.draft.serviceId,name:state.draft.name,presentation:{...state.draft.presentation}}:{flowId:state.phase==='ready'?'':state.flowId,serviceId:'',name:'',presentation:{accentColor:'#4f46e5',layout:'stacked'}};
 return {client,tenantId,state,fields,notice:'',error:''};
}
function PaidSimpleDraftEditor({client,tenantId,services,catalogLoading,onPublicationChange,rollbackLocked}:{client:PublisherClient;tenantId:string;services:ServiceRow[];catalogLoading:boolean;onPublicationChange:()=>void;rollbackLocked:boolean}){
 const [savedDraftSnapshot,setSavedDraftSnapshot]=useState<{client:PublisherClient;tenantId:string;list:SavedDrafts}>(()=>({client,tenantId,list:{phase:'idle',items:[],error:''}}));const draftListInFlight=useRef(false);
 const [previewScope,setPreviewScope]=useState<{client:PublisherClient;tenantId:string}|null>(null);
 const [publicationSnapshot,setPublicationSnapshot]=useState(()=>({client,tenantId,state:client.paidSimpleSavedDraftPublicationState(tenantId)}));
 const [snapshot,setSnapshot]=useState(()=>draftEditorState(client,tenantId));const generation=useRef(0),inFlight=useRef(false);
 useEffect(()=>{generation.current++;inFlight.current=false;draftListInFlight.current=false;setPreviewScope(null);setSavedDraftSnapshot({client,tenantId,list:{phase:'idle',items:[],error:''}});setSnapshot(draftEditorState(client,tenantId));setPublicationSnapshot({client,tenantId,state:client.paidSimpleSavedDraftPublicationState(tenantId)});return()=>{generation.current++;}},[client,tenantId]);
 const editor=snapshot.client===client&&snapshot.tenantId===tenantId?snapshot:draftEditorState(client,tenantId);
 const savedDrafts:SavedDrafts=savedDraftSnapshot.client===client&&savedDraftSnapshot.tenantId===tenantId?savedDraftSnapshot.list:{phase:'idle',items:[],error:''};
 const {fields,state}=editor;const busy=state.phase==='saving'||state.phase==='loading';
 const savedPublication=publicationSnapshot.client===client&&publicationSnapshot.tenantId===tenantId?publicationSnapshot.state:client.paidSimpleSavedDraftPublicationState(tenantId);
 const publicationLocked=rollbackLocked||savedPublication.phase==='publishing'||savedPublication.phase==='unknown';
 const pristine=state.phase==='loaded'&&fields.flowId===state.flowId&&fields.serviceId===state.draft.serviceId&&fields.name===state.draft.name&&fields.presentation.accentColor===state.draft.presentation.accentColor&&fields.presentation.layout===state.draft.presentation.layout;
 const canPublish=!rollbackLocked&&!busy&&!catalogLoading&&pristine&&savedPublication.phase!=='publishing'&&(savedPublication.phase!=='published'||savedPublication.flowId!==fields.flowId||savedPublication.draftRevision!==state.revision)&&(client.paidSimplePublicationState(tenantId).phase==='ready'||savedPublication.phase==='published'&&client.paidSimplePublicationState(tenantId).phase==='published');
 const revision=state.phase==='saved'||state.phase==='loaded'?state.revision:undefined;
 const blocked=state.phase==='unverified'||state.phase==='conflict';
 const canSave=!publicationLocked&&!busy&&!blocked&&!catalogLoading&&(state.phase!=='ready'||!fields.flowId.trim())&&(revision===undefined||revision<Number.MAX_SAFE_INTEGER);
 function edit(change:Partial<DraftFields>){setSnapshot({...editor,fields:{...fields,...change},notice:'Unsaved draft edits. Save draft to persist them.',error:''});}
 function checkSessionDraftState(){const next=client.paidSimpleDraftState(tenantId);setSnapshot({...editor,state:next,fields:{...fields,flowId:next.phase==='ready'?'':next.flowId},notice:'The draft state held in this session was checked. Load draft to refresh the current persisted fields.',error:''});}
 async function save(event:FormEvent){
  event.preventDefault();if(!canSave||inFlight.current)return;
  if(!services.some(service=>service.id===fields.serviceId)||!fields.name.trim()||fields.name.trim().length>200){setSnapshot({...editor,error:'Choose a supported simple service and enter a draft name.'});return;}
  const flowId=state.phase==='ready'?crypto.randomUUID():state.flowId,expectedRevision=revision??0,at=generation.current;
  inFlight.current=true;setSnapshot({...editor,state:{phase:'saving',flowId},fields:{...fields,flowId},notice:'',error:''});
  try{const promise=client.savePaidSimpleDraft(tenantId,flowId,{serviceId:fields.serviceId,name:fields.name.trim(),presentation:{...fields.presentation},expectedRevision});onPublicationChange();const receipt=await promise;if(at===generation.current)setSnapshot({...editor,state:client.paidSimpleDraftState(tenantId),fields:{...fields,flowId,name:fields.name.trim()},notice:`Draft revision ${receipt.revision} saved. This draft is not published.`,error:''});}
  catch(error){if(at===generation.current){const next=client.paidSimpleDraftState(tenantId);const retainedId=next.phase!=='ready'?next.flowId:state.phase==='ready'&&error instanceof PaidSimpleDraftError&&error.delivery==='rejected'?'':flowId;setSnapshot({...editor,state:next,fields:{...fields,flowId:retainedId},notice:'',error:error instanceof PaidSimpleDraftError?error.message:'Draft save status is unverified. Load this same draft before saving again.'});}}
  finally{if(at===generation.current){inFlight.current=false;onPublicationChange();}}
 }
 async function load(selectedFlowId=fields.flowId){
  if(publicationLocked||busy||inFlight.current)return;const flowId=selectedFlowId.trim().toLowerCase();
  if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/.test(flowId)){setSnapshot({...editor,error:'Enter a known draft ID before loading.'});return;}
  const at=generation.current;inFlight.current=true;setSnapshot({...editor,state:{phase:'loading',flowId},fields:{...fields,flowId},notice:'',error:''});
  try{const promise=client.loadPaidSimpleDraft(tenantId,flowId);onPublicationChange();const draft=await promise;if(at===generation.current)setSnapshot({client,tenantId,state:client.paidSimpleDraftState(tenantId),fields:{flowId:draft.flowId,serviceId:draft.serviceId,name:draft.name,presentation:{...draft.presentation}},notice:`Current draft revision ${draft.revision} loaded. This read shows current persisted fields; it does not verify a past uncertain save.`,error:''});}
  catch(error){if(at===generation.current)setSnapshot({...editor,state:client.paidSimpleDraftState(tenantId),fields:{...fields,flowId},notice:'',error:error instanceof PaidSimpleDraftError?error.message:'Current draft fields remain unverified. Load this same draft again before saving.'});}
  finally{if(at===generation.current){inFlight.current=false;onPublicationChange();}}
 }
 async function refreshDrafts(){
  if(draftListInFlight.current)return;const at=generation.current;draftListInFlight.current=true;setSavedDraftSnapshot({client,tenantId,list:{phase:'loading',items:[],error:''}});
  try{const items=await client.listPaidSimpleDrafts(tenantId);if(at===generation.current)setSavedDraftSnapshot({client,tenantId,list:{phase:'loaded',items,error:''}});}
  catch(error){if(at===generation.current)setSavedDraftSnapshot({client,tenantId,list:{phase:'failed',items:[],error:error instanceof PaidSimpleDraftError?error.message:'Saved drafts could not be verified. This does not release an uncertain save or publication.'}});}
  finally{if(at===generation.current)draftListInFlight.current=false;}
 }
 function checkPublicationState(){setPublicationSnapshot({client,tenantId,state:client.paidSimpleSavedDraftPublicationState(tenantId)});onPublicationChange();}
 async function publishSaved(){
  const retry=savedPublication.phase==='unknown';if(inFlight.current||savedPublication.phase==='publishing'||(!retry&&!canPublish))return;
  const flowId=retry?savedPublication.flowId:fields.flowId,draftRevision=retry?savedPublication.draftRevision:state.phase==='loaded'?state.revision:0,checkoutOrigin=retry?savedPublication.checkoutOrigin:STAGING_CHECKOUT_ORIGIN,at=generation.current;
  inFlight.current=true;const promise=client.publishPaidSimpleDraft(tenantId,flowId,{expectedDraftRevision:draftRevision,checkoutOrigin});checkPublicationState();
  try{const receipt=await promise;if(at===generation.current){setSnapshot({...editor,notice:`Saved draft revision ${receipt.draftRevision} published as an immutable staging version.`,error:''});checkPublicationState();}}
  catch(error){if(at===generation.current){setSnapshot({...editor,state:client.paidSimpleDraftState(tenantId),notice:'',error:error instanceof PublicationError?error.message:'Saved-draft publication status is unverified.'});checkPublicationState();}}
  finally{if(at===generation.current){inFlight.current=false;onPublicationChange();}}
 }
 return <section aria-label="Saved draft design"><h2>Draft design</h2><p>Save or load a staging draft for this business. Draft saves do not publish a form or change its price. Load the saved fields before explicitly publishing this draft revision. The separate new-form action below does not use this draft.</p><section aria-label="Saved staging drafts"><h3>Saved staging drafts</h3><p>Refresh to find up to 50 saved drafts for this business. Selecting one loads its current fields and replaces local edits. A list entry does not verify an uncertain save or publication, or make a draft published.</p><button type="button" disabled={savedDrafts.phase==='loading'} onClick={()=>void refreshDrafts()}>{savedDrafts.phase==='loading'?'Refreshing saved drafts...':'Refresh saved drafts'}</button>{savedDrafts.phase==='loading'&&<p role="status">Checking saved staging drafts...</p>}{savedDrafts.phase==='loaded'&&!savedDrafts.items.length&&<p role="status">No saved drafts were returned. This does not permit repeating an uncertain save or publication.</p>}{savedDrafts.error&&<p role="alert">{savedDrafts.error}</p>}{savedDrafts.items.length>0&&<ul>{savedDrafts.items.map(item=><li key={item.flowId}><h4>{item.name}</h4><p>Draft ID: {item.flowId}</p><p>Draft revision at last refresh: {item.revision}</p><button type="button" disabled={publicationLocked||busy||blocked&&state.flowId!==item.flowId} onClick={()=>void load(item.flowId)}>Load saved draft: {item.name}</button></li>)}</ul>}</section><form onSubmit={save}><fieldset disabled={busy||publicationLocked} className="form-stack" style={{minWidth:0}}>
  <label>Draft ID<input value={fields.flowId} readOnly={state.phase!=='ready'} onChange={event=>edit({flowId:event.target.value})} style={{width:'100%',maxWidth:'100%',minWidth:0}}/></label><p>Leave the ID empty for a new draft. To edit an existing draft, enter its ID and load it first. Keep the ID for loading after a reload.</p>
  <label>Draft simple service<select required disabled={catalogLoading} value={fields.serviceId} onChange={event=>edit({serviceId:event.target.value})}><option value="">Choose a service</option>{fields.serviceId&&!services.some(service=>service.id===fields.serviceId)&&<option value={fields.serviceId}>Saved service (unavailable in the current catalog)</option>}{services.map(service=><option key={service.id} value={service.id}>{service.name}</option>)}</select></label>
  <label>Draft name<input required maxLength={200} value={fields.name} onChange={event=>edit({name:event.target.value})}/></label>
  <label>Draft accent color<select value={fields.presentation.accentColor} onChange={event=>{const accentColor=PAID_SIMPLE_ACCENT_COLORS.find(color=>color===event.target.value);if(accentColor)edit({presentation:{...fields.presentation,accentColor}});}}>{PAID_SIMPLE_ACCENT_COLORS.map((color,index)=><option key={color} value={color}>{['Indigo','Cyan','Teal','Blue','Rose'][index]}</option>)}</select></label>
  <label>Draft layout<select value={fields.presentation.layout} onChange={event=>{const layout=event.target.value;if(layout==='stacked'||layout==='compact')edit({presentation:{...fields.presentation,layout}});}}><option value="stacked">Stacked</option><option value="compact">Compact</option></select></label>
  {revision!==undefined&&<p>Last verified draft revision: {revision}</p>}{revision===Number.MAX_SAFE_INTEGER&&<p role="alert">The maximum draft revision was reached. Further saves are unavailable.</p>}
  <button type="submit" disabled={!canSave}>Save draft</button><button type="button" disabled={publicationLocked||busy||!fields.flowId.trim()} onClick={()=>void load()}>Load draft</button><p>Loading replaces the local draft fields with the server's current fields.</p>
 </fieldset></form><button type="button" onClick={()=>setPreviewScope({client,tenantId})}>Preview draft presentation</button>{previewScope?.client===client&&previewScope.tenantId===tenantId&&<PaidSimpleDraftPreview name={fields.name} presentation={fields.presentation} service={services.find(service=>service.id===fields.serviceId)} catalogLoading={catalogLoading}/>}<p>Publishing uses the saved server service, name and design. Checkout origin: {STAGING_CHECKOUT_ORIGIN}. Staging test payments only.</p><button type="button" disabled={rollbackLocked||(savedPublication.phase==='unknown'?false:!canPublish)} onClick={()=>void publishSaved()}>{savedPublication.phase==='unknown'?'Retry this saved-draft publication':'Publish saved draft'}</button>{!pristine&&!publicationLocked&&<p>Save changes and load the current draft before publishing.</p>}{(savedPublication.phase==='publishing'||savedPublication.phase==='unknown')&&<><p role="status">{savedPublication.phase==='publishing'?'Publishing saved draft...':'Saved-draft publication status is unverified. Draft changes and loads are locked; retry only this frozen attempt.'}</p><p>Publication draft ID: {savedPublication.flowId}; frozen revision: {savedPublication.draftRevision}</p><button type="button" onClick={checkPublicationState}>Check this session's saved publication state</button></>}{savedPublication.phase==='published'&&<p>Published draft revision: {savedPublication.draftRevision}; immutable version: {savedPublication.receipt.publication.versionId}</p>}{busy&&<><p role="status">{state.phase==='saving'?'Saving draft...':'Loading draft...'}</p><button type="button" onClick={checkSessionDraftState}>Check this session's draft state</button><p>This checks only the state held in this signed-in session. It does not repeat a save or load. After the pending operation finishes, load the draft for a fresh read.</p></>}{blocked&&<p role="status">Draft writes are locked. Load this same draft before saving again; loading does not verify a publication attempt.</p>}{editor.notice&&<p role="status">{editor.notice}</p>}{editor.error&&<p role="alert">{editor.error}</p>}</section>;
}
type HistoryState={client:PublisherClient;tenantId:string;flowId:string;phase:'idle'|'loading'|'loaded'|'failed';history?:PaidSimpleVersionHistory;error:string};
function PaidSimpleHistory({client,tenantId,onStateChange}:{client:PublisherClient;tenantId:string;onStateChange:()=>void}){
 const initial=():HistoryState=>({client,tenantId,flowId:'',phase:'idle',error:''});const [snapshot,setSnapshot]=useState(initial),generation=useRef(0),inFlight=useRef(false);
 const [selected,setSelected]=useState(''),[reviewSnapshot,setReview]=useState<{client:PublisherClient;tenantId:string;history:PaidSimpleVersionHistory;targetVersionId:string}|null>(null),[checking,setChecking]=useState(false);
 const review=reviewSnapshot?.client===client&&reviewSnapshot.tenantId===tenantId?reviewSnapshot:null;
 const cancelRef=useRef<HTMLButtonElement>(null),reviewRef=useRef<HTMLButtonElement>(null);
 useEffect(()=>{generation.current++;inFlight.current=false;setSnapshot(initial());setSelected('');setReview(null);setChecking(false);return()=>{generation.current++;};},[client,tenantId]);
 useEffect(()=>{if(review)cancelRef.current?.focus();},[review]);
 const view=snapshot.client===client&&snapshot.tenantId===tenantId?snapshot:initial();
 const rollback=client.paidSimpleRollbackState(tenantId),locked=rollback.phase==='rolling_back'||rollback.phase==='unknown';
 const draft=client.paidSimpleDraftState(tenantId),publication=client.paidSimplePublicationState(tenantId),savedPublication=client.paidSimpleSavedDraftPublicationState(tenantId);
 const uncertain=draft.phase==='saving'||draft.phase==='loading'||draft.phase==='unverified'||draft.phase==='conflict'||publication.phase==='publishing'||publication.phase==='unknown'||savedPublication.phase==='publishing'||savedPublication.phase==='unknown';
 const current=view.history?.versions.find(version=>version.current),targets=view.history?.versions.filter(version=>!version.current&&version.publication&&current&&version.draftRevision<current.draftRevision)??[];
 function editFlowId(value:string){if(locked)return;generation.current++;inFlight.current=false;setSelected('');setReview(null);setSnapshot({client,tenantId,flowId:value,phase:'idle',error:''});}
 async function refresh(event:FormEvent){
  event.preventDefault();if(inFlight.current)return;const flowId=(locked?rollback.flowId:view.flowId).trim().toLowerCase();if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/.test(flowId)){setSnapshot({...view,error:'Enter a known form ID for this business.'});return;}
  const at=++generation.current;inFlight.current=true;setSelected('');setReview(null);setSnapshot({client,tenantId,flowId,phase:'loading',error:''});
  try{const history=await client.paidSimpleVersionHistory(tenantId,flowId);if(at===generation.current)setSnapshot({client,tenantId,flowId,phase:'loaded',history,error:''});}
  catch(error){if(at===generation.current)setSnapshot({client,tenantId,flowId,phase:'failed',error:error instanceof PublicationError?error.message:'Version history could not be verified. This does not release an uncertain save, publication or rollback.'});}
  finally{if(at===generation.current)inFlight.current=false;}
 }
 function closeReview(){setReview(null);reviewRef.current?.focus();}
 async function confirm(){
  if(!review||inFlight.current||locked)return;const at=generation.current,reviewed=review,currentVersion=reviewed.history.versions.find(version=>version.current);if(!currentVersion)return;
  inFlight.current=true;setReview(null);setSelected('');setSnapshot({...view,history:undefined,error:''});
  const promise=client.rollbackPaidSimplePublication(tenantId,reviewed.history.flowId,{expectedCurrentVersionId:currentVersion.versionId,targetVersionId:reviewed.targetVersionId});onStateChange();
  try{await promise;if(at===generation.current){setSnapshot({...view,history:undefined,error:''});onStateChange();}}
  catch(error){if(at===generation.current){setSnapshot({...view,history:undefined,error:error instanceof PublicationError?error.message:'Rollback outcome is unverified. Check the current receipt without repeating rollback.'});onStateChange();}}
  finally{if(at===generation.current)inFlight.current=false;}
 }
 async function checkCurrent(){
  if(inFlight.current||checking)return;const at=generation.current;inFlight.current=true;setChecking(true);
  try{await client.reconcilePaidSimpleRollback(tenantId);if(at===generation.current){setSnapshot({...view,history:undefined,error:''});onStateChange();}}
  catch(error){if(at===generation.current)setSnapshot({...view,error:error instanceof PublicationError?error.message:'Rollback remains unverified and locked.'});}
  finally{if(at===generation.current){inFlight.current=false;setChecking(false);}}
 }
 return <section aria-label="Published version history"><h2>Published version history</h2><p>Enter a form ID from a saved draft or publication, then refresh to view its immutable published names and designs. A history read does not verify an uncertain save or publication. Rollback requires a separate owner review and explicit action; the server checks current version and catalog eligibility.</p><form onSubmit={refresh}><label>Version history form ID<input value={locked?rollback.flowId:view.flowId} disabled={locked} onChange={event=>editFlowId(event.target.value)} style={{width:'100%',maxWidth:'100%',minWidth:0}}/></label><button type="submit" disabled={view.phase==='loading'||rollback.phase==='rolling_back'}>{view.phase==='loading'?'Refreshing version history...':'Refresh version history'}</button></form>{view.phase==='loading'&&<p role="status">Checking published version history...</p>}{view.error&&<p role="alert">{view.error}</p>}{view.history&&<><p>Form ID: {view.history.flowId}</p><ol>{view.history.versions.map(version=><li key={version.versionId}><h3>{version.name}</h3><p>Published draft revision: {version.draftRevision}</p><p>Version ID: {version.versionId}</p><p>{version.current?'Current version at last refresh':'Historical version'}</p><p>Pinned design: {version.presentation.layout==='compact'?'Compact':'Stacked'}; accent color {version.presentation.accentColor}</p>{version.publication?<><p>Installation ID: {version.publication.installationId}</p><a href={STAGING_CHECKOUT_ORIGIN+version.publication.hostedPath} target="_blank" rel="noopener noreferrer">Open published revision {version.draftRevision}: {version.name}</a></>:<p>No verified installation link for this version.</p>}</li>)}</ol>{targets.length>0&&current?.publication&&<><label>Prior version for rollback<select value={selected} disabled={locked||uncertain||view.phase==='loading'} onChange={event=>{setSelected(event.target.value);setReview(null);}}><option value="">Choose a prior published version</option>{targets.map(target=><option key={target.versionId} value={target.versionId}>Revision {target.draftRevision}: {target.name}</option>)}</select></label><button ref={reviewRef} type="button" disabled={!selected||locked||uncertain} onClick={()=>{if(view.history)setReview({client,tenantId,history:view.history,targetVersionId:selected});}}>Review rollback</button></> }</>}
 {review&&<div role="dialog" aria-label="Review publication rollback" onKeyDown={event=>{if(event.key==='Escape'){event.preventDefault();closeReview();}}}><h3>Review publication rollback</h3><p>Restore {review.history.versions.find(version=>version.versionId===review.targetVersionId)?.name} (revision {review.history.versions.find(version=>version.versionId===review.targetVersionId)?.draftRevision}) as the current published version for form {review.history.flowId}.</p><p>Expected current version: {review.history.versions.find(version=>version.current)?.versionId}</p><p>Target version: {review.targetVersionId}. Existing target installation: {review.history.versions.find(version=>version.versionId===review.targetVersionId)?.publication?.installationId}</p><p>This changes the current publication pointer. It does not edit the draft, reprice bookings, or modify historical versions. The server can reject catalog drift or a stale current version. A lost response requires a fresh read, never a repeated rollback.</p><button ref={cancelRef} type="button" onClick={closeReview}>Cancel rollback</button><button type="button" disabled={uncertain||locked} onClick={()=>void confirm()}>Confirm publication rollback</button></div>}
 {uncertain&&<p>Rollback is unavailable while a draft or publication outcome is uncertain or an operation is pending.</p>}
 {locked&&<><p role="status">{rollback.phase==='rolling_back'?'Restoring the reviewed published version...':'Rollback outcome is unverified. Draft and publication changes remain locked. Do not repeat rollback; check the current receipt for this same target.'}</p><p>Rollback form: {rollback.flowId}; target version: {rollback.targetVersionId}; target installation: {rollback.targetPublication.installationId}</p><button type="button" onClick={onStateChange}>Check this session's rollback state</button>{rollback.phase==='unknown'&&<button type="button" disabled={checking} onClick={()=>void checkCurrent()}>{checking?'Checking current rollback receipt...':'Check current rollback receipt'}</button>}</>}
 {rollback.phase==='verified'&&<><p role="status">Current publication verified at the restored target version: {rollback.receipt.versionId}. Form: {rollback.flowId}; installation: {rollback.receipt.installationId}.</p><a href={STAGING_CHECKOUT_ORIGIN+rollback.receipt.hostedPath} target="_blank" rel="noopener noreferrer">Open restored published form</a><p>Refresh version history before reviewing another change.</p></>}
 </section>;
}
export function PaidSimplePublisher({client,tenantId,role,services,staging,catalogLoading=false}:{client:PublisherClient;tenantId:string;role?:string;services:ServiceRow[];staging:boolean;catalogLoading?:boolean}){
 const [,setAuthorityRevision]=useState(0);
 const [name,setName]=useState(''),[serviceId,setServiceId]=useState(''),[error,setError]=useState('');
 const [attemptId,setAttemptId]=useState(''),[checking,setChecking]=useState(false);
 const [snapshot,setSnapshot]=useState<{client:PublisherClient;tenantId:string;publication:PaidSimplePublicationState}>(()=>({client,tenantId,publication:client.paidSimplePublicationState(tenantId)}));
 const [savedSnapshot,setSavedSnapshot]=useState<{client:PublisherClient;tenantId:string;saved:SavedForms}>(()=>({client,tenantId,saved:{phase:'idle',items:[],error:''}}));
 const generation=useRef(0),inFlight=useRef(false),listInFlight=useRef(false);
 useEffect(()=>{generation.current++;inFlight.current=false;listInFlight.current=false;setSavedSnapshot({client,tenantId,saved:{phase:'idle',items:[],error:''}});setName('');setServiceId('');setError('');setAttemptId('');setChecking(false);setSnapshot({client,tenantId,publication:client.paidSimplePublicationState(tenantId)});return()=>{generation.current++;}},[client,tenantId,role,staging]);
 const publication=snapshot.client===client&&snapshot.tenantId===tenantId?snapshot.publication:{phase:'ready'} as const;
 const saved:SavedForms=savedSnapshot.client===client&&savedSnapshot.tenantId===tenantId?savedSnapshot.saved:{phase:'idle',items:[],error:''};
 const available=services.filter(service=>service.tenant_id===tenantId&&service.active&&Number.isSafeInteger(service.base_price)&&service.base_price>0&&service.duration_minutes>=5&&service.duration_minutes<=1440&&/^[A-Z]{3}$/.test(service.currency));
 async function publish(event:FormEvent){
  event.preventDefault();if(!staging||role!=='BUSINESS_OWNER'||publication.phase!=='ready'||catalogLoading||inFlight.current)return;
  if(!available.some(service=>service.id===serviceId)||!name.trim()||name.trim().length>200){setError('Choose an active simple service and enter a form name.');return;}
  const at=generation.current,flowId=crypto.randomUUID();inFlight.current=true;setError('');setSnapshot({client,tenantId,publication:{phase:'publishing',flowId}});
  try{const receipt=await client.publishPaidSimple(tenantId,flowId,{serviceId,name:name.trim(),checkoutOrigin:STAGING_CHECKOUT_ORIGIN});if(at===generation.current)setSnapshot({client,tenantId,publication:{phase:'published',flowId,receipt}});}
  catch(error){if(at===generation.current){const unknown=!(error instanceof PublicationError)||error.delivery==='unknown';setSnapshot({client,tenantId,publication:unknown?{phase:'unknown',flowId}:{phase:'ready'}});setError(error instanceof PublicationError?error.message: 'Publication status is unverified. The request may have been saved. Check this same attempt using the receipt lookup; do not repeat publication.');}}
  finally{if(at===generation.current)inFlight.current=false;}
 }
 async function refreshSavedForms(){
  if(!staging||role!=='BUSINESS_OWNER'||listInFlight.current)return;
  const at=generation.current;listInFlight.current=true;setSavedSnapshot({client,tenantId,saved:{phase:'loading',items:[],error:''}});
  try{const items=await client.listPaidSimplePublications(tenantId);if(at===generation.current)setSavedSnapshot({client,tenantId,saved:{phase:'loaded',items,error:''}});}
  catch(error){if(at===generation.current)setSavedSnapshot({client,tenantId,saved:{phase:'failed',items:[],error:error instanceof PublicationError?error.message:'Saved forms could not be checked. This does not make publishing an uncertain attempt again safe.'}});}
  finally{if(at===generation.current)listInFlight.current=false;}
 }
 async function checkReceipt(flowId:string){
  if(!staging||role!=='BUSINESS_OWNER'||inFlight.current||publication.phase==='publishing'||publication.phase==='unknown'&&publication.flowId!==flowId)return;
  if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(flowId)){setError('Enter the exact publication attempt ID for this business.');return;}
  const at=generation.current;inFlight.current=true;setChecking(true);setError('');
  // Reading a known attempt cannot authorize another create-only publication.
  setSnapshot({client,tenantId,publication:{phase:'unknown',flowId}});
  try{const receipt=await client.recoverPaidSimplePublication(tenantId,flowId);if(at===generation.current)setSnapshot({client,tenantId,publication:{phase:'published',flowId,receipt}});}
  catch(error){if(at===generation.current){setSnapshot({client,tenantId,publication:client.paidSimplePublicationState(tenantId)});setError(error instanceof PublicationError?error.message:'The receipt could not be checked. Publication status remains unverified; do not publish again.');}}
  finally{if(at===generation.current){inFlight.current=false;setChecking(false);}}
 }
 function recover(event:FormEvent){event.preventDefault();void checkReceipt(publication.phase==='unknown'?publication.flowId:attemptId.trim());}
 if(!staging)return <section><h1>Booking Form</h1><p>Paid form publication is available only in the staging test workspace.</p></section>;
 if(role!=='BUSINESS_OWNER')return <section><h1>Booking Form</h1><p role="status">Only a business owner can publish a staging paid form.</p></section>;
 const rollbackState=client.paidSimpleRollbackState(tenantId),rollbackLocked=rollbackState.phase==='rolling_back'||rollbackState.phase==='unknown';
 function refreshAuthority(){setAuthorityRevision(value=>value+1);setSnapshot({client,tenantId,publication:client.paidSimplePublicationState(tenantId)});}
 const revisionAttempt=client.paidSimpleSavedDraftPublicationState(tenantId);const revisionUnverified=revisionAttempt.phase==='unknown'||revisionAttempt.phase==='publishing';
 const receipt=publication.phase==='published'?publication.receipt:undefined;
 const hostedUrl=receipt?STAGING_CHECKOUT_ORIGIN+receipt.hostedPath:'';
 const iframe=receipt?`<iframe src="${hostedUrl}" title="Booking Lumin staging test booking" width="100%" height="720" style="border:0"></iframe>`:'';
 return <section style={{minWidth:0,overflowWrap:'anywhere'}}><h1>Booking Form</h1><p>Staging paid simple-service form. Payment is simulated; no real money is charged.</p>
  <PaidSimpleDraftEditor client={client} tenantId={tenantId} services={available} catalogLoading={catalogLoading} rollbackLocked={rollbackLocked} onPublicationChange={refreshAuthority}/>
  <section aria-label="Saved staging forms"><h2>Saved staging forms</h2><p>Refresh to find up to 50 current staging publications for this business. This list does not verify an uncertain attempt or authorize publishing it again.</p><button type="button" disabled={saved.phase==='loading'} onClick={()=>void refreshSavedForms()}>{saved.phase==='loading'?'Refreshing saved forms...':'Refresh saved forms'}</button>
   {saved.phase==='loading'&&<p role="status">Checking saved staging forms...</p>}
   {saved.phase==='loaded'&&!saved.items.length&&<p role="status">No current saved forms were returned. An empty list does not prove an uncertain publication was not saved; check its attempt ID directly.</p>}
   {saved.error&&<p role="alert">{saved.error}</p>}
   {saved.items.length>0&&<ul>{saved.items.map(item=><li key={item.flowId}><h3>{item.name}</h3><p>Publication attempt: {item.flowId}</p><p>Current version at last refresh: {item.publication.versionId}</p><p><a href={STAGING_CHECKOUT_ORIGIN+item.publication.hostedPath} target="_blank" rel="noopener noreferrer">Open saved form: {item.name}</a></p><button type="button" disabled={rollbackLocked||revisionUnverified||checking||publication.phase==='publishing'||publication.phase==='unknown'&&publication.flowId!==item.flowId} onClick={()=>void checkReceipt(item.flowId)}>Check receipt for {item.name}</button></li>)}</ul>}
  </section>
  <PaidSimpleHistory client={client} tenantId={tenantId} onStateChange={refreshAuthority}/>
  {receipt?<><h2>Staging form published</h2><dl><dt>Publication attempt</dt><dd><input aria-label="Publication attempt ID" readOnly value={publication.phase==='published'?publication.flowId:''} style={{width:'100%',maxWidth:'100%',minWidth:0}}/></dd><dt>Published version</dt><dd>{receipt.versionId}</dd><dt>Installation</dt><dd>{receipt.installationId}</dd><dt>Hosted path</dt><dd>{receipt.hostedPath}</dd></dl><p>This installation points to the immutable published version.</p><p><a href={hostedUrl} target="_blank" rel="noopener noreferrer">Open staging booking form</a></p><label>Website iframe code<textarea readOnly value={iframe} rows={5} style={{width:'100%',maxWidth:'100%',minWidth:0}}/></label><p>Use this code for a staging test installation. Keep the publication attempt ID. After reloading and signing in, use that ID to check the receipt for this business.</p></>:publication.phase==='unknown'?<><p role="alert">Publication status is unverified. The request may have been saved. Publishing again is locked for this business in this session.</p><p>{revisionUnverified?'Use the saved-draft retry action above with the same frozen revision and origin. A different attempt is locked.':'Do not submit another publication to recover this attempt. Check its receipt below.'} If you reload, keep this attempt ID and sign in to the same business before checking its receipt again.</p><p>Publication attempt: {publication.flowId}</p></>:publication.phase==='publishing'?<><p>Publication attempt: {publication.flowId}. Keep this ID if you reload before the receipt arrives.</p><p role="status">Publishing the staging form...</p><button type="button" onClick={()=>setSnapshot({client,tenantId,publication:client.paidSimplePublicationState(tenantId)})}>Check this session's receipt</button><p>This checks the receipt held in this session. It does not repeat publication.</p></>:<form onSubmit={publish}><fieldset disabled={catalogLoading||rollbackLocked} className="form-stack" style={{minWidth:0}}><label>Simple service<select required value={serviceId} onChange={event=>setServiceId(event.target.value)}><option value="">Choose a service</option>{available.map(service=><option key={service.id} value={service.id}>{service.name} - {formatMoney({amount:service.base_price,currency:service.currency})}</option>)}</select></label><label>Form name<input required maxLength={200} value={name} onChange={event=>setName(event.target.value)}/></label><label>Checkout origin<input readOnly value={STAGING_CHECKOUT_ORIGIN}/></label><p>The server verifies that the service has a positive price and no questions, items, add-ons or resource requirements, then pins its current catalog in a new version.</p>{!catalogLoading&&!available.length&&<p>No active simple services with a positive price are available.</p>}<button disabled={catalogLoading||!available.length}>Publish staging test form</button></fieldset></form>}
  {!rollbackLocked&&!revisionUnverified&&(publication.phase==='ready'||publication.phase==='unknown')&&<form onSubmit={recover} aria-label="Check publication receipt"><h2>Check an existing publication</h2><p>Enter a known publication attempt ID for this business. This reads its current active receipt and never creates or republishes a form. A missing receipt keeps publication locked for this attempt.</p><label>Publication attempt ID<input required value={publication.phase==='unknown'?publication.flowId:attemptId} readOnly={publication.phase==='unknown'} disabled={checking} onChange={event=>setAttemptId(event.target.value)} style={{width:'100%',maxWidth:'100%',minWidth:0}}/></label><button disabled={checking} type="submit">{checking?'Checking receipt...':'Check publication receipt'}</button></form>}
  {error&&<p role="alert">{error}</p>}
 </section>;
}
