import {afterEach,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {createRuntimeClient,type ServiceRow} from '@lumin/runtime-client';
import {PaidSimplePublisher,STAGING_CHECKOUT_ORIGIN} from './PaidSimplePublisher';
const tenant='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222',serviceId='33333333-3333-4333-8333-333333333333';
const service:ServiceRow={id:serviceId,tenant_id:tenant,name:'Housekeeping',currency:'USD',duration_minutes:60,base_price:12500,active:true};
const receipt={versionId:other,installationId:serviceId,renderSchemaVersion:3,hostedPath:'/checkout/flow/'+serviceId};
const json=(value:unknown,status=200)=>new Response(JSON.stringify(value),{status});
afterEach(()=>{cleanup();vi.restoreAllMocks();vi.unstubAllGlobals();});
async function fixture(publish:()=>Promise<Response>){
 const calls=vi.fn<typeof fetch>(async(input)=>String(input).includes('/auth/v1/token')?json({access_token:'synthetic-owner-private-token'}):String(input).includes('/auth/v1/user')?json({id:other}):publish());
 const client=createRuntimeClient({url:'https://example.supabase.co',publishableKey:'sb_publishable_synthetic',tenantId:tenant,bookingApiOrigin:'https://api.example.test'},calls);await client.signIn('owner@example.test','fixture');return{client,calls};
}
function fill(){fireEvent.change(screen.getByLabelText('Simple service'),{target:{value:serviceId}});fireEvent.change(screen.getByLabelText('Form name'),{target:{value:'Housekeeping booking'}});}
it('publishes only on an explicit owner action and shows the immutable canonical link and iframe receipt',async()=>{
 const {client,calls}=await fixture(async()=>json({ok:true,data:receipt}));render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service,{...service,id:other,active:false},{...service,id:tenant,base_price:0},{...service,id:tenant,tenant_id:other}]} staging/>);
 expect(calls).toHaveBeenCalledTimes(2);expect(screen.getByLabelText('Checkout origin')).toHaveValue(STAGING_CHECKOUT_ORIGIN);expect(Array.from((screen.getByLabelText('Simple service') as HTMLSelectElement).options)).toHaveLength(2);fill();fireEvent.click(screen.getByText('Publish staging test form'));await screen.findByText('Staging form published');expect(calls).toHaveBeenCalledTimes(3);expect(screen.getByRole('link',{name:'Open staging booking form'})).toHaveAttribute('href',STAGING_CHECKOUT_ORIGIN+receipt.hostedPath);expect(screen.getByLabelText('Website iframe code')).toHaveValue(`<iframe src="${STAGING_CHECKOUT_ORIGIN+receipt.hostedPath}" title="Booking Lumin staging test booking" width="100%" height="720" style="border:0"></iframe>`);expect(screen.getByText(receipt.versionId)).toBeTruthy();expect(screen.queryByText('Publish staging test form')).toBeNull();expect(document.body.textContent).not.toContain('synthetic-owner-private-token');
});
it.each([{role:'BUSINESS_STAFF',staging:true},{role:'BUSINESS_OWNER',staging:false}])('blocks staff or nonstaging publication in the UI: %j',async(props)=>{
 const {client,calls}=await fixture(async()=>{throw Error('unexpected');});render(<PaidSimplePublisher client={client} tenantId={tenant} services={[service]} {...props}/>);expect(screen.queryByText('Publish staging test form')).toBeNull();expect(screen.queryByLabelText('Form name')).toBeNull();expect(screen.queryByLabelText('Publication attempt ID')).toBeNull();expect(screen.queryByRole('button',{name:'Check publication receipt'})).toBeNull();expect(screen.queryByRole('button',{name:'Refresh saved forms'})).toBeNull();expect(screen.queryByRole('button',{name:'Save draft'})).toBeNull();expect(screen.queryByRole('button',{name:'Refresh saved drafts'})).toBeNull();expect(screen.queryByRole('button',{name:'Refresh version history'})).toBeNull();expect(screen.queryByLabelText('Draft accent color')).toBeNull();expect(calls).toHaveBeenCalledTimes(2);
});
it('keeps unknown delivery locked after remount, with no new identity or automatic replay',async()=>{
 const {client,calls}=await fixture(async()=>{throw Error('private-server-token');});const first=render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fill();fireEvent.click(screen.getByText('Publish staging test form'));await screen.findByText(/Publishing again is locked/);expect(screen.queryByText('Publish staging test form')).toBeNull();const attempt=client.paidSimplePublicationState(tenant);expect(attempt.phase).toBe('unknown');first.unmount();render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);await screen.findByText(/Publishing again is locked/);expect(client.paidSimplePublicationState(tenant)).toEqual(attempt);expect(calls).toHaveBeenCalledTimes(3);expect(document.body.textContent).not.toContain('private-server-token');expect(screen.getByRole('button',{name:'Check publication receipt'})).toBeEnabled();
});
it('clears the form and discards a late receipt when the selected business changes',async()=>{
 let resolve!:(response:Response)=>void;const {client,calls}=await fixture(()=>new Promise<Response>(r=>resolve=r));const {rerender}=render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fill();fireEvent.click(screen.getByText('Publish staging test form'));await waitFor(()=>expect(resolve).toBeTypeOf('function'));rerender(<PaidSimplePublisher client={client} tenantId={other} role="BUSINESS_OWNER" services={[{...service,tenant_id:other}]} staging/>);expect(screen.getByLabelText('Form name')).toHaveValue('');resolve(json({ok:true,data:receipt}));await waitFor(()=>expect(client.paidSimplePublicationState(tenant).phase).toBe('published'));expect(screen.queryByText('Staging form published')).toBeNull();expect(screen.queryByText(receipt.versionId)).toBeNull();expect(calls).toHaveBeenCalledTimes(3);
});
it('shows definitive rejection without fabricating publication, and preserves unknown server outcomes',async()=>{
 const {client}=await fixture(async()=>json({ok:false,code:'UNSUPPORTED_CONFIG'},422));render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fill();fireEvent.click(screen.getByText('Publish staging test form'));await screen.findByText('This service does not support the staging paid form.');expect(screen.queryByText('Staging form published')).toBeNull();expect(screen.getByText('Publish staging test form')).toBeEnabled();
});

it('recovers a known attempt after reload only on an explicit read and shows its canonical installation',async()=>{
 const {client,calls}=await fixture(async()=>json({ok:true,data:receipt}));render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fireEvent.change(screen.getByLabelText('Publication attempt ID'),{target:{value:other}});expect(calls).toHaveBeenCalledTimes(2);fireEvent.click(screen.getByRole('button',{name:'Check publication receipt'}));await screen.findByText('Staging form published');expect(calls).toHaveBeenCalledTimes(3);expect(calls.mock.calls[2]?.[0]).toBe('https://api.example.test/api/paid-simple-flows/'+other+'/publication?tenantId='+tenant);expect(calls.mock.calls[2]?.[1]?.method).toBe('GET');expect(screen.getByRole('link',{name:'Open staging booking form'})).toHaveAttribute('href',STAGING_CHECKOUT_ORIGIN+receipt.hostedPath);expect(screen.getByText('Publication attempt')).toBeTruthy();expect(screen.getByLabelText('Publication attempt ID')).toHaveValue(other);expect(screen.getByLabelText('Publication attempt ID')).toHaveAttribute('readonly');expect(document.body.textContent).not.toContain('synthetic-owner-private-token');expect(screen.queryByText('Publish staging test form')).toBeNull();
});
it('keeps a not-found lookup locked and allows only an explicit same-attempt read',async()=>{
 let n=0;const {client,calls}=await fixture(async()=>++n===1?json({ok:false,code:'NOT_AVAILABLE'},404):json({ok:true,data:receipt}));render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fireEvent.change(screen.getByLabelText('Publication attempt ID'),{target:{value:other}});fireEvent.click(screen.getByRole('button',{name:'Check publication receipt'}));await screen.findByText(/No active receipt was found/);expect(screen.queryByText('Publish staging test form')).toBeNull();expect(screen.getByLabelText('Publication attempt ID')).toHaveValue(other);expect(screen.getByLabelText('Publication attempt ID')).toHaveAttribute('readonly');expect(calls).toHaveBeenCalledTimes(3);fireEvent.click(screen.getByRole('button',{name:'Check publication receipt'}));await screen.findByText('Staging form published');expect(calls.mock.calls.slice(2).every(([,options])=>options?.method==='GET')).toBe(true);
});
it('checks an unknown POST attempt without replay or a new identity',async()=>{
 let n=0;const {client,calls}=await fixture(async()=>++n===1?Promise.reject(Error('private-response-secret')):json({ok:true,data:receipt}));render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fill();fireEvent.click(screen.getByText('Publish staging test form'));await screen.findByText(/Publishing again is locked/);const state=client.paidSimplePublicationState(tenant);expect(state.phase).toBe('unknown');fireEvent.click(screen.getByRole('button',{name:'Check publication receipt'}));await screen.findByText('Staging form published');if(state.phase==='unknown')expect(calls.mock.calls[3]?.[0]).toContain('/'+state.flowId+'/publication?');expect(calls.mock.calls[2]?.[1]?.method).toBe('POST');expect(calls.mock.calls[3]?.[1]?.method).toBe('GET');expect(document.body.textContent).not.toContain('private-response-secret');
});
it('clears the recovery field and discards a late receipt on tenant changes',async()=>{
 let resolve!:(response:Response)=>void;const {client}=await fixture(()=>new Promise<Response>(r=>resolve=r));const {rerender}=render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fireEvent.change(screen.getByLabelText('Publication attempt ID'),{target:{value:other}});fireEvent.click(screen.getByRole('button',{name:'Check publication receipt'}));await waitFor(()=>expect(resolve).toBeTypeOf('function'));rerender(<PaidSimplePublisher client={client} tenantId={other} role="BUSINESS_OWNER" services={[{...service,tenant_id:other}]} staging/>);expect(screen.getByLabelText('Publication attempt ID')).toHaveValue('');resolve(json({ok:true,data:receipt}));await waitFor(()=>expect(client.paidSimplePublicationState(tenant).phase).toBe('published'));expect(screen.queryByText('Staging form published')).toBeNull();expect(client.paidSimplePublicationState(other)).toEqual({phase:'ready'});
});
it('rejects invalid recovery IDs without a network read or hiding the publication form',async()=>{
 const {client,calls}=await fixture(async()=>{throw Error('unexpected');});render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fireEvent.change(screen.getByLabelText('Publication attempt ID'),{target:{value:'invalid'}});fireEvent.click(screen.getByRole('button',{name:'Check publication receipt'}));await screen.findByText('Enter the exact publication attempt ID for this business.');expect(calls).toHaveBeenCalledTimes(2);expect(screen.getByText('Publish staging test form')).toBeEnabled();
});

const savedForms=[{flowId:other,name:'Saved housekeeping',publication:receipt},{flowId:serviceId,name:'Another saved form',publication:{versionId:tenant,installationId:other,renderSchemaVersion:3,hostedPath:'/checkout/flow/'+other}}];
it('refreshes saved names and canonical links explicitly, then checks selected receipts without any publication writer',async()=>{
 let n=0;const {client,calls}=await fixture(async()=>++n===1?json({ok:true,data:{publications:savedForms}}):json({ok:true,data:savedForms[n-2]!.publication}));render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);expect(calls).toHaveBeenCalledTimes(2);fireEvent.click(screen.getByRole('button',{name:'Refresh saved forms'}));await screen.findByText('Saved housekeeping');expect(calls).toHaveBeenCalledTimes(3);expect(screen.getByRole('link',{name:'Open saved form: Saved housekeeping'})).toHaveAttribute('href',STAGING_CHECKOUT_ORIGIN+receipt.hostedPath);expect(screen.getByText('Current version at last refresh: '+receipt.versionId)).toBeTruthy();expect(screen.queryByText('Staging form published')).toBeNull();expect(client.paidSimplePublicationState(tenant)).toEqual({phase:'ready'});fireEvent.click(screen.getByRole('button',{name:'Check receipt for Saved housekeeping'}));await screen.findByText('Staging form published');expect(screen.getByLabelText('Publication attempt ID')).toHaveValue(other);fireEvent.click(screen.getByRole('button',{name:'Check receipt for Another saved form'}));await waitFor(()=>expect(screen.getByLabelText('Publication attempt ID')).toHaveValue(serviceId));expect(screen.getByRole('link',{name:'Open staging booking form'})).toHaveAttribute('href',STAGING_CHECKOUT_ORIGIN+savedForms[1]!.publication.hostedPath);expect(calls.mock.calls.slice(2).every(([,options])=>options?.method==='GET'&&!options?.body)).toBe(true);expect(calls.mock.calls[2]?.[0]).toBe('https://api.example.test/api/paid-simple-flows?tenantId='+tenant);expect(calls.mock.calls[3]?.[0]).toContain('/'+other+'/publication?tenantId='+tenant);expect(calls.mock.calls[4]?.[0]).toContain('/'+serviceId+'/publication?tenantId='+tenant);expect(document.body.textContent).not.toContain('synthetic-owner-private-token');expect(screen.queryByText('Publish staging test form')).toBeNull();
});
it.each(['empty','unavailable'])('retains an unknown attempt after an explicit %s saved list response',async(kind)=>{
 let n=0;const {client,calls}=await fixture(async()=>++n===1?Promise.reject(Error('private-secret')):kind==='empty'?json({ok:true,data:{publications:[]}}):json({ok:false,code:'NOT_AVAILABLE'},404));render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fill();fireEvent.click(screen.getByText('Publish staging test form'));await screen.findByText(/Publishing again is locked/);const original=client.paidSimplePublicationState(tenant);fireEvent.click(screen.getByRole('button',{name:'Refresh saved forms'}));await screen.findByText(kind==='empty'?/No current saved forms were returned/:/saved form list could not be verified/);expect(client.paidSimplePublicationState(tenant)).toEqual(original);expect(screen.queryByText('Publish staging test form')).toBeNull();expect(calls).toHaveBeenCalledTimes(4);expect(calls.mock.calls[3]?.[1]?.method).toBe('GET');expect(document.body.textContent).not.toContain('private-secret');
});
it('permits only the matching unknown attempt from a saved list and never switches its identity',async()=>{
 let n=0;const {client,calls}=await fixture(async()=>{if(++n===1)throw Error('ambiguous');const state=client.paidSimplePublicationState(tenant);if(n===2&&state.phase==='unknown')return json({ok:true,data:{publications:[{flowId:state.flowId,name:'Matching attempt',publication:receipt},savedForms[0]!].sort((a,b)=>a.flowId<b.flowId?-1:1)}});return json({ok:true,data:receipt});});render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fill();fireEvent.click(screen.getByText('Publish staging test form'));await screen.findByText(/Publishing again is locked/);const original=client.paidSimplePublicationState(tenant);fireEvent.click(screen.getByRole('button',{name:'Refresh saved forms'}));await screen.findByText('Matching attempt');expect(screen.getByRole('button',{name:'Check receipt for Saved housekeeping'})).toBeDisabled();expect(screen.getByRole('button',{name:'Check receipt for Matching attempt'})).toBeEnabled();expect(client.paidSimplePublicationState(tenant)).toEqual(original);fireEvent.click(screen.getByRole('button',{name:'Check receipt for Matching attempt'}));await screen.findByText('Staging form published');if(original.phase==='unknown')expect(calls.mock.calls[4]?.[0]).toContain('/'+original.flowId+'/publication?');expect(calls.mock.calls[4]?.[1]?.method).toBe('GET');
});
it('keeps saved form selection disabled while publication is in flight',async()=>{
 let resolve!:(response:Response)=>void,n=0;const {client,calls}=await fixture(async()=>++n===1?new Promise<Response>(r=>resolve=r):json({ok:true,data:{publications:savedForms}}));render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fill();fireEvent.click(screen.getByText('Publish staging test form'));await screen.findByText('Publishing the staging form...');fireEvent.click(screen.getByRole('button',{name:'Refresh saved forms'}));await screen.findByText('Saved housekeeping');expect(screen.getByRole('button',{name:'Check receipt for Saved housekeeping'})).toBeDisabled();expect(client.paidSimplePublicationState(tenant).phase).toBe('publishing');expect(calls).toHaveBeenCalledTimes(4);resolve(json({ok:true,data:receipt}));await screen.findByText('Staging form published');
});
it('clears saved forms on tenant change and drops an old late list without disturbing a newer refresh',async()=>{
 let resolveOld!:(response:Response)=>void,resolveNew!:(response:Response)=>void,n=0;const {client,calls}=await fixture(async()=>++n===1?new Promise<Response>(r=>resolveOld=r):new Promise<Response>(r=>resolveNew=r));const {rerender}=render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fireEvent.click(screen.getByRole('button',{name:'Refresh saved forms'}));await waitFor(()=>expect(resolveOld).toBeTypeOf('function'));rerender(<PaidSimplePublisher client={client} tenantId={other} role="BUSINESS_OWNER" services={[{...service,tenant_id:other}]} staging/>);fireEvent.click(screen.getByRole('button',{name:'Refresh saved forms'}));await waitFor(()=>expect(resolveNew).toBeTypeOf('function'));resolveOld(json({ok:true,data:{publications:savedForms}}));await waitFor(()=>expect(calls).toHaveBeenCalledTimes(4));expect(screen.queryByText('Saved housekeeping')).toBeNull();expect(screen.getByRole('button',{name:'Refreshing saved forms...'})).toBeDisabled();resolveNew(json({ok:true,data:{publications:[{...savedForms[0],name:'New business form'}]}}));await screen.findByText('New business form');expect(screen.queryByText('Saved housekeeping')).toBeNull();expect(calls.mock.calls[3]?.[0]).toBe('https://api.example.test/api/paid-simple-flows?tenantId='+other);
});

function fillDraft(){fireEvent.change(screen.getByLabelText('Draft simple service'),{target:{value:serviceId}});fireEvent.change(screen.getByLabelText('Draft name'),{target:{value:'Housekeeping design'}});}
it('explicitly saves design choices and loads persisted fields after a remount without publishing them',async()=>{
 let n=0;const {client,calls}=await fixture(async()=>{const state=client.paidSimpleDraftState(tenant);if(state.phase==='ready')throw Error('fixture requires bound draft');return ++n<=2?json({ok:true,data:{flowId:state.flowId,revision:n}}):json({ok:true,data:{flowId:state.flowId,revision:2,serviceId,name:'Housekeeping design',presentation:{accentColor:'#2563eb',layout:'compact'}}});});const first=render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);expect(calls).toHaveBeenCalledTimes(2);fillDraft();fireEvent.change(screen.getByLabelText('Draft name'),{target:{value:' Housekeeping design '}});fireEvent.change(screen.getByLabelText('Draft accent color'),{target:{value:'#be123c'}});fireEvent.change(screen.getByLabelText('Draft layout'),{target:{value:'compact'}});fireEvent.click(screen.getByRole('button',{name:'Save draft'}));await screen.findByText('Draft revision 1 saved. This draft is not published.');const id=(screen.getByLabelText('Draft ID') as HTMLInputElement).value;expect(id).toMatch(/^[0-9a-f-]{36}$/);expect(screen.getByLabelText('Draft name')).toHaveValue('Housekeeping design');expect(JSON.parse(calls.mock.calls[2]?.[1]?.body as string)).toEqual({serviceId,name:'Housekeeping design',presentation:{accentColor:'#be123c',layout:'compact'},expectedRevision:0});expect(screen.queryByText('Staging form published')).toBeNull();fireEvent.change(screen.getByLabelText('Draft accent color'),{target:{value:'#2563eb'}});fireEvent.click(screen.getByRole('button',{name:'Save draft'}));await screen.findByText('Draft revision 2 saved. This draft is not published.');expect(JSON.parse(calls.mock.calls[3]?.[1]?.body as string).expectedRevision).toBe(1);first.unmount();render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);expect(screen.getByLabelText('Draft ID')).toHaveValue(id);expect(screen.getByLabelText('Draft name')).toHaveValue('');fireEvent.click(screen.getByRole('button',{name:'Load draft'}));await screen.findByText(/Current draft revision 2 loaded/);expect(screen.getByLabelText('Draft name')).toHaveValue('Housekeeping design');expect(screen.getByLabelText('Draft accent color')).toHaveValue('#2563eb');expect(screen.getByLabelText('Draft layout')).toHaveValue('compact');expect(calls.mock.calls[4]?.[1]?.method).toBe('GET');expect(calls.mock.calls.slice(2).every(([url])=>String(url).includes('/'+id+'/draft?tenantId='+tenant))).toBe(true);expect(client.paidSimplePublicationState(tenant)).toEqual({phase:'ready'});expect(document.body.textContent).not.toContain('synthetic-owner-private-token');
});
it('requires loading an existing draft, retains conflict edits, then saves with the fresh server revision',async()=>{
 let n=0;const {client,calls}=await fixture(async()=>++n===1?json({ok:true,data:{flowId:other,revision:7,serviceId,name:'Server draft',presentation:{accentColor:'#0e7490',layout:'stacked'}}}):n===2?json({ok:false,code:'CONFLICT'},409):n===3?json({ok:true,data:{flowId:other,revision:8,serviceId,name:'Another owner edit',presentation:{accentColor:'#2563eb',layout:'compact'}}}):json({ok:true,data:{flowId:other,revision:9}}));render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fireEvent.change(screen.getByLabelText('Draft ID'),{target:{value:other}});expect(screen.getByRole('button',{name:'Save draft'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'Load draft'}));await screen.findByText(/Current draft revision 7 loaded/);expect(screen.getByLabelText('Draft accent color')).toHaveValue('#0e7490');fireEvent.change(screen.getByLabelText('Draft name'),{target:{value:'My unsaved name'}});fireEvent.click(screen.getByRole('button',{name:'Save draft'}));await screen.findByText(/draft revision changed/);expect(screen.getByLabelText('Draft name')).toHaveValue('My unsaved name');expect(screen.getByRole('button',{name:'Save draft'})).toBeDisabled();expect(JSON.parse(calls.mock.calls[3]?.[1]?.body as string).expectedRevision).toBe(7);fireEvent.click(screen.getByRole('button',{name:'Load draft'}));await screen.findByText(/Current draft revision 8 loaded/);expect(screen.getByLabelText('Draft name')).toHaveValue('Another owner edit');expect(screen.getByLabelText('Draft layout')).toHaveValue('compact');fireEvent.change(screen.getByLabelText('Draft name'),{target:{value:'Updated draft'}});fireEvent.click(screen.getByRole('button',{name:'Save draft'}));await screen.findByText('Draft revision 9 saved. This draft is not published.');expect(JSON.parse(calls.mock.calls[5]?.[1]?.body as string).expectedRevision).toBe(8);expect(screen.queryByText('Staging form published')).toBeNull();
});
it('keeps uncertain draft saves locked after remount and missing reads without changing publication uncertainty',async()=>{
 let n=0;const {client,calls}=await fixture(async()=>{if(++n===1)return json({ok:false,code:'INTERNAL_ERROR'},500);if(n===2)throw Error('private-draft-secret');if(n===3)return json({ok:false,code:'NOT_AVAILABLE'},404);const state=client.paidSimpleDraftState(tenant);if(state.phase==='ready')throw Error('fixture requires draft');return json({ok:true,data:{flowId:state.flowId,revision:1,serviceId,name:'Current persisted draft',presentation:{accentColor:'#0f766e',layout:'stacked'}}});});await client.publishPaidSimple(tenant,other,{serviceId,name:'Unverified publication',checkoutOrigin:STAGING_CHECKOUT_ORIGIN}).catch(()=>{});const publication=client.paidSimplePublicationState(tenant);const first=render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fillDraft();fireEvent.click(screen.getByRole('button',{name:'Save draft'}));await screen.findByText(/Draft save status is unverified/);const id=(screen.getByLabelText('Draft ID') as HTMLInputElement).value;expect(screen.getByRole('button',{name:'Save draft'})).toBeDisabled();first.unmount();render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);expect(screen.getByLabelText('Draft ID')).toHaveValue(id);expect(screen.getByLabelText('Draft ID')).toHaveAttribute('readonly');fireEvent.click(screen.getByRole('button',{name:'Load draft'}));await screen.findByText(/This draft is unavailable/);expect(screen.getByRole('button',{name:'Save draft'})).toBeDisabled();expect(client.paidSimplePublicationState(tenant)).toEqual(publication);fireEvent.click(screen.getByRole('button',{name:'Load draft'}));await screen.findByText(/Current draft revision 1 loaded/);expect(screen.getByLabelText('Draft name')).toHaveValue('Current persisted draft');expect(screen.getByRole('button',{name:'Save draft'})).toBeEnabled();expect(client.paidSimplePublicationState(tenant)).toEqual(publication);expect(calls).toHaveBeenCalledTimes(6);expect(calls.mock.calls[4]?.[1]?.method).toBe('GET');expect(calls.mock.calls[5]?.[1]?.method).toBe('GET');expect(document.body.textContent).not.toContain('private-draft-secret');expect(screen.queryByText('Staging form published')).toBeNull();
});
it('permits an explicit corrected first draft after definitive rejection, without any automatic retry',async()=>{
 let n=0;const {client,calls}=await fixture(async()=>{if(++n===1)return json({ok:false,code:'UNSUPPORTED_CONFIG'},422);const state=client.paidSimpleDraftState(tenant);if(state.phase==='ready')throw Error('fixture requires draft');return json({ok:true,data:{flowId:state.flowId,revision:1}});});render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fillDraft();fireEvent.click(screen.getByRole('button',{name:'Save draft'}));await screen.findByText(/does not support staging paid drafts/);expect(screen.getByLabelText('Draft name')).toHaveValue('Housekeeping design');expect(screen.getByLabelText('Draft ID')).toHaveValue('');expect(calls).toHaveBeenCalledTimes(3);fireEvent.click(screen.getByRole('button',{name:'Save draft'}));await screen.findByText('Draft revision 1 saved. This draft is not published.');expect(JSON.parse(calls.mock.calls[3]?.[1]?.body as string).expectedRevision).toBe(0);expect(calls).toHaveBeenCalledTimes(4);
});
it('clears draft fields on tenant change and cannot show a late old save receipt',async()=>{
 let resolve!:(response:Response)=>void;const {client}=await fixture(()=>new Promise<Response>(r=>resolve=r));const {rerender}=render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fillDraft();fireEvent.change(screen.getByLabelText('Draft accent color'),{target:{value:'#be123c'}});fireEvent.click(screen.getByRole('button',{name:'Save draft'}));await waitFor(()=>expect(resolve).toBeTypeOf('function'));const id=(screen.getByLabelText('Draft ID') as HTMLInputElement).value;rerender(<PaidSimplePublisher client={client} tenantId={other} role="BUSINESS_OWNER" services={[{...service,tenant_id:other}]} staging/>);expect(screen.getByLabelText('Draft ID')).toHaveValue('');expect(screen.getByLabelText('Draft name')).toHaveValue('');expect(screen.getByLabelText('Draft accent color')).toHaveValue('#4f46e5');resolve(json({ok:true,data:{flowId:id,revision:1}}));await waitFor(()=>expect(client.paidSimpleDraftState(tenant).phase).toBe('saved'));expect(screen.queryByText('Draft revision 1 saved. This draft is not published.')).toBeNull();expect(client.paidSimpleDraftState(other)).toEqual({phase:'ready'});
});
it('discards a late draft load after sign-out and does not expose draft controls to staff',async()=>{
 let resolve!:(response:Response)=>void;const {client}=await fixture(()=>new Promise<Response>(r=>resolve=r));const {rerender}=render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fireEvent.change(screen.getByLabelText('Draft ID'),{target:{value:other}});fireEvent.click(screen.getByRole('button',{name:'Load draft'}));await waitFor(()=>expect(resolve).toBeTypeOf('function'));client.signOut();rerender(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_STAFF" services={[service]} staging/>);resolve(json({ok:true,data:{flowId:other,revision:1,serviceId,name:'Private old draft',presentation:{accentColor:'#be123c',layout:'compact'}}}));await waitFor(()=>expect(client.paidSimpleDraftState(tenant)).toEqual({phase:'ready'}));expect(screen.queryByText('Private old draft')).toBeNull();expect(screen.queryByLabelText('Draft name')).toBeNull();
});
it('validates draft IDs and prevents overflowing a maximum persisted revision',async()=>{
 const {client,calls}=await fixture(async()=>json({ok:true,data:{flowId:other,revision:Number.MAX_SAFE_INTEGER,serviceId,name:'Last draft revision',presentation:{accentColor:'#2563eb',layout:'compact'}}}));render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fireEvent.change(screen.getByLabelText('Draft ID'),{target:{value:'invalid'}});fireEvent.click(screen.getByRole('button',{name:'Load draft'}));await screen.findByText('Enter a known draft ID before loading.');expect(calls).toHaveBeenCalledTimes(2);fireEvent.change(screen.getByLabelText('Draft ID'),{target:{value:other}});fireEvent.click(screen.getByRole('button',{name:'Load draft'}));await screen.findByText('The maximum draft revision was reached. Further saves are unavailable.');expect(screen.getByRole('button',{name:'Save draft'})).toBeDisabled();expect(calls).toHaveBeenCalledTimes(3);
});

it.each(['saved','uncertain'])('reconciles a remounted pending %s draft save without another POST or replacement identity',async(outcome)=>{
 let resolve!:(response:Response)=>void,n=0;const {client,calls}=await fixture(async()=>{if(++n===1)return new Promise<Response>(r=>resolve=r);const state=client.paidSimpleDraftState(tenant);if(state.phase==='ready')throw Error('fixture requires draft');if(outcome==='uncertain'&&n===2)return json({ok:false,code:'NOT_AVAILABLE'},404);return json({ok:true,data:{flowId:state.flowId,revision:1,serviceId,name:'Current persisted design',presentation:{accentColor:'#2563eb',layout:'compact'}}});});const first=render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fillDraft();fireEvent.click(screen.getByRole('button',{name:'Save draft'}));await waitFor(()=>expect(resolve).toBeTypeOf('function'));const id=(screen.getByLabelText('Draft ID') as HTMLInputElement).value;first.unmount();render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);expect(screen.getByRole('button',{name:'Load draft'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:"Check this session's draft state"}));expect(screen.getByRole('button',{name:'Load draft'})).toBeDisabled();expect(calls).toHaveBeenCalledTimes(3);resolve(outcome==='saved'?json({ok:true,data:{flowId:id,revision:1}}):json({ok:false,code:'INTERNAL_ERROR'},500));await waitFor(()=>expect(client.paidSimpleDraftState(tenant).phase).toBe(outcome==='saved'?'saved':'unverified'));fireEvent.click(screen.getByRole('button',{name:"Check this session's draft state"}));expect(screen.getByRole('button',{name:'Load draft'})).toBeEnabled();expect(screen.getByLabelText('Draft ID')).toHaveValue(id);expect(screen.getByLabelText('Draft name')).toHaveValue('');if(outcome==='uncertain'){expect(screen.getByRole('button',{name:'Save draft'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'Load draft'}));await screen.findByText(/This draft is unavailable/);expect(screen.getByRole('button',{name:'Save draft'})).toBeDisabled();expect(screen.getByLabelText('Draft ID')).toHaveValue(id);}fireEvent.click(screen.getByRole('button',{name:'Load draft'}));await screen.findByText(/Current draft revision 1 loaded/);expect(screen.getByLabelText('Draft name')).toHaveValue('Current persisted design');expect(screen.getByRole('button',{name:'Save draft'})).toBeEnabled();expect(calls.mock.calls.slice(2).filter(([,options])=>options?.method==='POST')).toHaveLength(1);expect(calls.mock.calls.slice(3).every(([,options])=>options?.method==='GET')).toBe(true);expect(client.paidSimplePublicationState(tenant)).toEqual({phase:'ready'});
});
it('reconciles a remounted pending draft load and permits an explicit fresh read after completion',async()=>{
 let resolve!:(response:Response)=>void,n=0;const dto={flowId:other,revision:4,serviceId,name:'Stored design',presentation:{accentColor:'#0f766e',layout:'stacked'}};const {client,calls}=await fixture(async()=>++n===1?new Promise<Response>(r=>resolve=r):json({ok:true,data:dto}));const first=render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fireEvent.change(screen.getByLabelText('Draft ID'),{target:{value:other}});fireEvent.click(screen.getByRole('button',{name:'Load draft'}));await waitFor(()=>expect(resolve).toBeTypeOf('function'));first.unmount();render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);expect(screen.getByRole('button',{name:'Load draft'})).toBeDisabled();resolve(json({ok:true,data:dto}));await waitFor(()=>expect(client.paidSimpleDraftState(tenant).phase).toBe('loaded'));fireEvent.click(screen.getByRole('button',{name:"Check this session's draft state"}));expect(screen.getByRole('button',{name:'Load draft'})).toBeEnabled();expect(calls).toHaveBeenCalledTimes(3);fireEvent.click(screen.getByRole('button',{name:'Load draft'}));await screen.findByText(/Current draft revision 4 loaded/);expect(screen.getByLabelText('Draft name')).toHaveValue('Stored design');expect(screen.getByRole('button',{name:'Save draft'})).toBeEnabled();expect(calls).toHaveBeenCalledTimes(4);expect(calls.mock.calls.slice(2).every(([,options])=>options?.method==='GET')).toBe(true);
});
it('reconciles a remounted pending publication through its existing session-state check without repeating the writer',async()=>{
 let resolve!:(response:Response)=>void;const {client,calls}=await fixture(()=>new Promise<Response>(r=>resolve=r));const first=render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fill();fireEvent.click(screen.getByText('Publish staging test form'));await waitFor(()=>expect(resolve).toBeTypeOf('function'));first.unmount();render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);resolve(json({ok:true,data:receipt}));await waitFor(()=>expect(client.paidSimplePublicationState(tenant).phase).toBe('published'));fireEvent.click(screen.getByRole('button',{name:"Check this session's receipt"}));await screen.findByText('Staging form published');expect(calls).toHaveBeenCalledTimes(3);expect(calls.mock.calls[2]?.[1]?.method).toBe('POST');expect(screen.queryByText('Publish staging test form')).toBeNull();
});
it('permits a fresh explicit receipt read after remounting an in-flight publication recovery without any writer',async()=>{
 let resolve!:(response:Response)=>void,n=0;const {client,calls}=await fixture(async()=>++n===1?new Promise<Response>(r=>resolve=r):json({ok:true,data:receipt}));const first=render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fireEvent.change(screen.getByLabelText('Publication attempt ID'),{target:{value:other}});fireEvent.click(screen.getByRole('button',{name:'Check publication receipt'}));await waitFor(()=>expect(resolve).toBeTypeOf('function'));first.unmount();render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);expect(screen.getByRole('button',{name:'Check publication receipt'})).toBeEnabled();resolve(json({ok:true,data:receipt}));await waitFor(()=>expect(client.paidSimplePublicationState(tenant).phase).toBe('published'));fireEvent.click(screen.getByRole('button',{name:'Check publication receipt'}));await screen.findByText('Staging form published');expect(calls).toHaveBeenCalledTimes(4);expect(calls.mock.calls.slice(2).every(([,options])=>options?.method==='GET')).toBe(true);
});

const publishDraftDto={flowId:other,revision:3,serviceId,name:'Stored design',presentation:{accentColor:'#0f766e',layout:'compact'}};
async function loadKnownDraft(){fireEvent.change(screen.getByLabelText('Draft ID'),{target:{value:other}});fireEvent.click(screen.getByRole('button',{name:'Load draft'}));await screen.findByText(/Current draft revision 3 loaded/);}
it('publishes only pristine loaded server fields and displays the canonical immutable saved revision receipt',async()=>{
 let n=0;const {client,calls}=await fixture(async()=>++n===1?json({ok:true,data:publishDraftDto}):json({ok:true,data:{flowId:other,draftRevision:3,publication:receipt}}));render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);expect(screen.getByRole('button',{name:'Publish saved draft'})).toBeDisabled();await loadKnownDraft();expect(screen.getByRole('button',{name:'Publish saved draft'})).toBeEnabled();fireEvent.change(screen.getByLabelText('Draft name'),{target:{value:'Unsaved name'}});expect(screen.getByRole('button',{name:'Publish saved draft'})).toBeDisabled();fireEvent.change(screen.getByLabelText('Draft name'),{target:{value:publishDraftDto.name}});fireEvent.click(screen.getByRole('button',{name:'Publish saved draft'}));await screen.findByText('Staging form published');expect(calls.mock.calls[3]?.[0]).toContain('/'+other+'/publish-draft?tenantId='+tenant);expect(JSON.parse(calls.mock.calls[3]?.[1]?.body as string)).toEqual({expectedDraftRevision:3,allowedOrigins:[STAGING_CHECKOUT_ORIGIN]});expect(screen.getByText(/Published draft revision: 3; immutable version:/)).toBeTruthy();expect(screen.getByRole('link',{name:'Open staging booking form'})).toHaveAttribute('href',STAGING_CHECKOUT_ORIGIN+receipt.hostedPath);expect((screen.getByLabelText('Website iframe code') as HTMLTextAreaElement).value).toContain(STAGING_CHECKOUT_ORIGIN+receipt.hostedPath);expect(screen.queryByText('Publish staging test form')).toBeNull();expect(screen.getByRole('button',{name:'Publish saved draft'})).toBeDisabled();
});
it('freezes a lost saved publication through remount and conflict then explicitly retries identical bytes without draft changes',async()=>{
 let n=0;const {client,calls}=await fixture(async()=>++n===1?json({ok:true,data:publishDraftDto}):n===2?Promise.reject(Error('private failure')):n===3?json({ok:false,code:'CONFLICT'},409):json({ok:true,data:{flowId:other,draftRevision:3,publication:receipt}}));const first=render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);await loadKnownDraft();fireEvent.click(screen.getByRole('button',{name:'Publish saved draft'}));await screen.findByRole('button',{name:'Retry this saved-draft publication'});expect(screen.getByLabelText('Draft name')).toBeDisabled();expect(screen.getByRole('button',{name:'Load draft'})).toBeDisabled();first.unmount();render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);expect(calls).toHaveBeenCalledTimes(4);fireEvent.click(screen.getByRole('button',{name:'Retry this saved-draft publication'}));await screen.findByText(/This response does not prove the earlier attempt failed/);expect(screen.getByRole('button',{name:'Save draft'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'Retry this saved-draft publication'}));await screen.findByText('Staging form published');expect(calls.mock.calls.slice(3).every(([url,options])=>String(url).includes('/'+other+'/publish-draft?')&&options?.body===calls.mock.calls[3]?.[1]?.body)).toBe(true);expect(document.body.textContent).not.toContain('private failure');
});
it('settles an in-flight saved publication after remount only through explicit session reconciliation with no extra writer',async()=>{
 let n=0,resolve!:(response:Response)=>void;const {client,calls}=await fixture(async()=>++n===1?json({ok:true,data:publishDraftDto}):new Promise(r=>resolve=r));const first=render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);await loadKnownDraft();fireEvent.click(screen.getByRole('button',{name:'Publish saved draft'}));await waitFor(()=>expect(resolve).toBeTypeOf('function'));first.unmount();render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);expect(screen.getByRole('button',{name:'Publish saved draft'})).toBeDisabled();resolve(json({ok:true,data:{flowId:other,draftRevision:3,publication:receipt}}));await waitFor(()=>expect(client.paidSimpleSavedDraftPublicationState(tenant).phase).toBe('published'));fireEvent.click(screen.getByRole('button',{name:"Check this session's saved publication state"}));await screen.findByText('Staging form published');expect(screen.getByRole('button',{name:'Load draft'})).toBeEnabled();expect(calls).toHaveBeenCalledTimes(4);
});
it('allows a fresh draft read after first definitive conflict but never publishes a legacy uncertain attempt',async()=>{
 let n=0;const {client,calls}=await fixture(async()=>++n===1?json({ok:true,data:publishDraftDto}):n===2?json({ok:false,code:'CONFLICT'},409):n===3?json({ok:true,data:publishDraftDto}):json({ok:false,code:'INTERNAL_ERROR'},500));render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);await loadKnownDraft();fireEvent.click(screen.getByRole('button',{name:'Publish saved draft'}));await screen.findByText(/Saved-draft publication was rejected/);expect(screen.getByRole('button',{name:'Publish saved draft'})).toBeDisabled();expect(screen.getByRole('button',{name:'Load draft'})).toBeEnabled();fireEvent.click(screen.getByRole('button',{name:'Load draft'}));await screen.findByText(/Current draft revision 3 loaded/);fill();fireEvent.click(screen.getByRole('button',{name:'Publish staging test form'}));await screen.findByText(/Publishing again is locked/);expect(screen.getByRole('button',{name:'Publish saved draft'})).toBeDisabled();expect(calls).toHaveBeenCalledTimes(6);
});

it.each([['Draft simple service',''],['Draft accent color','#be123c'],['Draft layout','stacked']])('denies saved publication with unsaved %s changes',async(label,value)=>{
 const {client,calls}=await fixture(async()=>json({ok:true,data:publishDraftDto}));render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);await loadKnownDraft();fireEvent.change(screen.getByLabelText(label),{target:{value}});expect(screen.getByRole('button',{name:'Publish saved draft'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'Publish saved draft'}));expect(calls).toHaveBeenCalledTimes(3);
});
it('drops a late saved publication receipt when the selected tenant changes without leaking old fields or version',async()=>{
 let n=0,resolve!:(response:Response)=>void;const {client}=await fixture(async()=>++n===1?json({ok:true,data:publishDraftDto}):new Promise(r=>resolve=r));const {rerender}=render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);await loadKnownDraft();fireEvent.click(screen.getByRole('button',{name:'Publish saved draft'}));await waitFor(()=>expect(resolve).toBeTypeOf('function'));rerender(<PaidSimplePublisher client={client} tenantId={other} role="BUSINESS_OWNER" services={[{...service,tenant_id:other}]} staging/>);expect(screen.getByLabelText('Draft name')).toHaveValue('');resolve(json({ok:true,data:{flowId:other,draftRevision:3,publication:receipt}}));await waitFor(()=>expect(client.paidSimpleSavedDraftPublicationState(tenant).phase).toBe('published'));expect(screen.queryByText('Staging form published')).toBeNull();expect(screen.queryByText(/Published draft revision:/)).toBeNull();expect(client.paidSimpleSavedDraftPublicationState(other)).toEqual({phase:'ready'});
});

it('reconciles an uncertain pending saved publication after remount without replaying and leaves only explicit frozen retry available',async()=>{
 let n=0,resolve!:(response:Response)=>void;const {client,calls}=await fixture(async()=>++n===1?json({ok:true,data:publishDraftDto}):new Promise(r=>resolve=r));const first=render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);await loadKnownDraft();fireEvent.click(screen.getByRole('button',{name:'Publish saved draft'}));await waitFor(()=>expect(resolve).toBeTypeOf('function'));first.unmount();render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);resolve(json({ok:false,code:'INTERNAL_ERROR'},500));await waitFor(()=>expect(client.paidSimpleSavedDraftPublicationState(tenant).phase).toBe('unknown'));fireEvent.click(screen.getByRole('button',{name:"Check this session's saved publication state"}));expect(screen.getByRole('button',{name:'Retry this saved-draft publication'})).toBeEnabled();expect(screen.getByRole('button',{name:'Save draft'})).toBeDisabled();expect(screen.getByRole('button',{name:'Load draft'})).toBeDisabled();expect(screen.queryByRole('button',{name:'Check publication receipt'})).toBeNull();expect(screen.queryByText('Staging form published')).toBeNull();expect(calls).toHaveBeenCalledTimes(4);
});

const discoveredUiDrafts=[{...publishDraftDto,name:'Saved catalog draft',revision:2},{...publishDraftDto,flowId:serviceId,name:'Second saved draft',revision:7}];
it('refreshes saved drafts explicitly and selects only through a fresh current draft GET before editing or publishing',async()=>{
 let n=0;const {client,calls}=await fixture(async()=>++n===1?json({ok:true,data:{drafts:discoveredUiDrafts}}):json({ok:true,data:{...publishDraftDto,name:'Fresh server name',revision:4,presentation:{accentColor:'#be123c',layout:'stacked'}}}));render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);expect(calls).toHaveBeenCalledTimes(2);fireEvent.click(screen.getByRole('button',{name:'Refresh saved drafts'}));await screen.findByRole('button',{name:'Load saved draft: Saved catalog draft'});expect(calls.mock.calls[2]).toEqual(['https://api.example.test/api/paid-simple-drafts?tenantId='+tenant,{method:'GET',credentials:'omit',cache:'no-store',redirect:'error',referrerPolicy:'no-referrer',headers:{Authorization:'Bearer synthetic-owner-private-token'}}]);expect(screen.getByLabelText('Draft name')).toHaveValue('');expect(screen.getByRole('button',{name:'Publish saved draft'})).toBeDisabled();expect(client.paidSimpleDraftState(tenant)).toEqual({phase:'ready'});fireEvent.change(screen.getByLabelText('Draft name'),{target:{value:'Local unsaved fields'}});fireEvent.click(screen.getByRole('button',{name:'Load saved draft: Saved catalog draft'}));await screen.findByText(/Current draft revision 4 loaded/);expect(screen.getByLabelText('Draft name')).toHaveValue('Fresh server name');expect(screen.getByLabelText('Draft accent color')).toHaveValue('#be123c');expect(screen.getByLabelText('Draft layout')).toHaveValue('stacked');expect(screen.getByRole('button',{name:'Publish saved draft'})).toBeEnabled();expect(calls.mock.calls[3]).toEqual(['https://api.example.test/api/paid-simple-flows/'+other+'/draft?tenantId='+tenant,{method:'GET',credentials:'omit',cache:'no-store',redirect:'error',referrerPolicy:'no-referrer',headers:{Authorization:'Bearer synthetic-owner-private-token'}}]);expect(calls.mock.calls.slice(2).every(([,options])=>options?.method==='GET'&&!options.body)).toBe(true);expect(document.body.textContent).not.toContain('synthetic-owner-private-token');
});
it.each(['empty','unavailable','malformed'])('preserves a legacy publication uncertainty lock after %s saved draft discovery',async(kind)=>{
 let n=0;const {client,calls}=await fixture(async()=>++n===1?Promise.reject(Error('SECRET')):kind==='empty'?json({ok:true,data:{drafts:[]}}):kind==='unavailable'?json({ok:false,code:'NOT_AVAILABLE'},404):json({ok:true,data:{drafts:[{...discoveredUiDrafts[0],price:1}]}}));render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fill();fireEvent.click(screen.getByText('Publish staging test form'));await screen.findByText(/Publishing again is locked/);const locked=client.paidSimplePublicationState(tenant);fireEvent.click(screen.getByRole('button',{name:'Refresh saved drafts'}));await screen.findByText(kind==='empty'?/No saved drafts were returned/:kind==='unavailable'?/saved draft list could not be verified/:/saved draft list could not be validated/);expect(client.paidSimplePublicationState(tenant)).toEqual(locked);expect(screen.queryByText('Publish staging test form')).toBeNull();expect(screen.getByRole('button',{name:'Publish saved draft'})).toBeDisabled();expect(calls).toHaveBeenCalledTimes(4);
});
it('keeps saved publication uncertainty frozen while allowing read-only discovery but no draft selection',async()=>{
 let n=0;const {client,calls}=await fixture(async()=>++n===1?json({ok:true,data:publishDraftDto}):n===2?json({ok:false,code:'INTERNAL_ERROR'},500):json({ok:true,data:{drafts:discoveredUiDrafts}}));render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);await loadKnownDraft();fireEvent.click(screen.getByRole('button',{name:'Publish saved draft'}));await screen.findByRole('button',{name:'Retry this saved-draft publication'});const locked=client.paidSimpleSavedDraftPublicationState(tenant);fireEvent.click(screen.getByRole('button',{name:'Refresh saved drafts'}));await screen.findByRole('button',{name:'Load saved draft: Saved catalog draft'});expect(screen.getByRole('button',{name:'Load saved draft: Saved catalog draft'})).toBeDisabled();expect(screen.getByRole('button',{name:'Load saved draft: Second saved draft'})).toBeDisabled();expect(screen.getByRole('button',{name:'Save draft'})).toBeDisabled();expect(client.paidSimpleSavedDraftPublicationState(tenant)).toEqual(locked);expect(calls).toHaveBeenCalledTimes(5);
});
it('allows fresh selection of only the same draft after an uncertain save, never a list-derived save or revision',async()=>{
 const id=other;vi.spyOn(crypto,'randomUUID').mockReturnValue(id);let n=0;const {client,calls}=await fixture(async()=>++n===1?json({ok:false,code:'INTERNAL_ERROR'},500):n===2?json({ok:true,data:{drafts:discoveredUiDrafts}}):json({ok:true,data:{...publishDraftDto,revision:5}}));render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fillDraft();fireEvent.click(screen.getByRole('button',{name:'Save draft'}));await screen.findByText(/Draft status is unverified/);const locked=client.paidSimpleDraftState(tenant);fireEvent.click(screen.getByRole('button',{name:'Refresh saved drafts'}));await screen.findByRole('button',{name:'Load saved draft: Saved catalog draft'});expect(client.paidSimpleDraftState(tenant)).toEqual(locked);expect(screen.getByRole('button',{name:'Save draft'})).toBeDisabled();expect(screen.getByRole('button',{name:'Load saved draft: Second saved draft'})).toBeDisabled();expect(screen.getByRole('button',{name:'Load saved draft: Saved catalog draft'})).toBeEnabled();fireEvent.click(screen.getByRole('button',{name:'Load saved draft: Saved catalog draft'}));await screen.findByText(/Current draft revision 5 loaded/);expect(screen.getByRole('button',{name:'Save draft'})).toBeEnabled();expect(calls.mock.calls.slice(2).filter(([,options])=>options?.method==='POST')).toHaveLength(1);expect(calls.mock.calls[4]?.[0]).toContain('/'+other+'/draft?tenantId='+tenant);
});
it.each(['tenant','client'])('drops a late saved draft discovery result after %s changes',async(change)=>{
 let resolve!:(response:Response)=>void;const {client,calls}=await fixture(()=>new Promise(r=>resolve=r));const fresh=await fixture(async()=>json({ok:true,data:{drafts:[]}}));const {rerender}=render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fireEvent.click(screen.getByRole('button',{name:'Refresh saved drafts'}));await waitFor(()=>expect(resolve).toBeTypeOf('function'));rerender(<PaidSimplePublisher client={change==='client'?fresh.client:client} tenantId={change==='tenant'?other:tenant} role="BUSINESS_OWNER" services={[{...service,tenant_id:change==='tenant'?other:tenant}]} staging/>);resolve(json({ok:true,data:{drafts:discoveredUiDrafts}}));await waitFor(()=>expect(screen.getByRole('button',{name:'Refresh saved drafts'})).toBeEnabled());expect(screen.queryByRole('button',{name:'Load saved draft: Saved catalog draft'})).toBeNull();expect(screen.getByLabelText('Draft name')).toHaveValue('');expect(calls).toHaveBeenCalledTimes(3);expect(fresh.calls).toHaveBeenCalledTimes(2);
});
it('drops a late selected draft read after the business changes and never hydrates fields from its old list',async()=>{
 let n=0,resolve!:(response:Response)=>void;const {client}=await fixture(async()=>++n===1?json({ok:true,data:{drafts:discoveredUiDrafts}}):new Promise(r=>resolve=r));const {rerender}=render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fireEvent.click(screen.getByRole('button',{name:'Refresh saved drafts'}));await screen.findByRole('button',{name:'Load saved draft: Saved catalog draft'});fireEvent.click(screen.getByRole('button',{name:'Load saved draft: Saved catalog draft'}));await waitFor(()=>expect(resolve).toBeTypeOf('function'));expect(screen.getByLabelText('Draft name')).toHaveValue('');rerender(<PaidSimplePublisher client={client} tenantId={other} role="BUSINESS_OWNER" services={[{...service,tenant_id:other}]} staging/>);resolve(json({ok:true,data:publishDraftDto}));await waitFor(()=>expect(client.paidSimpleDraftState(tenant).phase).toBe('loaded'));expect(screen.getByLabelText('Draft name')).toHaveValue('');expect(screen.queryByText(/Current draft revision 3 loaded/)).toBeNull();expect(screen.getByRole('button',{name:'Publish saved draft'})).toBeDisabled();
});
it('does not retain a loading discovery state after remount or repeat any writer',async()=>{
 let resolve!:(response:Response)=>void,n=0;const {client,calls}=await fixture(async()=>++n===1?new Promise(r=>resolve=r):json({ok:true,data:{drafts:discoveredUiDrafts}}));const first=render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fireEvent.click(screen.getByRole('button',{name:'Refresh saved drafts'}));await waitFor(()=>expect(resolve).toBeTypeOf('function'));first.unmount();render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);expect(screen.getByRole('button',{name:'Refresh saved drafts'})).toBeEnabled();resolve(json({ok:true,data:{drafts:discoveredUiDrafts}}));expect(screen.queryByRole('button',{name:'Load saved draft: Saved catalog draft'})).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Refresh saved drafts'}));await screen.findByRole('button',{name:'Load saved draft: Saved catalog draft'});expect(calls).toHaveBeenCalledTimes(4);expect(calls.mock.calls.slice(2).every(([,options])=>options?.method==='GET')).toBe(true);
});

const uiVersionHistory={flowId:other,versions:[{versionId:other,draftRevision:4,name:'Pinned current name',presentation:{accentColor:'#2563eb',layout:'compact'},current:true,publication:receipt},{versionId:tenant,draftRevision:2,name:'Pinned historical name',presentation:{accentColor:'#be123c',layout:'stacked'},current:false,publication:null}]};
function refreshHistory(flowId=other){fireEvent.change(screen.getByLabelText('Version history form ID'),{target:{value:flowId}});fireEvent.click(screen.getByRole('button',{name:'Refresh version history'}));}
it('refreshes immutable version names/designs explicitly and links only independently verified installations without creating authority',async()=>{
 const {client,calls}=await fixture(async()=>json({ok:true,data:uiVersionHistory}));render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);expect(calls).toHaveBeenCalledTimes(2);refreshHistory();await screen.findByText('Pinned historical name');expect(calls.mock.calls[2]).toEqual(['https://api.example.test/api/paid-simple-flows/'+other+'/versions?tenantId='+tenant,{method:'GET',credentials:'omit',cache:'no-store',redirect:'error',referrerPolicy:'no-referrer',headers:{Authorization:'Bearer synthetic-owner-private-token'}}]);expect(screen.getByText('Current version at last refresh')).toBeTruthy();expect(screen.getByText('Historical version')).toBeTruthy();expect(screen.getByText('Pinned design: Compact; accent color #2563eb')).toBeTruthy();expect(screen.getByText('Pinned design: Stacked; accent color #be123c')).toBeTruthy();expect(screen.getByRole('link',{name:'Open published revision 4: Pinned current name'})).toHaveAttribute('href',STAGING_CHECKOUT_ORIGIN+receipt.hostedPath);expect(screen.queryByRole('link',{name:'Open published revision 2: Pinned historical name'})).toBeNull();expect(screen.getByText('No verified installation link for this version.')).toBeTruthy();expect(screen.queryByText('Staging form published')).toBeNull();expect(screen.queryByRole('button',{name:/rollback/i})).toBeNull();expect(client.paidSimpleDraftState(tenant)).toEqual({phase:'ready'});expect(client.paidSimplePublicationState(tenant)).toEqual({phase:'ready'});expect(screen.getByRole('button',{name:'Publish saved draft'})).toBeDisabled();expect(document.body.textContent).not.toContain('synthetic-owner-private-token');
});
it('escapes pinned history names and shows no link from malformed nullable receipts',async()=>{
 const hostile='<img src=x onerror=alert(1)>';let n=0;const {client}=await fixture(async()=>++n===1?json({ok:true,data:{...uiVersionHistory,versions:[{...uiVersionHistory.versions[0],name:hostile},uiVersionHistory.versions[1]]}}):json({ok:true,data:{...uiVersionHistory,versions:[{...uiVersionHistory.versions[0],publication:{...receipt,hostedPath:'https://unapproved.example'}},uiVersionHistory.versions[1]]}}));render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);refreshHistory();const heading=await screen.findByRole('heading',{name:hostile});expect(heading.querySelector('img')).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Refresh version history'}));await screen.findByText('Version history could not be validated.');expect(screen.queryByRole('link',{name:/Open published revision/})).toBeNull();expect(screen.queryByRole('heading',{name:hostile})).toBeNull();expect(client.paidSimplePublicationState(tenant)).toEqual({phase:'ready'});
});
it('keeps legacy publication uncertainty locked even after authoritative current history evidence',async()=>{
 let n=0;const {client,calls}=await fixture(async()=>++n===1?json({ok:false,code:'INTERNAL_ERROR'},500):json({ok:true,data:{...uiVersionHistory,flowId:client.paidSimplePublicationState(tenant).phase==='ready'?other:(client.paidSimplePublicationState(tenant) as {flowId:string}).flowId}}));render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fill();fireEvent.click(screen.getByText('Publish staging test form'));await screen.findByText(/Publishing again is locked/);const state=client.paidSimplePublicationState(tenant);if(state.phase==='ready')throw Error('Expected unknown attempt');refreshHistory(state.flowId);await screen.findByText('Pinned current name');expect(client.paidSimplePublicationState(tenant)).toEqual(state);expect(screen.queryByText('Publish staging test form')).toBeNull();expect(screen.queryByText('Staging form published')).toBeNull();expect(screen.getByRole('button',{name:'Publish saved draft'})).toBeDisabled();expect(calls.mock.calls[3]?.[1]?.method).toBe('GET');
});
it('keeps saved publication frozen and editor actions locked after current version history',async()=>{
 let n=0;const {client,calls}=await fixture(async()=>++n===1?json({ok:true,data:publishDraftDto}):n===2?json({ok:false,code:'INTERNAL_ERROR'},500):json({ok:true,data:uiVersionHistory}));render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);await loadKnownDraft();fireEvent.click(screen.getByRole('button',{name:'Publish saved draft'}));await screen.findByRole('button',{name:'Retry this saved-draft publication'});const state=client.paidSimpleSavedDraftPublicationState(tenant);refreshHistory();await screen.findByText('Pinned current name');expect(client.paidSimpleSavedDraftPublicationState(tenant)).toEqual(state);expect(screen.getByRole('button',{name:'Load draft'})).toBeDisabled();expect(screen.getByRole('button',{name:'Save draft'})).toBeDisabled();expect(screen.queryByText('Staging form published')).toBeNull();expect(calls).toHaveBeenCalledTimes(5);
});
it.each(['tenant','client'])('drops a late version history result after %s changes',async(change)=>{
 let finish!:(response:Response)=>void;const {client,calls}=await fixture(()=>new Promise(r=>finish=r));const method=vi.spyOn(client,'paidSimpleVersionHistory');const fresh=await fixture(async()=>json({ok:true,data:uiVersionHistory}));const {rerender}=render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);refreshHistory();await waitFor(()=>expect(finish).toBeTypeOf('function'));rerender(<PaidSimplePublisher client={change==='client'?fresh.client:client} tenantId={change==='tenant'?other:tenant} role="BUSINESS_OWNER" services={[{...service,tenant_id:change==='tenant'?other:tenant}]} staging/>);finish(json({ok:true,data:uiVersionHistory}));await method.mock.results[0]!.value;await waitFor(()=>expect(screen.queryByText('Pinned current name')).toBeNull());expect(screen.getByLabelText('Version history form ID')).toHaveValue('');expect(screen.getByRole('button',{name:'Refresh version history'})).toBeEnabled();expect(calls).toHaveBeenCalledTimes(3);expect(fresh.calls).toHaveBeenCalledTimes(2);
});
it('drops a late history for an edited form ID and performs no automatic read for the new ID',async()=>{
 let finish!:(response:Response)=>void,n=0;const {client,calls}=await fixture(async()=>++n===1?new Promise(r=>finish=r):json({ok:true,data:{...uiVersionHistory,flowId:serviceId}}));const method=vi.spyOn(client,'paidSimpleVersionHistory');render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);refreshHistory();await waitFor(()=>expect(finish).toBeTypeOf('function'));fireEvent.change(screen.getByLabelText('Version history form ID'),{target:{value:serviceId}});finish(json({ok:true,data:uiVersionHistory}));await method.mock.results[0]!.value;expect(screen.queryByText('Pinned current name')).toBeNull();expect(calls).toHaveBeenCalledTimes(3);fireEvent.click(screen.getByRole('button',{name:'Refresh version history'}));await screen.findByText('Pinned current name');expect(calls.mock.calls[3]?.[0]).toContain('/'+serviceId+'/versions?tenantId='+tenant);expect(calls.mock.calls.slice(2).every(([,options])=>options?.method==='GET')).toBe(true);
});
it('allows explicit history refresh after remount without keeping a pending lock or replaying a writer',async()=>{
 let finish!:(response:Response)=>void,n=0;const {client,calls}=await fixture(async()=>++n===1?new Promise(r=>finish=r):json({ok:true,data:uiVersionHistory}));const method=vi.spyOn(client,'paidSimpleVersionHistory');const first=render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);refreshHistory();await waitFor(()=>expect(finish).toBeTypeOf('function'));first.unmount();render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);expect(screen.getByRole('button',{name:'Refresh version history'})).toBeEnabled();expect(calls).toHaveBeenCalledTimes(3);finish(json({ok:true,data:uiVersionHistory}));await method.mock.results[0]!.value;expect(screen.queryByText('Pinned current name')).toBeNull();refreshHistory();await screen.findByText('Pinned current name');expect(calls).toHaveBeenCalledTimes(4);expect(calls.mock.calls.slice(2).every(([,options])=>options?.method==='GET')).toBe(true);
});
it('refuses invalid history IDs without reading and keeps unavailable history separate from editor authority',async()=>{
 const {client,calls}=await fixture(async()=>json({ok:false,code:'NOT_AVAILABLE'},404));render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);refreshHistory('invalid');await screen.findByText('Enter a known form ID for this business.');expect(calls).toHaveBeenCalledTimes(2);refreshHistory();await screen.findByText(/Version history is unavailable for this form/);expect(client.paidSimpleDraftState(tenant)).toEqual({phase:'ready'});expect(client.paidSimplePublicationState(tenant)).toEqual({phase:'ready'});expect(screen.getByLabelText('Draft ID')).toHaveValue('');expect(screen.queryByText('Pinned current name')).toBeNull();expect(calls).toHaveBeenCalledTimes(3);
});

it('opens draft preview explicitly without reads or writes and keeps device controls outside the save form',async()=>{
 const {client,calls}=await fixture(async()=>{throw Error('unexpected request');});
 const {rerender}=render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);
 expect(screen.queryByLabelText('Draft presentation preview')).toBeNull();
 fillDraft();fireEvent.change(screen.getByLabelText('Draft accent color'),{target:{value:'#be123c'}});fireEvent.change(screen.getByLabelText('Draft layout'),{target:{value:'compact'}});
 const trigger=screen.getByRole('button',{name:'Preview draft presentation'});expect(trigger).toHaveAttribute('type','button');expect(trigger.closest('form')).toBeNull();fireEvent.click(trigger);
 expect(screen.getByRole('heading',{name:'Housekeeping design'})).toHaveStyle({color:'#be123c'});expect(screen.getByText('Current catalog price: $125.00')).toBeTruthy();
 fireEvent.click(screen.getByRole('radio',{name:'Desktop 1024'}));expect(calls).toHaveBeenCalledTimes(2);expect(client.paidSimpleDraftState(tenant)).toEqual({phase:'ready'});expect(client.paidSimplePublicationState(tenant)).toEqual({phase:'ready'});
 rerender(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[]} staging/>);expect(screen.queryByText(/Current catalog price:/)).toBeNull();expect(screen.getByText(/Service details are unavailable or unverified/)).toBeTruthy();
 rerender(<PaidSimplePublisher client={client} tenantId={other} role="BUSINESS_OWNER" services={[{...service,tenant_id:other}]} staging/>);expect(screen.queryByLabelText('Draft presentation preview')).toBeNull();expect(screen.getByLabelText('Draft name')).toHaveValue('');expect(calls).toHaveBeenCalledTimes(2);
});
it('preview and device changes retain unknown draft-save locks without reconciliation or another POST',async()=>{
 const {client,calls}=await fixture(async()=>{throw Error('unknown');});render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);
 fillDraft();fireEvent.click(screen.getByRole('button',{name:'Save draft'}));await screen.findByText(/Draft writes are locked/);const locked=client.paidSimpleDraftState(tenant);
 fireEvent.click(screen.getByRole('button',{name:'Preview draft presentation'}));fireEvent.click(screen.getByRole('radio',{name:'Tablet 768'}));expect(client.paidSimpleDraftState(tenant)).toEqual(locked);expect(screen.getByRole('button',{name:'Save draft'})).toBeDisabled();expect(screen.getByRole('button',{name:'Publish saved draft'})).toBeDisabled();expect(calls).toHaveBeenCalledTimes(3);
});
it('preview cannot release a legacy unknown publication or create customer capabilities',async()=>{
 const {client,calls}=await fixture(async()=>{throw Error('unknown');});render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fill();fireEvent.click(screen.getByRole('button',{name:'Publish staging test form'}));await screen.findByText(/Publishing again is locked/);const locked=client.paidSimplePublicationState(tenant);
 fillDraft();fireEvent.click(screen.getByRole('button',{name:'Preview draft presentation'}));fireEvent.click(screen.getByRole('radio',{name:'Desktop 1024'}));expect(client.paidSimplePublicationState(tenant)).toEqual(locked);expect(screen.queryByRole('button',{name:'Publish staging test form'})).toBeNull();expect(screen.getByRole('button',{name:'Publish saved draft'})).toBeDisabled();expect(calls).toHaveBeenCalledTimes(3);expect(calls.mock.calls.slice(2).some(([url])=>String(url).includes('flow-sessions'))).toBe(false);
});

it('preview retains frozen saved-publication identity and locked editor fields after an ambiguous publish',async()=>{
 let n=0;const {client,calls}=await fixture(async()=>++n===1?json({ok:true,data:publishDraftDto}):json({ok:false,code:'INTERNAL_ERROR'},500));render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);await loadKnownDraft();fireEvent.click(screen.getByRole('button',{name:'Publish saved draft'}));await screen.findByRole('button',{name:'Retry this saved-draft publication'});const frozen=client.paidSimpleSavedDraftPublicationState(tenant);
 fireEvent.click(screen.getByRole('button',{name:'Preview draft presentation'}));fireEvent.click(screen.getByRole('radio',{name:'Tablet 768'}));expect(screen.getByRole('heading',{name:'Stored design'})).toBeTruthy();expect(screen.getByLabelText('Draft name')).toBeDisabled();expect(screen.getByRole('button',{name:'Save draft'})).toBeDisabled();expect(screen.getByRole('button',{name:'Load draft'})).toBeDisabled();expect(client.paidSimpleSavedDraftPublicationState(tenant)).toEqual(frozen);expect(calls).toHaveBeenCalledTimes(4);
});
it('closes the preview on client replacement and ignores an old pending load response',async()=>{
 let resolve!:(response:Response)=>void;const first=await fixture(()=>new Promise<Response>(r=>resolve=r)),second=await fixture(async()=>{throw Error('unexpected');});
 const {rerender}=render(<PaidSimplePublisher client={first.client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fillDraft();fireEvent.click(screen.getByRole('button',{name:'Preview draft presentation'}));fireEvent.change(screen.getByLabelText('Draft ID'),{target:{value:other}});fireEvent.click(screen.getByRole('button',{name:'Load draft'}));await waitFor(()=>expect(resolve).toBeTypeOf('function'));
 rerender(<PaidSimplePublisher client={second.client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);expect(screen.queryByLabelText('Draft presentation preview')).toBeNull();resolve(json({ok:true,data:publishDraftDto}));await waitFor(()=>expect(first.client.paidSimpleDraftState(tenant).phase).toBe('loaded'));expect(screen.getByLabelText('Draft name')).toHaveValue('');fireEvent.click(screen.getByRole('button',{name:'Preview draft presentation'}));expect(screen.getByRole('heading',{name:'Untitled draft'})).toBeTruthy();expect(screen.queryByRole('heading',{name:'Stored design'})).toBeNull();expect(second.calls).toHaveBeenCalledTimes(2);
});
