import {afterEach,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {createRuntimeClient,type ServiceRow} from '@lumin/runtime-client';
import {PaidSimplePublisher,STAGING_CHECKOUT_ORIGIN} from './PaidSimplePublisher';
const tenant='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222',serviceId='33333333-3333-4333-8333-333333333333';
const service:ServiceRow={id:serviceId,tenant_id:tenant,name:'Housekeeping',currency:'USD',duration_minutes:60,base_price:12500,active:true};
const receipt={versionId:other,installationId:serviceId,renderSchemaVersion:3,hostedPath:'/checkout/flow/'+serviceId};
const json=(value:unknown,status=200)=>new Response(JSON.stringify(value),{status});
afterEach(()=>{cleanup();vi.restoreAllMocks();vi.unstubAllGlobals();});
async function fixture(publish:()=>Promise<Response>){
 const calls=vi.fn<typeof fetch>(async(input)=>String(input).includes('/auth/v1/token')?json({access_token:'synthetic-owner-private-token'}):String(input).includes('/auth/v1/user')?json({id:other}):publish());
 const client=createRuntimeClient({url:'https://example.supabase.co',publishableKey:'sb_publishable_synthetic',tenantId:tenant,bookingApiOrigin:'https://api.example.test'},calls);await client.signIn('owner@example.test','fixture');return{client,calls};
}
function fill(){fireEvent.change(screen.getByLabelText('Simple service'),{target:{value:serviceId}});fireEvent.change(screen.getByLabelText('Form name'),{target:{value:'Housekeeping booking'}});}
it('publishes only on an explicit owner action and shows the immutable canonical link and iframe receipt',async()=>{
 const {client,calls}=await fixture(async()=>json({ok:true,data:receipt}));render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service,{...service,id:other,active:false},{...service,id:tenant,base_price:0},{...service,id:tenant,tenant_id:other}]} staging/>);
 expect(calls).toHaveBeenCalledTimes(2);expect(screen.getByLabelText('Checkout origin')).toHaveValue(STAGING_CHECKOUT_ORIGIN);expect(Array.from((screen.getByLabelText('Simple service') as HTMLSelectElement).options)).toHaveLength(2);fill();fireEvent.click(screen.getByText('Publish staging test form'));await screen.findByText('Staging form published');expect(calls).toHaveBeenCalledTimes(3);expect(screen.getByRole('link',{name:'Open staging booking form'})).toHaveAttribute('href',STAGING_CHECKOUT_ORIGIN+receipt.hostedPath);expect(screen.getByLabelText('Website iframe code')).toHaveValue(`<iframe src="${STAGING_CHECKOUT_ORIGIN+receipt.hostedPath}" title="Booking Lumin staging test booking" width="100%" height="720" style="border:0"></iframe>`);expect(screen.getByText(receipt.versionId)).toBeTruthy();expect(screen.queryByText('Publish staging test form')).toBeNull();expect(document.body.textContent).not.toContain('synthetic-owner-private-token');
});
it.each([{role:'BUSINESS_STAFF',staging:true},{role:'BUSINESS_OWNER',staging:false}])('blocks staff or nonstaging publication in the UI: %j',async(props)=>{
 const {client,calls}=await fixture(async()=>{throw Error('unexpected');});render(<PaidSimplePublisher client={client} tenantId={tenant} services={[service]} {...props}/>);expect(screen.queryByText('Publish staging test form')).toBeNull();expect(screen.queryByLabelText('Form name')).toBeNull();expect(screen.queryByLabelText('Publication attempt ID')).toBeNull();expect(screen.queryByRole('button',{name:'Check publication receipt'})).toBeNull();expect(screen.queryByRole('button',{name:'Refresh saved forms'})).toBeNull();expect(calls).toHaveBeenCalledTimes(2);
});
it('keeps unknown delivery locked after remount, with no new identity or automatic replay',async()=>{
 const {client,calls}=await fixture(async()=>{throw Error('private-server-token');});const first=render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fill();fireEvent.click(screen.getByText('Publish staging test form'));await screen.findByText(/Publishing again is locked/);expect(screen.queryByText('Publish staging test form')).toBeNull();const attempt=client.paidSimplePublicationState(tenant);expect(attempt.phase).toBe('unknown');first.unmount();render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);await screen.findByText(/Publishing again is locked/);expect(client.paidSimplePublicationState(tenant)).toEqual(attempt);expect(calls).toHaveBeenCalledTimes(3);expect(document.body.textContent).not.toContain('private-server-token');expect(screen.getByRole('button',{name:'Check publication receipt'})).toBeEnabled();
});
it('clears the form and discards a late receipt when the selected business changes',async()=>{
 let resolve!:(response:Response)=>void;const {client,calls}=await fixture(()=>new Promise<Response>(r=>resolve=r));const {rerender}=render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fill();fireEvent.click(screen.getByText('Publish staging test form'));await waitFor(()=>expect(resolve).toBeTypeOf('function'));rerender(<PaidSimplePublisher client={client} tenantId={other} role="BUSINESS_OWNER" services={[{...service,tenant_id:other}]} staging/>);expect(screen.getByLabelText('Form name')).toHaveValue('');resolve(json({ok:true,data:receipt}));await waitFor(()=>expect(client.paidSimplePublicationState(tenant).phase).toBe('published'));expect(screen.queryByText('Staging form published')).toBeNull();expect(screen.queryByText(receipt.versionId)).toBeNull();expect(calls).toHaveBeenCalledTimes(3);
});
it('shows definitive rejection without fabricating publication, and preserves unknown server outcomes',async()=>{
 const {client}=await fixture(async()=>json({ok:false,code:'UNSUPPORTED_CONFIG'},422));render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fill();fireEvent.click(screen.getByText('Publish staging test form'));await screen.findByText('This service does not support the staging paid form.');expect(screen.queryByText('Staging form published')).toBeNull();expect(screen.getByText('Publish staging test form')).toBeEnabled();
});

it('recovers a known attempt after reload only on an explicit read and shows its canonical installation',async()=>{
 const {client,calls}=await fixture(async()=>json({ok:true,data:receipt}));render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fireEvent.change(screen.getByLabelText('Publication attempt ID'),{target:{value:other}});expect(calls).toHaveBeenCalledTimes(2);fireEvent.click(screen.getByRole('button',{name:'Check publication receipt'}));await screen.findByText('Staging form published');expect(calls).toHaveBeenCalledTimes(3);expect(calls.mock.calls[2]?.[0]).toBe('https://api.example.test/api/paid-simple-flows/'+other+'/publication?tenantId='+tenant);expect(calls.mock.calls[2]?.[1]?.method).toBe('GET');expect(screen.getByRole('link',{name:'Open staging booking form'})).toHaveAttribute('href',STAGING_CHECKOUT_ORIGIN+receipt.hostedPath);expect(screen.getByText('Publication attempt')).toBeTruthy();expect(screen.getByLabelText('Publication attempt ID')).toHaveValue(other);expect(screen.getByLabelText('Publication attempt ID')).toHaveAttribute('readonly');expect(document.body.textContent).not.toContain('synthetic-owner-private-token');expect(screen.queryByText('Publish staging test form')).toBeNull();
});
it('keeps a not-found lookup locked and allows only an explicit same-attempt read',async()=>{
 let n=0;const {client,calls}=await fixture(async()=>++n===1?json({ok:false,code:'NOT_AVAILABLE'},404):json({ok:true,data:receipt}));render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fireEvent.change(screen.getByLabelText('Publication attempt ID'),{target:{value:other}});fireEvent.click(screen.getByRole('button',{name:'Check publication receipt'}));await screen.findByText(/No active receipt was found/);expect(screen.queryByText('Publish staging test form')).toBeNull();expect(screen.getByLabelText('Publication attempt ID')).toHaveValue(other);expect(screen.getByLabelText('Publication attempt ID')).toHaveAttribute('readonly');expect(calls).toHaveBeenCalledTimes(3);fireEvent.click(screen.getByRole('button',{name:'Check publication receipt'}));await screen.findByText('Staging form published');expect(calls.mock.calls.slice(2).every(([,options])=>options?.method==='GET')).toBe(true);
});
it('checks an unknown POST attempt without replay or a new identity',async()=>{
 let n=0;const {client,calls}=await fixture(async()=>++n===1?Promise.reject(Error('private-response-secret')):json({ok:true,data:receipt}));render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fill();fireEvent.click(screen.getByText('Publish staging test form'));await screen.findByText(/Publishing again is locked/);const state=client.paidSimplePublicationState(tenant);expect(state.phase).toBe('unknown');fireEvent.click(screen.getByRole('button',{name:'Check publication receipt'}));await screen.findByText('Staging form published');if(state.phase==='unknown')expect(calls.mock.calls[3]?.[0]).toContain('/'+state.flowId+'/publication?');expect(calls.mock.calls[2]?.[1]?.method).toBe('POST');expect(calls.mock.calls[3]?.[1]?.method).toBe('GET');expect(document.body.textContent).not.toContain('private-response-secret');
});
it('clears the recovery field and discards a late receipt on tenant changes',async()=>{
 let resolve!:(response:Response)=>void;const {client}=await fixture(()=>new Promise<Response>(r=>resolve=r));const {rerender}=render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fireEvent.change(screen.getByLabelText('Publication attempt ID'),{target:{value:other}});fireEvent.click(screen.getByRole('button',{name:'Check publication receipt'}));await waitFor(()=>expect(resolve).toBeTypeOf('function'));rerender(<PaidSimplePublisher client={client} tenantId={other} role="BUSINESS_OWNER" services={[{...service,tenant_id:other}]} staging/>);expect(screen.getByLabelText('Publication attempt ID')).toHaveValue('');resolve(json({ok:true,data:receipt}));await waitFor(()=>expect(client.paidSimplePublicationState(tenant).phase).toBe('published'));expect(screen.queryByText('Staging form published')).toBeNull();expect(client.paidSimplePublicationState(other)).toEqual({phase:'ready'});
});
it('rejects invalid recovery IDs without a network read or hiding the publication form',async()=>{
 const {client,calls}=await fixture(async()=>{throw Error('unexpected');});render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fireEvent.change(screen.getByLabelText('Publication attempt ID'),{target:{value:'invalid'}});fireEvent.click(screen.getByRole('button',{name:'Check publication receipt'}));await screen.findByText('Enter the exact publication attempt ID for this business.');expect(calls).toHaveBeenCalledTimes(2);expect(screen.getByText('Publish staging test form')).toBeEnabled();
});

const savedForms=[{flowId:other,name:'Saved housekeeping',publication:receipt},{flowId:serviceId,name:'Another saved form',publication:{versionId:tenant,installationId:other,renderSchemaVersion:3,hostedPath:'/checkout/flow/'+other}}];
it('refreshes saved names and canonical links explicitly, then checks selected receipts without any publication writer',async()=>{
 let n=0;const {client,calls}=await fixture(async()=>++n===1?json({ok:true,data:{publications:savedForms}}):json({ok:true,data:savedForms[n-2]!.publication}));render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);expect(calls).toHaveBeenCalledTimes(2);fireEvent.click(screen.getByRole('button',{name:'Refresh saved forms'}));await screen.findByText('Saved housekeeping');expect(calls).toHaveBeenCalledTimes(3);expect(screen.getByRole('link',{name:'Open saved form: Saved housekeeping'})).toHaveAttribute('href',STAGING_CHECKOUT_ORIGIN+receipt.hostedPath);expect(screen.getByText('Current version at last refresh: '+receipt.versionId)).toBeTruthy();expect(screen.queryByText('Staging form published')).toBeNull();expect(client.paidSimplePublicationState(tenant)).toEqual({phase:'ready'});fireEvent.click(screen.getByRole('button',{name:'Check receipt for Saved housekeeping'}));await screen.findByText('Staging form published');expect(screen.getByLabelText('Publication attempt ID')).toHaveValue(other);fireEvent.click(screen.getByRole('button',{name:'Check receipt for Another saved form'}));await waitFor(()=>expect(screen.getByLabelText('Publication attempt ID')).toHaveValue(serviceId));expect(screen.getByRole('link',{name:'Open staging booking form'})).toHaveAttribute('href',STAGING_CHECKOUT_ORIGIN+savedForms[1]!.publication.hostedPath);expect(calls.mock.calls.slice(2).every(([,options])=>options?.method==='GET'&&!options?.body)).toBe(true);expect(calls.mock.calls[2]?.[0]).toBe('https://api.example.test/api/paid-simple-flows?tenantId='+tenant);expect(calls.mock.calls[3]?.[0]).toContain('/'+other+'/publication?tenantId='+tenant);expect(calls.mock.calls[4]?.[0]).toContain('/'+serviceId+'/publication?tenantId='+tenant);expect(document.body.textContent).not.toContain('synthetic-owner-private-token');expect(screen.queryByText('Publish staging test form')).toBeNull();
});
it.each(['empty','unavailable'])('retains an unknown attempt after an explicit %s saved list response',async(kind)=>{
 let n=0;const {client,calls}=await fixture(async()=>++n===1?Promise.reject(Error('private-secret')):kind==='empty'?json({ok:true,data:{publications:[]}}):json({ok:false,code:'NOT_AVAILABLE'},404));render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fill();fireEvent.click(screen.getByText('Publish staging test form'));await screen.findByText(/Publishing again is locked/);const original=client.paidSimplePublicationState(tenant);fireEvent.click(screen.getByRole('button',{name:'Refresh saved forms'}));await screen.findByText(kind==='empty'?/No current saved forms were returned/:/saved form list could not be verified/);expect(client.paidSimplePublicationState(tenant)).toEqual(original);expect(screen.queryByText('Publish staging test form')).toBeNull();expect(calls).toHaveBeenCalledTimes(4);expect(calls.mock.calls[3]?.[1]?.method).toBe('GET');expect(document.body.textContent).not.toContain('private-secret');
});
it('permits only the matching unknown attempt from a saved list and never switches its identity',async()=>{
 let n=0;const {client,calls}=await fixture(async()=>{if(++n===1)throw Error('ambiguous');const state=client.paidSimplePublicationState(tenant);if(n===2&&state.phase==='unknown')return json({ok:true,data:{publications:[{flowId:state.flowId,name:'Matching attempt',publication:receipt},savedForms[0]!].sort((a,b)=>a.flowId<b.flowId?-1:1)}});return json({ok:true,data:receipt});});render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fill();fireEvent.click(screen.getByText('Publish staging test form'));await screen.findByText(/Publishing again is locked/);const original=client.paidSimplePublicationState(tenant);fireEvent.click(screen.getByRole('button',{name:'Refresh saved forms'}));await screen.findByText('Matching attempt');expect(screen.getByRole('button',{name:'Check receipt for Saved housekeeping'})).toBeDisabled();expect(screen.getByRole('button',{name:'Check receipt for Matching attempt'})).toBeEnabled();expect(client.paidSimplePublicationState(tenant)).toEqual(original);fireEvent.click(screen.getByRole('button',{name:'Check receipt for Matching attempt'}));await screen.findByText('Staging form published');if(original.phase==='unknown')expect(calls.mock.calls[4]?.[0]).toContain('/'+original.flowId+'/publication?');expect(calls.mock.calls[4]?.[1]?.method).toBe('GET');
});
it('keeps saved form selection disabled while publication is in flight',async()=>{
 let resolve!:(response:Response)=>void,n=0;const {client,calls}=await fixture(async()=>++n===1?new Promise<Response>(r=>resolve=r):json({ok:true,data:{publications:savedForms}}));render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fill();fireEvent.click(screen.getByText('Publish staging test form'));await screen.findByText('Publishing the staging form...');fireEvent.click(screen.getByRole('button',{name:'Refresh saved forms'}));await screen.findByText('Saved housekeeping');expect(screen.getByRole('button',{name:'Check receipt for Saved housekeeping'})).toBeDisabled();expect(client.paidSimplePublicationState(tenant).phase).toBe('publishing');expect(calls).toHaveBeenCalledTimes(4);resolve(json({ok:true,data:receipt}));await screen.findByText('Staging form published');
});
it('clears saved forms on tenant change and drops an old late list without disturbing a newer refresh',async()=>{
 let resolveOld!:(response:Response)=>void,resolveNew!:(response:Response)=>void,n=0;const {client,calls}=await fixture(async()=>++n===1?new Promise<Response>(r=>resolveOld=r):new Promise<Response>(r=>resolveNew=r));const {rerender}=render(<PaidSimplePublisher client={client} tenantId={tenant} role="BUSINESS_OWNER" services={[service]} staging/>);fireEvent.click(screen.getByRole('button',{name:'Refresh saved forms'}));await waitFor(()=>expect(resolveOld).toBeTypeOf('function'));rerender(<PaidSimplePublisher client={client} tenantId={other} role="BUSINESS_OWNER" services={[{...service,tenant_id:other}]} staging/>);fireEvent.click(screen.getByRole('button',{name:'Refresh saved forms'}));await waitFor(()=>expect(resolveNew).toBeTypeOf('function'));resolveOld(json({ok:true,data:{publications:savedForms}}));await waitFor(()=>expect(calls).toHaveBeenCalledTimes(4));expect(screen.queryByText('Saved housekeeping')).toBeNull();expect(screen.getByRole('button',{name:'Refreshing saved forms...'})).toBeDisabled();resolveNew(json({ok:true,data:{publications:[{...savedForms[0],name:'New business form'}]}}));await screen.findByText('New business form');expect(screen.queryByText('Saved housekeeping')).toBeNull();expect(calls.mock.calls[3]?.[0]).toBe('https://api.example.test/api/paid-simple-flows?tenantId='+other);
});
