import {readFileSync} from 'node:fs';
import {runInNewContext} from 'node:vm';
import {afterEach,expect,it} from 'vitest';
const html=readFileSync('public/staging-install-check.html','utf8');
const boot=readFileSync('public/staging-install-check.js','utf8');
const portal='https://booking-lumin-portal-staging.netlify.app';
const preview='https://deploy-preview-97--booking-lumin-portal-staging.netlify.app';
const checkout='https://booking-lumin-checkout-staging.netlify.app';
function run(origin=portal,search='',hash=''){runInNewContext(boot,{document,location:{origin,search,hash}});}
function prepare(){document.body.innerHTML=new DOMParser().parseFromString(html,'text/html').body.innerHTML;}
afterEach(()=>document.body.replaceChildren());
it.each([portal,preview])('loads only the two fixed cross-origin controllers from approved origin %s',origin=>{
 prepare();expect(document.querySelector('h1')?.textContent).toContain('Internal staging cross-origin');expect(document.body.textContent).toContain('Payments are simulated');expect(document.body.textContent).toContain('does not publish a form');expect(document.querySelectorAll('script,iframe')).toHaveLength(0);
 run(origin);const scripts=Array.from(document.querySelectorAll('script'));expect(scripts).toHaveLength(2);
 for(const [index,script] of scripts.entries()){const url=new URL(script.src);expect(url.href).toBe(checkout+'/booking-lumin-staging.js');expect(url.origin).not.toBe(portal);expect(url.search).toBe('');expect(url.hash).toBe('');expect(script.getAttribute('data-installation')).toBe('0fe09ceb-7660-444d-bb6a-161eb4baa665');expect(script.getAttribute('data-mode')).toBe(index===0?'inline':'launcher');expect(script.referrerPolicy).toBe('no-referrer');expect(script.textContent).toBe('');}
 expect(document.querySelector('iframe')).toBeNull();expect(document.querySelector('[role="status"]')?.textContent).toContain('unverified');expect(document.body.textContent).toContain('Escape');expect(document.querySelectorAll('section[aria-labelledby]')).toHaveLength(2);run(origin);expect(document.querySelectorAll('script')).toHaveLength(2);
});
it.each(['https://merchant.example','http://booking-lumin-portal-staging.netlify.app','https://booking-lumin-portal-staging.netlify.app.evil.test','https://booking-lumin-checkout-staging.netlify.app','null','https://booking-lumin-portal-staging.netlify.app:444','https://deploy-preview-97--booking-lumin-portal-staging.netlify.app.evil.test','https://deploy-preview-98--booking-lumin-portal-staging.netlify.app','https://deploy-preview-97--booking-lumin-checkout-staging.netlify.app','http://deploy-preview-97--booking-lumin-portal-staging.netlify.app','https://deploy-preview-97--booking-lumin-portal-staging.netlify.app:444'])('rejects origin %s before loading any controller',origin=>{prepare();run(origin);expect(document.querySelectorAll('script,iframe,a')).toHaveLength(0);expect(document.querySelector('[role="status"]')?.textContent).toContain('Fixture unavailable');});
it('keeps load and error events honest without treating script delivery as browser acceptance',()=>{prepare();run();const scripts=document.querySelectorAll('script');scripts[0]!.dispatchEvent(new Event('load'));scripts[1]!.dispatchEvent(new Event('load'));expect(document.querySelector('[role="status"]')?.textContent).toContain('checks are still required');scripts[0]!.dispatchEvent(new Event('error'));scripts[1]!.dispatchEvent(new Event('load'));expect(document.querySelector('[role="status"]')?.textContent).toContain('remain unverified');});
it('has only a fixed local deferred boot and no form, credentials, dynamic URL inputs or automatic booking actions',()=>{const page=new DOMParser().parseFromString(html,'text/html');const script=page.querySelector('script')!;expect(script.getAttribute('src')).toBe('/staging-install-check.js');expect(script.hasAttribute('defer')).toBe(true);expect(page.querySelectorAll('script')).toHaveLength(1);expect(page.querySelectorAll('form,input,textarea,iframe')).toHaveLength(0);expect(boot).not.toMatch(/fetch\(|XMLHttpRequest|localStorage|sessionStorage|innerHTML|eval\(/);});

it.each([['?installation=foreign','','installation'],['?src=https://evil.test/controller.js','','URL'],['?access_token=PRIVATE_TOKEN','','auth'],['','#sessionToken=PRIVATE_TOKEN','fragment']])('rejects %s %s %s override inputs before any controller loads',(search,hash)=>{for(const origin of [portal,preview]){prepare();run(origin,search,hash);expect(document.querySelectorAll('script,iframe,a')).toHaveLength(0);expect(document.querySelector('[role="status"]')?.textContent).toContain('Fixture unavailable');expect(document.body.textContent).not.toContain('PRIVATE_TOKEN');}});
it('duplicate load events cannot claim both controllers loaded and any error stays unverified',()=>{prepare();run(preview);const scripts=document.querySelectorAll('script');scripts[0]!.dispatchEvent(new Event('load'));scripts[0]!.dispatchEvent(new Event('load'));expect(document.querySelector('[role="status"]')?.textContent).toContain('remain unverified');scripts[1]!.dispatchEvent(new Event('load'));expect(document.querySelector('[role="status"]')?.textContent).toContain('checks are still required');scripts[1]!.dispatchEvent(new Event('error'));scripts[0]!.dispatchEvent(new Event('load'));scripts[1]!.dispatchEvent(new Event('load'));expect(document.querySelector('[role="status"]')?.textContent).toContain('remain unverified');expect(document.querySelector('[role="status"]')?.textContent).not.toMatch(/healthy|passed|certified/i);});
it('pins only the restored public installation and never uses private/browser-controlled configuration',()=>{expect(boot).toContain('0fe09ceb-7660-444d-bb6a-161eb4baa665');expect(boot).not.toContain('66000000-0000-4000-8000-000000000006');expect(boot).not.toMatch(/URLSearchParams|document\.cookie|Authorization|Bearer|access_token|sessionToken|supabase|data-api|data-origin|\/hold|\/request|\/confirm|\/mock-payment|postMessage/i);prepare();document.getElementById('inline-install')!.setAttribute('data-installation','PRIVATE_TOKEN');document.getElementById('launcher-install')!.setAttribute('data-script-url','https://evil.test/private.js');run(preview);for(const script of document.querySelectorAll('script')){expect(script.src).toBe(checkout+'/booking-lumin-staging.js');expect(script.getAttribute('data-installation')).toBe('0fe09ceb-7660-444d-bb6a-161eb4baa665');}});
