import {afterEach,describe,expect,it,vi} from "vitest";
import {BusinessType} from "@lumin/contracts";
import {createPricingEngine} from "@lumin/core";
import {getBusinessTemplateDefaults} from "../src/business-defaults";
import {getTemplate} from "../src/registry";
import {templateCases} from "./fixtures";
const tenantId="45000000-0000-4000-8000-000000000002",profile=(businessType:unknown)=>({schemaVersion:1,tenantId,businessType,templateVersion:1});
const expected={HOUSEKEEPING:["housekeeping","configurable","Jobs","Services","crew","pooled"],AUTO_DETAILING:["car-detailing","configurable","Appointments","Detailing services","technician","pooled"],VEHICLE_RENTAL:["vehicle-rental","rental","Reservations","Vehicles","vehicle","exclusive"],EQUIPMENT_RENTAL:["equipment-rental","rental","Reservations","Equipment","equipment","exclusive"],EVENT_RENTAL:["tent-event-rental","cart","Reservations","Event items","equipment","pooled"],JUNK_REMOVAL:["junk-removal","cart","Pickups","Removal items","crew","pooled"]} as const;
afterEach(()=>vi.restoreAllMocks());
describe("authoritative six-type structural mapping",()=>{
 it.each(BusinessType.options)("%s resolves the correct existing template, labels and generic resource model",businessType=>{const d=getBusinessTemplateDefaults(profile(businessType)),e=expected[businessType];expect([d.serviceTemplateKey,d.archetype,d.primaryNavigation[1]!.label,d.catalog.plural,d.resourceModel.kind,d.resourceModel.mode]).toEqual(e);expect(d.businessType).toBe(businessType);expect(d.templateVersion).toBe(1);expect(d.primaryNavigation.map(n=>n.id)).toEqual(["overview","bookings","catalog","resources","design"]);expect(d.booking.steps.map(s=>s.id)).toEqual(["service","options","schedule","customer","review"]);expect(new Set(d.booking.steps.flatMap(s=>s.fieldIds)).size).toBe(d.booking.steps.flatMap(s=>s.fieldIds).length);});
 it.each(["pressure-washing","landscaping","housekeeping","simple","__proto__",null])( "rejects unsupported/inferred business type %s",businessType=>{expect(()=>getBusinessTemplateDefaults(profile(businessType))).toThrow();});
 it.each([{templateVersion:2},{schemaVersion:2},{tenantId:"bad"},{theme:"HOUSEKEEPING"},{archetype:"rental"},{price:12500}])("rejects widened profile %j",extra=>{expect(()=>getBusinessTemplateDefaults({...profile("HOUSEKEEPING"),...extra})).toThrow();});
 it("keeps vertical fields from leaking into unrelated templates",()=>{const h=getBusinessTemplateDefaults(profile("HOUSEKEEPING")),a=getBusinessTemplateDefaults(profile("AUTO_DETAILING"));expect(h.booking.steps[1]!.fieldIds).toEqual(["answers.bedrooms","answers.bathrooms","answers.depth","answers.frequency","addonIds"]);expect(a.booking.steps[1]!.fieldIds).toEqual(["answers.package","answers.vehicle","addonIds"]);for(const type of ["VEHICLE_RENTAL","EQUIPMENT_RENTAL"]){expect(getBusinessTemplateDefaults(profile(type)).booking.steps[1]!.fieldIds).toEqual(["rentalPeriods"]);}for(const type of ["EVENT_RENTAL","JUNK_REMOVAL"]){expect(getBusinessTemplateDefaults(profile(type)).booking.steps[1]!.fieldIds).toEqual(["itemQuantities","addonIds"]);}});
});
it("references actual existing service question IDs and selection primitives",()=>{for(const businessType of BusinessType.options){const d=getBusinessTemplateDefaults(profile(businessType)),service=getTemplate(d.serviceTemplateKey).build({tenantId,currency:"USD",timezone:"UTC"});for(const field of d.booking.steps[1]!.fieldIds){if(field.startsWith("answers."))expect(service.questions.map(q=>q.id)).toContain(field.slice(8));else if(field==="rentalPeriods")expect(service.rental).toBeDefined();else if(field==="itemQuantities")expect(service.items.length).toBeGreaterThan(0);else if(field==="addonIds")expect(service.addons.length).toBeGreaterThan(0);else throw Error("unknown field");}}});
it("does not invoke priced builders or return financial/permission authority",()=>{const builders=BusinessType.options.map(type=>vi.spyOn(getTemplate(expected[type][0]),"build"));for(const type of BusinessType.options){const d=getBusinessTemplateDefaults(profile(type));expect(JSON.parse(JSON.stringify(d))).toEqual(d);const keys=(value:unknown):string[]=>value&&typeof value==="object"?Object.entries(value).flatMap(([key,child])=>[key,...keys(child)]):[];expect(keys(d).filter(key=>/price|amount|tax|deposit|payment|currency|permission|role|capacity|tenantId|provider/i.test(key))).toEqual([]);}for(const builder of builders)expect(builder).not.toHaveBeenCalled();});
it("visual themes cannot mutate or select the locked structural type",()=>{const structure=getBusinessTemplateDefaults(profile("HOUSEKEEPING"));for(const appearance of [{accentColor:"#4f46e5",layout:"compact"},{accentColor:"#0e7490",layout:"stacked"},{theme:"rental"}]){const design={structure,appearance};expect(design.structure).toEqual(getBusinessTemplateDefaults(profile("HOUSEKEEPING")));expect(design.structure.businessType).toBe("HOUSEKEEPING");}expect(()=>{(structure.resourceModel as {kind:string}).kind="vehicle";}).toThrow();expect(()=>{(structure.booking.steps[1]!.fieldIds as string[]).push("rentalPeriods");}).toThrow();expect(getBusinessTemplateDefaults(profile("HOUSEKEEPING")).resourceModel.kind).toBe("crew");});
it("all six registry templates still use one shared pricing engine with existing authoritative fixtures",()=>{const engine=createPricingEngine(),fixtures=templateCases();for(const type of BusinessType.options){const d=getBusinessTemplateDefaults(profile(type)),fixture=fixtures.find(f=>f.key===d.serviceTemplateKey)!;expect(engine.price(fixture.service,fixture.selection).total.amount).toBe(fixture.total);}});
