import {expect,it} from 'vitest';
import {parseFieldDocumentV2} from '../src/fieldDocumentV2';
import {parseTextFieldDocument} from '../src/fieldAnswers';
const field=(extra={})=>({key:'notes',kind:'text',required:false,minLength:0,maxLength:4096,...extra});
const doc=(fields:unknown[])=>({schemaVersion:2,fields});
it('copies mixed definitions and preserves prompt omission/exact text',()=>{const f=field({prompt:'  Label  '});const out=parseFieldDocumentV2(doc([f,field({key:'details',kind:'textarea'})]));expect(out.fields[0]?.prompt).toBe('  Label  ');expect(out.fields[1]).not.toHaveProperty('prompt');f.key='changed';expect(out.fields[0]?.key).toBe('notes');expect(Object.isFrozen(out.fields[0])).toBe(true);expect(Object.isFrozen(out.fields)).toBe(true);expect(Object.isFrozen(out)).toBe(true);});
it('rejects cross versions, unsupported kinds, bounds and duplicates',()=>{for(const value of [{schemaVersion:1,fields:[]},doc([field({kind:'email'})]),doc([field({required:true,maxLength:0})]),doc([field(),field()]),doc([field({minLength:2,maxLength:1})]),doc(Array.from({length:65},(_,i)=>field({key:'a'+i})))])expect(()=>parseFieldDocumentV2(value)).toThrow('INVALID_FIELD_V2_CONTRACT');expect(()=>parseTextFieldDocument(doc([field()]))).toThrow();});
it('rejects descriptor attacks without getters and enforces exact prompt semantics',()=>{let calls=0;const hostile=Object.defineProperty(field(),'prompt',{enumerable:true,get(){calls++;return 'x';}});expect(()=>parseFieldDocumentV2(doc([hostile]))).toThrow();expect(calls).toBe(0);for(const prompt of [undefined,null,'','\u00a0','\ufeff','x\ny','\0','\ud800','a'.repeat(201)])expect(()=>parseFieldDocumentV2(doc([field({prompt})]))).toThrow();for(const prompt of ['\u0085','\u200b','\u{1f600}'.repeat(200)])expect(parseFieldDocumentV2(doc([field({prompt})])).fields[0]?.prompt).toBe(prompt);});
it('rejects unsafe shapes while permitting plain null prototypes',()=>{for(const value of [Object.create({schemaVersion:2,fields:[]}),{schemaVersion:2,fields:[],extra:1},doc(new Array(1)),doc([field({key:'constructor'})])])expect(()=>parseFieldDocumentV2(value)).toThrow();expect(parseFieldDocumentV2(Object.assign(Object.create(null),doc([]))).fields).toEqual([]);});
