import {describe,expect,it} from 'vitest';
import {PaidSimpleRender,isPaidSimpleRender,PaidSimplePublication} from '../src/paidPublication';
const render={versionId:'40000000-0000-4000-8000-000000000001',renderSchemaVersion:3,submissionMode:'paid_service_request',paymentMode:'staging_mock',simulated:true,service:{id:'40000000-0000-4000-8000-000000000002',name:'Catalog housekeeping',durationMinutes:60,price:{amount:12500,currency:'USD'}}};
const publication={name:'Published housekeeping',draftRevision:1,presentation:{accentColor:'#0e7490',layout:'compact'}};
describe('paid V3 saved publication snapshot contract',()=>{
 it('preserves legacy V3 and accepts explicit saved design metadata without changing service authority',()=>{expect(PaidSimpleRender.parse(render)).toEqual(render);const saved={...render,publication};expect(PaidSimpleRender.parse(saved)).toEqual(saved);expect(isPaidSimpleRender(saved)).toBe(true);expect(PaidSimpleRender.parse(saved).service).toEqual(render.service);});
 it.each([{...publication,price:1},{...publication,draftRevision:0},{...publication,draftRevision:0.5},{...publication,draftRevision:Number.MAX_SAFE_INTEGER+1},{...publication,name:''},{...publication,name:'x'.repeat(201)},{...publication,presentation:{accentColor:'#ffffff',layout:'compact'}},{...publication,presentation:{accentColor:'#0e7490',layout:'grid'}},{...publication,presentation:{...publication.presentation,provider:'stripe'}},{name:'Partial',draftRevision:1}])('rejects malformed/widened snapshot metadata %j',value=>{expect(PaidSimplePublication.safeParse(value).success).toBe(false);expect(isPaidSimpleRender({...render,publication:value})).toBe(false);});
 it('rejects accidental top-level design fields and keeps test mode strict',()=>{expect(isPaidSimpleRender({...render,name:'Unbound name'})).toBe(false);expect(isPaidSimpleRender({...render,publication,paymentMode:'stripe'})).toBe(false);expect(isPaidSimpleRender({...render,publication,simulated:false})).toBe(false);});
});
